In [1]:
import random, os
import numpy as np
import torch
os.environ["CUDA_VISIBLE_DEVICES"]="0,2"

from transformers import AutoTokenizer, BitsAndBytesConfig, AutoModelForCausalLM, AutoModel
from datasets import load_dataset
import pandas as pd
import re

device1 = 'cuda:0'
device2 = 'cuda:1'
data_dir = '/raid/deallab/SF_RAG_Data/ASQA'
# data_dir = '../data'

/home/dataconv/anaconda3/envs/sf_rag_djk/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
def set_seed(seed_value):
    # Set seed for reproducibility.
    random.seed(seed_value)
    os.environ['PYTHONHASHSEED']=str(seed_value)
    np.random.seed(seed_value)
    torch.manual_seed(seed_value)
    torch.cuda.manual_seed(seed_value)
    torch.backends.cudnn.deterministic=True    
    torch.backends.cudnn.benchmark=True
    torch.cuda.manual_seed_all(seed_value)

In [3]:
#load embeddings
embedd_test_path = f'{data_dir}/test/embedd_test.npy'
evidence_embeddings = np.load(embedd_test_path)
print(evidence_embeddings.shape)
evidence_embeddings = torch.from_numpy(evidence_embeddings).to(device1)

#load embeddings (evidence_eval)
embedd_test_path = f'{data_dir}/test/embedd_test_eval2.npy'
evidence_embeddings_eval = np.load(embedd_test_path)
print(evidence_embeddings_eval.shape)
evidence_embeddings_eval = torch.from_numpy(evidence_embeddings_eval).to(device1)

#load embeddings (evidence_title)
embedd_test_path = f'{data_dir}/test/embedd_test_eval_title.npy'
evidence_embeddings_title = np.load(embedd_test_path)
print(evidence_embeddings_title.shape)
evidence_embeddings_title = torch.from_numpy(evidence_embeddings_title).to(device1)

#load evidence
evidence_test_path = f'{data_dir}/test/evidence_test.csv'
evidence_df = pd.read_csv(evidence_test_path)
print(len(evidence_df))

#load evidence
evidence_test_path = f'{data_dir}/test/evidence_test_eval.csv'
evidence_eval_df = pd.read_csv(evidence_test_path)
print(len(evidence_eval_df))

#load title evidence
evidence_test_path = f'{data_dir}/test/evidence_test_eval_title.csv'
evidence_eval_title_df = pd.read_csv(evidence_test_path)
print(len(evidence_eval_title_df))

#load qa data
qa_df=pd.read_csv(f'{data_dir}/test/qa_test.csv') #data=df[['question','long_answers']] # questions=data['question'] #references = [row.to_dict() for i, row in df.iterrows() if i < len(questions)]
qa_df.head()

(21586, 4096)
(21801, 4096)
(1897, 4096)
21586
21801
1897

,id,sample_id,question,follow_up_questions,long_answers,short_answers
0,aee000f3-d2b0-4de5-8206-a96e9c203207,-7013890438520559398,Who has the highest goals in world football?,"[""Who has the highest goals in men's world int...","[""Ali Dael has the highest goals in men's worl...","[['Daei', 'Ali Daei'], ['Bican', 'Josef Bican'..."
1,b80ea7a2-5084-422f-94d1-e67e7e29819b,7089015503030534342,Who is the original artist of sound of silence?,['Who is the original artist of sound of silen...,[' The original artist of the song sound of si...,"[['Simon & Garfunkel', 'Paul Simon and Art Gar..."
2,a9c1319b-ed69-4b1b-8486-05ad3d444e22,8793099883447006698,When was the first apple i phone made?,"['When was the first apple i phone released?',...",['The iPhone beta was created in 2004 to test ...,"[['June 29, 2007'], ['2004'], ['June 29, 2007...."
3,b07f0006-0628-49cf-b5b4-c0c7e88d3190,-881464876144297194,Who played the weasley brothers in harry potter?,['Who played Bill weasley in Harry Potter and...,['Rupert Grint played Ron Weasley in all the H...,"[['Richard Fish'], ['Chris Rankin'], ['James P..."
4,a9d31e99-6402-4a41-a4af-52de1aebeb16,1650309494326541834,How many state parks are there in virginia?,['How many state parks are there in virginia i...,['When the Virginia state park system was form...,"[['six'], ['38'], ['6'], ['38']]"

In [4]:
#load quantized model
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_storage=torch.bfloat16,
)

# load model with tokenizer
model = AutoModel.from_pretrained(
    'nvidia/NV-Embed-v2', 
    trust_remote_code=True,
    quantization_config = bnb_config,
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage =True,
)
model.eval()

Loading checkpoint shards: 100%|██████████| 4/4 [00:04<00:00,  1.22s/it]

NVEmbedModel(
  (latent_attention_model): LatentAttentionModel(
    (cross_attend_blocks): ModuleList(
      (0): PreNorm(
        (fn): Attention(
          (to_q): Linear4bit(in_features=4096, out_features=32768, bias=False)
          (to_kv): Linear4bit(in_features=4096, out_features=65536, bias=False)
          (to_out): Linear4bit(in_features=32768, out_features=4096, bias=False)
        )
        (norm): LayerNorm((4096,), eps=1e-05, elementwise_affine=True)
        (norm_context): LayerNorm((4096,), eps=1e-05, elementwise_affine=True)
      )
      (1): PreNorm(
        (fn): FeedForward(
          (net): Sequential(
            (0): Linear4bit(in_features=4096, out_features=32768, bias=True)
            (1): GEGLU()
            (2): Linear4bit(in_features=16384, out_features=4096, bias=True)
          )
        )
        (norm): LayerNorm((4096,), eps=1e-05, elementwise_affine=True)
      )
    )
  )
  (embedding_model): BidirectionalMistralModel(
    (embed_tokens): Embedding(32000, 4096)
    (layers): ModuleList(
      (0-31): 32 x MistralDecoderLayer(
        (self_attn): MistralSdpaAttention(
          (q_proj): Linear4bit(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear4bit(in_features=4096, out_features=1024, bias=False)
          (v_proj): Linear4bit(in_features=4096, out_features=1024, bias=False)
          (o_proj): Linear4bit(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): MistralRotaryEmbedding()
        )
        (mlp): MistralMLP(
          (gate_proj): Linear4bit(in_features=4096, out_features=14336, bias=False)
          (up_proj): Linear4bit(in_features=4096, out_features=14336, bias=False)
          (down_proj): Linear4bit(in_features=14336, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): MistralRMSNorm()
        (post_attention_layernorm): MistralRMSNorm()
      )
    )
    (norm): MistralRMSNorm()
  )
)

In [5]:
#load tokenizer
tokenizer_gen = AutoTokenizer.from_pretrained("meta-llama/Meta-Llama-3.1-8B-Instruct")
# cache_dir= '/raid/deallab/.cache')
tokenizer_gen.pad_token = tokenizer_gen.eos_token

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    # bnb_4bit_quant_type="nf4",
    # bnb_4bit_compute_dtype=torch.bfloat16,
    # bnb_4bit_use_double_quant=True,
    # bnb_4bit_quant_storage=torch.bfloat16,
)

model_gen = AutoModelForCausalLM.from_pretrained(
    "meta-llama/Meta-Llama-3.1-8B-Instruct",
    quantization_config=bnb_config,
    torch_dtype=torch.bfloat16,
    device_map= 'auto',
    # cache_dir= '/raid/deallab/.cache'
)
model_gen.eval()

Loading checkpoint shards: 100%|██████████| 4/4 [00:03<00:00,  1.28it/s]

LlamaForCausalLM(
  (model): LlamaModel(
    (embed_tokens): Embedding(128256, 4096)
    (layers): ModuleList(
      (0-31): 32 x LlamaDecoderLayer(
        (self_attn): LlamaSdpaAttention(
          (q_proj): Linear4bit(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear4bit(in_features=4096, out_features=1024, bias=False)
          (v_proj): Linear4bit(in_features=4096, out_features=1024, bias=False)
          (o_proj): Linear4bit(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear4bit(in_features=4096, out_features=14336, bias=False)
          (up_proj): Linear4bit(in_features=4096, out_features=14336, bias=False)
          (down_proj): Linear4bit(in_features=14336, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm()
        (post_attention_layernorm): LlamaRMSNorm()
      )
    )
    (norm): LlamaRMSNorm()
    (rotary_emb): LlamaRotaryEmbedding()
  )
  (lm_head): Linear(in_features=4096, out_features=128256, bias=False)
)

In [6]:
# from langchain_text_splitters import TokenTextSplitter

# text_splitter = TokenTextSplitter(
#     chunk_size=500,  # 청크 크기를 10으로 설정합니다.
#     chunk_overlap=50,  # 청크 간 중복을 0으로 설정합니다.
# )
# # combined_text = " ".join(evidence_text_list)
# # texts = text_splitter.split_text(combined_text)
# split_texts = [text_splitter.split_text(text)[0] for text in evidence_text_list]
# print(split_texts[0])

In [7]:
# from langchain.retrievers import BM25Retriever, EnsembleRetriever
# from langchain.vectorstores import FAISS

# # bm25 retriever와 faiss retriever를 초기화합니다.
# bm25_retriever = BM25Retriever.from_texts(
#     evidence_text_list,
# )
# bm25_retriever.k = 10  # BM25Retriever의 검색 결과 개수를 1로 설정합니다.

# embedding = model
# faiss_vectorstore = FAISS.from_texts(
#     evidence_text,
#     embedding,
# )
# faiss_retriever = faiss_vectorstore.as_retriever(search_kwargs={"k": 2})

# # 앙상블 retriever를 초기화합니다.
# ensemble_retriever = EnsembleRetriever(
#     retrievers=[bm25_retriever, faiss_retriever],
#     weights=[0.7, 0.3],
# )

In [8]:
# from langchain_community.document_transformers import LongContextReorder

# def bm25_retrieve(query):
#     bm25_result = bm25_retriever.invoke(query)
#     bm25_docs=list()

#     print("[BM25 Retriever]")
#     for doc in bm25_result:
#         # print(f"Content: {doc.page_content}")
#         # print()
#         bm25_docs.append(doc.page_content)
#     reordering = LongContextReorder()
#     bm25_docs = reordering.transform_documents(bm25_docs)
#     return bm25_docs

In [9]:
# res=bm25_retrieve("Who has the highest goals in world football?")
# res

In [10]:
evidence_eval_path = f'{data_dir}/test/evidence_test_eval.csv'
eval_df = pd.read_csv(evidence_eval_path)
eval_df.head(20)

,sample_id,title,text
0,-7013890438520559398,International Federation of Football History &...,Document: International Federation of Football...
1,-7013890438520559398,International Federation of Football History &...,Document: International Federation of Football...
2,-7013890438520559398,International Federation of Football History &...,Document: International Federation of Football...
3,-7013890438520559398,International Federation of Football History &...,Document: International Federation of Football...
4,-7013890438520559398,International Federation of Football History &...,Document: International Federation of Football...
5,-7013890438520559398,International Federation of Football History &...,Document: International Federation of Football...
6,-7013890438520559398,International Federation of Football History &...,Document: International Federation of Football...
7,-7013890438520559398,International Federation of Football History &...,Document: International Federation of Football...
8,-7013890438520559398,International Federation of Football History &...,Document: International Federation of Football...
9,-7013890438520559398,International Federation of Football History &...,Document: International Federation of Football...
10,-7013890438520559398,List of FIFA World Cup records and statistics,Document: List of FIFA World Cup records and s...
11,-7013890438520559398,List of FIFA World Cup records and statistics,Document: List of FIFA World Cup records and s...
12,-7013890438520559398,List of FIFA World Cup records and statistics,Document: List of FIFA World Cup records and s...
13,-7013890438520559398,List of FIFA World Cup records and statistics,Document: List of FIFA World Cup records and s...
14,-7013890438520559398,List of FIFA World Cup records and statistics,Document: List of FIFA World Cup records and s...
15,-7013890438520559398,List of FIFA World Cup records and statistics,Document: List of FIFA World Cup records and s...
16,-7013890438520559398,List of FIFA World Cup records and statistics,Document: List of FIFA World Cup records and s...
17,-7013890438520559398,List of FIFA World Cup records and statistics,Document: List of FIFA World Cup records and s...
18,-7013890438520559398,List of FIFA World Cup records and statistics,Document: List of FIFA World Cup records and s...
19,-7013890438520559398,List of FIFA World Cup records and statistics,Document: List of FIFA World Cup records and s...

In [11]:
def match_sample_id(query_id, doc_id):
    query_sample_id=qa_df.loc[query_id,'sample_id']
    doc_sample_id=eval_df.loc[doc_id,'sample_id']
    if query_sample_id==doc_sample_id:
        return 1
    else:
        return 0

In [12]:
def match_sample_id2(query_id, title):
    query_sample_id=qa_df.loc[query_id,'sample_id']
    doc_sample_id=evidence_eval_title_df.loc[evidence_eval_title_df['title']==title,'sample_id'].item()
    if query_sample_id==doc_sample_id:
        return 1
    else:
        return 0

In [13]:
# retrive docs from the document embeddings
def retrieve_documents(query,num=10):
    max_length = 1024
    
    #query prefix
    task_name_to_instruct = {"example": "Given a question, retrieve passages that answer the question",}
    query_prefix = "Instruct: "+task_name_to_instruct["example"]+"\nQuery: "
    
    query_embedding = model.encode([query],instruction=query_prefix, max_length=max_length).to(device1)
    similarities = torch.nn.functional.cosine_similarity(query_embedding, evidence_embeddings)

    top_results = similarities.argsort(descending=True)[:num].cpu().detach().numpy()
    res=[evidence_df.loc[idx, 'text'] for idx in top_results if idx < len(evidence_df)]
    idx=[idx for idx in top_results if idx < len(evidence_df)]
    return res, idx

In [14]:
# retrive docs from the document embeddings
def retrieve_documents_eval(query,num=10):
    max_length = 1024
    
    #query prefix
    task_name_to_instruct = {"example": "Given a question, retrieve passages that answer the question",}
    query_prefix = "Instruct: "+task_name_to_instruct["example"]+"\nQuery: "
    
    query_embedding = model.encode([query],instruction=query_prefix, max_length=max_length).to(device1)
    similarities = torch.nn.functional.cosine_similarity(query_embedding, evidence_embeddings_eval)

    top_results = similarities.argsort(descending=True)[:num].cpu().detach().numpy()
    res=[evidence_eval_df.loc[idx, 'text'] for idx in top_results if idx < len(evidence_eval_df)]
    idx=[idx for idx in top_results if idx < len(evidence_eval_df)]
    return res, idx

In [15]:
# retrive docs from the document embeddings
def retrieve_documents2(query, embed, evidence, num=10):
    max_length = 1024
    
    #query prefix
    task_name_to_instruct = {"example": "Given a question, retrieve passages that answer the question",}
    query_prefix = "Instruct: "+task_name_to_instruct["example"]+"\nQuery: "
    
    query_embedding = model.encode([query],instruction=query_prefix, max_length=max_length).to(device1)
    similarities = torch.nn.functional.cosine_similarity(query_embedding, embed)

    top_results = similarities.argsort(descending=True)[:num].cpu().detach().numpy()
    res=[evidence.loc[idx, 'text'] for idx in top_results if idx < len(evidence)]
    titles=[evidence.loc[idx, 'title'] for idx in top_results if idx < len(evidence)]
    # idx=[idx for idx in top_results if idx < len(evidence)]
    return res, titles

In [16]:
# retrive docs from the document embeddings
def retrieve_documents3(query, embed, evidence, num=10):
    max_length = 1024
    
    #query prefix
    task_name_to_instruct = {"example": "Given a question, retrieve passages that answer the question",}
    query_prefix = "Instruct: "+task_name_to_instruct["example"]+"\nQuery: "
    
    query_embedding = model.encode([query],instruction=query_prefix, max_length=max_length).to(device1)
    similarities = torch.nn.functional.cosine_similarity(query_embedding, embed)

    top_results = similarities.argsort(descending=True)[:num].cpu().detach().numpy()
    res=[evidence.loc[idx, 'text'] for idx in top_results if idx < len(evidence)]
    # titles=[evidence.loc[idx, 'title'] for idx in top_results if idx < len(evidence)]
    idx=[idx for idx in top_results if idx < len(evidence)]
    return res, idx

In [17]:
# retrive docs from the document embeddings
def retrieve_titles(query,num=10):
    max_length = 1024
    
    #query prefix
    task_name_to_instruct = {"example": "Given a question, retrieve passages that answer the question",}
    query_prefix = "Instruct: "+task_name_to_instruct["example"]+"\nQuery: "
    
    query_embedding = model.encode([query],instruction=query_prefix, max_length=max_length).to(device1)
    similarities = torch.nn.functional.cosine_similarity(query_embedding, evidence_embeddings_title)

    top_results = similarities.argsort(descending=True)[:num].cpu().detach().numpy()
    res=[evidence_eval_title_df.loc[idx, 'title'] for idx in top_results if idx < len(evidence_eval_title_df)]
    idx=[idx for idx in top_results if idx < len(evidence_eval_title_df)]
    return res, idx

In [18]:
def find_titles(query):
    titles,title_ids=retrieve_titles(query, 10)
    return titles

In [19]:
def find_docs(titles):
    docs=[]
    for title in titles:
        # print(title)
        # print(evidence_eval_df.loc[evidence_eval_df['title']==title,'text'].to_list())
        docs.extend(evidence_eval_df.loc[evidence_eval_df['title']==title,'text'])
        # print()
    return docs

In [20]:
def retrieve_inside(query, titles, num=10):
    docs=[]
    text_docs=pd.DataFrame(columns=['text','title'])
    final_docs=[]
    for title in titles:
        text_docs=pd.concat([text_docs, evidence_eval_df.loc[evidence_eval_df['title']==title,['text','title']]],ignore_index=True)
        docs.extend(evidence_embeddings_eval[evidence_eval_df['title']==title])
        # print(title_retrieved_docs)
        # print()
    docs_tensor = torch.stack(docs)
    title_retrieved_docs,t=retrieve_documents2(query, docs_tensor, text_docs, num)
    final_docs.extend(title_retrieved_docs)
    return final_docs,t

In [21]:
# query="Who has the highet goals in world football?"
# titles,title_ids=retrieve_titles(query, 11)
# for t in titles:
#     print(t)
# title_docs=find_docs(titles)
# final_docs,d=retrieve_inside(query, titles, 10)
# d

In [37]:
def total_answer(query, docs):
    prompt = """
    Context information is below.
    ---------------------
    {0}
    ---------------------
    Given the context information and not prior knowledge, answer the query.
    1. The query is an ambiguous question.
    2. Therefore, you must include the contents according to the various interpretations of the query in one answer by utilizing the given context.
    3. Each content according to the various interpretations of the query must be explained in one or two sentences.
    4. The total answer must be 5 sentences or less.
    Do not comment your answer and strictly follow this instructions.
    Query: {1}
    Answer:
    """.format('\n'.join(docs), query)
    input_ids = tokenizer_gen.apply_chat_template([{"role":'user', "content":prompt}], return_tensors='pt').to(device1)

    attention_mask = (input_ids != tokenizer_gen.pad_token_id).long().to(device1)

    out = model_gen.generate(input_ids, attention_mask=attention_mask, pad_token_id=tokenizer_gen.pad_token_id, max_new_tokens = 512)
    res = tokenizer_gen.decode(out[0]).split('<|end_header_id|>')[-1] 
    return re.sub('\n|<\|eot_id\|>', '', res)

In [38]:
def answer(query, context):
    prompt = """
    Context information is below.
    ---------------------
    {0}
    ---------------------
    Given the context information and not prior knowledge, answer the query.
    Query: {1}
    Answer:
    """.format('\n'.join(context), query)
    input_ids = tokenizer_gen.apply_chat_template([{"role":'user', "content":prompt}], return_tensors='pt').to(device1)

    attention_mask = (input_ids != tokenizer_gen.pad_token_id).long().to(device1)

    out = model_gen.generate(input_ids, attention_mask=attention_mask, pad_token_id=tokenizer_gen.pad_token_id, max_new_tokens = 512)
    res = tokenizer_gen.decode(out[0]).split('<|end_header_id|>')[-1] 
    return re.sub('\n|<\|eot_id\|>', '', res)

In [39]:
def retrieve_inside(query, titles, num=10):
    docs=[]
    text_docs=pd.DataFrame(columns=['text','title'])
    final_docs=[]
    for title in titles:
        text_docs=pd.concat([text_docs, evidence_eval_df.loc[evidence_eval_df['title']==title,['text','title']]],ignore_index=True)
        docs.extend(evidence_embeddings_eval[evidence_eval_df['title']==title])
        # print(title_retrieved_docs)
        # print()
    docs_tensor = torch.stack(docs)
    title_retrieved_docs,t=retrieve_documents2(query, docs_tensor, text_docs, num)
    final_docs.extend(title_retrieved_docs)
    return final_docs,t

In [25]:
# import torch
# from transformers import AutoModelForSequenceClassification, AutoTokenizer

# tokenizer_rerank = AutoTokenizer.from_pretrained('BAAI/bge-reranker-v2-m3')
# model_rerank = AutoModelForSequenceClassification.from_pretrained('BAAI/bge-reranker-v2-m3')
# model_rerank.eval()

In [26]:
# pairs = [['what is panda?', 'hi'], ['what is panda?', 'The giant panda (Ailuropoda melanoleuca), sometimes called a panda bear or simply panda, is a bear species endemic to China.']]
# with torch.no_grad():
#     inputs = tokenizer_rerank(pairs, padding=True, truncation=True, return_tensors='pt', max_length=512)
#     scores = model(**inputs, return_dict=True).logits.view(-1, ).float()

# print(scores)

In [27]:
# from sentence_transformers import CrossEncoder

# v2m3_model = CrossEncoder("BAAI/bge-reranker-v2-m3", trust_remote_code=True)

# # Sample query and contexts
# query, contexts = ('Were Scott Derrickson and Ed Wood of the same nationality?',
#  [{'id': 0, 'text': 'Scott Derrickson Scott Derrickson (born July 16, 1966) is an American director, screenwriter and producer. He lives in Los Angeles, California. He is best known for directing horror films such as "Sinister", "The Exorcism of Emily Rose", and "Deliver Us From Evil", as well as the 2016 Marvel Cinematic Universe installment, "Doctor Strange."'},
#  {'id': 1, 'text': 'Ed Wood Edward Davis Wood Jr. (October 10, 1924 - December 10, 1978) was an American filmmaker, actor, writer, producer, and director.'}
#  # 100 context in total ...
# ])
# context_texts = [t['text'] for t in contexts]

# def rerank_documents(model, query, contexts):
#  rets = model.rank(query, contexts, batch_size=64)
#  return rets


# rets=rerank_documents(v2m3_model, query, context_texts)

# Baseline

In [28]:
from tqdm import tqdm
from evaluation import evaluate

set_seed(24)

stop_iteration = 20
retrival_list=[]
scores_list=[]
for idx, row in tqdm(qa_df.iterrows(), total=min([stop_iteration, len(qa_df)])):
    if idx == stop_iteration: break
    query = row['question']
    retrieved_docs, doc_ids = retrieve_documents_eval(query,10)
    tmp=0
    for doc_id in doc_ids:    
        tmp+=match_sample_id(idx, doc_id)
    res=tmp/len(retrieved_docs)
    print("Retrival Match Rate:", res)
    dic=dict()
    dic['first_retrival']=res
    ans=total_answer(query,retrieved_docs)
    print('Final ans:', ans)
    scores=evaluate([ans], [row.to_dict()])
    scores_list.append(scores)
    scores_df=pd.DataFrame(scores_list)
    print(scores)
    retrival_list.append(dic)
    retrival_df=pd.DataFrame(retrival_list)
    print(dic)
        
scores_df=pd.DataFrame(scores_list)
scores_df.mean()

retrival_df=pd.DataFrame(retrival_list)
retrival_df.mean()

  0%|          | 0/20 [00:00<?, ?it/s]/home/dataconv/.cache/huggingface/modules/transformers_modules/nvidia/NV-Embed-v2/5130cf1daf847c1bacee854a6ef1ca939e747fb2/modeling_nvembed.py:349: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'input_ids': torch.tensor(batch_dict.get('input_ids').to(batch_dict.get('input_ids')).long()),
/home/dataconv/anaconda3/envs/sf_rag_djk/lib/python3.10/contextlib.py:103: FutureWarning: `torch.backends.cuda.sdp_kernel()` is deprecated. In the future, this context manager will be removed. Please see `torch.nn.attention.sdpa_kernel()` for the new context manager, with updated signature.
  self.gen = func(*args, **kwds)

Retrival Match Rate: 0.5
Final ans: Ali Daei holds the record for the highest number of international goals with 109 goals for Iran, surpassing Ferenc Puskás' record of 84 goals. Cristiano Ronaldo has scored 1030 goals in his career, the highest among active players, with a total of 738 goals in his international career. Miroslav Klose holds the record for most World Cup goals with 16 goals, while Gerd Müller used to be the holder of that record from 1974 until it was broken by Ronaldo in 2006. Pelé scored 77 international goals, the highest among players from outside Europe, and Jürgen Klinsmann scored 11 goals in the World Cup, the highest among players from Germany. The top goalscorers in the World Cup history are Ali Daei, Cristiano Ronaldo, Ferenc Puskás, Kunishige Kamamoto, Godfrey Chitalu, Hussein Saeed, and Zainal Abidin, among others.
Ali Daei holds the record for the highest number of international goals with 109 goals for Iran, surpassing Ferenc Puskás' record of 84 goals. Cristiano Ronaldo has scored 1030 goals in his career, the highest among active players, with a total of 738 goals in his international career. Miroslav Klose holds the record for most World Cup goals with 16 goals, while Gerd Müller used to be the holder of that record from 1974 until it was broken by Ronaldo in 2006. Pelé scored 77 international goals, the highest among players from outside Europe, and Jürgen Klinsmann scored 11 goals in the World Cup, the highest among players from Germany. The top goalscorers in the World Cup history are Ali Daei, Cristiano Ronaldo, Ferenc Puskás, Kunishige Kamamoto, Godfrey Chitalu, Hussein Saeed, and Zainal Abidin, among others.
Who has the highest goals in world football?
["Who has the highest goals in men's world international football?", "Who has the highest goals all-time in men's football?", "Who has the highest goals in women's world international football?"]
[['Daei', 'Ali Daei'], ['Bican', 'Josef Bican'], ['Sinclair', 'Christine Sinclair']]

  5%|▌         | 1/20 [00:26<08:14, 26.01s/it]

follow question : Who has the highest goals in men's world international football?
short answer : ['Daei', 'Ali Daei']
{'score': 0.7431520223617554, 'start': 143, 'end': 160, 'answer': 'Cristiano Ronaldo'}
follow question : Who has the highest goals all-time in men's football?
short answer : ['Bican', 'Josef Bican']
{'score': 0.39714962244033813, 'start': 143, 'end': 160, 'answer': 'Cristiano Ronaldo'}
follow question : Who has the highest goals in women's world international football?
short answer : ['Sinclair', 'Christine Sinclair']
{'score': 8.483205249376624e-08, 'start': 0, 'end': 8, 'answer': 'Ali Daei'}
{'rougeLsum': 38.68312757201646, 'length': 136.0, 'str_em': 33.33333333333333, 'Disambig-F1': 0.0}
{'first_retrival': 0.5}
Retrival Match Rate: 1.0

  5%|▌         | 1/20 [00:31<10:05, 31.87s/it]

KeyboardInterrupt:

In [130]:
# 기본 라그에 문서 10개 검색 함수는 기본 함수 answer
import pandas as pd
import math
sf = pd.read_csv('results/basicRAG_seed24-len20-newdata_results.csv')
sf=sf[sf['length']<1000][:100]
print(len(sf))
print(sf.mean())
r=sf.mean()['rougeLsum']
d=sf.mean()['Disambig-F1']
dr=math.sqrt(r*d)
print(dr)

20
rougeLsum      26.424077
length         31.200000
str_em         49.166667
Disambig-F1    44.894841
dtype: float64
34.44277482138087

In [132]:
# 기본 라그에 제목 검색 10개 후 그안에서 문서 10개 검색 함수는 기본함수 answer
import pandas as pd
import math
sf = pd.read_csv('results/basicRAG_seed24-len20-title_results.csv')
sf=sf[sf['length']<1000][:100]
print(len(sf))
print(sf.mean())
r=sf.mean()['rougeLsum']
d=sf.mean()['Disambig-F1']
dr=math.sqrt(r*d)
print(dr)

20
rougeLsum      30.492810
length         27.050000
str_em         48.750000
Disambig-F1    51.680556
dtype: float64
39.697422727900765

In [129]:
# 기본 라그에 문서 10개 검색 함수는 total_answer
import pandas as pd
import math
sf = pd.read_csv('results/basicRAG_seed24-totalanswer-doc10_results.csv')
sf=sf[sf['length']<1000][:100]
print(len(sf))
print(sf.mean())
r=sf.mean()['rougeLsum']
d=sf.mean()['Disambig-F1']
dr=math.sqrt(r*d)
print(dr)

20
rougeLsum      36.529148
length         93.200000
str_em         58.333333
Disambig-F1    49.708333
dtype: float64
42.61224056875744

In [131]:
# 기본 라그에 제목 검색 10개후 그안에서 문서 10개 검색 함수는 total_answer
import pandas as pd
import math
sf = pd.read_csv('results/basicRAG_seed24-totalanswer-title10_results.csv')
sf=sf[sf['length']<1000][:100]
print(len(sf))
print(sf.mean())
r=sf.mean()['rougeLsum']
d=sf.mean()['Disambig-F1']
dr=math.sqrt(r*d)
print(dr)

20
rougeLsum      36.918206
length         92.000000
str_em         56.666667
Disambig-F1    47.319444
dtype: float64
41.796519228254525

In [36]:
def answer_2020(query, title, context):
    prompt = """
    Context information is below.
    ---------------------
    {0}
    ---------------------
    Given the context information and not prior knowledge, answer this ambiuous question.
    1. You should include in answer the content according to the various interpretations of the question
    2. When using time-related information to answer the question, only use information before February 1, 2020.
    3. If you can’t answer the question, say "Not relevant" only.
    4. The answer should be made considering the title.
    5. Each contents should include the subject, verb, predicate, object, time, and place appropriately.
    6. Answers to questions should be no longer than 5 sentences.
    Do not comment your answer and strictly follow this instructions.
    Query: {1}
    Title: {2}
    Answer:
    """.format('\n'.join(context), query, title)
    input_ids = tokenizer_gen.apply_chat_template([{"role":'user', "content":prompt}], return_tensors='pt').to(device1)

    attention_mask = (input_ids != tokenizer_gen.pad_token_id).long().to(device1)

    out = model_gen.generate(input_ids, attention_mask=attention_mask, pad_token_id=tokenizer_gen.pad_token_id, max_new_tokens = 512)
    res = tokenizer_gen.decode(out[0]).split('<|end_header_id|>')[-1] 
    return re.sub('\n|<\|eot_id\|>', '', res)

In [45]:
def answer_2020_2(query, title, context):
    prompt = """
    Context information is below.
    ---------------------
    {0}
    ---------------------
    Given the context information and not prior knowledge, answer this ambiuous question.
    1. You should include in answer the content according to the various interpretations of the question
    2. When using time-related information to answer the question, only use information before February 1, 2020.
    3. If you can’t answer the question, say "Not relevant" only.
    4. Title means topic of context, so it should be considered when making answer.
    5. Answers to questions should be no longer than 200 words.
    Do not comment your answer and strictly follow this instructions.
    Query: {1}
    Title: {2}
    Answer:
    """.format('\n'.join(context), query, title)
    input_ids = tokenizer_gen.apply_chat_template([{"role":'user', "content":prompt}], return_tensors='pt').to(device1)

    attention_mask = (input_ids != tokenizer_gen.pad_token_id).long().to(device1)

    out = model_gen.generate(input_ids, attention_mask=attention_mask, pad_token_id=tokenizer_gen.pad_token_id, max_new_tokens = 512)
    res = tokenizer_gen.decode(out[0]).split('<|end_header_id|>')[-1] 
    return re.sub('\n|<\|eot_id\|>', '', res)

In [60]:
def total_answer_2020(query, docs):
    prompt = """
    Context information is below.
    ---------------------
    {0}
    ---------------------
    Given the context information and not prior knowledge, answer this ambiuous question.
    1. Summarize all information in less than 100 characters. 
    2. You must include subject, verb, object, time, and place.
    Do not comment your answer and strictly follow this instructions.
    Query: {1}
    Answer:
    """.format('\n'.join(docs), query)
    input_ids = tokenizer_gen.apply_chat_template([{"role":'user', "content":prompt}], return_tensors='pt').to(device1)

    attention_mask = (input_ids != tokenizer_gen.pad_token_id).long().to(device1)

    out = model_gen.generate(input_ids, attention_mask=attention_mask, pad_token_id=tokenizer_gen.pad_token_id, max_new_tokens = 512)
    res = tokenizer_gen.decode(out[0]).split('<|end_header_id|>')[-1] 
    return re.sub('\n|<\|eot_id\|>', '', res)

In [58]:
# def total_answer(query, docs):
#     prompt = """
#     Context information is below.
#     ---------------------
#     {0}
#     ---------------------
#     Given the context information and not prior knowledge, answer the query.
#     1. The query is an ambiguous question.
#     2. Therefore, you must include the contents according to the various interpretations of the query in one answer by utilizing the given context.
#     3. When using time-related information to answer the question, only use information before February 1, 2020.
#     4. Each content according to the various interpretations of the query must be explained in one or two sentences.
#     5. The total answer must be 5 sentences or less.
#     Do not comment your answer and strictly follow this instructions.
#     Query: {1}
#     Answer:
#     """.format('\n'.join(docs), query)
#     input_ids = tokenizer_gen.apply_chat_template([{"role":'user', "content":prompt}], return_tensors='pt').to(device1)

#     attention_mask = (input_ids != tokenizer_gen.pad_token_id).long().to(device1)

#     out = model_gen.generate(input_ids, attention_mask=attention_mask, pad_token_id=tokenizer_gen.pad_token_id, max_new_tokens = 512)
#     res = tokenizer_gen.decode(out[0]).split('<|end_header_id|>')[-1] 
#     return re.sub('\n|<\|eot_id\|>', '', res)

In [40]:
from tqdm import tqdm
from evaluation import evaluate

set_seed(24)

stop_iteration = 20
retrival_list=[]
scores_list=[]
for idx, row in tqdm(qa_df.iterrows(), total=min([stop_iteration, len(qa_df)])):
    if idx == stop_iteration: break
    query = row['question']   
    
    retrieved_docs, doc_ids = retrieve_documents_eval(query,10)
    ori_ans=total_answer(query, retrieved_docs)
    print('Basic ans:',ori_ans)
    
    titles,title_ids=retrieve_titles(query, 10)
    docs=[]
    first_ans=[]
    
    first_ans.append(ori_ans)
    
    for title in titles:
        text_docs=evidence_eval_df.loc[evidence_eval_df['title']==title,'text'].to_list()
        docs_tensor=evidence_embeddings_eval[evidence_eval_df['title']==title]
        title_retrieved_docs,_=retrieve_documents3(query, docs_tensor, pd.DataFrame(text_docs, columns=['text']), 2)
        while 1:
            ans=answer_2020(query, title, title_retrieved_docs)
            if "Context information is below." not in ans:
                break
        print(ans)
        if "Not relevant" in ans:
            continue
        first_ans.append(ans)
    print(first_ans)
    # final_docs, doc_titles=retrieve_inside(query, titles, 10)
    # print(final_docs, doc_titles)
    # # retrieved_docs, doc_ids = retrieve_documents2(query)
    # tmp=0
    # for doc_title in doc_titles:
    #     tmp+=match_sample_id2(idx, doc_title)
    # res=tmp/len(final_docs)
    # print("Retrival Match Rate:", res)
    # dic=dict()
    # dic['first_retrival']=res
    
    final_ans=total_answer(query,first_ans)
    # ans='. '.join(first_ans)
    print('Final ans:', final_ans)
    scores=evaluate([final_ans], [row.to_dict()])
    scores_list.append(scores)
    scores_df=pd.DataFrame(scores_list)
    print(scores)
    # retrival_list.append(dic)
    # retrival_df=pd.DataFrame(retrival_list)
    # print(dic)
        
scores_df=pd.DataFrame(scores_list)
scores_df.mean()

# retrival_df=pd.DataFrame(retrival_list)
# retrival_df.mean()

  0%|          | 0/20 [00:00<?, ?it/s]

Basic ans: Ali Daei holds the record for the highest number of international goals with 109 goals for Iran, surpassing Ferenc Puskás' record of 84 goals. Cristiano Ronaldo has scored 1030 goals in his career, the highest among active players, with a total of 738 goals in his international career. Miroslav Klose holds the record for most World Cup goals with 16 goals, while Gerd Müller used to be the holder of that record from 1974 until it was broken by Ronaldo in 2006. Pelé scored 77 international goals, the highest among players from outside Europe, and Jürgen Klinsmann scored 11 goals in the World Cup, the highest among players from Germany. The top goalscorers in the World Cup history are Ali Daei, Cristiano Ronaldo, Ferenc Puskás, Kunishige Kamamoto, Godfrey Chitalu, Hussein Saeed, and Zainal Abidin, among others.
Ali Daei has the highest goals in world football with 109 international goals.
Josef Bican has the highest goals in world football with 805 goals.Cristiano Ronaldo has the highest total goals with 1030 goals.Romário has the highest goals among active players with 994 goals.Lionel Messi has the highest goals among active players with 903 goals.Zlatan Ibrahimović has the highest goals among active players with 920 goals.Cristiano Ronaldo is the most active player with the highest number of matches played with 0.72 ratio.Lionel Messi is the most active player with the highest number of matches played with 0.8 ratio.Zlatan Ibrahimović is the most active player with the highest number of matches played with 0.59 ratio.Cristiano Ronaldo has played for several clubs including Sporting CP, Manchester United, and Real Madrid.Lionel Messi has played for several clubs including Barcelona, and Paris Saint-Germain.Zlatan Ibrahimović has played for several clubs including Malmö FF, Ajax, and Paris Saint-Germain.Cristiano Ronaldo has won several awards and titles throughout his career.Lionel Messi has won several awards and titles throughout his career.Zlatan Ibrahimović has won several awards and titles throughout his career.Cristiano Ronaldo has been playing football since 2001.Lionel Messi has been playing football since 2003.Zlatan Ibrahimović has been playing football since 1999.Cristiano Ronaldo has scored 1030 goals in his career.Lionel Messi has scored 903 goals in his career.Zlatan Ibrahimović has scored 920 goals in his career.Cristiano Ronaldo has played for the Portugal national team.Lionel Messi has played for the Argentina national team.Zlatan Ibrahimović has played for the Sweden national team.Cristiano Ronaldo has won the Ballon d'Or award.Lionel Messi has won the Ballon d'Or award.Zlatan Ibrahimović has won the Golden Boot award.Cristiano Ronaldo has been playing for Real Madrid since 2009.Lionel Messi has been playing for Barcelona since 2004.Zlatan Ibrahimović has been playing for Paris Saint-Germain since 2012.Cristiano Ronaldo has scored 69 goals for Real Madrid.Lionel Messi has scored 269 goals for Barcelona.Zlatan Ibrahimović has scored 53 goals for Paris
Ali Daei of Iran holds the record with 109 international goals.
Miroslav Klose holds the record for the highest goals in the FIFA World Cup with 16 goals across four consecutive tournaments between 2002 and 2014.
Ali Daei has the highest goals in world football with 109 international goals.
Christine Sinclair holds the record for the highest number of international goals with 185 goals.
Cristiano Ronaldo has the highest goals in the UEFA Champions League with 128 goals as of 11 December 2019.
Pelé has the highest goals in world football with a total of 128 goals, but the highest goals in a single World Cup tournament is held by Just Fontaine with 13 goals in the 1958 World Cup.
Not relevant, as the information provided focuses on own goals in the FIFA World Cup, not overall goals in world football.
Miroslav Klose of Germany has the highest goals in world football with 16 goals.
["Ali Daei holds the record for the highest number of international goals with 109 goals for Iran, surpassing Ferenc Puskás' record of 84 goals. Cristiano Ronaldo has scored 1030 goals in his career, the highest among active players, with a total of 738 goals in his international career. Miroslav Klose holds the record for most World Cup goals with 16 goals, while Gerd Müller used to be the holder of that record from 1974 until it was broken by Ronaldo in 2006. Pelé scored 77 international goals, the highest among players from outside Europe, and Jürgen Klinsmann scored 11 goals in the World Cup, the highest among players from Germany. The top goalscorers in the World Cup history are Ali Daei, Cristiano Ronaldo, Ferenc Puskás, Kunishige Kamamoto, Godfrey Chitalu, Hussein Saeed, and Zainal Abidin, among others.", 'Ali Daei has the highest goals in world football with 109 international goals.', "Josef Bican has the highest goals in world football with 805 goals.Cristiano Ronaldo has the highest total goals with 1030 goals.Romário has the highest goals among active players with 994 goals.Lionel Messi has the highest goals among active players with 903 goals.Zlatan Ibrahimović has the highest goals among active players with 920 goals.Cristiano Ronaldo is the most active player with the highest number of matches played with 0.72 ratio.Lionel Messi is the most active player with the highest number of matches played with 0.8 ratio.Zlatan Ibrahimović is the most active player with the highest number of matches played with 0.59 ratio.Cristiano Ronaldo has played for several clubs including Sporting CP, Manchester United, and Real Madrid.Lionel Messi has played for several clubs including Barcelona, and Paris Saint-Germain.Zlatan Ibrahimović has played for several clubs including Malmö FF, Ajax, and Paris Saint-Germain.Cristiano Ronaldo has won several awards and titles throughout his career.Lionel Messi has won several awards and titles throughout his career.Zlatan Ibrahimović has won several awards and titles throughout his career.Cristiano Ronaldo has been playing football since 2001.Lionel Messi has been playing football since 2003.Zlatan Ibrahimović has been playing football since 1999.Cristiano Ronaldo has scored 1030 goals in his career.Lionel Messi has scored 903 goals in his career.Zlatan Ibrahimović has scored 920 goals in his career.Cristiano Ronaldo has played for the Portugal national team.Lionel Messi has played for the Argentina national team.Zlatan Ibrahimović has played for the Sweden national team.Cristiano Ronaldo has won the Ballon d'Or award.Lionel Messi has won the Ballon d'Or award.Zlatan Ibrahimović has won the Golden Boot award.Cristiano Ronaldo has been playing for Real Madrid since 2009.Lionel Messi has been playing for Barcelona since 2004.Zlatan Ibrahimović has been playing for Paris Saint-Germain since 2012.Cristiano Ronaldo has scored 69 goals for Real Madrid.Lionel Messi has scored 269 goals for Barcelona.Zlatan Ibrahimović has scored 53 goals for Paris", 'Ali Daei of Iran holds the record with 109 international goals.', 'Miroslav Klose holds the record for the highest goals in the FIFA World Cup with 16 goals across four consecutive tournaments between 2002 and 2014.', 'Ali Daei has the highest goals in world football with 109 international goals.', 'Christine Sinclair holds the record for the highest number of international goals with 185 goals.', 'Cristiano Ronaldo has the highest goals in the UEFA Champions League with 128 goals as of 11 December 2019.', 'Pelé has the highest goals in world football with a total of 128 goals, but the highest goals in a single World Cup tournament is held by Just Fontaine with 13 goals in the 1958 World Cup.', 'Miroslav Klose of Germany has the highest goals in world football with 16 goals.']
Final ans: Josef Bican holds the highest goals in world football with 805 goals. However, Ali Daei holds the record for the highest number of international goals with 109 goals, but this is not the highest in world football. Christine Sinclair holds the record for the highest number of international goals with 185 goals, making her the highest goals in world football. Ali Daei has the highest goals in world football with 109 international goals. Josef Bican has the highest goals in world football with 805 goals, but this is not the same as the highest number of international goals.
Josef Bican holds the highest goals in world football with 805 goals. However, Ali Daei holds the record for the highest number of international goals with 109 goals, but this is not the highest in world football. Christine Sinclair holds the record for the highest number of international goals with 185 goals, making her the highest goals in world football. Ali Daei has the highest goals in world football with 109 international goals. Josef Bican has the highest goals in world football with 805 goals, but this is not the same as the highest number of international goals.
Who has the highest goals in world football?
["Who has the highest goals in men's world international football?", "Who has the highest goals all-time in men's football?", "Who has the highest goals in women's world international football?"]
[['Daei', 'Ali Daei'], ['Bican', 'Josef Bican'], ['Sinclair', 'Christine Sinclair']]

  5%|▌         | 1/20 [01:40<31:58, 100.99s/it]

follow question : Who has the highest goals in men's world international football?
short answer : ['Daei', 'Ali Daei']
{'score': 0.0013633996713906527, 'start': 79, 'end': 87, 'answer': 'Ali Daei'}
follow question : Who has the highest goals all-time in men's football?
short answer : ['Bican', 'Josef Bican']
{'score': 9.925947961164638e-05, 'start': 0, 'end': 11, 'answer': 'Josef Bican'}
follow question : Who has the highest goals in women's world international football?
short answer : ['Sinclair', 'Christine Sinclair']
{'score': 0.6236764788627625, 'start': 214, 'end': 232, 'answer': 'Christine Sinclair'}
{'rougeLsum': 46.76616915422886, 'length': 98.0, 'str_em': 100.0, 'Disambig-F1': 100.0}
Basic ans: The original artist of "Sound of Silence" is Simon & Garfunkel, an American music duo composed of Paul Simon and Art Garfunkel. The song was written by Paul Simon, and its original version was recorded in March 1964 for their debut album, Wednesday Morning, 3 A.M. The duo's version of "Sound of Silence" was later re-recorded with electric instruments and drums, which became a hit single in September 1965. This re-recorded version was released as a single and is the one that gained popularity worldwide.
The original artist of "The Sound of Silence" is Paul Simon, who wrote the song over several months in 1963 and 1964.
The song "Sound of Silence" is originally performed by Australian recording artist Dami Im.
The original artist of "The Sound of Silence" is Paul Simon, and the song was originally released as "The Sounds of Silence" on the album Wednesday Morning, 3 A.M. in March 1964. The song was later modified and released as a single in September 1965, and the electric version was overdubbed by Columbia Records staff producer Tom Wilson on June 15, 1965.The song's original release was as part of the album Wednesday Morning, 3 A.M., which was released in March 1964.The album Sounds of Silence, which includes the modified version of "The Sound of Silence", was released on January 17, 1966.The song "The Sound of Silence" was recorded in April, June, and December 1965 at CBS Studios in New York City, New York and Los Angeles, California.The song's original artist, Paul Simon, wrote the song while he lived in London during 1965.The album Sounds of Silence is the second studio album by Simon & Garfunkel, released on January 17, 1966.The song "The Sound of Silence" was later released as part of the box set Simon & Garfunkel Collected Works, on both LP and CD.The song's electric version was overdubbed by Columbia Records staff producer Tom Wilson on June 15, 1965.The album Sounds of Silence is included in its entirety as part of the Simon & Garfunkel box sets Collected Works and The Columbia Studio Recordings (1964–1970).The song "The Sound of Silence" was announced to be preserved by the Library of Congress in the National Recording Registry on March 22, 2013.The song's original artist, Paul Simon, is the lead vocalist, and the song features electric guitars, bass, and drums, which were overdubbed by Columbia Records staff producer Tom Wilson on June 15, 1965.The song's original release was as part of the album Wednesday Morning, 3 A.M., which was released in March 1964.The song "The Sound of Silence" was later released as a single in September 1965, and the electric version was overdubbed by Columbia Records staff producer Tom Wilson on June 15, 1965.The album Sounds of Silence, which includes the modified version of "The Sound of Silence", was released on January 17, 1966.The song's
Not relevant
Not relevant because the original artist of the song "The Sound of Silence" is not mentioned in the context information provided for The Greatest Showman (soundtrack).
Not relevant
The original artist of the soundtrack of The Last Airbender is James Newton Howard.
Not relevant.
David Coverdale is the original artist of the song "Still of the Night".
Not relevant.
['The original artist of "Sound of Silence" is Simon & Garfunkel, an American music duo composed of Paul Simon and Art Garfunkel. The song was written by Paul Simon, and its original version was recorded in March 1964 for their debut album, Wednesday Morning, 3 A.M. The duo\'s version of "Sound of Silence" was later re-recorded with electric instruments and drums, which became a hit single in September 1965. This re-recorded version was released as a single and is the one that gained popularity worldwide.', 'The original artist of "The Sound of Silence" is Paul Simon, who wrote the song over several months in 1963 and 1964.', 'The song "Sound of Silence" is originally performed by Australian recording artist Dami Im.', 'The original artist of "The Sound of Silence" is Paul Simon, and the song was originally released as "The Sounds of Silence" on the album Wednesday Morning, 3 A.M. in March 1964. The song was later modified and released as a single in September 1965, and the electric version was overdubbed by Columbia Records staff producer Tom Wilson on June 15, 1965.The song\'s original release was as part of the album Wednesday Morning, 3 A.M., which was released in March 1964.The album Sounds of Silence, which includes the modified version of "The Sound of Silence", was released on January 17, 1966.The song "The Sound of Silence" was recorded in April, June, and December 1965 at CBS Studios in New York City, New York and Los Angeles, California.The song\'s original artist, Paul Simon, wrote the song while he lived in London during 1965.The album Sounds of Silence is the second studio album by Simon & Garfunkel, released on January 17, 1966.The song "The Sound of Silence" was later released as part of the box set Simon & Garfunkel Collected Works, on both LP and CD.The song\'s electric version was overdubbed by Columbia Records staff producer Tom Wilson on June 15, 1965.The album Sounds of Silence is included in its entirety as part of the Simon & Garfunkel box sets Collected Works and The Columbia Studio Recordings (1964–1970).The song "The Sound of Silence" was announced to be preserved by the Library of Congress in the National Recording Registry on March 22, 2013.The song\'s original artist, Paul Simon, is the lead vocalist, and the song features electric guitars, bass, and drums, which were overdubbed by Columbia Records staff producer Tom Wilson on June 15, 1965.The song\'s original release was as part of the album Wednesday Morning, 3 A.M., which was released in March 1964.The song "The Sound of Silence" was later released as a single in September 1965, and the electric version was overdubbed by Columbia Records staff producer Tom Wilson on June 15, 1965.The album Sounds of Silence, which includes the modified version of "The Sound of Silence", was released on January 17, 1966.The song\'s', 'The original artist of the soundtrack of The Last Airbender is James Newton Howard.', 'David Coverdale is the original artist of the song "Still of the Night".']
Final ans: The original artist of "Sound of Silence" is Simon & Garfunkel, an American music duo composed of Paul Simon and Art Garfunkel, with Paul Simon writing the song. Paul Simon is credited as the original artist of "The Sound of Silence". The song was originally released as "The Sounds of Silence" on the album Wednesday Morning, 3.A. The song's electric version was overdubbed by Columbia Records staff producer Tom Wilson on June 15, 1965. David Coverdale is the original artist of the song "Still of the Night", which is unrelated to "Sound of Silence".
The original artist of "Sound of Silence" is Simon & Garfunkel, an American music duo composed of Paul Simon and Art Garfunkel, with Paul Simon writing the song. Paul Simon is credited as the original artist of "The Sound of Silence". The song was originally released as "The Sounds of Silence" on the album Wednesday Morning, 3.A. The song's electric version was overdubbed by Columbia Records staff producer Tom Wilson on June 15, 1965. David Coverdale is the original artist of the song "Still of the Night", which is unrelated to "Sound of Silence".
Who is the original artist of sound of silence?
['Who is the original artist of sound of silence, the song, released in 1964?', 'Who is the original artist of sound of silence, the album?', 'Who is the original artist of sound of silence, the song, released in 2016?']
[['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon'], ['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon'], ['Dami Im']]

 10%|█         | 2/20 [03:04<27:13, 90.73s/it]

follow question : Who is the original artist of sound of silence, the song, released in 1964?
short answer : ['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon']
{'score': 0.00011776974861277267, 'start': 45, 'end': 62, 'answer': 'Simon & Garfunkel'}
follow question : Who is the original artist of sound of silence, the album?
short answer : ['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon']
{'score': 0.21595408022403717, 'start': 45, 'end': 62, 'answer': 'Simon & Garfunkel'}
follow question : Who is the original artist of sound of silence, the song, released in 2016?
short answer : ['Dami Im']
{'score': 0.00010484140511834994, 'start': 45, 'end': 62, 'answer': 'Simon & Garfunkel'}
{'rougeLsum': 45.16129032258064, 'length': 94.0, 'str_em': 66.66666666666666, 'Disambig-F1': 66.66666666666666}
Basic ans: The first iPhone was developed in 2004, with a team of 1,000 employees, including Jonathan Ive, working on the highly confidential "Project Purple." The development cost of the collaboration was estimated to have been $150 million over a thirty-month period. Apple created the device during a secretive collaboration with Cingular Wireless, now AT&T Mobility, and the development cost of the collaboration was estimated to have been $150 million over a thirty-month period. The original iPhone was announced on January 9, 2007, and was released in the United States on June 29, 2007. The first-generation iPhone was discontinued on July 15, 2008, with total sales volume coming to 6,124,000 units.
The first iPhone was conceived by Steve Jobs in 2005 and officially announced on January 9, 2007, with its release in the United States on June 29, 2007.
The first iPhone beta was created in 2004 to test the commands of the Apple team, but it was never released to the public.
Development of what was to become the iPhone began in 2004, when Apple started to gather a team of 1,000 employees to work on the highly confidential "Project Purple."
Not relevant
Not relevant
Not relevant.
Not relevant
Not relevant
Not relevant.
Not relevant
['The first iPhone was developed in 2004, with a team of 1,000 employees, including Jonathan Ive, working on the highly confidential "Project Purple." The development cost of the collaboration was estimated to have been $150 million over a thirty-month period. Apple created the device during a secretive collaboration with Cingular Wireless, now AT&T Mobility, and the development cost of the collaboration was estimated to have been $150 million over a thirty-month period. The original iPhone was announced on January 9, 2007, and was released in the United States on June 29, 2007. The first-generation iPhone was discontinued on July 15, 2008, with total sales volume coming to 6,124,000 units.', 'The first iPhone was conceived by Steve Jobs in 2005 and officially announced on January 9, 2007, with its release in the United States on June 29, 2007.', 'The first iPhone beta was created in 2004 to test the commands of the Apple team, but it was never released to the public.', 'Development of what was to become the iPhone began in 2004, when Apple started to gather a team of 1,000 employees to work on the highly confidential "Project Purple."']
Final ans: The first iPhone was developed in 2004, with a team of 1,000 employees, including Jonathan Ive, working on the highly confidential "Project Purple." The development cost of the collaboration was estimated to have been $150 million over a thirty-month period. However, the development of the iPhone as we know it today, began in 2004, but it was conceived by Steve Jobs in 2005. The first iPhone beta was created in 2004 to test the commands of the Apple team, but it was never released to the public. The first-generation iPhone was announced on January 9, 2007, and was released in the United States on June 29, 2007.
The first iPhone was developed in 2004, with a team of 1,000 employees, including Jonathan Ive, working on the highly confidential "Project Purple." The development cost of the collaboration was estimated to have been $150 million over a thirty-month period. However, the development of the iPhone as we know it today, began in 2004, but it was conceived by Steve Jobs in 2005. The first iPhone beta was created in 2004 to test the commands of the Apple team, but it was never released to the public. The first-generation iPhone was announced on January 9, 2007, and was released in the United States on June 29, 2007.
When was the first apple i phone made?
['When was the first apple i phone released?', 'When was the first apple i phone for beta testing made?', 'When was the first apple i phone 1 made?', 'When was the first apple i phone beta made?']
[['June 29, 2007'], ['2004'], ['June 29, 2007.'], ['2004.']]

 15%|█▌        | 3/20 [03:46<19:22, 68.40s/it]

follow question : When was the first apple i phone released?
short answer : ['June 29, 2007']
{'score': 0.6799805760383606, 'start': 604, 'end': 617, 'answer': 'June 29, 2007'}
follow question : When was the first apple i phone for beta testing made?
short answer : ['2004']
{'score': 0.6845384836196899, 'start': 415, 'end': 419, 'answer': '2004'}
follow question : When was the first apple i phone 1 made?
short answer : ['June 29, 2007.']
{'score': 0.9383801221847534, 'start': 34, 'end': 38, 'answer': '2004'}
follow question : When was the first apple i phone beta made?
short answer : ['2004.']
{'score': 0.6954370737075806, 'start': 415, 'end': 419, 'answer': '2004'}
{'rougeLsum': 44.31818181818181, 'length': 107.0, 'str_em': 100.0, 'Disambig-F1': 75.0}
Basic ans: The Weasley brothers, Bill, Charlie, Fred, George, Percy, Ron, and their father Arthur, were portrayed by multiple actors in the Harry Potter film series. James and Oliver Phelps played the roles of Fred and George Weasley, respectively, in all eight films. David Thewlis played the role of Remus Lupin, who becomes a close friend of the Weasley family, in the third film, Harry Potter and the Prisoner of Azkaban. Richard Griffiths played the role of Vernon Dursley, Ron's uncle and the husband of Petunia Dursley, in the first three films. David Bradley played the role of Argus Filch, the caretaker of Hogwarts School of Witchcraft and Wizardry, in all eight films.
The Weasley brothers were played by James Phelps and Oliver Phelps, who portrayed Fred and George Weasley, respectively, in all eight films of the series, from "The Philosopher's Stone" in 2001 to "The Deathly Hallows – Part 1" in 2010.
The Weasley brothers were played by actors Daniel Radcliffe, Rupert Grint, and their real-life friends and fellow actors, including Matthew Lewis, Devon Murray, and Louis Mawston, who portrayed Fred, George, and Percy Weasley, respectively.
The Weasley brothers were played by various actors, including Chris Rankin as Percy Weasley, Jeff Rawles as Fred Weasley, and Sean Biggerstaff as Ron Weasley.
Not relevant
Not relevant
The Weasley brothers, Fred and George, were played by actors Daniel Radcliffe and his friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by
Not relevant
Not relevant
Rupert Grint played Ron Weasley, but the question asks for the Weasley brothers, so the answer is incomplete. However, considering the title and the information provided, it can be inferred that the Weasley brothers are Ron, Harry's best friend, and his siblings, but the specific siblings are not mentioned in the provided information.However, in the book and the series, the Weasley brothers are George and Fred, but the question is about the film "Harry Potter and the Philosopher's Stone" and the information provided is about the casting of the film, not the book. Considering the casting information for the film, it is clear that Rupert Grint played Ron Weasley, but the question asks for the Weasley brothers, which implies that the answer should include Ron's brothers, George and Fred. However, the information provided does not explicitly mention George and Fred being cast for the film. Given the information, the best answer is:Rupert Grint played Ron Weasley, but the Weasley brothers are implied to be Ron and his siblings, however, George and Fred are not explicitly mentioned in the provided information.However, the question is ambiguous and can be interpreted in different ways. If the question is asking for the actors who played the Weasley brothers in the film "Harry Potter and the Philosopher's Stone", the answer is incomplete. Considering the context and the casting information, the best answer is:Rupert Grint played Ron Weasley, but the Weasley brothers are implied to be Ron and his siblings, however, the information provided does not explicitly mention George and Fred being cast for the film.
Not relevant.
["The Weasley brothers, Bill, Charlie, Fred, George, Percy, Ron, and their father Arthur, were portrayed by multiple actors in the Harry Potter film series. James and Oliver Phelps played the roles of Fred and George Weasley, respectively, in all eight films. David Thewlis played the role of Remus Lupin, who becomes a close friend of the Weasley family, in the third film, Harry Potter and the Prisoner of Azkaban. Richard Griffiths played the role of Vernon Dursley, Ron's uncle and the husband of Petunia Dursley, in the first three films. David Bradley played the role of Argus Filch, the caretaker of Hogwarts School of Witchcraft and Wizardry, in all eight films.", 'The Weasley brothers were played by James Phelps and Oliver Phelps, who portrayed Fred and George Weasley, respectively, in all eight films of the series, from "The Philosopher\'s Stone" in 2001 to "The Deathly Hallows – Part 1" in 2010.', 'The Weasley brothers were played by actors Daniel Radcliffe, Rupert Grint, and their real-life friends and fellow actors, including Matthew Lewis, Devon Murray, and Louis Mawston, who portrayed Fred, George, and Percy Weasley, respectively.', 'The Weasley brothers were played by various actors, including Chris Rankin as Percy Weasley, Jeff Rawles as Fred Weasley, and Sean Biggerstaff as Ron Weasley.', "The Weasley brothers, Fred and George, were played by actors Daniel Radcliffe and his friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by actors Daniel Radcliffe's friends were not in the main cast, but the twins were played by", 'Rupert Grint played Ron Weasley, but the question asks for the Weasley brothers, so the answer is incomplete. However, considering the title and the information provided, it can be inferred that the Weasley brothers are Ron, Harry\'s best friend, and his siblings, but the specific siblings are not mentioned in the provided information.However, in the book and the series, the Weasley brothers are George and Fred, but the question is about the film "Harry Potter and the Philosopher\'s Stone" and the information provided is about the casting of the film, not the book. Considering the casting information for the film, it is clear that Rupert Grint played Ron Weasley, but the question asks for the Weasley brothers, which implies that the answer should include Ron\'s brothers, George and Fred. However, the information provided does not explicitly mention George and Fred being cast for the film. Given the information, the best answer is:Rupert Grint played Ron Weasley, but the Weasley brothers are implied to be Ron and his siblings, however, George and Fred are not explicitly mentioned in the provided information.However, the question is ambiguous and can be interpreted in different ways. If the question is asking for the actors who played the Weasley brothers in the film "Harry Potter and the Philosopher\'s Stone", the answer is incomplete. Considering the context and the casting information, the best answer is:Rupert Grint played Ron Weasley, but the Weasley brothers are implied to be Ron and his siblings, however, the information provided does not explicitly mention George and Fred being cast for the film.']
Final ans: The query is an ambiguous question, making it difficult to provide a definitive answer. However, considering the context information, one interpretation is that the Weasley brothers are Ron and his siblings, with Rupert Grint playing Ron Weasley in the film "Harry Potter and the Philosopher's Stone". However, George and Fred are not explicitly mentioned in the provided information, making it unclear who played these roles. Another interpretation is that the question is asking for the actors who played the Weasley brothers in the film "Harry Potter and the Philosopher's Stone", in which case the answer is incomplete. The most accurate answer based on the information provided is that Rupert Grint played Ron Weasley, but the Weasley brothers are implied to be Ron and his siblings, however, George and Fred are not explicitly mentioned in the provided information.
The query is an ambiguous question, making it difficult to provide a definitive answer. However, considering the context information, one interpretation is that the Weasley brothers are Ron and his siblings, with Rupert Grint playing Ron Weasley in the film "Harry Potter and the Philosopher's Stone". However, George and Fred are not explicitly mentioned in the provided information, making it unclear who played these roles. Another interpretation is that the question is asking for the actors who played the Weasley brothers in the film "Harry Potter and the Philosopher's Stone", in which case the answer is incomplete. The most accurate answer based on the information provided is that Rupert Grint played Ron Weasley, but the Weasley brothers are implied to be Ron and his siblings, however, George and Fred are not explicitly mentioned in the provided information.
Who played the weasley brothers in harry potter?
['Who played  Bill weasley in Harry Potter and the Prisoner of Azkaban?', 'Who played percy weasley in harry potter?', 'Who played fred weasley in harry potter?', 'Who played ron weasley in harry potter?', 'Who played george weasley in harry potter?', 'Who played  Bill weasley in harry potter (2001-2011)?']
[['Richard Fish'], ['Chris Rankin'], ['James Phelps'], ['Rupert Grint'], ['Oliver Phelps'], ['Domhnall Gleeson']]

 20%|██        | 4/20 [05:23<21:13, 79.58s/it]

follow question : Who played  Bill weasley in Harry Potter and the Prisoner of Azkaban?
short answer : ['Richard Fish']
{'score': 2.032855718425708e-06, 'start': 213, 'end': 225, 'answer': 'Rupert Grint'}
follow question : Who played percy weasley in harry potter?
short answer : ['Chris Rankin']
{'score': 0.0018550248350948095, 'start': 213, 'end': 225, 'answer': 'Rupert Grint'}
follow question : Who played fred weasley in harry potter?
short answer : ['James Phelps']
{'score': 0.00018785099382512271, 'start': 213, 'end': 225, 'answer': 'Rupert Grint'}
follow question : Who played ron weasley in harry potter?
short answer : ['Rupert Grint']
{'score': 0.7462419271469116, 'start': 213, 'end': 225, 'answer': 'Rupert Grint'}
follow question : Who played george weasley in harry potter?
short answer : ['Oliver Phelps']
{'score': 2.89349458171273e-07, 'start': 213, 'end': 225, 'answer': 'Rupert Grint'}
follow question : Who played  Bill weasley in harry potter (2001-2011)?
short answer : ['Domhnall Gleeson']
{'score': 2.996242528752191e-06, 'start': 213, 'end': 225, 'answer': 'Rupert Grint'}
{'rougeLsum': 29.53586497890295, 'length': 137.0, 'str_em': 16.666666666666664, 'Disambig-F1': 16.666666666666664}
Basic ans: There are 38 state parks in Virginia, as mentioned in the first document about the list of Virginia state parks. This number includes parks that are currently operational, under construction, and closed. The list of parks includes well-known parks such as Shenandoah River Raymond R. "Andy" Guest Jr. State Park, Shot Tower Historical State Park, and Sky Meadows State Park. Additionally, the list includes lesser-known parks such as Middle Peninsula State Park and Seven Bends State Park. The total number of state parks in Virginia is 38.
There are 38 state parks in Virginia as of June 15, 1936, and the number has increased over time, but as of the information before February 1, 2020, there are still 38 state parks in Virginia.
Not relevant, the document describes the Virginia State Capitol, not state parks.
Not relevant
There are more than 40 parks comprising a total of more than 1,500 acres in Richmond, Virginia, but the number of state parks in Virginia is not explicitly stated in the provided context information.
Not relevant.
Not relevant.
Not relevant
Not relevant.
Not relevant
Not relevant to the Battle of Philippi (West Virginia), but according to the Virginia State Parks website, as of my last update before February 1, 2020, there are 27 state parks in Virginia.
['There are 38 state parks in Virginia, as mentioned in the first document about the list of Virginia state parks. This number includes parks that are currently operational, under construction, and closed. The list of parks includes well-known parks such as Shenandoah River Raymond R. "Andy" Guest Jr. State Park, Shot Tower Historical State Park, and Sky Meadows State Park. Additionally, the list includes lesser-known parks such as Middle Peninsula State Park and Seven Bends State Park. The total number of state parks in Virginia is 38.', 'There are 38 state parks in Virginia as of June 15, 1936, and the number has increased over time, but as of the information before February 1, 2020, there are still 38 state parks in Virginia.', 'There are more than 40 parks comprising a total of more than 1,500 acres in Richmond, Virginia, but the number of state parks in Virginia is not explicitly stated in the provided context information.']
Final ans: The query "How many state parks are there in Virginia?" can be interpreted in different ways based on the provided context information.There are 38 state parks in Virginia as of June 15, 1936, and the number has increased over time, but as of the information before February 1, 2020, there are still 38 state parks in Virginia. This interpretation suggests that the number of state parks in Virginia is 38.However, the provided context information does not explicitly state that the 38 state parks include all parks in Virginia, which could potentially include parks outside of the state park system. This interpretation suggests that the number of state parks in Virginia could be different from 38.Moreover, the context information mentions that there are more than 40 parks comprising a total of more than 1,500 acres in Richmond, Virginia, but does not provide information about the total number of state parks in Virginia. This interpretation suggests that the number of state parks in Virginia is not 38, but rather a different number.Considering the ambiguity of the query, a more accurate answer would be that there are 38 state parks in Virginia as of the provided information, but it is unclear if this number includes all parks in Virginia or only those within the state park system.
The query "How many state parks are there in Virginia?" can be interpreted in different ways based on the provided context information.There are 38 state parks in Virginia as of June 15, 1936, and the number has increased over time, but as of the information before February 1, 2020, there are still 38 state parks in Virginia. This interpretation suggests that the number of state parks in Virginia is 38.However, the provided context information does not explicitly state that the 38 state parks include all parks in Virginia, which could potentially include parks outside of the state park system. This interpretation suggests that the number of state parks in Virginia could be different from 38.Moreover, the context information mentions that there are more than 40 parks comprising a total of more than 1,500 acres in Richmond, Virginia, but does not provide information about the total number of state parks in Virginia. This interpretation suggests that the number of state parks in Virginia is not 38, but rather a different number.Considering the ambiguity of the query, a more accurate answer would be that there are 38 state parks in Virginia as of the provided information, but it is unclear if this number includes all parks in Virginia or only those within the state park system.
How many state parks are there in virginia?
['How many state parks are there in virginia in 1936?', 'How many state parks are there in virginia in 2016?', 'How many state parks were there when the state park system formed in Virginia?', 'How many state parks were there in Virginia as of 2016?']
[['six'], ['38'], ['6'], ['38']]

 25%|██▌       | 5/20 [06:07<16:41, 66.75s/it]

follow question : How many state parks are there in virginia in 1936?
short answer : ['six']
{'score': 0.7302600741386414, 'start': 145, 'end': 147, 'answer': '38'}
follow question : How many state parks are there in virginia in 2016?
short answer : ['38']
{'score': 3.499498234305065e-06, 'start': 145, 'end': 147, 'answer': '38'}
follow question : How many state parks were there when the state park system formed in Virginia?
short answer : ['6']
{'score': 5.047075683251023e-05, 'start': 145, 'end': 147, 'answer': '38'}
follow question : How many state parks were there in Virginia as of 2016?
short answer : ['38']
{'score': 8.288002391054761e-07, 'start': 145, 'end': 147, 'answer': '38'}
{'rougeLsum': 23.972602739726025, 'length': 214.0, 'str_em': 75.0, 'Disambig-F1': 50.0}

In [29]:
query="Who has the highest goals in world football?"

In [30]:
first_ans=["Ali Daei holds the record for the highest number of international goals with 109 goals for Iran, surpassing Ferenc Puskás' record of 84 goals. Cristiano Ronaldo has scored 1030 goals in his career, the highest among active players, with a total of 738 goals in his international career. Miroslav Klose holds the record for most World Cup goals with 16 goals, while Gerd Müller used to be the holder of that record from 1974 until it was broken by Ronaldo in 2006. Pelé scored 77 international goals, the highest among players from outside Europe, and Jürgen Klinsmann scored 11 goals in the World Cup, the highest among players from Germany. The top goalscorers in the World Cup history are Ali Daei, Cristiano Ronaldo, Ferenc Puskás, Kunishige Kamamoto, Godfrey Chitalu, Hussein Saeed, and Zainal Abidin, among others.",
 "Ali Daei has the highest goals in world football with 109 international goals. He achieved this feat in his career span of 1993–2006, scoring his 50th goal on 9 January 2000. As of 2 December 2019, he holds the record for the most international goals scored.Ferenc Puskás of Hungary was the second player to achieve the feat, scoring 84 international goals. He scored his 50th goal on 24 July 1952, and his record remained unbroken for 47 years until Ali Daei broke it in 2003. Puskás held the record for the most international goals scored by a European player.Pelé of Brazil was the first player from outside Europe to score at least 50 goals, achieving the feat on 21 November 1965. He scored 77 international goals in his career span of 1957–1971. Pelé's record for the most international goals scored by a South American player was later surpassed by other players.Bader Al-Mutawa of Kuwait played the most matches to score 50 international goals, achieving the feat on 3 September 2015. He scored a hat-trick against Myanmar in the 2018 FIFA World Cup qualification matches.",
 'Josef Bican has the highest goals in world football with a total of 805 goals. He achieved this record between 1928 and 1955. Bican played for various clubs and national teams during his career.',
 'Ali Daei of Iran holds the record for the highest goals in international football with 109 goals, surpassing Ferenc Puskás of Hungary who had held the record for 47 years. He achieved this feat on 17 November 2004, when he scored a hat-trick against Laos in the 2006 FIFA World Cup qualification. This record is as of 2 December 2019.',
 "Miroslav Klose holds the record for the most goals in the World Cup, with 16 goals across four consecutive tournaments between 2002 and 2014. His record stood for more than three decades until it was surpassed by another player. Klose's achievement is considered one of the most impressive in the history of the World Cup.Ronaldo is the second-highest goalscorer in the World Cup, with 15 goals between 1998 and 2006 for Brazil. He broke the overall record when he scored his 14th goal in the World Cup final tournament during West Germany's win in the 1974 final. His record stood for more than three decades until Klose surpassed him.The top 97 goalscorers have represented 28 nations, with 14 players scoring for Brazil, and another 14 for Germany or West Germany. In total, 64 footballers came from UEFA (Europe), 29 from CONMEBOL (South America), and only four from elsewhere.",
 "Ali Daei holds the record for the highest goals in world football with 109 international goals as of 2 December 2019. He achieved this feat while playing for Iran, a country with a rich football history. This impressive record showcases Daei's exceptional skill and dedication to the sport.",
 'Christine Sinclair has the highest goals in world football among the listed players with 185 international goals. She achieved this milestone in just under 10 years of her active years, which started in 2000 and is still ongoing. As of 29 January 2020, she holds the record for the highest number of international goals.The top scorer of the respective nation is also a part of the list, however, it is not a direct answer to the query.',
 'Cristiano Ronaldo has the highest goals in the UEFA Champions League with 128 goals. He achieved this milestone throughout his career, starting from 2003 and playing for Manchester United, Real Madrid, and Juventus. As of February 1, 2020, his record remains unmatched in the competition.This information is relevant to the List of UEFA Champions League top scorers, which provides a comprehensive overview of the top goal scorers in the competition.',
 'Miroslav Klose has the highest goals in world football with a total of 16 goals scored in the finals of the FIFA World Cup. He achieved this record throughout his career spanning from 2002 to 2014. His impressive goal-scoring record earned him a place in the history of the FIFA World Cup.',
 'France has the highest number of own goals in favor of a team in one tournament, with 2 own goals in the 2014 and 2018 tournaments. France also holds the record for the most own goals in favor of a team overall, with 6 own goals. The team with the most own goals overall is Mexico, with 4 own goals.',
 "Miroslav Klose of Germany has the highest goals in world football with 16 goals, surpassing Ronaldo of Brazil's record of 15 goals. He achieved this milestone during the 2014 World Cup, specifically in the semi-final match against Brazil. This impressive feat earned him the top spot among all-time World Cup scorers."]

In [31]:
basic_ans="Ali Daei holds the record for the highest number of international goals with 109 goals for Iran, surpassing Ferenc Puskás' record of 84 goals. Cristiano Ronaldo has scored 1030 goals in his career, the highest among active players, with a total of 738 goals in his international career. Miroslav Klose holds the record for most World Cup goals with 16 goals, while Gerd Müller used to be the holder of that record from 1974 until it was broken by Ronaldo in 2006. Pelé scored 77 international goals, the highest among players from outside Europe, and Jürgen Klinsmann scored 11 goals in the World Cup, the highest among players from Germany. The top goalscorers in the World Cup history are Ali Daei, Cristiano Ronaldo, Ferenc Puskás, Kunishige Kamamoto, Godfrey Chitalu, Hussein Saeed, and Zainal Abidin, among others."

In [31]:
set_seed(24)
final_ans=total_answer(query, first_ans)
final_ans

'Ali Daei holds the record for the highest goals in world football with 109 international goals as of 2 December 2019. Josef Bican has the highest goals in world football with a total of 805 goals achieved between 1928 and 1955. However, Ali Daei of Iran holds the record for the highest goals in international football with 109 goals, surpassing Ferenc Puskás of Hungary who had held the record for 47 years. Christine Sinclair has the highest goals in world football among the listed players with 185 international goals, making her the top scorer.'

In [34]:
from evaluation import evaluate
scores=evaluate([final_ans], [row.to_dict()])
scores

Ali Daei holds the record for the highest goals in world football with 109 international goals as of 2 December 2019. Josef Bican has the highest goals in world football with a total of 805 goals achieved between 1928 and 1955. However, Ali Daei of Iran holds the record for the highest goals in international football with 109 goals, surpassing Ferenc Puskás of Hungary who had held the record for 47 years. Christine Sinclair has the highest goals in world football among the listed players with 185 international goals, making her the top scorer.
Who has the highest goals in world football?
["Who has the highest goals in men's world international football?", "Who has the highest goals all-time in men's football?", "Who has the highest goals in women's world international football?"]
[['Daei', 'Ali Daei'], ['Bican', 'Josef Bican'], ['Sinclair', 'Christine Sinclair']]
follow question : Who has the highest goals in men's world international football?
short answer : ['Daei', 'Ali Daei']
{'score': 0.278212308883667, 'start': 118, 'end': 129, 'answer': 'Josef Bican'}
follow question : Who has the highest goals all-time in men's football?
short answer : ['Bican', 'Josef Bican']
{'score': 0.0021326811984181404, 'start': 118, 'end': 129, 'answer': 'Josef Bican'}
follow question : Who has the highest goals in women's world international football?
short answer : ['Sinclair', 'Christine Sinclair']
{'score': 0.9738244414329529, 'start': 409, 'end': 427, 'answer': 'Christine Sinclair'}

{'rougeLsum': 48.484848484848484,
 'length': 94.0,
 'str_em': 100.0,
 'Disambig-F1': 66.66666666666666}

In [50]:
# scores_df.to_csv('./results/titleRAG_0218_results.csv', index=False)
import pandas as pd
import math
sf = pd.read_csv('results/titleRAG_0218_results.csv')
sf=sf[sf['length']<1000][:100]
print(len(sf))
print(sf.mean())
r=sf.mean()['rougeLsum']
d=sf.mean()['Disambig-F1']
dr=math.sqrt(r*d)
print(dr)

20
rougeLsum       34.604354
length         104.550000
str_em          54.166667
Disambig-F1     46.166667
dtype: float64
39.96958463256686

In [ ]:
import pandas as pd
import math
sf = pd.read_csv('results/basicRAG_seed24-len20-title_results.csv')
sf=sf[sf['length']<1000][:100]
print(len(sf))
print(sf.mean())
r=sf.mean()['rougeLsum']
d=sf.mean()['Disambig-F1']
dr=math.sqrt(r*d)
print(dr)

# Answer RAG

In [30]:
def hyde_query(query):
    prompt = """
    Create text that can answer the following question: Question: {0} Answer:
    """.format(query)
    input_ids = tokenizer_gen.apply_chat_template([{"role":'user', "content":prompt}], return_tensors='pt').to(device1)

    attention_mask = (input_ids != tokenizer_gen.pad_token_id).long().to(device1)

    out = model_gen.generate(input_ids, attention_mask=attention_mask, pad_token_id=tokenizer_gen.pad_token_id, max_new_tokens = 1024)
    res = tokenizer_gen.decode(out[0]).split('<|end_header_id|>')[-1] 
    return re.sub('\n|<\|eot_id\|>', '', res)

In [ ]:
docs=[]
for _ in range(1):
    docs.append(hyde_query("Who has the highet goals in world football?"))
docs

["The highest goals in world football are held by Brazilian legend, Pelé, who scored an impressive 772 goals in 891 appearances throughout his career. However, it's essential to note that the accuracy of Pelé's goals may be disputed due to the lack of official records from his early years.The player with the second-highest goals in world football is Argentine legend, Lionel Messi, who has scored over 770 goals in around 912 appearances. Messi's impressive goal-scoring record has earned him numerous accolades, including seven Ballon d'Or awards.Other notable players who have achieved high goal-scoring records include:- Josef Bican (Austria): 805 goals in 529 appearances- Ferenc Puskás (Hungary): 746 goals in 629 appearances- Gerd Müller (Germany): 735 goals in 706 appearances- Roberto Baggio (Italy): 707 goals in 758 appearances- Alfredo Di Stéfano (Argentina/Spain): 694 goals in 659 appearancesThese players have all achieved incredible feats in the world of football, and their records continue to inspire and motivate new generations of players and fans alike."]

In [34]:
def hyde_answer(ans):
    prompt = """
    Create a text that can ask questions in the following answers. Answer: {0} Question:
    """.format(ans)
    input_ids = tokenizer_gen.apply_chat_template([{"role":'user', "content":prompt}], return_tensors='pt').to(device1)

    attention_mask = (input_ids != tokenizer_gen.pad_token_id).long().to(device1)

    out = model_gen.generate(input_ids, attention_mask=attention_mask, pad_token_id=tokenizer_gen.pad_token_id, max_new_tokens = 1024)
    res = tokenizer_gen.decode(out[0]).split('<|end_header_id|>')[-1] 
    return re.sub('\n|<\|eot_id\|>', '', res)

In [35]:
res="Ali Daei holds the record for the highest number of international goals with 109 goals for Iran, surpassing Ferenc Puskás' record of 84 goals. Cristiano Ronaldo has scored 1030 goals in his career, the highest among active players, with a total of 738 goals in his international career. Miroslav Klose holds the record for most World Cup goals with 16 goals, while Gerd Müller used to be the holder of that record from 1974 until it was broken by Ronaldo in 2006. Pelé scored 77 international goals, the highest among players from outside Europe, and Jürgen Klinsmann scored 11 goals in the World Cup, the highest among players from Germany. The top goalscorers in the World Cup history are Ali Daei, Cristiano Ronaldo, Ferenc Puskás, Kunishige Kamamoto, Godfrey Chitalu, Hussein Saeed, and Zainal Abidin, among others."

In [36]:
ans=[]
for _ in range(1):
    ans.append(hyde_answer(res))
ans

["Here's a text with questions based on the given information:Football is a highly competitive sport, and records are often broken by new generations of players. Who holds the record for the highest number of international goals with 109 goals for Iran? Another notable record is held by Cristiano Ronaldo, who has scored a massive number of goals in his career. What is the total number of goals Cristiano Ronaldo has scored in his career? In the history of the World Cup, several players have stood out for their impressive goal-scoring skills. Who holds the record for most World Cup goals with 16 goals? Pelé is another football legend known for his incredible goal-scoring record. How many international goals did Pelé score? Some players have managed to break records that were previously held by other football legends. Who broke the record for most World Cup goals previously held by Gerd Müller? The top goalscorers in the World Cup history include many talented players from around the world. Who are some of the top goalscorers in the World Cup history, besides Ali Daei and Cristiano Ronaldo?"]

In [42]:
def query_rewriting(query):
    prompt = """
    You are an AI assistant that improves user queries by rewriting ambiguous questions into clear and precise ones. When a question is unclear due to ambiguity, missing key elements, vague pronouns, overly broad scope, or lack of context, refine the question while preserving its original intent. Follow these steps:

    Identify ambiguity: Determine whether the question has multiple interpretations, missing elements, vague references, excessive generalization, or lacks context.
    Clarify missing details: If necessary, infer plausible missing information or add context to make the question specific.
    Eliminate vague pronouns: Replace words like "this," "that," or "it" with explicit references.
    Narrow overly broad questions: Specify the scope or include examples to make the question more actionable.
    Maintain intent: Ensure that the rewritten question conveys the same fundamental purpose as the original one.
    
    Example Cases and Rewritten Versions:
    Original: "How can I fix this?"
    Rewritten: "How can I fix the network connectivity issue on my laptop?"
    Original: "Why did he do that?"
    Rewritten: "Why did the project manager decide to change the deadline?"
    Original: "Is this theory applicable in real life?"
    Rewritten: "Can reinforcement learning be effectively applied to real-world robotics?"
    Original: "What is AI?"
    Rewritten: "What are the core principles of artificial intelligence in machine learning?"
    
    Now, rewrite the following ambiguous question into a clearer, more specific one:
    User's Question: {0}
    Rewritten Question:
    Do not comment your answer and strictly follow this instructions.
    """.format(query)
    input_ids = tokenizer_gen.apply_chat_template([{"role":'user', "content":prompt}], return_tensors='pt').to(device1)

    attention_mask = (input_ids != tokenizer_gen.pad_token_id).long().to(device1)

    out = model_gen.generate(input_ids, attention_mask=attention_mask, pad_token_id=tokenizer_gen.pad_token_id, max_new_tokens = 1024)
    res = tokenizer_gen.decode(out[0]).split('<|end_header_id|>')[-1] 
    return re.sub('\n|<\|eot_id\|>', '', res)

In [43]:
ans=[]
for _ in range(5):
    ans.append(query_rewriting("who has the highet goals in world football?"))
ans

['Identify ambiguity: The question "who has the highest goals in world football" has multiple interpretations due to the ambiguity of "world football". It could refer to international football, domestic football leagues, or even a specific tournament.Clarify missing details: To make the question specific, we need to clarify the scope of "world football". Narrow overly broad questions: Let\'s assume the user is referring to international football. We\'ll also assume they\'re asking about the top scorer in the FIFA World Cup.Eliminate vague pronouns: No vague pronouns are present in this question.Maintain intent: The rewritten question conveys the same fundamental purpose as the original one: to find the top scorer in international football.Rewritten Question: "Who is the top scorer in the FIFA World Cup history?"',
 'Identify ambiguity: The question "who has the highest goals in world football" is ambiguous due to the lack of context and specificity. It\'s unclear whether the question refers to a specific time period, competition, or player category (e.g., all-time, current season, or a particular tournament).Clarify missing details: To make the question more specific, we can add context such as the time period, competition, or player category.Eliminate vague pronouns: There are no vague pronouns in this question.Narrow overly broad questions: To make the question more actionable, we can specify the scope or include examples.Maintain intent: The rewritten question should still convey the same fundamental purpose as the original one, which is to identify the player with the most goals in world football.Rewritten Question: "Who is the all-time leading goal scorer in the FIFA World Cup?"',
 'Identify ambiguity: The original question has multiple interpretations, including who has the highest goals in terms of skill level, goal-scoring ability, or other factors. It also lacks context, such as the time period or specific competitions considered.Clarify missing details: To make the question more specific, we need to clarify the scope and context. Let\'s assume we\'re looking at the highest goal-scoring ability in world football.Eliminate vague pronouns: There are no vague pronouns in the original question.Narrow overly broad questions: The original question is too broad and can be narrowed down by specifying the time period, such as "all-time" or "since 1990."Maintain intent: The rewritten question should convey the same fundamental purpose as the original one, which is to identify the top goal-scorers in world football.Rewritten Question: "Who are the top goal-scorers in world football since 1990?"',
 'Identify ambiguity: The question "who has the highest goals in world football" is ambiguous because it does not specify what it means by "highest goals." Are they referring to the most goals scored by a player in their career, the most goals scored by a team in a single season, or something else?Clarify missing details: To make the question more specific, let\'s assume they are referring to the player with the most goals scored in their career.Eliminate vague pronouns: There are no vague pronouns in this question, so this step is not necessary.Narrow overly broad questions: The question is still quite broad, as it asks about the "highest goals" in "world football." To make it more specific, let\'s focus on the top scorer in the history of the FIFA World Cup.Maintain intent: The rewritten question should still ask about the player with the most goals scored in their career, specifically in the context of the FIFA World Cup.Rewritten Question: Who is the top scorer in the history of the FIFA World Cup?',
 'Identify ambiguity: The original question is ambiguous due to its overly broad scope, as it asks about the "highest goals" in "world football", which can be interpreted in various ways, such as goals scored by a single player, goals scored by a team, or the number of goals scored in a particular tournament.Clarify missing details: To make the question more specific, we need to clarify what is meant by "highest goals". Let\'s assume the user is asking about the player who has scored the most goals in the history of football.Eliminate vague pronouns: There are no vague pronouns in the original question.Narrow overly broad questions: To make the question more actionable, let\'s specify that we are looking for the player with the most goals scored in the history of the FIFA World Cup.Maintain intent: The rewritten question conveys the same fundamental purpose as the original one, which is to identify the player with the most goals scored in football.Rewritten Question: "Who is the player with the most goals scored in the history of the FIFA World Cup?"']

In [37]:
from tqdm import tqdm
from evaluation import evaluate

set_seed(24)

stop_iteration = 20

scores_list=[]
retrival_list=[]
for idx, row in tqdm(qa_df.iterrows(), total=min([stop_iteration, len(qa_df)])):
    if idx == stop_iteration: break
    query = row['question']
    
    retrieved_docs, doc_ids = retrieve_documents(query)
    tmp1=0
    for doc_id in doc_ids:    
        tmp1+=match_sample_id(idx, doc_id)
    first_retrival=tmp1/len(retrieved_docs)
    print("First Retrival Match Rate:", first_retrival)
    
    dic=dict()
    dic['first_retrival']=first_retrival
    
    first_ans=total_answer(query,retrieved_docs)
    print('First ans:', first_ans)
    
    # hyde_ans_list=hyde(query,first_ans)
    # print(hyde_ans_list)
    
    virtual_ans=hyde_answer(first_ans)
    print(virtual_ans)
    
    ans_docs, doc_ids=retrieve_documents(virtual_ans)
    
    tmp2=0
    for doc_id in doc_ids:    
        tmp2+=match_sample_id(idx, doc_id)
    
    second_retrival=tmp2/len(ans_docs)
    print("Second Retrival Match Rate:", second_retrival)
    
    dic['second_retrival']=second_retrival
    
    final_ans=total_answer(query,ans_docs)
    print('Second ans:', final_ans)
    scores=evaluate([final_ans], [row.to_dict()])
    scores_list.append(scores)
    scores_df=pd.DataFrame(scores_list)
    print(scores)
    retrival_list.append(dic)
    retrival_df=pd.DataFrame(retrival_list)
    print(dic)
        
scores_df=pd.DataFrame(scores_list)
scores_df.mean()

retrival_df=pd.DataFrame(retrival_list)
retrival_df.mean()

  0%|          | 0/20 [00:00<?, ?it/s]/home/dataconv/.cache/huggingface/modules/transformers_modules/nvidia/NV-Embed-v2/5130cf1daf847c1bacee854a6ef1ca939e747fb2/modeling_nvembed.py:349: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'input_ids': torch.tensor(batch_dict.get('input_ids').to(batch_dict.get('input_ids')).long()),
/home/dataconv/anaconda3/envs/sf_rag_djk/lib/python3.10/contextlib.py:103: FutureWarning: `torch.backends.cuda.sdp_kernel()` is deprecated. In the future, this context manager will be removed. Please see `torch.nn.attention.sdpa_kernel()` for the new context manager, with updated signature.
  self.gen = func(*args, **kwds)

First Retrival Match Rate: 0.5
First ans: Ali Daei holds the record for the highest number of international goals with 109 goals for Iran, surpassing Ferenc Puskás' record of 84 goals. Cristiano Ronaldo has scored 1030 goals in his career, the highest among active players, with a total of 738 goals in his international career. Miroslav Klose holds the record for most World Cup goals with 16 goals, while Gerd Müller used to be the holder of that record from 1974 until it was broken by Ronaldo in 2006. Pelé scored 77 international goals, the highest among players from outside Europe, and Jürgen Klinsmann scored 11 goals in the World Cup, the highest among players from Germany. The top goalscorers in the World Cup history are Ali Daei, Cristiano Ronaldo, Ferenc Puskás, Kunishige Kamamoto, Godfrey Chitalu, Hussein Saeed, and Zainal Abidin, among others.
Here's a text asking questions related to the information provided:In the world of football, several records have been set by talented players. One player holds the record for the highest number of international goals, but who is it? This record was previously held by another player, who scored 84 goals. Which active player has scored the highest number of goals in his career, with a total of 738 goals in international matches?Some players have also excelled in the World Cup, with one player holding the record for most World Cup goals. This record was previously held by another player, who held it for over 30 years before being broken. Who are the top goalscorers in the World Cup history? In addition to these records, some players have achieved great success in international matches, with one player scoring the highest number of goals among players from outside Europe. Who is this player, and how many goals did he score? Another player, who is a legend from Germany, scored the highest number of goals in the World Cup among his countrymen. Who is this player, and how many goals did he score?
Second Retrival Match Rate: 0.3
Second ans: Ali Daei of Iran holds the record for the highest goals in international football with 109 goals, surpassing Ferenc Puskás' record of 84 goals. He achieved this feat after scoring his 50th goal in a friendly match against Mexico on 9 January 2000, becoming the first Asian footballer to achieve the feat. Ali Daei is the only player to score over 100 goals in international football with 109 goals, and his 100th goal came on 17 November 2004, when he scored a hat-trick (in this case four goals) against Laos in the 2006 FIFA World Cup qualification. However, Pelé of Brazil is the first player from outside Europe and the first player from South America to score at least 50 goals, with a total of 77 international goals in 92 matches. Pelé is also the highest international goalscorer for Brazil, and he has won three World Cup winners' medals, although he did not play in the 1962 final due to injury.
Ali Daei of Iran holds the record for the highest goals in international football with 109 goals, surpassing Ferenc Puskás' record of 84 goals. He achieved this feat after scoring his 50th goal in a friendly match against Mexico on 9 January 2000, becoming the first Asian footballer to achieve the feat. Ali Daei is the only player to score over 100 goals in international football with 109 goals, and his 100th goal came on 17 November 2004, when he scored a hat-trick (in this case four goals) against Laos in the 2006 FIFA World Cup qualification. However, Pelé of Brazil is the first player from outside Europe and the first player from South America to score at least 50 goals, with a total of 77 international goals in 92 matches. Pelé is also the highest international goalscorer for Brazil, and he has won three World Cup winners' medals, although he did not play in the 1962 final due to injury.
Who has the highest goals in world football?
["Who has the highest goals in men's world international football?", "Who has the highest goals all-time in men's football?", "Who has the highest goals in women's world international football?"]
[['Daei', 'Ali Daei'], ['Bican', 'Josef Bican'], ['Sinclair', 'Christine Sinclair']]

  5%|▌         | 1/20 [00:36<11:31, 36.38s/it]

follow question : Who has the highest goals in men's world international football?
short answer : ['Daei', 'Ali Daei']
{'score': 0.5171696543693542, 'start': 0, 'end': 8, 'answer': 'Ali Daei'}
follow question : Who has the highest goals all-time in men's football?
short answer : ['Bican', 'Josef Bican']
{'score': 0.24958856403827667, 'start': 0, 'end': 8, 'answer': 'Ali Daei'}
follow question : Who has the highest goals in women's world international football?
short answer : ['Sinclair', 'Christine Sinclair']
{'score': 0.0008715770090930164, 'start': 0, 'end': 8, 'answer': 'Ali Daei'}
{'rougeLsum': 31.57894736842105, 'length': 161.0, 'str_em': 33.33333333333333, 'Disambig-F1': 33.33333333333333}
{'first_retrival': 0.5, 'second_retrival': 0.3}
First Retrival Match Rate: 1.0
First ans: The original artist of "Sound of Silence" is Simon & Garfunkel, an American music duo composed of Paul Simon and Art Garfunkel. The song was written by Paul Simon and was first released on their debut album "Wednesday Morning, 3 A.M." in 1964. The song gained popularity after it was re-released with electric overdubs in 1965, and it became a hit single, reaching number one on the Billboard Hot 100 chart in January 1966. Simon & Garfunkel's version of "Sound of Silence" is considered a classic folk rock song and has been added to the National Recording Registry in the Library of Congress.
Here's a text that asks questions about the original artist and song details of "The Sound of Silence":The song "The Sound of Silence" is a classic hit from the American music duo Simon & Garfunkel. But, do you know which member of the duo actually wrote the song?The song was first released on their debut album "Wednesday Morning, 3 A.M." in 1964, but it wasn't until the electric overdubs were added that it gained popularity. What was the result of this re-release, and how did the song perform on the Billboard Hot 100 chart?Simon & Garfunkel's version of "The Sound of Silence" is considered a masterpiece of folk rock music and has been recognized by the Library of Congress. Can you guess which year the song was added to the National Recording Registry?The song's success can be attributed to the unique blend of Paul Simon's and Art Garfunkel's harmonies, which created a distinctive sound. Which member of the duo is credited with writing the song, and what is the name of their debut album?
Second Retrival Match Rate: 1.0
Second ans: The original artist of "The Sound of Silence" is Simon & Garfunkel, an American music duo composed of Paul Simon and Art Garfunkel. They recorded the song in March 1964, and it was released on their debut album "Wednesday Morning, 3 A.M." in October 1964. The song was later remixed and released as a single in September 1965, which became a huge success and reached number one on the Billboard Hot 100 chart. Paul Simon is credited as the primary songwriter of the song, with Art Garfunkel providing vocals. The song's success led to the duo's reunion and the creation of their second album, "Sounds of Silence".
The original artist of "The Sound of Silence" is Simon & Garfunkel, an American music duo composed of Paul Simon and Art Garfunkel. They recorded the song in March 1964, and it was released on their debut album "Wednesday Morning, 3 A.M." in October 1964. The song was later remixed and released as a single in September 1965, which became a huge success and reached number one on the Billboard Hot 100 chart. Paul Simon is credited as the primary songwriter of the song, with Art Garfunkel providing vocals. The song's success led to the duo's reunion and the creation of their second album, "Sounds of Silence".
Who is the original artist of sound of silence?
['Who is the original artist of sound of silence, the song, released in 1964?', 'Who is the original artist of sound of silence, the album?', 'Who is the original artist of sound of silence, the song, released in 2016?']
[['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon'], ['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon'], ['Dami Im']]

 10%|█         | 2/20 [01:04<09:27, 31.51s/it]

follow question : Who is the original artist of sound of silence, the song, released in 1964?
short answer : ['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon']
{'score': 0.8518556356430054, 'start': 49, 'end': 66, 'answer': 'Simon & Garfunkel'}
follow question : Who is the original artist of sound of silence, the album?
short answer : ['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon']
{'score': 0.8871653079986572, 'start': 49, 'end': 66, 'answer': 'Simon & Garfunkel'}
follow question : Who is the original artist of sound of silence, the song, released in 2016?
short answer : ['Dami Im']
{'score': 1.6793939721537754e-05, 'start': 49, 'end': 66, 'answer': 'Simon & Garfunkel'}
{'rougeLsum': 40.96385542168675, 'length': 107.0, 'str_em': 66.66666666666666, 'Disambig-F1': 66.66666666666666}
{'first_retrival': 1.0, 'second_retrival': 1.0}
First Retrival Match Rate: 0.9
First ans: The first Apple iPhone was conceived in 2005, and its development cost was estimated to be $150 million over a thirty-month period. The original iPhone was introduced by Steve Jobs on January 9, 2007, at the Macworld Conference & Expo. The iPhone was released in the United States on June 29, 2007, and was initially available in 4 GB and 8 GB models. The first-generation iPhone was discontinued on July 15, 2008, and was succeeded by the iPhone 3G. The first iPhone was a revolutionary device that combined a mobile phone, an iPod, and an internet communications device into one product.
Here's a text that can ask questions related to the information provided about the first Apple iPhone:The Apple iPhone has been a groundbreaking device since its conception in 2005. Its development cost was estimated to be $150 million over a thirty-month period. What was the name of the person who introduced the iPhone to the public?A) Steve JobsB) Tim CookC) Jony IveD) Phil SchillerThe correct answer is A) Steve Jobs. He introduced the iPhone on January 9, 2007, at the Macworld Conference & Expo.
Second Retrival Match Rate: 0.9
Second ans: The first iPhone was conceived in 2005 by Steve Jobs, and its development began in that year. The iPhone was officially announced on January 9, 2007, and was released to the public on June 29, 2007. Apple created the device during a secretive collaboration with Cingular Wireless, and the development cost was estimated to be $150 million over a thirty-month period. The iPhone was initially available in the US, UK, Canada, Germany, Norway, Sweden, Finland, France, Spain, Italy, and South Africa, and its release was highly anticipated, with thousands of people waiting outside Apple and AT&T retail stores days before the device's launch.
The first iPhone was conceived in 2005 by Steve Jobs, and its development began in that year. The iPhone was officially announced on January 9, 2007, and was released to the public on June 29, 2007. Apple created the device during a secretive collaboration with Cingular Wireless, and the development cost was estimated to be $150 million over a thirty-month period. The iPhone was initially available in the US, UK, Canada, Germany, Norway, Sweden, Finland, France, Spain, Italy, and South Africa, and its release was highly anticipated, with thousands of people waiting outside Apple and AT&T retail stores days before the device's launch.
When was the first apple i phone made?
['When was the first apple i phone released?', 'When was the first apple i phone for beta testing made?', 'When was the first apple i phone 1 made?', 'When was the first apple i phone beta made?']
[['June 29, 2007'], ['2004'], ['June 29, 2007.'], ['2004.']]

 15%|█▌        | 3/20 [01:27<07:47, 27.52s/it]

follow question : When was the first apple i phone released?
short answer : ['June 29, 2007']
{'score': 0.16785547137260437, 'start': 184, 'end': 197, 'answer': 'June 29, 2007'}
follow question : When was the first apple i phone for beta testing made?
short answer : ['2004']
{'score': 0.1579633206129074, 'start': 34, 'end': 38, 'answer': '2005'}
follow question : When was the first apple i phone 1 made?
short answer : ['June 29, 2007.']
{'score': 0.7774783968925476, 'start': 34, 'end': 38, 'answer': '2005'}
follow question : When was the first apple i phone beta made?
short answer : ['2004.']
{'score': 0.013913760893046856, 'start': 184, 'end': 197, 'answer': 'June 29, 2007'}
{'rougeLsum': 36.04651162790697, 'length': 103.0, 'str_em': 50.0, 'Disambig-F1': 25.0}
{'first_retrival': 0.9, 'second_retrival': 0.9}
First Retrival Match Rate: 0.9
First ans: The Weasley brothers, Bill, Charlie, Fred, and George, were played by Richard Fish, Alex Crockford, James Phelps, and Oliver Phelps, respectively. James and Oliver Phelps portrayed the twins Fred and George Weasley in the film series. Richard Fish played Bill Weasley briefly in the film adaptation of Harry Potter and the Prisoner of Azkaban. Alex Crockford also played Charlie Weasley in the same film.
Here are some questions based on the provided answers:1. Which actors played the Weasley brothers in the Harry Potter film series?   a) Richard Fish, Alex Crockford, James Phelps, and Oliver Phelps   b) Richard Fish, Alex Crockford, James Phelps, and Rupert Grint   c) Richard Fish, Alex Crockford, James Phelps, and Daniel Radcliffe   d) Richard Fish, Alex Crockford, James Phelps, and Tom FeltonAnswer: a) Richard Fish, Alex Crockford, James Phelps, and Oliver Phelps2. Who played the roles of Fred and George Weasley in the film series?   a) James and Oliver Phelps   b) Richard and Alex Crockford   c) Rupert and Tom Felton   d) Daniel and James PhelpsAnswer: a) James and Oliver Phelps3. Which actor played the role of Bill Weasley in the film adaptation of Harry Potter and the Prisoner of Azkaban?   a) Richard Fish   b) Alex Crockford   c) James Phelps   d) Oliver PhelpsAnswer: a) Richard Fish4. Who played the role of Charlie Weasley in the film adaptation of Harry Potter and the Prisoner of Azkaban?   a) Richard Fish   b) Alex Crockford   c) James Phelps   d) Oliver PhelpsAnswer: b) Alex Crockford
Second Retrival Match Rate: 1.0
Second ans: The Weasley brothers were portrayed by the Phelps twins, James and Oliver, who played the roles of Fred and George Weasley respectively. They appeared in all eight films of the series, starting from the first film, "Harry Potter and the Philosopher's Stone" in 2001. The twins' performances as the mischievous and comedic Weasley twins were well-received by audiences and critics alike. Richard Griffiths, who played the role of Vernon Dursley, also had a notable appearance in the first film as the father of the Dursley children, where he interacted with the Weasley brothers. The Weasley family was a significant part of the Harry Potter series, and the Phelps twins' performances were an integral part of that.
The Weasley brothers were portrayed by the Phelps twins, James and Oliver, who played the roles of Fred and George Weasley respectively. They appeared in all eight films of the series, starting from the first film, "Harry Potter and the Philosopher's Stone" in 2001. The twins' performances as the mischievous and comedic Weasley twins were well-received by audiences and critics alike. Richard Griffiths, who played the role of Vernon Dursley, also had a notable appearance in the first film as the father of the Dursley children, where he interacted with the Weasley brothers. The Weasley family was a significant part of the Harry Potter series, and the Phelps twins' performances were an integral part of that.
Who played the weasley brothers in harry potter?
['Who played  Bill weasley in Harry Potter and the Prisoner of Azkaban?', 'Who played percy weasley in harry potter?', 'Who played fred weasley in harry potter?', 'Who played ron weasley in harry potter?', 'Who played george weasley in harry potter?', 'Who played  Bill weasley in harry potter (2001-2011)?']
[['Richard Fish'], ['Chris Rankin'], ['James Phelps'], ['Rupert Grint'], ['Oliver Phelps'], ['Domhnall Gleeson']]

 20%|██        | 4/20 [01:56<07:33, 28.36s/it]

follow question : Who played  Bill weasley in Harry Potter and the Prisoner of Azkaban?
short answer : ['Richard Fish']
{'score': 0.00014068240125197917, 'start': 43, 'end': 55, 'answer': 'Phelps twins'}
follow question : Who played percy weasley in harry potter?
short answer : ['Chris Rankin']
{'score': 0.15339699387550354, 'start': 43, 'end': 55, 'answer': 'Phelps twins'}
follow question : Who played fred weasley in harry potter?
short answer : ['James Phelps']
{'score': 0.14391471445560455, 'start': 43, 'end': 55, 'answer': 'Phelps twins'}
follow question : Who played ron weasley in harry potter?
short answer : ['Rupert Grint']
{'score': 0.14792980253696442, 'start': 43, 'end': 55, 'answer': 'Phelps twins'}
follow question : Who played george weasley in harry potter?
short answer : ['Oliver Phelps']
{'score': 0.29493001103401184, 'start': 43, 'end': 55, 'answer': 'Phelps twins'}
follow question : Who played  Bill weasley in harry potter (2001-2011)?
short answer : ['Domhnall Gleeson']
{'score': 0.001827951637096703, 'start': 43, 'end': 55, 'answer': 'Phelps twins'}
{'rougeLsum': 39.81481481481482, 'length': 116.0, 'str_em': 0.0, 'Disambig-F1': 16.666666666666664}
{'first_retrival': 0.9, 'second_retrival': 1.0}
First Retrival Match Rate: 0.4
First ans: There are 38 state parks in Virginia, according to the information provided. However, this number may not include all state parks, as some parks are listed as "Closed" or "Under construction". The list of state parks in Virginia includes parks such as Shenandoah River Raymond R. "Andy" Guest Jr. State Park, Shot Tower Historical State Park, and Sky Meadows State Park, among others. Some state parks are listed as having a specific size, such as Douthat State Park with 4,545 acres, and Fairy Stone State Park with 4,678 acres. The list also includes information on parks that are currently closed or under construction, such as Seven Bends State Park and Middle Peninsula State Park.
Here's a text that can be used to ask questions based on the provided information:Virginia is known for its beautiful state parks, but how many are there in total? According to the information, there are 38 state parks in Virginia, but this number may not be exhaustive as some parks are listed as "Closed" or "Under construction". Some notable state parks in Virginia include Shenandoah River Raymond R. "Andy" Guest Jr. State Park, Shot Tower Historical State Park, and Sky Meadows State Park. The size of these parks also varies, with some covering a significant amount of land. For example, Douthat State Park spans an impressive 4,545 acres, while Fairy Stone State Park covers 4,678 acres. However, some parks are not currently accessible due to being closed or under construction. What are some examples of these parks, and what are the reasons behind their closure?
Second Retrival Match Rate: 0.4
Second ans: There are 38 state parks in Virginia, according to the document "List of Virginia state parks/State parks". This number includes parks such as Shenandoah River Raymond R. "Andy" Guest Jr. State Park, which has 1,704 acres, and other parks like First Landing State Park, which is the oldest park in the system, established in 1933. However, the total number of parks in Virginia is not explicitly stated in the provided documents. The document "Dallas/Parks and recreation" does not provide information on state parks in Virginia.
There are 38 state parks in Virginia, according to the document "List of Virginia state parks/State parks". This number includes parks such as Shenandoah River Raymond R. "Andy" Guest Jr. State Park, which has 1,704 acres, and other parks like First Landing State Park, which is the oldest park in the system, established in 1933. However, the total number of parks in Virginia is not explicitly stated in the provided documents. The document "Dallas/Parks and recreation" does not provide information on state parks in Virginia.
How many state parks are there in virginia?
['How many state parks are there in virginia in 1936?', 'How many state parks are there in virginia in 2016?', 'How many state parks were there when the state park system formed in Virginia?', 'How many state parks were there in Virginia as of 2016?']
[['six'], ['38'], ['6'], ['38']]

 25%|██▌       | 5/20 [02:21<06:44, 26.97s/it]

follow question : How many state parks are there in virginia in 1936?
short answer : ['six']
{'score': 0.00025877999723888934, 'start': 10, 'end': 12, 'answer': '38'}
follow question : How many state parks are there in virginia in 2016?
short answer : ['38']
{'score': 0.5062050223350525, 'start': 10, 'end': 12, 'answer': '38'}
follow question : How many state parks were there when the state park system formed in Virginia?
short answer : ['6']
{'score': 0.7399467825889587, 'start': 10, 'end': 12, 'answer': '38'}
follow question : How many state parks were there in Virginia as of 2016?
short answer : ['38']
{'score': 0.2952701449394226, 'start': 10, 'end': 12, 'answer': '38'}
{'rougeLsum': 33.54037267080745, 'length': 85.0, 'str_em': 50.0, 'Disambig-F1': 50.0}
{'first_retrival': 0.4, 'second_retrival': 0.4}
First Retrival Match Rate: 0.5
First ans: The 2018 UEFA Champions League Final featured several performances, including the opening ceremony with English singer Dua Lipa and Jamaican rapper Sean Paul, and the UEFA Champions League Anthem performed by Slovenian–Croatian cello duo 2Cellos. The annual UEFA Champions Festival was also held between 24–27 May 2018 at the Kiev city centre. In the match itself, the teams did not have any specific halftime show performances. However, the UEFA Champions League Anthem was played before each match, including the final, as the teams were lined up. The anthem's chorus is played before each match, as well as at the beginning and end of television broadcasts of the matches.
What pre-match and halftime performances were featured in the 2018 UEFA Champions League Final?
Second Retrival Match Rate: 0.3
Second ans: The UEFA Champions League anthem was performed by Slovenian–Croatian cello duo 2Cellos at the 2018 UEFA Champions League Final. English singer Dua Lipa performed at the opening ceremony preceding the final. The match began with the teams lining up to the Champions League anthem, which is played before each UEFA Champions League game. The anthem's chorus contains the three official languages used by UEFA: English, German, and French. The complete anthem is about three minutes long, and has two short verses and the chorus.
The UEFA Champions League anthem was performed by Slovenian–Croatian cello duo 2Cellos at the 2018 UEFA Champions League Final. English singer Dua Lipa performed at the opening ceremony preceding the final. The match began with the teams lining up to the Champions League anthem, which is played before each UEFA Champions League game. The anthem's chorus contains the three official languages used by UEFA: English, German, and French. The complete anthem is about three minutes long, and has two short verses and the chorus.
Who performed at the champions league final 2018?
['Who are the teams that performed in competition at the champions league final 2018?', 'Who performed best at the champions league final 2018, winning man of the match?', 'Who performed at the opening ceremony of the champions league final 2018?', 'Who performed the anthem at the champions league final 2018?']
[['Real Madrid and Liverpool', 'Liverpool', 'Real Madrid'], ['Gareth Bale', 'Bale'], ['Dua Lipa', 'Sean Paul', 'Dua Lipa and Sean Paul'], ['2Cellos', 'Luka Šulić and Stjepan Hauser', 'Luka Šulić', '2CΞLLOS', 'Stjepan Hauser']]

 30%|███       | 6/20 [02:37<05:26, 23.32s/it]

follow question : Who are the teams that performed in competition at the champions league final 2018?
short answer : ['Real Madrid and Liverpool', 'Liverpool', 'Real Madrid']
{'score': 0.05167701095342636, 'start': 50, 'end': 86, 'answer': 'Slovenian–Croatian cello duo 2Cellos'}
follow question : Who performed best at the champions league final 2018, winning man of the match?
short answer : ['Gareth Bale', 'Bale']
{'score': 0.1988331377506256, 'start': 143, 'end': 151, 'answer': 'Dua Lipa'}
follow question : Who performed at the opening ceremony of the champions league final 2018?
short answer : ['Dua Lipa', 'Sean Paul', 'Dua Lipa and Sean Paul']
{'score': 0.6913731098175049, 'start': 143, 'end': 151, 'answer': 'Dua Lipa'}
follow question : Who performed the anthem at the champions league final 2018?
short answer : ['2Cellos', 'Luka Šulić and Stjepan Hauser', 'Luka Šulić', '2CΞLLOS', 'Stjepan Hauser']
{'score': 0.9441965222358704, 'start': 79, 'end': 86, 'answer': '2Cellos'}
{'rougeLsum': 48.554913294797686, 'length': 84.0, 'str_em': 50.0, 'Disambig-F1': 50.0}
{'first_retrival': 0.5, 'second_retrival': 0.3}
First Retrival Match Rate: 0.3
First ans: Harlan, a stranger Thelma met at a roadhouse bar, killed the man in the parking lot after Thelma resisted his advances and Louise threatened him with a gun. Harlan's death was a result of Louise's actions, and she was left shaken and fearful of being caught. The incident sparked a chain of events that led Thelma and Louise to flee and go on the run. Harlan's death was a pivotal moment in the film, marking a turning point in the relationship between Thelma and Louise. In the film's context, Harlan's death is a catalyst for the events that unfold, leading to a series of unfortunate consequences for the two women.
Here's a text that can ask questions in the following answers:The incident that sparked the chain of events in the lives of Thelma and Louise occurred when Harlan, a stranger Thelma met at a roadhouse bar, made unwanted advances towards her. How did Harlan's actions affect Thelma and Louise?A) They went to the police station to report the incidentB) Harlan killed the man in the parking lot after Thelma resisted his advances and Louise threatened him with a gunC) They laughed it off and continued their night outD) They decided to confront Harlan about his behaviorWhat was the outcome of Harlan's actions towards Thelma and Louise?A) They were left unharmed and continued their eveningB) Harlan was arrested and charged with harassmentC) Harlan's death was a result of Louise's actions, and she was left shaken and fearful of being caughtD) Harlan's actions sparked a romantic relationship between Thelma and LouiseHow did Harlan's death affect the lives of Thelma and Louise?A) It marked the end of their friendship and the beginning of their separate livesB) It was a turning point in their relationship, marking the beginning of their adventure togetherC) It was a catalyst for the events that unfold, leading to a series of unfortunate consequences for the two womenD) It was a minor incident that didn't affect their lives at allWhat was the significance of Harlan's death in the film?A) It was a pivotal moment in the film, marking a turning point in the relationship between Thelma and LouiseB) It was a minor incident that didn't affect the plot of the filmC) It was a symbol of the male-dominated society and the oppression of womenD) It was a representation of the destructive power of love and relationships
Second Retrival Match Rate: 0.3
Second ans: Harlan was killed by Louise after he attempted to rape Thelma. Harlan's death was a pivotal moment in the film, leading Thelma and Louise to go on the run. In the film's climax, Thelma and Louise are cornered by the authorities and, rather than surrender, they choose to drive off a cliff, killing themselves. However, in the context of the film's original plot, Harlan's death is the inciting incident that sets the story in motion.
Harlan was killed by Louise after he attempted to rape Thelma. Harlan's death was a pivotal moment in the film, leading Thelma and Louise to go on the run. In the film's climax, Thelma and Louise are cornered by the authorities and, rather than surrender, they choose to drive off a cliff, killing themselves. However, in the context of the film's original plot, Harlan's death is the inciting incident that sets the story in motion.
Who killed the man in thelma and louise?
['Which character killed the man in thelma and louise?', 'Which actor killed the man in thelma and louise?', 'Who is the character that kills Harlan in the film Thelma and Louise?', 'Who is the actor of the character that killed a man in the film Thelma and Louise?']
[['Louise Elizabeth Sawyer', 'Louise'], ['Susan Sarandon', 'Susan Abigail Sarandon'], ['Louise Elizabeth Sawyer', 'Louise'], ['Susan Sarandon']]

 35%|███▌      | 7/20 [03:12<05:50, 26.94s/it]

follow question : Which character killed the man in thelma and louise?
short answer : ['Louise Elizabeth Sawyer', 'Louise']
{'score': 0.6373345851898193, 'start': 0, 'end': 6, 'answer': 'Harlan'}
follow question : Which actor killed the man in thelma and louise?
short answer : ['Susan Sarandon', 'Susan Abigail Sarandon']
{'score': 0.5534887313842773, 'start': 0, 'end': 6, 'answer': 'Harlan'}
follow question : Who is the character that kills Harlan in the film Thelma and Louise?
short answer : ['Louise Elizabeth Sawyer', 'Louise']
{'score': 0.7995679378509521, 'start': 21, 'end': 27, 'answer': 'Louise'}
follow question : Who is the actor of the character that killed a man in the film Thelma and Louise?
short answer : ['Susan Sarandon']
{'score': 0.5156844258308411, 'start': 0, 'end': 6, 'answer': 'Harlan'}
{'rougeLsum': 27.142857142857142, 'length': 75.0, 'str_em': 50.0, 'Disambig-F1': 25.0}
{'first_retrival': 0.3, 'second_retrival': 0.3}
First Retrival Match Rate: 0.9
First ans: Charlie Kelly is a main character in the TV show "It's Always Sunny in Philadelphia" and is played by actor Charlie Day. Charlie Kelly is a former co-owner of Paddy's Pub and a childhood friend of Mac and Dennis, and is known for his illiteracy, alcoholism, and various psychological problems. Charlie Kelly is also the janitor at the pub and is often referred to as the one who does the "Charlie work". The character of Charlie Kelly is a central figure in the show's dark humor and absurdity, and is often the source of chaos and conflict. Charlie Day is the actor who brings this complex and eccentric character to life.
Here's a text that can ask questions in the following answers:**It's Always Sunny in Philadelphia**Charlie Kelly is a main character in the TV show "It's Always Sunny in Philadelphia" and is played by actor Charlie Day. Charlie Kelly is a former co-owner of Paddy's Pub and a childhood friend of Mac and Dennis, and is known for his illiteracy, alcoholism, and various psychological problems. Charlie Kelly is also the janitor at the pub and is often referred to as the one who does the "Charlie work". The character of Charlie Kelly is a central figure in the show's dark humor and absurdity, and is often the source of chaos and conflict. Charlie Day is the actor who brings this complex and eccentric character to life.**About Charlie Kelly**1. What is Charlie Kelly's role in the TV show "It's Always Sunny in Philadelphia"?Answer: Charlie Kelly is a main character in the TV show "It's Always Sunny in Philadelphia"2. Who plays the role of Charlie Kelly in the TV show "It's Always Sunny in Philadelphia"?Answer: Charlie Day3. What is Charlie Kelly's relationship with Mac and Dennis?Answer: Charlie Kelly is a childhood friend of Mac and Dennis4. What are some of Charlie Kelly's notable characteristics?Answer: Charlie Kelly is known for his illiteracy, alcoholism, and various psychological problems5. What is Charlie Kelly's job at Paddy's Pub?Answer: Charlie Kelly is the janitor at the pub6. What is the term used to describe Charlie Kelly's contributions to the pub?Answer: The term used to describe Charlie Kelly's contributions is "Charlie work"7. What is Charlie Kelly's impact on the show?Answer: The character of Charlie Kelly is a central figure in the show's dark humor and absurdity, and is often the source of chaos and conflict
Second Retrival Match Rate: 0.9
Second ans: Charlie Kelly is a main character in the FX television series It's Always Sunny in Philadelphia, and he is played by actor Charlie Day. Charlie Kelly is a former co-owner at Paddy's Pub and a childhood friend of Mac and Dennis, and he is known for his illiteracy, alcoholism, and various psychological problems. Charlie Kelly is a key member of "The Gang" and is often involved in the group's schemes and misadventures. Charlie Kelly's character is portrayed as a wild card, with his intentions often being pure but his plans frequently ending in chaos. Charlie Kelly is a central character in the show and has appeared in many episodes throughout its run.
Charlie Kelly is a main character in the FX television series It's Always Sunny in Philadelphia, and he is played by actor Charlie Day. Charlie Kelly is a former co-owner at Paddy's Pub and a childhood friend of Mac and Dennis, and he is known for his illiteracy, alcoholism, and various psychological problems. Charlie Kelly is a key member of "The Gang" and is often involved in the group's schemes and misadventures. Charlie Kelly's character is portrayed as a wild card, with his intentions often being pure but his plans frequently ending in chaos. Charlie Kelly is a central character in the show and has appeared in many episodes throughout its run.
Who plays charlie on it's always sunny?
["Who does Charlie Day play on It's Always Sunny in Philadelphia?", "Who plays Charlie Kelly on It's Always Sunny in Philadelphia?"]
[['Charlie Kelly'], ['Charlie Day']]

 40%|████      | 8/20 [03:46<05:51, 29.32s/it]

follow question : Who does Charlie Day play on It's Always Sunny in Philadelphia?
short answer : ['Charlie Kelly']
{'score': 0.9654441475868225, 'start': 0, 'end': 13, 'answer': 'Charlie Kelly'}
follow question : Who plays Charlie Kelly on It's Always Sunny in Philadelphia?
short answer : ['Charlie Day']
{'score': 0.983471155166626, 'start': 123, 'end': 134, 'answer': 'Charlie Day'}
{'rougeLsum': 31.3953488372093, 'length': 112.0, 'str_em': 100.0, 'Disambig-F1': 100.0}
{'first_retrival': 0.9, 'second_retrival': 0.9}
First Retrival Match Rate: 0.4
First ans: The Los Angeles Lakers have won the NBA Finals a total of 16 times, with their first championship in 1949 and their most recent in 2010. They have appeared in the NBA Finals a total of 31 times, making them one of the most successful teams in NBA history. The Lakers have won championships in Minneapolis (5) and Los Angeles (11), with their most successful period being the 1980s under the leadership of Magic Johnson and the 2000s under the leadership of Kobe Bryant and Shaquille O'Neal. The team's 16 championships trail only the Boston Celtics' 17 championships.
Here's a text with questions based on the information provided:The Los Angeles Lakers have a rich history of success in the NBA, with 16 championship titles under their belt. This impressive record trails only the Boston Celtics' 17 championships, but it's still an incredible achievement. They've won championships in two different cities, Minneapolis and Los Angeles, with a total of 16 titles. Here are some questions about the Lakers' history:- When did the Lakers win their first NBA championship?- How many championships did the Lakers win in the 1980s under Magic Johnson's leadership?- Which two cities have the Lakers won championships in?- Who led the Lakers to success in the 2000s?- How many championships do the Lakers have in total?- How many championships do the Lakers have in Los Angeles?- How many championships do the Lakers have in Minneapolis?- What year did the Lakers win their most recent NBA championship?- How many times have the Lakers appeared in the NBA Finals?- Who leads the league in championships with the Lakers?
Second Retrival Match Rate: 0.5
Second ans: The Los Angeles Lakers have won the NBA Finals 16 times, with their first championship in Minneapolis in 1949 and their most recent in 2010. They have appeared in the NBA Finals a total of 31 times, with their most successful period being the 1980s, where they won five championships in a nine-year span. The Lakers have also won the Finals in the following years: 1950, 1952, 1953, 1954, 1972, 1980, 1982, 1985, 1987, 1988, 2000, 2001, 2002, 2009, and 2010. They have a long-standing rivalry with the Boston Celtics, with whom they have met a record 12 times in the NBA Finals. The Lakers' 16 championships are second only to the Boston Celtics' 17 championships in the NBA.
The Los Angeles Lakers have won the NBA Finals 16 times, with their first championship in Minneapolis in 1949 and their most recent in 2010. They have appeared in the NBA Finals a total of 31 times, with their most successful period being the 1980s, where they won five championships in a nine-year span. The Lakers have also won the Finals in the following years: 1950, 1952, 1953, 1954, 1972, 1980, 1982, 1985, 1987, 1988, 2000, 2001, 2002, 2009, and 2010. They have a long-standing rivalry with the Boston Celtics, with whom they have met a record 12 times in the NBA Finals. The Lakers' 16 championships are second only to the Boston Celtics' 17 championships in the NBA.
How many times have the lakers won the finals?
['As of 2017, how many times have the lakers won the finals?', 'As of 2016, how many times have the Lakers won the finals?', 'As of 2015, how many times have the Lakers won the finals?']
[['16'], ['16'], ['16']]

 45%|████▌     | 9/20 [04:15<05:22, 29.31s/it]

follow question : As of 2017, how many times have the lakers won the finals?
short answer : ['16']
{'score': 0.511303186416626, 'start': 47, 'end': 49, 'answer': '16'}
follow question : As of 2016, how many times have the Lakers won the finals?
short answer : ['16']
{'score': 0.6982125043869019, 'start': 47, 'end': 49, 'answer': '16'}
follow question : As of 2015, how many times have the Lakers won the finals?
short answer : ['16']
{'score': 0.3959483206272125, 'start': 47, 'end': 49, 'answer': '16'}
{'rougeLsum': 33.93939393939394, 'length': 119.0, 'str_em': 100.0, 'Disambig-F1': 100.0}
{'first_retrival': 0.4, 'second_retrival': 0.5}
First Retrival Match Rate: 0.7
First ans: The Indian National Congress is in power in six legislative assemblies: Punjab, Rajasthan, Chhattisgarh, Madhya Pradesh, Maharashtra (as part of the Maha Vikas Aghadi), and the union territory of Puducherry (in an alliance with DMK). The party is also in power in seven legislative assemblies as of July 2019: Punjab, Rajasthan, Chhattisgarh, Madhya Pradesh, Maharashtra, Puducherry, and Jharkhand. In total, the party is in power in seven legislative assemblies and the union territory of Puducherry. The party has a significant presence in many other states in India, but is not in power in all of them. As of July 2019, the party is in power in a total of seven legislative assemblies and the union territory of Puducherry.
Here's a text that can be used to ask questions in the following answers:The Indian National Congress has a significant presence in many states across India. As of a certain year, the party was in power in a total of seven legislative assemblies and the union territory of Puducherry. The party's current status in these regions can be summarized as follows:1. Which states have the Indian National Congress in power, as of the given year?2. Which union territory has the Indian National Congress in power, as of the given year?3. In addition to the states mentioned, which other states have a significant presence of the Indian National Congress?4. As of the given year, how many legislative assemblies and union territories in total have the Indian National Congress in power?5. Which year was used to determine the party's current status in these regions?
Second Retrival Match Rate: 0.6
Second ans: The Indian National Congress (INC) is in power in the states of Punjab, Chhattisgarh, Rajasthan, and Madhya Pradesh, where the party has majority support. In Puducherry, it shares power with alliance partner Dravida Munnetra Kazhagam. In Maharashtra, it shares power as a junior ally with alliance partners Nationalist Congress Party, Shiv Sena, and other smaller regional parties under the multi-party Maha Vikas Aghadi coalition. The party has a presence in six legislative assemblies: Punjab, Rajasthan, Chhattisgarh, Madhya Pradesh, Maharashtra, and the union territory of Puducherry. Additionally, Congress is in power in the union territories of Chandigarh and Puducherry.
The Indian National Congress (INC) is in power in the states of Punjab, Chhattisgarh, Rajasthan, and Madhya Pradesh, where the party has majority support. In Puducherry, it shares power with alliance partner Dravida Munnetra Kazhagam. In Maharashtra, it shares power as a junior ally with alliance partners Nationalist Congress Party, Shiv Sena, and other smaller regional parties under the multi-party Maha Vikas Aghadi coalition. The party has a presence in six legislative assemblies: Punjab, Rajasthan, Chhattisgarh, Madhya Pradesh, Maharashtra, and the union territory of Puducherry. Additionally, Congress is in power in the union territories of Chandigarh and Puducherry.
How many states in india are under congress?
['How many states plus territories in india are under congress?', 'How many states alone in india are under congress?']
[['7'], ['5']]

 50%|█████     | 10/20 [04:44<04:50, 29.08s/it]

follow question : How many states plus territories in india are under congress?
short answer : ['7']
{'score': 0.48130932450294495, 'start': 460, 'end': 463, 'answer': 'six'}
follow question : How many states alone in india are under congress?
short answer : ['5']
{'score': 0.11698012799024582, 'start': 460, 'end': 463, 'answer': 'six'}
{'rougeLsum': 20.000000000000004, 'length': 98.0, 'str_em': 0.0, 'Disambig-F1': 0.0}
{'first_retrival': 0.7, 'second_retrival': 0.6}
First Retrival Match Rate: 1.0
First ans: Fruma-Sarah is the late wife of Lazar Wolf, a wealthy butcher, who rises from the grave in Tevye's dream to warn him of severe retribution if Tzeitel marries Lazar. She is mentioned as a character in the musical, but not a major one, and is portrayed as a formidable figure who plays a key role in Tevye's decision-making process. Fruma-Sarah's presence in the story is a supernatural one, as she appears in Tevye's dream to convey her disapproval of Tzeitel's potential marriage to Lazar. The character of Fruma-Sarah is not a living person in the story, but rather a symbolic representation of the consequences of Tzeitel's choices. In the context of the musical, Fruma-Sarah serves as a plot device to drive the story forward and highlight the tension between tradition and modernity.
Here's a text that asks questions about the character Fruma-Sarah, with the answers provided:Fruma-Sarah is a significant character in the musical Fiddler on the Roof. She is the late wife of Lazar Wolf, a wealthy butcher, and plays a crucial role in Tevye's decision-making process.1. Who is Fruma-Sarah?Answer: Fruma-Sarah is the late wife of Lazar Wolf, a wealthy butcher.2. Why does Fruma-Sarah appear in Tevye's dream?Answer: Fruma-Sarah appears in Tevye's dream to warn him of severe retribution if Tzeitel marries Lazar.3. What role does Fruma-Sarah play in the story?Answer: Fruma-Sarah serves as a plot device to drive the story forward and highlight the tension between tradition and modernity.4. Is Fruma-Sarah a living person in the story?Answer: No, Fruma-Sarah is a supernatural character who appears in Tevye's dream.5. What is the significance of Fruma-Sarah's presence in the story?Answer: Fruma-Sarah's presence serves as a symbolic representation of the consequences of Tzeitel's choices.6. What does Fruma-Sarah represent in the context of the musical?Answer: Fruma-Sarah represents the consequences of Tzeitel's choices and the tension between tradition and modernity.7. Is Fruma-Sarah a major character in the musical?Answer: No, Fruma-Sarah is not a major character in the musical, but plays a key role in Tevye's decision-making process.8. What is the relationship between Fruma-Sarah and Lazar Wolf?Answer: Fruma-Sarah is the late wife of Lazar Wolf, a wealthy butcher.9. What is the relationship between Fruma-Sarah and Tevye?Answer: Fruma-Sarah appears in Tevye's dream to warn him of severe retribution if Tzeitel marries Lazar.10. What is the outcome of Tevye's decision-making process influenced by Fruma-Sarah?Answer: Tevye's decision to allow Tzeitel to marry Motel is influenced by Fruma-Sarah's warning of severe retribution if Tzeitel marries Lazar.
Second Retrival Match Rate: 0.8

 50%|█████     | 10/20 [05:22<05:22, 32.24s/it]

KeyboardInterrupt:

In [39]:
scores_df.to_csv('./results/0211answer_results.csv', index=False)
import pandas as pd
import math
sf = pd.read_csv('results/0211answer_results.csv')
sf=sf[sf['length']<1000][:100]
print(len(sf))
print(sf.mean())
r=sf.mean()['rougeLsum']
d=sf.mean()['Disambig-F1']
dr=math.sqrt(r*d)
print(dr)

19
rougeLsum      38.764659
length         86.526316
str_em         58.333333
Disambig-F1    45.701754
dtype: float64
42.09053249441862

In [ ]:
# from tqdm import tqdm
# from evaluation import evaluate

# set_seed(24)

# stop_iteration = 20

# scores_list=[]
# retrival_list=[]
# for idx, row in tqdm(qa_df.iterrows(), total=min([stop_iteration, len(qa_df)])):
#     if idx == stop_iteration: break
#     query = row['question']
    
#     retrieved_docs, doc_ids = retrieve_documents(query)
#     tmp1=0
#     for doc_id in doc_ids:    
#         tmp1+=match_sample_id(idx, doc_id)
#     first_retrival=tmp1/len(retrieved_docs)
#     print("First Retrival Match Rate:", first_retrival)
    
#     dic=dict()
#     dic['first_retrival']=first_retrival
    
#     first_ans=total_answer(query,retrieved_docs)
#     print('First ans:', first_ans)
    
#     # hyde_ans_list=hyde(query,first_ans)
#     # print(hyde_ans_list)
    
#     ans_docs, doc_ids=retrieve_documents(first_ans)
#     id_dic=dict()
#     tmp2=0
#     for doc_id in doc_ids:    
#         tmp2+=match_sample_id(idx, doc_id)
#         doc_sample_id=eval_df.loc[doc_id,'sample_id']
#         if doc_sample_id not in id_dic:
#             id_dic[doc_sample_id]=1
#         else:
#             id_dic[doc_sample_id]+=1
#     res=sorted(id_dic.items(), key= lambda item:-item[1])
#     print(res)
#     max_sample_id,max_value=res[0]
#     print("Max sample id:", max_sample_id)
#     # print(ans_docs)
    
#     if max_value>=5:
#         if max_sample_id==qa_df.loc[idx,'sample_id']:
#             second_retrival=1.0
#         else:
#             second_retrival=0.0
#         ans_docs=retrieve_documents2(query, max_sample_id)
#     else:
#         second_retrival=tmp2/len(ans_docs)
        
#     print("Second Retrival Match Rate:", second_retrival)
    
#     dic['second_retrival']=second_retrival
    
#     final_ans=total_answer(query,ans_docs)
#     print('Second ans:', final_ans)
#     scores=evaluate([final_ans], [row.to_dict()])
#     scores_list.append(scores)
#     scores_df=pd.DataFrame(scores_list)
#     print(scores)
#     retrival_list.append(dic)
#     retrival_df=pd.DataFrame(retrival_list)
#     print(dic)
        
# scores_df=pd.DataFrame(scores_list)
# scores_df.mean()

# retrival_df=pd.DataFrame(retrival_list)
# retrival_df.mean()

In [41]:
scores_df.mean()

rougeLsum      41.618101
length         90.600000
str_em         67.083333
Disambig-F1    51.569444
dtype: float64

In [19]:
scores_df.to_csv('./results/answer_rag_4_len60_results.csv', index=False)

In [3]:
# 기본 라그에서 total_answer함수써서 답변 생성 후 그 답변을 다시 검색해서 total_answer로 최종 답변 생성
import pandas as pd
import math
sf = pd.read_csv('results/answer_rag_4_len60_results.csv')
sf=sf[sf['length']<1000][:60]
print(len(sf))
print(sf.mean())
r=sf.mean()['rougeLsum']
d=sf.mean()['Disambig-F1']
dr=math.sqrt(r*d)
print(dr)

60
rougeLsum      38.451280
length         99.533333
str_em         64.583333
Disambig-F1    51.052730
dtype: float64
44.30623874568943

In [27]:
from tqdm import tqdm
from evaluation import evaluate

set_seed()

stop_iteration = 20

scores_list=[]
for idx, row in tqdm(qa_df.iterrows(), total=min([stop_iteration, len(qa_df)])):
    if idx == stop_iteration: break
    query = row['question']
    retrieved_docs = retrieve_documents(query)
    first_ans=answer(query,retrieved_docs)
    print('First ans:', first_ans[0])
    ans_docs=retrieve_documents(first_ans[0])
    final_ans=answer(first_ans[0],ans_docs)
    print('Second ans:', final_ans[0])
    scores=evaluate(final_ans, [row.to_dict()])
    scores_list.append(scores)
    scores_df=pd.DataFrame(scores_list)
    print(scores)
        
scores_df=pd.DataFrame(scores_list)
scores_df.mean()

  0%|          | 0/20 [00:00<?, ?it/s]/home/dataconv/.cache/huggingface/modules/transformers_modules/nvidia/NV-Embed-v2/5130cf1daf847c1bacee854a6ef1ca939e747fb2/modeling_nvembed.py:349: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'input_ids': torch.tensor(batch_dict.get('input_ids').to(batch_dict.get('input_ids')).long()),
/home/dataconv/anaconda3/envs/sf_rag_djk/lib/python3.10/contextlib.py:103: FutureWarning: `torch.backends.cuda.sdp_kernel()` is deprecated. In the future, this context manager will be removed. Please see `torch.nn.attention.sdpa_kernel()` for the new context manager, with updated signature.
  self.gen = func(*args, **kwds)

First ans: According to the provided context information, the player with the highest goals in world football is Ali Daei of Iran, with 109 goals in international matches.
Second ans: According to the provided context information, the player with the highest goals in world football is Ali Daei of Iran, with 109 goals in international matches.
According to the provided context information, the player with the highest goals in world football is Ali Daei of Iran, with 109 goals in international matches.
Who has the highest goals in world football?
["Who has the highest goals in men's world international football?", "Who has the highest goals all-time in men's football?", "Who has the highest goals in women's world international football?"]
[['Daei', 'Ali Daei'], ['Bican', 'Josef Bican'], ['Sinclair', 'Christine Sinclair']]

  5%|▌         | 1/20 [00:07<02:27,  7.74s/it]

follow question : Who has the highest goals in men's world international football?
short answer : ['Daei', 'Ali Daei']
{'score': 0.8568584322929382, 'start': 102, 'end': 110, 'answer': 'Ali Daei'}
follow question : Who has the highest goals all-time in men's football?
short answer : ['Bican', 'Josef Bican']
{'score': 0.17466114461421967, 'start': 102, 'end': 110, 'answer': 'Ali Daei'}
follow question : Who has the highest goals in women's world international football?
short answer : ['Sinclair', 'Christine Sinclair']
{'score': 0.05843370407819748, 'start': 102, 'end': 110, 'answer': 'Ali Daei'}
{'rougeLsum': 36.36363636363637, 'length': 26.0, 'str_em': 33.33333333333333, 'Disambig-F1': 33.33333333333333}
First ans: Simon & Garfunkel
Second ans: Simon & Garfunkel was an American folk rock duo consisting of Paul Simon and Art Garfunkel. They were one of the most popular and influential musical acts of the 1960s, known for their harmonious vocals and introspective songwriting.Simon & Garfunkel's music career began in the early 1960s, when they performed together as a folk duo called Tom and Jerry. However, they went their separate ways in the late 1950s and early 1960s, with Simon attending college and Garfunkel studying at Columbia University.In 1963, Simon and Garfunkel regrouped and began performing together again, this time as Simon & Garfunkel. They signed with Columbia Records and released their debut album, "Wednesday Morning, 3 A.M.," in 1964. Although the album was initially a commercial failure, it eventually gained popularity and became a cult classic.Simon & Garfunkel's breakthrough came with the release of their single "The Sound of Silence" in 1965. The song, which was originally recorded in an acoustic version for their debut album, was remixed with electric instruments and drums by producer Tom Wilson. The new version of the song became a huge success, reaching number one on the Billboard Hot 100 chart in January 1966.The duo's second album, "Sounds of Silence," was released in 1966 and featured a mix of folk rock, pop, and psychedelic sounds. The album included the hit singles "I Am a Rock" and "The Sound of Silence," and became a huge commercial success, reaching number 21 on the Billboard 200 chart.Simon & Garfunkel's music career continued to thrive throughout the 1960s and 1970s, with the release of albums such as "Parsley, Sage, Rosemary and Thyme" and "Bridge Over Troubled Water." They became one of the most popular and influential musical acts of the decade, known for their harmonious vocals and introspective songwriting.Some of their most famous songs include:* "The Sound of Silence"* "I Am a Rock"* "The Boxer"* "Bridge Over Troubled Water"* "Cecilia"* "Mrs. Robinson"Simon & Garfunkel's music has had a lasting impact on the music industry, and they continue to be celebrated as one of the most influential and beloved musical acts of all
Simon & Garfunkel was an American folk rock duo consisting of Paul Simon and Art Garfunkel. They were one of the most popular and influential musical acts of the 1960s, known for their harmonious vocals and introspective songwriting.Simon & Garfunkel's music career began in the early 1960s, when they performed together as a folk duo called Tom and Jerry. However, they went their separate ways in the late 1950s and early 1960s, with Simon attending college and Garfunkel studying at Columbia University.In 1963, Simon and Garfunkel regrouped and began performing together again, this time as Simon & Garfunkel. They signed with Columbia Records and released their debut album, "Wednesday Morning, 3 A.M.," in 1964. Although the album was initially a commercial failure, it eventually gained popularity and became a cult classic.Simon & Garfunkel's breakthrough came with the release of their single "The Sound of Silence" in 1965. The song, which was originally recorded in an acoustic version for their debut album, was remixed with electric instruments and drums by producer Tom Wilson. The new version of the song became a huge success, reaching number one on the Billboard Hot 100 chart in January 1966.The duo's second album, "Sounds of Silence," was released in 1966 and featured a mix of folk rock, pop, and psychedelic sounds. The album included the hit singles "I Am a Rock" and "The Sound of Silence," and became a huge commercial success, reaching number 21 on the Billboard 200 chart.Simon & Garfunkel's music career continued to thrive throughout the 1960s and 1970s, with the release of albums such as "Parsley, Sage, Rosemary and Thyme" and "Bridge Over Troubled Water." They became one of the most popular and influential musical acts of the decade, known for their harmonious vocals and introspective songwriting.Some of their most famous songs include:* "The Sound of Silence"* "I Am a Rock"* "The Boxer"* "Bridge Over Troubled Water"* "Cecilia"* "Mrs. Robinson"Simon & Garfunkel's music has had a lasting impact on the music industry, and they continue to be celebrated as one of the most influential and beloved musical acts of all
Who is the original artist of sound of silence?
['Who is the original artist of sound of silence, the song, released in 1964?', 'Who is the original artist of sound of silence, the album?', 'Who is the original artist of sound of silence, the song, released in 2016?']
[['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon'], ['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon'], ['Dami Im']]

 10%|█         | 2/20 [00:36<06:06, 20.37s/it]

follow question : Who is the original artist of sound of silence, the song, released in 1964?
short answer : ['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon']
{'score': 0.0009827768662944436, 'start': 1080, 'end': 1090, 'answer': 'Tom Wilson'}
follow question : Who is the original artist of sound of silence, the album?
short answer : ['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon']
{'score': 0.13287265598773956, 'start': 1499, 'end': 1516, 'answer': 'Simon & Garfunkel'}
follow question : Who is the original artist of sound of silence, the song, released in 2016?
short answer : ['Dami Im']
{'score': 6.20093260295107e-06, 'start': 1080, 'end': 1090, 'answer': 'Tom Wilson'}
{'rougeLsum': 21.97309417040359, 'length': 348.0, 'str_em': 66.66666666666666, 'Disambig-F1': 33.33333333333333}
First ans: The first Apple iPhone was made in 2005, when Apple started to gather a team of 1,000 employees to work on the highly confidential "Project Purple."
Second ans: The statement is incorrect. The first Apple iPhone was not made in 2005. According to the provided information, development of the iPhone began in 2005, but it was released in 2007. The development cost of the collaboration was estimated to have been $150 million over a thirty-month period, and the original iPhone was introduced by Steve Jobs on January 9, 2007, at the Macworld Conference & Expo held in Moscone West in San Francisco, California.
The statement is incorrect. The first Apple iPhone was not made in 2005. According to the provided information, development of the iPhone began in 2005, but it was released in 2007. The development cost of the collaboration was estimated to have been $150 million over a thirty-month period, and the original iPhone was introduced by Steve Jobs on January 9, 2007, at the Macworld Conference & Expo held in Moscone West in San Francisco, California.
When was the first apple i phone made?
['When was the first apple i phone released?', 'When was the first apple i phone for beta testing made?', 'When was the first apple i phone 1 made?', 'When was the first apple i phone beta made?']
[['June 29, 2007'], ['2004'], ['June 29, 2007.'], ['2004.']]

 15%|█▌        | 3/20 [00:47<04:27, 15.75s/it]

follow question : When was the first apple i phone released?
short answer : ['June 29, 2007']
{'score': 0.5703911781311035, 'start': 176, 'end': 180, 'answer': '2007'}
follow question : When was the first apple i phone for beta testing made?
short answer : ['2004']
{'score': 0.2193128764629364, 'start': 67, 'end': 71, 'answer': '2005'}
follow question : When was the first apple i phone 1 made?
short answer : ['June 29, 2007.']
{'score': 0.3912900984287262, 'start': 67, 'end': 71, 'answer': '2005'}
follow question : When was the first apple i phone beta made?
short answer : ['2004.']
{'score': 0.07923733443021774, 'start': 67, 'end': 71, 'answer': '2005'}
{'rougeLsum': 34.53237410071942, 'length': 75.0, 'str_em': 0.0, 'Disambig-F1': 12.5}
First ans: The Weasley brothers were played by the following actors:* Bill Weasley: Richard Fish (briefly in the film adaptation of Harry Potter and the Prisoner of Azkaban), Domhnall Gleeson (in Harry Potter and the Deathly Hallows)* Charlie Weasley: Alex Crockford (briefly in the film adaptation of Prisoner of Azkaban)* Fred and George Weasley: James and Oliver PhelpsThey are twins who played the identical twin brothers in the film series.
Second ans: The Weasley brothers were played by the following actors:* Bill Weasley: Richard Fish (briefly in the film adaptation of Harry Potter and the Prisoner of Azkaban), Domhnall Gleeson (in Harry Potter and the Deathly Hallows)* Charlie Weasley: Alex Crockford (briefly in the film adaptation of Prisoner of Azkaban)* Fred and George Weasley: James and Oliver Phelps (They are twins who played the identical twin brothers in the film series.)
The Weasley brothers were played by the following actors:* Bill Weasley: Richard Fish (briefly in the film adaptation of Harry Potter and the Prisoner of Azkaban), Domhnall Gleeson (in Harry Potter and the Deathly Hallows)* Charlie Weasley: Alex Crockford (briefly in the film adaptation of Prisoner of Azkaban)* Fred and George Weasley: James and Oliver Phelps (They are twins who played the identical twin brothers in the film series.)
Who played the weasley brothers in harry potter?
['Who played  Bill weasley in Harry Potter and the Prisoner of Azkaban?', 'Who played percy weasley in harry potter?', 'Who played fred weasley in harry potter?', 'Who played ron weasley in harry potter?', 'Who played george weasley in harry potter?', 'Who played  Bill weasley in harry potter (2001-2011)?']
[['Richard Fish'], ['Chris Rankin'], ['James Phelps'], ['Rupert Grint'], ['Oliver Phelps'], ['Domhnall Gleeson']]

 20%|██        | 4/20 [01:00<03:55, 14.71s/it]

follow question : Who played  Bill weasley in Harry Potter and the Prisoner of Azkaban?
short answer : ['Richard Fish']
{'score': 0.6618728637695312, 'start': 73, 'end': 85, 'answer': 'Richard Fish'}
follow question : Who played percy weasley in harry potter?
short answer : ['Chris Rankin']
{'score': 0.7059646844863892, 'start': 73, 'end': 85, 'answer': 'Richard Fish'}
follow question : Who played fred weasley in harry potter?
short answer : ['James Phelps']
{'score': 0.7058833837509155, 'start': 73, 'end': 85, 'answer': 'Richard Fish'}
follow question : Who played ron weasley in harry potter?
short answer : ['Rupert Grint']
{'score': 0.7591727375984192, 'start': 73, 'end': 85, 'answer': 'Richard Fish'}
follow question : Who played george weasley in harry potter?
short answer : ['Oliver Phelps']
{'score': 0.3762194514274597, 'start': 73, 'end': 85, 'answer': 'Richard Fish'}
follow question : Who played  Bill weasley in harry potter (2001-2011)?
short answer : ['Domhnall Gleeson']
{'score': 0.6254032254219055, 'start': 73, 'end': 85, 'answer': 'Richard Fish'}
{'rougeLsum': 48.05194805194806, 'length': 69.0, 'str_em': 50.0, 'Disambig-F1': 16.666666666666664}
First ans: According to the provided context information, there are 38 state parks in Virginia.
Second ans: That's correct. According to the provided context information, there are 38 state parks in Virginia.
That's correct. According to the provided context information, there are 38 state parks in Virginia.
How many state parks are there in virginia?
['How many state parks are there in virginia in 1936?', 'How many state parks are there in virginia in 2016?', 'How many state parks were there when the state park system formed in Virginia?', 'How many state parks were there in Virginia as of 2016?']
[['six'], ['38'], ['6'], ['38']]

 25%|██▌       | 5/20 [01:04<02:45, 11.02s/it]

follow question : How many state parks are there in virginia in 1936?
short answer : ['six']
{'score': 0.008646625094115734, 'start': 73, 'end': 75, 'answer': '38'}
follow question : How many state parks are there in virginia in 2016?
short answer : ['38']
{'score': 0.5548556447029114, 'start': 73, 'end': 75, 'answer': '38'}
follow question : How many state parks were there when the state park system formed in Virginia?
short answer : ['6']
{'score': 0.8253440856933594, 'start': 73, 'end': 75, 'answer': '38'}
follow question : How many state parks were there in Virginia as of 2016?
short answer : ['38']
{'score': 0.575831413269043, 'start': 73, 'end': 75, 'answer': '38'}
{'rougeLsum': 31.999999999999996, 'length': 15.0, 'str_em': 50.0, 'Disambig-F1': 50.0}
First ans: Dua Lipa performed at the opening ceremony preceding the final. Jamaican rapper Sean Paul joined her as a special guest to perform their collaborative song, "No Lie". The UEFA Champions League Anthem was performed by Slovenian–Croatian cello duo 2Cellos.
Second ans: Dua Lipa performed at the opening ceremony preceding the 2018 UEFA Champions League Final, accompanied by Jamaican rapper Sean Paul, who performed their collaborative song "No Lie". Additionally, the Slovenian-Croatian cello duo 2Cellos performed the UEFA Champions League Anthem.
Dua Lipa performed at the opening ceremony preceding the 2018 UEFA Champions League Final, accompanied by Jamaican rapper Sean Paul, who performed their collaborative song "No Lie". Additionally, the Slovenian-Croatian cello duo 2Cellos performed the UEFA Champions League Anthem.
Who performed at the champions league final 2018?
['Who are the teams that performed in competition at the champions league final 2018?', 'Who performed best at the champions league final 2018, winning man of the match?', 'Who performed at the opening ceremony of the champions league final 2018?', 'Who performed the anthem at the champions league final 2018?']
[['Real Madrid and Liverpool', 'Liverpool', 'Real Madrid'], ['Gareth Bale', 'Bale'], ['Dua Lipa', 'Sean Paul', 'Dua Lipa and Sean Paul'], ['2Cellos', 'Luka Šulić and Stjepan Hauser', 'Luka Šulić', '2CΞLLOS', 'Stjepan Hauser']]

 30%|███       | 6/20 [01:13<02:23, 10.27s/it]

follow question : Who are the teams that performed in competition at the champions league final 2018?
short answer : ['Real Madrid and Liverpool', 'Liverpool', 'Real Madrid']
{'score': 0.016498327255249023, 'start': 200, 'end': 236, 'answer': 'Slovenian-Croatian cello duo 2Cellos'}
follow question : Who performed best at the champions league final 2018, winning man of the match?
short answer : ['Gareth Bale', 'Bale']
{'score': 0.87488853931427, 'start': 0, 'end': 8, 'answer': 'Dua Lipa'}
follow question : Who performed at the opening ceremony of the champions league final 2018?
short answer : ['Dua Lipa', 'Sean Paul', 'Dua Lipa and Sean Paul']
{'score': 0.7995817065238953, 'start': 0, 'end': 8, 'answer': 'Dua Lipa'}
follow question : Who performed the anthem at the champions league final 2018?
short answer : ['2Cellos', 'Luka Šulić and Stjepan Hauser', 'Luka Šulić', '2CΞLLOS', 'Stjepan Hauser']
{'score': 0.3890477418899536, 'start': 229, 'end': 236, 'answer': '2Cellos'}
{'rougeLsum': 53.54330708661418, 'length': 39.0, 'str_em': 50.0, 'Disambig-F1': 50.0}
First ans: In the movie Thelma and Louise, the man who was killed was Harlan, a stranger who attempted to rape Thelma. He was shot and killed by Louise after she threatened him with a gun.
Second ans: Harlan, a stranger who attempted to rape Thelma, was shot and killed by Louise after she threatened him with a gun.
Harlan, a stranger who attempted to rape Thelma, was shot and killed by Louise after she threatened him with a gun.
Who killed the man in thelma and louise?
['Which character killed the man in thelma and louise?', 'Which actor killed the man in thelma and louise?', 'Who is the character that kills Harlan in the film Thelma and Louise?', 'Who is the actor of the character that killed a man in the film Thelma and Louise?']
[['Louise Elizabeth Sawyer', 'Louise'], ['Susan Sarandon', 'Susan Abigail Sarandon'], ['Louise Elizabeth Sawyer', 'Louise'], ['Susan Sarandon']]

 35%|███▌      | 7/20 [01:20<01:58,  9.15s/it]

follow question : Which character killed the man in thelma and louise?
short answer : ['Louise Elizabeth Sawyer', 'Louise']
{'score': 0.6458455324172974, 'start': 0, 'end': 6, 'answer': 'Harlan'}
follow question : Which actor killed the man in thelma and louise?
short answer : ['Susan Sarandon', 'Susan Abigail Sarandon']
{'score': 0.6744271516799927, 'start': 0, 'end': 6, 'answer': 'Harlan'}
follow question : Who is the character that kills Harlan in the film Thelma and Louise?
short answer : ['Louise Elizabeth Sawyer', 'Louise']
{'score': 0.6058520078659058, 'start': 10, 'end': 18, 'answer': 'stranger'}
follow question : Who is the actor of the character that killed a man in the film Thelma and Louise?
short answer : ['Susan Sarandon']
{'score': 0.772394597530365, 'start': 0, 'end': 6, 'answer': 'Harlan'}
{'rougeLsum': 15.384615384615383, 'length': 21.0, 'str_em': 50.0, 'Disambig-F1': 0.0}
First ans: Charlie Kelly is played by Charlie Day.
Second ans: Yes, that is correct. Charlie Kelly is played by Charlie Day.
Yes, that is correct. Charlie Kelly is played by Charlie Day.
Who plays charlie on it's always sunny?
["Who does Charlie Day play on It's Always Sunny in Philadelphia?", "Who plays Charlie Kelly on It's Always Sunny in Philadelphia?"]
[['Charlie Kelly'], ['Charlie Day']]

 40%|████      | 8/20 [01:24<01:29,  7.49s/it]

follow question : Who does Charlie Day play on It's Always Sunny in Philadelphia?
short answer : ['Charlie Kelly']
{'score': 0.9868155717849731, 'start': 22, 'end': 35, 'answer': 'Charlie Kelly'}
follow question : Who plays Charlie Kelly on It's Always Sunny in Philadelphia?
short answer : ['Charlie Day']
{'score': 0.9854613542556763, 'start': 49, 'end': 60, 'answer': 'Charlie Day'}
{'rougeLsum': 32.25806451612903, 'length': 11.0, 'str_em': 100.0, 'Disambig-F1': 100.0}
First ans: The Los Angeles Lakers have won the NBA Finals 16 times.
Second ans: Yes, that's correct. The Los Angeles Lakers have won the NBA Finals 16 times, which is the second-most championships in NBA history, behind the Boston Celtics' 17 championships.
Yes, that's correct. The Los Angeles Lakers have won the NBA Finals 16 times, which is the second-most championships in NBA history, behind the Boston Celtics' 17 championships.
How many times have the lakers won the finals?
['As of 2017, how many times have the lakers won the finals?', 'As of 2016, how many times have the Lakers won the finals?', 'As of 2015, how many times have the Lakers won the finals?']
[['16'], ['16'], ['16']]

 45%|████▌     | 9/20 [01:30<01:18,  7.10s/it]

follow question : As of 2017, how many times have the lakers won the finals?
short answer : ['16']
{'score': 0.8009308576583862, 'start': 68, 'end': 70, 'answer': '16'}
follow question : As of 2016, how many times have the Lakers won the finals?
short answer : ['16']
{'score': 0.8325595259666443, 'start': 68, 'end': 70, 'answer': '16'}
follow question : As of 2015, how many times have the Lakers won the finals?
short answer : ['16']
{'score': 0.6845507621765137, 'start': 68, 'end': 70, 'answer': '16'}
{'rougeLsum': 37.83783783783784, 'length': 28.0, 'str_em': 100.0, 'Disambig-F1': 100.0}
First ans: Based on the provided context information, the following states in India are under the Congress:1. Punjab2. Chhattisgarh3. Rajasthan4. Madhya Pradesh5. Puducherry (union territory)6. Maharashtra (as part of the Maha Vikas Aghadi coalition)7. Jharkhand (junior ally with Jharkhand Mukti Morcha)These states and union territories are under the control of the Indian National Congress, either as the ruling party or as part of a coalition government.
Second ans: Based on the provided context information, the following states in India are under the Congress:1. Punjab2. Chhattisgarh3. Rajasthan4. Madhya Pradesh5. Puducherry (union territory)6. Maharashtra (as part of the Maha Vikas Aghadi coalition)7. Jharkhand (junior ally with Jharkhand Mukti Morcha)These states and union territories are under the control of the Indian National Congress, either as the ruling party or as part of a coalition government.
Based on the provided context information, the following states in India are under the Congress:1. Punjab2. Chhattisgarh3. Rajasthan4. Madhya Pradesh5. Puducherry (union territory)6. Maharashtra (as part of the Maha Vikas Aghadi coalition)7. Jharkhand (junior ally with Jharkhand Mukti Morcha)These states and union territories are under the control of the Indian National Congress, either as the ruling party or as part of a coalition government.
How many states in india are under congress?
['How many states plus territories in india are under congress?', 'How many states alone in india are under congress?']
[['7'], ['5']]

 50%|█████     | 10/20 [01:44<01:31,  9.19s/it]

follow question : How many states plus territories in india are under congress?
short answer : ['7']
{'score': 0.023033540695905685, 'start': 96, 'end': 106, 'answer': '1. Punjab2'}
follow question : How many states alone in india are under congress?
short answer : ['5']
{'score': 0.015681445598602295, 'start': 43, 'end': 56, 'answer': 'the following'}
{'rougeLsum': 31.007751937984494, 'length': 64.0, 'str_em': 100.0, 'Disambig-F1': 0.0}
First ans: Fruma-Sarah is the deceased wife of Lazar Wolf, a wealthy butcher in the village of Anatevka. She rises from the grave in Tevye's "nightmare" to warn of severe retribution if Tzeitel marries Lazar.
Second ans: Fruma-Sarah is the deceased wife of Lazar Wolf, a wealthy butcher in the village of Anatevka. She rises from the grave in Tevye's "nightmare" to warn of severe retribution if Tzeitel marries Lazar.
Fruma-Sarah is the deceased wife of Lazar Wolf, a wealthy butcher in the village of Anatevka. She rises from the grave in Tevye's "nightmare" to warn of severe retribution if Tzeitel marries Lazar.
Who is fruma sarah in fiddler on the roof?
['Who played fruma sarah in the 1971 film, Fiddler on the Roof?', 'Who played Fruma Sarah in the original 1964 Broadway cast of Fiddler on the Roof?', 'Who is the character of Fruma Sarah in Fiddler on the Roof?', 'Who played Fruma Sarah in the 2015-2016 Broadway Revival of Fiddler on the Roof?']
[['Ruth Madoc'], ['Carol Sawyer Yussel'], ['a ghostly depiction of the late wife of Lazar Wolf'], ['Jessica Vosk']]

 55%|█████▌    | 11/20 [01:52<01:19,  8.88s/it]

follow question : Who played fruma sarah in the 1971 film, Fiddler on the Roof?
short answer : ['Ruth Madoc']
{'score': 0.0021976102143526077, 'start': 122, 'end': 127, 'answer': 'Tevye'}
follow question : Who played Fruma Sarah in the original 1964 Broadway cast of Fiddler on the Roof?
short answer : ['Carol Sawyer Yussel']
{'score': 0.023890621960163116, 'start': 122, 'end': 127, 'answer': 'Tevye'}
follow question : Who is the character of Fruma Sarah in Fiddler on the Roof?
short answer : ['a ghostly depiction of the late wife of Lazar Wolf']
{'score': 0.5104489326477051, 'start': 36, 'end': 46, 'answer': 'Lazar Wolf'}
follow question : Who played Fruma Sarah in the 2015-2016 Broadway Revival of Fiddler on the Roof?
short answer : ['Jessica Vosk']
{'score': 0.005705648101866245, 'start': 122, 'end': 127, 'answer': 'Tevye'}
{'rougeLsum': 21.897810218978105, 'length': 33.0, 'str_em': 0.0, 'Disambig-F1': 10.0}
First ans: July 9, 1991, the Toronto Blue Jays hosted the MLB All-Star Game at the SkyDome.
Second ans: No, that is incorrect. The Toronto Blue Jays hosted the MLB All-Star Game on July 9, 1991, at the SkyDome, but they were the American League team, and the host team was actually the Toronto Blue Jays.
No, that is incorrect. The Toronto Blue Jays hosted the MLB All-Star Game on July 9, 1991, at the SkyDome, but they were the American League team, and the host team was actually the Toronto Blue Jays.
When did toronto host the mlb all-star game?
['What date did toronto host the mlb all-star game?', 'Which all-star game did toronto host?']
[['July 9, 1991'], ['1991 Major League Baseball All-Star Game', 'the 62nd playing of the midsummer classic']]

 60%|██████    | 12/20 [02:00<01:07,  8.44s/it]

follow question : What date did toronto host the mlb all-star game?
short answer : ['July 9, 1991']
{'score': 0.9494990110397339, 'start': 77, 'end': 89, 'answer': 'July 9, 1991'}
follow question : Which all-star game did toronto host?
short answer : ['1991 Major League Baseball All-Star Game', 'the 62nd playing of the midsummer classic']
{'score': 0.3525626063346863, 'start': 56, 'end': 73, 'answer': 'MLB All-Star Game'}
{'rougeLsum': 39.603960396039604, 'length': 37.0, 'str_em': 50.0, 'Disambig-F1': 72.22222222222221}
First ans: A metallic blue 1953 Sunbeam Alpine Mk I is driven by Grace Kelly in the film "To Catch a Thief" (1955) with Cary Grant.
Second ans: The Sunbeam Alpine Mk I, a metallic blue 1953 model, is driven by Grace Kelly in the 1955 film "To Catch a Thief" starring Cary Grant.
The Sunbeam Alpine Mk I, a metallic blue 1953 model, is driven by Grace Kelly in the 1955 film "To Catch a Thief" starring Cary Grant.
What kind of car in to catch a thief?
['What kind of car in to catch a thief in terms of model?', 'What kind of car in to catch a thief in terms of automobile make?']
[['Sunbeam Alpine', '1953 Sunbeam Alpine Mk I'], ['Rootes Group']]

 65%|██████▌   | 13/20 [02:07<00:55,  7.99s/it]

follow question : What kind of car in to catch a thief in terms of model?
short answer : ['Sunbeam Alpine', '1953 Sunbeam Alpine Mk I']
{'score': 0.5046610832214355, 'start': 4, 'end': 23, 'answer': 'Sunbeam Alpine Mk I'}
follow question : What kind of car in to catch a thief in terms of automobile make?
short answer : ['Rootes Group']
{'score': 0.5758154988288879, 'start': 4, 'end': 23, 'answer': 'Sunbeam Alpine Mk I'}
{'rougeLsum': 31.746031746031743, 'length': 26.0, 'str_em': 50.0, 'Disambig-F1': 44.44444444444445}
First ans: The last season of Jersey Shore (Season 6) aired from October 4, 2012, to December 20, 2012.
Second ans: The last season of Jersey Shore (Season 6) actually aired from October 4, 2012, to December 4, 2012, not December 20, 2012.
The last season of Jersey Shore (Season 6) actually aired from October 4, 2012, to December 4, 2012, not December 20, 2012.
When did the last season of jersey shore air?
['When did season 4 of jersey shore first air?', 'When did season 4 of jersey shore last air?', 'When did season 5 of jersey shore first air?', 'When did season 5 of jersey shore last air?', 'When did season 6 of jersey shore first air?', 'When did season 6 of jersey shore last air?']
[['August 4, 2011'], ['October 20, 2011'], ['January 5, 2012'], ['March 15, 2012'], ['October 4, 2012'], ['December 20, 2012']]

 70%|███████   | 14/20 [02:13<00:45,  7.63s/it]

follow question : When did season 4 of jersey shore first air?
short answer : ['August 4, 2011']
{'score': 0.07206683605909348, 'start': 63, 'end': 78, 'answer': 'October 4, 2012'}
follow question : When did season 4 of jersey shore last air?
short answer : ['October 20, 2011']
{'score': 0.2847982347011566, 'start': 83, 'end': 99, 'answer': 'December 4, 2012'}
follow question : When did season 5 of jersey shore first air?
short answer : ['January 5, 2012']
{'score': 0.021944589912891388, 'start': 63, 'end': 78, 'answer': 'October 4, 2012'}
follow question : When did season 5 of jersey shore last air?
short answer : ['March 15, 2012']
{'score': 0.09906397759914398, 'start': 63, 'end': 78, 'answer': 'October 4, 2012'}
follow question : When did season 6 of jersey shore first air?
short answer : ['October 4, 2012']
{'score': 0.17413854598999023, 'start': 63, 'end': 78, 'answer': 'October 4, 2012'}
follow question : When did season 6 of jersey shore last air?
short answer : ['December 20, 2012']
{'score': 0.6348809599876404, 'start': 63, 'end': 78, 'answer': 'October 4, 2012'}
{'rougeLsum': 43.0379746835443, 'length': 22.0, 'str_em': 33.33333333333333, 'Disambig-F1': 38.88888888888889}
First ans: The plane crash occurred in the Season 8 episode "Flight" which is the 24th episode of the season and the 172nd episode overall.
Second ans: The plane crash occurred in the Season 8 episode "Flight" which is the 24th episode of the season and the 172nd episode overall.
The plane crash occurred in the Season 8 episode "Flight" which is the 24th episode of the season and the 172nd episode overall.
What season of greys anatomy was the plane crash?
["What season of Grey's Anatomy was the plane crash involving six doctors?", "What season of Grey's Anatomy was the plane crash in Seattle that brought memories of a previous plane crash?", "What season of Grey's Anatomy was the plane crash that claimed the life of Lexie Grey?", "What season of Grey's Anatomy was the plane crash in downtown Seattle?"]
[['season 8'], ['season 11'], ['8'], ['11']]

 75%|███████▌  | 15/20 [02:20<00:36,  7.23s/it]

follow question : What season of Grey's Anatomy was the plane crash involving six doctors?
short answer : ['season 8']
{'score': 0.8863816857337952, 'start': 32, 'end': 40, 'answer': 'Season 8'}
follow question : What season of Grey's Anatomy was the plane crash in Seattle that brought memories of a previous plane crash?
short answer : ['season 11']
{'score': 0.9001052379608154, 'start': 32, 'end': 40, 'answer': 'Season 8'}
follow question : What season of Grey's Anatomy was the plane crash that claimed the life of Lexie Grey?
short answer : ['8']
{'score': 0.8906877040863037, 'start': 32, 'end': 40, 'answer': 'Season 8'}
follow question : What season of Grey's Anatomy was the plane crash in downtown Seattle?
short answer : ['11']
{'score': 0.9075095653533936, 'start': 32, 'end': 40, 'answer': 'Season 8'}
{'rougeLsum': 32.35294117647059, 'length': 23.0, 'str_em': 50.0, 'Disambig-F1': 54.166666666666664}
First ans: According to the provided context information, the Oriental Bank of Commerce had 2390 branches across India as of the 2018-2019 annual report.
Second ans: According to the provided context information, the Oriental Bank of Commerce had 2390 branches across India as of the 2018-2019 annual report.
According to the provided context information, the Oriental Bank of Commerce had 2390 branches across India as of the 2018-2019 annual report.
Number of branches of oriental bank of commerce in india?
['As per the March 2018-2019 report, what is the number of branches of oriental bank of commerce in india?', 'What is the number of branches of oriental bank of commerce in india after amalgamation of Global Trust Bank?', 'Number of branches of oriental bank of commerce in india after expected merger with United Bank of India in 2020?']
[['2390'], ['1092'], ['11,437']]

 80%|████████  | 16/20 [02:26<00:28,  7.04s/it]

follow question : As per the March 2018-2019 report, what is the number of branches of oriental bank of commerce in india?
short answer : ['2390']
{'score': 0.8879122734069824, 'start': 81, 'end': 85, 'answer': '2390'}
follow question : What is the number of branches of oriental bank of commerce in india after amalgamation of Global Trust Bank?
short answer : ['1092']
{'score': 0.7891730070114136, 'start': 81, 'end': 85, 'answer': '2390'}
follow question : Number of branches of oriental bank of commerce in india after expected merger with United Bank of India in 2020?
short answer : ['11,437']
{'score': 0.4474791884422302, 'start': 81, 'end': 85, 'answer': '2390'}
{'rougeLsum': 30.952380952380953, 'length': 22.0, 'str_em': 33.33333333333333, 'Disambig-F1': 33.33333333333333}
First ans: 1995
Second ans: Here are some of the notable events and information from the provided context related to the year 1995:1. **Windows 95**: Microsoft released Windows 95, a new version of its operating system, on August 24, 1995. This operating system was designed to be more user-friendly and efficient than its predecessors.2. **1995 Canadian Open**: The 1995 Canadian Open was a men's and women's professional tennis tournament that took place in Montreal, Quebec, Canada, from July 24 to July 31, 1995, and in Toronto, Ontario, Canada, from August 13 to August 20, 1995.3. **Manchester United**: The 1995-96 season was a significant one for Manchester United, as they won the league title and the FA Cup, with Sir Alex Ferguson at the helm.4. **UEFA Champions League**: The 1995-96 UEFA Champions League season saw the introduction of a new format, with the top teams from each group advancing to the quarterfinals.5. **Major League Baseball**: The 1995 season was a notable one for Major League Baseball, with the Colorado Rockies and the New York Yankees competing for the World Series title.6. **FIFA World Cup**: The 1994 FIFA World Cup was held in the United States, and the 1998 FIFA World Cup was held in France. The 1995-96 season was a significant one for the FIFA World Cup, with the introduction of new rules and regulations.7. **Personal Computers**: The 1990s saw significant advancements in personal computers, with the introduction of new technologies such as CD-ROMs, ThinkPads, and Power Macintosh computers.These are just a few of the notable events and information related to the year 1995 from the provided context.
Here are some of the notable events and information from the provided context related to the year 1995:1. **Windows 95**: Microsoft released Windows 95, a new version of its operating system, on August 24, 1995. This operating system was designed to be more user-friendly and efficient than its predecessors.2. **1995 Canadian Open**: The 1995 Canadian Open was a men's and women's professional tennis tournament that took place in Montreal, Quebec, Canada, from July 24 to July 31, 1995, and in Toronto, Ontario, Canada, from August 13 to August 20, 1995.3. **Manchester United**: The 1995-96 season was a significant one for Manchester United, as they won the league title and the FA Cup, with Sir Alex Ferguson at the helm.4. **UEFA Champions League**: The 1995-96 UEFA Champions League season saw the introduction of a new format, with the top teams from each group advancing to the quarterfinals.5. **Major League Baseball**: The 1995 season was a notable one for Major League Baseball, with the Colorado Rockies and the New York Yankees competing for the World Series title.6. **FIFA World Cup**: The 1994 FIFA World Cup was held in the United States, and the 1998 FIFA World Cup was held in France. The 1995-96 season was a significant one for the FIFA World Cup, with the introduction of new rules and regulations.7. **Personal Computers**: The 1990s saw significant advancements in personal computers, with the introduction of new technologies such as CD-ROMs, ThinkPads, and Power Macintosh computers.These are just a few of the notable events and information related to the year 1995 from the provided context.
When did the rams go to st louis?
['In what year did the rams go to St. Louis?', 'What was the first game the Rams played in St. Louis?']
[['1995'], ['September 10, 1995']]

 85%|████████▌ | 17/20 [02:47<00:33, 11.20s/it]

follow question : In what year did the rams go to St. Louis?
short answer : ['1995']
{'score': 0.0012254201574251056, 'start': 98, 'end': 102, 'answer': '1995'}
follow question : What was the first game the Rams played in St. Louis?
short answer : ['September 10, 1995']
{'score': 1.4408171409741044e-05, 'start': 98, 'end': 102, 'answer': '1995'}
{'rougeLsum': 20.971867007672635, 'length': 262.0, 'str_em': 50.0, 'Disambig-F1': 75.0}
First ans: The Voortrekkers, a group of Dutch-speaking settlers, began their trek into South Africa in 1835. The first two parties left in September 1835, led by Louis Tregardt and Hans van Rensburg. They crossed the Vaal river at Robert's Drift in January 1836.However, the question seems to refer to the Voortrekkers as a youth organization, which was established in 1931. In this case, the answer would be:The Voortrekkers youth organization was established in 1931, and its first "Kommando" (Troop) was established in Bloemfontein at the Central High School in 1920.
Second ans: The Voortrekkers youth organization was established in 1931, and its first "Kommando" (Troop) was established in Bloemfontein at the Central High School in 1920.
The Voortrekkers youth organization was established in 1931, and its first "Kommando" (Troop) was established in Bloemfontein at the Central High School in 1920.
When did the voortrekkers arrive in south africa?
['When did the first wave of voortrekkers arrive in south africa?', 'When did the voortrekkers exploratory treks arrive in south africa?']
[['1836', '1836 onwards'], ['February 1835']]

 90%|█████████ | 18/20 [02:59<00:22, 11.42s/it]

follow question : When did the first wave of voortrekkers arrive in south africa?
short answer : ['1836', '1836 onwards']
{'score': 0.0015232550213113427, 'start': 156, 'end': 160, 'answer': '1920'}
follow question : When did the voortrekkers exploratory treks arrive in south africa?
short answer : ['February 1835']
{'score': 4.85175805806648e-05, 'start': 55, 'end': 59, 'answer': '1931'}
{'rougeLsum': 29.78723404255319, 'length': 24.0, 'str_em': 0.0, 'Disambig-F1': 0.0}
First ans: Heath Ledger plays Patrick Verona in the 1999 film "10 Things I Hate About You."
Second ans: Yes, that's correct. In the 1999 film "10 Things I Hate About You," Heath Ledger plays the role of Patrick Verona, the "bad boy" who is hired to date Kat Stratford, played by Julia Stiles.
Yes, that's correct. In the 1999 film "10 Things I Hate About You," Heath Ledger plays the role of Patrick Verona, the "bad boy" who is hired to date Kat Stratford, played by Julia Stiles.
Who plays patrick in 10 things i hate about you?
['Who plays patrick in  the 1999 film 10 things i hate about you?', 'Who plays patrick in the 2009 tv series 10 things i hate about you?', 'Who plays patrick in the film 10 things i hate about you?', 'Who plays patrick in the TV series 10 things i hate about you?']
[['Heath Andrew Ledger', 'Heath Ledger', 'Ledger'], ['Ethan Peck', 'Peck', 'Ethan Gregory Peck'], ['Heath Andrew Ledger', 'Heath Ledger'], ['Ethan Peck', 'Ethan Gregory Peck']]

 95%|█████████▌| 19/20 [03:06<00:09,  9.98s/it]

follow question : Who plays patrick in  the 1999 film 10 things i hate about you?
short answer : ['Heath Andrew Ledger', 'Heath Ledger', 'Ledger']
{'score': 0.9635234475135803, 'start': 68, 'end': 80, 'answer': 'Heath Ledger'}
follow question : Who plays patrick in the 2009 tv series 10 things i hate about you?
short answer : ['Ethan Peck', 'Peck', 'Ethan Gregory Peck']
{'score': 1.869488914962858e-05, 'start': 68, 'end': 80, 'answer': 'Heath Ledger'}
follow question : Who plays patrick in the film 10 things i hate about you?
short answer : ['Heath Andrew Ledger', 'Heath Ledger']
{'score': 0.8692940473556519, 'start': 68, 'end': 80, 'answer': 'Heath Ledger'}
follow question : Who plays patrick in the TV series 10 things i hate about you?
short answer : ['Ethan Peck', 'Ethan Gregory Peck']
{'score': 0.00026919867377728224, 'start': 68, 'end': 80, 'answer': 'Heath Ledger'}
{'rougeLsum': 42.10526315789474, 'length': 35.0, 'str_em': 50.0, 'Disambig-F1': 50.0}
First ans: No, Microsoft Live Movie Maker is not an example of a free product. It is a freeware product, which means it is free to download and use, but it is not open-source. It is a proprietary software developed by Microsoft, and its source code is not available for modification or redistribution.
Second ans: Microsoft Live Movie Maker is actually an example of a freeware product, not a free product. It is a proprietary software developed by Microsoft, and its source code is not available for modification or redistribution. While it is free to download and use, it is not open-source, and its development and maintenance are controlled by Microsoft.
Microsoft Live Movie Maker is actually an example of a freeware product, not a free product. It is a proprietary software developed by Microsoft, and its source code is not available for modification or redistribution. While it is free to download and use, it is not open-source, and its development and maintenance are controlled by Microsoft.
Microsoft live movie maker is an example of free?
['Microsoft live movie maker is an example of a freely licensed software, often called free what?', 'Microsoft live movie maker is an example of free software used for what purpose?']
[['freeware'], ['Video editing software']]

100%|██████████| 20/20 [03:14<00:00,  9.75s/it]

follow question : Microsoft live movie maker is an example of a freely licensed software, often called free what?
short answer : ['freeware']
{'score': 0.023067617788910866, 'start': 55, 'end': 63, 'answer': 'freeware'}
follow question : Microsoft live movie maker is an example of free software used for what purpose?
short answer : ['Video editing software']
{'score': 0.2880362868309021, 'start': 239, 'end': 255, 'answer': 'download and use'}
{'rougeLsum': 32.608695652173914, 'length': 56.0, 'str_em': 50.0, 'Disambig-F1': 50.0}

rougeLsum      33.400839
length         61.800000
str_em         48.333333
Disambig-F1    41.194444
dtype: float64

In [25]:
scores_df.to_csv('./results/answer_rag_2_results.csv', index=False)

In [26]:
import pandas as pd
import math
sf = pd.read_csv('results/answer_rag_2_results.csv')
sf=sf[sf['length']<1000][:100]
print(len(sf))
print(sf.mean())
r=sf.mean()['rougeLsum']
d=sf.mean()['Disambig-F1']
dr=math.sqrt(r*d)
print(dr)

16
rougeLsum      33.482502
length         97.562500
str_em         62.500000
Disambig-F1    42.708333
dtype: float64
37.815101059628596