In [4]:
import random, os
import numpy as np
import torch
os.environ["CUDA_VISIBLE_DEVICES"]="1"

from transformers import AutoTokenizer, BitsAndBytesConfig, AutoModelForCausalLM, AutoModel
from datasets import load_dataset
import pandas as pd
import re

device1 = 'cuda:0'
device2 = 'cuda:1'
data_dir = '/raid/deallab/SF_RAG_Data/ASQA'
# data_dir = '../data'

In [34]:
def set_seed(seed_value):
    # Set seed for reproducibility.
    random.seed(seed_value)
    os.environ['PYTHONHASHSEED']=str(seed_value)
    np.random.seed(seed_value)
    torch.manual_seed(seed_value)
    torch.cuda.manual_seed(seed_value)
    torch.backends.cudnn.deterministic=True    
    torch.backends.cudnn.benchmark=True
    torch.cuda.manual_seed_all(seed_value)

In [3]:
# set_seed(30)

In [6]:
#load embeddings
embedd_test_path = f'{data_dir}/test/embedd_test.npy'
evidence_embeddings = np.load(embedd_test_path)
print(evidence_embeddings.shape)
evidence_embeddings = torch.from_numpy(evidence_embeddings).to(device1)

#load evidence
evidence_test_path = f'{data_dir}/test/evidence_test.csv'
evidence_df = pd.read_csv(evidence_test_path)

#load qa data
qa_df=pd.read_csv(f'{data_dir}/test/qa_test.csv') #data=df[['question','long_answers']] # questions=data['question'] #references = [row.to_dict() for i, row in df.iterrows() if i < len(questions)]
qa_df.head()

(21586, 4096)

,id,sample_id,question,follow_up_questions,long_answers,short_answers
0,aee000f3-d2b0-4de5-8206-a96e9c203207,-7013890438520559398,Who has the highest goals in world football?,"[""Who has the highest goals in men's world int...","[""Ali Dael has the highest goals in men's worl...","[['Daei', 'Ali Daei'], ['Bican', 'Josef Bican'..."
1,b80ea7a2-5084-422f-94d1-e67e7e29819b,7089015503030534342,Who is the original artist of sound of silence?,['Who is the original artist of sound of silen...,[' The original artist of the song sound of si...,"[['Simon & Garfunkel', 'Paul Simon and Art Gar..."
2,a9c1319b-ed69-4b1b-8486-05ad3d444e22,8793099883447006698,When was the first apple i phone made?,"['When was the first apple i phone released?',...",['The iPhone beta was created in 2004 to test ...,"[['June 29, 2007'], ['2004'], ['June 29, 2007...."
3,b07f0006-0628-49cf-b5b4-c0c7e88d3190,-881464876144297194,Who played the weasley brothers in harry potter?,['Who played Bill weasley in Harry Potter and...,['Rupert Grint played Ron Weasley in all the H...,"[['Richard Fish'], ['Chris Rankin'], ['James P..."
4,a9d31e99-6402-4a41-a4af-52de1aebeb16,1650309494326541834,How many state parks are there in virginia?,['How many state parks are there in virginia i...,['When the Virginia state park system was form...,"[['six'], ['38'], ['6'], ['38']]"

In [7]:
#load quantized model
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_storage=torch.bfloat16,
)

# load model with tokenizer
model = AutoModel.from_pretrained(
    'nvidia/NV-Embed-v2', 
    trust_remote_code=True,
    quantization_config = bnb_config,
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage =True,
)
model.eval()

Loading checkpoint shards: 100%|██████████| 4/4 [00:04<00:00,  1.14s/it]

NVEmbedModel(
  (latent_attention_model): LatentAttentionModel(
    (cross_attend_blocks): ModuleList(
      (0): PreNorm(
        (fn): Attention(
          (to_q): Linear4bit(in_features=4096, out_features=32768, bias=False)
          (to_kv): Linear4bit(in_features=4096, out_features=65536, bias=False)
          (to_out): Linear4bit(in_features=32768, out_features=4096, bias=False)
        )
        (norm): LayerNorm((4096,), eps=1e-05, elementwise_affine=True)
        (norm_context): LayerNorm((4096,), eps=1e-05, elementwise_affine=True)
      )
      (1): PreNorm(
        (fn): FeedForward(
          (net): Sequential(
            (0): Linear4bit(in_features=4096, out_features=32768, bias=True)
            (1): GEGLU()
            (2): Linear4bit(in_features=16384, out_features=4096, bias=True)
          )
        )
        (norm): LayerNorm((4096,), eps=1e-05, elementwise_affine=True)
      )
    )
  )
  (embedding_model): BidirectionalMistralModel(
    (embed_tokens): Embedding(32000, 4096)
    (layers): ModuleList(
      (0-31): 32 x MistralDecoderLayer(
        (self_attn): MistralSdpaAttention(
          (q_proj): Linear4bit(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear4bit(in_features=4096, out_features=1024, bias=False)
          (v_proj): Linear4bit(in_features=4096, out_features=1024, bias=False)
          (o_proj): Linear4bit(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): MistralRotaryEmbedding()
        )
        (mlp): MistralMLP(
          (gate_proj): Linear4bit(in_features=4096, out_features=14336, bias=False)
          (up_proj): Linear4bit(in_features=4096, out_features=14336, bias=False)
          (down_proj): Linear4bit(in_features=14336, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): MistralRMSNorm()
        (post_attention_layernorm): MistralRMSNorm()
      )
    )
    (norm): MistralRMSNorm()
  )
)

In [8]:
#load tokenizer
tokenizer_gen = AutoTokenizer.from_pretrained("meta-llama/Meta-Llama-3.1-8B-Instruct")
# cache_dir= '/raid/deallab/.cache')
tokenizer_gen.pad_token = tokenizer_gen.eos_token

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    # bnb_4bit_quant_type="nf4",
    # bnb_4bit_compute_dtype=torch.bfloat16,
    # bnb_4bit_use_double_quant=True,
    # bnb_4bit_quant_storage=torch.bfloat16,
)

model_gen = AutoModelForCausalLM.from_pretrained(
    "meta-llama/Meta-Llama-3.1-8B-Instruct",
    quantization_config=bnb_config,
    torch_dtype=torch.bfloat16,
    device_map= 'auto',
    # cache_dir= '/raid/deallab/.cache'
)
model_gen.eval()

Loading checkpoint shards: 100%|██████████| 4/4 [00:03<00:00,  1.33it/s]

LlamaForCausalLM(
  (model): LlamaModel(
    (embed_tokens): Embedding(128256, 4096)
    (layers): ModuleList(
      (0-31): 32 x LlamaDecoderLayer(
        (self_attn): LlamaSdpaAttention(
          (q_proj): Linear4bit(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear4bit(in_features=4096, out_features=1024, bias=False)
          (v_proj): Linear4bit(in_features=4096, out_features=1024, bias=False)
          (o_proj): Linear4bit(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear4bit(in_features=4096, out_features=14336, bias=False)
          (up_proj): Linear4bit(in_features=4096, out_features=14336, bias=False)
          (down_proj): Linear4bit(in_features=14336, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm()
        (post_attention_layernorm): LlamaRMSNorm()
      )
    )
    (norm): LlamaRMSNorm()
    (rotary_emb): LlamaRotaryEmbedding()
  )
  (lm_head): Linear(in_features=4096, out_features=128256, bias=False)
)

In [9]:
import pandas as pd
evidence_test_path = f'/raid/deallab/SF_RAG_Data/ASQA/test/evidence_test.csv'

evidence_text = pd.read_csv(evidence_test_path)

In [10]:
evidence_text

                                                    text
0      Document: International Federation of Football...
1      Document: International Federation of Football...
2      Document: International Federation of Football...
3      Document: International Federation of Football...
4      Document: International Federation of Football...
...                                                  ...
21581  Document: Sign of the Times (Harry Styles song...
21582  Document: Sign of the Times (Harry Styles song...
21583  Document: Sign of the Times (Harry Styles song...
21584  Document: Sign of the Times (Harry Styles song...
21585  Document: Sign of the Times (Harry Styles song...

[21586 rows x 1 columns]

In [6]:
# from langchain_text_splitters import TokenTextSplitter

# text_splitter = TokenTextSplitter(
#     chunk_size=500,  # 청크 크기를 10으로 설정합니다.
#     chunk_overlap=50,  # 청크 간 중복을 0으로 설정합니다.
# )
# # combined_text = " ".join(evidence_text_list)
# # texts = text_splitter.split_text(combined_text)
# split_texts = [text_splitter.split_text(text)[0] for text in evidence_text_list]
# print(split_texts[0])

In [72]:
# from langchain.retrievers import BM25Retriever, EnsembleRetriever
# from langchain.vectorstores import FAISS

# # bm25 retriever와 faiss retriever를 초기화합니다.
# bm25_retriever = BM25Retriever.from_texts(
#     evidence_text_list,
# )
# bm25_retriever.k = 10  # BM25Retriever의 검색 결과 개수를 1로 설정합니다.

# embedding = model
# faiss_vectorstore = FAISS.from_texts(
#     evidence_text,
#     embedding,
# )
# faiss_retriever = faiss_vectorstore.as_retriever(search_kwargs={"k": 2})

# # 앙상블 retriever를 초기화합니다.
# ensemble_retriever = EnsembleRetriever(
#     retrievers=[bm25_retriever, faiss_retriever],
#     weights=[0.7, 0.3],
# )

In [75]:
# from langchain_community.document_transformers import LongContextReorder

# def bm25_retrieve(query):
#     bm25_result = bm25_retriever.invoke(query)
#     bm25_docs=list()

#     print("[BM25 Retriever]")
#     for doc in bm25_result:
#         # print(f"Content: {doc.page_content}")
#         # print()
#         bm25_docs.append(doc.page_content)
#     reordering = LongContextReorder()
#     bm25_docs = reordering.transform_documents(bm25_docs)
#     return bm25_docs

In [7]:
# res=bm25_retrieve("Who has the highest goals in world football?")
# res

In [21]:
evidence_eval_path = f'{data_dir}/test/evidence_test_eval.csv'
eval_df = pd.read_csv(evidence_eval_path)
eval_df

,sample_id,title,text
0,-7013890438520559398,International Federation of Football History &...,Document: International Federation of Football...
1,-7013890438520559398,International Federation of Football History &...,Document: International Federation of Football...
2,-7013890438520559398,International Federation of Football History &...,Document: International Federation of Football...
3,-7013890438520559398,International Federation of Football History &...,Document: International Federation of Football...
4,-7013890438520559398,International Federation of Football History &...,Document: International Federation of Football...
...,...,...,...
21796,4198094437803531947,Sign of the Times (Harry Styles song),Document: Sign of the Times (Harry Styles song...
21797,4198094437803531947,Sign of the Times (Harry Styles song),Document: Sign of the Times (Harry Styles song...
21798,4198094437803531947,Sign of the Times (Harry Styles song),Document: Sign of the Times (Harry Styles song...
21799,4198094437803531947,Sign of the Times (Harry Styles song),Document: Sign of the Times (Harry Styles song...
21800,4198094437803531947,Sign of the Times (Harry Styles song),Document: Sign of the Times (Harry Styles song...

In [24]:
def match_sample_id(query_id, doc_id):
    query_sample_id=qa_df.loc[query_id,'sample_id']
    doc_sample_id=eval_df.loc[doc_id,'sample_id']
    if query_sample_id==doc_sample_id:
        return 1
    else:
        return 0

In [25]:
# retrive docs from the document embeddings
def retrieve_documents(query):
    max_length = 1024
    
    #query prefix
    task_name_to_instruct = {"example": "Given a question, retrieve passages that answer the question",}
    query_prefix = "Instruct: "+task_name_to_instruct["example"]+"\nQuery: "
    
    query_embedding = model.encode([query],instruction=query_prefix, max_length=max_length).to(device1)
    
    similarities = torch.nn.functional.cosine_similarity(query_embedding, evidence_embeddings)

    top_results = similarities.argsort(descending=True)[:10].cpu().detach().numpy()
    res=[evidence_df.loc[idx, 'text'] for idx in top_results if idx < len(evidence_df)]
    idx=[idx for idx in top_results if idx < len(evidence_df)]
    return res, idx

In [7]:
def summarize(query, docs):
    prompt = """
    In a Retrieval Augmentation Generation system, documents close to the query vector are as follows:
    ---------------------
    {0}
    ---------------------
    Identify entities and contexts in a query, and use them to extract and summarize only relevant content from documents.
    Query: {1}
    Answer:
    """.format('\n'.join(docs), query)
    input_ids = tokenizer_gen.apply_chat_template([{"role":'user', "content":prompt}], return_tensors='pt').to(device2)

    attention_mask = (input_ids != tokenizer_gen.pad_token_id).long().to(device2)

    out = model_gen.generate(input_ids, attention_mask=attention_mask, pad_token_id=tokenizer_gen.pad_token_id, max_new_tokens = 512)
    res = tokenizer_gen.decode(out[0]).split('<|end_header_id|>')[-1] 
    return re.sub('\n|<\|eot_id\|>', '', res)

In [12]:
def total_answer(query, docs):
    prompt = """
    Context information is below.
    ---------------------
    {0}
    ---------------------
    Given the context information and not prior knowledge, answer the query.
    1. The query is an ambiguous question.
    2. Therefore, you must include the contents according to the various interpretations of the query in one answer by utilizing the given context.
    3. Each content according to the various interpretations of the query must be explained in one or two sentences.
    4. The total answer must be 5 sentences or less.
    Do not comment your answer and strictly follow this instructions.
    Query: {1}
    Answer:
    """.format('\n'.join(docs), query)
    input_ids = tokenizer_gen.apply_chat_template([{"role":'user', "content":prompt}], return_tensors='pt').to(device1)

    attention_mask = (input_ids != tokenizer_gen.pad_token_id).long().to(device1)

    out = model_gen.generate(input_ids, attention_mask=attention_mask, pad_token_id=tokenizer_gen.pad_token_id, max_new_tokens = 512)
    res = tokenizer_gen.decode(out[0]).split('<|end_header_id|>')[-1] 
    return re.sub('\n|<\|eot_id\|>', '', res)

In [13]:
def various_answer(query, docs, first_ans=None):
    prompt = """
    Context information is below.
    ---------------------
    {0}
    ---------------------
    Given the context information and not prior knowledge, answer the query.
    There may be multiple golden short answers in your answers, and they should be explained.
    Query: {1}{2}
    Answer:
    """.format('\n'.join(docs), query, f"Prior Answer: {first_ans}")
    input_ids = tokenizer_gen.apply_chat_template([{"role":'user', "content":prompt}], return_tensors='pt').to(device1)

    attention_mask = (input_ids != tokenizer_gen.pad_token_id).long().to(device1)

    out = model_gen.generate(input_ids, attention_mask=attention_mask, pad_token_id=tokenizer_gen.pad_token_id, max_new_tokens = 512)
    res = tokenizer_gen.decode(out[0]).split('<|end_header_id|>')[-1] 
    return re.sub('\n|<\|eot_id\|>', '', res)

In [30]:
def answer(query, context):
    prompt = """
    Context information is below.
    ---------------------
    {0}
    ---------------------
    Given the context information and not prior knowledge, answer the query.
    Query: {1}
    Answer:
    """.format('\n'.join(context), query)
    input_ids = tokenizer_gen.apply_chat_template([{"role":'user', "content":prompt}], return_tensors='pt').to(device1)

    attention_mask = (input_ids != tokenizer_gen.pad_token_id).long().to(device1)

    out = model_gen.generate(input_ids, attention_mask=attention_mask, pad_token_id=tokenizer_gen.pad_token_id, max_new_tokens = 512)
    res = tokenizer_gen.decode(out[0]).split('<|end_header_id|>')[-1] 
    return re.sub('\n|<\|eot_id\|>', '', res)

In [43]:
# def HyDE(query, docs):
#     prompt = """
#     In a Retrieval Augmentation Generation system, documents close to the query vector are as follows:
#     ---------------------
#     {0}
#     ---------------------
#     Identify entities and contexts in a query, and use them to extract and summarize only relevant content from documents.
#     Query: {1}
#     Answer:
#     """.format('\n'.join(docs), query)
#     input_ids = tokenizer_gen.apply_chat_template([{"role":'user', "content":prompt}], return_tensors='pt').to(device2)

#     attention_mask = (input_ids != tokenizer_gen.pad_token_id).long().to(device2)

#     out = model_gen.generate(input_ids, attention_mask=attention_mask, pad_token_id=tokenizer_gen.pad_token_id, max_new_tokens = 512)
#     res = tokenizer_gen.decode(out[0]).split('<|end_header_id|>')[-1] 
#     return [re.sub('\n|<\|eot_id\|>', '', res)]

In [ ]:
# tokenizer = AutoTokenizer.from_pretrained('BAAI/bge-reranker-v2-m3')
# model = AutoModelForSequenceClassification.from_pretrained('BAAI/bge-reranker-v2-m3')
# model.eval()

# with torch.no_grad():
#     inputs = tokenizer(pairs, padding=True, truncation=True, return_tensors='pt', max_length=512)
#     scores = model(**inputs, return_dict=True).logits.view(-1, ).float()
#     scores = exp_normalize(scores.numpy()) 
    
# print(np.round(scores * 100, 2))

# Baseline

In [22]:
qa_df

,id,sample_id,question,follow_up_questions,long_answers,short_answers
0,aee000f3-d2b0-4de5-8206-a96e9c203207,-7013890438520559398,Who has the highest goals in world football?,"[""Who has the highest goals in men's world int...","[""Ali Dael has the highest goals in men's worl...","[['Daei', 'Ali Daei'], ['Bican', 'Josef Bican'..."
1,b80ea7a2-5084-422f-94d1-e67e7e29819b,7089015503030534342,Who is the original artist of sound of silence?,['Who is the original artist of sound of silen...,[' The original artist of the song sound of si...,"[['Simon & Garfunkel', 'Paul Simon and Art Gar..."
2,a9c1319b-ed69-4b1b-8486-05ad3d444e22,8793099883447006698,When was the first apple i phone made?,"['When was the first apple i phone released?',...",['The iPhone beta was created in 2004 to test ...,"[['June 29, 2007'], ['2004'], ['June 29, 2007...."
3,b07f0006-0628-49cf-b5b4-c0c7e88d3190,-881464876144297194,Who played the weasley brothers in harry potter?,['Who played Bill weasley in Harry Potter and...,['Rupert Grint played Ron Weasley in all the H...,"[['Richard Fish'], ['Chris Rankin'], ['James P..."
4,a9d31e99-6402-4a41-a4af-52de1aebeb16,1650309494326541834,How many state parks are there in virginia?,['How many state parks are there in virginia i...,['When the Virginia state park system was form...,"[['six'], ['38'], ['6'], ['38']]"
...,...,...,...,...,...,...
933,abf0fb83-9d44-440f-9d8a-b0b8a0f21f65,5398357621914791303,Where did the practice of baptism come from?,"['Where did the baptism practice come from?', ...",['The practice of baptism comes from John the ...,"[['John the Baptist'], ['Middle East'], ['Tevi..."
934,32ad2c7c-355a-4247-b800-06446a55124c,-7709444270791071714,Who sings the song i'm just a love machine?,"['Who sings the song ""Love Machine"" from 1975?...",['Love Machine is a 1975 single recorded by Mo...,"[['The Miracles'], ['Billy Griffin'], ['Bobby ..."
935,f821f32d-bd1d-4979-b81d-2565e0cf4786,6163437434205590885,When was the last time man united were in the ...,"['As of the 2016-2017 season, when was the las...",['Manchester United Football Club is an Englis...,"[['2015–16'], ['2015–16'], ['2013–14']]"
936,9a80603c-be09-4fc3-beba-50be12c0e7e9,8651936974639934250,Who sings beautiful girl in singin in the rain?,['Who sings beautiful girl in the 1952 stage m...,"[""Singin' in the Rain is a 1952 American music...","[['Don Lockwood and Fans'], ['Female Chorus (i..."
937,477e3c88-f2f7-4cfd-9c4b-e2932db26aa9,4198094437803531947,Who wrote harry styles sign of the times lyrics?,['Who from Redditch wrote harry styles sign of...,['Sign of the Times is the debut single by Eng...,"[['Harry Styles'], ['Jeff Bhasker'], ['Alex Sa..."

In [35]:
from tqdm import tqdm
from evaluation import evaluate

set_seed(24)

stop_iteration = 20

scores_list=[]
for idx, row in tqdm(qa_df.iterrows(), total=min([stop_iteration, len(qa_df)])):
    if idx == stop_iteration: break
    query = row['question']
    retrieved_docs, doc_ids = retrieve_documents(query)
    tmp=0
    for doc_id in doc_ids:    
        tmp+=match_sample_id(idx, doc_id)
    print("Retrival Match Rate:", tmp/len(retrieved_docs))
    ans=answer(query,retrieved_docs)
    print('Final ans:', ans)
    scores=evaluate([ans], [row.to_dict()])
    scores_list.append(scores)
    scores_df=pd.DataFrame(scores_list)
    print(scores)
        
scores_df=pd.DataFrame(scores_list)
scores_df.mean()

  0%|          | 0/20 [00:00<?, ?it/s]

Retrival Match Rate: 0.5
Final ans: Based on the provided information, the top goalscorers in international football are:1. Ali Daei - 109 goals2. Cristiano Ronaldo - 99 goals3. Ferenc Puskás - 84 goals4. Kunishige Kamamoto - 80 goals5. Godfrey Chitalu - 79 goals6. Hussein Saeed - 78 goals7. Zainal Abidin - 78 goals8. Pelé - 77 goals9. Bashar Abdullah - 75 goals10. Sunil Chhetri - 72 goalsHowever, the player with the highest goals in world football is not explicitly stated in the provided information.
Based on the provided information, the top goalscorers in international football are:1. Ali Daei - 109 goals2. Cristiano Ronaldo - 99 goals3. Ferenc Puskás - 84 goals4. Kunishige Kamamoto - 80 goals5. Godfrey Chitalu - 79 goals6. Hussein Saeed - 78 goals7. Zainal Abidin - 78 goals8. Pelé - 77 goals9. Bashar Abdullah - 75 goals10. Sunil Chhetri - 72 goalsHowever, the player with the highest goals in world football is not explicitly stated in the provided information.
Who has the highest goals in world football?
["Who has the highest goals in men's world international football?", "Who has the highest goals all-time in men's football?", "Who has the highest goals in women's world international football?"]
[['Daei', 'Ali Daei'], ['Bican', 'Josef Bican'], ['Sinclair', 'Christine Sinclair']]

  5%|▌         | 1/20 [00:12<04:06, 12.99s/it]

follow question : Who has the highest goals in men's world international football?
short answer : ['Daei', 'Ali Daei']
{'score': 0.323673278093338, 'start': 88, 'end': 96, 'answer': 'Ali Daei'}
follow question : Who has the highest goals all-time in men's football?
short answer : ['Bican', 'Josef Bican']
{'score': 0.01449085958302021, 'start': 88, 'end': 96, 'answer': 'Ali Daei'}
follow question : Who has the highest goals in women's world international football?
short answer : ['Sinclair', 'Christine Sinclair']
{'score': 0.01846776157617569, 'start': 88, 'end': 96, 'answer': 'Ali Daei'}
{'rougeLsum': 24.277456647398843, 'length': 78.0, 'str_em': 33.33333333333333, 'Disambig-F1': 33.33333333333333}
Retrival Match Rate: 1.0
Final ans: The original artist of "The Sound of Silence" is Simon & Garfunkel, an American music duo composed of Paul Simon and Art Garfunkel.
The original artist of "The Sound of Silence" is Simon & Garfunkel, an American music duo composed of Paul Simon and Art Garfunkel.
Who is the original artist of sound of silence?
['Who is the original artist of sound of silence, the song, released in 1964?', 'Who is the original artist of sound of silence, the album?', 'Who is the original artist of sound of silence, the song, released in 2016?']
[['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon'], ['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon'], ['Dami Im']]

 10%|█         | 2/20 [00:18<02:29,  8.32s/it]

follow question : Who is the original artist of sound of silence, the song, released in 1964?
short answer : ['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon']
{'score': 0.08147318661212921, 'start': 49, 'end': 66, 'answer': 'Simon & Garfunkel'}
follow question : Who is the original artist of sound of silence, the album?
short answer : ['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon']
{'score': 0.9712766408920288, 'start': 49, 'end': 66, 'answer': 'Simon & Garfunkel'}
follow question : Who is the original artist of sound of silence, the song, released in 2016?
short answer : ['Dami Im']
{'score': 0.5759341716766357, 'start': 49, 'end': 66, 'answer': 'Simon & Garfunkel'}
{'rougeLsum': 35.44303797468354, 'length': 23.0, 'str_em': 66.66666666666666, 'Disambig-F1': 66.66666666666666}
Retrival Match Rate: 0.9
Final ans: The first iPhone was created in 2004, as a beta version, but it was never released to the public. The first iPhone that was officially launched and made accessible to the public was released on June 29, 2007.
The first iPhone was created in 2004, as a beta version, but it was never released to the public. The first iPhone that was officially launched and made accessible to the public was released on June 29, 2007.
When was the first apple i phone made?
['When was the first apple i phone released?', 'When was the first apple i phone for beta testing made?', 'When was the first apple i phone 1 made?', 'When was the first apple i phone beta made?']
[['June 29, 2007'], ['2004'], ['June 29, 2007.'], ['2004.']]

 15%|█▌        | 3/20 [00:24<02:09,  7.63s/it]

follow question : When was the first apple i phone released?
short answer : ['June 29, 2007']
{'score': 0.2979375422000885, 'start': 194, 'end': 207, 'answer': 'June 29, 2007'}
follow question : When was the first apple i phone for beta testing made?
short answer : ['2004']
{'score': 0.9476490616798401, 'start': 32, 'end': 36, 'answer': '2004'}
follow question : When was the first apple i phone 1 made?
short answer : ['June 29, 2007.']
{'score': 0.8698769211769104, 'start': 32, 'end': 36, 'answer': '2004'}
follow question : When was the first apple i phone beta made?
short answer : ['2004.']
{'score': 0.9172279834747314, 'start': 32, 'end': 36, 'answer': '2004'}
{'rougeLsum': 58.82352941176471, 'length': 38.0, 'str_em': 100.0, 'Disambig-F1': 75.0}
Retrival Match Rate: 0.9
Final ans: The Weasley brothers were played by James Phelps and Oliver Phelps, who played the roles of Fred and George Weasley respectively.
The Weasley brothers were played by James Phelps and Oliver Phelps, who played the roles of Fred and George Weasley respectively.
Who played the weasley brothers in harry potter?
['Who played  Bill weasley in Harry Potter and the Prisoner of Azkaban?', 'Who played percy weasley in harry potter?', 'Who played fred weasley in harry potter?', 'Who played ron weasley in harry potter?', 'Who played george weasley in harry potter?', 'Who played  Bill weasley in harry potter (2001-2011)?']
[['Richard Fish'], ['Chris Rankin'], ['James Phelps'], ['Rupert Grint'], ['Oliver Phelps'], ['Domhnall Gleeson']]

 20%|██        | 4/20 [00:29<01:42,  6.41s/it]

follow question : Who played  Bill weasley in Harry Potter and the Prisoner of Azkaban?
short answer : ['Richard Fish']
{'score': 0.0022090268321335316, 'start': 36, 'end': 66, 'answer': 'James Phelps and Oliver Phelps'}
follow question : Who played percy weasley in harry potter?
short answer : ['Chris Rankin']
{'score': 0.5648441910743713, 'start': 36, 'end': 66, 'answer': 'James Phelps and Oliver Phelps'}
follow question : Who played fred weasley in harry potter?
short answer : ['James Phelps']
{'score': 0.5998745560646057, 'start': 36, 'end': 66, 'answer': 'James Phelps and Oliver Phelps'}
follow question : Who played ron weasley in harry potter?
short answer : ['Rupert Grint']
{'score': 0.566528856754303, 'start': 36, 'end': 66, 'answer': 'James Phelps and Oliver Phelps'}
follow question : Who played george weasley in harry potter?
short answer : ['Oliver Phelps']
{'score': 0.46838927268981934, 'start': 53, 'end': 66, 'answer': 'Oliver Phelps'}
follow question : Who played  Bill weasley in harry potter (2001-2011)?
short answer : ['Domhnall Gleeson']
{'score': 0.00666668638586998, 'start': 36, 'end': 66, 'answer': 'James Phelps and Oliver Phelps'}
{'rougeLsum': 25.210084033613445, 'length': 21.0, 'str_em': 33.33333333333333, 'Disambig-F1': 26.190476190476193}
Retrival Match Rate: 0.4
Final ans: According to the provided context information, there are 38 state parks in Virginia.
According to the provided context information, there are 38 state parks in Virginia.
How many state parks are there in virginia?
['How many state parks are there in virginia in 1936?', 'How many state parks are there in virginia in 2016?', 'How many state parks were there when the state park system formed in Virginia?', 'How many state parks were there in Virginia as of 2016?']
[['six'], ['38'], ['6'], ['38']]

 25%|██▌       | 5/20 [00:32<01:20,  5.38s/it]

follow question : How many state parks are there in virginia in 1936?
short answer : ['six']
{'score': 0.0019380656303837895, 'start': 57, 'end': 59, 'answer': '38'}
follow question : How many state parks are there in virginia in 2016?
short answer : ['38']
{'score': 0.4065036177635193, 'start': 57, 'end': 59, 'answer': '38'}
follow question : How many state parks were there when the state park system formed in Virginia?
short answer : ['6']
{'score': 0.785505473613739, 'start': 57, 'end': 59, 'answer': '38'}
follow question : How many state parks were there in Virginia as of 2016?
short answer : ['38']
{'score': 0.43257200717926025, 'start': 57, 'end': 59, 'answer': '38'}
{'rougeLsum': 29.78723404255319, 'length': 13.0, 'str_em': 50.0, 'Disambig-F1': 50.0}
Retrival Match Rate: 0.5
Final ans: Dua Lipa performed at the opening ceremony preceding the final, along with Jamaican rapper Sean Paul as a special guest. The UEFA Champions League Anthem was performed by Slovenian–Croatian cello duo 2Cellos.
Dua Lipa performed at the opening ceremony preceding the final, along with Jamaican rapper Sean Paul as a special guest. The UEFA Champions League Anthem was performed by Slovenian–Croatian cello duo 2Cellos.
Who performed at the champions league final 2018?
['Who are the teams that performed in competition at the champions league final 2018?', 'Who performed best at the champions league final 2018, winning man of the match?', 'Who performed at the opening ceremony of the champions league final 2018?', 'Who performed the anthem at the champions league final 2018?']
[['Real Madrid and Liverpool', 'Liverpool', 'Real Madrid'], ['Gareth Bale', 'Bale'], ['Dua Lipa', 'Sean Paul', 'Dua Lipa and Sean Paul'], ['2Cellos', 'Luka Šulić and Stjepan Hauser', 'Luka Šulić', '2CΞLLOS', 'Stjepan Hauser']]

 30%|███       | 6/20 [00:38<01:18,  5.60s/it]

follow question : Who are the teams that performed in competition at the champions league final 2018?
short answer : ['Real Madrid and Liverpool', 'Liverpool', 'Real Madrid']
{'score': 0.0037635716143995523, 'start': 171, 'end': 208, 'answer': 'Slovenian–Croatian cello duo 2Cellos.'}
follow question : Who performed best at the champions league final 2018, winning man of the match?
short answer : ['Gareth Bale', 'Bale']
{'score': 0.5292783975601196, 'start': 0, 'end': 8, 'answer': 'Dua Lipa'}
follow question : Who performed at the opening ceremony of the champions league final 2018?
short answer : ['Dua Lipa', 'Sean Paul', 'Dua Lipa and Sean Paul']
{'score': 0.47206616401672363, 'start': 0, 'end': 8, 'answer': 'Dua Lipa'}
follow question : Who performed the anthem at the champions league final 2018?
short answer : ['2Cellos', 'Luka Šulić and Stjepan Hauser', 'Luka Šulić', '2CΞLLOS', 'Stjepan Hauser']
{'score': 0.7660547494888306, 'start': 200, 'end': 207, 'answer': '2Cellos'}
{'rougeLsum': 51.66666666666667, 'length': 32.0, 'str_em': 50.0, 'Disambig-F1': 50.0}
Retrival Match Rate: 0.3
Final ans: Harlan.
Harlan.
Who killed the man in thelma and louise?
['Which character killed the man in thelma and louise?', 'Which actor killed the man in thelma and louise?', 'Who is the character that kills Harlan in the film Thelma and Louise?', 'Who is the actor of the character that killed a man in the film Thelma and Louise?']
[['Louise Elizabeth Sawyer', 'Louise'], ['Susan Sarandon', 'Susan Abigail Sarandon'], ['Louise Elizabeth Sawyer', 'Louise'], ['Susan Sarandon']]

 35%|███▌      | 7/20 [00:41<00:59,  4.58s/it]

follow question : Which character killed the man in thelma and louise?
short answer : ['Louise Elizabeth Sawyer', 'Louise']
{'score': 0.00506547698751092, 'start': 0, 'end': 6, 'answer': 'Harlan'}
follow question : Which actor killed the man in thelma and louise?
short answer : ['Susan Sarandon', 'Susan Abigail Sarandon']
{'score': 0.01647324301302433, 'start': 0, 'end': 6, 'answer': 'Harlan'}
follow question : Who is the character that kills Harlan in the film Thelma and Louise?
short answer : ['Louise Elizabeth Sawyer', 'Louise']
{'score': 0.0001407041127094999, 'start': 0, 'end': 6, 'answer': 'Harlan'}
follow question : Who is the actor of the character that killed a man in the film Thelma and Louise?
short answer : ['Susan Sarandon']
{'score': 0.27317699790000916, 'start': 0, 'end': 6, 'answer': 'Harlan'}
{'rougeLsum': 10.526315789473683, 'length': 1.0, 'str_em': 0.0, 'Disambig-F1': 0.0}
Retrival Match Rate: 0.9
Final ans: Charlie Kelly is played by Charlie Day.
Charlie Kelly is played by Charlie Day.
Who plays charlie on it's always sunny?
["Who does Charlie Day play on It's Always Sunny in Philadelphia?", "Who plays Charlie Kelly on It's Always Sunny in Philadelphia?"]
[['Charlie Kelly'], ['Charlie Day']]

 40%|████      | 8/20 [00:43<00:46,  3.90s/it]

follow question : Who does Charlie Day play on It's Always Sunny in Philadelphia?
short answer : ['Charlie Kelly']
{'score': 0.9911195039749146, 'start': 0, 'end': 13, 'answer': 'Charlie Kelly'}
follow question : Who plays Charlie Kelly on It's Always Sunny in Philadelphia?
short answer : ['Charlie Day']
{'score': 0.9776415824890137, 'start': 27, 'end': 38, 'answer': 'Charlie Day'}
{'rougeLsum': 37.03703703703704, 'length': 7.0, 'str_em': 100.0, 'Disambig-F1': 100.0}
Retrival Match Rate: 0.4
Final ans: The Los Angeles Lakers have won the NBA Finals 16 times.
The Los Angeles Lakers have won the NBA Finals 16 times.
How many times have the lakers won the finals?
['As of 2017, how many times have the lakers won the finals?', 'As of 2016, how many times have the Lakers won the finals?', 'As of 2015, how many times have the Lakers won the finals?']
[['16'], ['16'], ['16']]

 45%|████▌     | 9/20 [00:47<00:40,  3.69s/it]

follow question : As of 2017, how many times have the lakers won the finals?
short answer : ['16']
{'score': 0.8386049270629883, 'start': 47, 'end': 49, 'answer': '16'}
follow question : As of 2016, how many times have the Lakers won the finals?
short answer : ['16']
{'score': 0.8818942904472351, 'start': 47, 'end': 49, 'answer': '16'}
follow question : As of 2015, how many times have the Lakers won the finals?
short answer : ['16']
{'score': 0.7783189415931702, 'start': 47, 'end': 49, 'answer': '16'}
{'rougeLsum': 25.454545454545457, 'length': 11.0, 'str_em': 100.0, 'Disambig-F1': 100.0}
Retrival Match Rate: 0.7
Final ans: According to the provided context, the Indian National Congress is in power in the following states:1. Punjab2. Chhattisgarh3. Rajasthan4. Madhya Pradesh5. Puducherry (union territory)Additionally, the party is in a coalition government in the following states:1. Maharashtra (as part of the Maha Vikas Aghadi coalition)2. Jharkhand (as a junior ally with Jharkhand Mukti Morcha)Therefore, the total number of states and union territories where the Indian National Congress is in power is 6.
According to the provided context, the Indian National Congress is in power in the following states:1. Punjab2. Chhattisgarh3. Rajasthan4. Madhya Pradesh5. Puducherry (union territory)Additionally, the party is in a coalition government in the following states:1. Maharashtra (as part of the Maha Vikas Aghadi coalition)2. Jharkhand (as a junior ally with Jharkhand Mukti Morcha)Therefore, the total number of states and union territories where the Indian National Congress is in power is 6.
How many states in india are under congress?
['How many states plus territories in india are under congress?', 'How many states alone in india are under congress?']
[['7'], ['5']]

 50%|█████     | 10/20 [00:57<00:58,  5.86s/it]

follow question : How many states plus territories in india are under congress?
short answer : ['7']
{'score': 0.9664148688316345, 'start': 489, 'end': 490, 'answer': '6'}
follow question : How many states alone in india are under congress?
short answer : ['5']
{'score': 0.30833786725997925, 'start': 489, 'end': 490, 'answer': '6'}
{'rougeLsum': 24.817518248175183, 'length': 71.0, 'str_em': 50.0, 'Disambig-F1': 0.0}
Retrival Match Rate: 1.0
Final ans: Fruma-Sarah is the late wife of Lazar Wolf, a wealthy butcher in the village of Anatevka. She rises from the grave in Tevye's dream to warn of severe retribution if Tzeitel marries Lazar.
Fruma-Sarah is the late wife of Lazar Wolf, a wealthy butcher in the village of Anatevka. She rises from the grave in Tevye's dream to warn of severe retribution if Tzeitel marries Lazar.
Who is fruma sarah in fiddler on the roof?
['Who played fruma sarah in the 1971 film, Fiddler on the Roof?', 'Who played Fruma Sarah in the original 1964 Broadway cast of Fiddler on the Roof?', 'Who is the character of Fruma Sarah in Fiddler on the Roof?', 'Who played Fruma Sarah in the 2015-2016 Broadway Revival of Fiddler on the Roof?']
[['Ruth Madoc'], ['Carol Sawyer Yussel'], ['a ghostly depiction of the late wife of Lazar Wolf'], ['Jessica Vosk']]

 55%|█████▌    | 11/20 [01:03<00:52,  5.80s/it]

follow question : Who played fruma sarah in the 1971 film, Fiddler on the Roof?
short answer : ['Ruth Madoc']
{'score': 0.0004273341619409621, 'start': 118, 'end': 123, 'answer': 'Tevye'}
follow question : Who played Fruma Sarah in the original 1964 Broadway cast of Fiddler on the Roof?
short answer : ['Carol Sawyer Yussel']
{'score': 0.0032899868674576283, 'start': 118, 'end': 123, 'answer': 'Tevye'}
follow question : Who is the character of Fruma Sarah in Fiddler on the Roof?
short answer : ['a ghostly depiction of the late wife of Lazar Wolf']
{'score': 0.5539121627807617, 'start': 32, 'end': 42, 'answer': 'Lazar Wolf'}
follow question : Who played Fruma Sarah in the 2015-2016 Broadway Revival of Fiddler on the Roof?
short answer : ['Jessica Vosk']
{'score': 0.0012725809356197715, 'start': 118, 'end': 123, 'answer': 'Tevye'}
{'rougeLsum': 23.35766423357664, 'length': 33.0, 'str_em': 0.0, 'Disambig-F1': 10.0}
Retrival Match Rate: 0.9
Final ans: July 9, 1991
July 9, 1991
When did toronto host the mlb all-star game?
['What date did toronto host the mlb all-star game?', 'Which all-star game did toronto host?']
[['July 9, 1991'], ['1991 Major League Baseball All-Star Game', 'the 62nd playing of the midsummer classic']]

 60%|██████    | 12/20 [01:06<00:40,  5.00s/it]

follow question : What date did toronto host the mlb all-star game?
short answer : ['July 9, 1991']
{'score': 0.010271838866174221, 'start': 0, 'end': 12, 'answer': 'July 9, 1991'}
follow question : Which all-star game did toronto host?
short answer : ['1991 Major League Baseball All-Star Game', 'the 62nd playing of the midsummer classic']
{'score': 1.9473118300084025e-06, 'start': 8, 'end': 12, 'answer': '1991'}
{'rougeLsum': 23.076923076923077, 'length': 3.0, 'str_em': 50.0, 'Disambig-F1': 64.28571428571428}
Retrival Match Rate: 0.7
Final ans: The car driven by Grace Kelly in the 1955 film "To Catch a Thief" is a metallic blue 1953 Sunbeam Alpine Mk I.
The car driven by Grace Kelly in the 1955 film "To Catch a Thief" is a metallic blue 1953 Sunbeam Alpine Mk I.
What kind of car in to catch a thief?
['What kind of car in to catch a thief in terms of model?', 'What kind of car in to catch a thief in terms of automobile make?']
[['Sunbeam Alpine', '1953 Sunbeam Alpine Mk I'], ['Rootes Group']]

 65%|██████▌   | 13/20 [01:11<00:33,  4.80s/it]

follow question : What kind of car in to catch a thief in terms of model?
short answer : ['Sunbeam Alpine', '1953 Sunbeam Alpine Mk I']
{'score': 0.33145755529403687, 'start': 90, 'end': 109, 'answer': 'Sunbeam Alpine Mk I'}
follow question : What kind of car in to catch a thief in terms of automobile make?
short answer : ['Rootes Group']
{'score': 0.32918521761894226, 'start': 90, 'end': 109, 'answer': 'Sunbeam Alpine Mk I'}
{'rougeLsum': 63.33333333333333, 'length': 23.0, 'str_em': 50.0, 'Disambig-F1': 44.44444444444445}
Retrival Match Rate: 0.8
Final ans: The last season of Jersey Shore aired from October 4, 2012, to December 20, 2012.
The last season of Jersey Shore aired from October 4, 2012, to December 20, 2012.
When did the last season of jersey shore air?
['When did season 4 of jersey shore first air?', 'When did season 4 of jersey shore last air?', 'When did season 5 of jersey shore first air?', 'When did season 5 of jersey shore last air?', 'When did season 6 of jersey shore first air?', 'When did season 6 of jersey shore last air?']
[['August 4, 2011'], ['October 20, 2011'], ['January 5, 2012'], ['March 15, 2012'], ['October 4, 2012'], ['December 20, 2012']]

 70%|███████   | 14/20 [01:14<00:26,  4.48s/it]

follow question : When did season 4 of jersey shore first air?
short answer : ['August 4, 2011']
{'score': 0.07297001779079437, 'start': 43, 'end': 58, 'answer': 'October 4, 2012'}
follow question : When did season 4 of jersey shore last air?
short answer : ['October 20, 2011']
{'score': 0.5013733506202698, 'start': 43, 'end': 58, 'answer': 'October 4, 2012'}
follow question : When did season 5 of jersey shore first air?
short answer : ['January 5, 2012']
{'score': 0.028503216803073883, 'start': 43, 'end': 58, 'answer': 'October 4, 2012'}
follow question : When did season 5 of jersey shore last air?
short answer : ['March 15, 2012']
{'score': 0.3522070348262787, 'start': 43, 'end': 58, 'answer': 'October 4, 2012'}
follow question : When did season 6 of jersey shore first air?
short answer : ['October 4, 2012']
{'score': 0.03184444457292557, 'start': 43, 'end': 58, 'answer': 'October 4, 2012'}
follow question : When did season 6 of jersey shore last air?
short answer : ['December 20, 2012']
{'score': 0.3431626856327057, 'start': 43, 'end': 58, 'answer': 'October 4, 2012'}
{'rougeLsum': 38.888888888888886, 'length': 15.0, 'str_em': 33.33333333333333, 'Disambig-F1': 44.44444444444444}
Retrival Match Rate: 0.7
Final ans: The plane crash occurred in Season 8 of Grey's Anatomy, specifically in the episode "Flight" (Season 8, Episode 24).
The plane crash occurred in Season 8 of Grey's Anatomy, specifically in the episode "Flight" (Season 8, Episode 24).
What season of greys anatomy was the plane crash?
["What season of Grey's Anatomy was the plane crash involving six doctors?", "What season of Grey's Anatomy was the plane crash in Seattle that brought memories of a previous plane crash?", "What season of Grey's Anatomy was the plane crash that claimed the life of Lexie Grey?", "What season of Grey's Anatomy was the plane crash in downtown Seattle?"]
[['season 8'], ['season 11'], ['8'], ['11']]

 75%|███████▌  | 15/20 [01:18<00:21,  4.28s/it]

follow question : What season of Grey's Anatomy was the plane crash involving six doctors?
short answer : ['season 8']
{'score': 0.6553112864494324, 'start': 28, 'end': 36, 'answer': 'Season 8'}
follow question : What season of Grey's Anatomy was the plane crash in Seattle that brought memories of a previous plane crash?
short answer : ['season 11']
{'score': 0.6392587423324585, 'start': 28, 'end': 36, 'answer': 'Season 8'}
follow question : What season of Grey's Anatomy was the plane crash that claimed the life of Lexie Grey?
short answer : ['8']
{'score': 0.5412282943725586, 'start': 28, 'end': 36, 'answer': 'Season 8'}
follow question : What season of Grey's Anatomy was the plane crash in downtown Seattle?
short answer : ['11']
{'score': 0.6328945159912109, 'start': 28, 'end': 36, 'answer': 'Season 8'}
{'rougeLsum': 43.07692307692307, 'length': 19.0, 'str_em': 50.0, 'Disambig-F1': 54.166666666666664}
Retrival Match Rate: 0.1
Final ans: According to the provided information, as of March 2018-2019, Oriental Bank of Commerce has 2390 branches in India.
According to the provided information, as of March 2018-2019, Oriental Bank of Commerce has 2390 branches in India.
Number of branches of oriental bank of commerce in india?
['As per the March 2018-2019 report, what is the number of branches of oriental bank of commerce in india?', 'What is the number of branches of oriental bank of commerce in india after amalgamation of Global Trust Bank?', 'Number of branches of oriental bank of commerce in india after expected merger with United Bank of India in 2020?']
[['2390'], ['1092'], ['11,437']]

 80%|████████  | 16/20 [01:22<00:16,  4.18s/it]

follow question : As per the March 2018-2019 report, what is the number of branches of oriental bank of commerce in india?
short answer : ['2390']
{'score': 0.8898491859436035, 'start': 92, 'end': 96, 'answer': '2390'}
follow question : What is the number of branches of oriental bank of commerce in india after amalgamation of Global Trust Bank?
short answer : ['1092']
{'score': 0.8336718082427979, 'start': 92, 'end': 96, 'answer': '2390'}
follow question : Number of branches of oriental bank of commerce in india after expected merger with United Bank of India in 2020?
short answer : ['11,437']
{'score': 0.48598453402519226, 'start': 92, 'end': 96, 'answer': '2390'}
{'rougeLsum': 26.41509433962264, 'length': 18.0, 'str_em': 33.33333333333333, 'Disambig-F1': 33.33333333333333}
Retrival Match Rate: 0.5
Final ans: The Rams relocated to St. Louis in 1995, after the 1994 NFL season.
The Rams relocated to St. Louis in 1995, after the 1994 NFL season.
When did the rams go to st louis?
['In what year did the rams go to St. Louis?', 'What was the first game the Rams played in St. Louis?']
[['1995'], ['September 10, 1995']]

 85%|████████▌ | 17/20 [01:25<00:11,  3.85s/it]

follow question : In what year did the rams go to St. Louis?
short answer : ['1995']
{'score': 0.6700248122215271, 'start': 35, 'end': 39, 'answer': '1995'}
follow question : What was the first game the Rams played in St. Louis?
short answer : ['September 10, 1995']
{'score': 0.33787354826927185, 'start': 35, 'end': 39, 'answer': '1995'}
{'rougeLsum': 20.253164556962027, 'length': 13.0, 'str_em': 50.0, 'Disambig-F1': 75.0}
Retrival Match Rate: 0.8
Final ans: The Voortrekkers arrived in South Africa from 1835 to 1840, with the first two parties leaving in September 1835, led by Louis Tregardt and Hans van Rensburg.
The Voortrekkers arrived in South Africa from 1835 to 1840, with the first two parties leaving in September 1835, led by Louis Tregardt and Hans van Rensburg.
When did the voortrekkers arrive in south africa?
['When did the first wave of voortrekkers arrive in south africa?', 'When did the voortrekkers exploratory treks arrive in south africa?']
[['1836', '1836 onwards'], ['February 1835']]

 90%|█████████ | 18/20 [01:30<00:08,  4.12s/it]

follow question : When did the first wave of voortrekkers arrive in south africa?
short answer : ['1836', '1836 onwards']
{'score': 0.40410587191581726, 'start': 46, 'end': 58, 'answer': '1835 to 1840'}
follow question : When did the voortrekkers exploratory treks arrive in south africa?
short answer : ['February 1835']
{'score': 0.5072824358940125, 'start': 46, 'end': 58, 'answer': '1835 to 1840'}
{'rougeLsum': 40.0, 'length': 27.0, 'str_em': 0.0, 'Disambig-F1': 20.0}
Retrival Match Rate: 0.8
Final ans: In the 1999 film "10 Things I Hate About You", Patrick Verona is played by Heath Ledger. In the 2009-2010 television series, Patrick Verona is played by Ethan Peck.
In the 1999 film "10 Things I Hate About You", Patrick Verona is played by Heath Ledger. In the 2009-2010 television series, Patrick Verona is played by Ethan Peck.
Who plays patrick in 10 things i hate about you?
['Who plays patrick in  the 1999 film 10 things i hate about you?', 'Who plays patrick in the 2009 tv series 10 things i hate about you?', 'Who plays patrick in the film 10 things i hate about you?', 'Who plays patrick in the TV series 10 things i hate about you?']
[['Heath Andrew Ledger', 'Heath Ledger', 'Ledger'], ['Ethan Peck', 'Peck', 'Ethan Gregory Peck'], ['Heath Andrew Ledger', 'Heath Ledger'], ['Ethan Peck', 'Ethan Gregory Peck']]

 95%|█████████▌| 19/20 [01:36<00:04,  4.64s/it]

follow question : Who plays patrick in  the 1999 film 10 things i hate about you?
short answer : ['Heath Andrew Ledger', 'Heath Ledger', 'Ledger']
{'score': 0.9788501262664795, 'start': 75, 'end': 87, 'answer': 'Heath Ledger'}
follow question : Who plays patrick in the 2009 tv series 10 things i hate about you?
short answer : ['Ethan Peck', 'Peck', 'Ethan Gregory Peck']
{'score': 0.8789895176887512, 'start': 153, 'end': 163, 'answer': 'Ethan Peck'}
follow question : Who plays patrick in the film 10 things i hate about you?
short answer : ['Heath Andrew Ledger', 'Heath Ledger']
{'score': 0.9475837349891663, 'start': 75, 'end': 87, 'answer': 'Heath Ledger'}
follow question : Who plays patrick in the TV series 10 things i hate about you?
short answer : ['Ethan Peck', 'Ethan Gregory Peck']
{'score': 0.8670162558555603, 'start': 153, 'end': 163, 'answer': 'Ethan Peck'}
{'rougeLsum': 71.42857142857143, 'length': 29.0, 'str_em': 100.0, 'Disambig-F1': 100.0}
Retrival Match Rate: 0.7
Final ans: Kamal Nath
Kamal Nath
Who is the chief minister of m. p?
['Who is the 17th Chief Minister of MP?', 'Who is the 16th Chief Minister of MP?', 'Who is the 15th Chief Minister of MP?', 'Who is the 17th chief minister of m. p?', 'Who is the 16th chief minister of m. p?', 'Who is the 15th chief minister of m. p?']
[['Shivraj Singh Chauhan'], ['Babulal Gaur'], ['Uma Bharti'], ['Shivraj Singh Chauhan'], ['Babulal Gaur', 'Babulal Gaur Yadav'], ['Uma Bharti']]

100%|██████████| 20/20 [01:38<00:00,  4.93s/it]

follow question : Who is the 17th Chief Minister of MP?
short answer : ['Shivraj Singh Chauhan']
{'score': 0.008324082009494305, 'start': 0, 'end': 10, 'answer': 'Kamal Nath'}
follow question : Who is the 16th Chief Minister of MP?
short answer : ['Babulal Gaur']
{'score': 0.006203873548656702, 'start': 0, 'end': 10, 'answer': 'Kamal Nath'}
follow question : Who is the 15th Chief Minister of MP?
short answer : ['Uma Bharti']
{'score': 0.010113616473972797, 'start': 0, 'end': 10, 'answer': 'Kamal Nath'}
follow question : Who is the 17th chief minister of m. p?
short answer : ['Shivraj Singh Chauhan']
{'score': 0.023427948355674744, 'start': 0, 'end': 10, 'answer': 'Kamal Nath'}
follow question : Who is the 16th chief minister of m. p?
short answer : ['Babulal Gaur', 'Babulal Gaur Yadav']
{'score': 0.021564064547419548, 'start': 0, 'end': 10, 'answer': 'Kamal Nath'}
follow question : Who is the 15th chief minister of m. p?
short answer : ['Uma Bharti']
{'score': 0.022985488176345825, 'start': 0, 'end': 10, 'answer': 'Kamal Nath'}
{'rougeLsum': 0.0, 'length': 2.0, 'str_em': 0.0, 'Disambig-F1': 0.0}

rougeLsum      33.643699
length         23.850000
str_em         47.500000
Disambig-F1    47.343254
dtype: float64

In [36]:
scores_df.to_csv('./results/basicRAG_seed24-len20_results.csv', index=False)
import pandas as pd
import math
sf = pd.read_csv('results/basicRAG_seed24-len20_results.csv')
sf=sf[sf['length']<1000][:100]
print(len(sf))
print(sf.mean())
r=sf.mean()['rougeLsum']
d=sf.mean()['Disambig-F1']
dr=math.sqrt(r*d)
print(dr)

20
rougeLsum      33.643699
length         23.850000
str_em         47.500000
Disambig-F1    47.343254
dtype: float64
39.90992615497553

# Answer RAG

In [39]:
from tqdm import tqdm
from evaluation import evaluate

set_seed(24)

stop_iteration = 20

scores_list=[]
retrival_list=[]
for idx, row in tqdm(qa_df.iterrows(), total=min([stop_iteration, len(qa_df)])):
    if idx == stop_iteration: break
    query = row['question']
    
    retrieved_docs, doc_ids = retrieve_documents(query)
    tmp1=0
    for doc_id in doc_ids:    
        tmp1+=match_sample_id(idx, doc_id)
    first_retrival=tmp1/len(retrieved_docs)
    print("First Retrival Match Rate:", first_retrival)
    
    dic=dict()
    dic['first_retrival']=first_retrival
    
    first_ans=total_answer(query,retrieved_docs)
    print('First ans:', first_ans)
    
    ans_docs, doc_ids=retrieve_documents(first_ans)
    tmp2=0
    for doc_id in doc_ids:    
        tmp2+=match_sample_id(idx, doc_id)
    second_retrival=tmp2/len(ans_docs)
    print("Second Retrival Match Rate:", second_retrival)
    
    dic['second_retrival']=second_retrival
    
    final_ans=total_answer(query,ans_docs)
    print('Second ans:', final_ans)
    scores=evaluate([final_ans], [row.to_dict()])
    scores_list.append(scores)
    scores_df=pd.DataFrame(scores_list)
    print(scores)
    retrival_list.append(dic)
    retrival_df=pd.DataFrame(retrival_list)
    print(dic)
        
scores_df=pd.DataFrame(scores_list)
scores_df.mean()

retrival_df=pd.DataFrame(retrival_list)
retrival_df.mean()

  0%|          | 0/20 [00:00<?, ?it/s]

First Retrival Match Rate: 0.5
First ans: Ali Daei holds the record for the highest number of international goals with 109 goals for Iran, surpassing Ferenc Puskás' record of 84 goals. Cristiano Ronaldo has scored 1030 goals in his career, the highest among active players, with a total of 738 goals in his international career. Miroslav Klose holds the record for most World Cup goals with 16 goals, while Gerd Müller used to be the holder of that record from 1974 until it was broken by Ronaldo in 2006. Pelé scored 77 international goals, the highest among players from outside Europe, and Jürgen Klinsmann scored 11 goals in the World Cup, the highest among players from Germany. The top goalscorers in the World Cup history are Ali Daei, Cristiano Ronaldo, Ferenc Puskás, Kunishige Kamamoto, Godfrey Chitalu, Hussein Saeed, and Zainal Abidin, among others.
Second Retrival Match Rate: 0.5
Second ans: Ali Daei holds the record for the highest goals in international football with 109 goals, while Josef Bican is the top scorer in top-level football with 805 goals in his career. Cristiano Ronaldo is the second-highest goal scorer in international football with 99 goals, and Pelé is the third-highest goal scorer with 77 international goals. Josef Bican's 805 goals were achieved over a period of 28 years, while Ali Daei's 109 goals were scored in 149 international appearances. Pelé's 77 goals were scored in 92 international matches, and Cristiano Ronaldo's 99 goals were achieved in 164 international appearances. The top scorer in the FIFA World Cup is Miroslav Klose with 16 goals, while Just Fontaine holds the record for the most goals scored at a single tournament with 13 goals in 1958.
Ali Daei holds the record for the highest goals in international football with 109 goals, while Josef Bican is the top scorer in top-level football with 805 goals in his career. Cristiano Ronaldo is the second-highest goal scorer in international football with 99 goals, and Pelé is the third-highest goal scorer with 77 international goals. Josef Bican's 805 goals were achieved over a period of 28 years, while Ali Daei's 109 goals were scored in 149 international appearances. Pelé's 77 goals were scored in 92 international matches, and Cristiano Ronaldo's 99 goals were achieved in 164 international appearances. The top scorer in the FIFA World Cup is Miroslav Klose with 16 goals, while Just Fontaine holds the record for the most goals scored at a single tournament with 13 goals in 1958.
Who has the highest goals in world football?
["Who has the highest goals in men's world international football?", "Who has the highest goals all-time in men's football?", "Who has the highest goals in women's world international football?"]
[['Daei', 'Ali Daei'], ['Bican', 'Josef Bican'], ['Sinclair', 'Christine Sinclair']]

  5%|▌         | 1/20 [00:30<09:34, 30.24s/it]

follow question : Who has the highest goals in men's world international football?
short answer : ['Daei', 'Ali Daei']
{'score': 0.9316173195838928, 'start': 0, 'end': 8, 'answer': 'Ali Daei'}
follow question : Who has the highest goals all-time in men's football?
short answer : ['Bican', 'Josef Bican']
{'score': 0.0013116518966853619, 'start': 0, 'end': 8, 'answer': 'Ali Daei'}
follow question : Who has the highest goals in women's world international football?
short answer : ['Sinclair', 'Christine Sinclair']
{'score': 0.024364793673157692, 'start': 0, 'end': 8, 'answer': 'Ali Daei'}
{'rougeLsum': 42.97520661157024, 'length': 132.0, 'str_em': 66.66666666666666, 'Disambig-F1': 33.33333333333333}
{'first_retrival': 0.5, 'second_retrival': 0.5}
First Retrival Match Rate: 1.0
First ans: The original artist of "Sound of Silence" is Simon & Garfunkel, an American music duo composed of Paul Simon and Art Garfunkel. The song was written by Paul Simon and recorded by Simon & Garfunkel in March 1964, with electric overdubs added by Tom Wilson in June 1965. Simon & Garfunkel's version of "The Sound of Silence" was released as a single in September 1965 and later included on their debut album "Wednesday Morning, 3 A.M." and their second album "Sounds of Silence". The duo's version of the song became a huge success, reaching number one on the Billboard Hot 100 chart in January 1966. Simon & Garfunkel's "Sound of Silence" is considered a classic folk rock song and a quintessential release in the duo's career.
Second Retrival Match Rate: 1.0
Second ans: The original artist of "Sound of Silence" is Simon & Garfunkel, an American music duo composed of Paul Simon and Art Garfunkel. They recorded the song in March 1964 and it was initially released as part of their debut album, "Wednesday Morning, 3 A.M." The song was written by Paul Simon and features his distinctive vocals and guitar work. Simon & Garfunkel's original version of "Sound of Silence" is a folk-rock ballad that has become one of the most iconic and enduring songs of the 1960s.
The original artist of "Sound of Silence" is Simon & Garfunkel, an American music duo composed of Paul Simon and Art Garfunkel. They recorded the song in March 1964 and it was initially released as part of their debut album, "Wednesday Morning, 3 A.M." The song was written by Paul Simon and features his distinctive vocals and guitar work. Simon & Garfunkel's original version of "Sound of Silence" is a folk-rock ballad that has become one of the most iconic and enduring songs of the 1960s.
Who is the original artist of sound of silence?
['Who is the original artist of sound of silence, the song, released in 1964?', 'Who is the original artist of sound of silence, the album?', 'Who is the original artist of sound of silence, the song, released in 2016?']
[['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon'], ['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon'], ['Dami Im']]

 10%|█         | 2/20 [00:51<07:30, 25.01s/it]

follow question : Who is the original artist of sound of silence, the song, released in 1964?
short answer : ['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon']
{'score': 0.9238919019699097, 'start': 45, 'end': 62, 'answer': 'Simon & Garfunkel'}
follow question : Who is the original artist of sound of silence, the album?
short answer : ['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon']
{'score': 0.9447035789489746, 'start': 45, 'end': 62, 'answer': 'Simon & Garfunkel'}
follow question : Who is the original artist of sound of silence, the song, released in 2016?
short answer : ['Dami Im']
{'score': 2.5097884645219892e-05, 'start': 45, 'end': 62, 'answer': 'Simon & Garfunkel'}
{'rougeLsum': 41.66666666666667, 'length': 86.0, 'str_em': 66.66666666666666, 'Disambig-F1': 66.66666666666666}
{'first_retrival': 1.0, 'second_retrival': 1.0}
First Retrival Match Rate: 0.9
First ans: The first Apple iPhone was conceived by Steve Jobs in 2005, and the development cost of the collaboration with Cingular Wireless was estimated to be $150 million over a thirty-month period. The original iPhone was introduced by Steve Jobs on January 9, 2007, at the Macworld Conference & Expo held in Moscone West in San Francisco, California. The iPhone was released in the United States on June 29, 2007, at the price of $499 for the 4 GB model and $599 for the 8 GB model, both requiring a 2-year contract. The iPhone's main competitors in both consumer and business markets were considered to be the LG Prada, LG Viewty, Samsung Ultra Smart F700, Nokia N95, Nokia E61i, Palm Treo 750, Palm Centro, HTC Touch, Sony Ericsson W960, and BlackBerry. The iPhone's history began with a request from Apple Inc. CEO Steve Jobs to the company's engineers, asking them to investigate the use of touchscreen devices and tablet computers.
Second Retrival Match Rate: 0.9
Second ans: The first iPhone was conceived by Steve Jobs in 2005, and the development of the device began in that year. The design was expanded upon over the next 2 years in complete secrecy before being announced in Q1 of 2007. The iPhone beta was created in 2004 to test the commands of the Apple team, but it was never released to the public. The first iPhone was officially launched and made accessible to the public in 2007, with the release date being June 29, 2007.
The first iPhone was conceived by Steve Jobs in 2005, and the development of the device began in that year. The design was expanded upon over the next 2 years in complete secrecy before being announced in Q1 of 2007. The iPhone beta was created in 2004 to test the commands of the Apple team, but it was never released to the public. The first iPhone was officially launched and made accessible to the public in 2007, with the release date being June 29, 2007.
When was the first apple i phone made?
['When was the first apple i phone released?', 'When was the first apple i phone for beta testing made?', 'When was the first apple i phone 1 made?', 'When was the first apple i phone beta made?']
[['June 29, 2007'], ['2004'], ['June 29, 2007.'], ['2004.']]

 15%|█▌        | 3/20 [01:14<06:46, 23.93s/it]

follow question : When was the first apple i phone released?
short answer : ['June 29, 2007']
{'score': 0.2852415442466736, 'start': 446, 'end': 459, 'answer': 'June 29, 2007'}
follow question : When was the first apple i phone for beta testing made?
short answer : ['2004']
{'score': 0.9337247014045715, 'start': 248, 'end': 252, 'answer': '2004'}
follow question : When was the first apple i phone 1 made?
short answer : ['June 29, 2007.']
{'score': 0.6377459168434143, 'start': 48, 'end': 52, 'answer': '2005'}
follow question : When was the first apple i phone beta made?
short answer : ['2004.']
{'score': 0.9528789520263672, 'start': 248, 'end': 252, 'answer': '2004'}
{'rougeLsum': 52.348993288590606, 'length': 85.0, 'str_em': 100.0, 'Disambig-F1': 75.0}
{'first_retrival': 0.9, 'second_retrival': 0.9}
First Retrival Match Rate: 0.9
First ans: The Weasley brothers, Fred, George, and their family members, were portrayed by the acting duo James and Oliver Phelps. They played the roles of Fred and George Weasley in the film series, with James playing the elder twin and Oliver playing the younger twin. The duo's portrayal of the Weasley brothers became iconic in the series, and they appeared in all eight films. The Weasley family members, including Arthur, Molly, and their children, were also played by other actors, including Mark Williams, Julie Walters, and Bonnie Wright. The Weasley family was a central part of the series, and their characters added depth and richness to the story.
Second Retrival Match Rate: 1.0
Second ans: The Weasley brothers, Fred and George, were played by twins James and Oliver Phelps. James Phelps played Fred Weasley in all eight films of the series, while Oliver Phelps played George Weasley in all eight films. Richard Fish played Bill Weasley briefly in the film adaptation of Harry Potter and the Prisoner of Azkaban. Domhnall Gleeson played Bill Weasley in Harry Potter and the Deathly Hallows and the theme park attraction Harry Potter and the Escape from Gringotts.
The Weasley brothers, Fred and George, were played by twins James and Oliver Phelps. James Phelps played Fred Weasley in all eight films of the series, while Oliver Phelps played George Weasley in all eight films. Richard Fish played Bill Weasley briefly in the film adaptation of Harry Potter and the Prisoner of Azkaban. Domhnall Gleeson played Bill Weasley in Harry Potter and the Deathly Hallows and the theme park attraction Harry Potter and the Escape from Gringotts.
Who played the weasley brothers in harry potter?
['Who played  Bill weasley in Harry Potter and the Prisoner of Azkaban?', 'Who played percy weasley in harry potter?', 'Who played fred weasley in harry potter?', 'Who played ron weasley in harry potter?', 'Who played george weasley in harry potter?', 'Who played  Bill weasley in harry potter (2001-2011)?']
[['Richard Fish'], ['Chris Rankin'], ['James Phelps'], ['Rupert Grint'], ['Oliver Phelps'], ['Domhnall Gleeson']]

 20%|██        | 4/20 [01:35<06:08, 23.05s/it]

follow question : Who played  Bill weasley in Harry Potter and the Prisoner of Azkaban?
short answer : ['Richard Fish']
{'score': 0.6119859218597412, 'start': 214, 'end': 226, 'answer': 'Richard Fish'}
follow question : Who played percy weasley in harry potter?
short answer : ['Chris Rankin']
{'score': 0.34922823309898376, 'start': 323, 'end': 339, 'answer': 'Domhnall Gleeson'}
follow question : Who played fred weasley in harry potter?
short answer : ['James Phelps']
{'score': 0.39705175161361694, 'start': 323, 'end': 339, 'answer': 'Domhnall Gleeson'}
follow question : Who played ron weasley in harry potter?
short answer : ['Rupert Grint']
{'score': 0.46663224697113037, 'start': 323, 'end': 339, 'answer': 'Domhnall Gleeson'}
follow question : Who played george weasley in harry potter?
short answer : ['Oliver Phelps']
{'score': 0.12447860091924667, 'start': 70, 'end': 83, 'answer': 'Oliver Phelps'}
follow question : Who played  Bill weasley in harry potter (2001-2011)?
short answer : ['Domhnall Gleeson']
{'score': 0.5724259614944458, 'start': 323, 'end': 339, 'answer': 'Domhnall Gleeson'}
{'rougeLsum': 65.9090909090909, 'length': 78.0, 'str_em': 66.66666666666666, 'Disambig-F1': 50.0}
{'first_retrival': 0.9, 'second_retrival': 1.0}
First Retrival Match Rate: 0.4
First ans: According to the provided context, there are 38 state parks in Virginia as mentioned in the first document. However, this number might not be up-to-date as the information is not current. In addition, the second document mentions that the Virginia State Capitol is the seat of state government, but it does not provide information on the number of state parks. The third document mentions that New York City has a complex park system, but it does not provide information on the number of state parks in Virginia.
Second Retrival Match Rate: 0.4
Second ans: There are 38 state parks in Virginia. This number is mentioned in the document "List of Virginia state parks" which provides information about the Virginia state park system. The system was established in 1936 with six parks and has since grown to oversee 38 parks. The exact number of state parks can be found in the document by counting the number of parks listed.
There are 38 state parks in Virginia. This number is mentioned in the document "List of Virginia state parks" which provides information about the Virginia state park system. The system was established in 1936 with six parks and has since grown to oversee 38 parks. The exact number of state parks can be found in the document by counting the number of parks listed.
How many state parks are there in virginia?
['How many state parks are there in virginia in 1936?', 'How many state parks are there in virginia in 2016?', 'How many state parks were there when the state park system formed in Virginia?', 'How many state parks were there in Virginia as of 2016?']
[['six'], ['38'], ['6'], ['38']]

 25%|██▌       | 5/20 [01:51<05:04, 20.30s/it]

follow question : How many state parks are there in virginia in 1936?
short answer : ['six']
{'score': 0.1975339949131012, 'start': 10, 'end': 12, 'answer': '38'}
follow question : How many state parks are there in virginia in 2016?
short answer : ['38']
{'score': 0.11582784354686737, 'start': 10, 'end': 12, 'answer': '38'}
follow question : How many state parks were there when the state park system formed in Virginia?
short answer : ['6']
{'score': 0.22324897348880768, 'start': 215, 'end': 218, 'answer': 'six'}
follow question : How many state parks were there in Virginia as of 2016?
short answer : ['38']
{'score': 0.018562588840723038, 'start': 10, 'end': 12, 'answer': '38'}
{'rougeLsum': 38.775510204081634, 'length': 64.0, 'str_em': 100.0, 'Disambig-F1': 50.0}
{'first_retrival': 0.4, 'second_retrival': 0.4}
First Retrival Match Rate: 0.5
First ans: The 2018 UEFA Champions League Final featured a performance by English singer Dua Lipa during the opening ceremony, where she sang alongside Jamaican rapper Sean Paul. The UEFA Champions League Anthem was performed by Slovenian–Croatian cello duo 2Cellos. In addition, the annual UEFA Champions Festival was held between 24–27 May 2018 at the Kiev city centre, but it is unclear if any specific performance was part of this event. The 2018 UEFA Champions League Final also featured a performance by Gareth Bale's bicycle kick goal, which received acclaim as one of the best in Champions League history.
Second Retrival Match Rate: 0.3
Second ans: Dua Lipa performed at the opening ceremony preceding the final, alongside special guest Sean Paul, and the UEFA Champions League Anthem was performed by Slovenian–Croatian cello duo 2Cellos. The annual UEFA Champions Festival was held between 24–27 May 2018 at the Kiev city centre, featuring various performances. The match between Real Madrid and Liverpool was officiated by Serbian referee Milorad Mažić, and the match ball was the Telstar 18, which was unveiled on 9 November 2017. The official mascot for the tournament was Zabivaka, an anthropomorphic wolf dressed in the colours of the Russian national team, unveiled on 21 October 2016. The official song of the tournament was "Live It Up" by Will Smith, Nicky Jam, and Era Istrefi, released on 25 May 2018.
Dua Lipa performed at the opening ceremony preceding the final, alongside special guest Sean Paul, and the UEFA Champions League Anthem was performed by Slovenian–Croatian cello duo 2Cellos. The annual UEFA Champions Festival was held between 24–27 May 2018 at the Kiev city centre, featuring various performances. The match between Real Madrid and Liverpool was officiated by Serbian referee Milorad Mažić, and the match ball was the Telstar 18, which was unveiled on 9 November 2017. The official mascot for the tournament was Zabivaka, an anthropomorphic wolf dressed in the colours of the Russian national team, unveiled on 21 October 2016. The official song of the tournament was "Live It Up" by Will Smith, Nicky Jam, and Era Istrefi, released on 25 May 2018.
Who performed at the champions league final 2018?
['Who are the teams that performed in competition at the champions league final 2018?', 'Who performed best at the champions league final 2018, winning man of the match?', 'Who performed at the opening ceremony of the champions league final 2018?', 'Who performed the anthem at the champions league final 2018?']
[['Real Madrid and Liverpool', 'Liverpool', 'Real Madrid'], ['Gareth Bale', 'Bale'], ['Dua Lipa', 'Sean Paul', 'Dua Lipa and Sean Paul'], ['2Cellos', 'Luka Šulić and Stjepan Hauser', 'Luka Šulić', '2CΞLLOS', 'Stjepan Hauser']]

 30%|███       | 6/20 [02:12<04:50, 20.72s/it]

follow question : Who are the teams that performed in competition at the champions league final 2018?
short answer : ['Real Madrid and Liverpool', 'Liverpool', 'Real Madrid']
{'score': 0.46176183223724365, 'start': 333, 'end': 358, 'answer': 'Real Madrid and Liverpool'}
follow question : Who performed best at the champions league final 2018, winning man of the match?
short answer : ['Gareth Bale', 'Bale']
{'score': 0.38792285323143005, 'start': 0, 'end': 8, 'answer': 'Dua Lipa'}
follow question : Who performed at the opening ceremony of the champions league final 2018?
short answer : ['Dua Lipa', 'Sean Paul', 'Dua Lipa and Sean Paul']
{'score': 0.26639577746391296, 'start': 0, 'end': 8, 'answer': 'Dua Lipa'}
follow question : Who performed the anthem at the champions league final 2018?
short answer : ['2Cellos', 'Luka Šulić and Stjepan Hauser', 'Luka Šulić', '2CΞLLOS', 'Stjepan Hauser']
{'score': 0.8560420870780945, 'start': 182, 'end': 189, 'answer': '2Cellos'}
{'rougeLsum': 39.252336448598136, 'length': 124.0, 'str_em': 75.0, 'Disambig-F1': 75.0}
{'first_retrival': 0.5, 'second_retrival': 0.3}
First Retrival Match Rate: 0.3
First ans: Harlan, a stranger Thelma met at a roadhouse bar, attempted to rape Thelma, but was shot and killed by Louise in self-defense. This event sets off a chain of circumstances that leads to the two friends going on the run. Although Harlan's death is a pivotal moment in the film, it is not explicitly stated who killed him in the sense of a person being directly responsible for his death. The film portrays Harlan's death as a result of Louise's actions, but also suggests that the societal and systemic failures that allowed Harlan's predatory behavior to continue unchecked contributed to his demise.
Second Retrival Match Rate: 0.3
Second ans: The man killed in the film Thelma and Louise is Harlan, a stranger who attempted to rape Thelma. He was shot and killed by Louise after she threatened him with a gun. Harlan's death sparks the events of the film as Thelma and Louise go on the run. In a separate context, Joe, a hitchhiker, is revealed to be the son of the man who killed Laura, but his identity and the circumstances surrounding his father's actions are not explicitly stated in the provided information.
The man killed in the film Thelma and Louise is Harlan, a stranger who attempted to rape Thelma. He was shot and killed by Louise after she threatened him with a gun. Harlan's death sparks the events of the film as Thelma and Louise go on the run. In a separate context, Joe, a hitchhiker, is revealed to be the son of the man who killed Laura, but his identity and the circumstances surrounding his father's actions are not explicitly stated in the provided information.
Who killed the man in thelma and louise?
['Which character killed the man in thelma and louise?', 'Which actor killed the man in thelma and louise?', 'Who is the character that kills Harlan in the film Thelma and Louise?', 'Who is the actor of the character that killed a man in the film Thelma and Louise?']
[['Louise Elizabeth Sawyer', 'Louise'], ['Susan Sarandon', 'Susan Abigail Sarandon'], ['Louise Elizabeth Sawyer', 'Louise'], ['Susan Sarandon']]

 35%|███▌      | 7/20 [02:30<04:14, 19.61s/it]

follow question : Which character killed the man in thelma and louise?
short answer : ['Louise Elizabeth Sawyer', 'Louise']
{'score': 0.9014881253242493, 'start': 48, 'end': 54, 'answer': 'Harlan'}
follow question : Which actor killed the man in thelma and louise?
short answer : ['Susan Sarandon', 'Susan Abigail Sarandon']
{'score': 0.8025162220001221, 'start': 48, 'end': 54, 'answer': 'Harlan'}
follow question : Who is the character that kills Harlan in the film Thelma and Louise?
short answer : ['Louise Elizabeth Sawyer', 'Louise']
{'score': 0.40509697794914246, 'start': 123, 'end': 129, 'answer': 'Louise'}
follow question : Who is the actor of the character that killed a man in the film Thelma and Louise?
short answer : ['Susan Sarandon']
{'score': 0.28228044509887695, 'start': 48, 'end': 54, 'answer': 'Harlan'}
{'rougeLsum': 27.027027027027028, 'length': 85.0, 'str_em': 50.0, 'Disambig-F1': 25.0}
{'first_retrival': 0.3, 'second_retrival': 0.3}
First Retrival Match Rate: 0.9
First ans: Charlie Kelly is a main character in the TV show It's Always Sunny in Philadelphia, and he is played by actor Charlie Day. Charlie Day is one of the main cast members of the show, and he has a significant role in the series as Charlie Kelly, a wild and unpredictable member of the gang. Charlie Kelly is a complex and dynamic character, and Charlie Day brings him to life with his energetic and unpredictable performances. Charlie Day has been a part of the show since its beginning and has become closely associated with the character of Charlie Kelly. Charlie Day's portrayal of Charlie Kelly is a key part of the show's humor and charm, and he has become a fan favorite among viewers.
Second Retrival Match Rate: 0.9
Second ans: Charlie Kelly is played by Charlie Day, an actor and one of the main cast members of the show. Charlie Kelly is a main character in the show, and Charlie Day also co-created the show, along with Rob McElhenney, Glenn Howerton, and Kaitlin Olson. Charlie Kelly is a complex and troubled character, and Charlie Day brings his eccentric and unpredictable personality to the role. Charlie Day's portrayal of Charlie Kelly has been widely praised, and he has become closely associated with the character. Charlie Day's performance as Charlie Kelly has been a key part of the show's success and has helped to make Charlie Kelly one of the most iconic and beloved characters in television history.
Charlie Kelly is played by Charlie Day, an actor and one of the main cast members of the show. Charlie Kelly is a main character in the show, and Charlie Day also co-created the show, along with Rob McElhenney, Glenn Howerton, and Kaitlin Olson. Charlie Kelly is a complex and troubled character, and Charlie Day brings his eccentric and unpredictable personality to the role. Charlie Day's portrayal of Charlie Kelly has been widely praised, and he has become closely associated with the character. Charlie Day's performance as Charlie Kelly has been a key part of the show's success and has helped to make Charlie Kelly one of the most iconic and beloved characters in television history.
Who plays charlie on it's always sunny?
["Who does Charlie Day play on It's Always Sunny in Philadelphia?", "Who plays Charlie Kelly on It's Always Sunny in Philadelphia?"]
[['Charlie Kelly'], ['Charlie Day']]

 40%|████      | 8/20 [02:49<03:55, 19.59s/it]

follow question : Who does Charlie Day play on It's Always Sunny in Philadelphia?
short answer : ['Charlie Kelly']
{'score': 0.6349177956581116, 'start': 0, 'end': 13, 'answer': 'Charlie Kelly'}
follow question : Who plays Charlie Kelly on It's Always Sunny in Philadelphia?
short answer : ['Charlie Day']
{'score': 0.8470332622528076, 'start': 27, 'end': 38, 'answer': 'Charlie Day'}
{'rougeLsum': 20.57142857142857, 'length': 116.0, 'str_em': 100.0, 'Disambig-F1': 100.0}
{'first_retrival': 0.9, 'second_retrival': 0.9}
First Retrival Match Rate: 0.4
First ans: The Los Angeles Lakers have won the NBA Finals 16 times, with their first championship in 1949 and their most recent one in 2010. They have appeared in the NBA Finals a total of 31 times, making them one of the most successful teams in the league's history. The Lakers have won the championship in Minneapolis and Los Angeles, with 11 titles in Los Angeles and 5 in Minneapolis. Their championships include five in a row from 2000 to 2002, and two more in 2009 and 2010. The team's 16 championships are second only to the Boston Celtics' 17 championships.
Second Retrival Match Rate: 0.4
Second ans: The Los Angeles Lakers have won the NBA Finals 16 times. They have appeared in the Finals 31 times, which is the most in the league's history. Their most recent championship was in 2010, when they defeated the Boston Celtics in the Finals. The Lakers have a long and storied history, with their first championship coming in 1949 and their most recent "three-peat" occurring from 1999 to 2001. Their 16 championships are second only to the Boston Celtics' 17 championships in the league's history.
The Los Angeles Lakers have won the NBA Finals 16 times. They have appeared in the Finals 31 times, which is the most in the league's history. Their most recent championship was in 2010, when they defeated the Boston Celtics in the Finals. The Lakers have a long and storied history, with their first championship coming in 1949 and their most recent "three-peat" occurring from 1999 to 2001. Their 16 championships are second only to the Boston Celtics' 17 championships in the league's history.
How many times have the lakers won the finals?
['As of 2017, how many times have the lakers won the finals?', 'As of 2016, how many times have the Lakers won the finals?', 'As of 2015, how many times have the Lakers won the finals?']
[['16'], ['16'], ['16']]

 45%|████▌     | 9/20 [03:08<03:32, 19.29s/it]

follow question : As of 2017, how many times have the lakers won the finals?
short answer : ['16']
{'score': 0.56845623254776, 'start': 47, 'end': 49, 'answer': '16'}
follow question : As of 2016, how many times have the Lakers won the finals?
short answer : ['16']
{'score': 0.6399193406105042, 'start': 47, 'end': 49, 'answer': '16'}
follow question : As of 2015, how many times have the Lakers won the finals?
short answer : ['16']
{'score': 0.45287978649139404, 'start': 47, 'end': 49, 'answer': '16'}
{'rougeLsum': 41.221374045801525, 'length': 84.0, 'str_em': 100.0, 'Disambig-F1': 100.0}
{'first_retrival': 0.4, 'second_retrival': 0.4}
First Retrival Match Rate: 0.7
First ans: The Indian National Congress is in power in seven legislative assemblies: Punjab, Rajasthan, Chhattisgarh, Madhya Pradesh, Maharashtra, Jharkhand, and Puducherry. In these states, the party has a majority support and forms the government. Additionally, the party has a presence in other states, including Andhra Pradesh, Arunachal Pradesh, Assam, Bihar, Goa, Gujarat, Haryana, Himachal Pradesh, Jammu and Kashmir, Jharkhand, Karnataka, Kerala, Ladakh, Lakshadweep, Maharashtra, Manipur, Meghalaya, Mizoram, Nagaland, Odisha, Punjab, Rajasthan, Sikkim, Tamil Nadu, Telangana, Tripura, Uttar Pradesh, Uttarakhand, and West Bengal, where it shares power with other parties or is in opposition. The party's strength and presence vary across these states. The party has a significant presence in the country and is one of the major political parties in India.
Second Retrival Match Rate: 0.7
Second ans: The Indian National Congress is in power in the states of Punjab, Chhattisgarh, Rajasthan, and Madhya Pradesh, where the party has a majority support. Additionally, it shares power with alliance partners in Puducherry and Maharashtra. As of December 2019, the party has a presence in 7 out of 31 states and union territories in India. The party has a majority in the legislative assemblies of Punjab, Chhattisgarh, Rajasthan, and Madhya Pradesh. It shares power with other parties in the remaining states and union territories.
The Indian National Congress is in power in the states of Punjab, Chhattisgarh, Rajasthan, and Madhya Pradesh, where the party has a majority support. Additionally, it shares power with alliance partners in Puducherry and Maharashtra. As of December 2019, the party has a presence in 7 out of 31 states and union territories in India. The party has a majority in the legislative assemblies of Punjab, Chhattisgarh, Rajasthan, and Madhya Pradesh. It shares power with other parties in the remaining states and union territories.
How many states in india are under congress?
['How many states plus territories in india are under congress?', 'How many states alone in india are under congress?']
[['7'], ['5']]

 50%|█████     | 10/20 [03:33<03:30, 21.06s/it]

follow question : How many states plus territories in india are under congress?
short answer : ['7']
{'score': 0.2717338800430298, 'start': 284, 'end': 285, 'answer': '7'}
follow question : How many states alone in india are under congress?
short answer : ['5']
{'score': 0.24371139705181122, 'start': 284, 'end': 285, 'answer': '7'}
{'rougeLsum': 24.82758620689655, 'length': 84.0, 'str_em': 50.0, 'Disambig-F1': 50.0}
{'first_retrival': 0.7, 'second_retrival': 0.7}
First Retrival Match Rate: 1.0
First ans: Fruma Sarah is the deceased wife of Lazar Wolf, a wealthy butcher in the village of Anatevka, and her spirit appears to Tevye in a dream, warning him against allowing Tzeitel to marry Lazar. In the musical, Fruma Sarah is a character who rises from the grave to advise Tevye against marrying Tzeitel to Lazar Wolf. In the original Broadway production, the role of Fruma Sarah was played by Carol Sawyer. The character of Fruma Sarah is a significant part of the story, as her appearance in Tevye's dream serves as a catalyst for the events that unfold. Fruma Sarah's presence also highlights the themes of tradition, family, and the importance of honoring one's heritage.
Second Retrival Match Rate: 1.0
Second ans: Fruma-Sarah is the late wife of Lazar Wolf, a wealthy butcher in the village of Anatevka, and she rises from the grave in Tevye's dream to warn of severe retribution if Tzeitel marries Lazar. In the context of the story, Fruma-Sarah serves as a supernatural warning to protect Tzeitel from marrying Lazar. In the film adaptation, Fruma-Sarah's presence is also used to foreshadow the impending pogrom and the persecution of the Jewish community. As a character, Fruma-Sarah is a representation of the Jewish traditions and customs that are being threatened by the changing world. Despite her passing, Fruma-Sarah's spirit continues to play a significant role in the story, influencing the characters and their decisions.
Fruma-Sarah is the late wife of Lazar Wolf, a wealthy butcher in the village of Anatevka, and she rises from the grave in Tevye's dream to warn of severe retribution if Tzeitel marries Lazar. In the context of the story, Fruma-Sarah serves as a supernatural warning to protect Tzeitel from marrying Lazar. In the film adaptation, Fruma-Sarah's presence is also used to foreshadow the impending pogrom and the persecution of the Jewish community. As a character, Fruma-Sarah is a representation of the Jewish traditions and customs that are being threatened by the changing world. Despite her passing, Fruma-Sarah's spirit continues to play a significant role in the story, influencing the characters and their decisions.
Who is fruma sarah in fiddler on the roof?
['Who played fruma sarah in the 1971 film, Fiddler on the Roof?', 'Who played Fruma Sarah in the original 1964 Broadway cast of Fiddler on the Roof?', 'Who is the character of Fruma Sarah in Fiddler on the Roof?', 'Who played Fruma Sarah in the 2015-2016 Broadway Revival of Fiddler on the Roof?']
[['Ruth Madoc'], ['Carol Sawyer Yussel'], ['a ghostly depiction of the late wife of Lazar Wolf'], ['Jessica Vosk']]

 55%|█████▌    | 11/20 [03:59<03:22, 22.50s/it]

follow question : Who played fruma sarah in the 1971 film, Fiddler on the Roof?
short answer : ['Ruth Madoc']
{'score': 0.0019759086426347494, 'start': 122, 'end': 127, 'answer': 'Tevye'}
follow question : Who played Fruma Sarah in the original 1964 Broadway cast of Fiddler on the Roof?
short answer : ['Carol Sawyer Yussel']
{'score': 0.0002419951924821362, 'start': 122, 'end': 127, 'answer': 'Tevye'}
follow question : Who is the character of Fruma Sarah in Fiddler on the Roof?
short answer : ['a ghostly depiction of the late wife of Lazar Wolf']
{'score': 0.17800521850585938, 'start': 32, 'end': 42, 'answer': 'Lazar Wolf'}
follow question : Who played Fruma Sarah in the 2015-2016 Broadway Revival of Fiddler on the Roof?
short answer : ['Jessica Vosk']
{'score': 0.00013080154894851148, 'start': 122, 'end': 127, 'answer': 'Tevye'}
{'rougeLsum': 33.92857142857143, 'length': 114.0, 'str_em': 0.0, 'Disambig-F1': 10.0}
{'first_retrival': 1.0, 'second_retrival': 1.0}
First Retrival Match Rate: 0.9
First ans: The Toronto Blue Jays hosted the MLB All-Star Game on July 9, 1991, at the SkyDome.
Second Retrival Match Rate: 0.8
Second ans: The Toronto Blue Jays hosted the MLB All-Star Game in 1991. The game was played at the SkyDome on July 9, 1991, with an attendance of 52,383. This was the first time Toronto hosted the All-Star Game.
The Toronto Blue Jays hosted the MLB All-Star Game in 1991. The game was played at the SkyDome on July 9, 1991, with an attendance of 52,383. This was the first time Toronto hosted the All-Star Game.
When did toronto host the mlb all-star game?
['What date did toronto host the mlb all-star game?', 'Which all-star game did toronto host?']
[['July 9, 1991'], ['1991 Major League Baseball All-Star Game', 'the 62nd playing of the midsummer classic']]

 60%|██████    | 12/20 [04:08<02:28, 18.50s/it]

follow question : What date did toronto host the mlb all-star game?
short answer : ['July 9, 1991']
{'score': 0.7676581144332886, 'start': 98, 'end': 110, 'answer': 'July 9, 1991'}
follow question : Which all-star game did toronto host?
short answer : ['1991 Major League Baseball All-Star Game', 'the 62nd playing of the midsummer classic']
{'score': 0.24765203893184662, 'start': 33, 'end': 50, 'answer': 'MLB All-Star Game'}
{'rougeLsum': 44.66019417475728, 'length': 37.0, 'str_em': 50.0, 'Disambig-F1': 72.22222222222221}
{'first_retrival': 0.9, 'second_retrival': 0.8}
First Retrival Match Rate: 0.7
First ans: The car driven by Grace Kelly in the 1955 film "To Catch a Thief" is a metallic blue 1953 Sunbeam Alpine Mk I. This car is a two-seater sports roadster that was hand-built at Thrupp & Maberly coachbuilders from 1953 to 1955. The Sunbeam Alpine was a car that was initially developed for a one-off rally car, and it had its beginnings as a 1952 Sunbeam-Talbot drophead coupé. In the film, the car is used as a key plot element, and it is driven by Grace Kelly's character, Frances Stevens. The Sunbeam Alpine has also appeared in several other films and TV shows, including "Night of the Demon" and "Dr. No".
Second Retrival Match Rate: 0.7
Second ans: The car driven by Grace Kelly in the movie "To Catch a Thief" is a metallic blue 1953 Sunbeam Alpine Mk I. The Sunbeam Alpine is a two-seater sports roadster produced by Rootes Group from 1953 to 1955, and then 1959 to 1968. It was initially developed from the Sunbeam-Talbot 90 Saloon and was known for its sleek design and powerful engine. The car has been featured in several notable films and television shows, including "To Catch a Thief" and "Get Smart".
The car driven by Grace Kelly in the movie "To Catch a Thief" is a metallic blue 1953 Sunbeam Alpine Mk I. The Sunbeam Alpine is a two-seater sports roadster produced by Rootes Group from 1953 to 1955, and then 1959 to 1968. It was initially developed from the Sunbeam-Talbot 90 Saloon and was known for its sleek design and powerful engine. The car has been featured in several notable films and television shows, including "To Catch a Thief" and "Get Smart".
What kind of car in to catch a thief?
['What kind of car in to catch a thief in terms of model?', 'What kind of car in to catch a thief in terms of automobile make?']
[['Sunbeam Alpine', '1953 Sunbeam Alpine Mk I'], ['Rootes Group']]

 65%|██████▌   | 13/20 [04:27<02:11, 18.75s/it]

follow question : What kind of car in to catch a thief in terms of model?
short answer : ['Sunbeam Alpine', '1953 Sunbeam Alpine Mk I']
{'score': 0.3186212480068207, 'start': 86, 'end': 105, 'answer': 'Sunbeam Alpine Mk I'}
follow question : What kind of car in to catch a thief in terms of automobile make?
short answer : ['Rootes Group']
{'score': 0.15545375645160675, 'start': 86, 'end': 105, 'answer': 'Sunbeam Alpine Mk I'}
{'rougeLsum': 47.5, 'length': 82.0, 'str_em': 100.0, 'Disambig-F1': 44.44444444444445}
{'first_retrival': 0.7, 'second_retrival': 0.7}
First Retrival Match Rate: 0.8
First ans: The sixth season of Jersey Shore, which was considered a new series and not the seventh season of the original show, premiered globally on April 5, 2018. This season was the final season of the series and consisted of 12 episodes. The season wrapped on December 20, 2012, but the new series, Jersey Shore: Family Vacation, premiered in 2018. The last season of Jersey Shore: Family Vacation, which is considered a continuation of the original series, aired from January 4 to July 26, 2018. The final eight episodes of the sixth season aired in the summer of 2018, wrapping up the series.
Second Retrival Match Rate: 0.4
Second ans: The last season of Jersey Shore aired from October 4, 2012, to December 20, 2012, with a total of 71 episodes over six seasons. The show premiered on December 3, 2009, and the final episode of the sixth season aired on December 20, 2012. However, a reunion series, Jersey Shore: Family Vacation, premiered on April 5, 2018, which is considered a new series and not the seventh season of the original show. The sixth season of Jersey Shore was the final season to air on MTV, but the franchise continues with spin-offs and international adaptations. The Jersey Shore franchise has continued to evolve with new seasons and spin-offs, including Jersey Shore: Family Vacation, which premiered in 2018.
The last season of Jersey Shore aired from October 4, 2012, to December 20, 2012, with a total of 71 episodes over six seasons. The show premiered on December 3, 2009, and the final episode of the sixth season aired on December 20, 2012. However, a reunion series, Jersey Shore: Family Vacation, premiered on April 5, 2018, which is considered a new series and not the seventh season of the original show. The sixth season of Jersey Shore was the final season to air on MTV, but the franchise continues with spin-offs and international adaptations. The Jersey Shore franchise has continued to evolve with new seasons and spin-offs, including Jersey Shore: Family Vacation, which premiered in 2018.
When did the last season of jersey shore air?
['When did season 4 of jersey shore first air?', 'When did season 4 of jersey shore last air?', 'When did season 5 of jersey shore first air?', 'When did season 5 of jersey shore last air?', 'When did season 6 of jersey shore first air?', 'When did season 6 of jersey shore last air?']
[['August 4, 2011'], ['October 20, 2011'], ['January 5, 2012'], ['March 15, 2012'], ['October 4, 2012'], ['December 20, 2012']]

 70%|███████   | 14/20 [04:48<01:56, 19.35s/it]

follow question : When did season 4 of jersey shore first air?
short answer : ['August 4, 2011']
{'score': 0.14830394089221954, 'start': 43, 'end': 58, 'answer': 'October 4, 2012'}
follow question : When did season 4 of jersey shore last air?
short answer : ['October 20, 2011']
{'score': 0.5868931412696838, 'start': 43, 'end': 58, 'answer': 'October 4, 2012'}
follow question : When did season 5 of jersey shore first air?
short answer : ['January 5, 2012']
{'score': 0.12128744274377823, 'start': 150, 'end': 166, 'answer': 'December 3, 2009'}
follow question : When did season 5 of jersey shore last air?
short answer : ['March 15, 2012']
{'score': 0.5384283661842346, 'start': 43, 'end': 58, 'answer': 'October 4, 2012'}
follow question : When did season 6 of jersey shore first air?
short answer : ['October 4, 2012']
{'score': 0.50522381067276, 'start': 150, 'end': 166, 'answer': 'December 3, 2009'}
follow question : When did season 6 of jersey shore last air?
short answer : ['December 20, 2012']
{'score': 0.5005173683166504, 'start': 43, 'end': 58, 'answer': 'October 4, 2012'}
{'rougeLsum': 36.36363636363636, 'length': 117.0, 'str_em': 33.33333333333333, 'Disambig-F1': 22.22222222222222}
{'first_retrival': 0.8, 'second_retrival': 0.4}
First Retrival Match Rate: 0.7
First ans: The plane crash occurred in the season 8 episode "Flight" (Season 8, Episode 24), which is the 172nd episode overall. The season 8 episode "Going, Going, Gone" (Season 8, Episode 24) is the finale of the season and picks up about one month after the crash, where the doctors deal with the aftermath of the plane crash. The season 9 episode "Flight" is actually a repeat of the season 8 episode "Flight" and is not a new episode, but rather a re-airing of the plane crash storyline. The season 8 plane crash is a significant plot point in the series, and its aftermath is explored in the following season. The episode "Flight" is a part of the season 8 finale, "Going, Going, Gone".
Second Retrival Match Rate: 0.8
Second ans: The plane crash occurred at the end of Season 8, specifically in the episode "Flight" (Season 8, Episode 24). This crash had a significant impact on the characters, particularly Meredith, Derek, Cristina, Arizona, and Mark. The crash resulted in the death of Lexie Grey, and the survivors struggled to cope with the aftermath. The season 8 finale, "Flight", marked a turning point in the series, with the characters dealing with the physical and emotional repercussions of the crash. The episode "Going, Going, Gone" (Season 9, Episode 1) picks up about a month after the crash, with the characters still reeling from the tragedy.
The plane crash occurred at the end of Season 8, specifically in the episode "Flight" (Season 8, Episode 24). This crash had a significant impact on the characters, particularly Meredith, Derek, Cristina, Arizona, and Mark. The crash resulted in the death of Lexie Grey, and the survivors struggled to cope with the aftermath. The season 8 finale, "Flight", marked a turning point in the series, with the characters dealing with the physical and emotional repercussions of the crash. The episode "Going, Going, Gone" (Season 9, Episode 1) picks up about a month after the crash, with the characters still reeling from the tragedy.
What season of greys anatomy was the plane crash?
["What season of Grey's Anatomy was the plane crash involving six doctors?", "What season of Grey's Anatomy was the plane crash in Seattle that brought memories of a previous plane crash?", "What season of Grey's Anatomy was the plane crash that claimed the life of Lexie Grey?", "What season of Grey's Anatomy was the plane crash in downtown Seattle?"]
[['season 8'], ['season 11'], ['8'], ['11']]

 75%|███████▌  | 15/20 [05:10<01:39, 19.98s/it]

follow question : What season of Grey's Anatomy was the plane crash involving six doctors?
short answer : ['season 8']
{'score': 0.5354451537132263, 'start': 39, 'end': 47, 'answer': 'Season 8'}
follow question : What season of Grey's Anatomy was the plane crash in Seattle that brought memories of a previous plane crash?
short answer : ['season 11']
{'score': 0.6365526914596558, 'start': 39, 'end': 47, 'answer': 'Season 8'}
follow question : What season of Grey's Anatomy was the plane crash that claimed the life of Lexie Grey?
short answer : ['8']
{'score': 0.715430736541748, 'start': 39, 'end': 47, 'answer': 'Season 8'}
follow question : What season of Grey's Anatomy was the plane crash in downtown Seattle?
short answer : ['11']
{'score': 0.6484429240226746, 'start': 39, 'end': 47, 'answer': 'Season 8'}
{'rougeLsum': 30.952380952380953, 'length': 103.0, 'str_em': 50.0, 'Disambig-F1': 54.166666666666664}
{'first_retrival': 0.7, 'second_retrival': 0.8}
First Retrival Match Rate: 0.1
First ans: The Oriental Bank of Commerce has a total of 2390 branches across India, as per its annual report for the year 2018-2019. This number includes branches acquired from other banks, such as Global Trust Bank, which was amalgamated into OBC in 2004. The bank has a significant presence in various states and union territories, with a large number of branches in states like Maharashtra, Tamil Nadu, and Karnataka. The exact number of branches in each state is not explicitly mentioned in the provided context. However, the bank's annual report provides a detailed breakdown of its branch network and geographical distribution.
Second Retrival Match Rate: 0.1
Second ans: The Oriental Bank of Commerce has a total of 2390 branches across India. As of March 2018-2019, the bank had 2390 branches and 2625 ATMs pan India. The acquisition of Global Trust Bank (GTB) in 2004 brought 103 branches to OBC, increasing its branch total to 1092.
The Oriental Bank of Commerce has a total of 2390 branches across India. As of March 2018-2019, the bank had 2390 branches and 2625 ATMs pan India. The acquisition of Global Trust Bank (GTB) in 2004 brought 103 branches to OBC, increasing its branch total to 1092.
Number of branches of oriental bank of commerce in india?
['As per the March 2018-2019 report, what is the number of branches of oriental bank of commerce in india?', 'What is the number of branches of oriental bank of commerce in india after amalgamation of Global Trust Bank?', 'Number of branches of oriental bank of commerce in india after expected merger with United Bank of India in 2020?']
[['2390'], ['1092'], ['11,437']]

 80%|████████  | 16/20 [05:26<01:16, 19.00s/it]

follow question : As per the March 2018-2019 report, what is the number of branches of oriental bank of commerce in india?
short answer : ['2390']
{'score': 0.6184519529342651, 'start': 109, 'end': 113, 'answer': '2390'}
follow question : What is the number of branches of oriental bank of commerce in india after amalgamation of Global Trust Bank?
short answer : ['1092']
{'score': 0.13961704075336456, 'start': 45, 'end': 49, 'answer': '2390'}
follow question : Number of branches of oriental bank of commerce in india after expected merger with United Bank of India in 2020?
short answer : ['11,437']
{'score': 0.13313038647174835, 'start': 45, 'end': 49, 'answer': '2390'}
{'rougeLsum': 51.37614678899083, 'length': 47.0, 'str_em': 66.66666666666666, 'Disambig-F1': 33.33333333333333}
{'first_retrival': 0.1, 'second_retrival': 0.1}
First Retrival Match Rate: 0.5
First ans: The Rams relocated to St. Louis in 1995, and played their first game in St. Louis on September 10, 1995, against the New Orleans Saints. They initially played at Busch Memorial Stadium and later moved to the Trans World Dome, which was renamed the Edward Jones Dome in 2005. The team played in St. Louis until the end of the 2015 season, after which they returned to Los Angeles. During their time in St. Louis, the Rams experienced their greatest period of success from 1999 to 2006, winning their first and only Super Bowl title in 1999. The relocation to St. Louis was initially met with opposition from the team's original fans in Los Angeles, who felt that the team had abandoned its roots in the city.
Second Retrival Match Rate: 0.5
Second ans: The Rams relocated to St. Louis in 1995, after the 1994 NFL season, and became known as the St. Louis Rams. They initially played their home games at Busch Memorial Stadium and later moved to the Trans World Dome, now known as the Dome at America's Center, in downtown St. Louis. The team's relocation was a result of Georgia Frontiere's efforts to find a new home for the Rams after the team's financial struggles in Los Angeles. The Rams played in St. Louis for 21 seasons, from 1995 to 2015, before returning to Los Angeles in 2016. The relocation was initially met with excitement and optimism in St. Louis, but the team's struggles on the field and financial issues eventually led to their departure.
The Rams relocated to St. Louis in 1995, after the 1994 NFL season, and became known as the St. Louis Rams. They initially played their home games at Busch Memorial Stadium and later moved to the Trans World Dome, now known as the Dome at America's Center, in downtown St. Louis. The team's relocation was a result of Georgia Frontiere's efforts to find a new home for the Rams after the team's financial struggles in Los Angeles. The Rams played in St. Louis for 21 seasons, from 1995 to 2015, before returning to Los Angeles in 2016. The relocation was initially met with excitement and optimism in St. Louis, but the team's struggles on the field and financial issues eventually led to their departure.
When did the rams go to st louis?
['In what year did the rams go to St. Louis?', 'What was the first game the Rams played in St. Louis?']
[['1995'], ['September 10, 1995']]

 85%|████████▌ | 17/20 [05:51<01:02, 20.67s/it]

follow question : In what year did the rams go to St. Louis?
short answer : ['1995']
{'score': 0.5273695588111877, 'start': 35, 'end': 39, 'answer': '1995'}
follow question : What was the first game the Rams played in St. Louis?
short answer : ['September 10, 1995']
{'score': 0.893345296382904, 'start': 150, 'end': 172, 'answer': 'Busch Memorial Stadium'}
{'rougeLsum': 42.79835390946502, 'length': 124.0, 'str_em': 50.0, 'Disambig-F1': 50.0}
{'first_retrival': 0.5, 'second_retrival': 0.5}
First Retrival Match Rate: 0.8
First ans: The Voortrekkers arrived in South Africa in various waves, with the first wave trek parties led by Louis Tregardt, Hans van Rensburg, Hendrik Potgieter, Gerrit Maritz, Piet Retief, and Piet Uys leaving the Cape Colony in September 1835, late 1835 or early 1836, late 1835 or early 1836, September 1836, February 1837, and April 1837, respectively. The first two parties crossed the Vaal river at Robert's Drift in January 1836. The Voortrekkers established five to six large settlements between the Vaal and Orange Rivers by spring 1837. The Voortrekkers continued to arrive in South Africa over the next few years, with some parties arriving as late as 1840. The Voortrekkers' movement was a complex and ongoing process, with different groups arriving at different times.
Second Retrival Match Rate: 0.8
Second ans: The Voortrekkers arrived in South Africa in various waves, starting from 1835 to 1840, with the first two parties led by Louis Tregardt and Hans van Rensburg leaving in September 1835. Hendrik Potgieter's party trekked out of the Tarka area in either late 1835 or early 1836, while Gerrit Maritz's party began their trek from Graaff-Reinet in September 1836. Piet Retief's party arrived in February 1837, and Piet Uys's party arrived in April 1837. The Great Trek was a mass migration of Dutch-speaking settlers who traveled by wagon trains from the Cape Colony into the interior of modern South Africa, with the first exploratory treks to Natal taking place in 1834 and 1835. The Voortrekkers, as a youth organization, was founded in 1931, and its members celebrated the completion of the Voortrekker Monument in 1949.
The Voortrekkers arrived in South Africa in various waves, starting from 1835 to 1840, with the first two parties led by Louis Tregardt and Hans van Rensburg leaving in September 1835. Hendrik Potgieter's party trekked out of the Tarka area in either late 1835 or early 1836, while Gerrit Maritz's party began their trek from Graaff-Reinet in September 1836. Piet Retief's party arrived in February 1837, and Piet Uys's party arrived in April 1837. The Great Trek was a mass migration of Dutch-speaking settlers who traveled by wagon trains from the Cape Colony into the interior of modern South Africa, with the first exploratory treks to Natal taking place in 1834 and 1835. The Voortrekkers, as a youth organization, was founded in 1931, and its members celebrated the completion of the Voortrekker Monument in 1949.
When did the voortrekkers arrive in south africa?
['When did the first wave of voortrekkers arrive in south africa?', 'When did the voortrekkers exploratory treks arrive in south africa?']
[['1836', '1836 onwards'], ['February 1835']]

 90%|█████████ | 18/20 [06:25<00:49, 24.84s/it]

follow question : When did the first wave of voortrekkers arrive in south africa?
short answer : ['1836', '1836 onwards']
{'score': 0.6307660937309265, 'start': 73, 'end': 85, 'answer': '1835 to 1840'}
follow question : When did the voortrekkers exploratory treks arrive in south africa?
short answer : ['February 1835']
{'score': 0.30857062339782715, 'start': 662, 'end': 675, 'answer': '1834 and 1835'}
{'rougeLsum': 35.67567567567568, 'length': 135.0, 'str_em': 50.0, 'Disambig-F1': 20.0}
{'first_retrival': 0.8, 'second_retrival': 0.8}
First Retrival Match Rate: 0.8
First ans: In the 1999 film "10 Things I Hate About You", the character Patrick Verona is played by Heath Ledger. In the 2009-2010 television series "10 Things I Hate About You", the character Patrick Verona is played by Ethan Peck. The character Patrick Verona is a significant role in both the film and the television series, as he is the love interest of the main character Kat Stratford. The character Patrick Verona is known for his bad boy image and his complicated relationship with Kat. Both Heath Ledger and Ethan Peck bring depth and complexity to the character of Patrick Verona in their respective versions of the story.
Second Retrival Match Rate: 0.5
Second ans: In the 1999 film adaptation of 10 Things I Hate About You, Patrick Verona is played by Heath Ledger. In the 2009-2010 TV series adaptation, Patrick Verona is played by Ethan Peck.
In the 1999 film adaptation of 10 Things I Hate About You, Patrick Verona is played by Heath Ledger. In the 2009-2010 TV series adaptation, Patrick Verona is played by Ethan Peck.
Who plays patrick in 10 things i hate about you?
['Who plays patrick in  the 1999 film 10 things i hate about you?', 'Who plays patrick in the 2009 tv series 10 things i hate about you?', 'Who plays patrick in the film 10 things i hate about you?', 'Who plays patrick in the TV series 10 things i hate about you?']
[['Heath Andrew Ledger', 'Heath Ledger', 'Ledger'], ['Ethan Peck', 'Peck', 'Ethan Gregory Peck'], ['Heath Andrew Ledger', 'Heath Ledger'], ['Ethan Peck', 'Ethan Gregory Peck']]

 95%|█████████▌| 19/20 [06:40<00:21, 21.66s/it]

follow question : Who plays patrick in  the 1999 film 10 things i hate about you?
short answer : ['Heath Andrew Ledger', 'Heath Ledger', 'Ledger']
{'score': 0.9672249555587769, 'start': 87, 'end': 99, 'answer': 'Heath Ledger'}
follow question : Who plays patrick in the 2009 tv series 10 things i hate about you?
short answer : ['Ethan Peck', 'Peck', 'Ethan Gregory Peck']
{'score': 0.8626343607902527, 'start': 168, 'end': 178, 'answer': 'Ethan Peck'}
follow question : Who plays patrick in the film 10 things i hate about you?
short answer : ['Heath Andrew Ledger', 'Heath Ledger']
{'score': 0.9423097968101501, 'start': 87, 'end': 99, 'answer': 'Heath Ledger'}
follow question : Who plays patrick in the TV series 10 things i hate about you?
short answer : ['Ethan Peck', 'Ethan Gregory Peck']
{'score': 0.7188664674758911, 'start': 168, 'end': 178, 'answer': 'Ethan Peck'}
{'rougeLsum': 71.23287671232875, 'length': 32.0, 'str_em': 100.0, 'Disambig-F1': 100.0}
{'first_retrival': 0.8, 'second_retrival': 0.5}
First Retrival Match Rate: 0.7
First ans: The chief minister of Madhya Pradesh is Kamal Nath, who is a member of the Indian National Congress. He was appointed as the chief minister on 17 December 2018 and is currently in office. Prior to Kamal Nath, the chief ministers of Madhya Pradesh were Shivraj Singh Chouhan, Babulal Gaur, Uma Bharti, Digvijaya Singh, and Arjun Singh, among others. The current government of Kamal Nath is the 15th Assembly of Madhya Pradesh, which was elected in the 2018 state assembly elections.
Second Retrival Match Rate: 0.7
Second ans: The current chief minister of Madhya Pradesh is Kamal Nath of the Indian National Congress. He was appointed on 17 December 2018 and is still in office. Prior to Kamal Nath, the chief ministers of Madhya Pradesh were Shivraj Singh Chouhan of the Bharatiya Janata Party, who served from 2005 to 2018, and Digvijaya Singh of the Indian National Congress, who served from 1993 to 2003. The list of chief ministers of Madhya Pradesh includes names like Uma Bharti, Babulal Gaur, and others.
The current chief minister of Madhya Pradesh is Kamal Nath of the Indian National Congress. He was appointed on 17 December 2018 and is still in office. Prior to Kamal Nath, the chief ministers of Madhya Pradesh were Shivraj Singh Chouhan of the Bharatiya Janata Party, who served from 2005 to 2018, and Digvijaya Singh of the Indian National Congress, who served from 1993 to 2003. The list of chief ministers of Madhya Pradesh includes names like Uma Bharti, Babulal Gaur, and others.
Who is the chief minister of m. p?
['Who is the 17th Chief Minister of MP?', 'Who is the 16th Chief Minister of MP?', 'Who is the 15th Chief Minister of MP?', 'Who is the 17th chief minister of m. p?', 'Who is the 16th chief minister of m. p?', 'Who is the 15th chief minister of m. p?']
[['Shivraj Singh Chauhan'], ['Babulal Gaur'], ['Uma Bharti'], ['Shivraj Singh Chauhan'], ['Babulal Gaur', 'Babulal Gaur Yadav'], ['Uma Bharti']]

100%|██████████| 20/20 [06:58<00:00, 20.92s/it]

follow question : Who is the 17th Chief Minister of MP?
short answer : ['Shivraj Singh Chauhan']
{'score': 0.006330415140837431, 'start': 48, 'end': 58, 'answer': 'Kamal Nath'}
follow question : Who is the 16th Chief Minister of MP?
short answer : ['Babulal Gaur']
{'score': 0.0007905298261903226, 'start': 48, 'end': 58, 'answer': 'Kamal Nath'}
follow question : Who is the 15th Chief Minister of MP?
short answer : ['Uma Bharti']
{'score': 0.00046769733307883143, 'start': 48, 'end': 58, 'answer': 'Kamal Nath'}
follow question : Who is the 17th chief minister of m. p?
short answer : ['Shivraj Singh Chauhan']
{'score': 0.0013391203247010708, 'start': 48, 'end': 58, 'answer': 'Kamal Nath'}
follow question : Who is the 16th chief minister of m. p?
short answer : ['Babulal Gaur', 'Babulal Gaur Yadav']
{'score': 0.0001431153214070946, 'start': 48, 'end': 58, 'answer': 'Kamal Nath'}
follow question : Who is the 15th chief minister of m. p?
short answer : ['Uma Bharti']
{'score': 6.877242412883788e-05, 'start': 48, 'end': 58, 'answer': 'Kamal Nath'}
{'rougeLsum': 43.29896907216495, 'length': 83.0, 'str_em': 66.66666666666666, 'Disambig-F1': 0.0}
{'first_retrival': 0.7, 'second_retrival': 0.7}

first_retrival     0.675
second_retrival    0.635
dtype: float64

In [41]:
scores_df.mean()

rougeLsum      41.618101
length         90.600000
str_em         67.083333
Disambig-F1    51.569444
dtype: float64

In [19]:
scores_df.to_csv('./results/answer_rag_4_len60_results.csv', index=False)

In [20]:
import pandas as pd
import math
sf = pd.read_csv('results/answer_rag_4_len60_results.csv')
sf=sf[sf['length']<1000][:100]
print(len(sf))
print(sf.mean())
r=sf.mean()['rougeLsum']
d=sf.mean()['Disambig-F1']
dr=math.sqrt(r*d)
print(dr)

60
rougeLsum      38.451280
length         99.533333
str_em         64.583333
Disambig-F1    51.052730
dtype: float64
44.30623874568943

In [27]:
from tqdm import tqdm
from evaluation import evaluate

set_seed()

stop_iteration = 20

scores_list=[]
for idx, row in tqdm(qa_df.iterrows(), total=min([stop_iteration, len(qa_df)])):
    if idx == stop_iteration: break
    query = row['question']
    retrieved_docs = retrieve_documents(query)
    first_ans=answer(query,retrieved_docs)
    print('First ans:', first_ans[0])
    ans_docs=retrieve_documents(first_ans[0])
    final_ans=answer(first_ans[0],ans_docs)
    print('Second ans:', final_ans[0])
    scores=evaluate(final_ans, [row.to_dict()])
    scores_list.append(scores)
    scores_df=pd.DataFrame(scores_list)
    print(scores)
        
scores_df=pd.DataFrame(scores_list)
scores_df.mean()

  0%|          | 0/20 [00:00<?, ?it/s]/home/dataconv/.cache/huggingface/modules/transformers_modules/nvidia/NV-Embed-v2/5130cf1daf847c1bacee854a6ef1ca939e747fb2/modeling_nvembed.py:349: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'input_ids': torch.tensor(batch_dict.get('input_ids').to(batch_dict.get('input_ids')).long()),
/home/dataconv/anaconda3/envs/sf_rag_djk/lib/python3.10/contextlib.py:103: FutureWarning: `torch.backends.cuda.sdp_kernel()` is deprecated. In the future, this context manager will be removed. Please see `torch.nn.attention.sdpa_kernel()` for the new context manager, with updated signature.
  self.gen = func(*args, **kwds)

First ans: According to the provided context information, the player with the highest goals in world football is Ali Daei of Iran, with 109 goals in international matches.
Second ans: According to the provided context information, the player with the highest goals in world football is Ali Daei of Iran, with 109 goals in international matches.
According to the provided context information, the player with the highest goals in world football is Ali Daei of Iran, with 109 goals in international matches.
Who has the highest goals in world football?
["Who has the highest goals in men's world international football?", "Who has the highest goals all-time in men's football?", "Who has the highest goals in women's world international football?"]
[['Daei', 'Ali Daei'], ['Bican', 'Josef Bican'], ['Sinclair', 'Christine Sinclair']]

  5%|▌         | 1/20 [00:07<02:27,  7.74s/it]

follow question : Who has the highest goals in men's world international football?
short answer : ['Daei', 'Ali Daei']
{'score': 0.8568584322929382, 'start': 102, 'end': 110, 'answer': 'Ali Daei'}
follow question : Who has the highest goals all-time in men's football?
short answer : ['Bican', 'Josef Bican']
{'score': 0.17466114461421967, 'start': 102, 'end': 110, 'answer': 'Ali Daei'}
follow question : Who has the highest goals in women's world international football?
short answer : ['Sinclair', 'Christine Sinclair']
{'score': 0.05843370407819748, 'start': 102, 'end': 110, 'answer': 'Ali Daei'}
{'rougeLsum': 36.36363636363637, 'length': 26.0, 'str_em': 33.33333333333333, 'Disambig-F1': 33.33333333333333}
First ans: Simon & Garfunkel
Second ans: Simon & Garfunkel was an American folk rock duo consisting of Paul Simon and Art Garfunkel. They were one of the most popular and influential musical acts of the 1960s, known for their harmonious vocals and introspective songwriting.Simon & Garfunkel's music career began in the early 1960s, when they performed together as a folk duo called Tom and Jerry. However, they went their separate ways in the late 1950s and early 1960s, with Simon attending college and Garfunkel studying at Columbia University.In 1963, Simon and Garfunkel regrouped and began performing together again, this time as Simon & Garfunkel. They signed with Columbia Records and released their debut album, "Wednesday Morning, 3 A.M.," in 1964. Although the album was initially a commercial failure, it eventually gained popularity and became a cult classic.Simon & Garfunkel's breakthrough came with the release of their single "The Sound of Silence" in 1965. The song, which was originally recorded in an acoustic version for their debut album, was remixed with electric instruments and drums by producer Tom Wilson. The new version of the song became a huge success, reaching number one on the Billboard Hot 100 chart in January 1966.The duo's second album, "Sounds of Silence," was released in 1966 and featured a mix of folk rock, pop, and psychedelic sounds. The album included the hit singles "I Am a Rock" and "The Sound of Silence," and became a huge commercial success, reaching number 21 on the Billboard 200 chart.Simon & Garfunkel's music career continued to thrive throughout the 1960s and 1970s, with the release of albums such as "Parsley, Sage, Rosemary and Thyme" and "Bridge Over Troubled Water." They became one of the most popular and influential musical acts of the decade, known for their harmonious vocals and introspective songwriting.Some of their most famous songs include:* "The Sound of Silence"* "I Am a Rock"* "The Boxer"* "Bridge Over Troubled Water"* "Cecilia"* "Mrs. Robinson"Simon & Garfunkel's music has had a lasting impact on the music industry, and they continue to be celebrated as one of the most influential and beloved musical acts of all
Simon & Garfunkel was an American folk rock duo consisting of Paul Simon and Art Garfunkel. They were one of the most popular and influential musical acts of the 1960s, known for their harmonious vocals and introspective songwriting.Simon & Garfunkel's music career began in the early 1960s, when they performed together as a folk duo called Tom and Jerry. However, they went their separate ways in the late 1950s and early 1960s, with Simon attending college and Garfunkel studying at Columbia University.In 1963, Simon and Garfunkel regrouped and began performing together again, this time as Simon & Garfunkel. They signed with Columbia Records and released their debut album, "Wednesday Morning, 3 A.M.," in 1964. Although the album was initially a commercial failure, it eventually gained popularity and became a cult classic.Simon & Garfunkel's breakthrough came with the release of their single "The Sound of Silence" in 1965. The song, which was originally recorded in an acoustic version for their debut album, was remixed with electric instruments and drums by producer Tom Wilson. The new version of the song became a huge success, reaching number one on the Billboard Hot 100 chart in January 1966.The duo's second album, "Sounds of Silence," was released in 1966 and featured a mix of folk rock, pop, and psychedelic sounds. The album included the hit singles "I Am a Rock" and "The Sound of Silence," and became a huge commercial success, reaching number 21 on the Billboard 200 chart.Simon & Garfunkel's music career continued to thrive throughout the 1960s and 1970s, with the release of albums such as "Parsley, Sage, Rosemary and Thyme" and "Bridge Over Troubled Water." They became one of the most popular and influential musical acts of the decade, known for their harmonious vocals and introspective songwriting.Some of their most famous songs include:* "The Sound of Silence"* "I Am a Rock"* "The Boxer"* "Bridge Over Troubled Water"* "Cecilia"* "Mrs. Robinson"Simon & Garfunkel's music has had a lasting impact on the music industry, and they continue to be celebrated as one of the most influential and beloved musical acts of all
Who is the original artist of sound of silence?
['Who is the original artist of sound of silence, the song, released in 1964?', 'Who is the original artist of sound of silence, the album?', 'Who is the original artist of sound of silence, the song, released in 2016?']
[['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon'], ['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon'], ['Dami Im']]

 10%|█         | 2/20 [00:36<06:06, 20.37s/it]

follow question : Who is the original artist of sound of silence, the song, released in 1964?
short answer : ['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon']
{'score': 0.0009827768662944436, 'start': 1080, 'end': 1090, 'answer': 'Tom Wilson'}
follow question : Who is the original artist of sound of silence, the album?
short answer : ['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon']
{'score': 0.13287265598773956, 'start': 1499, 'end': 1516, 'answer': 'Simon & Garfunkel'}
follow question : Who is the original artist of sound of silence, the song, released in 2016?
short answer : ['Dami Im']
{'score': 6.20093260295107e-06, 'start': 1080, 'end': 1090, 'answer': 'Tom Wilson'}
{'rougeLsum': 21.97309417040359, 'length': 348.0, 'str_em': 66.66666666666666, 'Disambig-F1': 33.33333333333333}
First ans: The first Apple iPhone was made in 2005, when Apple started to gather a team of 1,000 employees to work on the highly confidential "Project Purple."
Second ans: The statement is incorrect. The first Apple iPhone was not made in 2005. According to the provided information, development of the iPhone began in 2005, but it was released in 2007. The development cost of the collaboration was estimated to have been $150 million over a thirty-month period, and the original iPhone was introduced by Steve Jobs on January 9, 2007, at the Macworld Conference & Expo held in Moscone West in San Francisco, California.
The statement is incorrect. The first Apple iPhone was not made in 2005. According to the provided information, development of the iPhone began in 2005, but it was released in 2007. The development cost of the collaboration was estimated to have been $150 million over a thirty-month period, and the original iPhone was introduced by Steve Jobs on January 9, 2007, at the Macworld Conference & Expo held in Moscone West in San Francisco, California.
When was the first apple i phone made?
['When was the first apple i phone released?', 'When was the first apple i phone for beta testing made?', 'When was the first apple i phone 1 made?', 'When was the first apple i phone beta made?']
[['June 29, 2007'], ['2004'], ['June 29, 2007.'], ['2004.']]

 15%|█▌        | 3/20 [00:47<04:27, 15.75s/it]

follow question : When was the first apple i phone released?
short answer : ['June 29, 2007']
{'score': 0.5703911781311035, 'start': 176, 'end': 180, 'answer': '2007'}
follow question : When was the first apple i phone for beta testing made?
short answer : ['2004']
{'score': 0.2193128764629364, 'start': 67, 'end': 71, 'answer': '2005'}
follow question : When was the first apple i phone 1 made?
short answer : ['June 29, 2007.']
{'score': 0.3912900984287262, 'start': 67, 'end': 71, 'answer': '2005'}
follow question : When was the first apple i phone beta made?
short answer : ['2004.']
{'score': 0.07923733443021774, 'start': 67, 'end': 71, 'answer': '2005'}
{'rougeLsum': 34.53237410071942, 'length': 75.0, 'str_em': 0.0, 'Disambig-F1': 12.5}
First ans: The Weasley brothers were played by the following actors:* Bill Weasley: Richard Fish (briefly in the film adaptation of Harry Potter and the Prisoner of Azkaban), Domhnall Gleeson (in Harry Potter and the Deathly Hallows)* Charlie Weasley: Alex Crockford (briefly in the film adaptation of Prisoner of Azkaban)* Fred and George Weasley: James and Oliver PhelpsThey are twins who played the identical twin brothers in the film series.
Second ans: The Weasley brothers were played by the following actors:* Bill Weasley: Richard Fish (briefly in the film adaptation of Harry Potter and the Prisoner of Azkaban), Domhnall Gleeson (in Harry Potter and the Deathly Hallows)* Charlie Weasley: Alex Crockford (briefly in the film adaptation of Prisoner of Azkaban)* Fred and George Weasley: James and Oliver Phelps (They are twins who played the identical twin brothers in the film series.)
The Weasley brothers were played by the following actors:* Bill Weasley: Richard Fish (briefly in the film adaptation of Harry Potter and the Prisoner of Azkaban), Domhnall Gleeson (in Harry Potter and the Deathly Hallows)* Charlie Weasley: Alex Crockford (briefly in the film adaptation of Prisoner of Azkaban)* Fred and George Weasley: James and Oliver Phelps (They are twins who played the identical twin brothers in the film series.)
Who played the weasley brothers in harry potter?
['Who played  Bill weasley in Harry Potter and the Prisoner of Azkaban?', 'Who played percy weasley in harry potter?', 'Who played fred weasley in harry potter?', 'Who played ron weasley in harry potter?', 'Who played george weasley in harry potter?', 'Who played  Bill weasley in harry potter (2001-2011)?']
[['Richard Fish'], ['Chris Rankin'], ['James Phelps'], ['Rupert Grint'], ['Oliver Phelps'], ['Domhnall Gleeson']]

 20%|██        | 4/20 [01:00<03:55, 14.71s/it]

follow question : Who played  Bill weasley in Harry Potter and the Prisoner of Azkaban?
short answer : ['Richard Fish']
{'score': 0.6618728637695312, 'start': 73, 'end': 85, 'answer': 'Richard Fish'}
follow question : Who played percy weasley in harry potter?
short answer : ['Chris Rankin']
{'score': 0.7059646844863892, 'start': 73, 'end': 85, 'answer': 'Richard Fish'}
follow question : Who played fred weasley in harry potter?
short answer : ['James Phelps']
{'score': 0.7058833837509155, 'start': 73, 'end': 85, 'answer': 'Richard Fish'}
follow question : Who played ron weasley in harry potter?
short answer : ['Rupert Grint']
{'score': 0.7591727375984192, 'start': 73, 'end': 85, 'answer': 'Richard Fish'}
follow question : Who played george weasley in harry potter?
short answer : ['Oliver Phelps']
{'score': 0.3762194514274597, 'start': 73, 'end': 85, 'answer': 'Richard Fish'}
follow question : Who played  Bill weasley in harry potter (2001-2011)?
short answer : ['Domhnall Gleeson']
{'score': 0.6254032254219055, 'start': 73, 'end': 85, 'answer': 'Richard Fish'}
{'rougeLsum': 48.05194805194806, 'length': 69.0, 'str_em': 50.0, 'Disambig-F1': 16.666666666666664}
First ans: According to the provided context information, there are 38 state parks in Virginia.
Second ans: That's correct. According to the provided context information, there are 38 state parks in Virginia.
That's correct. According to the provided context information, there are 38 state parks in Virginia.
How many state parks are there in virginia?
['How many state parks are there in virginia in 1936?', 'How many state parks are there in virginia in 2016?', 'How many state parks were there when the state park system formed in Virginia?', 'How many state parks were there in Virginia as of 2016?']
[['six'], ['38'], ['6'], ['38']]

 25%|██▌       | 5/20 [01:04<02:45, 11.02s/it]

follow question : How many state parks are there in virginia in 1936?
short answer : ['six']
{'score': 0.008646625094115734, 'start': 73, 'end': 75, 'answer': '38'}
follow question : How many state parks are there in virginia in 2016?
short answer : ['38']
{'score': 0.5548556447029114, 'start': 73, 'end': 75, 'answer': '38'}
follow question : How many state parks were there when the state park system formed in Virginia?
short answer : ['6']
{'score': 0.8253440856933594, 'start': 73, 'end': 75, 'answer': '38'}
follow question : How many state parks were there in Virginia as of 2016?
short answer : ['38']
{'score': 0.575831413269043, 'start': 73, 'end': 75, 'answer': '38'}
{'rougeLsum': 31.999999999999996, 'length': 15.0, 'str_em': 50.0, 'Disambig-F1': 50.0}
First ans: Dua Lipa performed at the opening ceremony preceding the final. Jamaican rapper Sean Paul joined her as a special guest to perform their collaborative song, "No Lie". The UEFA Champions League Anthem was performed by Slovenian–Croatian cello duo 2Cellos.
Second ans: Dua Lipa performed at the opening ceremony preceding the 2018 UEFA Champions League Final, accompanied by Jamaican rapper Sean Paul, who performed their collaborative song "No Lie". Additionally, the Slovenian-Croatian cello duo 2Cellos performed the UEFA Champions League Anthem.
Dua Lipa performed at the opening ceremony preceding the 2018 UEFA Champions League Final, accompanied by Jamaican rapper Sean Paul, who performed their collaborative song "No Lie". Additionally, the Slovenian-Croatian cello duo 2Cellos performed the UEFA Champions League Anthem.
Who performed at the champions league final 2018?
['Who are the teams that performed in competition at the champions league final 2018?', 'Who performed best at the champions league final 2018, winning man of the match?', 'Who performed at the opening ceremony of the champions league final 2018?', 'Who performed the anthem at the champions league final 2018?']
[['Real Madrid and Liverpool', 'Liverpool', 'Real Madrid'], ['Gareth Bale', 'Bale'], ['Dua Lipa', 'Sean Paul', 'Dua Lipa and Sean Paul'], ['2Cellos', 'Luka Šulić and Stjepan Hauser', 'Luka Šulić', '2CΞLLOS', 'Stjepan Hauser']]

 30%|███       | 6/20 [01:13<02:23, 10.27s/it]

follow question : Who are the teams that performed in competition at the champions league final 2018?
short answer : ['Real Madrid and Liverpool', 'Liverpool', 'Real Madrid']
{'score': 0.016498327255249023, 'start': 200, 'end': 236, 'answer': 'Slovenian-Croatian cello duo 2Cellos'}
follow question : Who performed best at the champions league final 2018, winning man of the match?
short answer : ['Gareth Bale', 'Bale']
{'score': 0.87488853931427, 'start': 0, 'end': 8, 'answer': 'Dua Lipa'}
follow question : Who performed at the opening ceremony of the champions league final 2018?
short answer : ['Dua Lipa', 'Sean Paul', 'Dua Lipa and Sean Paul']
{'score': 0.7995817065238953, 'start': 0, 'end': 8, 'answer': 'Dua Lipa'}
follow question : Who performed the anthem at the champions league final 2018?
short answer : ['2Cellos', 'Luka Šulić and Stjepan Hauser', 'Luka Šulić', '2CΞLLOS', 'Stjepan Hauser']
{'score': 0.3890477418899536, 'start': 229, 'end': 236, 'answer': '2Cellos'}
{'rougeLsum': 53.54330708661418, 'length': 39.0, 'str_em': 50.0, 'Disambig-F1': 50.0}
First ans: In the movie Thelma and Louise, the man who was killed was Harlan, a stranger who attempted to rape Thelma. He was shot and killed by Louise after she threatened him with a gun.
Second ans: Harlan, a stranger who attempted to rape Thelma, was shot and killed by Louise after she threatened him with a gun.
Harlan, a stranger who attempted to rape Thelma, was shot and killed by Louise after she threatened him with a gun.
Who killed the man in thelma and louise?
['Which character killed the man in thelma and louise?', 'Which actor killed the man in thelma and louise?', 'Who is the character that kills Harlan in the film Thelma and Louise?', 'Who is the actor of the character that killed a man in the film Thelma and Louise?']
[['Louise Elizabeth Sawyer', 'Louise'], ['Susan Sarandon', 'Susan Abigail Sarandon'], ['Louise Elizabeth Sawyer', 'Louise'], ['Susan Sarandon']]

 35%|███▌      | 7/20 [01:20<01:58,  9.15s/it]

follow question : Which character killed the man in thelma and louise?
short answer : ['Louise Elizabeth Sawyer', 'Louise']
{'score': 0.6458455324172974, 'start': 0, 'end': 6, 'answer': 'Harlan'}
follow question : Which actor killed the man in thelma and louise?
short answer : ['Susan Sarandon', 'Susan Abigail Sarandon']
{'score': 0.6744271516799927, 'start': 0, 'end': 6, 'answer': 'Harlan'}
follow question : Who is the character that kills Harlan in the film Thelma and Louise?
short answer : ['Louise Elizabeth Sawyer', 'Louise']
{'score': 0.6058520078659058, 'start': 10, 'end': 18, 'answer': 'stranger'}
follow question : Who is the actor of the character that killed a man in the film Thelma and Louise?
short answer : ['Susan Sarandon']
{'score': 0.772394597530365, 'start': 0, 'end': 6, 'answer': 'Harlan'}
{'rougeLsum': 15.384615384615383, 'length': 21.0, 'str_em': 50.0, 'Disambig-F1': 0.0}
First ans: Charlie Kelly is played by Charlie Day.
Second ans: Yes, that is correct. Charlie Kelly is played by Charlie Day.
Yes, that is correct. Charlie Kelly is played by Charlie Day.
Who plays charlie on it's always sunny?
["Who does Charlie Day play on It's Always Sunny in Philadelphia?", "Who plays Charlie Kelly on It's Always Sunny in Philadelphia?"]
[['Charlie Kelly'], ['Charlie Day']]

 40%|████      | 8/20 [01:24<01:29,  7.49s/it]

follow question : Who does Charlie Day play on It's Always Sunny in Philadelphia?
short answer : ['Charlie Kelly']
{'score': 0.9868155717849731, 'start': 22, 'end': 35, 'answer': 'Charlie Kelly'}
follow question : Who plays Charlie Kelly on It's Always Sunny in Philadelphia?
short answer : ['Charlie Day']
{'score': 0.9854613542556763, 'start': 49, 'end': 60, 'answer': 'Charlie Day'}
{'rougeLsum': 32.25806451612903, 'length': 11.0, 'str_em': 100.0, 'Disambig-F1': 100.0}
First ans: The Los Angeles Lakers have won the NBA Finals 16 times.
Second ans: Yes, that's correct. The Los Angeles Lakers have won the NBA Finals 16 times, which is the second-most championships in NBA history, behind the Boston Celtics' 17 championships.
Yes, that's correct. The Los Angeles Lakers have won the NBA Finals 16 times, which is the second-most championships in NBA history, behind the Boston Celtics' 17 championships.
How many times have the lakers won the finals?
['As of 2017, how many times have the lakers won the finals?', 'As of 2016, how many times have the Lakers won the finals?', 'As of 2015, how many times have the Lakers won the finals?']
[['16'], ['16'], ['16']]

 45%|████▌     | 9/20 [01:30<01:18,  7.10s/it]

follow question : As of 2017, how many times have the lakers won the finals?
short answer : ['16']
{'score': 0.8009308576583862, 'start': 68, 'end': 70, 'answer': '16'}
follow question : As of 2016, how many times have the Lakers won the finals?
short answer : ['16']
{'score': 0.8325595259666443, 'start': 68, 'end': 70, 'answer': '16'}
follow question : As of 2015, how many times have the Lakers won the finals?
short answer : ['16']
{'score': 0.6845507621765137, 'start': 68, 'end': 70, 'answer': '16'}
{'rougeLsum': 37.83783783783784, 'length': 28.0, 'str_em': 100.0, 'Disambig-F1': 100.0}
First ans: Based on the provided context information, the following states in India are under the Congress:1. Punjab2. Chhattisgarh3. Rajasthan4. Madhya Pradesh5. Puducherry (union territory)6. Maharashtra (as part of the Maha Vikas Aghadi coalition)7. Jharkhand (junior ally with Jharkhand Mukti Morcha)These states and union territories are under the control of the Indian National Congress, either as the ruling party or as part of a coalition government.
Second ans: Based on the provided context information, the following states in India are under the Congress:1. Punjab2. Chhattisgarh3. Rajasthan4. Madhya Pradesh5. Puducherry (union territory)6. Maharashtra (as part of the Maha Vikas Aghadi coalition)7. Jharkhand (junior ally with Jharkhand Mukti Morcha)These states and union territories are under the control of the Indian National Congress, either as the ruling party or as part of a coalition government.
Based on the provided context information, the following states in India are under the Congress:1. Punjab2. Chhattisgarh3. Rajasthan4. Madhya Pradesh5. Puducherry (union territory)6. Maharashtra (as part of the Maha Vikas Aghadi coalition)7. Jharkhand (junior ally with Jharkhand Mukti Morcha)These states and union territories are under the control of the Indian National Congress, either as the ruling party or as part of a coalition government.
How many states in india are under congress?
['How many states plus territories in india are under congress?', 'How many states alone in india are under congress?']
[['7'], ['5']]

 50%|█████     | 10/20 [01:44<01:31,  9.19s/it]

follow question : How many states plus territories in india are under congress?
short answer : ['7']
{'score': 0.023033540695905685, 'start': 96, 'end': 106, 'answer': '1. Punjab2'}
follow question : How many states alone in india are under congress?
short answer : ['5']
{'score': 0.015681445598602295, 'start': 43, 'end': 56, 'answer': 'the following'}
{'rougeLsum': 31.007751937984494, 'length': 64.0, 'str_em': 100.0, 'Disambig-F1': 0.0}
First ans: Fruma-Sarah is the deceased wife of Lazar Wolf, a wealthy butcher in the village of Anatevka. She rises from the grave in Tevye's "nightmare" to warn of severe retribution if Tzeitel marries Lazar.
Second ans: Fruma-Sarah is the deceased wife of Lazar Wolf, a wealthy butcher in the village of Anatevka. She rises from the grave in Tevye's "nightmare" to warn of severe retribution if Tzeitel marries Lazar.
Fruma-Sarah is the deceased wife of Lazar Wolf, a wealthy butcher in the village of Anatevka. She rises from the grave in Tevye's "nightmare" to warn of severe retribution if Tzeitel marries Lazar.
Who is fruma sarah in fiddler on the roof?
['Who played fruma sarah in the 1971 film, Fiddler on the Roof?', 'Who played Fruma Sarah in the original 1964 Broadway cast of Fiddler on the Roof?', 'Who is the character of Fruma Sarah in Fiddler on the Roof?', 'Who played Fruma Sarah in the 2015-2016 Broadway Revival of Fiddler on the Roof?']
[['Ruth Madoc'], ['Carol Sawyer Yussel'], ['a ghostly depiction of the late wife of Lazar Wolf'], ['Jessica Vosk']]

 55%|█████▌    | 11/20 [01:52<01:19,  8.88s/it]

follow question : Who played fruma sarah in the 1971 film, Fiddler on the Roof?
short answer : ['Ruth Madoc']
{'score': 0.0021976102143526077, 'start': 122, 'end': 127, 'answer': 'Tevye'}
follow question : Who played Fruma Sarah in the original 1964 Broadway cast of Fiddler on the Roof?
short answer : ['Carol Sawyer Yussel']
{'score': 0.023890621960163116, 'start': 122, 'end': 127, 'answer': 'Tevye'}
follow question : Who is the character of Fruma Sarah in Fiddler on the Roof?
short answer : ['a ghostly depiction of the late wife of Lazar Wolf']
{'score': 0.5104489326477051, 'start': 36, 'end': 46, 'answer': 'Lazar Wolf'}
follow question : Who played Fruma Sarah in the 2015-2016 Broadway Revival of Fiddler on the Roof?
short answer : ['Jessica Vosk']
{'score': 0.005705648101866245, 'start': 122, 'end': 127, 'answer': 'Tevye'}
{'rougeLsum': 21.897810218978105, 'length': 33.0, 'str_em': 0.0, 'Disambig-F1': 10.0}
First ans: July 9, 1991, the Toronto Blue Jays hosted the MLB All-Star Game at the SkyDome.
Second ans: No, that is incorrect. The Toronto Blue Jays hosted the MLB All-Star Game on July 9, 1991, at the SkyDome, but they were the American League team, and the host team was actually the Toronto Blue Jays.
No, that is incorrect. The Toronto Blue Jays hosted the MLB All-Star Game on July 9, 1991, at the SkyDome, but they were the American League team, and the host team was actually the Toronto Blue Jays.
When did toronto host the mlb all-star game?
['What date did toronto host the mlb all-star game?', 'Which all-star game did toronto host?']
[['July 9, 1991'], ['1991 Major League Baseball All-Star Game', 'the 62nd playing of the midsummer classic']]

 60%|██████    | 12/20 [02:00<01:07,  8.44s/it]

follow question : What date did toronto host the mlb all-star game?
short answer : ['July 9, 1991']
{'score': 0.9494990110397339, 'start': 77, 'end': 89, 'answer': 'July 9, 1991'}
follow question : Which all-star game did toronto host?
short answer : ['1991 Major League Baseball All-Star Game', 'the 62nd playing of the midsummer classic']
{'score': 0.3525626063346863, 'start': 56, 'end': 73, 'answer': 'MLB All-Star Game'}
{'rougeLsum': 39.603960396039604, 'length': 37.0, 'str_em': 50.0, 'Disambig-F1': 72.22222222222221}
First ans: A metallic blue 1953 Sunbeam Alpine Mk I is driven by Grace Kelly in the film "To Catch a Thief" (1955) with Cary Grant.
Second ans: The Sunbeam Alpine Mk I, a metallic blue 1953 model, is driven by Grace Kelly in the 1955 film "To Catch a Thief" starring Cary Grant.
The Sunbeam Alpine Mk I, a metallic blue 1953 model, is driven by Grace Kelly in the 1955 film "To Catch a Thief" starring Cary Grant.
What kind of car in to catch a thief?
['What kind of car in to catch a thief in terms of model?', 'What kind of car in to catch a thief in terms of automobile make?']
[['Sunbeam Alpine', '1953 Sunbeam Alpine Mk I'], ['Rootes Group']]

 65%|██████▌   | 13/20 [02:07<00:55,  7.99s/it]

follow question : What kind of car in to catch a thief in terms of model?
short answer : ['Sunbeam Alpine', '1953 Sunbeam Alpine Mk I']
{'score': 0.5046610832214355, 'start': 4, 'end': 23, 'answer': 'Sunbeam Alpine Mk I'}
follow question : What kind of car in to catch a thief in terms of automobile make?
short answer : ['Rootes Group']
{'score': 0.5758154988288879, 'start': 4, 'end': 23, 'answer': 'Sunbeam Alpine Mk I'}
{'rougeLsum': 31.746031746031743, 'length': 26.0, 'str_em': 50.0, 'Disambig-F1': 44.44444444444445}
First ans: The last season of Jersey Shore (Season 6) aired from October 4, 2012, to December 20, 2012.
Second ans: The last season of Jersey Shore (Season 6) actually aired from October 4, 2012, to December 4, 2012, not December 20, 2012.
The last season of Jersey Shore (Season 6) actually aired from October 4, 2012, to December 4, 2012, not December 20, 2012.
When did the last season of jersey shore air?
['When did season 4 of jersey shore first air?', 'When did season 4 of jersey shore last air?', 'When did season 5 of jersey shore first air?', 'When did season 5 of jersey shore last air?', 'When did season 6 of jersey shore first air?', 'When did season 6 of jersey shore last air?']
[['August 4, 2011'], ['October 20, 2011'], ['January 5, 2012'], ['March 15, 2012'], ['October 4, 2012'], ['December 20, 2012']]

 70%|███████   | 14/20 [02:13<00:45,  7.63s/it]

follow question : When did season 4 of jersey shore first air?
short answer : ['August 4, 2011']
{'score': 0.07206683605909348, 'start': 63, 'end': 78, 'answer': 'October 4, 2012'}
follow question : When did season 4 of jersey shore last air?
short answer : ['October 20, 2011']
{'score': 0.2847982347011566, 'start': 83, 'end': 99, 'answer': 'December 4, 2012'}
follow question : When did season 5 of jersey shore first air?
short answer : ['January 5, 2012']
{'score': 0.021944589912891388, 'start': 63, 'end': 78, 'answer': 'October 4, 2012'}
follow question : When did season 5 of jersey shore last air?
short answer : ['March 15, 2012']
{'score': 0.09906397759914398, 'start': 63, 'end': 78, 'answer': 'October 4, 2012'}
follow question : When did season 6 of jersey shore first air?
short answer : ['October 4, 2012']
{'score': 0.17413854598999023, 'start': 63, 'end': 78, 'answer': 'October 4, 2012'}
follow question : When did season 6 of jersey shore last air?
short answer : ['December 20, 2012']
{'score': 0.6348809599876404, 'start': 63, 'end': 78, 'answer': 'October 4, 2012'}
{'rougeLsum': 43.0379746835443, 'length': 22.0, 'str_em': 33.33333333333333, 'Disambig-F1': 38.88888888888889}
First ans: The plane crash occurred in the Season 8 episode "Flight" which is the 24th episode of the season and the 172nd episode overall.
Second ans: The plane crash occurred in the Season 8 episode "Flight" which is the 24th episode of the season and the 172nd episode overall.
The plane crash occurred in the Season 8 episode "Flight" which is the 24th episode of the season and the 172nd episode overall.
What season of greys anatomy was the plane crash?
["What season of Grey's Anatomy was the plane crash involving six doctors?", "What season of Grey's Anatomy was the plane crash in Seattle that brought memories of a previous plane crash?", "What season of Grey's Anatomy was the plane crash that claimed the life of Lexie Grey?", "What season of Grey's Anatomy was the plane crash in downtown Seattle?"]
[['season 8'], ['season 11'], ['8'], ['11']]

 75%|███████▌  | 15/20 [02:20<00:36,  7.23s/it]

follow question : What season of Grey's Anatomy was the plane crash involving six doctors?
short answer : ['season 8']
{'score': 0.8863816857337952, 'start': 32, 'end': 40, 'answer': 'Season 8'}
follow question : What season of Grey's Anatomy was the plane crash in Seattle that brought memories of a previous plane crash?
short answer : ['season 11']
{'score': 0.9001052379608154, 'start': 32, 'end': 40, 'answer': 'Season 8'}
follow question : What season of Grey's Anatomy was the plane crash that claimed the life of Lexie Grey?
short answer : ['8']
{'score': 0.8906877040863037, 'start': 32, 'end': 40, 'answer': 'Season 8'}
follow question : What season of Grey's Anatomy was the plane crash in downtown Seattle?
short answer : ['11']
{'score': 0.9075095653533936, 'start': 32, 'end': 40, 'answer': 'Season 8'}
{'rougeLsum': 32.35294117647059, 'length': 23.0, 'str_em': 50.0, 'Disambig-F1': 54.166666666666664}
First ans: According to the provided context information, the Oriental Bank of Commerce had 2390 branches across India as of the 2018-2019 annual report.
Second ans: According to the provided context information, the Oriental Bank of Commerce had 2390 branches across India as of the 2018-2019 annual report.
According to the provided context information, the Oriental Bank of Commerce had 2390 branches across India as of the 2018-2019 annual report.
Number of branches of oriental bank of commerce in india?
['As per the March 2018-2019 report, what is the number of branches of oriental bank of commerce in india?', 'What is the number of branches of oriental bank of commerce in india after amalgamation of Global Trust Bank?', 'Number of branches of oriental bank of commerce in india after expected merger with United Bank of India in 2020?']
[['2390'], ['1092'], ['11,437']]

 80%|████████  | 16/20 [02:26<00:28,  7.04s/it]

follow question : As per the March 2018-2019 report, what is the number of branches of oriental bank of commerce in india?
short answer : ['2390']
{'score': 0.8879122734069824, 'start': 81, 'end': 85, 'answer': '2390'}
follow question : What is the number of branches of oriental bank of commerce in india after amalgamation of Global Trust Bank?
short answer : ['1092']
{'score': 0.7891730070114136, 'start': 81, 'end': 85, 'answer': '2390'}
follow question : Number of branches of oriental bank of commerce in india after expected merger with United Bank of India in 2020?
short answer : ['11,437']
{'score': 0.4474791884422302, 'start': 81, 'end': 85, 'answer': '2390'}
{'rougeLsum': 30.952380952380953, 'length': 22.0, 'str_em': 33.33333333333333, 'Disambig-F1': 33.33333333333333}
First ans: 1995
Second ans: Here are some of the notable events and information from the provided context related to the year 1995:1. **Windows 95**: Microsoft released Windows 95, a new version of its operating system, on August 24, 1995. This operating system was designed to be more user-friendly and efficient than its predecessors.2. **1995 Canadian Open**: The 1995 Canadian Open was a men's and women's professional tennis tournament that took place in Montreal, Quebec, Canada, from July 24 to July 31, 1995, and in Toronto, Ontario, Canada, from August 13 to August 20, 1995.3. **Manchester United**: The 1995-96 season was a significant one for Manchester United, as they won the league title and the FA Cup, with Sir Alex Ferguson at the helm.4. **UEFA Champions League**: The 1995-96 UEFA Champions League season saw the introduction of a new format, with the top teams from each group advancing to the quarterfinals.5. **Major League Baseball**: The 1995 season was a notable one for Major League Baseball, with the Colorado Rockies and the New York Yankees competing for the World Series title.6. **FIFA World Cup**: The 1994 FIFA World Cup was held in the United States, and the 1998 FIFA World Cup was held in France. The 1995-96 season was a significant one for the FIFA World Cup, with the introduction of new rules and regulations.7. **Personal Computers**: The 1990s saw significant advancements in personal computers, with the introduction of new technologies such as CD-ROMs, ThinkPads, and Power Macintosh computers.These are just a few of the notable events and information related to the year 1995 from the provided context.
Here are some of the notable events and information from the provided context related to the year 1995:1. **Windows 95**: Microsoft released Windows 95, a new version of its operating system, on August 24, 1995. This operating system was designed to be more user-friendly and efficient than its predecessors.2. **1995 Canadian Open**: The 1995 Canadian Open was a men's and women's professional tennis tournament that took place in Montreal, Quebec, Canada, from July 24 to July 31, 1995, and in Toronto, Ontario, Canada, from August 13 to August 20, 1995.3. **Manchester United**: The 1995-96 season was a significant one for Manchester United, as they won the league title and the FA Cup, with Sir Alex Ferguson at the helm.4. **UEFA Champions League**: The 1995-96 UEFA Champions League season saw the introduction of a new format, with the top teams from each group advancing to the quarterfinals.5. **Major League Baseball**: The 1995 season was a notable one for Major League Baseball, with the Colorado Rockies and the New York Yankees competing for the World Series title.6. **FIFA World Cup**: The 1994 FIFA World Cup was held in the United States, and the 1998 FIFA World Cup was held in France. The 1995-96 season was a significant one for the FIFA World Cup, with the introduction of new rules and regulations.7. **Personal Computers**: The 1990s saw significant advancements in personal computers, with the introduction of new technologies such as CD-ROMs, ThinkPads, and Power Macintosh computers.These are just a few of the notable events and information related to the year 1995 from the provided context.
When did the rams go to st louis?
['In what year did the rams go to St. Louis?', 'What was the first game the Rams played in St. Louis?']
[['1995'], ['September 10, 1995']]

 85%|████████▌ | 17/20 [02:47<00:33, 11.20s/it]

follow question : In what year did the rams go to St. Louis?
short answer : ['1995']
{'score': 0.0012254201574251056, 'start': 98, 'end': 102, 'answer': '1995'}
follow question : What was the first game the Rams played in St. Louis?
short answer : ['September 10, 1995']
{'score': 1.4408171409741044e-05, 'start': 98, 'end': 102, 'answer': '1995'}
{'rougeLsum': 20.971867007672635, 'length': 262.0, 'str_em': 50.0, 'Disambig-F1': 75.0}
First ans: The Voortrekkers, a group of Dutch-speaking settlers, began their trek into South Africa in 1835. The first two parties left in September 1835, led by Louis Tregardt and Hans van Rensburg. They crossed the Vaal river at Robert's Drift in January 1836.However, the question seems to refer to the Voortrekkers as a youth organization, which was established in 1931. In this case, the answer would be:The Voortrekkers youth organization was established in 1931, and its first "Kommando" (Troop) was established in Bloemfontein at the Central High School in 1920.
Second ans: The Voortrekkers youth organization was established in 1931, and its first "Kommando" (Troop) was established in Bloemfontein at the Central High School in 1920.
The Voortrekkers youth organization was established in 1931, and its first "Kommando" (Troop) was established in Bloemfontein at the Central High School in 1920.
When did the voortrekkers arrive in south africa?
['When did the first wave of voortrekkers arrive in south africa?', 'When did the voortrekkers exploratory treks arrive in south africa?']
[['1836', '1836 onwards'], ['February 1835']]

 90%|█████████ | 18/20 [02:59<00:22, 11.42s/it]

follow question : When did the first wave of voortrekkers arrive in south africa?
short answer : ['1836', '1836 onwards']
{'score': 0.0015232550213113427, 'start': 156, 'end': 160, 'answer': '1920'}
follow question : When did the voortrekkers exploratory treks arrive in south africa?
short answer : ['February 1835']
{'score': 4.85175805806648e-05, 'start': 55, 'end': 59, 'answer': '1931'}
{'rougeLsum': 29.78723404255319, 'length': 24.0, 'str_em': 0.0, 'Disambig-F1': 0.0}
First ans: Heath Ledger plays Patrick Verona in the 1999 film "10 Things I Hate About You."
Second ans: Yes, that's correct. In the 1999 film "10 Things I Hate About You," Heath Ledger plays the role of Patrick Verona, the "bad boy" who is hired to date Kat Stratford, played by Julia Stiles.
Yes, that's correct. In the 1999 film "10 Things I Hate About You," Heath Ledger plays the role of Patrick Verona, the "bad boy" who is hired to date Kat Stratford, played by Julia Stiles.
Who plays patrick in 10 things i hate about you?
['Who plays patrick in  the 1999 film 10 things i hate about you?', 'Who plays patrick in the 2009 tv series 10 things i hate about you?', 'Who plays patrick in the film 10 things i hate about you?', 'Who plays patrick in the TV series 10 things i hate about you?']
[['Heath Andrew Ledger', 'Heath Ledger', 'Ledger'], ['Ethan Peck', 'Peck', 'Ethan Gregory Peck'], ['Heath Andrew Ledger', 'Heath Ledger'], ['Ethan Peck', 'Ethan Gregory Peck']]

 95%|█████████▌| 19/20 [03:06<00:09,  9.98s/it]

follow question : Who plays patrick in  the 1999 film 10 things i hate about you?
short answer : ['Heath Andrew Ledger', 'Heath Ledger', 'Ledger']
{'score': 0.9635234475135803, 'start': 68, 'end': 80, 'answer': 'Heath Ledger'}
follow question : Who plays patrick in the 2009 tv series 10 things i hate about you?
short answer : ['Ethan Peck', 'Peck', 'Ethan Gregory Peck']
{'score': 1.869488914962858e-05, 'start': 68, 'end': 80, 'answer': 'Heath Ledger'}
follow question : Who plays patrick in the film 10 things i hate about you?
short answer : ['Heath Andrew Ledger', 'Heath Ledger']
{'score': 0.8692940473556519, 'start': 68, 'end': 80, 'answer': 'Heath Ledger'}
follow question : Who plays patrick in the TV series 10 things i hate about you?
short answer : ['Ethan Peck', 'Ethan Gregory Peck']
{'score': 0.00026919867377728224, 'start': 68, 'end': 80, 'answer': 'Heath Ledger'}
{'rougeLsum': 42.10526315789474, 'length': 35.0, 'str_em': 50.0, 'Disambig-F1': 50.0}
First ans: No, Microsoft Live Movie Maker is not an example of a free product. It is a freeware product, which means it is free to download and use, but it is not open-source. It is a proprietary software developed by Microsoft, and its source code is not available for modification or redistribution.
Second ans: Microsoft Live Movie Maker is actually an example of a freeware product, not a free product. It is a proprietary software developed by Microsoft, and its source code is not available for modification or redistribution. While it is free to download and use, it is not open-source, and its development and maintenance are controlled by Microsoft.
Microsoft Live Movie Maker is actually an example of a freeware product, not a free product. It is a proprietary software developed by Microsoft, and its source code is not available for modification or redistribution. While it is free to download and use, it is not open-source, and its development and maintenance are controlled by Microsoft.
Microsoft live movie maker is an example of free?
['Microsoft live movie maker is an example of a freely licensed software, often called free what?', 'Microsoft live movie maker is an example of free software used for what purpose?']
[['freeware'], ['Video editing software']]

100%|██████████| 20/20 [03:14<00:00,  9.75s/it]

follow question : Microsoft live movie maker is an example of a freely licensed software, often called free what?
short answer : ['freeware']
{'score': 0.023067617788910866, 'start': 55, 'end': 63, 'answer': 'freeware'}
follow question : Microsoft live movie maker is an example of free software used for what purpose?
short answer : ['Video editing software']
{'score': 0.2880362868309021, 'start': 239, 'end': 255, 'answer': 'download and use'}
{'rougeLsum': 32.608695652173914, 'length': 56.0, 'str_em': 50.0, 'Disambig-F1': 50.0}

rougeLsum      33.400839
length         61.800000
str_em         48.333333
Disambig-F1    41.194444
dtype: float64

In [25]:
scores_df.to_csv('./results/answer_rag_2_results.csv', index=False)

In [26]:
import pandas as pd
import math
sf = pd.read_csv('results/answer_rag_2_results.csv')
sf=sf[sf['length']<1000][:100]
print(len(sf))
print(sf.mean())
r=sf.mean()['rougeLsum']
d=sf.mean()['Disambig-F1']
dr=math.sqrt(r*d)
print(dr)

16
rougeLsum      33.482502
length         97.562500
str_em         62.500000
Disambig-F1    42.708333
dtype: float64
37.815101059628596