In [3]:
import random, os
import numpy as np
import torch
os.environ["CUDA_VISIBLE_DEVICES"]="0,2"

from transformers import AutoTokenizer, BitsAndBytesConfig, AutoModelForCausalLM, AutoModel
from datasets import load_dataset
import pandas as pd
import re

device1 = 'cuda:0'
device2 = 'cuda:1'
data_dir = '/raid/deallab/SF_RAG_Data/ASQA'
# data_dir = '../data'

In [4]:
def set_seed(seed_value):
    # Set seed for reproducibility.
    random.seed(seed_value)
    os.environ['PYTHONHASHSEED']=str(seed_value)
    np.random.seed(seed_value)
    torch.manual_seed(seed_value)
    torch.cuda.manual_seed(seed_value)
    torch.backends.cudnn.deterministic=True    
    torch.backends.cudnn.benchmark=True
    torch.cuda.manual_seed_all(seed_value)

In [146]:
#load embeddings
embedd_test_path = f'{data_dir}/test/embedd_test.npy'
evidence_embeddings = np.load(embedd_test_path)
print(evidence_embeddings.shape)
evidence_embeddings = torch.from_numpy(evidence_embeddings).to(device1)

#load embeddings (evidence_eval)
embedd_test_path = f'{data_dir}/test/embedd_test_eval2.npy'
evidence_embeddings_eval = np.load(embedd_test_path)
print(evidence_embeddings_eval.shape)
evidence_embeddings_eval = torch.from_numpy(evidence_embeddings_eval).to(device1)

#load embeddings (evidence_title)
embedd_test_path = f'{data_dir}/test/embedd_test_eval_title.npy'
evidence_embeddings_title = np.load(embedd_test_path)
print(evidence_embeddings_title.shape)
evidence_embeddings_title = torch.from_numpy(evidence_embeddings_title).to(device1)

#load evidence
evidence_test_path = f'{data_dir}/test/evidence_test2.csv'
evidence_df = pd.read_csv(evidence_test_path)
print(len(evidence_df))

#load evidence
evidence_test_path = f'{data_dir}/test/evidence_test_eval.csv'
evidence_eval_df = pd.read_csv(evidence_test_path)
print(len(evidence_eval_df))

#load title evidence
evidence_test_path = f'{data_dir}/test/evidence_test_eval_title.csv'
evidence_eval_title_df = pd.read_csv(evidence_test_path)
print(len(evidence_eval_title_df))

#load qa data
qa_df=pd.read_csv(f'{data_dir}/test/qa_test.csv') #data=df[['question','long_answers']] # questions=data['question'] #references = [row.to_dict() for i, row in df.iterrows() if i < len(questions)]
qa_df.head()

(21586, 4096)
(21801, 4096)
(1897, 4096)
21586
21801
1897

,id,sample_id,question,follow_up_questions,long_answers,short_answers
0,aee000f3-d2b0-4de5-8206-a96e9c203207,-7013890438520559398,Who has the highest goals in world football?,"[""Who has the highest goals in men's world int...","[""Ali Dael has the highest goals in men's worl...","[['Daei', 'Ali Daei'], ['Bican', 'Josef Bican'..."
1,b80ea7a2-5084-422f-94d1-e67e7e29819b,7089015503030534342,Who is the original artist of sound of silence?,['Who is the original artist of sound of silen...,[' The original artist of the song sound of si...,"[['Simon & Garfunkel', 'Paul Simon and Art Gar..."
2,a9c1319b-ed69-4b1b-8486-05ad3d444e22,8793099883447006698,When was the first apple i phone made?,"['When was the first apple i phone released?',...",['The iPhone beta was created in 2004 to test ...,"[['June 29, 2007'], ['2004'], ['June 29, 2007...."
3,b07f0006-0628-49cf-b5b4-c0c7e88d3190,-881464876144297194,Who played the weasley brothers in harry potter?,['Who played Bill weasley in Harry Potter and...,['Rupert Grint played Ron Weasley in all the H...,"[['Richard Fish'], ['Chris Rankin'], ['James P..."
4,a9d31e99-6402-4a41-a4af-52de1aebeb16,1650309494326541834,How many state parks are there in virginia?,['How many state parks are there in virginia i...,['When the Virginia state park system was form...,"[['six'], ['38'], ['6'], ['38']]"

In [149]:
evidence_df

,text,title
0,Document: International Federation of Football...,International Federation of Football History &...
1,Document: International Federation of Football...,International Federation of Football History &...
2,Document: International Federation of Football...,International Federation of Football History &...
3,Document: International Federation of Football...,International Federation of Football History &...
4,Document: International Federation of Football...,International Federation of Football History &...
...,...,...
21581,Document: Sign of the Times (Harry Styles song...,Sign of the Times (Harry Styles song)
21582,Document: Sign of the Times (Harry Styles song...,Sign of the Times (Harry Styles song)
21583,Document: Sign of the Times (Harry Styles song...,Sign of the Times (Harry Styles song)
21584,Document: Sign of the Times (Harry Styles song...,Sign of the Times (Harry Styles song)
21585,Document: Sign of the Times (Harry Styles song...,Sign of the Times (Harry Styles song)

In [6]:
#load quantized model
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_storage=torch.bfloat16,
)

# load model with tokenizer
model = AutoModel.from_pretrained(
    'nvidia/NV-Embed-v2', 
    trust_remote_code=True,
    quantization_config = bnb_config,
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage =True,
)
model.eval()

Loading checkpoint shards: 100%|██████████| 4/4 [00:04<00:00,  1.24s/it]

NVEmbedModel(
  (latent_attention_model): LatentAttentionModel(
    (cross_attend_blocks): ModuleList(
      (0): PreNorm(
        (fn): Attention(
          (to_q): Linear4bit(in_features=4096, out_features=32768, bias=False)
          (to_kv): Linear4bit(in_features=4096, out_features=65536, bias=False)
          (to_out): Linear4bit(in_features=32768, out_features=4096, bias=False)
        )
        (norm): LayerNorm((4096,), eps=1e-05, elementwise_affine=True)
        (norm_context): LayerNorm((4096,), eps=1e-05, elementwise_affine=True)
      )
      (1): PreNorm(
        (fn): FeedForward(
          (net): Sequential(
            (0): Linear4bit(in_features=4096, out_features=32768, bias=True)
            (1): GEGLU()
            (2): Linear4bit(in_features=16384, out_features=4096, bias=True)
          )
        )
        (norm): LayerNorm((4096,), eps=1e-05, elementwise_affine=True)
      )
    )
  )
  (embedding_model): BidirectionalMistralModel(
    (embed_tokens): Embedding(32000, 4096)
    (layers): ModuleList(
      (0-31): 32 x MistralDecoderLayer(
        (self_attn): MistralSdpaAttention(
          (q_proj): Linear4bit(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear4bit(in_features=4096, out_features=1024, bias=False)
          (v_proj): Linear4bit(in_features=4096, out_features=1024, bias=False)
          (o_proj): Linear4bit(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): MistralRotaryEmbedding()
        )
        (mlp): MistralMLP(
          (gate_proj): Linear4bit(in_features=4096, out_features=14336, bias=False)
          (up_proj): Linear4bit(in_features=4096, out_features=14336, bias=False)
          (down_proj): Linear4bit(in_features=14336, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): MistralRMSNorm()
        (post_attention_layernorm): MistralRMSNorm()
      )
    )
    (norm): MistralRMSNorm()
  )
)

In [7]:
#load tokenizer
tokenizer_gen = AutoTokenizer.from_pretrained("meta-llama/Meta-Llama-3.1-8B-Instruct")
# cache_dir= '/raid/deallab/.cache')
tokenizer_gen.pad_token = tokenizer_gen.eos_token

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    # bnb_4bit_quant_type="nf4",
    # bnb_4bit_compute_dtype=torch.bfloat16,
    # bnb_4bit_use_double_quant=True,
    # bnb_4bit_quant_storage=torch.bfloat16,
)

model_gen = AutoModelForCausalLM.from_pretrained(
    "meta-llama/Meta-Llama-3.1-8B-Instruct",
    quantization_config=bnb_config,
    torch_dtype=torch.bfloat16,
    device_map= 'auto',
    # cache_dir= '/raid/deallab/.cache'
)
model_gen.eval()

Loading checkpoint shards: 100%|██████████| 4/4 [00:03<00:00,  1.05it/s]

LlamaForCausalLM(
  (model): LlamaModel(
    (embed_tokens): Embedding(128256, 4096)
    (layers): ModuleList(
      (0-31): 32 x LlamaDecoderLayer(
        (self_attn): LlamaSdpaAttention(
          (q_proj): Linear4bit(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear4bit(in_features=4096, out_features=1024, bias=False)
          (v_proj): Linear4bit(in_features=4096, out_features=1024, bias=False)
          (o_proj): Linear4bit(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear4bit(in_features=4096, out_features=14336, bias=False)
          (up_proj): Linear4bit(in_features=4096, out_features=14336, bias=False)
          (down_proj): Linear4bit(in_features=14336, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm()
        (post_attention_layernorm): LlamaRMSNorm()
      )
    )
    (norm): LlamaRMSNorm()
    (rotary_emb): LlamaRotaryEmbedding()
  )
  (lm_head): Linear(in_features=4096, out_features=128256, bias=False)
)

In [8]:
# from langchain_text_splitters import TokenTextSplitter

# text_splitter = TokenTextSplitter(
#     chunk_size=500,  # 청크 크기를 10으로 설정합니다.
#     chunk_overlap=50,  # 청크 간 중복을 0으로 설정합니다.
# )
# # combined_text = " ".join(evidence_text_list)
# # texts = text_splitter.split_text(combined_text)
# split_texts = [text_splitter.split_text(text)[0] for text in evidence_text_list]
# print(split_texts[0])

In [9]:
# from langchain.retrievers import BM25Retriever, EnsembleRetriever
# from langchain.vectorstores import FAISS

# # bm25 retriever와 faiss retriever를 초기화합니다.
# bm25_retriever = BM25Retriever.from_texts(
#     evidence_text_list,
# )
# bm25_retriever.k = 10  # BM25Retriever의 검색 결과 개수를 1로 설정합니다.

# embedding = model
# faiss_vectorstore = FAISS.from_texts(
#     evidence_text,
#     embedding,
# )
# faiss_retriever = faiss_vectorstore.as_retriever(search_kwargs={"k": 2})

# # 앙상블 retriever를 초기화합니다.
# ensemble_retriever = EnsembleRetriever(
#     retrievers=[bm25_retriever, faiss_retriever],
#     weights=[0.7, 0.3],
# )

In [10]:
# from langchain_community.document_transformers import LongContextReorder

# def bm25_retrieve(query):
#     bm25_result = bm25_retriever.invoke(query)
#     bm25_docs=list()

#     print("[BM25 Retriever]")
#     for doc in bm25_result:
#         # print(f"Content: {doc.page_content}")
#         # print()
#         bm25_docs.append(doc.page_content)
#     reordering = LongContextReorder()
#     bm25_docs = reordering.transform_documents(bm25_docs)
#     return bm25_docs

In [11]:
# res=bm25_retrieve("Who has the highest goals in world football?")
# res

In [12]:
evidence_eval_path = f'{data_dir}/test/evidence_test_eval.csv'
eval_df = pd.read_csv(evidence_eval_path)
eval_df.head(20)

,sample_id,title,text
0,-7013890438520559398,International Federation of Football History &...,Document: International Federation of Football...
1,-7013890438520559398,International Federation of Football History &...,Document: International Federation of Football...
2,-7013890438520559398,International Federation of Football History &...,Document: International Federation of Football...
3,-7013890438520559398,International Federation of Football History &...,Document: International Federation of Football...
4,-7013890438520559398,International Federation of Football History &...,Document: International Federation of Football...
5,-7013890438520559398,International Federation of Football History &...,Document: International Federation of Football...
6,-7013890438520559398,International Federation of Football History &...,Document: International Federation of Football...
7,-7013890438520559398,International Federation of Football History &...,Document: International Federation of Football...
8,-7013890438520559398,International Federation of Football History &...,Document: International Federation of Football...
9,-7013890438520559398,International Federation of Football History &...,Document: International Federation of Football...
10,-7013890438520559398,List of FIFA World Cup records and statistics,Document: List of FIFA World Cup records and s...
11,-7013890438520559398,List of FIFA World Cup records and statistics,Document: List of FIFA World Cup records and s...
12,-7013890438520559398,List of FIFA World Cup records and statistics,Document: List of FIFA World Cup records and s...
13,-7013890438520559398,List of FIFA World Cup records and statistics,Document: List of FIFA World Cup records and s...
14,-7013890438520559398,List of FIFA World Cup records and statistics,Document: List of FIFA World Cup records and s...
15,-7013890438520559398,List of FIFA World Cup records and statistics,Document: List of FIFA World Cup records and s...
16,-7013890438520559398,List of FIFA World Cup records and statistics,Document: List of FIFA World Cup records and s...
17,-7013890438520559398,List of FIFA World Cup records and statistics,Document: List of FIFA World Cup records and s...
18,-7013890438520559398,List of FIFA World Cup records and statistics,Document: List of FIFA World Cup records and s...
19,-7013890438520559398,List of FIFA World Cup records and statistics,Document: List of FIFA World Cup records and s...

In [13]:
def match_sample_id(query_id, doc_id):
    query_sample_id=qa_df.loc[query_id,'sample_id']
    doc_sample_id=eval_df.loc[doc_id,'sample_id']
    if query_sample_id==doc_sample_id:
        return 1
    else:
        return 0

In [14]:
def match_sample_id2(query_id, title):
    query_sample_id=qa_df.loc[query_id,'sample_id']
    doc_sample_id=evidence_eval_title_df.loc[evidence_eval_title_df['title']==title,'sample_id'].item()
    if query_sample_id==doc_sample_id:
        return 1
    else:
        return 0

In [15]:
# retrive docs from the document embeddings
def retrieve_documents(query,num=10):
    max_length = 1024
    
    #query prefix
    task_name_to_instruct = {"example": "Given a question, retrieve passages that answer the question",}
    query_prefix = "Instruct: "+task_name_to_instruct["example"]+"\nQuery: "
    
    query_embedding = model.encode([query],instruction=query_prefix, max_length=max_length).to(device1)
    similarities = torch.nn.functional.cosine_similarity(query_embedding, evidence_embeddings)

    top_results = similarities.argsort(descending=True)[:num].cpu().detach().numpy()
    res=[evidence_df.loc[idx, 'text'] for idx in top_results if idx < len(evidence_df)]
    idx=[idx for idx in top_results if idx < len(evidence_df)]
    return res, idx

In [16]:
# retrive docs from the document embeddings
def retrieve_documents_eval(query,num=10):
    max_length = 1024
    
    #query prefix
    task_name_to_instruct = {"example": "Given a question, retrieve passages that answer the question",}
    query_prefix = "Instruct: "+task_name_to_instruct["example"]+"\nQuery: "
    
    query_embedding = model.encode([query],instruction=query_prefix, max_length=max_length).to(device1)
    similarities = torch.nn.functional.cosine_similarity(query_embedding, evidence_embeddings_eval)

    top_results = similarities.argsort(descending=True)[:num].cpu().detach().numpy()
    res=[evidence_eval_df.loc[idx, 'text'] for idx in top_results if idx < len(evidence_eval_df)]
    idx=[idx for idx in top_results if idx < len(evidence_eval_df)]
    return res, idx

In [17]:
# retrive docs from the document embeddings
def retrieve_documents2(query, embed, evidence, num=10):
    max_length = 1024
    
    #query prefix
    task_name_to_instruct = {"example": "Given a question, retrieve passages that answer the question",}
    query_prefix = "Instruct: "+task_name_to_instruct["example"]+"\nQuery: "
    
    query_embedding = model.encode([query],instruction=query_prefix, max_length=max_length).to(device1)
    similarities = torch.nn.functional.cosine_similarity(query_embedding, embed)

    top_results = similarities.argsort(descending=True)[:num].cpu().detach().numpy()
    res=[evidence.loc[idx, 'text'] for idx in top_results if idx < len(evidence)]
    titles=[evidence.loc[idx, 'title'] for idx in top_results if idx < len(evidence)]
    # idx=[idx for idx in top_results if idx < len(evidence)]
    return res, titles

In [18]:
# retrive docs from the document embeddings
def retrieve_documents3(query, embed, evidence, num=10):
    max_length = 1024
    
    #query prefix
    task_name_to_instruct = {"example": "Given a question, retrieve passages that answer the question",}
    query_prefix = "Instruct: "+task_name_to_instruct["example"]+"\nQuery: "
    
    query_embedding = model.encode([query],instruction=query_prefix, max_length=max_length).to(device1)
    similarities = torch.nn.functional.cosine_similarity(query_embedding, embed)

    top_results = similarities.argsort(descending=True)[:num].cpu().detach().numpy()
    res=[evidence.loc[idx, 'text'] for idx in top_results if idx < len(evidence)]
    # titles=[evidence.loc[idx, 'title'] for idx in top_results if idx < len(evidence)]
    idx=[idx for idx in top_results if idx < len(evidence)]
    return res, idx

In [19]:
# retrive docs from the document embeddings
def retrieve_titles(query,num=10):
    max_length = 1024
    
    #query prefix
    task_name_to_instruct = {"example": "Given a question, retrieve passages that answer the question",}
    query_prefix = "Instruct: "+task_name_to_instruct["example"]+"\nQuery: "
    
    query_embedding = model.encode([query],instruction=query_prefix, max_length=max_length).to(device1)
    similarities = torch.nn.functional.cosine_similarity(query_embedding, evidence_embeddings_title)

    top_results = similarities.argsort(descending=True)[:num].cpu().detach().numpy()
    res=[evidence_eval_title_df.loc[idx, 'title'] for idx in top_results if idx < len(evidence_eval_title_df)]
    idx=[idx for idx in top_results if idx < len(evidence_eval_title_df)]
    return res, idx

In [20]:
def find_titles(query):
    titles,title_ids=retrieve_titles(query, 10)
    return titles

In [21]:
def find_docs(titles):
    docs=[]
    for title in titles:
        # print(title)
        # print(evidence_eval_df.loc[evidence_eval_df['title']==title,'text'].to_list())
        docs.extend(evidence_eval_df.loc[evidence_eval_df['title']==title,'text'])
        # print()
    return docs

In [22]:
def retrieve_inside(query, titles, num=10):
    docs=[]
    text_docs=pd.DataFrame(columns=['text','title'])
    final_docs=[]
    for title in titles:
        text_docs=pd.concat([text_docs, evidence_eval_df.loc[evidence_eval_df['title']==title,['text','title']]],ignore_index=True)
        docs.extend(evidence_embeddings_eval[evidence_eval_df['title']==title])
        # print(title_retrieved_docs)
        # print()
    docs_tensor = torch.stack(docs)
    title_retrieved_docs,t=retrieve_documents2(query, docs_tensor, text_docs, num)
    final_docs.extend(title_retrieved_docs)
    return final_docs,t

In [23]:
# query="Who has the highet goals in world football?"
# titles,title_ids=retrieve_titles(query, 11)
# for t in titles:
#     print(t)
# title_docs=find_docs(titles)
# final_docs,d=retrieve_inside(query, titles, 10)
# d

In [24]:
def total_answer(query, docs):
    prompt = """
    Context information is below.
    ---------------------
    {0}
    ---------------------
    Given the context information and not prior knowledge, answer the query.
    1. The query is an ambiguous question.
    2. Therefore, you must include the contents according to the various interpretations of the query in one answer by utilizing the given context.
    3. Each content according to the various interpretations of the query must be explained in one or two sentences.
    4. The total answer must be 5 sentences or less.
    Do not comment your answer and strictly follow this instructions.
    Query: {1}
    Answer:
    """.format('\n'.join(docs), query)
    input_ids = tokenizer_gen.apply_chat_template([{"role":'user', "content":prompt}], return_tensors='pt').to(device1)

    attention_mask = (input_ids != tokenizer_gen.pad_token_id).long().to(device1)

    out = model_gen.generate(input_ids, attention_mask=attention_mask, pad_token_id=tokenizer_gen.pad_token_id, max_new_tokens = 512)
    res = tokenizer_gen.decode(out[0]).split('<|end_header_id|>')[-1] 
    return re.sub('\n|<\|eot_id\|>', '', res)

In [163]:
def answer(query, context):
    prompt = """
    Context information is below.
    ---------------------
    {0}
    ---------------------
    Given the context information and not prior knowledge, answer the query.
    Query: {1}
    Answer:
    """.format('\n'.join(context), query)
    input_ids = tokenizer_gen.apply_chat_template([{"role":'user', "content":prompt}], return_tensors='pt').to(device1)

    attention_mask = (input_ids != tokenizer_gen.pad_token_id).long().to(device1)

    out = model_gen.generate(input_ids, attention_mask=attention_mask, pad_token_id=tokenizer_gen.pad_token_id, max_new_tokens = 512)
    res = tokenizer_gen.decode(out[0]).split('<|end_header_id|>')[-1] 
    return re.sub('\n|<\|eot_id\|>', '', res)

In [26]:
def retrieve_inside(query, titles, num=10):
    docs=[]
    text_docs=pd.DataFrame(columns=['text','title'])
    final_docs=[]
    for title in titles:
        text_docs=pd.concat([text_docs, evidence_eval_df.loc[evidence_eval_df['title']==title,['text','title']]],ignore_index=True)
        docs.extend(evidence_embeddings_eval[evidence_eval_df['title']==title])
        # print(title_retrieved_docs)
        # print()
    docs_tensor = torch.stack(docs)
    title_retrieved_docs,t=retrieve_documents2(query, docs_tensor, text_docs, num)
    final_docs.extend(title_retrieved_docs)
    return final_docs,t

In [27]:
# import torch
# from transformers import AutoModelForSequenceClassification, AutoTokenizer

# tokenizer_rerank = AutoTokenizer.from_pretrained('BAAI/bge-reranker-v2-m3')
# model_rerank = AutoModelForSequenceClassification.from_pretrained('BAAI/bge-reranker-v2-m3')
# model_rerank.eval()

In [28]:
# pairs = [['what is panda?', 'hi'], ['what is panda?', 'The giant panda (Ailuropoda melanoleuca), sometimes called a panda bear or simply panda, is a bear species endemic to China.']]
# with torch.no_grad():
#     inputs = tokenizer_rerank(pairs, padding=True, truncation=True, return_tensors='pt', max_length=512)
#     scores = model(**inputs, return_dict=True).logits.view(-1, ).float()

# print(scores)

In [29]:
# from sentence_transformers import CrossEncoder

# v2m3_model = CrossEncoder("BAAI/bge-reranker-v2-m3", trust_remote_code=True)

# # Sample query and contexts
# query, contexts = ('Were Scott Derrickson and Ed Wood of the same nationality?',
#  [{'id': 0, 'text': 'Scott Derrickson Scott Derrickson (born July 16, 1966) is an American director, screenwriter and producer. He lives in Los Angeles, California. He is best known for directing horror films such as "Sinister", "The Exorcism of Emily Rose", and "Deliver Us From Evil", as well as the 2016 Marvel Cinematic Universe installment, "Doctor Strange."'},
#  {'id': 1, 'text': 'Ed Wood Edward Davis Wood Jr. (October 10, 1924 - December 10, 1978) was an American filmmaker, actor, writer, producer, and director.'}
#  # 100 context in total ...
# ])
# context_texts = [t['text'] for t in contexts]

# def rerank_documents(model, query, contexts):
#  rets = model.rank(query, contexts, batch_size=64)
#  return rets


# rets=rerank_documents(v2m3_model, query, context_texts)

In [150]:
def cal_sample_title(query_id,documents):
    titles_of_documents = evidence_df[evidence_df['text'].isin(documents)]['title'].values
    query_sample_id=qa_df.loc[query_id,'sample_id']
    titles_of_query = set(eval_df[eval_df['sample_id']==query_sample_id]['title'].values)
    
    print(titles_of_documents)
    print(titles_of_query)
    return len(set(titles_of_documents) & titles_of_query)/len(titles_of_query)

# Baseline

In [151]:
from tqdm import tqdm
from evaluation import evaluate

set_seed(24)

stop_iteration = 20
retrival_list=[]
scores_list=[]
for idx, row in tqdm(qa_df.iterrows(), total=min([stop_iteration, len(qa_df)])):
    if idx == stop_iteration: break
    query = row['question']
    retrieved_docs, doc_ids = retrieve_documents(query,10)
    tmp=0
    for doc_id in doc_ids:    
        tmp+=match_sample_id(idx, doc_id)
    res=tmp/len(retrieved_docs)
    
    print(" Retrival Match Rate:", res)
    dic=dict()
    dic['first_doc_retrival']=res
    
    title_retival_rate=cal_sample_title(idx,retrieved_docs)
    print("Title Match Rate:", title_retival_rate)
    dic['first_title_retrival']=title_retival_rate
    
    ans=total_answer(query,retrieved_docs)
    print('Final ans:', ans)
    scores=evaluate([ans], [row.to_dict()])
    scores_list.append(scores)
    scores_df=pd.DataFrame(scores_list)
    print(scores)
    retrival_list.append(dic)
    retrival_df=pd.DataFrame(retrival_list)
    print(dic)
        
scores_df=pd.DataFrame(scores_list)
print(scores_df.mean())

retrival_df=pd.DataFrame(retrival_list)
print(retrival_df.mean())

  0%|          | 0/20 [00:00<?, ?it/s]/home/dataconv/.cache/huggingface/modules/transformers_modules/nvidia/NV-Embed-v2/5130cf1daf847c1bacee854a6ef1ca939e747fb2/modeling_nvembed.py:349: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'input_ids': torch.tensor(batch_dict.get('input_ids').to(batch_dict.get('input_ids')).long()),
/home/dataconv/anaconda3/envs/sf_rag_djk/lib/python3.10/contextlib.py:103: FutureWarning: `torch.backends.cuda.sdp_kernel()` is deprecated. In the future, this context manager will be removed. Please see `torch.nn.attention.sdpa_kernel()` for the new context manager, with updated signature.
  self.gen = func(*args, **kwds)

 Retrival Match Rate: 0.5
['List of FIFA World Cup records and statistics'
 'List of footballers with more than 50 international goals'
 'List of footballers with 500 or more goals'
 'List of footballers with 500 or more goals'
 'List of footballers with 500 or more goals'
 "List of top international men's association football goal scorers by ..."
 "List of men's footballers with 50 or more international goals"
 'Football records and statistics in Spain'
 'Germany at the FIFA World Cup' 'FIFA World Cup top goalscorers']
{'International Federation of Football History & Statistics', 'List of footballers with more than 50 international goals', 'List of footballers with 500 or more goals', 'List of FIFA World Cup records and statistics', "List of women's footballers with 100 or more international goals ..."}
Title Match Rate: 0.6
Final ans: Ali Daei holds the record for the highest number of international goals with 109 goals for Iran, surpassing Ferenc Puskás' record of 84 goals. Cristiano Ronaldo has scored 1030 goals in his career, the highest among active players, with a total of 738 goals in his international career. Miroslav Klose holds the record for most World Cup goals with 16 goals, while Gerd Müller used to be the holder of that record from 1974 until it was broken by Ronaldo in 2006. Pelé scored 77 international goals, the highest among players from outside Europe, and Jürgen Klinsmann scored 11 goals in the World Cup, the highest among players from Germany. The top goalscorers in the World Cup history are Ali Daei, Cristiano Ronaldo, Ferenc Puskás, Kunishige Kamamoto, Godfrey Chitalu, Hussein Saeed, and Zainal Abidin, among others.
Ali Daei holds the record for the highest number of international goals with 109 goals for Iran, surpassing Ferenc Puskás' record of 84 goals. Cristiano Ronaldo has scored 1030 goals in his career, the highest among active players, with a total of 738 goals in his international career. Miroslav Klose holds the record for most World Cup goals with 16 goals, while Gerd Müller used to be the holder of that record from 1974 until it was broken by Ronaldo in 2006. Pelé scored 77 international goals, the highest among players from outside Europe, and Jürgen Klinsmann scored 11 goals in the World Cup, the highest among players from Germany. The top goalscorers in the World Cup history are Ali Daei, Cristiano Ronaldo, Ferenc Puskás, Kunishige Kamamoto, Godfrey Chitalu, Hussein Saeed, and Zainal Abidin, among others.
Who has the highest goals in world football?
["Who has the highest goals in men's world international football?", "Who has the highest goals all-time in men's football?", "Who has the highest goals in women's world international football?"]
[['Daei', 'Ali Daei'], ['Bican', 'Josef Bican'], ['Sinclair', 'Christine Sinclair']]

  5%|▌         | 1/20 [00:19<06:05, 19.21s/it]

follow question : Who has the highest goals in men's world international football?
short answer : ['Daei', 'Ali Daei']
{'score': 0.7431520223617554, 'start': 143, 'end': 160, 'answer': 'Cristiano Ronaldo'}
follow question : Who has the highest goals all-time in men's football?
short answer : ['Bican', 'Josef Bican']
{'score': 0.39714962244033813, 'start': 143, 'end': 160, 'answer': 'Cristiano Ronaldo'}
follow question : Who has the highest goals in women's world international football?
short answer : ['Sinclair', 'Christine Sinclair']
{'score': 8.483205249376624e-08, 'start': 0, 'end': 8, 'answer': 'Ali Daei'}
{'rougeLsum': 38.68312757201646, 'length': 136.0, 'str_em': 33.33333333333333, 'Disambig-F1': 0.0}
{'first_doc_retrival': 0.5, 'first_title_retrival': 0.6}
 Retrival Match Rate: 1.0
['The Sound of Silence' 'The Sound of Silence' 'The Sound of Silence'
 'The Sound of Silence' 'The Sound of Silence' 'The Sound of Silence'
 'The Sound of Silence' 'Sounds of Silence' 'Sounds of Silence'
 'Sound of Silence (Dami Im song)']
{'The Sound of Silence', 'Sound of Silence (Dami Im song)', 'Sounds of Silence'}
Title Match Rate: 1.0
Final ans: The original artist of "Sound of Silence" is Simon & Garfunkel, an American music duo consisting of Paul Simon and Art Garfunkel. The song was written by Paul Simon, with the duo's original recording being in D♯ minor, featuring acoustic guitars and vocals. The duo's partnership had previously dissolved when they attended college, but they regrouped in 1963 and began performing Simon's original compositions locally. The song was originally titled "The Sounds of Silence" on the album Wednesday Morning, 3 A.M. and was later shortened for later compilations.
The original artist of "Sound of Silence" is Simon & Garfunkel, an American music duo consisting of Paul Simon and Art Garfunkel. The song was written by Paul Simon, with the duo's original recording being in D♯ minor, featuring acoustic guitars and vocals. The duo's partnership had previously dissolved when they attended college, but they regrouped in 1963 and began performing Simon's original compositions locally. The song was originally titled "The Sounds of Silence" on the album Wednesday Morning, 3 A.M. and was later shortened for later compilations.
Who is the original artist of sound of silence?
['Who is the original artist of sound of silence, the song, released in 1964?', 'Who is the original artist of sound of silence, the album?', 'Who is the original artist of sound of silence, the song, released in 2016?']
[['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon'], ['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon'], ['Dami Im']]

 10%|█         | 2/20 [00:31<04:27, 14.89s/it]

follow question : Who is the original artist of sound of silence, the song, released in 1964?
short answer : ['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon']
{'score': 0.13219714164733887, 'start': 45, 'end': 62, 'answer': 'Simon & Garfunkel'}
follow question : Who is the original artist of sound of silence, the album?
short answer : ['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon']
{'score': 0.901651918888092, 'start': 45, 'end': 62, 'answer': 'Simon & Garfunkel'}
follow question : Who is the original artist of sound of silence, the song, released in 2016?
short answer : ['Dami Im']
{'score': 0.3635461628437042, 'start': 45, 'end': 62, 'answer': 'Simon & Garfunkel'}
{'rougeLsum': 40.54054054054054, 'length': 88.0, 'str_em': 66.66666666666666, 'Disambig-F1': 66.66666666666666}
{'first_doc_retrival': 1.0, 'first_title_retrival': 1.0}
 Retrival Match Rate: 0.9
['iPhone (1st generation)' 'iPhone (1st generation)'
 'iPhone (1st generation)' 'History of iPhone' 'History of iPhone'
 'iPhone' 'iPhone' 'iPhone' 'iPhone' 'iPhone']
{'History of iPhone', 'iPhone', 'iPhone (1st generation)'}
Title Match Rate: 1.0
Final ans: The first iPhone was announced by Steve Jobs on January 9, 2007, at the Macworld Conference & Expo held in Moscone West in San Francisco, California. It was released in the United States on June 29, 2007, and later made available in other countries. The development of the iPhone began in 2004, when Apple started to gather a team of 1,000 employees to work on the highly confidential "Project Purple." The first iPhone was released after a secretive collaboration with Cingular Wireless (now AT&T Mobility) at an estimated development cost of US$150 million over thirty months. The iPhone was initially available in two models, a 4 GB model priced at US$499 and an 8 GB model at US$599.
The first iPhone was announced by Steve Jobs on January 9, 2007, at the Macworld Conference & Expo held in Moscone West in San Francisco, California. It was released in the United States on June 29, 2007, and later made available in other countries. The development of the iPhone began in 2004, when Apple started to gather a team of 1,000 employees to work on the highly confidential "Project Purple." The first iPhone was released after a secretive collaboration with Cingular Wireless (now AT&T Mobility) at an estimated development cost of US$150 million over thirty months. The iPhone was initially available in two models, a 4 GB model priced at US$499 and an 8 GB model at US$599.
When was the first apple i phone made?
['When was the first apple i phone released?', 'When was the first apple i phone for beta testing made?', 'When was the first apple i phone 1 made?', 'When was the first apple i phone beta made?']
[['June 29, 2007'], ['2004'], ['June 29, 2007.'], ['2004.']]

 15%|█▌        | 3/20 [00:46<04:18, 15.20s/it]

follow question : When was the first apple i phone released?
short answer : ['June 29, 2007']
{'score': 0.8568127751350403, 'start': 190, 'end': 203, 'answer': 'June 29, 2007'}
follow question : When was the first apple i phone for beta testing made?
short answer : ['2004']
{'score': 0.00016745703760534525, 'start': 289, 'end': 293, 'answer': '2004'}
follow question : When was the first apple i phone 1 made?
short answer : ['June 29, 2007.']
{'score': 0.3698033392429352, 'start': 48, 'end': 63, 'answer': 'January 9, 2007'}
follow question : When was the first apple i phone beta made?
short answer : ['2004.']
{'score': 1.64343703090708e-06, 'start': 289, 'end': 293, 'answer': '2004'}
{'rougeLsum': 35.10638297872341, 'length': 118.0, 'str_em': 100.0, 'Disambig-F1': 83.33333333333334}
{'first_doc_retrival': 0.9, 'first_title_retrival': 1.0}
 Retrival Match Rate: 0.9
['List of Harry Potter characters'
 'List of supporting Harry Potter characters'
 'List of Harry Potter cast members' 'List of Harry Potter cast members'
 'List of Harry Potter cast members' 'List of Harry Potter cast members'
 'Order of the Phoenix (fictional organisation)'
 'Order of the Phoenix (fictional organisation)'
 'Order of the Phoenix (fictional organisation)'
 'Harry Potter and the Prisoner of Azkaban (film)']
{'Order of the Phoenix (fictional organisation)', 'List of Harry Potter cast members', 'List of Harry Potter characters', 'List of supporting Harry Potter characters'}
Title Match Rate: 1.0
Final ans: The Weasley brothers, including Bill, Charlie, Fred, George, and Percy, were played by actors James and Oliver Phelps, who are real-life twins and were cast to play the identical twins Fred and George Weasley. The twins' performances were so convincing that they were often referred to as the "Weasley twins" in the films. In addition to the twins, the Weasley brothers were also played by other actors, including David Bradley as Argus Filch, who appeared as a minor character, and other actors who played various Weasley relatives and friends. The Weasley family was an important part of the Harry Potter series, and the actors who played them brought the family to life on screen. Overall, the Weasley brothers were played by a talented group of actors who helped to bring the beloved family to life.
The Weasley brothers, including Bill, Charlie, Fred, George, and Percy, were played by actors James and Oliver Phelps, who are real-life twins and were cast to play the identical twins Fred and George Weasley. The twins' performances were so convincing that they were often referred to as the "Weasley twins" in the films. In addition to the twins, the Weasley brothers were also played by other actors, including David Bradley as Argus Filch, who appeared as a minor character, and other actors who played various Weasley relatives and friends. The Weasley family was an important part of the Harry Potter series, and the actors who played them brought the family to life on screen. Overall, the Weasley brothers were played by a talented group of actors who helped to bring the beloved family to life.
Who played the weasley brothers in harry potter?
['Who played  Bill weasley in Harry Potter and the Prisoner of Azkaban?', 'Who played percy weasley in harry potter?', 'Who played fred weasley in harry potter?', 'Who played ron weasley in harry potter?', 'Who played george weasley in harry potter?', 'Who played  Bill weasley in harry potter (2001-2011)?']
[['Richard Fish'], ['Chris Rankin'], ['James Phelps'], ['Rupert Grint'], ['Oliver Phelps'], ['Domhnall Gleeson']]

 20%|██        | 4/20 [01:02<04:04, 15.31s/it]

follow question : Who played  Bill weasley in Harry Potter and the Prisoner of Azkaban?
short answer : ['Richard Fish']
{'score': 0.3422260582447052, 'start': 94, 'end': 117, 'answer': 'James and Oliver Phelps'}
follow question : Who played percy weasley in harry potter?
short answer : ['Chris Rankin']
{'score': 0.7011380195617676, 'start': 94, 'end': 117, 'answer': 'James and Oliver Phelps'}
follow question : Who played fred weasley in harry potter?
short answer : ['James Phelps']
{'score': 0.7462304830551147, 'start': 94, 'end': 117, 'answer': 'James and Oliver Phelps'}
follow question : Who played ron weasley in harry potter?
short answer : ['Rupert Grint']
{'score': 0.3138059079647064, 'start': 94, 'end': 117, 'answer': 'James and Oliver Phelps'}
follow question : Who played george weasley in harry potter?
short answer : ['Oliver Phelps']
{'score': 0.8155282735824585, 'start': 94, 'end': 117, 'answer': 'James and Oliver Phelps'}
follow question : Who played  Bill weasley in harry potter (2001-2011)?
short answer : ['Domhnall Gleeson']
{'score': 0.38119590282440186, 'start': 94, 'end': 117, 'answer': 'James and Oliver Phelps'}
{'rougeLsum': 37.10407239819005, 'length': 135.0, 'str_em': 16.666666666666664, 'Disambig-F1': 22.22222222222222}
{'first_doc_retrival': 0.9, 'first_title_retrival': 1.0}
 Retrival Match Rate: 0.4
['List of Virginia state parks' 'List of Virginia state parks'
 'List of Virginia state parks' 'List of Virginia state parks'
 'List of Virginia state parks' 'New York (state)' 'Richmond, Virginia'
 'Richmond, Virginia' 'Virginia State Capitol' 'New York City']
{'List of Virginia state parks'}
Title Match Rate: 1.0
Final ans: There are 38 state parks in Virginia, according to the information provided. The six original state parks were Seashore State Park, Westmoreland State Park, Staunton River State Park, Douthat State Park, Fairy Stone State Park, and Hungry Mother State Park, which were opened on June 15, 1936. The list of state parks in Virginia includes 38 parks, each with its own unique features, size, and location. The total number of state parks in Virginia is 38, with various sizes ranging from 7 acres to 6,900 acres. The state parks in Virginia offer a range of outdoor recreational activities and opportunities for nature exploration and conservation.
There are 38 state parks in Virginia, according to the information provided. The six original state parks were Seashore State Park, Westmoreland State Park, Staunton River State Park, Douthat State Park, Fairy Stone State Park, and Hungry Mother State Park, which were opened on June 15, 1936. The list of state parks in Virginia includes 38 parks, each with its own unique features, size, and location. The total number of state parks in Virginia is 38, with various sizes ranging from 7 acres to 6,900 acres. The state parks in Virginia offer a range of outdoor recreational activities and opportunities for nature exploration and conservation.
How many state parks are there in virginia?
['How many state parks are there in virginia in 1936?', 'How many state parks are there in virginia in 2016?', 'How many state parks were there when the state park system formed in Virginia?', 'How many state parks were there in Virginia as of 2016?']
[['six'], ['38'], ['6'], ['38']]

 25%|██▌       | 5/20 [01:14<03:35, 14.39s/it]

follow question : How many state parks are there in virginia in 1936?
short answer : ['six']
{'score': 9.823852451518178e-06, 'start': 10, 'end': 12, 'answer': '38'}
follow question : How many state parks are there in virginia in 2016?
short answer : ['38']
{'score': 1.2754749150190037e-06, 'start': 10, 'end': 12, 'answer': '38'}
follow question : How many state parks were there when the state park system formed in Virginia?
short answer : ['6']
{'score': 0.4856792986392975, 'start': 81, 'end': 84, 'answer': 'six'}
follow question : How many state parks were there in Virginia as of 2016?
short answer : ['38']
{'score': 0.001818185904994607, 'start': 10, 'end': 12, 'answer': '38'}
{'rougeLsum': 49.162011173184354, 'length': 105.0, 'str_em': 100.0, 'Disambig-F1': 50.0}
{'first_doc_retrival': 0.4, 'first_title_retrival': 1.0}
 Retrival Match Rate: 0.5
['2018 UEFA Champions League Final' '2018 UEFA Champions League Final'
 '2018 UEFA Champions League Final' '2018 UEFA Champions League Final'
 '2018 UEFA Champions League Final' '2018 UEFA Champions League Final'
 'List of Super Bowl halftime shows' '2018 FIFA World Cup'
 'UEFA Champions League' '2017 AFL Grand Final']
{'2018 UEFA Champions League Final'}
Title Match Rate: 1.0
Final ans: The opening ceremony of the 2018 UEFA Champions League Final featured English singer Dua Lipa, who performed alongside Jamaican rapper Sean Paul. The UEFA Champions League Anthem was performed by Slovenian-Croatian cello duo 2Cellos. The annual UEFA Champions Festival was held between 24–27 May 2018 at the Kiev city centre, featuring various performances. The match ball for the 2018 FIFA World Cup, the "Telstar 18", was unveiled on 9 November 2017, and the official mascot for the tournament was Zabivaka, an anthropomorphic wolf. The 2018 UEFA Champions League Final itself featured Real Madrid winning 3-1 against Liverpool, with Gareth Bale being named man of the match for his two goals.
The opening ceremony of the 2018 UEFA Champions League Final featured English singer Dua Lipa, who performed alongside Jamaican rapper Sean Paul. The UEFA Champions League Anthem was performed by Slovenian-Croatian cello duo 2Cellos. The annual UEFA Champions Festival was held between 24–27 May 2018 at the Kiev city centre, featuring various performances. The match ball for the 2018 FIFA World Cup, the "Telstar 18", was unveiled on 9 November 2017, and the official mascot for the tournament was Zabivaka, an anthropomorphic wolf. The 2018 UEFA Champions League Final itself featured Real Madrid winning 3-1 against Liverpool, with Gareth Bale being named man of the match for his two goals.
Who performed at the champions league final 2018?
['Who are the teams that performed in competition at the champions league final 2018?', 'Who performed best at the champions league final 2018, winning man of the match?', 'Who performed at the opening ceremony of the champions league final 2018?', 'Who performed the anthem at the champions league final 2018?']
[['Real Madrid and Liverpool', 'Liverpool', 'Real Madrid'], ['Gareth Bale', 'Bale'], ['Dua Lipa', 'Sean Paul', 'Dua Lipa and Sean Paul'], ['2Cellos', 'Luka Šulić and Stjepan Hauser', 'Luka Šulić', '2CΞLLOS', 'Stjepan Hauser']]

 30%|███       | 6/20 [01:29<03:22, 14.49s/it]

follow question : Who are the teams that performed in competition at the champions league final 2018?
short answer : ['Real Madrid and Liverpool', 'Liverpool', 'Real Madrid']
{'score': 0.34995007514953613, 'start': 588, 'end': 629, 'answer': 'Real Madrid winning 3-1 against Liverpool'}
follow question : Who performed best at the champions league final 2018, winning man of the match?
short answer : ['Gareth Bale', 'Bale']
{'score': 0.9318289160728455, 'start': 636, 'end': 647, 'answer': 'Gareth Bale'}
follow question : Who performed at the opening ceremony of the champions league final 2018?
short answer : ['Dua Lipa', 'Sean Paul', 'Dua Lipa and Sean Paul']
{'score': 0.9299752712249756, 'start': 85, 'end': 93, 'answer': 'Dua Lipa'}
follow question : Who performed the anthem at the champions league final 2018?
short answer : ['2Cellos', 'Luka Šulić and Stjepan Hauser', 'Luka Šulić', '2CΞLLOS', 'Stjepan Hauser']
{'score': 0.6367819309234619, 'start': 225, 'end': 232, 'answer': '2Cellos'}
{'rougeLsum': 44.99999999999999, 'length': 110.0, 'str_em': 100.0, 'Disambig-F1': 90.0}
{'first_doc_retrival': 0.5, 'first_title_retrival': 1.0}
 Retrival Match Rate: 0.3
['Thelma & Louise' 'Thelma & Louise' 'Thelma & Louise' 'Thelma & Louise'
 'Riddler' 'Snapped' 'Snapped: Killer Couples' 'The Bodyguard (1992 film)'
 '800 Words' 'List of Lucifer episodes']
{'Thelma & Louise', 'Come Thelma & Louise'}
Title Match Rate: 0.5
Final ans: Harlan, a stranger Thelma met at a roadhouse bar, was killed by Louise after he attempted to rape Thelma. Harlan's death was a pivotal moment in the film, leading to Thelma and Louise's decision to go on the run. The killer, Harlan, was not a character with a complex backstory or motivation, but rather a symbol of the violence and danger that Thelma and Louise faced on their road trip. Harlan's death was a catalyst for the events that unfolded in the film, leading to the duo's increased desperation and reckless behavior. In the context of the film, Harlan's killing was a necessary evil, a means to an end, rather than a morally complex or nuanced act.
Harlan, a stranger Thelma met at a roadhouse bar, was killed by Louise after he attempted to rape Thelma. Harlan's death was a pivotal moment in the film, leading to Thelma and Louise's decision to go on the run. The killer, Harlan, was not a character with a complex backstory or motivation, but rather a symbol of the violence and danger that Thelma and Louise faced on their road trip. Harlan's death was a catalyst for the events that unfolded in the film, leading to the duo's increased desperation and reckless behavior. In the context of the film, Harlan's killing was a necessary evil, a means to an end, rather than a morally complex or nuanced act.
Who killed the man in thelma and louise?
['Which character killed the man in thelma and louise?', 'Which actor killed the man in thelma and louise?', 'Who is the character that kills Harlan in the film Thelma and Louise?', 'Who is the actor of the character that killed a man in the film Thelma and Louise?']
[['Louise Elizabeth Sawyer', 'Louise'], ['Susan Sarandon', 'Susan Abigail Sarandon'], ['Louise Elizabeth Sawyer', 'Louise'], ['Susan Sarandon']]

 35%|███▌      | 7/20 [01:44<03:08, 14.50s/it]

follow question : Which character killed the man in thelma and louise?
short answer : ['Louise Elizabeth Sawyer', 'Louise']
{'score': 0.6023950576782227, 'start': 0, 'end': 6, 'answer': 'Harlan'}
follow question : Which actor killed the man in thelma and louise?
short answer : ['Susan Sarandon', 'Susan Abigail Sarandon']
{'score': 8.195706323022023e-05, 'start': 0, 'end': 6, 'answer': 'Harlan'}
follow question : Who is the character that kills Harlan in the film Thelma and Louise?
short answer : ['Louise Elizabeth Sawyer', 'Louise']
{'score': 0.9151970744132996, 'start': 64, 'end': 70, 'answer': 'Louise'}
follow question : Who is the actor of the character that killed a man in the film Thelma and Louise?
short answer : ['Susan Sarandon']
{'score': 1.8167372672905913e-06, 'start': 0, 'end': 6, 'answer': 'Harlan'}
{'rougeLsum': 24.043715846994537, 'length': 117.0, 'str_em': 50.0, 'Disambig-F1': 25.0}
{'first_doc_retrival': 0.3, 'first_title_retrival': 0.5}
 Retrival Match Rate: 0.9
["Charlie Kelly (It's Always Sunny in Philadelphia)"
 "Charlie Kelly (It's Always Sunny in Philadelphia)"
 "Charlie Kelly (It's Always Sunny in Philadelphia)"
 "Charlie Kelly (It's Always Sunny in Philadelphia)"
 "Charlie Kelly (It's Always Sunny in Philadelphia)"
 "Charlie Kelly (It's Always Sunny in Philadelphia)"
 "Charlie Kelly (It's Always Sunny in Philadelphia)"
 "List of It's Always Sunny in Philadelphia characters"
 "List of It's Always Sunny in Philadelphia characters"
 "List of It's Always Sunny in Philadelphia characters"]
{"List of It's Always Sunny in Philadelphia characters", "Charlie Kelly (It's Always Sunny in Philadelphia)"}
Title Match Rate: 1.0
Final ans: Charlie Kelly is played by Charlie Day. Charlie Kelly is a main character in the show It's Always Sunny in Philadelphia, and Charlie Day is the actor who portrays him. Charlie Kelly is a member of "The Gang" and is known for his outrageous behavior and antics. Charlie Day is a main cast member and has appeared in numerous episodes throughout the series. Charlie Day's portrayal of Charlie Kelly is a key part of the show's humor and charm.
Charlie Kelly is played by Charlie Day. Charlie Kelly is a main character in the show It's Always Sunny in Philadelphia, and Charlie Day is the actor who portrays him. Charlie Kelly is a member of "The Gang" and is known for his outrageous behavior and antics. Charlie Day is a main cast member and has appeared in numerous episodes throughout the series. Charlie Day's portrayal of Charlie Kelly is a key part of the show's humor and charm.
Who plays charlie on it's always sunny?
["Who does Charlie Day play on It's Always Sunny in Philadelphia?", "Who plays Charlie Kelly on It's Always Sunny in Philadelphia?"]
[['Charlie Kelly'], ['Charlie Day']]

 40%|████      | 8/20 [01:53<02:34, 12.85s/it]

follow question : Who does Charlie Day play on It's Always Sunny in Philadelphia?
short answer : ['Charlie Kelly']
{'score': 0.7858500480651855, 'start': 0, 'end': 13, 'answer': 'Charlie Kelly'}
follow question : Who plays Charlie Kelly on It's Always Sunny in Philadelphia?
short answer : ['Charlie Day']
{'score': 0.9377378821372986, 'start': 27, 'end': 38, 'answer': 'Charlie Day'}
{'rougeLsum': 42.335766423357654, 'length': 79.0, 'str_em': 100.0, 'Disambig-F1': 100.0}
{'first_doc_retrival': 0.9, 'first_title_retrival': 1.0}
 Retrival Match Rate: 0.4
['Los Angeles Lakers' 'Los Angeles Lakers' 'Los Angeles Lakers'
 'Los Angeles Lakers' 'Los Angeles Lakers' '2010 NBA Finals'
 '2010 NBA Finals' '2010 NBA Finals' '2009 NBA Finals'
 'National Basketball Association']
{'Los Angeles Lakers'}
Title Match Rate: 1.0
Final ans: The Los Angeles Lakers have won the NBA Finals 16 times, with their most recent championship in 2010. They have appeared in the NBA Finals a total of 31 times, which is the second-most in NBA history. The Lakers have won five championships since moving to Los Angeles in 1960, and their most successful era was in the 1980s, where they won five championships in a nine-year span. They have also won three consecutive titles between 2000 to 2002, and two more championships in 2009 and 2010. Overall, the Lakers have a rich history of success in the NBA Finals.
The Los Angeles Lakers have won the NBA Finals 16 times, with their most recent championship in 2010. They have appeared in the NBA Finals a total of 31 times, which is the second-most in NBA history. The Lakers have won five championships since moving to Los Angeles in 1960, and their most successful era was in the 1980s, where they won five championships in a nine-year span. They have also won three consecutive titles between 2000 to 2002, and two more championships in 2009 and 2010. Overall, the Lakers have a rich history of success in the NBA Finals.
How many times have the lakers won the finals?
['As of 2017, how many times have the lakers won the finals?', 'As of 2016, how many times have the Lakers won the finals?', 'As of 2015, how many times have the Lakers won the finals?']
[['16'], ['16'], ['16']]

 45%|████▌     | 9/20 [02:06<02:21, 12.84s/it]

follow question : As of 2017, how many times have the lakers won the finals?
short answer : ['16']
{'score': 0.7807962894439697, 'start': 47, 'end': 49, 'answer': '16'}
follow question : As of 2016, how many times have the Lakers won the finals?
short answer : ['16']
{'score': 0.8590690493583679, 'start': 47, 'end': 49, 'answer': '16'}
follow question : As of 2015, how many times have the Lakers won the finals?
short answer : ['16']
{'score': 0.68630051612854, 'start': 47, 'end': 49, 'answer': '16'}
{'rougeLsum': 38.35616438356165, 'length': 100.0, 'str_em': 100.0, 'Disambig-F1': 100.0}
{'first_doc_retrival': 0.4, 'first_title_retrival': 1.0}
 Retrival Match Rate: 0.7
['Indian National Congress' 'Indian National Congress'
 'Indian National Congress' 'Indian National Congress'
 'Indian National Congress' 'Indian National Congress'
 'Indian National Congress'
 'List of current Indian ruling and opposition parties'
 'List of presidents of the Indian National Congress' 'India']
{'List of current Indian ruling and opposition parties', 'Indian National Congress'}
Title Match Rate: 1.0
Final ans: The Indian National Congress is in power in six legislative assemblies: Punjab, Rajasthan, Chhattisgarh, Madhya Pradesh, Maharashtra (as part of the Maha Vikas Aghadi), and the union territory of Puducherry (in an alliance with DMK). In addition, the party is in power in the state of Jharkhand, as a junior ally with Jharkhand Mukti Morcha. However, the party's presence in other states is not as prominent, with the Bharatiya Janata Party (BJP) being the dominant force in many states. The Congress party has a significant presence in the union territories of Chandigarh and Delhi, but is not in power in these territories. Overall, the Congress party is in power in a total of seven legislative assemblies and union territories.
The Indian National Congress is in power in six legislative assemblies: Punjab, Rajasthan, Chhattisgarh, Madhya Pradesh, Maharashtra (as part of the Maha Vikas Aghadi), and the union territory of Puducherry (in an alliance with DMK). In addition, the party is in power in the state of Jharkhand, as a junior ally with Jharkhand Mukti Morcha. However, the party's presence in other states is not as prominent, with the Bharatiya Janata Party (BJP) being the dominant force in many states. The Congress party has a significant presence in the union territories of Chandigarh and Delhi, but is not in power in these territories. Overall, the Congress party is in power in a total of seven legislative assemblies and union territories.
How many states in india are under congress?
['How many states plus territories in india are under congress?', 'How many states alone in india are under congress?']
[['7'], ['5']]

 50%|█████     | 10/20 [02:24<02:24, 14.44s/it]

follow question : How many states plus territories in india are under congress?
short answer : ['7']
{'score': 0.9327518939971924, 'start': 680, 'end': 685, 'answer': 'seven'}
follow question : How many states alone in india are under congress?
short answer : ['5']
{'score': 0.647281289100647, 'start': 680, 'end': 685, 'answer': 'seven'}
{'rougeLsum': 22.09944751381215, 'length': 119.0, 'str_em': 0.0, 'Disambig-F1': 0.0}
{'first_doc_retrival': 0.7, 'first_title_retrival': 1.0}
 Retrival Match Rate: 1.0
['Fiddler on the Roof (film)' 'Fiddler on the Roof (film)'
 'Fiddler on the Roof (film)' 'Fiddler on the Roof' 'Fiddler on the Roof'
 'Fiddler on the Roof' 'Fiddler on the Roof' 'Fiddler on the Roof'
 'Fiddler on the Roof' 'Fiddler on the Roof']
{'Fiddler on the Roof', 'Category:Fiddler on the Roof', 'Jessica Vosk', 'Fiddler on the Roof (film)'}
Title Match Rate: 0.5
Final ans: Fruma-Sarah is the deceased wife of Lazar Wolf, a wealthy butcher, who rises from the grave to warn against the marriage of her namesake, Tzeitel, to Lazar. In the musical, Fruma-Sarah is portrayed as a ghostly figure who appears to Tevye in his dream, warning him of the dangers of Tzeitel marrying Lazar. She is a significant character in the story, representing the traditions and values of the Jewish community. Fruma-Sarah's presence serves as a catalyst for Tevye's decision to allow Tzeitel to marry Motel, rather than Lazar. Her ghostly appearance also adds a sense of mystery and magic to the story.
Fruma-Sarah is the deceased wife of Lazar Wolf, a wealthy butcher, who rises from the grave to warn against the marriage of her namesake, Tzeitel, to Lazar. In the musical, Fruma-Sarah is portrayed as a ghostly figure who appears to Tevye in his dream, warning him of the dangers of Tzeitel marrying Lazar. She is a significant character in the story, representing the traditions and values of the Jewish community. Fruma-Sarah's presence serves as a catalyst for Tevye's decision to allow Tzeitel to marry Motel, rather than Lazar. Her ghostly appearance also adds a sense of mystery and magic to the story.
Who is fruma sarah in fiddler on the roof?
['Who played fruma sarah in the 1971 film, Fiddler on the Roof?', 'Who played Fruma Sarah in the original 1964 Broadway cast of Fiddler on the Roof?', 'Who is the character of Fruma Sarah in Fiddler on the Roof?', 'Who played Fruma Sarah in the 2015-2016 Broadway Revival of Fiddler on the Roof?']
[['Ruth Madoc'], ['Carol Sawyer Yussel'], ['a ghostly depiction of the late wife of Lazar Wolf'], ['Jessica Vosk']]

 55%|█████▌    | 11/20 [02:37<02:07, 14.13s/it]

follow question : Who played fruma sarah in the 1971 film, Fiddler on the Roof?
short answer : ['Ruth Madoc']
{'score': 8.419319783570245e-06, 'start': 36, 'end': 46, 'answer': 'Lazar Wolf'}
follow question : Who played Fruma Sarah in the original 1964 Broadway cast of Fiddler on the Roof?
short answer : ['Carol Sawyer Yussel']
{'score': 1.639369742179042e-07, 'start': 36, 'end': 46, 'answer': 'Lazar Wolf'}
follow question : Who is the character of Fruma Sarah in Fiddler on the Roof?
short answer : ['a ghostly depiction of the late wife of Lazar Wolf']
{'score': 0.3772675395011902, 'start': 15, 'end': 46, 'answer': 'the deceased wife of Lazar Wolf'}
follow question : Who played Fruma Sarah in the 2015-2016 Broadway Revival of Fiddler on the Roof?
short answer : ['Jessica Vosk']
{'score': 6.755554409210163e-07, 'start': 36, 'end': 46, 'answer': 'Lazar Wolf'}
{'rougeLsum': 34.28571428571428, 'length': 102.0, 'str_em': 0.0, 'Disambig-F1': 15.384615384615385}
{'first_doc_retrival': 1.0, 'first_title_retrival': 0.5}
 Retrival Match Rate: 0.9
['List of Major League Baseball All-Star Game venues'
 'List of Major League Baseball All-Star Game venues'
 'List of Major League Baseball All-Star Game venues'
 'List of Major League Baseball All-Star Game venues'
 'List of Major League Baseball All-Star Game venues'
 'List of Major League Baseball All-Star Game venues'
 'List of Major League Baseball All-Star Game venues'
 'List of Major League Baseball All-Star Game venues'
 'List of Major League Baseball All-Star Game venues'
 'List of Major League Baseball All-Star Game venues']
{'List of Major League Baseball All-Star Game venues'}
Title Match Rate: 1.0
Final ans: Toronto hosted the MLB All-Star Game on July 9, 1991, at SkyDome. This was the only time Toronto hosted the All-Star Game.
Toronto hosted the MLB All-Star Game on July 9, 1991, at SkyDome. This was the only time Toronto hosted the All-Star Game.
When did toronto host the mlb all-star game?
['What date did toronto host the mlb all-star game?', 'Which all-star game did toronto host?']
[['July 9, 1991'], ['1991 Major League Baseball All-Star Game', 'the 62nd playing of the midsummer classic']]

 60%|██████    | 12/20 [02:43<01:32, 11.55s/it]

follow question : What date did toronto host the mlb all-star game?
short answer : ['July 9, 1991']
{'score': 0.9901335835456848, 'start': 40, 'end': 52, 'answer': 'July 9, 1991'}
follow question : Which all-star game did toronto host?
short answer : ['1991 Major League Baseball All-Star Game', 'the 62nd playing of the midsummer classic']
{'score': 0.633891224861145, 'start': 19, 'end': 36, 'answer': 'MLB All-Star Game'}
{'rougeLsum': 42.5531914893617, 'length': 22.0, 'str_em': 50.0, 'Disambig-F1': 72.22222222222221}
{'first_doc_retrival': 0.9, 'first_title_retrival': 1.0}
 Retrival Match Rate: 0.7
['To Catch a Thief' 'To Catch a Thief' 'To Catch a Thief'
 'To Catch a Thief' 'To Catch a Thief (1936 film)' 'Sunbeam Alpine'
 'Sunbeam Alpine' 'It Takes a Thief (1968 TV series)'
 'List of Cars characters' 'Doc Hudson']
{'Sunbeam Alpine', 'To Catch a Thief', 'To Catch a Thief (1936 film)', 'It Takes a Thief (1968 TV series)'}
Title Match Rate: 1.0
Final ans: The car driven by Grace Kelly in the 1955 film To Catch a Thief is a metallic blue 1953 Sunbeam Alpine Mk I. The Sunbeam Alpine is a two-door roadster produced from 1953 to 1955, with a 2.267 cc engine and a top speed of around 90 mph. In the film, the car is driven by Grace Kelly's character, Frances Stevens, and is featured prominently throughout the movie. The Sunbeam Alpine has made appearances in several other films and TV shows, including Night of the Demon, Butterfield 8, and Dr. No. The car's sleek design and sporty features made it a popular choice for movie and TV producers looking for a stylish and exciting vehicle.
The car driven by Grace Kelly in the 1955 film To Catch a Thief is a metallic blue 1953 Sunbeam Alpine Mk I. The Sunbeam Alpine is a two-door roadster produced from 1953 to 1955, with a 2.267 cc engine and a top speed of around 90 mph. In the film, the car is driven by Grace Kelly's character, Frances Stevens, and is featured prominently throughout the movie. The Sunbeam Alpine has made appearances in several other films and TV shows, including Night of the Demon, Butterfield 8, and Dr. No. The car's sleek design and sporty features made it a popular choice for movie and TV producers looking for a stylish and exciting vehicle.
What kind of car in to catch a thief?
['What kind of car in to catch a thief in terms of model?', 'What kind of car in to catch a thief in terms of automobile make?']
[['Sunbeam Alpine', '1953 Sunbeam Alpine Mk I'], ['Rootes Group']]

 65%|██████▌   | 13/20 [02:57<01:26, 12.38s/it]

follow question : What kind of car in to catch a thief in terms of model?
short answer : ['Sunbeam Alpine', '1953 Sunbeam Alpine Mk I']
{'score': 0.49405863881111145, 'start': 83, 'end': 107, 'answer': '1953 Sunbeam Alpine Mk I'}
follow question : What kind of car in to catch a thief in terms of automobile make?
short answer : ['Rootes Group']
{'score': 0.4290896952152252, 'start': 83, 'end': 107, 'answer': '1953 Sunbeam Alpine Mk I'}
{'rougeLsum': 44.10256410256411, 'length': 115.0, 'str_em': 50.0, 'Disambig-F1': 50.0}
{'first_doc_retrival': 0.7, 'first_title_retrival': 1.0}
 Retrival Match Rate: 0.8
['Jersey Shore (TV series)' 'Jersey Shore (TV series)'
 'Jersey Shore (TV series)' 'Jersey Shore (TV series)'
 'Jersey Shore (TV series)' 'Jersey Shore (TV series)'
 'Jersey Shore (TV series)' 'Jersey Shore (TV series)'
 'Jersey Shore (TV series)' 'Nashville (season 6)']
{'Jersey Shore (TV series)'}
Title Match Rate: 1.0
Final ans: The last season of Jersey Shore aired from October 4, 2012, to December 20, 2012. The sixth season, which was the final season, premiered on October 4, 2012, and consisted of 13 episodes. The season finale aired on December 20, 2012. However, the cast reunited for a new series, Jersey Shore: Family Vacation, which premiered on April 5, 2018.
The last season of Jersey Shore aired from October 4, 2012, to December 20, 2012. The sixth season, which was the final season, premiered on October 4, 2012, and consisted of 13 episodes. The season finale aired on December 20, 2012. However, the cast reunited for a new series, Jersey Shore: Family Vacation, which premiered on April 5, 2018.
When did the last season of jersey shore air?
['When did season 4 of jersey shore first air?', 'When did season 4 of jersey shore last air?', 'When did season 5 of jersey shore first air?', 'When did season 5 of jersey shore last air?', 'When did season 6 of jersey shore first air?', 'When did season 6 of jersey shore last air?']
[['August 4, 2011'], ['October 20, 2011'], ['January 5, 2012'], ['March 15, 2012'], ['October 4, 2012'], ['December 20, 2012']]

 70%|███████   | 14/20 [03:07<01:09, 11.65s/it]

follow question : When did season 4 of jersey shore first air?
short answer : ['August 4, 2011']
{'score': 0.5106071829795837, 'start': 43, 'end': 58, 'answer': 'October 4, 2012'}
follow question : When did season 4 of jersey shore last air?
short answer : ['October 20, 2011']
{'score': 0.4544923007488251, 'start': 43, 'end': 58, 'answer': 'October 4, 2012'}
follow question : When did season 5 of jersey shore first air?
short answer : ['January 5, 2012']
{'score': 0.010889302007853985, 'start': 43, 'end': 58, 'answer': 'October 4, 2012'}
follow question : When did season 5 of jersey shore last air?
short answer : ['March 15, 2012']
{'score': 0.5089642405509949, 'start': 43, 'end': 58, 'answer': 'October 4, 2012'}
follow question : When did season 6 of jersey shore first air?
short answer : ['October 4, 2012']
{'score': 0.947599470615387, 'start': 141, 'end': 156, 'answer': 'October 4, 2012'}
follow question : When did season 6 of jersey shore last air?
short answer : ['December 20, 2012']
{'score': 0.32458850741386414, 'start': 63, 'end': 80, 'answer': 'December 20, 2012'}
{'rougeLsum': 37.931034482758626, 'length': 59.0, 'str_em': 33.33333333333333, 'Disambig-F1': 55.55555555555555}
{'first_doc_retrival': 0.8, 'first_title_retrival': 1.0}
 Retrival Match Rate: 0.7
["One Flight Down (Grey's Anatomy)" "Grey's Anatomy (season 9)"
 "Grey's Anatomy (season 9)" "Flight (Grey's Anatomy)"
 "Flight (Grey's Anatomy)" "Flight (Grey's Anatomy)"
 "Going, Going, Gone (Grey's Anatomy)" "Grey's Anatomy (season 8)"
 "Grey's Anatomy (season 6)" "Grey's Anatomy"]
{"One Flight Down (Grey's Anatomy)", "Grey's Anatomy (season 8)", "Grey's Anatomy (season 9)", "Going, Going, Gone (Grey's Anatomy)", "Flight (Grey's Anatomy)"}
Title Match Rate: 1.0
Final ans: The plane crash occurred in the eighth season of Grey's Anatomy. The episode "Flight" (Season 8, Episode 24) depicts the crash and its aftermath. The plane crash is a pivotal event in the series, marking a turning point for the characters and the hospital. The season's finale, "Flight," shows the aftermath of the crash, with the doctors struggling to survive and cope with their injuries. The crash also has a significant impact on the characters' personal and professional lives, leading to changes and developments in the following seasons.
The plane crash occurred in the eighth season of Grey's Anatomy. The episode "Flight" (Season 8, Episode 24) depicts the crash and its aftermath. The plane crash is a pivotal event in the series, marking a turning point for the characters and the hospital. The season's finale, "Flight," shows the aftermath of the crash, with the doctors struggling to survive and cope with their injuries. The crash also has a significant impact on the characters' personal and professional lives, leading to changes and developments in the following seasons.
What season of greys anatomy was the plane crash?
["What season of Grey's Anatomy was the plane crash involving six doctors?", "What season of Grey's Anatomy was the plane crash in Seattle that brought memories of a previous plane crash?", "What season of Grey's Anatomy was the plane crash that claimed the life of Lexie Grey?", "What season of Grey's Anatomy was the plane crash in downtown Seattle?"]
[['season 8'], ['season 11'], ['8'], ['11']]

 75%|███████▌  | 15/20 [03:18<00:57, 11.54s/it]

follow question : What season of Grey's Anatomy was the plane crash involving six doctors?
short answer : ['season 8']
{'score': 0.14534629881381989, 'start': 32, 'end': 38, 'answer': 'eighth'}
follow question : What season of Grey's Anatomy was the plane crash in Seattle that brought memories of a previous plane crash?
short answer : ['season 11']
{'score': 0.3803563714027405, 'start': 32, 'end': 45, 'answer': 'eighth season'}
follow question : What season of Grey's Anatomy was the plane crash that claimed the life of Lexie Grey?
short answer : ['8']
{'score': 0.4800831377506256, 'start': 32, 'end': 38, 'answer': 'eighth'}
follow question : What season of Grey's Anatomy was the plane crash in downtown Seattle?
short answer : ['11']
{'score': 0.4241483211517334, 'start': 32, 'end': 38, 'answer': 'eighth'}
{'rougeLsum': 34.83870967741935, 'length': 88.0, 'str_em': 50.0, 'Disambig-F1': 12.5}
{'first_doc_retrival': 0.7, 'first_title_retrival': 1.0}
 Retrival Match Rate: 0.1
['Oriental Bank of Commerce' 'Oriental Bank of Commerce'
 'Public Accounts Committee (India)'
 'List of Indian parliamentary committees'
 'List of Indian parliamentary committees' 'India'
 'India at the 2018 Asian Games' 'India at the 2018 Asian Games'
 'Christianity' 'Sports Authority of India']
{'Oriental Bank of Commerce'}
Title Match Rate: 1.0
Final ans: The Oriental Bank of Commerce has 2390 branches across India, as mentioned in the document. Additionally, after the acquisition of Global Trust Bank (GTB) in 2004, the total number of branches increased to 1092, and as of the March 2018-2019 annual report, it has 2390 branches and 2625 ATMs pan India.
The Oriental Bank of Commerce has 2390 branches across India, as mentioned in the document. Additionally, after the acquisition of Global Trust Bank (GTB) in 2004, the total number of branches increased to 1092, and as of the March 2018-2019 annual report, it has 2390 branches and 2625 ATMs pan India.
Number of branches of oriental bank of commerce in india?
['As per the March 2018-2019 report, what is the number of branches of oriental bank of commerce in india?', 'What is the number of branches of oriental bank of commerce in india after amalgamation of Global Trust Bank?', 'Number of branches of oriental bank of commerce in india after expected merger with United Bank of India in 2020?']
[['2390'], ['1092'], ['11,437']]

 80%|████████  | 16/20 [03:28<00:43, 10.87s/it]

follow question : As per the March 2018-2019 report, what is the number of branches of oriental bank of commerce in india?
short answer : ['2390']
{'score': 0.36508798599243164, 'start': 34, 'end': 38, 'answer': '2390'}
follow question : What is the number of branches of oriental bank of commerce in india after amalgamation of Global Trust Bank?
short answer : ['1092']
{'score': 0.9757329821586609, 'start': 206, 'end': 210, 'answer': '1092'}
follow question : Number of branches of oriental bank of commerce in india after expected merger with United Bank of India in 2020?
short answer : ['11,437']
{'score': 0.007541196420788765, 'start': 34, 'end': 38, 'answer': '2390'}
{'rougeLsum': 54.86725663716814, 'length': 51.0, 'str_em': 66.66666666666666, 'Disambig-F1': 66.66666666666666}
{'first_doc_retrival': 0.1, 'first_title_retrival': 1.0}
 Retrival Match Rate: 0.5
['History of the St. Louis Rams' 'History of the St. Louis Rams'
 'History of the St. Louis Rams' 'History of the Los Angeles Rams'
 'History of the Los Angeles Rams' 'History of the Los Angeles Rams'
 'History of the St. Louis Cardinals (NFL)' 'Los Angeles Rams'
 'Los Angeles Rams' 'Los Angeles Rams']
{'History of the Los Angeles Rams', 'History of the St. Louis Rams'}
Title Match Rate: 1.0
Final ans: The Rams relocated to St. Louis in 1995, after the city was granted a new stadium, the Trans World Dome, and agreed to build a taxpayer-financed stadium. The team played their first game in St. Louis on September 10, 1995, against the New Orleans Saints, and their new stadium opened on November 12, 1995, with a 28-17 victory against the Carolina Panthers. The Rams played in St. Louis for 21 seasons, until the end of the 2015 season, when they returned to Los Angeles. The relocation was initially voted down by the other NFL owners, but Commissioner Paul Tagliabue eventually acquiesced to the move after Georgia Frontiere threatened to sue the league. The Rams' final game in St. Louis was played on December 17, 2015, against the Tampa Bay Buccaneers.
The Rams relocated to St. Louis in 1995, after the city was granted a new stadium, the Trans World Dome, and agreed to build a taxpayer-financed stadium. The team played their first game in St. Louis on September 10, 1995, against the New Orleans Saints, and their new stadium opened on November 12, 1995, with a 28-17 victory against the Carolina Panthers. The Rams played in St. Louis for 21 seasons, until the end of the 2015 season, when they returned to Los Angeles. The relocation was initially voted down by the other NFL owners, but Commissioner Paul Tagliabue eventually acquiesced to the move after Georgia Frontiere threatened to sue the league. The Rams' final game in St. Louis was played on December 17, 2015, against the Tampa Bay Buccaneers.
When did the rams go to st louis?
['In what year did the rams go to St. Louis?', 'What was the first game the Rams played in St. Louis?']
[['1995'], ['September 10, 1995']]

 85%|████████▌ | 17/20 [03:44<00:37, 12.43s/it]

follow question : In what year did the rams go to St. Louis?
short answer : ['1995']
{'score': 0.9425658583641052, 'start': 35, 'end': 39, 'answer': '1995'}
follow question : What was the first game the Rams played in St. Louis?
short answer : ['September 10, 1995']
{'score': 0.4774143695831299, 'start': 235, 'end': 253, 'answer': 'New Orleans Saints'}
{'rougeLsum': 41.463414634146346, 'length': 130.0, 'str_em': 100.0, 'Disambig-F1': 50.0}
{'first_doc_retrival': 0.5, 'first_title_retrival': 1.0}
 Retrival Match Rate: 0.8
['Voortrekkers (youth organisation)' 'Voortrekkers (youth organisation)'
 'Voortrekkers (youth organisation)' 'Great Trek' 'Great Trek'
 'Great Trek' 'Great Trek' 'Great Trek' 'Great Trek' 'Great Trek']
{'Voortrekkers (youth organisation)', 'Great Trek'}
Title Match Rate: 1.0
Final ans: The Voortrekkers, a group of Dutch-speaking settlers, arrived in South Africa in the early 19th century, specifically from 1835 to 1840, with the first wave of trekkers leaving in September 1835. The trekkers, led by Louis Tregardt and Hans van Rensburg, crossed the Vaal river at Robert's Drift in January 1836. However, the exact dates of arrival vary depending on the specific group of Voortrekkers, with some arriving in September 1835, others in late 1835 or early 1836, and others in February or April 1837. The first two parties of Voortrekkers left in September 1835, but they split up in April 1836, just 70 miles from the Zoutpansberg mountains. Overall, the Voortrekkers arrived in South Africa over a period of several years, with different groups arriving at different times.
The Voortrekkers, a group of Dutch-speaking settlers, arrived in South Africa in the early 19th century, specifically from 1835 to 1840, with the first wave of trekkers leaving in September 1835. The trekkers, led by Louis Tregardt and Hans van Rensburg, crossed the Vaal river at Robert's Drift in January 1836. However, the exact dates of arrival vary depending on the specific group of Voortrekkers, with some arriving in September 1835, others in late 1835 or early 1836, and others in February or April 1837. The first two parties of Voortrekkers left in September 1835, but they split up in April 1836, just 70 miles from the Zoutpansberg mountains. Overall, the Voortrekkers arrived in South Africa over a period of several years, with different groups arriving at different times.
When did the voortrekkers arrive in south africa?
['When did the first wave of voortrekkers arrive in south africa?', 'When did the voortrekkers exploratory treks arrive in south africa?']
[['1836', '1836 onwards'], ['February 1835']]

 90%|█████████ | 18/20 [04:02<00:28, 14.19s/it]

follow question : When did the first wave of voortrekkers arrive in south africa?
short answer : ['1836', '1836 onwards']
{'score': 0.6554544568061829, 'start': 180, 'end': 194, 'answer': 'September 1835'}
follow question : When did the voortrekkers exploratory treks arrive in south africa?
short answer : ['February 1835']
{'score': 0.033598050475120544, 'start': 180, 'end': 194, 'answer': 'September 1835'}
{'rougeLsum': 24.000000000000004, 'length': 129.0, 'str_em': 50.0, 'Disambig-F1': 25.0}
{'first_doc_retrival': 0.8, 'first_title_retrival': 1.0}
 Retrival Match Rate: 0.8
['10 Things I Hate About You' '10 Things I Hate About You'
 '10 Things I Hate About You' '10 Things I Hate About You'
 '10 Things I Hate About You' '10 Things I Hate About You (TV series)'
 '10 Things I Hate About You (TV series)'
 '10 Things I Hate About You (TV series)'
 '10 Things I Hate About You (TV series)'
 '10 Things I Hate About You (TV series)']
{'10 Things I Hate About You', '10 Things I Hate About You (TV series)'}
Title Match Rate: 1.0
Final ans: Heath Ledger plays Patrick Verona in the 1999 film adaptation of 10 Things I Hate About You. In the TV series, Ethan Peck plays Patrick Verona, the brooding high school junior who often gets into trouble. Both actors portray Patrick as a bad boy with a soft spot for Kat Stratford. The character's complexities and charm are a central aspect of the story in both the film and the TV series. The portrayal of Patrick by both actors brings depth and nuance to the character, making him a memorable and beloved figure in the story.
Heath Ledger plays Patrick Verona in the 1999 film adaptation of 10 Things I Hate About You. In the TV series, Ethan Peck plays Patrick Verona, the brooding high school junior who often gets into trouble. Both actors portray Patrick as a bad boy with a soft spot for Kat Stratford. The character's complexities and charm are a central aspect of the story in both the film and the TV series. The portrayal of Patrick by both actors brings depth and nuance to the character, making him a memorable and beloved figure in the story.
Who plays patrick in 10 things i hate about you?
['Who plays patrick in  the 1999 film 10 things i hate about you?', 'Who plays patrick in the 2009 tv series 10 things i hate about you?', 'Who plays patrick in the film 10 things i hate about you?', 'Who plays patrick in the TV series 10 things i hate about you?']
[['Heath Andrew Ledger', 'Heath Ledger', 'Ledger'], ['Ethan Peck', 'Peck', 'Ethan Gregory Peck'], ['Heath Andrew Ledger', 'Heath Ledger'], ['Ethan Peck', 'Ethan Gregory Peck']]

 95%|█████████▌| 19/20 [04:14<00:13, 13.53s/it]

follow question : Who plays patrick in  the 1999 film 10 things i hate about you?
short answer : ['Heath Andrew Ledger', 'Heath Ledger', 'Ledger']
{'score': 0.9978004097938538, 'start': 0, 'end': 12, 'answer': 'Heath Ledger'}
follow question : Who plays patrick in the 2009 tv series 10 things i hate about you?
short answer : ['Ethan Peck', 'Peck', 'Ethan Gregory Peck']
{'score': 2.8766098125743156e-07, 'start': 111, 'end': 121, 'answer': 'Ethan Peck'}
follow question : Who plays patrick in the film 10 things i hate about you?
short answer : ['Heath Andrew Ledger', 'Heath Ledger']
{'score': 0.9974117875099182, 'start': 0, 'end': 12, 'answer': 'Heath Ledger'}
follow question : Who plays patrick in the TV series 10 things i hate about you?
short answer : ['Ethan Peck', 'Ethan Gregory Peck']
{'score': 0.9973465204238892, 'start': 111, 'end': 121, 'answer': 'Ethan Peck'}
{'rougeLsum': 30.88235294117647, 'length': 95.0, 'str_em': 100.0, 'Disambig-F1': 100.0}
{'first_doc_retrival': 0.8, 'first_title_retrival': 1.0}
 Retrival Match Rate: 0.7
['Indian National Congress' 'List of chief ministers of Madhya Pradesh'
 'List of chief ministers of Madhya Pradesh'
 'List of chief ministers of Madhya Pradesh'
 'List of chief ministers of Madhya Pradesh' 'Babulal Gaur' 'Babulal Gaur'
 'Babulal Gaur' 'List of chief ministers of Maharashtra'
 'List of current members of the Rajya Sabha']
{'M. Karunanidhi', 'List of chief ministers of Maharashtra', 'List of chief ministers of Madhya Pradesh', 'Babulal Gaur'}
Title Match Rate: 0.75
Final ans: The current chief minister of Madhya Pradesh is Kamal Nath of the Indian National Congress. He was appointed as the chief minister on 17 December 2018 and is still in office. Prior to him, the chief ministers of Madhya Pradesh were Digvijaya Singh, Uma Bharti, Babulal Gaur, and Shivraj Singh Chouhan. Babulal Gaur served as the chief minister from 23 August 2004 to 29 November 2005, while Shivraj Singh Chouhan served from 29 November 2005 to 17 December 2018.
The current chief minister of Madhya Pradesh is Kamal Nath of the Indian National Congress. He was appointed as the chief minister on 17 December 2018 and is still in office. Prior to him, the chief ministers of Madhya Pradesh were Digvijaya Singh, Uma Bharti, Babulal Gaur, and Shivraj Singh Chouhan. Babulal Gaur served as the chief minister from 23 August 2004 to 29 November 2005, while Shivraj Singh Chouhan served from 29 November 2005 to 17 December 2018.
Who is the chief minister of m. p?
['Who is the 17th Chief Minister of MP?', 'Who is the 16th Chief Minister of MP?', 'Who is the 15th Chief Minister of MP?', 'Who is the 17th chief minister of m. p?', 'Who is the 16th chief minister of m. p?', 'Who is the 15th chief minister of m. p?']
[['Shivraj Singh Chauhan'], ['Babulal Gaur'], ['Uma Bharti'], ['Shivraj Singh Chauhan'], ['Babulal Gaur', 'Babulal Gaur Yadav'], ['Uma Bharti']]

100%|██████████| 20/20 [04:26<00:00, 13.32s/it]

follow question : Who is the 17th Chief Minister of MP?
short answer : ['Shivraj Singh Chauhan']
{'score': 0.42385420203208923, 'start': 48, 'end': 58, 'answer': 'Kamal Nath'}
follow question : Who is the 16th Chief Minister of MP?
short answer : ['Babulal Gaur']
{'score': 0.03904242441058159, 'start': 48, 'end': 58, 'answer': 'Kamal Nath'}
follow question : Who is the 15th Chief Minister of MP?
short answer : ['Uma Bharti']
{'score': 0.008034644648432732, 'start': 48, 'end': 58, 'answer': 'Kamal Nath'}
follow question : Who is the 17th chief minister of m. p?
short answer : ['Shivraj Singh Chauhan']
{'score': 0.32213136553764343, 'start': 48, 'end': 58, 'answer': 'Kamal Nath'}
follow question : Who is the 16th chief minister of m. p?
short answer : ['Babulal Gaur', 'Babulal Gaur Yadav']
{'score': 0.005532736424356699, 'start': 48, 'end': 58, 'answer': 'Kamal Nath'}
follow question : Who is the 15th chief minister of m. p?
short answer : ['Uma Bharti']
{'score': 0.0027071579825133085, 'start': 48, 'end': 58, 'answer': 'Kamal Nath'}
{'rougeLsum': 54.285714285714285, 'length': 79.0, 'str_em': 66.66666666666666, 'Disambig-F1': 0.0}
{'first_doc_retrival': 0.7, 'first_title_retrival': 0.75}
rougeLsum      38.582059
length         98.850000
str_em         61.666667
Disambig-F1    49.227564
dtype: float64
first_doc_retrival      0.6750
first_title_retrival    0.9175
dtype: float64

## 성능비교 (예전데이터)

In [171]:
# 기본 라그 예전 데이터 문서 10개 검색 함수는 기본함수 answer
# first_retrival    0.675
# first_title_retrival    0.9175
import pandas as pd
import math
sf = pd.read_csv('results/basicRAG_seed24-answer-len100_results.csv')
sf=sf[sf['length']<1000][:20]
print(len(sf))
print(sf.mean())
r=sf.mean()['rougeLsum']
d=sf.mean()['Disambig-F1']
dr=math.sqrt(r*d)
print(dr)

20
rougeLsum      26.424077
length         31.200000
str_em         49.166667
Disambig-F1    44.894841
dtype: float64
34.44277482138087

In [167]:
# 답변에 답변 검색 첫번째 답변 생성은 total_answer 두번째 답변 생성은 answer
# first_doc_retrival       0.6750
# first_title_retrival     0.9175
# second_doc_retrival      0.6500
# second_title_retrival    0.8575
import pandas as pd
import math
sf = pd.read_csv('results/answer_rag_answer_results.csv')
sf=sf[sf['length']<1000][:100]
print(len(sf))
print(sf.mean())
r=sf.mean()['rougeLsum']
d=sf.mean()['Disambig-F1']
dr=math.sqrt(r*d)
print(dr)

20
Unnamed: 0      9.500000
rougeLsum      30.056829
length         19.350000
str_em         44.583333
Disambig-F1    47.346612
dtype: float64
37.723852102774856

In [172]:
# 기본 라그 예전 데이터 문서 10개 검색 함수는 기본함수 toal_answer
# first_retrival    0.675
# first_title_retrival    0.9175
import pandas as pd
import math
sf = pd.read_csv('results/basicRAG-total-seed24-len20_results.csv')
sf=sf[sf['length']<1000][:20]
print(len(sf))
print(sf.mean())
r=sf.mean()['rougeLsum']
d=sf.mean()['Disambig-F1']
dr=math.sqrt(r*d)
print(dr)

20
Unnamed: 0      9.500000
rougeLsum      38.582059
length         98.850000
str_em         61.666667
Disambig-F1    49.227564
dtype: float64
43.58096816265843

In [162]:
# 기본 라그에서 total_answer함수써서 답변 생성 후 그 답변을 다시 검색해서 total_answer로 최종 답변 생성
# first_doc_retrival       0.6750
# first_title_retrival     0.9175
# second_doc_retrival      0.6350
# second_title_retrival    0.8925
sf = pd.read_csv('results/answer_rag_0219_seed24_results.csv')
sf=sf[sf['length']<1000][:20]
print(len(sf))
print(sf.mean())
r=sf.mean()['rougeLsum']
d=sf.mean()['Disambig-F1']
dr=math.sqrt(r*d)
print(dr)

20
rougeLsum      41.618101
length         90.600000
str_em         67.083333
Disambig-F1    57.100427
dtype: float64
48.748449893849504

## 성능 비교 (새로운 데이터)

In [130]:
# 기본 라그에 문서 10개 검색 함수는 기본 함수 answer
import pandas as pd
import math
sf = pd.read_csv('results/basicRAG_seed24-len20-newdata_results.csv')
sf=sf[sf['length']<1000][:100]
print(len(sf))
print(sf.mean())
r=sf.mean()['rougeLsum']
d=sf.mean()['Disambig-F1']
dr=math.sqrt(r*d)
print(dr)

20
rougeLsum      26.424077
length         31.200000
str_em         49.166667
Disambig-F1    44.894841
dtype: float64
34.44277482138087

In [132]:
# 기본 라그에 제목 검색 10개 후 그안에서 문서 10개 검색 함수는 기본함수 answer
import pandas as pd
import math
sf = pd.read_csv('results/basicRAG_seed24-len20-title_results.csv')
sf=sf[sf['length']<1000][:100]
print(len(sf))
print(sf.mean())
r=sf.mean()['rougeLsum']
d=sf.mean()['Disambig-F1']
dr=math.sqrt(r*d)
print(dr)

20
rougeLsum      30.492810
length         27.050000
str_em         48.750000
Disambig-F1    51.680556
dtype: float64
39.697422727900765

In [129]:
# 기본 라그에 문서 10개 검색 함수는 total_answer
import pandas as pd
import math
sf = pd.read_csv('results/basicRAG_seed24-totalanswer-doc10_results.csv')
sf=sf[sf['length']<1000][:100]
print(len(sf))
print(sf.mean())
r=sf.mean()['rougeLsum']
d=sf.mean()['Disambig-F1']
dr=math.sqrt(r*d)
print(dr)

20
rougeLsum      36.529148
length         93.200000
str_em         58.333333
Disambig-F1    49.708333
dtype: float64
42.61224056875744

In [131]:
# 기본 라그에 제목 검색 10개후 그안에서 문서 10개 검색 함수는 total_answer
import pandas as pd
import math
sf = pd.read_csv('results/basicRAG_seed24-totalanswer-title10_results.csv')
sf=sf[sf['length']<1000][:100]
print(len(sf))
print(sf.mean())
r=sf.mean()['rougeLsum']
d=sf.mean()['Disambig-F1']
dr=math.sqrt(r*d)
print(dr)

20
rougeLsum      36.918206
length         92.000000
str_em         56.666667
Disambig-F1    47.319444
dtype: float64
41.796519228254525

In [156]:
def answer_2020(query, title, context):
    prompt = """
    Context information is below.
    ---------------------
    {0}
    ---------------------
    Given the context information and not prior knowledge, answer this ambiuous question.
    1. You should include in answer the content according to the various interpretations of the question
    2. When using time-related information to answer the question, only use information before February 1, 2020.
    3. If you can’t answer the question, say "Not relevant" only.
    4. The answer should be made considering the title.
    5. Each contents should include the subject, verb, predicate, object, time, and place appropriately.
    6. Answers to questions should be no longer than 3 sentences.
    Do not comment your answer and strictly follow this instructions.
    Query: {1}
    Title: {2}
    Answer:
    """.format('\n'.join(context), query, title)
    input_ids = tokenizer_gen.apply_chat_template([{"role":'user', "content":prompt}], return_tensors='pt').to(device1)

    attention_mask = (input_ids != tokenizer_gen.pad_token_id).long().to(device1)

    out = model_gen.generate(input_ids, attention_mask=attention_mask, pad_token_id=tokenizer_gen.pad_token_id, max_new_tokens = 512)
    res = tokenizer_gen.decode(out[0]).split('<|end_header_id|>')[-1] 
    return re.sub('\n|<\|eot_id\|>', '', res)

In [45]:
def answer_2020_2(query, title, context):
    prompt = """
    Context information is below.
    ---------------------
    {0}
    ---------------------
    Given the context information and not prior knowledge, answer this ambiuous question.
    1. You should include in answer the content according to the various interpretations of the question
    2. When using time-related information to answer the question, only use information before February 1, 2020.
    3. If you can’t answer the question, say "Not relevant" only.
    4. Title means topic of context, so it should be considered when making answer.
    5. Answers to questions should be no longer than 200 words.
    Do not comment your answer and strictly follow this instructions.
    Query: {1}
    Title: {2}
    Answer:
    """.format('\n'.join(context), query, title)
    input_ids = tokenizer_gen.apply_chat_template([{"role":'user', "content":prompt}], return_tensors='pt').to(device1)

    attention_mask = (input_ids != tokenizer_gen.pad_token_id).long().to(device1)

    out = model_gen.generate(input_ids, attention_mask=attention_mask, pad_token_id=tokenizer_gen.pad_token_id, max_new_tokens = 512)
    res = tokenizer_gen.decode(out[0]).split('<|end_header_id|>')[-1] 
    return re.sub('\n|<\|eot_id\|>', '', res)

In [60]:
def total_answer_2020(query, docs):
    prompt = """
    Context information is below.
    ---------------------
    {0}
    ---------------------
    Given the context information and not prior knowledge, answer this ambiuous question.
    1. Summarize all information in less than 100 characters. 
    2. You must include subject, verb, object, time, and place.
    Do not comment your answer and strictly follow this instructions.
    Query: {1}
    Answer:
    """.format('\n'.join(docs), query)
    input_ids = tokenizer_gen.apply_chat_template([{"role":'user', "content":prompt}], return_tensors='pt').to(device1)

    attention_mask = (input_ids != tokenizer_gen.pad_token_id).long().to(device1)

    out = model_gen.generate(input_ids, attention_mask=attention_mask, pad_token_id=tokenizer_gen.pad_token_id, max_new_tokens = 512)
    res = tokenizer_gen.decode(out[0]).split('<|end_header_id|>')[-1] 
    return re.sub('\n|<\|eot_id\|>', '', res)

In [58]:
# def total_answer(query, docs):
#     prompt = """
#     Context information is below.
#     ---------------------
#     {0}
#     ---------------------
#     Given the context information and not prior knowledge, answer the query.
#     1. The query is an ambiguous question.
#     2. Therefore, you must include the contents according to the various interpretations of the query in one answer by utilizing the given context.
#     3. When using time-related information to answer the question, only use information before February 1, 2020.
#     4. Each content according to the various interpretations of the query must be explained in one or two sentences.
#     5. The total answer must be 5 sentences or less.
#     Do not comment your answer and strictly follow this instructions.
#     Query: {1}
#     Answer:
#     """.format('\n'.join(docs), query)
#     input_ids = tokenizer_gen.apply_chat_template([{"role":'user', "content":prompt}], return_tensors='pt').to(device1)

#     attention_mask = (input_ids != tokenizer_gen.pad_token_id).long().to(device1)

#     out = model_gen.generate(input_ids, attention_mask=attention_mask, pad_token_id=tokenizer_gen.pad_token_id, max_new_tokens = 512)
#     res = tokenizer_gen.decode(out[0]).split('<|end_header_id|>')[-1] 
#     return re.sub('\n|<\|eot_id\|>', '', res)

In [157]:
from tqdm import tqdm
from evaluation import evaluate

set_seed(24)

stop_iteration = 20
retrival_list=[]
scores_list=[]
for idx, row in tqdm(qa_df.iterrows(), total=min([stop_iteration, len(qa_df)])):
    if idx == stop_iteration: break
    query = row['question']   
    
    retrieved_docs, doc_ids = retrieve_documents(query,10)
    ori_ans=total_answer(query, retrieved_docs)
    print('Basic ans:',ori_ans)
    
    titles,title_ids=retrieve_titles(query, 10)
    docs=[]
    first_ans=[]
    
    first_ans.append(ori_ans)
    
    for title in titles:
        text_docs=evidence_df.loc[evidence_df['title']==title,'text'].to_list()
        docs_tensor=evidence_embeddings[evidence_df['title']==title]
        title_retrieved_docs,_=retrieve_documents3(query, docs_tensor, pd.DataFrame(text_docs, columns=['text']), 10)
        while 1:
            ans=answer_2020(query,title,title_retrieved_docs)
            if "Context information is below." not in ans:
                break
        print(ans)
        if "Not relevant" in ans:
            continue
        first_ans.append(ans)
    print(first_ans)
    # final_docs, doc_titles=retrieve_inside(query, titles, 10)
    # print(final_docs, doc_titles)
    # # retrieved_docs, doc_ids = retrieve_documents2(query)
    # tmp=0
    # for doc_title in doc_titles:
    #     tmp+=match_sample_id2(idx, doc_title)
    # res=tmp/len(final_docs)
    # print("Retrival Match Rate:", res)
    # dic=dict()
    # dic['first_retrival']=res
    
    final_ans=total_answer(query,first_ans)
    # ans='. '.join(first_ans)
    print('Final ans:', ori_ans+final_ans)
    scores=evaluate([final_ans], [row.to_dict()])
    scores_list.append(scores)
    scores_df=pd.DataFrame(scores_list)
    print(scores)
    # retrival_list.append(dic)
    # retrival_df=pd.DataFrame(retrival_list)
    # print(dic)
        
scores_df=pd.DataFrame(scores_list)
scores_df.mean()

# retrival_df=pd.DataFrame(retrival_list)
# retrival_df.mean()

  0%|          | 0/20 [00:00<?, ?it/s]

Basic ans: Ali Daei holds the record for the highest number of international goals with 109 goals for Iran, surpassing Ferenc Puskás' record of 84 goals. Cristiano Ronaldo has scored 1030 goals in his career, the highest among active players, with a total of 738 goals in his international career. Miroslav Klose holds the record for most World Cup goals with 16 goals, while Gerd Müller used to be the holder of that record from 1974 until it was broken by Ronaldo in 2006. Pelé scored 77 international goals, the highest among players from outside Europe, and Jürgen Klinsmann scored 11 goals in the World Cup, the highest among players from Germany. The top goalscorers in the World Cup history are Ali Daei, Cristiano Ronaldo, Ferenc Puskás, Kunishige Kamamoto, Godfrey Chitalu, Hussein Saeed, and Zainal Abidin, among others.
Ali Daei of Iran holds the record for the highest number of international goals with 109 goals, surpassing Ferenc Puskás of Hungary who had the record for 47 years. He achieved this feat on 9 January 2000, becoming the first Asian footballer to score at least 50 goals. His record was set during his international career spanning from 1993 to 2006.
Josef Bican has the highest goals in world football with 805 goals, scoring 530 goals in 1.51 matches, with an impressive ratio of 1928-1955. This record surpasses other notable footballers, including Cristiano Ronaldo, who has scored 1030 goals, and Lionel Messi, who has scored 903 goals. Bican's achievement remains a remarkable feat in the history of football.
Ali Daei has the highest goals in world football with 109 international goals, surpassing Ferenc Puskás' record of 84 goals. He achieved this feat on 9 January 2000, becoming the first Asian footballer to score 50 international goals. Daei's impressive record remains unmatched to date.Alternatively, considering the title, the answer could be:Ali Daei has the highest number of international goals with 109 goals, surpassing Ferenc Puskás' record of 84 goals. He achieved this feat on 9 January 2000, becoming the first Asian footballer to score 50 international goals.
Miroslav Klose has the highest goals in world football with 24 goals, followed by Ronaldo with 19 goals and Gerd Müller with 13 goals. Klose achieved this feat across four consecutive tournaments between 2002 and 2014, while Ronaldo scored his goals between 1994 and 2006, and Müller scored his goals in the 1970 and 1974 World Cups. Klose's record stood for more than three decades until Grzegorz Lato broke it with 20 goals in the 1974, 1978, and 1982 World Cups.
Ali Daei has the highest goals in world football with 109 international goals. He achieved this record for Iran. As of 2 December 2019, Ali Daei holds the record for most goals scored in international football.
Christine Sinclair has the highest goals in world football with 185 international goals, scoring at a rate of 0.63 goals per match. She achieved this milestone in just under 10 years, from 2000 to 2010. As of 29 January 2020, she is one of the top all-time female goal scorers in official international football matches.
Cristiano Ronaldo has the highest goals in the UEFA Champions League with 128 goals as of 11 December 2019. He achieved this feat through his time playing for Manchester United, Real Madrid, and Juventus from 2003 to the present. This makes him the top scorer in the competition's history.
Miroslav Klose has the highest goals in the FIFA World Cup with 16 goals. He played for Germany from 2002 to 2014. This record is based on the information provided in the document "List of FIFA World Cup records and statistics/Goalscoring/Individual."
France has the highest number of own goals in favour of a team in one tournament with 2 goals, and overall, France has benefited from 6 own goals.
Miroslav Klose of Germany has the highest goals in world football with 16 goals, surpassing Ronaldo of Brazil's record of 15 goals. He achieved this milestone during the 2014 World Cup semi-final match against Brazil. Klose's impressive record has cemented his place as the all-time top scorer in the World Cup history.
["Ali Daei holds the record for the highest number of international goals with 109 goals for Iran, surpassing Ferenc Puskás' record of 84 goals. Cristiano Ronaldo has scored 1030 goals in his career, the highest among active players, with a total of 738 goals in his international career. Miroslav Klose holds the record for most World Cup goals with 16 goals, while Gerd Müller used to be the holder of that record from 1974 until it was broken by Ronaldo in 2006. Pelé scored 77 international goals, the highest among players from outside Europe, and Jürgen Klinsmann scored 11 goals in the World Cup, the highest among players from Germany. The top goalscorers in the World Cup history are Ali Daei, Cristiano Ronaldo, Ferenc Puskás, Kunishige Kamamoto, Godfrey Chitalu, Hussein Saeed, and Zainal Abidin, among others.", 'Ali Daei of Iran holds the record for the highest number of international goals with 109 goals, surpassing Ferenc Puskás of Hungary who had the record for 47 years. He achieved this feat on 9 January 2000, becoming the first Asian footballer to score at least 50 goals. His record was set during his international career spanning from 1993 to 2006.', "Josef Bican has the highest goals in world football with 805 goals, scoring 530 goals in 1.51 matches, with an impressive ratio of 1928-1955. This record surpasses other notable footballers, including Cristiano Ronaldo, who has scored 1030 goals, and Lionel Messi, who has scored 903 goals. Bican's achievement remains a remarkable feat in the history of football.", "Ali Daei has the highest goals in world football with 109 international goals, surpassing Ferenc Puskás' record of 84 goals. He achieved this feat on 9 January 2000, becoming the first Asian footballer to score 50 international goals. Daei's impressive record remains unmatched to date.Alternatively, considering the title, the answer could be:Ali Daei has the highest number of international goals with 109 goals, surpassing Ferenc Puskás' record of 84 goals. He achieved this feat on 9 January 2000, becoming the first Asian footballer to score 50 international goals.", "Miroslav Klose has the highest goals in world football with 24 goals, followed by Ronaldo with 19 goals and Gerd Müller with 13 goals. Klose achieved this feat across four consecutive tournaments between 2002 and 2014, while Ronaldo scored his goals between 1994 and 2006, and Müller scored his goals in the 1970 and 1974 World Cups. Klose's record stood for more than three decades until Grzegorz Lato broke it with 20 goals in the 1974, 1978, and 1982 World Cups.", 'Ali Daei has the highest goals in world football with 109 international goals. He achieved this record for Iran. As of 2 December 2019, Ali Daei holds the record for most goals scored in international football.', 'Christine Sinclair has the highest goals in world football with 185 international goals, scoring at a rate of 0.63 goals per match. She achieved this milestone in just under 10 years, from 2000 to 2010. As of 29 January 2020, she is one of the top all-time female goal scorers in official international football matches.', "Cristiano Ronaldo has the highest goals in the UEFA Champions League with 128 goals as of 11 December 2019. He achieved this feat through his time playing for Manchester United, Real Madrid, and Juventus from 2003 to the present. This makes him the top scorer in the competition's history.", 'Miroslav Klose has the highest goals in the FIFA World Cup with 16 goals. He played for Germany from 2002 to 2014. This record is based on the information provided in the document "List of FIFA World Cup records and statistics/Goalscoring/Individual."', 'France has the highest number of own goals in favour of a team in one tournament with 2 goals, and overall, France has benefited from 6 own goals.', "Miroslav Klose of Germany has the highest goals in world football with 16 goals, surpassing Ronaldo of Brazil's record of 15 goals. He achieved this milestone during the 2014 World Cup semi-final match against Brazil. Klose's impressive record has cemented his place as the all-time top scorer in the World Cup history."]
Final ans: Ali Daei holds the record for the highest number of international goals with 109 goals for Iran, surpassing Ferenc Puskás' record of 84 goals. Cristiano Ronaldo has scored 1030 goals in his career, the highest among active players, with a total of 738 goals in his international career. Miroslav Klose holds the record for most World Cup goals with 16 goals, while Gerd Müller used to be the holder of that record from 1974 until it was broken by Ronaldo in 2006. Pelé scored 77 international goals, the highest among players from outside Europe, and Jürgen Klinsmann scored 11 goals in the World Cup, the highest among players from Germany. The top goalscorers in the World Cup history are Ali Daei, Cristiano Ronaldo, Ferenc Puskás, Kunishige Kamamoto, Godfrey Chitalu, Hussein Saeed, and Zainal Abidin, among others.Josef Bican has the highest goals in world football with 805 goals, scoring 530 goals in 1.51 matches, with an impressive ratio of 1928-1955. Alternatively, Ali Daei holds the record for the highest number of international goals with 109 goals, surpassing Ferenc Puskás' record of 84 goals. Christine Sinclair has the highest goals in world football with 185 international goals, scoring at a rate of 0.63 goals per match. Miroslav Klose has the highest goals in the FIFA World Cup with 16 goals, surpassing Ronaldo's record of 15 goals. Cristiano Ronaldo has the highest goals in the UEFA Champions League with 128 goals.
Josef Bican has the highest goals in world football with 805 goals, scoring 530 goals in 1.51 matches, with an impressive ratio of 1928-1955. Alternatively, Ali Daei holds the record for the highest number of international goals with 109 goals, surpassing Ferenc Puskás' record of 84 goals. Christine Sinclair has the highest goals in world football with 185 international goals, scoring at a rate of 0.63 goals per match. Miroslav Klose has the highest goals in the FIFA World Cup with 16 goals, surpassing Ronaldo's record of 15 goals. Cristiano Ronaldo has the highest goals in the UEFA Champions League with 128 goals.
Who has the highest goals in world football?
["Who has the highest goals in men's world international football?", "Who has the highest goals all-time in men's football?", "Who has the highest goals in women's world international football?"]
[['Daei', 'Ali Daei'], ['Bican', 'Josef Bican'], ['Sinclair', 'Christine Sinclair']]

  5%|▌         | 1/20 [04:40<1:28:54, 280.77s/it]

follow question : Who has the highest goals in men's world international football?
short answer : ['Daei', 'Ali Daei']
{'score': 0.7461572885513306, 'start': 0, 'end': 11, 'answer': 'Josef Bican'}
follow question : Who has the highest goals all-time in men's football?
short answer : ['Bican', 'Josef Bican']
{'score': 0.19398072361946106, 'start': 0, 'end': 11, 'answer': 'Josef Bican'}
follow question : Who has the highest goals in women's world international football?
short answer : ['Sinclair', 'Christine Sinclair']
{'score': 0.9859077334403992, 'start': 291, 'end': 309, 'answer': 'Christine Sinclair'}
{'rougeLsum': 41.70616113744076, 'length': 103.0, 'str_em': 100.0, 'Disambig-F1': 66.66666666666666}
Basic ans: The original artist of "Sound of Silence" is Simon & Garfunkel, an American music duo composed of Paul Simon and Art Garfunkel. They recorded the song in March 1964, and it was initially released as a single in September 1965. The song was written by Paul Simon, and its original version was in a acoustic style, featuring Simon on vocals and guitar, and Garfunkel on vocals. The duo's version of "Sound of Silence" is considered a classic folk rock song and has been added to the National Recording Registry in the Library of Congress.
Simon & Garfunkel is the original artist of "The Sound of Silence". The song was written by Paul Simon and recorded by Simon & Garfunkel in March 1964 at Columbia Studios in New York City. It was initially released as part of their debut album, Wednesday Morning, 3 A.M., in October 1964.
The original artist of Sound of Silence is not Dami Im. Dami Im performed the song "Sound of Silence" at the Eurovision Song Contest 2016. The song was written by Anthony Egizii and David Musumeci, who are members of DNA Songs.
The original artist of "The Sound of Silence" is Paul Simon, who wrote the song. However, the electric version of the song was overdubbed by Columbia Records staff producer Tom Wilson on June 15, 1965, and released as a single in September 1965. The song was later included on the album "Sounds of Silence" by Simon & Garfunkel, released on January 17, 1966.The song was originally released as "The Sounds of Silence" on the album "Wednesday Morning, 3 A.M." in 1964. The album "Sounds of Silence" features the song "The Sound of Silence" as its opening track, which was released as a single in September 1965.
The original artist of the song "The Sound of Music" is Richard Rodgers, who composed the music. However, the original artist of the song "The Sound of Silence" is not mentioned in the provided context information. The Sound of Silence is actually a song by the American rock band The Doors, not related to the musical The Sound of Music.
The original artist of the song "This Is Me" is Keala Settle, who performed it in the film The Greatest Showman. The song was written by Benj Pasek and Justin Paul, and it won the Golden Globe Award for Best Original Song – Motion Picture in 2018. The song's success can be seen in its chart performance, where it reached number one on the UK album charts and number two in the United States.
Not relevant
The original artist of the soundtrack is James Newton Howard. He composed the music for the film, which was released on June 29, 2010. The soundtrack was produced by James Newton Howard and M. Night Shyamalan.
The Everly Brothers were not the original artists of "The Sound of Silence." The song was written and composed by Paul Simon, and it was originally recorded by Simon & Garfunkel in 1964.
The song "Still of the Night" is by the English band Whitesnake. The band Whitesnake was formed by David Coverdale, who is the lead singer and songwriter of the band. The song was written by David Coverdale and John Sykes, and it was released as a single from their self-titled album in 1987.
Not relevant
['The original artist of "Sound of Silence" is Simon & Garfunkel, an American music duo composed of Paul Simon and Art Garfunkel. They recorded the song in March 1964, and it was initially released as a single in September 1965. The song was written by Paul Simon, and its original version was in a acoustic style, featuring Simon on vocals and guitar, and Garfunkel on vocals. The duo\'s version of "Sound of Silence" is considered a classic folk rock song and has been added to the National Recording Registry in the Library of Congress.', 'Simon & Garfunkel is the original artist of "The Sound of Silence". The song was written by Paul Simon and recorded by Simon & Garfunkel in March 1964 at Columbia Studios in New York City. It was initially released as part of their debut album, Wednesday Morning, 3 A.M., in October 1964.', 'The original artist of Sound of Silence is not Dami Im. Dami Im performed the song "Sound of Silence" at the Eurovision Song Contest 2016. The song was written by Anthony Egizii and David Musumeci, who are members of DNA Songs.', 'The original artist of "The Sound of Silence" is Paul Simon, who wrote the song. However, the electric version of the song was overdubbed by Columbia Records staff producer Tom Wilson on June 15, 1965, and released as a single in September 1965. The song was later included on the album "Sounds of Silence" by Simon & Garfunkel, released on January 17, 1966.The song was originally released as "The Sounds of Silence" on the album "Wednesday Morning, 3 A.M." in 1964. The album "Sounds of Silence" features the song "The Sound of Silence" as its opening track, which was released as a single in September 1965.', 'The original artist of the song "The Sound of Music" is Richard Rodgers, who composed the music. However, the original artist of the song "The Sound of Silence" is not mentioned in the provided context information. The Sound of Silence is actually a song by the American rock band The Doors, not related to the musical The Sound of Music.', 'The original artist of the song "This Is Me" is Keala Settle, who performed it in the film The Greatest Showman. The song was written by Benj Pasek and Justin Paul, and it won the Golden Globe Award for Best Original Song – Motion Picture in 2018. The song\'s success can be seen in its chart performance, where it reached number one on the UK album charts and number two in the United States.', 'The original artist of the soundtrack is James Newton Howard. He composed the music for the film, which was released on June 29, 2010. The soundtrack was produced by James Newton Howard and M. Night Shyamalan.', 'The Everly Brothers were not the original artists of "The Sound of Silence." The song was written and composed by Paul Simon, and it was originally recorded by Simon & Garfunkel in 1964.', 'The song "Still of the Night" is by the English band Whitesnake. The band Whitesnake was formed by David Coverdale, who is the lead singer and songwriter of the band. The song was written by David Coverdale and John Sykes, and it was released as a single from their self-titled album in 1987.']
Final ans: The original artist of "Sound of Silence" is Simon & Garfunkel, an American music duo composed of Paul Simon and Art Garfunkel. They recorded the song in March 1964, and it was initially released as a single in September 1965. The song was written by Paul Simon, and its original version was in a acoustic style, featuring Simon on vocals and guitar, and Garfunkel on vocals. The duo's version of "Sound of Silence" is considered a classic folk rock song and has been added to the National Recording Registry in the Library of Congress.The original artist of "Sound of Silence" is Simon & Garfunkel, an American music duo composed of Paul Simon and Art Garfunkel. They recorded the song in March 1964, and it was initially released as a single in September 1965. The song was written by Paul Simon, and its original version was in an acoustic style, featuring Simon on vocals and guitar, and Garfunkel on vocals. However, the electric version of the song was overdubbed by Columbia Records staff producer Tom Wilson on June 15, 1965, and released as a single in September 1965. In terms of composition, the song's original artist is Paul Simon, who wrote the song.
The original artist of "Sound of Silence" is Simon & Garfunkel, an American music duo composed of Paul Simon and Art Garfunkel. They recorded the song in March 1964, and it was initially released as a single in September 1965. The song was written by Paul Simon, and its original version was in an acoustic style, featuring Simon on vocals and guitar, and Garfunkel on vocals. However, the electric version of the song was overdubbed by Columbia Records staff producer Tom Wilson on June 15, 1965, and released as a single in September 1965. In terms of composition, the song's original artist is Paul Simon, who wrote the song.
Who is the original artist of sound of silence?
['Who is the original artist of sound of silence, the song, released in 1964?', 'Who is the original artist of sound of silence, the album?', 'Who is the original artist of sound of silence, the song, released in 2016?']
[['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon'], ['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon'], ['Dami Im']]

 10%|█         | 2/20 [08:12<1:11:58, 239.90s/it]

follow question : Who is the original artist of sound of silence, the song, released in 1964?
short answer : ['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon']
{'score': 0.8430914878845215, 'start': 45, 'end': 62, 'answer': 'Simon & Garfunkel'}
follow question : Who is the original artist of sound of silence, the album?
short answer : ['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon']
{'score': 0.2371901571750641, 'start': 45, 'end': 62, 'answer': 'Simon & Garfunkel'}
follow question : Who is the original artist of sound of silence, the song, released in 2016?
short answer : ['Dami Im']
{'score': 8.468031410302501e-06, 'start': 45, 'end': 62, 'answer': 'Simon & Garfunkel'}
{'rougeLsum': 36.00000000000001, 'length': 109.0, 'str_em': 66.66666666666666, 'Disambig-F1': 66.66666666666666}
Basic ans: The first Apple iPhone was conceived by Steve Jobs in 2005, and its development began in the same year as a secretive collaboration with Cingular Wireless (now AT&T Mobility). The iPhone was first announced to the public on January 9, 2007, at the Macworld 2007 convention in San Francisco. The device was released in the United States on June 29, 2007, and was initially available in a 4 GB model priced at $499 and an 8 GB model priced at $599. The first generation iPhone was discontinued on July 15, 2008, after selling over 6 million units worldwide. The iPhone's development cost was estimated to be $150 million over a thirty-month period.
The first iPhone was conceived by Apple CEO Steve Jobs in 2005, and its development began that year. The design was expanded upon over the next two years in complete secrecy before being announced in Q1 of 2007. The iPhone was officially released on June 29, 2007.
The first iPhone beta was created in 2004, but it was never released to the public. The first iPhone was officially launched and made accessible to the public in 2007. It was released on June 29, 2007, in the US, UK, Canada, Germany, Norway, Sweden, Finland, France, Spain, Italy, and South Africa.
The first Apple iPhone was made in 2007. Apple CEO Steve Jobs unveiled the iPhone to the public on January 9, 2007, at the Macworld 2007 convention in San Francisco. The two initial models, a 4 GB model priced at US$499 and an 8 GB model at US$599, went on sale in the United States on June 29, 2007.
Not relevant.
The first iPhone was not made by Apple, but rather the first iPhone was the iPhone (1st generation), which was announced by Steve Jobs, the co-founder and CEO of Apple, on January 9, 2007, and was released to the public on June 29, 2007. It was designed and developed by Apple Inc. in Cupertino, California, USA.
The first Apple iPhone was announced by Steve Jobs, the co-founder and CEO of Apple, on January 9, 2007, at the Macworld conference in San Francisco, California. It was released to the public on June 29, 2007. The iPhone revolutionized the mobile phone industry with its multi-touch interface, mobile app store, and sleek design.
Not relevant.
Not relevant.
Not relevant. The title refers to the financial crisis of 2007-08, which is unrelated to the first Apple iPhone. The first iPhone was announced by Steve Jobs, the CEO of Apple, at the Macworld conference in San Francisco on January 9, 2007.
Not relevant.
["The first Apple iPhone was conceived by Steve Jobs in 2005, and its development began in the same year as a secretive collaboration with Cingular Wireless (now AT&T Mobility). The iPhone was first announced to the public on January 9, 2007, at the Macworld 2007 convention in San Francisco. The device was released in the United States on June 29, 2007, and was initially available in a 4 GB model priced at $499 and an 8 GB model priced at $599. The first generation iPhone was discontinued on July 15, 2008, after selling over 6 million units worldwide. The iPhone's development cost was estimated to be $150 million over a thirty-month period.", 'The first iPhone was conceived by Apple CEO Steve Jobs in 2005, and its development began that year. The design was expanded upon over the next two years in complete secrecy before being announced in Q1 of 2007. The iPhone was officially released on June 29, 2007.', 'The first iPhone beta was created in 2004, but it was never released to the public. The first iPhone was officially launched and made accessible to the public in 2007. It was released on June 29, 2007, in the US, UK, Canada, Germany, Norway, Sweden, Finland, France, Spain, Italy, and South Africa.', 'The first Apple iPhone was made in 2007. Apple CEO Steve Jobs unveiled the iPhone to the public on January 9, 2007, at the Macworld 2007 convention in San Francisco. The two initial models, a 4 GB model priced at US$499 and an 8 GB model at US$599, went on sale in the United States on June 29, 2007.', 'The first iPhone was not made by Apple, but rather the first iPhone was the iPhone (1st generation), which was announced by Steve Jobs, the co-founder and CEO of Apple, on January 9, 2007, and was released to the public on June 29, 2007. It was designed and developed by Apple Inc. in Cupertino, California, USA.', 'The first Apple iPhone was announced by Steve Jobs, the co-founder and CEO of Apple, on January 9, 2007, at the Macworld conference in San Francisco, California. It was released to the public on June 29, 2007. The iPhone revolutionized the mobile phone industry with its multi-touch interface, mobile app store, and sleek design.']
Final ans: The first Apple iPhone was conceived by Steve Jobs in 2005, and its development began in the same year as a secretive collaboration with Cingular Wireless (now AT&T Mobility). The iPhone was first announced to the public on January 9, 2007, at the Macworld 2007 convention in San Francisco. The device was released in the United States on June 29, 2007, and was initially available in a 4 GB model priced at $499 and an 8 GB model priced at $599. The first generation iPhone was discontinued on July 15, 2008, after selling over 6 million units worldwide. The iPhone's development cost was estimated to be $150 million over a thirty-month period.The first Apple iPhone was conceived by Steve Jobs in 2005, and its development began in the same year as a secretive collaboration with Cingular Wireless. The iPhone was first announced to the public on January 9, 2007, at the Macworld 2007 convention in San Francisco. It was released in the United States on June 29, 2007. The development cost was estimated to be $150 million over a thirty-month period. The iPhone's development began in 2005 and took two years to complete before being announced in Q1 of 2007.
The first Apple iPhone was conceived by Steve Jobs in 2005, and its development began in the same year as a secretive collaboration with Cingular Wireless. The iPhone was first announced to the public on January 9, 2007, at the Macworld 2007 convention in San Francisco. It was released in the United States on June 29, 2007. The development cost was estimated to be $150 million over a thirty-month period. The iPhone's development began in 2005 and took two years to complete before being announced in Q1 of 2007.
When was the first apple i phone made?
['When was the first apple i phone released?', 'When was the first apple i phone for beta testing made?', 'When was the first apple i phone 1 made?', 'When was the first apple i phone beta made?']
[['June 29, 2007'], ['2004'], ['June 29, 2007.'], ['2004.']]

 15%|█▌        | 3/20 [11:21<1:01:29, 217.04s/it]

follow question : When was the first apple i phone released?
short answer : ['June 29, 2007']
{'score': 0.1982092410326004, 'start': 311, 'end': 324, 'answer': 'June 29, 2007'}
follow question : When was the first apple i phone for beta testing made?
short answer : ['2004']
{'score': 0.0002718234609346837, 'start': 54, 'end': 58, 'answer': '2005'}
follow question : When was the first apple i phone 1 made?
short answer : ['June 29, 2007.']
{'score': 0.19793719053268433, 'start': 54, 'end': 58, 'answer': '2005'}
follow question : When was the first apple i phone beta made?
short answer : ['2004.']
{'score': 2.9085845199006144e-07, 'start': 54, 'end': 58, 'answer': '2005'}
{'rougeLsum': 34.83870967741935, 'length': 89.0, 'str_em': 50.0, 'Disambig-F1': 25.0}
Basic ans: The Weasley brothers, Bill, Charlie, Fred, and George, were played by various actors, including Richard Griffiths, David Thewlis, and the Weasley twins, James and Oliver Phelps. Richard Griffiths played the role of Uncle Vernon, but his sons, Bill and Charlie, were played by Richard's real-life sons, James and Oliver Phelps, who portrayed the Weasley twins, Fred and George. David Thewlis played the role of Professor Lupin, but his sons, James and Oliver Phelps, also played the Weasley twins, Fred and George. The Phelps twins, James and Oliver, played the Weasley twins, Fred and George, in all eight films of the series.
The Weasley brothers, Fred and George, were played by twins James and Oliver Phelps. They appeared in all eight films of the series, from "The Philosopher's Stone" in 2001 to "The Deathly Hallows – Part 1" in 2010. The twins portrayed the twins' on-screen characters, bringing the Weasley family to life in the Harry Potter film franchise.
The Weasley brothers were portrayed by actors Daniel Radcliffe as Arthur Weasley, Rupert Grint as Ron Weasley, and James and Oliver Phelps as Fred and George Weasley.
The Weasley brothers, Fred and George, were played by actors Daniel Radcliffe's friends, but more specifically, the Weasley brothers were played by actors Rupert Grint's friends, but more specifically, the Weasley brothers were played by actors Daniel Radcliffe's friends, but more specifically, the Weasley brothers were played by actors Rupert Grint's friends, but more specifically, the Weasley brothers were played by actors Daniel Radcliffe's friends, but more specifically, the Weasley brothers were played by actors Rupert Grint's friends, but more specifically, the Weasley brothers were played by actors Daniel Radcliffe's friends, but more specifically, the Weasley brothers were played by actors Rupert Grint's friends, but more specifically, the Weasley brothers were played by actors Daniel Radcliffe's friends, but more specifically, the Weasley brothers were played by actors Rupert Grint's friends, but more specifically, the Weasley brothers were played by actors Daniel Radcliffe's friends, but more specifically, the Weasley brothers were played by actors Rupert Grint's friends, but more specifically, the Weasley brothers were played by actors Daniel Radcliffe's friends, but more specifically, the Weasley brothers were played by actors Rupert Grint's friends, but more specifically, the Weasley brothers were played by actors Daniel Radcliffe's friends, but more specifically, the Weasley brothers were played by actors Rupert Grint's friends, but more specifically, the Weasley brothers were played by actors Daniel Radcliffe's friends, but more specifically, the Weasley brothers were played by actors Rupert Grint's friends, but more specifically, the Weasley brothers were played by actors Daniel Radcliffe's friends, but more specifically, the Weasley brothers were played by actors Rupert Grint's friends, but more specifically, the Weasley brothers were played by actors Daniel Radcliffe's friends, but more specifically, the Weasley brothers were played by actors Rupert Grint's friends, but more specifically, the Weasley brothers were played by actors Daniel Radcliffe's friends, but more specifically, the Weasley brothers were played by actors Rupert Grint's friends, but more specifically, the Weasley brothers were played by actors Daniel Radcliffe's friends, but more specifically, the Weasley brothers were played by actors Rupert Grint's friends, but more specifically, the Weasley brothers were played by actors Daniel Radcliffe's friends, but more specifically, the Weasley brothers were played by actors Rupert Grint's friends, but more
Not relevant.
The Everly Brothers were a real-life American country-influenced rock and roll duo, known for their steel-string acoustic guitar playing and close harmony singing, not the Weasley brothers from the Harry Potter series. The Everly Brothers consisted of Don and Phil Everly, who were raised in a musical family and gained fame in the 1950s and 1960s with hits like "Bye Bye Love" and "All I Have to Do Is Dream." They were inducted into the Rock and Roll Hall of Fame in 1986 and continued to perform and record music until their reunion concert in 1983.
The Weasley brothers were played by multiple actors in the Harry Potter film series. The roles of the Weasley brothers, including Fred and George Weasley, were played by actors Daniel Radcliffe's friends from school, Chris Rankin, and the twins, James and Oliver Phelps, who played the twins Fred and George Weasley.
Not relevant
Not relevant. The Isley Brothers are an American musical group, not characters from the Harry Potter series.
The Weasley brothers were not directly mentioned in the provided context. However, the text does mention Ron Weasley, one of the Weasley siblings, played by Rupert Grint. The Weasley family is mentioned, but specific actors playing the Weasley brothers are not provided.
Not relevant.
["The Weasley brothers, Bill, Charlie, Fred, and George, were played by various actors, including Richard Griffiths, David Thewlis, and the Weasley twins, James and Oliver Phelps. Richard Griffiths played the role of Uncle Vernon, but his sons, Bill and Charlie, were played by Richard's real-life sons, James and Oliver Phelps, who portrayed the Weasley twins, Fred and George. David Thewlis played the role of Professor Lupin, but his sons, James and Oliver Phelps, also played the Weasley twins, Fred and George. The Phelps twins, James and Oliver, played the Weasley twins, Fred and George, in all eight films of the series.", 'The Weasley brothers, Fred and George, were played by twins James and Oliver Phelps. They appeared in all eight films of the series, from "The Philosopher\'s Stone" in 2001 to "The Deathly Hallows – Part 1" in 2010. The twins portrayed the twins\' on-screen characters, bringing the Weasley family to life in the Harry Potter film franchise.', 'The Weasley brothers were portrayed by actors Daniel Radcliffe as Arthur Weasley, Rupert Grint as Ron Weasley, and James and Oliver Phelps as Fred and George Weasley.', "The Weasley brothers, Fred and George, were played by actors Daniel Radcliffe's friends, but more specifically, the Weasley brothers were played by actors Rupert Grint's friends, but more specifically, the Weasley brothers were played by actors Daniel Radcliffe's friends, but more specifically, the Weasley brothers were played by actors Rupert Grint's friends, but more specifically, the Weasley brothers were played by actors Daniel Radcliffe's friends, but more specifically, the Weasley brothers were played by actors Rupert Grint's friends, but more specifically, the Weasley brothers were played by actors Daniel Radcliffe's friends, but more specifically, the Weasley brothers were played by actors Rupert Grint's friends, but more specifically, the Weasley brothers were played by actors Daniel Radcliffe's friends, but more specifically, the Weasley brothers were played by actors Rupert Grint's friends, but more specifically, the Weasley brothers were played by actors Daniel Radcliffe's friends, but more specifically, the Weasley brothers were played by actors Rupert Grint's friends, but more specifically, the Weasley brothers were played by actors Daniel Radcliffe's friends, but more specifically, the Weasley brothers were played by actors Rupert Grint's friends, but more specifically, the Weasley brothers were played by actors Daniel Radcliffe's friends, but more specifically, the Weasley brothers were played by actors Rupert Grint's friends, but more specifically, the Weasley brothers were played by actors Daniel Radcliffe's friends, but more specifically, the Weasley brothers were played by actors Rupert Grint's friends, but more specifically, the Weasley brothers were played by actors Daniel Radcliffe's friends, but more specifically, the Weasley brothers were played by actors Rupert Grint's friends, but more specifically, the Weasley brothers were played by actors Daniel Radcliffe's friends, but more specifically, the Weasley brothers were played by actors Rupert Grint's friends, but more specifically, the Weasley brothers were played by actors Daniel Radcliffe's friends, but more specifically, the Weasley brothers were played by actors Rupert Grint's friends, but more specifically, the Weasley brothers were played by actors Daniel Radcliffe's friends, but more specifically, the Weasley brothers were played by actors Rupert Grint's friends, but more specifically, the Weasley brothers were played by actors Daniel Radcliffe's friends, but more specifically, the Weasley brothers were played by actors Rupert Grint's friends, but more", 'The Everly Brothers were a real-life American country-influenced rock and roll duo, known for their steel-string acoustic guitar playing and close harmony singing, not the Weasley brothers from the Harry Potter series. The Everly Brothers consisted of Don and Phil Everly, who were raised in a musical family and gained fame in the 1950s and 1960s with hits like "Bye Bye Love" and "All I Have to Do Is Dream." They were inducted into the Rock and Roll Hall of Fame in 1986 and continued to perform and record music until their reunion concert in 1983.', "The Weasley brothers were played by multiple actors in the Harry Potter film series. The roles of the Weasley brothers, including Fred and George Weasley, were played by actors Daniel Radcliffe's friends from school, Chris Rankin, and the twins, James and Oliver Phelps, who played the twins Fred and George Weasley.", 'The Weasley brothers were not directly mentioned in the provided context. However, the text does mention Ron Weasley, one of the Weasley siblings, played by Rupert Grint. The Weasley family is mentioned, but specific actors playing the Weasley brothers are not provided.']
Final ans: The Weasley brothers, Bill, Charlie, Fred, and George, were played by various actors, including Richard Griffiths, David Thewlis, and the Weasley twins, James and Oliver Phelps. Richard Griffiths played the role of Uncle Vernon, but his sons, Bill and Charlie, were played by Richard's real-life sons, James and Oliver Phelps, who portrayed the Weasley twins, Fred and George. David Thewlis played the role of Professor Lupin, but his sons, James and Oliver Phelps, also played the Weasley twins, Fred and George. The Phelps twins, James and Oliver, played the Weasley twins, Fred and George, in all eight films of the series.The Weasley brothers, Fred and George, were played by twins James and Oliver Phelps, who appeared in all eight films of the series. They portrayed the twins' on-screen characters, bringing the Weasley family to life in the Harry Potter film franchise. The Weasley brothers were also mentioned to be played by Daniel Radcliffe's friends, but more specifically, it is James and Oliver Phelps. The Weasley brothers, Fred and George, were played by actors Daniel Radcliffe's friends, but more specifically, the Weasley brothers were played by actors Rupert Grint's friends, but more specifically, it is James and Oliver Phelps. The Everly Brothers, a real-life American country-influenced rock and roll duo, are unrelated to the Weasley brothers from the Harry Potter series.
The Weasley brothers, Fred and George, were played by twins James and Oliver Phelps, who appeared in all eight films of the series. They portrayed the twins' on-screen characters, bringing the Weasley family to life in the Harry Potter film franchise. The Weasley brothers were also mentioned to be played by Daniel Radcliffe's friends, but more specifically, it is James and Oliver Phelps. The Weasley brothers, Fred and George, were played by actors Daniel Radcliffe's friends, but more specifically, the Weasley brothers were played by actors Rupert Grint's friends, but more specifically, it is James and Oliver Phelps. The Everly Brothers, a real-life American country-influenced rock and roll duo, are unrelated to the Weasley brothers from the Harry Potter series.
Who played the weasley brothers in harry potter?
['Who played  Bill weasley in Harry Potter and the Prisoner of Azkaban?', 'Who played percy weasley in harry potter?', 'Who played fred weasley in harry potter?', 'Who played ron weasley in harry potter?', 'Who played george weasley in harry potter?', 'Who played  Bill weasley in harry potter (2001-2011)?']
[['Richard Fish'], ['Chris Rankin'], ['James Phelps'], ['Rupert Grint'], ['Oliver Phelps'], ['Domhnall Gleeson']]
follow question : Who played  Bill weasley in Harry Potter and the Prisoner of Azkaban?
short answer : ['Richard Fish']
{'score': 4.365497807157226e-05, 'start': 60, 'end': 83, 'answer': 'James and Oliver Phelps'}
follow question : Who played percy weasley in harry potter?
short answer : ['Chris Rankin']
{'score': 0.004626841749995947, 'start': 60, 'end': 83, 'answer': 'James and Oliver Phelps'}
follow question : Who played fred weasley in harry potter?
short answer : ['James Phelps']
{'score': 0.7154062390327454, 'start': 60, 'end': 83, 'answer': 'James and Oliver Phelps'}
follow question : Who played ron weasley in harry potter?
short answer : ['Rupert Grint']
{'score': 0.18224605917930603, 'start': 60, 'end': 83, 'answer': 'James and Oliver Phelps'}
follow question : Who played george weasley in harry potter?
short answer : ['Oliver Phelps']
{'score': 0.6661038398742676, 'start': 60, 'end': 83, 'answer': 'James and Oliver Phelps'}
follow question : Who played  Bill weasley in harry potter (2001-2011)?
short answer : ['Domhnall Gleeson']

 20%|██        | 4/20 [16:12<1:05:38, 246.14s/it]

{'score': 0.000626852735877037, 'start': 60, 'end': 83, 'answer': 'James and Oliver Phelps'}
{'rougeLsum': 37.5, 'length': 120.0, 'str_em': 33.33333333333333, 'Disambig-F1': 22.22222222222222}
Basic ans: The Virginia state park system oversees 38 parks. This includes the original six parks established in 1936: Seashore State Park (now First Landing State Park), Westmoreland State Park, Staunton River State Park, Douthat State Park, Fairy Stone State Park, and Hungry Mother State Park. In addition to these original parks, the state park system has expanded to include 38 parks, with each park offering unique recreational and scenic opportunities. The parks range in size from 7 acres to over 6,900 acres and offer a variety of activities, including hiking, camping, fishing, boating, and more. Overall, the Virginia state park system provides a diverse range of outdoor recreational opportunities for visitors to enjoy.
The List of Virginia state parks contains information about 38 state parks in Virginia.  The Virginia state park system was opened on June 15, 1936, as a six-park system.  As of the information available before February 1, 2020, there are 38 state parks in Virginia.The list of state parks in Virginia includes parks such as Douthat State Park, Fairy Stone State Park, and First Landing State Park, which were established in 1933.  Some parks, like Sky Meadows State Park and Smith Mountain Lake State Park, have larger sizes, with 1,618 acres and 1,506 acres, respectively.  Other parks, like Shot Tower Historical State Park and Chippokes Plantation State Park, have smaller sizes, with 7 acres and 1,945 acres, respectively.
Not relevant, as the provided information is about the Virginia State Capitol, not state parks. However, I can provide information on the Capitol Square area, which is a part of the Virginia State Capitol. It contains several monuments, but it is not a state park. The area around the Capitol is known as Capitol Square, which contains monuments to prominent Virginians and events in Virginia, but it is not a state park.
Not relevant.
There are over 40 parks in the Richmond area, comprising more than 1,500 acres. The James River Parks System offers bike trails, hiking and nature trails, and scenic overlooks along the river's route through the city. Some of the parks in the area include Byrd Park, Maymont, Joseph Bryan Park Azalea Garden, and Forest Hill Park.Notably, the Virginia State Parks system has 16 parks, which are managed by the Virginia Department of Conservation and Recreation. These parks offer a range of outdoor activities, including hiking, camping, fishing, and boating.Some of the state parks near Richmond include:* Belle Isle State Park* Buggs Island State Park* Grayson Highlands State Park* Hungry Mother State Park* James River State Park* Kiptopeke State Park* Leesylvania State Park* New River Trail State Park* Occoneechee State Park* Pocahontas State Park* Sailor's Creek Battlefield State Park* Sailor's Creek Battlefield State Park* Shenandoah Valley State Park* York River State ParkThese parks offer a range of outdoor activities and are located within a few hours' drive of Richmond.
Not relevant to the title "Area codes 703 and 571" which discusses telephone area codes in Northern Virginia.
There is no information about state parks in Virginia in the provided context. However, Disney's America was a planned theme park in Virginia that was canceled in 1994.
Not relevant.
Not relevant.The query is about Virginia state parks, but the context information is about Kogi State in Nigeria.If the query is about the number of local government areas in Kogi State, the answer is:There are twenty-one (21) local government areas in Kogi State, which are: Adavi, Ajaokuta, Ankpa, Bassa, Dekina, Ibaji, Idah, Igalamela-Odolu, Ijumu, Kabba/Bunu, Koton Karfe, Lokoja, Mopa-Muro, Ofu, Ogori/Magongo, Okehi, Okene, Olamaboro, Omala, Yagba East, and Yagba West.If the query is about the number of senators from Kogi State, the answer is:Kogi State is represented by three senators, one from each of the three senatorial districts: Kogi East, Kogi West, and Kogi Central.If the query is about the number of notable people from Kogi State, the answer is:There are many notable people from Kogi State, including Halima Abubakar, Segun Adaju, S. A. Ajayi, Adeyemi, Joseph Benjamin, Darey - Darey Art Alade, Jaywon, Mercy Johnson, Dino Melaye, Edward David Onoja, and Praiz.
Not relevant.
Not relevant to the Battle of Philippi (West Virginia) which discusses the American Civil War and the state of West Virginia, not Virginia.
['The Virginia state park system oversees 38 parks. This includes the original six parks established in 1936: Seashore State Park (now First Landing State Park), Westmoreland State Park, Staunton River State Park, Douthat State Park, Fairy Stone State Park, and Hungry Mother State Park. In addition to these original parks, the state park system has expanded to include 38 parks, with each park offering unique recreational and scenic opportunities. The parks range in size from 7 acres to over 6,900 acres and offer a variety of activities, including hiking, camping, fishing, boating, and more. Overall, the Virginia state park system provides a diverse range of outdoor recreational opportunities for visitors to enjoy.', 'The List of Virginia state parks contains information about 38 state parks in Virginia.  The Virginia state park system was opened on June 15, 1936, as a six-park system.  As of the information available before February 1, 2020, there are 38 state parks in Virginia.The list of state parks in Virginia includes parks such as Douthat State Park, Fairy Stone State Park, and First Landing State Park, which were established in 1933.  Some parks, like Sky Meadows State Park and Smith Mountain Lake State Park, have larger sizes, with 1,618 acres and 1,506 acres, respectively.  Other parks, like Shot Tower Historical State Park and Chippokes Plantation State Park, have smaller sizes, with 7 acres and 1,945 acres, respectively.', "There are over 40 parks in the Richmond area, comprising more than 1,500 acres. The James River Parks System offers bike trails, hiking and nature trails, and scenic overlooks along the river's route through the city. Some of the parks in the area include Byrd Park, Maymont, Joseph Bryan Park Azalea Garden, and Forest Hill Park.Notably, the Virginia State Parks system has 16 parks, which are managed by the Virginia Department of Conservation and Recreation. These parks offer a range of outdoor activities, including hiking, camping, fishing, and boating.Some of the state parks near Richmond include:* Belle Isle State Park* Buggs Island State Park* Grayson Highlands State Park* Hungry Mother State Park* James River State Park* Kiptopeke State Park* Leesylvania State Park* New River Trail State Park* Occoneechee State Park* Pocahontas State Park* Sailor's Creek Battlefield State Park* Sailor's Creek Battlefield State Park* Shenandoah Valley State Park* York River State ParkThese parks offer a range of outdoor activities and are located within a few hours' drive of Richmond.", "There is no information about state parks in Virginia in the provided context. However, Disney's America was a planned theme park in Virginia that was canceled in 1994."]
Final ans: The Virginia state park system oversees 38 parks. This includes the original six parks established in 1936: Seashore State Park (now First Landing State Park), Westmoreland State Park, Staunton River State Park, Douthat State Park, Fairy Stone State Park, and Hungry Mother State Park. In addition to these original parks, the state park system has expanded to include 38 parks, with each park offering unique recreational and scenic opportunities. The parks range in size from 7 acres to over 6,900 acres and offer a variety of activities, including hiking, camping, fishing, boating, and more. Overall, the Virginia state park system provides a diverse range of outdoor recreational opportunities for visitors to enjoy.The Virginia state park system oversees 38 parks, offering a diverse range of outdoor recreational opportunities for visitors to enjoy. As of the information available before February 1, 2020, there are 38 state parks in Virginia. The Virginia state park system was opened on June 15, 1936, as a six-park system, but has expanded to include 38 parks. The list of state parks in Virginia includes parks such as Douthat State Park, Fairy Stone State Park, and First Landing State Park, which were established in 1933. Additionally, there are 16 parks managed by the Virginia Department of Conservation and Recreation, offering a range of outdoor activities.
The Virginia state park system oversees 38 parks, offering a diverse range of outdoor recreational opportunities for visitors to enjoy. As of the information available before February 1, 2020, there are 38 state parks in Virginia. The Virginia state park system was opened on June 15, 1936, as a six-park system, but has expanded to include 38 parks. The list of state parks in Virginia includes parks such as Douthat State Park, Fairy Stone State Park, and First Landing State Park, which were established in 1933. Additionally, there are 16 parks managed by the Virginia Department of Conservation and Recreation, offering a range of outdoor activities.
How many state parks are there in virginia?
['How many state parks are there in virginia in 1936?', 'How many state parks are there in virginia in 2016?', 'How many state parks were there when the state park system formed in Virginia?', 'How many state parks were there in Virginia as of 2016?']
[['six'], ['38'], ['6'], ['38']]

 25%|██▌       | 5/20 [20:15<1:01:12, 244.80s/it]

follow question : How many state parks are there in virginia in 1936?
short answer : ['six']
{'score': 0.20596492290496826, 'start': 296, 'end': 299, 'answer': 'six'}
follow question : How many state parks are there in virginia in 2016?
short answer : ['38']
{'score': 1.3425092504348868e-07, 'start': 40, 'end': 42, 'answer': '38'}
follow question : How many state parks were there when the state park system formed in Virginia?
short answer : ['6']
{'score': 0.9115836024284363, 'start': 296, 'end': 299, 'answer': 'six'}
follow question : How many state parks were there in Virginia as of 2016?
short answer : ['38']
{'score': 2.774912566394505e-08, 'start': 40, 'end': 42, 'answer': '38'}
{'rougeLsum': 41.111111111111114, 'length': 106.0, 'str_em': 100.0, 'Disambig-F1': 75.0}
Basic ans: The opening ceremony of the 2018 UEFA Champions League Final featured English singer Dua Lipa, who performed with Jamaican rapper Sean Paul, and the UEFA Champions League Anthem by Slovenian–Croatian cello duo 2Cellos. The annual UEFA Champions Festival was held between 24–27 May 2018 at the Kiev city centre. The 2018 UEFA Champions League Final match itself did not have a halftime show or entertainment, but it featured a performance by the UEFA Champions League Anthem before the match. The anthem is performed by London's Royal Philharmonic Orchestra and sung by the Academy of St. Martin in the Fields, and it is played before each UEFA Champions League game as the two teams are lined up. The anthem's chorus is played before each UEFA Champions League game as the two teams are lined up, as well as at the beginning and end of television broadcasts of the matches.
The opening ceremony preceding the final was performed by English singer Dua Lipa, with Jamaican rapper Sean Paul as a special guest to perform their collaborative song, "No Lie". The UEFA Champions League Anthem was performed by Slovenian–Croatian cello duo 2Cellos. The match began with Liverpool's kickoff and the team's successive attacks to counter Madrid's slower, possession-based buildup.
Not relevant
The instrumental version of the Champions League anthem was played at the 2018 final held in Kiev, by 2Cellos.
The 2018 UEFA Champions League Final took place on 26 May 2018, and it was between Real Madrid and Liverpool. However, the information about the performers at the 2018 UEFA Champions League Final is not available in the provided context.
Not relevant
Not relevant.
Not relevant.
Not relevant, the document provides information about the 2016-2017 UEFA Champions League group stage, which ended on 7 December 2016, and does not include information about the 2018 UEFA Champions League final.
Lyon performed at the champions league final 2018 and won the title for the sixth time. The match took place on May 16, 2018, at the Valerangi Stadium in Kiev, Ukraine.
Not relevant
["The opening ceremony of the 2018 UEFA Champions League Final featured English singer Dua Lipa, who performed with Jamaican rapper Sean Paul, and the UEFA Champions League Anthem by Slovenian–Croatian cello duo 2Cellos. The annual UEFA Champions Festival was held between 24–27 May 2018 at the Kiev city centre. The 2018 UEFA Champions League Final match itself did not have a halftime show or entertainment, but it featured a performance by the UEFA Champions League Anthem before the match. The anthem is performed by London's Royal Philharmonic Orchestra and sung by the Academy of St. Martin in the Fields, and it is played before each UEFA Champions League game as the two teams are lined up. The anthem's chorus is played before each UEFA Champions League game as the two teams are lined up, as well as at the beginning and end of television broadcasts of the matches.", 'The opening ceremony preceding the final was performed by English singer Dua Lipa, with Jamaican rapper Sean Paul as a special guest to perform their collaborative song, "No Lie". The UEFA Champions League Anthem was performed by Slovenian–Croatian cello duo 2Cellos. The match began with Liverpool\'s kickoff and the team\'s successive attacks to counter Madrid\'s slower, possession-based buildup.', 'The instrumental version of the Champions League anthem was played at the 2018 final held in Kiev, by 2Cellos.', 'The 2018 UEFA Champions League Final took place on 26 May 2018, and it was between Real Madrid and Liverpool. However, the information about the performers at the 2018 UEFA Champions League Final is not available in the provided context.', 'Lyon performed at the champions league final 2018 and won the title for the sixth time. The match took place on May 16, 2018, at the Valerangi Stadium in Kiev, Ukraine.']
Final ans: The opening ceremony of the 2018 UEFA Champions League Final featured English singer Dua Lipa, who performed with Jamaican rapper Sean Paul, and the UEFA Champions League Anthem by Slovenian–Croatian cello duo 2Cellos. The annual UEFA Champions Festival was held between 24–27 May 2018 at the Kiev city centre. The 2018 UEFA Champions League Final match itself did not have a halftime show or entertainment, but it featured a performance by the UEFA Champions League Anthem before the match. The anthem is performed by London's Royal Philharmonic Orchestra and sung by the Academy of St. Martin in the Fields, and it is played before each UEFA Champions League game as the two teams are lined up. The anthem's chorus is played before each UEFA Champions League game as the two teams are lined up, as well as at the beginning and end of television broadcasts of the matches.The UEFA Champions League Final took place on 26 May 2018, and it was between Real Madrid and Liverpool. The information about the performers at the 2018 UEFA Champions League Final is not available in the provided context. However, the UEFA Champions League Anthem was performed by London's Royal Philharmonic Orchestra and sung by the Academy of St. Martin in the Fields, and it is played before each UEFA Champions League game as the two teams are lined up. Lyon performed at the champions league final 2018 and won the title for the sixth time, but this information is not related to the 26 May 2018 final. The opening ceremony preceding the final was performed by English singer Dua Lipa, with Jamaican rapper Sean Paul as a special guest to perform their collaborative song, "No Lie".
The UEFA Champions League Final took place on 26 May 2018, and it was between Real Madrid and Liverpool. The information about the performers at the 2018 UEFA Champions League Final is not available in the provided context. However, the UEFA Champions League Anthem was performed by London's Royal Philharmonic Orchestra and sung by the Academy of St. Martin in the Fields, and it is played before each UEFA Champions League game as the two teams are lined up. Lyon performed at the champions league final 2018 and won the title for the sixth time, but this information is not related to the 26 May 2018 final. The opening ceremony preceding the final was performed by English singer Dua Lipa, with Jamaican rapper Sean Paul as a special guest to perform their collaborative song, "No Lie".
Who performed at the champions league final 2018?
['Who are the teams that performed in competition at the champions league final 2018?', 'Who performed best at the champions league final 2018, winning man of the match?', 'Who performed at the opening ceremony of the champions league final 2018?', 'Who performed the anthem at the champions league final 2018?']
[['Real Madrid and Liverpool', 'Liverpool', 'Real Madrid'], ['Gareth Bale', 'Bale'], ['Dua Lipa', 'Sean Paul', 'Dua Lipa and Sean Paul'], ['2Cellos', 'Luka Šulić and Stjepan Hauser', 'Luka Šulić', '2CΞLLOS', 'Stjepan Hauser']]

 30%|███       | 6/20 [22:55<50:26, 216.18s/it]

follow question : Who are the teams that performed in competition at the champions league final 2018?
short answer : ['Real Madrid and Liverpool', 'Liverpool', 'Real Madrid']
{'score': 0.3865434527397156, 'start': 78, 'end': 103, 'answer': 'Real Madrid and Liverpool'}
follow question : Who performed best at the champions league final 2018, winning man of the match?
short answer : ['Gareth Bale', 'Bale']
{'score': 0.1506006419658661, 'start': 461, 'end': 465, 'answer': 'Lyon'}
follow question : Who performed at the opening ceremony of the champions league final 2018?
short answer : ['Dua Lipa', 'Sean Paul', 'Dua Lipa and Sean Paul']
{'score': 0.8617753386497498, 'start': 684, 'end': 692, 'answer': 'Dua Lipa'}
follow question : Who performed the anthem at the champions league final 2018?
short answer : ['2Cellos', 'Luka Šulić and Stjepan Hauser', 'Luka Šulić', '2CΞLLOS', 'Stjepan Hauser']
{'score': 0.46240338683128357, 'start': 283, 'end': 320, 'answer': "London's Royal Philharmonic Orchestra"}
{'rougeLsum': 44.642857142857146, 'length': 136.0, 'str_em': 50.0, 'Disambig-F1': 50.0}
Basic ans: Harlan was killed by Louise with a gunshot, and later it is revealed that she was motivated by a past experience of being raped, which is hinted to have happened in Texas.
Louise Sawyer killed the man, Harlan, in self-defense after he attempted to rape Thelma Dickinson. This event occurs in a roadhouse bar parking lot, and the exact time is not specified. The location is a roadhouse bar, likely in Oklahoma, where the women had stopped for a drink.
The album "Come Thelma & Louise" by Giorgia does not directly relate to the movie "Thelma and Louise" as its title might suggest. However, considering the title and the information provided, it is more likely that the album's title is inspired by the 1991 American crime drama film "Thelma and Louise," which features two women who go on a road trip and encounter various challenges. Not relevant to the question of who killed the man in the movie, as the album's content does not directly address this topic.
Not relevant.
The man in the movie "Thelma and Louise" was killed by a couple, but it's a work of fiction, not a real-life case. The couple in the movie, Thelma and Louise, do not actually kill a man, they are on the run from the law and eventually meet a tragic end.
Ted Bundy killed the man in the film "Thelma and Louise" is not relevant to the context of the title "Ted Bundy". However, in the film "Thelma and Louise", the character who is murdered is actually the husband of Thelma, not a man. The correct answer is not relevant to the context of the title "Ted Bundy".
Not relevant.
Not relevant.
The Louvin Brothers were an American musical duo, not the characters from the movie Thelma and Louise. However, considering the title "The Louvin Brothers" and the provided context, the answer to the question is not relevant to the movie Thelma and Louise.
Not relevant.
Not relevant.
['Harlan was killed by Louise with a gunshot, and later it is revealed that she was motivated by a past experience of being raped, which is hinted to have happened in Texas.', 'Louise Sawyer killed the man, Harlan, in self-defense after he attempted to rape Thelma Dickinson. This event occurs in a roadhouse bar parking lot, and the exact time is not specified. The location is a roadhouse bar, likely in Oklahoma, where the women had stopped for a drink.', 'The man in the movie "Thelma and Louise" was killed by a couple, but it\'s a work of fiction, not a real-life case. The couple in the movie, Thelma and Louise, do not actually kill a man, they are on the run from the law and eventually meet a tragic end.', 'Ted Bundy killed the man in the film "Thelma and Louise" is not relevant to the context of the title "Ted Bundy". However, in the film "Thelma and Louise", the character who is murdered is actually the husband of Thelma, not a man. The correct answer is not relevant to the context of the title "Ted Bundy".', 'The Louvin Brothers were an American musical duo, not the characters from the movie Thelma and Louise. However, considering the title "The Louvin Brothers" and the provided context, the answer to the question is not relevant to the movie Thelma and Louise.']
Final ans: Harlan was killed by Louise with a gunshot, and later it is revealed that she was motivated by a past experience of being raped, which is hinted to have happened in Texas.Harlan was killed by Louise in self-defense after he attempted to rape Thelma Dickinson. This event occurred in a roadhouse bar parking lot, likely in Oklahoma, where the women had stopped for a drink. Louise's motivation for killing Harlan stemmed from a past experience of being raped, which is hinted to have happened in Texas. In the movie, Thelma and Louise, the character who is murdered is actually the husband of Thelma, not a man. The correct answer is Louise, who killed Harlan in self-defense.
Harlan was killed by Louise in self-defense after he attempted to rape Thelma Dickinson. This event occurred in a roadhouse bar parking lot, likely in Oklahoma, where the women had stopped for a drink. Louise's motivation for killing Harlan stemmed from a past experience of being raped, which is hinted to have happened in Texas. In the movie, Thelma and Louise, the character who is murdered is actually the husband of Thelma, not a man. The correct answer is Louise, who killed Harlan in self-defense.
Who killed the man in thelma and louise?
['Which character killed the man in thelma and louise?', 'Which actor killed the man in thelma and louise?', 'Who is the character that kills Harlan in the film Thelma and Louise?', 'Who is the actor of the character that killed a man in the film Thelma and Louise?']
[['Louise Elizabeth Sawyer', 'Louise'], ['Susan Sarandon', 'Susan Abigail Sarandon'], ['Louise Elizabeth Sawyer', 'Louise'], ['Susan Sarandon']]

 35%|███▌      | 7/20 [25:12<41:12, 190.22s/it]

follow question : Which character killed the man in thelma and louise?
short answer : ['Louise Elizabeth Sawyer', 'Louise']
{'score': 0.25649020075798035, 'start': 462, 'end': 468, 'answer': 'Louise'}
follow question : Which actor killed the man in thelma and louise?
short answer : ['Susan Sarandon', 'Susan Abigail Sarandon']
{'score': 0.031005509197711945, 'start': 462, 'end': 468, 'answer': 'Louise'}
follow question : Who is the character that kills Harlan in the film Thelma and Louise?
short answer : ['Louise Elizabeth Sawyer', 'Louise']
{'score': 0.35785984992980957, 'start': 462, 'end': 468, 'answer': 'Louise'}
follow question : Who is the actor of the character that killed a man in the film Thelma and Louise?
short answer : ['Susan Sarandon']
{'score': 3.4260934089758166e-09, 'start': 462, 'end': 468, 'answer': 'Louise'}
{'rougeLsum': 22.81879194630872, 'length': 85.0, 'str_em': 50.0, 'Disambig-F1': 50.0}
Basic ans: Charlie Kelly is played by Charlie Day, and his character is a former co-owner at Paddy's Pub and a childhood friend of Mac and Dennis. Charlie is also the janitor at the pub, known for his illiteracy and various psychological problems, including anger management issues and possible borderline personality disorder. He is often seen screaming to get his point across and referring to the dirty work of the bar as "Charlie work". Charlie's intentions are often pure, but his plans almost always end up affecting the entire plotline in a negative way. Charlie is a central character in the show, and his antics and actions drive many of the plotlines.
Charlie Kelly is played by Charlie Day. He is a main character in the show and a childhood friend of Mac and Dennis. Charlie is known for his antics, his illiteracy, and his various psychological problems.
Charlie Kelly is played by Charlie Day. Charlie Kelly is a main character in the show, and Charlie Day is the actor who portrays him. Charlie Day is a main cast member and a key part of the show's ensemble.
Charlie Kelly, a character from the TV show "It's Always Sunny in Philadelphia," is played by actor Charlie Day, but in the context of Charlie and the Chocolate Factory, Charlie Bucket is the main character, and he is played by different actors in different adaptations, including Peter Ostrum in the 1971 film and Freddie Highmore in the 2005 film.
Not relevant.
Not relevant.
Not relevant.
Not relevant.
Not relevant.
Not relevant.
Not relevant
['Charlie Kelly is played by Charlie Day, and his character is a former co-owner at Paddy\'s Pub and a childhood friend of Mac and Dennis. Charlie is also the janitor at the pub, known for his illiteracy and various psychological problems, including anger management issues and possible borderline personality disorder. He is often seen screaming to get his point across and referring to the dirty work of the bar as "Charlie work". Charlie\'s intentions are often pure, but his plans almost always end up affecting the entire plotline in a negative way. Charlie is a central character in the show, and his antics and actions drive many of the plotlines.', 'Charlie Kelly is played by Charlie Day. He is a main character in the show and a childhood friend of Mac and Dennis. Charlie is known for his antics, his illiteracy, and his various psychological problems.', "Charlie Kelly is played by Charlie Day. Charlie Kelly is a main character in the show, and Charlie Day is the actor who portrays him. Charlie Day is a main cast member and a key part of the show's ensemble.", 'Charlie Kelly, a character from the TV show "It\'s Always Sunny in Philadelphia," is played by actor Charlie Day, but in the context of Charlie and the Chocolate Factory, Charlie Bucket is the main character, and he is played by different actors in different adaptations, including Peter Ostrum in the 1971 film and Freddie Highmore in the 2005 film.']
Final ans: Charlie Kelly is played by Charlie Day, and his character is a former co-owner at Paddy's Pub and a childhood friend of Mac and Dennis. Charlie is also the janitor at the pub, known for his illiteracy and various psychological problems, including anger management issues and possible borderline personality disorder. He is often seen screaming to get his point across and referring to the dirty work of the bar as "Charlie work". Charlie's intentions are often pure, but his plans almost always end up affecting the entire plotline in a negative way. Charlie is a central character in the show, and his antics and actions drive many of the plotlines.Charlie Kelly is played by actor Charlie Day. Charlie Kelly is a main character in the show, and Charlie Day is the actor who portrays him. Charlie Day is a main cast member and a key part of the show's ensemble. Charlie Kelly is a character from the TV show "It's Always Sunny in Philadelphia," and he is played by actor Charlie Day. Charlie Kelly is known for his antics, his illiteracy, and his various psychological problems, which often drive the plotlines of the show.
Charlie Kelly is played by actor Charlie Day. Charlie Kelly is a main character in the show, and Charlie Day is the actor who portrays him. Charlie Day is a main cast member and a key part of the show's ensemble. Charlie Kelly is a character from the TV show "It's Always Sunny in Philadelphia," and he is played by actor Charlie Day. Charlie Kelly is known for his antics, his illiteracy, and his various psychological problems, which often drive the plotlines of the show.
Who plays charlie on it's always sunny?
["Who does Charlie Day play on It's Always Sunny in Philadelphia?", "Who plays Charlie Kelly on It's Always Sunny in Philadelphia?"]
[['Charlie Kelly'], ['Charlie Day']]

 40%|████      | 8/20 [27:15<33:45, 168.76s/it]

follow question : Who does Charlie Day play on It's Always Sunny in Philadelphia?
short answer : ['Charlie Kelly']
{'score': 0.6318163871765137, 'start': 0, 'end': 13, 'answer': 'Charlie Kelly'}
follow question : Who plays Charlie Kelly on It's Always Sunny in Philadelphia?
short answer : ['Charlie Day']
{'score': 0.7712142467498779, 'start': 33, 'end': 44, 'answer': 'Charlie Day'}
{'rougeLsum': 38.028169014084504, 'length': 85.0, 'str_em': 100.0, 'Disambig-F1': 100.0}
Basic ans: The Los Angeles Lakers have won the NBA Finals 16 times. This includes their championships in Minneapolis and Los Angeles, with the most recent one being in 2010. They have appeared in the NBA Finals a total of 31 times, making them one of the most successful teams in NBA history. The Lakers have won championships in five different decades, including the 1940s, 1950s, 1970s, 1980s, and 2000s. Their 16 championships are second only to the Boston Celtics' 17 championships.
The Los Angeles Lakers have won the NBA Finals 16 times. This includes their championships in 1949, 1950, 1952, 1953, 1954, 1972, 1980, 1982, 1985, 1987, 1988, 2000, 2001, 2002, 2009, and 2010. These championships were won under the leadership of various players and coaches, including George Mikan, Elgin Baylor, Jerry West, Magic Johnson, Shaquille O'Neal, and Kobe Bryant.
The Los Angeles Lakers have won the NBA Finals 17 times. Their most recent championship was in 2020, defeating the Miami Heat in the Finals. They have a long history of success, with their first championship in 1949 and their most championships won by any team in the league.
The Los Angeles Lakers have won the NBA Finals 16 times, with their most recent victory being in 2010. This championship win was their 16th overall and their 11th since moving from Minneapolis in 1960.
The Los Angeles Lakers have won the NBA Finals five times, including their third consecutive championship in the 2001 NBA Finals. They have a total of 17 NBA championships. The Lakers' 2001 NBA Finals victory was their 11th overall championship and their third consecutive title from 2000 to 2002.
The Los Angeles Lakers have won the NBA Finals 15 times. This includes their victory in the 2009 NBA Finals, where they defeated the Orlando Magic 4-1. Their previous titles include the 1950, 1952, 1953, 1954, 1972, 1980, 1982, 1985, 1987, 1988, 2000, 2001, 2002, and 2009 championships.
The Los Angeles Lakers have won the NBA Finals six times. The most recent championship was in 2020, but the question only considers information before February 1, 2020. The Lakers have won the finals in 1980, 1982, 1985, 1987, 1988, and 2000.
The Los Angeles Lakers have won the NBA Finals 17 times. The 2002 NBA Finals was the 56th edition of the championship series, and the Lakers won it by sweeping the New Jersey Nets 4-0. This was the Lakers' 14th NBA championship and third consecutive NBA championship.
The Los Angeles Lakers have won the NBA Finals six times, but not in the 2017 NBA Finals. The Warriors defeated the Cavaliers in the 2017 NBA Finals. The Lakers last won the championship in 2020, not in 2017.
The Los Angeles Kings have won the Stanley Cup 2 times, in 2012 and 2014. The Kings have appeared in the Stanley Cup Finals 3 times, winning the championship in 2012 and losing in 2013 and 2014.
The information provided is about the Cricket World Cup finals, not the Los Angeles Lakers. The Lakers are a professional basketball team and their achievements are not mentioned in the provided context.
["The Los Angeles Lakers have won the NBA Finals 16 times. This includes their championships in Minneapolis and Los Angeles, with the most recent one being in 2010. They have appeared in the NBA Finals a total of 31 times, making them one of the most successful teams in NBA history. The Lakers have won championships in five different decades, including the 1940s, 1950s, 1970s, 1980s, and 2000s. Their 16 championships are second only to the Boston Celtics' 17 championships.", "The Los Angeles Lakers have won the NBA Finals 16 times. This includes their championships in 1949, 1950, 1952, 1953, 1954, 1972, 1980, 1982, 1985, 1987, 1988, 2000, 2001, 2002, 2009, and 2010. These championships were won under the leadership of various players and coaches, including George Mikan, Elgin Baylor, Jerry West, Magic Johnson, Shaquille O'Neal, and Kobe Bryant.", 'The Los Angeles Lakers have won the NBA Finals 17 times. Their most recent championship was in 2020, defeating the Miami Heat in the Finals. They have a long history of success, with their first championship in 1949 and their most championships won by any team in the league.', 'The Los Angeles Lakers have won the NBA Finals 16 times, with their most recent victory being in 2010. This championship win was their 16th overall and their 11th since moving from Minneapolis in 1960.', "The Los Angeles Lakers have won the NBA Finals five times, including their third consecutive championship in the 2001 NBA Finals. They have a total of 17 NBA championships. The Lakers' 2001 NBA Finals victory was their 11th overall championship and their third consecutive title from 2000 to 2002.", 'The Los Angeles Lakers have won the NBA Finals 15 times. This includes their victory in the 2009 NBA Finals, where they defeated the Orlando Magic 4-1. Their previous titles include the 1950, 1952, 1953, 1954, 1972, 1980, 1982, 1985, 1987, 1988, 2000, 2001, 2002, and 2009 championships.', 'The Los Angeles Lakers have won the NBA Finals six times. The most recent championship was in 2020, but the question only considers information before February 1, 2020. The Lakers have won the finals in 1980, 1982, 1985, 1987, 1988, and 2000.', "The Los Angeles Lakers have won the NBA Finals 17 times. The 2002 NBA Finals was the 56th edition of the championship series, and the Lakers won it by sweeping the New Jersey Nets 4-0. This was the Lakers' 14th NBA championship and third consecutive NBA championship.", 'The Los Angeles Lakers have won the NBA Finals six times, but not in the 2017 NBA Finals. The Warriors defeated the Cavaliers in the 2017 NBA Finals. The Lakers last won the championship in 2020, not in 2017.', 'The Los Angeles Kings have won the Stanley Cup 2 times, in 2012 and 2014. The Kings have appeared in the Stanley Cup Finals 3 times, winning the championship in 2012 and losing in 2013 and 2014.', 'The information provided is about the Cricket World Cup finals, not the Los Angeles Lakers. The Lakers are a professional basketball team and their achievements are not mentioned in the provided context.']
Final ans: The Los Angeles Lakers have won the NBA Finals 16 times. This includes their championships in Minneapolis and Los Angeles, with the most recent one being in 2010. They have appeared in the NBA Finals a total of 31 times, making them one of the most successful teams in NBA history. The Lakers have won championships in five different decades, including the 1940s, 1950s, 1970s, 1980s, and 2000s. Their 16 championships are second only to the Boston Celtics' 17 championships.The Los Angeles Lakers have won the NBA Finals 16 times, according to some information. This includes their championships in Minneapolis and Los Angeles, with the most recent one being in 2010. However, another source states that they have won the NBA Finals 17 times, with their most recent championship in 2020. They have appeared in the NBA Finals a total of 31 times, making them one of the most successful teams in NBA history. Their championships were won under the leadership of various players and coaches, including George Mikan, Elgin Baylor, Jerry West, Magic Johnson, Shaquille O'Neal, and Kobe Bryant.
The Los Angeles Lakers have won the NBA Finals 16 times, according to some information. This includes their championships in Minneapolis and Los Angeles, with the most recent one being in 2010. However, another source states that they have won the NBA Finals 17 times, with their most recent championship in 2020. They have appeared in the NBA Finals a total of 31 times, making them one of the most successful teams in NBA history. Their championships were won under the leadership of various players and coaches, including George Mikan, Elgin Baylor, Jerry West, Magic Johnson, Shaquille O'Neal, and Kobe Bryant.
How many times have the lakers won the finals?
['As of 2017, how many times have the lakers won the finals?', 'As of 2016, how many times have the Lakers won the finals?', 'As of 2015, how many times have the Lakers won the finals?']
[['16'], ['16'], ['16']]

 45%|████▌     | 9/20 [31:11<34:48, 189.88s/it]

follow question : As of 2017, how many times have the lakers won the finals?
short answer : ['16']
{'score': 0.47165924310684204, 'start': 47, 'end': 49, 'answer': '16'}
follow question : As of 2016, how many times have the Lakers won the finals?
short answer : ['16']
{'score': 0.6305146813392639, 'start': 47, 'end': 49, 'answer': '16'}
follow question : As of 2015, how many times have the Lakers won the finals?
short answer : ['16']
{'score': 0.5757028460502625, 'start': 47, 'end': 49, 'answer': '16'}
{'rougeLsum': 38.35616438356165, 'length': 101.0, 'str_em': 100.0, 'Disambig-F1': 100.0}
Basic ans: The Indian National Congress is in power in the states of Punjab, Chhattisgarh, Rajasthan, and Madhya Pradesh, where the party has a majority support. In addition, it shares power in the states of Maharashtra and Jharkhand as a junior ally with other parties. The party also governs the union territory of Puducherry in an alliance with the Dravida Munnetra Kazhagam. As of July 2019, the party is in power in six legislative assemblies: Punjab, Rajasthan, Chhattisgarh, Madhya Pradesh, Maharashtra, and Puducherry.
The Indian National Congress is currently in power in 7 states in India, including Punjab, Chhattisgarh, Rajasthan, Madhya Pradesh, Maharashtra (as part of the Maha Vikas Aghadi), and the union territory of Puducherry, as well as Jharkhand. These states have a total of 7 legislative assemblies where Congress has a majority or is in power as a junior ally. The Congress-led United Progressive Alliance (UPA) government has been formed in these states.
The query "How many states in India are under Congress?" is not relevant to the provided context information, which focuses on the list of presidents of the Indian National Congress. The content does not provide information on states under Congress but rather on the history and leadership of the party.
The INC party is the ruling party in 6 states in India, including Andhra Pradesh, Chhattisgarh, Delhi is not under congress but INC is in some states, Punjab, Puducherry, and Telangana is not under congress but INC is in some states and Telangana, and Telangana is not under congress but INC is in some states. The INC party is also in opposition in some states, including Andhra Pradesh is not the case, Arunachal Pradesh, Assam, Bihar, Goa, Gujarat, Haryana, Himachal Pradesh, Jharkhand, Karnataka, Kerala, Madhya Pradesh, Maharashtra, Manipur, Meghalaya, Mizoram, Nagaland, Odisha, Rajasthan, Sikkim, Tamil Nadu, Telangana is not the case, Tripura, Uttar Pradesh, Uttarakhand, and West Bengal.
Not relevant. The given information is about the capitals of India, not the number of states under the Congress party.
The Indian National Congress has been the ruling party in 12 out of the 18 chief ministers listed in the document. These chief ministers served in the states of Madhya Pradesh, which is one of the states in India. The duration of their tenure varies, with the first Congress chief minister being Ravishankar Shukla in 1956 and the most recent being Kamal Nath in 2018.
Not relevant.
The information provided is about the union affiliation by U.S. state, not India. Therefore, the answer is Not relevant.
The Indian National Congress has a significant presence in the Rajya Sabha from Assam, with a total of 6 members, which is the majority of the 7 seats allocated to the state. The members include Dr. Manmohan Singh, who served 5 terms, and Ranee Narah, who is currently a member. The other members of the Congress party in the Rajya Sabha from Assam are Dr. Sanjay Sinh, Dr. Jayashree Goswami Mahanta, Dr. Bhubaneswar Kalita, and Ripun Bora.
The Indian National Congress is represented in the Rajya Sabha from the following states: Arunachal Pradesh, Assam, Bihar, Chhattisgarh, Gujarat, Haryana, Himachal Pradesh, Jammu and Kashmir, Jharkhand, Madhya Pradesh, Maharashtra, Meghalaya, Mizoram, Odisha, Punjab, Rajasthan, Sikkim, Tamil Nadu, Telangana, Tripura, Uttar Pradesh, Uttarakhand, West Bengal, and Andhra Pradesh. The party has a total of 16 members in the Rajya Sabha.
Not relevant
['The Indian National Congress is in power in the states of Punjab, Chhattisgarh, Rajasthan, and Madhya Pradesh, where the party has a majority support. In addition, it shares power in the states of Maharashtra and Jharkhand as a junior ally with other parties. The party also governs the union territory of Puducherry in an alliance with the Dravida Munnetra Kazhagam. As of July 2019, the party is in power in six legislative assemblies: Punjab, Rajasthan, Chhattisgarh, Madhya Pradesh, Maharashtra, and Puducherry.', 'The Indian National Congress is currently in power in 7 states in India, including Punjab, Chhattisgarh, Rajasthan, Madhya Pradesh, Maharashtra (as part of the Maha Vikas Aghadi), and the union territory of Puducherry, as well as Jharkhand. These states have a total of 7 legislative assemblies where Congress has a majority or is in power as a junior ally. The Congress-led United Progressive Alliance (UPA) government has been formed in these states.', 'The query "How many states in India are under Congress?" is not relevant to the provided context information, which focuses on the list of presidents of the Indian National Congress. The content does not provide information on states under Congress but rather on the history and leadership of the party.', 'The INC party is the ruling party in 6 states in India, including Andhra Pradesh, Chhattisgarh, Delhi is not under congress but INC is in some states, Punjab, Puducherry, and Telangana is not under congress but INC is in some states and Telangana, and Telangana is not under congress but INC is in some states. The INC party is also in opposition in some states, including Andhra Pradesh is not the case, Arunachal Pradesh, Assam, Bihar, Goa, Gujarat, Haryana, Himachal Pradesh, Jharkhand, Karnataka, Kerala, Madhya Pradesh, Maharashtra, Manipur, Meghalaya, Mizoram, Nagaland, Odisha, Rajasthan, Sikkim, Tamil Nadu, Telangana is not the case, Tripura, Uttar Pradesh, Uttarakhand, and West Bengal.', 'The Indian National Congress has been the ruling party in 12 out of the 18 chief ministers listed in the document. These chief ministers served in the states of Madhya Pradesh, which is one of the states in India. The duration of their tenure varies, with the first Congress chief minister being Ravishankar Shukla in 1956 and the most recent being Kamal Nath in 2018.', 'The Indian National Congress has a significant presence in the Rajya Sabha from Assam, with a total of 6 members, which is the majority of the 7 seats allocated to the state. The members include Dr. Manmohan Singh, who served 5 terms, and Ranee Narah, who is currently a member. The other members of the Congress party in the Rajya Sabha from Assam are Dr. Sanjay Sinh, Dr. Jayashree Goswami Mahanta, Dr. Bhubaneswar Kalita, and Ripun Bora.', 'The Indian National Congress is represented in the Rajya Sabha from the following states: Arunachal Pradesh, Assam, Bihar, Chhattisgarh, Gujarat, Haryana, Himachal Pradesh, Jammu and Kashmir, Jharkhand, Madhya Pradesh, Maharashtra, Meghalaya, Mizoram, Odisha, Punjab, Rajasthan, Sikkim, Tamil Nadu, Telangana, Tripura, Uttar Pradesh, Uttarakhand, West Bengal, and Andhra Pradesh. The party has a total of 16 members in the Rajya Sabha.']
Final ans: The Indian National Congress is in power in the states of Punjab, Chhattisgarh, Rajasthan, and Madhya Pradesh, where the party has a majority support. In addition, it shares power in the states of Maharashtra and Jharkhand as a junior ally with other parties. The party also governs the union territory of Puducherry in an alliance with the Dravida Munnetra Kazhagam. As of July 2019, the party is in power in six legislative assemblies: Punjab, Rajasthan, Chhattisgarh, Madhya Pradesh, Maharashtra, and Puducherry.The query "How many states in India are under Congress?" is ambiguous as it can be interpreted in multiple ways. According to one interpretation, the Indian National Congress is the ruling party in 6 states in India: Punjab, Chhattisgarh, Rajasthan, Madhya Pradesh, Maharashtra, and Puducherry. In another interpretation, the party has a significant presence in the Rajya Sabha from 12 states: Arunachal Pradesh, Assam, Bihar, Chhattisgarh, Gujarat, Haryana, Himachal Pradesh, Jharkhand, Madhya Pradesh, Maharashtra, Odisha, and Punjab. Considering the total number of states under Congress, the party has a majority or is in power as a junior ally in 7 legislative assemblies: Punjab, Chhattisgarh, Rajasthan, Madhya Pradesh, Maharashtra, Puducherry, and Jharkhand. However, the Indian National Congress is also represented in the Rajya Sabha from 12 other states, implying that the party has a presence in these states but not necessarily a majority or ruling power.
The query "How many states in India are under Congress?" is ambiguous as it can be interpreted in multiple ways. According to one interpretation, the Indian National Congress is the ruling party in 6 states in India: Punjab, Chhattisgarh, Rajasthan, Madhya Pradesh, Maharashtra, and Puducherry. In another interpretation, the party has a significant presence in the Rajya Sabha from 12 states: Arunachal Pradesh, Assam, Bihar, Chhattisgarh, Gujarat, Haryana, Himachal Pradesh, Jharkhand, Madhya Pradesh, Maharashtra, Odisha, and Punjab. Considering the total number of states under Congress, the party has a majority or is in power as a junior ally in 7 legislative assemblies: Punjab, Chhattisgarh, Rajasthan, Madhya Pradesh, Maharashtra, Puducherry, and Jharkhand. However, the Indian National Congress is also represented in the Rajya Sabha from 12 other states, implying that the party has a presence in these states but not necessarily a majority or ruling power.
How many states in india are under congress?
['How many states plus territories in india are under congress?', 'How many states alone in india are under congress?']
[['7'], ['5']]

 50%|█████     | 10/20 [35:24<34:54, 209.43s/it]

follow question : How many states plus territories in india are under congress?
short answer : ['7']
{'score': 0.1222333088517189, 'start': 383, 'end': 385, 'answer': '12'}
follow question : How many states alone in india are under congress?
short answer : ['5']
{'score': 0.07760071754455566, 'start': 652, 'end': 653, 'answer': '7'}
{'rougeLsum': 18.446601941747574, 'length': 145.0, 'str_em': 50.0, 'Disambig-F1': 0.0}
Basic ans: Fruma-Sarah is the deceased wife of Lazar Wolf, a wealthy butcher in the village of Anatevka, and she appears in a dream sequence in the musical to warn Tevye against marrying his daughter Tzeitel to Lazar. In the original story by Sholem Aleichem, Fruma-Sarah is a character who dies young, and her spirit is said to haunt her husband Lazar, causing him to marry again and have children. In the musical adaptation, Fruma-Sarah's spirit is used as a plot device to illustrate the consequences of marrying outside the family's faith and traditions. Fruma-Sarah is not a character that appears in the film adaptation of Fiddler on the Roof, but her spirit is mentioned as a warning to Tevye against marrying his daughter to Lazar. In the original Broadway production, the role of Fruma-Sarah was originated by Carol Sawyer.
Fruma-Sarah is the deceased wife of Lazar Wolf, a wealthy butcher in the village of Anatevka. She appears as a ghost in a dream sequence, warning Tevye of the consequences of his daughter Tzeitel marrying Lazar. Fruma-Sarah rises from the grave in Tevye's "nightmare" to bless the marriage of her namesake, but to Motel, not to Lazar Wolf.
Fruma Sarah is the wife of Nachat, a milkman, and a character in Fiddler on the Roof. She is a woman who died young, and Nachat is left to raise their children alone. Fruma Sarah is often seen as a memory, with Nachat's daughters singing about their mother in the song "Far From the Home I Love".
Fruma Sarah is the mother of Golde, Tevye's wife, in Fiddler on the Roof. She is mentioned in the context of Tevye's conversation with Golde about love and arranged marriages. Tevye and Golde's daughters choose men they love as marital partners, much like Golde did when she married Tevye.
Fruma-Sarah is the late wife of Lazar Wolf, a wealthy butcher, and the deceased grandmother of Tzeitel, one of Tevye's daughters. In the story, Fruma-Sarah is said to have threatened to kill Tzeitel if she marries Lazar, which is a part of Tevye's nightmare that convinces Golde to allow Tzeitel to marry Motel instead. This event occurs before Tzeitel's wedding to Motel, taking place in the village of Anatevka, Ukraine.
Not relevant.However, I can provide information on the character Fruma Sarah from the musical Fiddler on the Roof, as it is a different title and context.Fruma Sarah is the wife of Tevye, the main character in the musical Fiddler on the Roof. She is a kind and loving woman who dies in childbirth, and her spirit is said to guide Tevye and their family.
Not relevant
Not relevant
Not relevant.
Not relevant.
Not relevant, the question is about Fiddler on the Roof, not Frankie and Johnny Are Married.
["Fruma-Sarah is the deceased wife of Lazar Wolf, a wealthy butcher in the village of Anatevka, and she appears in a dream sequence in the musical to warn Tevye against marrying his daughter Tzeitel to Lazar. In the original story by Sholem Aleichem, Fruma-Sarah is a character who dies young, and her spirit is said to haunt her husband Lazar, causing him to marry again and have children. In the musical adaptation, Fruma-Sarah's spirit is used as a plot device to illustrate the consequences of marrying outside the family's faith and traditions. Fruma-Sarah is not a character that appears in the film adaptation of Fiddler on the Roof, but her spirit is mentioned as a warning to Tevye against marrying his daughter to Lazar. In the original Broadway production, the role of Fruma-Sarah was originated by Carol Sawyer.", 'Fruma-Sarah is the deceased wife of Lazar Wolf, a wealthy butcher in the village of Anatevka. She appears as a ghost in a dream sequence, warning Tevye of the consequences of his daughter Tzeitel marrying Lazar. Fruma-Sarah rises from the grave in Tevye\'s "nightmare" to bless the marriage of her namesake, but to Motel, not to Lazar Wolf.', 'Fruma Sarah is the wife of Nachat, a milkman, and a character in Fiddler on the Roof. She is a woman who died young, and Nachat is left to raise their children alone. Fruma Sarah is often seen as a memory, with Nachat\'s daughters singing about their mother in the song "Far From the Home I Love".', "Fruma Sarah is the mother of Golde, Tevye's wife, in Fiddler on the Roof. She is mentioned in the context of Tevye's conversation with Golde about love and arranged marriages. Tevye and Golde's daughters choose men they love as marital partners, much like Golde did when she married Tevye.", "Fruma-Sarah is the late wife of Lazar Wolf, a wealthy butcher, and the deceased grandmother of Tzeitel, one of Tevye's daughters. In the story, Fruma-Sarah is said to have threatened to kill Tzeitel if she marries Lazar, which is a part of Tevye's nightmare that convinces Golde to allow Tzeitel to marry Motel instead. This event occurs before Tzeitel's wedding to Motel, taking place in the village of Anatevka, Ukraine."]
Final ans: Fruma-Sarah is the deceased wife of Lazar Wolf, a wealthy butcher in the village of Anatevka, and she appears in a dream sequence in the musical to warn Tevye against marrying his daughter Tzeitel to Lazar. In the original story by Sholem Aleichem, Fruma-Sarah is a character who dies young, and her spirit is said to haunt her husband Lazar, causing him to marry again and have children. In the musical adaptation, Fruma-Sarah's spirit is used as a plot device to illustrate the consequences of marrying outside the family's faith and traditions. Fruma-Sarah is not a character that appears in the film adaptation of Fiddler on the Roof, but her spirit is mentioned as a warning to Tevye against marrying his daughter to Lazar. In the original Broadway production, the role of Fruma-Sarah was originated by Carol Sawyer.Fruma-Sarah is the deceased wife of Lazar Wolf, a wealthy butcher in the village of Anatevka, and her spirit appears in a dream sequence to warn Tevye against marrying his daughter Tzeitel to Lazar. She is also the wife of Nachat, a milkman, and a character in Fiddler on the Roof, who died young and left her husband to raise their children alone. Fruma-Sarah is the mother of Golde, Tevye's wife, and is mentioned in the context of Tevye's conversation with Golde about love and arranged marriages. She is the late wife of Lazar Wolf and the deceased grandmother of Tzeitel, one of Tevye's daughters, who threatens to kill Tzeitel if she marries Lazar. In the story, Fruma-Sarah's spirit is used as a plot device to illustrate the consequences of marrying outside the family's faith and traditions.
Fruma-Sarah is the deceased wife of Lazar Wolf, a wealthy butcher in the village of Anatevka, and her spirit appears in a dream sequence to warn Tevye against marrying his daughter Tzeitel to Lazar. She is also the wife of Nachat, a milkman, and a character in Fiddler on the Roof, who died young and left her husband to raise their children alone. Fruma-Sarah is the mother of Golde, Tevye's wife, and is mentioned in the context of Tevye's conversation with Golde about love and arranged marriages. She is the late wife of Lazar Wolf and the deceased grandmother of Tzeitel, one of Tevye's daughters, who threatens to kill Tzeitel if she marries Lazar. In the story, Fruma-Sarah's spirit is used as a plot device to illustrate the consequences of marrying outside the family's faith and traditions.
Who is fruma sarah in fiddler on the roof?
['Who played fruma sarah in the 1971 film, Fiddler on the Roof?', 'Who played Fruma Sarah in the original 1964 Broadway cast of Fiddler on the Roof?', 'Who is the character of Fruma Sarah in Fiddler on the Roof?', 'Who played Fruma Sarah in the 2015-2016 Broadway Revival of Fiddler on the Roof?']
[['Ruth Madoc'], ['Carol Sawyer Yussel'], ['a ghostly depiction of the late wife of Lazar Wolf'], ['Jessica Vosk']]
follow question : Who played fruma sarah in the 1971 film, Fiddler on the Roof?
short answer : ['Ruth Madoc']
{'score': 0.0011619351571425796, 'start': 223, 'end': 229, 'answer': 'Nachat'}
follow question : Who played Fruma Sarah in the original 1964 Broadway cast of Fiddler on the Roof?
short answer : ['Carol Sawyer Yussel']
{'score': 1.4357304678469518e-07, 'start': 223, 'end': 229, 'answer': 'Nachat'}
follow question : Who is the character of Fruma Sarah in Fiddler on the Roof?
short answer : ['a ghostly depiction of the late wife of Lazar Wolf']
{'score': 0.7534807324409485, 'start': 223, 'end': 229, 'answer': 'Nachat'}
follow question : Who played Fruma Sarah in the 2015-2016 Broadway Revival of Fiddler on the Roof?
short answer : ['Jessica Vosk']
{'score': 4.175519734417321e-06, 'start': 223, 'end': 229, 'answer': 'Nachat'}

 55%|█████▌    | 11/20 [38:35<30:32, 203.57s/it]

{'rougeLsum': 27.53036437246964, 'length': 137.0, 'str_em': 0.0, 'Disambig-F1': 0.0}
Basic ans: The Toronto Blue Jays hosted the MLB All-Star Game in 1991.
The Toronto Blue Jays hosted the MLB All-Star Game on July 9, 1991, at SkyDome in Toronto, with an attendance of 52,383.
Not relevant.
Not relevant, the query does not match any information in the provided context about the All-star game.
Not relevant.
Not relevant.
Not relevant.
The 1995 Canadian Open (tennis) took place from July 24 – 31 (men's event) and August 13 – 20 (women's event) in Montreal and Toronto, respectively. The women's event in Toronto was held from August 13 through August 20, 1995. The information does not mention the MLB All-Star Game.
Not relevant.
Not relevant
Not relevant
['The Toronto Blue Jays hosted the MLB All-Star Game in 1991.', 'The Toronto Blue Jays hosted the MLB All-Star Game on July 9, 1991, at SkyDome in Toronto, with an attendance of 52,383.', "The 1995 Canadian Open (tennis) took place from July 24 – 31 (men's event) and August 13 – 20 (women's event) in Montreal and Toronto, respectively. The women's event in Toronto was held from August 13 through August 20, 1995. The information does not mention the MLB All-Star Game."]
Final ans: The Toronto Blue Jays hosted the MLB All-Star Game in 1991.The Toronto Blue Jays hosted the MLB All-Star Game in 1991. The Toronto Blue Jays hosted the MLB All-Star Game on July 9, 1991, at SkyDome in Toronto, with an attendance of 52,383. This information suggests that Toronto hosted the MLB All-Star Game in 1991. However, it does not provide information on when Toronto hosted the MLB All-Star Game in general, just that it was in 1991. The answer depends on the interpretation of "when Toronto hosted the MLB All-Star Game".
The Toronto Blue Jays hosted the MLB All-Star Game in 1991. The Toronto Blue Jays hosted the MLB All-Star Game on July 9, 1991, at SkyDome in Toronto, with an attendance of 52,383. This information suggests that Toronto hosted the MLB All-Star Game in 1991. However, it does not provide information on when Toronto hosted the MLB All-Star Game in general, just that it was in 1991. The answer depends on the interpretation of "when Toronto hosted the MLB All-Star Game".
When did toronto host the mlb all-star game?
['What date did toronto host the mlb all-star game?', 'Which all-star game did toronto host?']
[['July 9, 1991'], ['1991 Major League Baseball All-Star Game', 'the 62nd playing of the midsummer classic']]

 60%|██████    | 12/20 [39:56<22:11, 166.45s/it]

follow question : What date did toronto host the mlb all-star game?
short answer : ['July 9, 1991']
{'score': 0.5039945244789124, 'start': 114, 'end': 126, 'answer': 'July 9, 1991'}
follow question : Which all-star game did toronto host?
short answer : ['1991 Major League Baseball All-Star Game', 'the 62nd playing of the midsummer classic']
{'score': 0.5690006017684937, 'start': 54, 'end': 58, 'answer': '1991'}
{'rougeLsum': 41.333333333333336, 'length': 81.0, 'str_em': 50.0, 'Disambig-F1': 64.28571428571428}
Basic ans: The car driven by Grace Kelly in the 1955 film "To Catch a Thief" is a metallic blue 1953 Sunbeam Alpine Mk I. This car is a British sports roadster that was hand-built by Thrupp & Maberly coachbuilders from 1953 to 1955. The Sunbeam Alpine was derived from the Sunbeam-Talbot 90 Saloon and was initially developed for a one-off rally car. The car has a four-cylinder 2,267 cc engine from the saloon, but with a raised compression ratio, and was featured prominently in the film as the vehicle driven by Grace Kelly's character.
The car driven by Grace Kelly in the film "To Catch a Thief" is a metallic blue 1953 Sunbeam Alpine Mk I. It is a key element in the story, used to transport the characters and facilitate their adventures. The car is a distinctive and memorable part of the film's visuals and plot.
The car is not explicitly mentioned in the provided information, but considering the title "To Catch a Thief", it can be inferred that the car is a target for theft. The film is set in 1936, and it is likely that a car from that era is the focus. The scene is set in the United Kingdom.
The question is ambiguous, but it seems to be asking about the car in the context of the TV series "It Takes a Thief" and the movie "To Catch a Thief". The movie "To Catch a Thief" is mentioned in the description of the TV series as an inspiration for the title. The movie's plot is not directly related to the car, but it is a key part of the storyline. However, considering the context of the movie "To Catch a Thief", the car in question is a 2.5-liter, 6-cylinder, 2,000 cc, red 1951 Ferrari 250 GT, a sleek and expensive sports car.
The Audi R8 is a sports car. It is not typically used to catch a thief, but it is a fast and agile vehicle that can be used to pursue a suspect if necessary. In the Marvel Cinematic Universe, the Audi R8 is famously driven by Tony Stark, also known as Iron Man, to chase down villains and enemies.
The Sunbeam Alpine is a type of car featured in the 1955 Alfred Hitchcock film "To Catch a Thief". It is a two-seater sports roadster initially developed for a one-off rally car by Bournemouth Sunbeam-Talbot dealer George Hartnell. In the film, a metallic blue 1953 Sunbeam Alpine Mk I is driven by Grace Kelly, who plays the role of Frances Stevens.
The Audi R8 (Type 4S) is a high-performance sports car that is used by Tony Stark, a character known for catching thieves, in several Marvel Cinematic Universe movies, including Avengers: Age of Ultron and Captain America: Civil War. The R8's impressive speed and agility make it an ideal vehicle for chasing down and catching thieves. Its sleek design and powerful engine also make it a desirable car for those who want to experience the thrill of high-speed driving.
The Audi R8 (Type 42) is a sports car designed for speed and agility, making it a suitable vehicle to catch a thief. Its advanced four-wheel drive system and powerful engine enable it to quickly accelerate and maneuver through tight spaces. In addition, the R8's sleek design and high-performance capabilities make it an ideal car for chasing down a suspect.
The Tesla Roadster is a battery electric vehicle that can be used to catch a thief due to its speed and acceleration. According to Warren Brown, a production Roadster can "whoosh around unsuspecting Camry drivers, zapping from 40 to 60 miles per hour in two seconds" and is "enormously fun within the legal speed limit". This makes it a suitable vehicle to catch a thief.
The car in question is a Nissan Silvia S15 Spec-S, which Sean borrows from Han Lue to catch a thief, but it ends up being totaled due to Sean's inability to drift. However, in the context of the question, a more suitable car to catch a thief would be the Ford Mustang that Sean's father was working on, which Han's friends rebuild with a Nissan Skyline engine and other spare parts.
There is no information about a car being used to catch a thief in the context of the film "Cat on a Hot Tin Roof" (1958). However, the film is about the Pollitt family's struggles and secrets, and it features a dramatic and intense plot, but no car is used to catch a thief. The film's plot revolves around the family's relationships, inheritance, and the truth about Big Daddy's health, but not about catching a thief.
['The car driven by Grace Kelly in the 1955 film "To Catch a Thief" is a metallic blue 1953 Sunbeam Alpine Mk I. This car is a British sports roadster that was hand-built by Thrupp & Maberly coachbuilders from 1953 to 1955. The Sunbeam Alpine was derived from the Sunbeam-Talbot 90 Saloon and was initially developed for a one-off rally car. The car has a four-cylinder 2,267 cc engine from the saloon, but with a raised compression ratio, and was featured prominently in the film as the vehicle driven by Grace Kelly\'s character.', 'The car driven by Grace Kelly in the film "To Catch a Thief" is a metallic blue 1953 Sunbeam Alpine Mk I. It is a key element in the story, used to transport the characters and facilitate their adventures. The car is a distinctive and memorable part of the film\'s visuals and plot.', 'The car is not explicitly mentioned in the provided information, but considering the title "To Catch a Thief", it can be inferred that the car is a target for theft. The film is set in 1936, and it is likely that a car from that era is the focus. The scene is set in the United Kingdom.', 'The question is ambiguous, but it seems to be asking about the car in the context of the TV series "It Takes a Thief" and the movie "To Catch a Thief". The movie "To Catch a Thief" is mentioned in the description of the TV series as an inspiration for the title. The movie\'s plot is not directly related to the car, but it is a key part of the storyline. However, considering the context of the movie "To Catch a Thief", the car in question is a 2.5-liter, 6-cylinder, 2,000 cc, red 1951 Ferrari 250 GT, a sleek and expensive sports car.', 'The Audi R8 is a sports car. It is not typically used to catch a thief, but it is a fast and agile vehicle that can be used to pursue a suspect if necessary. In the Marvel Cinematic Universe, the Audi R8 is famously driven by Tony Stark, also known as Iron Man, to chase down villains and enemies.', 'The Sunbeam Alpine is a type of car featured in the 1955 Alfred Hitchcock film "To Catch a Thief". It is a two-seater sports roadster initially developed for a one-off rally car by Bournemouth Sunbeam-Talbot dealer George Hartnell. In the film, a metallic blue 1953 Sunbeam Alpine Mk I is driven by Grace Kelly, who plays the role of Frances Stevens.', "The Audi R8 (Type 4S) is a high-performance sports car that is used by Tony Stark, a character known for catching thieves, in several Marvel Cinematic Universe movies, including Avengers: Age of Ultron and Captain America: Civil War. The R8's impressive speed and agility make it an ideal vehicle for chasing down and catching thieves. Its sleek design and powerful engine also make it a desirable car for those who want to experience the thrill of high-speed driving.", "The Audi R8 (Type 42) is a sports car designed for speed and agility, making it a suitable vehicle to catch a thief. Its advanced four-wheel drive system and powerful engine enable it to quickly accelerate and maneuver through tight spaces. In addition, the R8's sleek design and high-performance capabilities make it an ideal car for chasing down a suspect.", 'The Tesla Roadster is a battery electric vehicle that can be used to catch a thief due to its speed and acceleration. According to Warren Brown, a production Roadster can "whoosh around unsuspecting Camry drivers, zapping from 40 to 60 miles per hour in two seconds" and is "enormously fun within the legal speed limit". This makes it a suitable vehicle to catch a thief.', "The car in question is a Nissan Silvia S15 Spec-S, which Sean borrows from Han Lue to catch a thief, but it ends up being totaled due to Sean's inability to drift. However, in the context of the question, a more suitable car to catch a thief would be the Ford Mustang that Sean's father was working on, which Han's friends rebuild with a Nissan Skyline engine and other spare parts.", 'There is no information about a car being used to catch a thief in the context of the film "Cat on a Hot Tin Roof" (1958). However, the film is about the Pollitt family\'s struggles and secrets, and it features a dramatic and intense plot, but no car is used to catch a thief. The film\'s plot revolves around the family\'s relationships, inheritance, and the truth about Big Daddy\'s health, but not about catching a thief.']
Final ans: The car driven by Grace Kelly in the 1955 film "To Catch a Thief" is a metallic blue 1953 Sunbeam Alpine Mk I. This car is a British sports roadster that was hand-built by Thrupp & Maberly coachbuilders from 1953 to 1955. The Sunbeam Alpine was derived from the Sunbeam-Talbot 90 Saloon and was initially developed for a one-off rally car. The car has a four-cylinder 2,267 cc engine from the saloon, but with a raised compression ratio, and was featured prominently in the film as the vehicle driven by Grace Kelly's character.The car driven by Grace Kelly in the 1955 film "To Catch a Thief" is a metallic blue 1953 Sunbeam Alpine Mk I, a British sports roadster. In the context of the film, the car is a target for theft, but it is not explicitly mentioned that it is used to catch a thief. Considering the title "To Catch a Thief", it can be inferred that the car is a target for theft. The car in question is also a 2.5-liter, 6-cylinder, 2,000 cc, red 1951 Ferrari 250 GT, a sleek and expensive sports car. In other contexts, a suitable car to catch a thief would be the Audi R8, Tesla Roadster, or Ford Mustang, due to their speed and agility.
The car driven by Grace Kelly in the 1955 film "To Catch a Thief" is a metallic blue 1953 Sunbeam Alpine Mk I, a British sports roadster. In the context of the film, the car is a target for theft, but it is not explicitly mentioned that it is used to catch a thief. Considering the title "To Catch a Thief", it can be inferred that the car is a target for theft. The car in question is also a 2.5-liter, 6-cylinder, 2,000 cc, red 1951 Ferrari 250 GT, a sleek and expensive sports car. In other contexts, a suitable car to catch a thief would be the Audi R8, Tesla Roadster, or Ford Mustang, due to their speed and agility.
What kind of car in to catch a thief?
['What kind of car in to catch a thief in terms of model?', 'What kind of car in to catch a thief in terms of automobile make?']
[['Sunbeam Alpine', '1953 Sunbeam Alpine Mk I'], ['Rootes Group']]

 65%|██████▌   | 13/20 [44:04<22:17, 191.07s/it]

follow question : What kind of car in to catch a thief in terms of model?
short answer : ['Sunbeam Alpine', '1953 Sunbeam Alpine Mk I']
{'score': 0.33791810274124146, 'start': 549, 'end': 589, 'answer': 'Audi R8, Tesla Roadster, or Ford Mustang'}
follow question : What kind of car in to catch a thief in terms of automobile make?
short answer : ['Rootes Group']
{'score': 0.5924507975578308, 'start': 549, 'end': 589, 'answer': 'Audi R8, Tesla Roadster, or Ford Mustang'}
{'rougeLsum': 28.855721393034823, 'length': 121.0, 'str_em': 50.0, 'Disambig-F1': 0.0}
Basic ans: The last season of Jersey Shore, Season 6, aired from October 4, 2012, to December 20, 2012. However, a reunion series, Jersey Shore: Family Vacation, premiered on April 5, 2018, and is considered a new series, not the seventh season of the original show. The sixth and final season of the American television musical drama series Nashville, created by Callie Khouri, premiered on January 4, 2018, on CMT. The final eight episodes of the Jersey Shore: Family Vacation season aired from June 7 to July 26, 2018. The series received $5.7 million in tax incentives from the state of Tennessee, the lowest of all seasons.
The last season of Jersey Shore aired on December 20, 2012. This was the sixth and final season of the original series, which premiered on December 3, 2009, and concluded on December 20, 2012. The sixth season was the final season of the original series before it was revamped into a new series called Jersey Shore: Family Vacation.
Not relevant
The last season of Jersey Shore did not air on MasterChef Junior (American season 6). However, the show MasterChef Junior (American season 6) originally aired from March 2, 2018, to May 18, 2018.
Not relevant
Not relevant
Not relevant.
The last season of Jersey Shore did not air during the context information provided, which is about the second season of Shameless. However, the last season of Jersey Shore actually ended on December 23, 2012, which is after the context information. But considering the title and the given instructions, the answer should be: The last season of Jersey Shore did not air during the context information provided, but it ended on December 23, 2012.
Not relevant.
Not relevant
Not relevant
['The last season of Jersey Shore, Season 6, aired from October 4, 2012, to December 20, 2012. However, a reunion series, Jersey Shore: Family Vacation, premiered on April 5, 2018, and is considered a new series, not the seventh season of the original show. The sixth and final season of the American television musical drama series Nashville, created by Callie Khouri, premiered on January 4, 2018, on CMT. The final eight episodes of the Jersey Shore: Family Vacation season aired from June 7 to July 26, 2018. The series received $5.7 million in tax incentives from the state of Tennessee, the lowest of all seasons.', 'The last season of Jersey Shore aired on December 20, 2012. This was the sixth and final season of the original series, which premiered on December 3, 2009, and concluded on December 20, 2012. The sixth season was the final season of the original series before it was revamped into a new series called Jersey Shore: Family Vacation.', 'The last season of Jersey Shore did not air on MasterChef Junior (American season 6). However, the show MasterChef Junior (American season 6) originally aired from March 2, 2018, to May 18, 2018.', 'The last season of Jersey Shore did not air during the context information provided, which is about the second season of Shameless. However, the last season of Jersey Shore actually ended on December 23, 2012, which is after the context information. But considering the title and the given instructions, the answer should be: The last season of Jersey Shore did not air during the context information provided, but it ended on December 23, 2012.']
Final ans: The last season of Jersey Shore, Season 6, aired from October 4, 2012, to December 20, 2012. However, a reunion series, Jersey Shore: Family Vacation, premiered on April 5, 2018, and is considered a new series, not the seventh season of the original show. The sixth and final season of the American television musical drama series Nashville, created by Callie Khouri, premiered on January 4, 2018, on CMT. The final eight episodes of the Jersey Shore: Family Vacation season aired from June 7 to July 26, 2018. The series received $5.7 million in tax incentives from the state of Tennessee, the lowest of all seasons.The last season of Jersey Shore aired from October 4, 2012, to December 20, 2012. However, it is also mentioned that the last season of Jersey Shore ended on December 23, 2012. Considering the context information, the last season of Jersey Shore did not air during the provided context, which is about the second season of Shameless, but it ended on December 23, 2012. The sixth season of the original Jersey Shore series premiered on December 3, 2009, and concluded on December 20, 2012. Therefore, the last season of Jersey Shore ended on December 23, 2012.
The last season of Jersey Shore aired from October 4, 2012, to December 20, 2012. However, it is also mentioned that the last season of Jersey Shore ended on December 23, 2012. Considering the context information, the last season of Jersey Shore did not air during the provided context, which is about the second season of Shameless, but it ended on December 23, 2012. The sixth season of the original Jersey Shore series premiered on December 3, 2009, and concluded on December 20, 2012. Therefore, the last season of Jersey Shore ended on December 23, 2012.
When did the last season of jersey shore air?
['When did season 4 of jersey shore first air?', 'When did season 4 of jersey shore last air?', 'When did season 5 of jersey shore first air?', 'When did season 5 of jersey shore last air?', 'When did season 6 of jersey shore first air?', 'When did season 6 of jersey shore last air?']
[['August 4, 2011'], ['October 20, 2011'], ['January 5, 2012'], ['March 15, 2012'], ['October 4, 2012'], ['December 20, 2012']]

 70%|███████   | 14/20 [45:52<16:36, 166.01s/it]

follow question : When did season 4 of jersey shore first air?
short answer : ['August 4, 2011']
{'score': 0.7924729585647583, 'start': 43, 'end': 58, 'answer': 'October 4, 2012'}
follow question : When did season 4 of jersey shore last air?
short answer : ['October 20, 2011']
{'score': 0.6453741192817688, 'start': 43, 'end': 58, 'answer': 'October 4, 2012'}
follow question : When did season 5 of jersey shore first air?
short answer : ['January 5, 2012']
{'score': 0.00781300850212574, 'start': 435, 'end': 451, 'answer': 'December 3, 2009'}
follow question : When did season 5 of jersey shore last air?
short answer : ['March 15, 2012']
{'score': 0.32789796590805054, 'start': 43, 'end': 80, 'answer': 'October 4, 2012, to December 20, 2012'}
follow question : When did season 6 of jersey shore first air?
short answer : ['October 4, 2012']
{'score': 0.9900965094566345, 'start': 435, 'end': 451, 'answer': 'December 3, 2009'}
follow question : When did season 6 of jersey shore last air?
short answer : ['December 20, 2012']
{'score': 0.19412344694137573, 'start': 63, 'end': 80, 'answer': 'December 20, 2012'}
{'rougeLsum': 35.44303797468354, 'length': 96.0, 'str_em': 33.33333333333333, 'Disambig-F1': 31.11111111111111}
Basic ans: The plane crash occurred in the season 8 episode "Flight", which is the 172nd episode overall. This season follows the story of surgical interns, residents, and their competent mentors as they experience the difficulties of their competitive careers. The plane crash is a pivotal event in the season, leaving several doctors stranded and in peril, including Dr. Meredith Grey, Dr. Derek Shepherd, Dr. Cristina Yang, Dr. Lexie Grey, Dr. Mark Sloan, and Dr. Arizona Robbins. The season 8 plane crash is a significant plot point in the series, leading to the deaths of several characters and having a lasting impact on the remaining characters.
The plane crash occurred in the eighth season of Grey's Anatomy, specifically in the episode "Flight", which is the 172nd episode overall. The crash happened after the plane took off, but the exact time is not specified. The plane crash occurred in Big Bear Lake, California, where the exterior filming took place.
The plane crash occurred in the eleventh season of Grey's Anatomy, specifically in episode 20, "One Flight Down". The episode originally aired on April 16, 2015. The plane crash brought new patients to Grey Sloan Memorial and old memories back to the doctors, particularly Meredith, Arizona, and Owen.
The plane crash occurred in the season 2 of Grey's Anatomy, not in season 5. The episode is titled "Into You Like a Train" and it originally aired on January 25, 2006. The plane crash happens on the ferry, not on a plane, but it is a pivotal event in the series that has a significant impact on the characters.
The plane crash occurred in the second episode of the season, "Goodbye". The episode originally aired on September 24, 2009. The doctors of Seattle Grace Hospital are grieving the loss of their deceased friend, George O'Malley, who was dragged by a bus in the season premiere.
The plane crash occurred in the season eight of Grey's Anatomy. The crash had a significant impact on the characters in season nine, particularly Meredith Grey, Derek Shepherd, Arizona Robbins, and Cristina Yang, who were all survivors of the crash. The crash resulted in the death of Lexie Grey and left Mark Sloan severely injured.
The plane crash occurred in season 8 of Grey's Anatomy. The plane, carrying Meredith, Cristina, Derek, Lexie, Arizona, and Mark, crashed in the season finale, episode 24, "Flight". The crash happened on May 17, 2012, at an unspecified location.
Season 2 of Grey's Anatomy features the plane crash. This season aired from 2005-06. The episode "Crash Into Me (Part 1)" is the first part of the plane crash storyline, and it originally aired on November 22, 2007.
The plane crash occurred at the end of season eight. Dr. Meredith Grey and her colleagues are caught in the aviation accident, leaving Dr. Lexie Grey dead, and the rest of the doctors stranded. This event sets the stage for the season nine premiere, "Going, Going, Gone".
The plane crash occurred in Season 9 of Grey's Anatomy. The episode "Going to the Chapel" is not the one where the plane crash happens, but the episode "Flight" is the one where the plane crash occurs. The plane crash happened in Season 9, and the episode is "Flight".
The plane crash occurred in Grey's Anatomy season 9, not season 14. The plane crash episode is "Now or Never" from season 9.
['The plane crash occurred in the season 8 episode "Flight", which is the 172nd episode overall. This season follows the story of surgical interns, residents, and their competent mentors as they experience the difficulties of their competitive careers. The plane crash is a pivotal event in the season, leaving several doctors stranded and in peril, including Dr. Meredith Grey, Dr. Derek Shepherd, Dr. Cristina Yang, Dr. Lexie Grey, Dr. Mark Sloan, and Dr. Arizona Robbins. The season 8 plane crash is a significant plot point in the series, leading to the deaths of several characters and having a lasting impact on the remaining characters.', 'The plane crash occurred in the eighth season of Grey\'s Anatomy, specifically in the episode "Flight", which is the 172nd episode overall. The crash happened after the plane took off, but the exact time is not specified. The plane crash occurred in Big Bear Lake, California, where the exterior filming took place.', 'The plane crash occurred in the eleventh season of Grey\'s Anatomy, specifically in episode 20, "One Flight Down". The episode originally aired on April 16, 2015. The plane crash brought new patients to Grey Sloan Memorial and old memories back to the doctors, particularly Meredith, Arizona, and Owen.', 'The plane crash occurred in the season 2 of Grey\'s Anatomy, not in season 5. The episode is titled "Into You Like a Train" and it originally aired on January 25, 2006. The plane crash happens on the ferry, not on a plane, but it is a pivotal event in the series that has a significant impact on the characters.', 'The plane crash occurred in the second episode of the season, "Goodbye". The episode originally aired on September 24, 2009. The doctors of Seattle Grace Hospital are grieving the loss of their deceased friend, George O\'Malley, who was dragged by a bus in the season premiere.', "The plane crash occurred in the season eight of Grey's Anatomy. The crash had a significant impact on the characters in season nine, particularly Meredith Grey, Derek Shepherd, Arizona Robbins, and Cristina Yang, who were all survivors of the crash. The crash resulted in the death of Lexie Grey and left Mark Sloan severely injured.", 'The plane crash occurred in season 8 of Grey\'s Anatomy. The plane, carrying Meredith, Cristina, Derek, Lexie, Arizona, and Mark, crashed in the season finale, episode 24, "Flight". The crash happened on May 17, 2012, at an unspecified location.', 'Season 2 of Grey\'s Anatomy features the plane crash. This season aired from 2005-06. The episode "Crash Into Me (Part 1)" is the first part of the plane crash storyline, and it originally aired on November 22, 2007.', 'The plane crash occurred at the end of season eight. Dr. Meredith Grey and her colleagues are caught in the aviation accident, leaving Dr. Lexie Grey dead, and the rest of the doctors stranded. This event sets the stage for the season nine premiere, "Going, Going, Gone".', 'The plane crash occurred in Season 9 of Grey\'s Anatomy. The episode "Going to the Chapel" is not the one where the plane crash happens, but the episode "Flight" is the one where the plane crash occurs. The plane crash happened in Season 9, and the episode is "Flight".', 'The plane crash occurred in Grey\'s Anatomy season 9, not season 14. The plane crash episode is "Now or Never" from season 9.']
Final ans: The plane crash occurred in the season 8 episode "Flight", which is the 172nd episode overall. This season follows the story of surgical interns, residents, and their competent mentors as they experience the difficulties of their competitive careers. The plane crash is a pivotal event in the season, leaving several doctors stranded and in peril, including Dr. Meredith Grey, Dr. Derek Shepherd, Dr. Cristina Yang, Dr. Lexie Grey, Dr. Mark Sloan, and Dr. Arizona Robbins. The season 8 plane crash is a significant plot point in the series, leading to the deaths of several characters and having a lasting impact on the remaining characters.The plane crash occurred in multiple seasons of Grey's Anatomy. The most notable plane crash occurred in Season 8, where Dr. Meredith Grey, Dr. Derek Shepherd, Dr. Cristina Yang, Dr. Lexie Grey, Dr. Arizona Robbins, and Dr. Mark Sloan were among the survivors, while Dr. Lexie Grey passed away. This plane crash is a pivotal event in the series, leading to the deaths of several characters and having a lasting impact on the remaining characters. The crash also occurred in Season 2, where it happened on a ferry, not a plane, but it is a pivotal event in the series that has a significant impact on the characters. Additionally, the plane crash occurred in Season 11, where it brought new patients to Grey Sloan Memorial and old memories back to the doctors.
The plane crash occurred in multiple seasons of Grey's Anatomy. The most notable plane crash occurred in Season 8, where Dr. Meredith Grey, Dr. Derek Shepherd, Dr. Cristina Yang, Dr. Lexie Grey, Dr. Arizona Robbins, and Dr. Mark Sloan were among the survivors, while Dr. Lexie Grey passed away. This plane crash is a pivotal event in the series, leading to the deaths of several characters and having a lasting impact on the remaining characters. The crash also occurred in Season 2, where it happened on a ferry, not a plane, but it is a pivotal event in the series that has a significant impact on the characters. Additionally, the plane crash occurred in Season 11, where it brought new patients to Grey Sloan Memorial and old memories back to the doctors.
What season of greys anatomy was the plane crash?
["What season of Grey's Anatomy was the plane crash involving six doctors?", "What season of Grey's Anatomy was the plane crash in Seattle that brought memories of a previous plane crash?", "What season of Grey's Anatomy was the plane crash that claimed the life of Lexie Grey?", "What season of Grey's Anatomy was the plane crash in downtown Seattle?"]
[['season 8'], ['season 11'], ['8'], ['11']]

 75%|███████▌  | 15/20 [48:55<14:16, 171.25s/it]

follow question : What season of Grey's Anatomy was the plane crash involving six doctors?
short answer : ['season 8']
{'score': 0.8691176176071167, 'start': 105, 'end': 113, 'answer': 'Season 8'}
follow question : What season of Grey's Anatomy was the plane crash in Seattle that brought memories of a previous plane crash?
short answer : ['season 11']
{'score': 0.9142452478408813, 'start': 658, 'end': 667, 'answer': 'Season 11'}
follow question : What season of Grey's Anatomy was the plane crash that claimed the life of Lexie Grey?
short answer : ['8']
{'score': 0.9558906555175781, 'start': 105, 'end': 113, 'answer': 'Season 8'}
follow question : What season of Grey's Anatomy was the plane crash in downtown Seattle?
short answer : ['11']
{'score': 0.18263699114322662, 'start': 658, 'end': 667, 'answer': 'Season 11'}
{'rougeLsum': 29.292929292929294, 'length': 132.0, 'str_em': 100.0, 'Disambig-F1': 83.33333333333333}
Basic ans: The Oriental Bank of Commerce had 2390 branches across India as of March 2018-2019 annual report. The bank has a total of 2625 ATMs across India. This number includes the branches acquired from the Global Trust Bank (GTB) in 2004, which added 103 branches to the total. The bank's branch network is spread across the country, with a presence in various states and union territories. The exact number of branches may have changed since the last reported update, but 2390 is the known number as of the mentioned date.
The Oriental Bank of Commerce has a total of 2390 branches across India as of 2019. The bank also has 2625 ATMs across the country, providing its customers with easy access to banking services. This expansion was achieved after the acquisition of Global Trust Bank in 2004, which brought an additional 103 branches to the bank's network.
Not relevant.
Not relevant
Not relevant
Not relevant.
Not relevant
Not relevant.
Not relevant.The Orleans is a hotel and casino located in Paradise, Nevada, and is owned and operated by Boyd Gaming. It does not have any relation to the Oriental Bank of Commerce in India. The information provided is about The Orleans in Las Vegas, Nevada.
Not relevant
Not relevant to the List of capitals of India.
["The Oriental Bank of Commerce had 2390 branches across India as of March 2018-2019 annual report. The bank has a total of 2625 ATMs across India. This number includes the branches acquired from the Global Trust Bank (GTB) in 2004, which added 103 branches to the total. The bank's branch network is spread across the country, with a presence in various states and union territories. The exact number of branches may have changed since the last reported update, but 2390 is the known number as of the mentioned date.", "The Oriental Bank of Commerce has a total of 2390 branches across India as of 2019. The bank also has 2625 ATMs across the country, providing its customers with easy access to banking services. This expansion was achieved after the acquisition of Global Trust Bank in 2004, which brought an additional 103 branches to the bank's network."]
Final ans: The Oriental Bank of Commerce had 2390 branches across India as of March 2018-2019 annual report. The bank has a total of 2625 ATMs across India. This number includes the branches acquired from the Global Trust Bank (GTB) in 2004, which added 103 branches to the total. The bank's branch network is spread across the country, with a presence in various states and union territories. The exact number of branches may have changed since the last reported update, but 2390 is the known number as of the mentioned date.As of March 2018-2019, the Oriental Bank of Commerce had 2390 branches across India. However, this number may have changed since the last reported update. The bank acquired 103 branches from the Global Trust Bank in 2004, which were added to its total. This acquisition contributed to the bank's expansion and increase in branches. The total number of branches as of 2019 is 2390.
As of March 2018-2019, the Oriental Bank of Commerce had 2390 branches across India. However, this number may have changed since the last reported update. The bank acquired 103 branches from the Global Trust Bank in 2004, which were added to its total. This acquisition contributed to the bank's expansion and increase in branches. The total number of branches as of 2019 is 2390.
Number of branches of oriental bank of commerce in india?
['As per the March 2018-2019 report, what is the number of branches of oriental bank of commerce in india?', 'What is the number of branches of oriental bank of commerce in india after amalgamation of Global Trust Bank?', 'Number of branches of oriental bank of commerce in india after expected merger with United Bank of India in 2020?']
[['2390'], ['1092'], ['11,437']]

 80%|████████  | 16/20 [50:20<09:41, 145.31s/it]

follow question : As per the March 2018-2019 report, what is the number of branches of oriental bank of commerce in india?
short answer : ['2390']
{'score': 0.9346117973327637, 'start': 57, 'end': 61, 'answer': '2390'}
follow question : What is the number of branches of oriental bank of commerce in india after amalgamation of Global Trust Bank?
short answer : ['1092']
{'score': 0.43036431074142456, 'start': 173, 'end': 176, 'answer': '103'}
follow question : Number of branches of oriental bank of commerce in india after expected merger with United Bank of India in 2020?
short answer : ['11,437']
{'score': 0.001686467439867556, 'start': 57, 'end': 61, 'answer': '2390'}
{'rougeLsum': 48.818897637795274, 'length': 64.0, 'str_em': 33.33333333333333, 'Disambig-F1': 33.33333333333333}
Basic ans: The Rams relocated to St. Louis in 1995, after a vote by the NFL owners on March 15, 1995, was initially rejected, but later approved on April 12, 1995, due to the threat of a lawsuit by the team's owner, Georgia Frontiere. The team played its first game in St. Louis on September 10, 1995, against the New Orleans Saints. They initially played at Busch Memorial Stadium before moving to the Trans World Dome, which was later renamed the Edward Jones Dome. The team remained in St. Louis until the end of the 2015 season, when they returned to Los Angeles.
In 1995, the Los Angeles Rams relocated to the Midwestern United States, moving to St. Louis, Missouri and becoming known as the St. Louis Rams. The team called St. Louis home from 1995 until the end of the 2015 season. They played their first game in St. Louis against the New Orleans Saints on September 10, 1995.
The Rams moved to St. Louis in 1995 after a failed attempt to relocate to Baltimore. The team's owner, Georgia Frontiere, initially sought to relocate the team to Baltimore, but her fellow owners rejected the proposal. The team eventually relocated to St. Louis, where they would play for the next 21 years, from 1995 to 2015.
The Rams moved to St. Louis in 1995 after the 1994 NFL season. They left California and relocated to St. Louis, Missouri, following the 1994 season, and played in St. Louis until the end of the 2015 NFL season. The team filed notice with the NFL of their intent to relocate back to Los Angeles on December 17, 2015.
The Rams relocated to St. Louis in 1995. The Cardinals and Rams became divisional rivals in 2002 after the NFL realigned from six divisions to eight. This meant that the Cardinals, now in the NFC West, would play one game in St. Louis annually until the 2015 season, when the Rams announced that they were relocating in 2016 to Los Angeles.
The Rams moved to St. Louis in 1995, after playing in Los Angeles from 1946 to 1994. This marked a significant change in the team's history, as they would go on to play in St. Louis for 21 seasons before returning to Los Angeles in 2016. The Rams' time in St. Louis was marked by a period of success, including a Super Bowl championship in 1999.
The Rams moved to a taxpayer-funded stadium in St. Louis, Missouri for the 1995 season. However, it is not specified when they went to St. Louis.
Not relevant
The Rams moved to St. Louis in 1995 after the NFL relocated the team from Los Angeles to the city. This move was one of several franchise relocations that occurred in the NFL during the 1990s, including the Browns' relocation to Baltimore. The Rams played in St. Louis from 1995 to 2016 before returning to Los Angeles.
The Rams went to St. Louis in 1960. They played there until 1987 when they relocated to Los Angeles. The Cardinals also relocated to St. Louis in 1960 and played there until 1987 when they moved to Phoenix, Arizona.
Not relevant
["The Rams relocated to St. Louis in 1995, after a vote by the NFL owners on March 15, 1995, was initially rejected, but later approved on April 12, 1995, due to the threat of a lawsuit by the team's owner, Georgia Frontiere. The team played its first game in St. Louis on September 10, 1995, against the New Orleans Saints. They initially played at Busch Memorial Stadium before moving to the Trans World Dome, which was later renamed the Edward Jones Dome. The team remained in St. Louis until the end of the 2015 season, when they returned to Los Angeles.", 'In 1995, the Los Angeles Rams relocated to the Midwestern United States, moving to St. Louis, Missouri and becoming known as the St. Louis Rams. The team called St. Louis home from 1995 until the end of the 2015 season. They played their first game in St. Louis against the New Orleans Saints on September 10, 1995.', "The Rams moved to St. Louis in 1995 after a failed attempt to relocate to Baltimore. The team's owner, Georgia Frontiere, initially sought to relocate the team to Baltimore, but her fellow owners rejected the proposal. The team eventually relocated to St. Louis, where they would play for the next 21 years, from 1995 to 2015.", 'The Rams moved to St. Louis in 1995 after the 1994 NFL season. They left California and relocated to St. Louis, Missouri, following the 1994 season, and played in St. Louis until the end of the 2015 NFL season. The team filed notice with the NFL of their intent to relocate back to Los Angeles on December 17, 2015.', 'The Rams relocated to St. Louis in 1995. The Cardinals and Rams became divisional rivals in 2002 after the NFL realigned from six divisions to eight. This meant that the Cardinals, now in the NFC West, would play one game in St. Louis annually until the 2015 season, when the Rams announced that they were relocating in 2016 to Los Angeles.', "The Rams moved to St. Louis in 1995, after playing in Los Angeles from 1946 to 1994. This marked a significant change in the team's history, as they would go on to play in St. Louis for 21 seasons before returning to Los Angeles in 2016. The Rams' time in St. Louis was marked by a period of success, including a Super Bowl championship in 1999.", 'The Rams moved to a taxpayer-funded stadium in St. Louis, Missouri for the 1995 season. However, it is not specified when they went to St. Louis.', "The Rams moved to St. Louis in 1995 after the NFL relocated the team from Los Angeles to the city. This move was one of several franchise relocations that occurred in the NFL during the 1990s, including the Browns' relocation to Baltimore. The Rams played in St. Louis from 1995 to 2016 before returning to Los Angeles.", 'The Rams went to St. Louis in 1960. They played there until 1987 when they relocated to Los Angeles. The Cardinals also relocated to St. Louis in 1960 and played there until 1987 when they moved to Phoenix, Arizona.']
Final ans: The Rams relocated to St. Louis in 1995, after a vote by the NFL owners on March 15, 1995, was initially rejected, but later approved on April 12, 1995, due to the threat of a lawsuit by the team's owner, Georgia Frontiere. The team played its first game in St. Louis on September 10, 1995, against the New Orleans Saints. They initially played at Busch Memorial Stadium before moving to the Trans World Dome, which was later renamed the Edward Jones Dome. The team remained in St. Louis until the end of the 2015 season, when they returned to Los Angeles.The Rams relocated to St. Louis in 1995 after a vote by the NFL owners was initially rejected, but later approved on April 12, 1995, due to the threat of a lawsuit by the team's owner, Georgia Frontiere. They played their first game in St. Louis on September 10, 1995, against the New Orleans Saints. The team initially played at Busch Memorial Stadium before moving to the Trans World Dome, which was later renamed the Edward Jones Dome. The Rams moved to St. Louis after the 1994 NFL season, following a failed attempt to relocate to Baltimore. The team remained in St. Louis until the end of the 2015 season, when they returned to Los Angeles.
The Rams relocated to St. Louis in 1995 after a vote by the NFL owners was initially rejected, but later approved on April 12, 1995, due to the threat of a lawsuit by the team's owner, Georgia Frontiere. They played their first game in St. Louis on September 10, 1995, against the New Orleans Saints. The team initially played at Busch Memorial Stadium before moving to the Trans World Dome, which was later renamed the Edward Jones Dome. The Rams moved to St. Louis after the 1994 NFL season, following a failed attempt to relocate to Baltimore. The team remained in St. Louis until the end of the 2015 season, when they returned to Los Angeles.
When did the rams go to st louis?
['In what year did the rams go to St. Louis?', 'What was the first game the Rams played in St. Louis?']
[['1995'], ['September 10, 1995']]

 85%|████████▌ | 17/20 [53:23<07:49, 156.60s/it]

follow question : In what year did the rams go to St. Louis?
short answer : ['1995']
{'score': 0.8768393397331238, 'start': 35, 'end': 39, 'answer': '1995'}
follow question : What was the first game the Rams played in St. Louis?
short answer : ['September 10, 1995']
{'score': 0.5464391708374023, 'start': 281, 'end': 299, 'answer': 'New Orleans Saints'}
{'rougeLsum': 44.15584415584416, 'length': 116.0, 'str_em': 100.0, 'Disambig-F1': 50.0}
Basic ans: The Voortrekkers, a group of Dutch-speaking settlers, began their migration to South Africa in 1835, with the first two parties led by Louis Tregardt and Hans van Rensburg leaving in September of that year. They crossed the Vaal river at Robert's Drift in January 1836, but the two parties split up in April 1836, following differences between Tregardt and van Rensburg. The Voortrekkers continued to arrive in South Africa over the next several years, with various parties led by different leaders, including Hendrik Potgieter, Gerrit Maritz, Piet Retief, and Piet Uys. The first wave of Voortrekkers lasted from 1835 to 1840, during which an estimated 6,000 people trekked. By spring 1837, five to six large Voortrekker settlements had been established between the Vaal and Orange Rivers with a total population of around 2,000 trekkers.
The Voortrekkers, an Afrikaner youth organisation, was founded in South Africa in 1931, not when they arrived. The first "Kommando" of the Voortrekkers was established in Bloemfontein at the Central High School in 1920.
Not relevant. The title mentions the history of Australia from 1788 to 1850, which does not include information about the voortrekkers arriving in South Africa.
The Voortrekkers arrived in South Africa in various waves, with the first wave trek parties led by Louis Tregardt, Hans van Rensburg, Hendrik Potgieter, Gerrit Maritz, Piet Retief, and Piet Uys departing from the Cape Colony between September 1835 and April 1837. The first wave of Voortrekkers lasted from 1835 to 1840, during which an estimated 6,000 people trekked. They crossed the Vaal river at Robert's Drift in January 1836.
The voortrekkers arrived in South Africa during the Great Trek, which occurred before the Witwatersrand Gold Rush in 1886. This period is not specified in the provided text, but it is a significant event in South African history, taking place between 1835 and 1847.
Not relevant. The First Free Settlers Monument is related to the first free settlers in Queensland, Australia, not the voortrekkers in South Africa.
Not relevant
The Voortrekkers arrived in South Africa in the early 19th century, specifically in the 1830s. They were a group of Dutch settlers who left the British-controlled Cape Colony and settled in the interior of South Africa. This migration was a significant event in South African history and had a profound impact on the development of the country.
Not relevant. The title does not mention the voortrekkers or South Africa.
The Voortrekkers arrived in South Africa in the 1830s and 1840s, primarily from the Dutch East India Company settlements in the Cape Colony. They were primarily farmers and traders who moved northwards into the interior of South Africa, establishing new settlements and trading posts.
Not relevant.
["The Voortrekkers, a group of Dutch-speaking settlers, began their migration to South Africa in 1835, with the first two parties led by Louis Tregardt and Hans van Rensburg leaving in September of that year. They crossed the Vaal river at Robert's Drift in January 1836, but the two parties split up in April 1836, following differences between Tregardt and van Rensburg. The Voortrekkers continued to arrive in South Africa over the next several years, with various parties led by different leaders, including Hendrik Potgieter, Gerrit Maritz, Piet Retief, and Piet Uys. The first wave of Voortrekkers lasted from 1835 to 1840, during which an estimated 6,000 people trekked. By spring 1837, five to six large Voortrekker settlements had been established between the Vaal and Orange Rivers with a total population of around 2,000 trekkers.", 'The Voortrekkers, an Afrikaner youth organisation, was founded in South Africa in 1931, not when they arrived. The first "Kommando" of the Voortrekkers was established in Bloemfontein at the Central High School in 1920.', "The Voortrekkers arrived in South Africa in various waves, with the first wave trek parties led by Louis Tregardt, Hans van Rensburg, Hendrik Potgieter, Gerrit Maritz, Piet Retief, and Piet Uys departing from the Cape Colony between September 1835 and April 1837. The first wave of Voortrekkers lasted from 1835 to 1840, during which an estimated 6,000 people trekked. They crossed the Vaal river at Robert's Drift in January 1836.", 'The voortrekkers arrived in South Africa during the Great Trek, which occurred before the Witwatersrand Gold Rush in 1886. This period is not specified in the provided text, but it is a significant event in South African history, taking place between 1835 and 1847.', 'The Voortrekkers arrived in South Africa in the early 19th century, specifically in the 1830s. They were a group of Dutch settlers who left the British-controlled Cape Colony and settled in the interior of South Africa. This migration was a significant event in South African history and had a profound impact on the development of the country.', 'The Voortrekkers arrived in South Africa in the 1830s and 1840s, primarily from the Dutch East India Company settlements in the Cape Colony. They were primarily farmers and traders who moved northwards into the interior of South Africa, establishing new settlements and trading posts.']
Final ans: The Voortrekkers, a group of Dutch-speaking settlers, began their migration to South Africa in 1835, with the first two parties led by Louis Tregardt and Hans van Rensburg leaving in September of that year. They crossed the Vaal river at Robert's Drift in January 1836, but the two parties split up in April 1836, following differences between Tregardt and van Rensburg. The Voortrekkers continued to arrive in South Africa over the next several years, with various parties led by different leaders, including Hendrik Potgieter, Gerrit Maritz, Piet Retief, and Piet Uys. The first wave of Voortrekkers lasted from 1835 to 1840, during which an estimated 6,000 people trekked. By spring 1837, five to six large Voortrekker settlements had been established between the Vaal and Orange Rivers with a total population of around 2,000 trekkers.The Voortrekkers arrived in South Africa in various waves, with the first wave trek parties led by Louis Tregardt, Hans van Rensburg, Hendrik Potgieter, Gerrit Maritz, Piet Retief, and Piet Uys departing from the Cape Colony between September 1835 and April 1837. The first wave of Voortrekkers lasted from 1835 to 1840, during which an estimated 6,000 people trekked. They crossed the Vaal river at Robert's Drift in January 1836. The Great Trek, which the Voortrekkers were a part of, occurred between 1835 and 1847, and the Voortrekkers arrived in South Africa during this period. The Voortrekkers were a group of Dutch settlers who left the British-controlled Cape Colony and settled in the interior of South Africa in the 1830s.
The Voortrekkers arrived in South Africa in various waves, with the first wave trek parties led by Louis Tregardt, Hans van Rensburg, Hendrik Potgieter, Gerrit Maritz, Piet Retief, and Piet Uys departing from the Cape Colony between September 1835 and April 1837. The first wave of Voortrekkers lasted from 1835 to 1840, during which an estimated 6,000 people trekked. They crossed the Vaal river at Robert's Drift in January 1836. The Great Trek, which the Voortrekkers were a part of, occurred between 1835 and 1847, and the Voortrekkers arrived in South Africa during this period. The Voortrekkers were a group of Dutch settlers who left the British-controlled Cape Colony and settled in the interior of South Africa in the 1830s.
When did the voortrekkers arrive in south africa?
['When did the first wave of voortrekkers arrive in south africa?', 'When did the voortrekkers exploratory treks arrive in south africa?']
[['1836', '1836 onwards'], ['February 1835']]

 90%|█████████ | 18/20 [56:22<05:26, 163.30s/it]

follow question : When did the first wave of voortrekkers arrive in south africa?
short answer : ['1836', '1836 onwards']
{'score': 0.33767300844192505, 'start': 233, 'end': 262, 'answer': 'September 1835 and April 1837'}
follow question : When did the voortrekkers exploratory treks arrive in south africa?
short answer : ['February 1835']
{'score': 0.09463351219892502, 'start': 496, 'end': 517, 'answer': 'between 1835 and 1847'}
{'rougeLsum': 28.742514970059887, 'length': 120.0, 'str_em': 50.0, 'Disambig-F1': 16.666666666666664}
Basic ans: In the 1999 film adaptation of "10 Things I Hate About You", the role of Patrick Verona is played by Heath Ledger. In the 2009 television series adaptation, the role of Patrick Verona is played by Ethan Peck.
Heath Ledger plays Patrick Verona in 10 Things I Hate About You. The film was released on March 31, 1999, and Ledger's performance as the "bad boy" won the hearts of audiences. In the movie, Patrick is hired to date Kat Stratford, but eventually falls in love with her.
Ethan Peck plays Patrick Verona in the TV series 10 Things I Hate About You. He portrays the character as a brooding high school junior who often gets into trouble. This role is a central part of the show's plot, exploring Patrick's complicated relationships with Kat and the other characters.
Not relevant
Not relevant
Not relevant
Not relevant.
Not relevant
Not relevant.
Not relevant.
Not relevant.
['In the 1999 film adaptation of "10 Things I Hate About You", the role of Patrick Verona is played by Heath Ledger. In the 2009 television series adaptation, the role of Patrick Verona is played by Ethan Peck.', 'Heath Ledger plays Patrick Verona in 10 Things I Hate About You. The film was released on March 31, 1999, and Ledger\'s performance as the "bad boy" won the hearts of audiences. In the movie, Patrick is hired to date Kat Stratford, but eventually falls in love with her.', "Ethan Peck plays Patrick Verona in the TV series 10 Things I Hate About You. He portrays the character as a brooding high school junior who often gets into trouble. This role is a central part of the show's plot, exploring Patrick's complicated relationships with Kat and the other characters."]
Final ans: In the 1999 film adaptation of "10 Things I Hate About You", the role of Patrick Verona is played by Heath Ledger. In the 2009 television series adaptation, the role of Patrick Verona is played by Ethan Peck.Heath Ledger plays Patrick Verona in the 1999 film adaptation of "10 Things I Hate About You". In this version, Patrick is hired to date Kat Stratford but eventually falls in love with her. Ethan Peck plays Patrick Verona in the 2009 television series adaptation, portraying the character as a brooding high school junior who often gets into trouble. Both actors bring the character to life in their respective adaptations. The portrayal of Patrick Verona varies between the film and TV series.
Heath Ledger plays Patrick Verona in the 1999 film adaptation of "10 Things I Hate About You". In this version, Patrick is hired to date Kat Stratford but eventually falls in love with her. Ethan Peck plays Patrick Verona in the 2009 television series adaptation, portraying the character as a brooding high school junior who often gets into trouble. Both actors bring the character to life in their respective adaptations. The portrayal of Patrick Verona varies between the film and TV series.
Who plays patrick in 10 things i hate about you?
['Who plays patrick in  the 1999 film 10 things i hate about you?', 'Who plays patrick in the 2009 tv series 10 things i hate about you?', 'Who plays patrick in the film 10 things i hate about you?', 'Who plays patrick in the TV series 10 things i hate about you?']
[['Heath Andrew Ledger', 'Heath Ledger', 'Ledger'], ['Ethan Peck', 'Peck', 'Ethan Gregory Peck'], ['Heath Andrew Ledger', 'Heath Ledger'], ['Ethan Peck', 'Ethan Gregory Peck']]

 95%|█████████▌| 19/20 [57:40<02:17, 137.72s/it]

follow question : Who plays patrick in  the 1999 film 10 things i hate about you?
short answer : ['Heath Andrew Ledger', 'Heath Ledger', 'Ledger']
{'score': 0.9980365037918091, 'start': 0, 'end': 12, 'answer': 'Heath Ledger'}
follow question : Who plays patrick in the 2009 tv series 10 things i hate about you?
short answer : ['Ethan Peck', 'Peck', 'Ethan Gregory Peck']
{'score': 0.9846311807632446, 'start': 190, 'end': 200, 'answer': 'Ethan Peck'}
follow question : Who plays patrick in the film 10 things i hate about you?
short answer : ['Heath Andrew Ledger', 'Heath Ledger']
{'score': 0.9972240924835205, 'start': 0, 'end': 12, 'answer': 'Heath Ledger'}
follow question : Who plays patrick in the TV series 10 things i hate about you?
short answer : ['Ethan Peck', 'Ethan Gregory Peck']
{'score': 0.8490548133850098, 'start': 190, 'end': 200, 'answer': 'Ethan Peck'}
{'rougeLsum': 32.78688524590164, 'length': 82.0, 'str_em': 100.0, 'Disambig-F1': 100.0}
Basic ans: The chief minister of Madhya Pradesh is Kamal Nath of the Indian National Congress, who has been in office since 17 December 2018. He was appointed after the Bharatiya Janata Party (BJP) lost its majority in the state assembly. Before Kamal Nath, the chief ministers of Madhya Pradesh were Digvijaya Singh, Uma Bharti, Babulal Gaur, and Shivraj Singh Chouhan. Babulal Gaur served as the chief minister from 23 August 2004 to 29 November 2005. The current chief minister, Kamal Nath, is the 18th chief minister of Madhya Pradesh.
The current chief minister of Madhya Pradesh is Kamal Nath of the Indian National Congress, who has been in office since 17 December 2018. He was appointed after the Bharatiya Janata Party lost power in the state, and his tenure is still ongoing. He is serving as the chief minister of Madhya Pradesh for the Fifteenth Assembly.
The chief minister of Maharashtra is currently Uddhav Balasaheb Thackeray of the Shiv Sena. He was appointed on 28 November 2019 and his term is still ongoing. He serves at Mantralaya, Mumbai, and resides at Varsha Bungalow, Malabar Hill, Mumbai.
Uma Bharti was the Chief Minister of Madhya Pradesh before Babulal Gaur, and Babulal Gaur served as the Chief Minister from 23 August 2004 to 29 November 2005. After that, Shivraj Singh Chouhan succeeded Gaur as the Chief Minister.
M. Karunanidhi was the Chief Minister of Tamil Nadu, not Madhya Pradesh. He held the position multiple times from 1969 to 2011, serving a total of five terms.
Not relevant
Not relevant
Not relevant.
Not relevant.
Harsh Vardhan was the Chief Ministerial candidate for the BJP in the 2013 Delhi assembly election but the BJP did not form the government. He was named the Chief Minister candidate for Delhi Assembly elections by the BJP on 23 October 2013.
Sucheta Kripalani was the first female Chief Minister of Uttar Pradesh, not Madhya Pradesh. She served as the Chief Minister of Uttar Pradesh, not Madhya Pradesh.
['The chief minister of Madhya Pradesh is Kamal Nath of the Indian National Congress, who has been in office since 17 December 2018. He was appointed after the Bharatiya Janata Party (BJP) lost its majority in the state assembly. Before Kamal Nath, the chief ministers of Madhya Pradesh were Digvijaya Singh, Uma Bharti, Babulal Gaur, and Shivraj Singh Chouhan. Babulal Gaur served as the chief minister from 23 August 2004 to 29 November 2005. The current chief minister, Kamal Nath, is the 18th chief minister of Madhya Pradesh.', 'The current chief minister of Madhya Pradesh is Kamal Nath of the Indian National Congress, who has been in office since 17 December 2018. He was appointed after the Bharatiya Janata Party lost power in the state, and his tenure is still ongoing. He is serving as the chief minister of Madhya Pradesh for the Fifteenth Assembly.', 'The chief minister of Maharashtra is currently Uddhav Balasaheb Thackeray of the Shiv Sena. He was appointed on 28 November 2019 and his term is still ongoing. He serves at Mantralaya, Mumbai, and resides at Varsha Bungalow, Malabar Hill, Mumbai.', 'Uma Bharti was the Chief Minister of Madhya Pradesh before Babulal Gaur, and Babulal Gaur served as the Chief Minister from 23 August 2004 to 29 November 2005. After that, Shivraj Singh Chouhan succeeded Gaur as the Chief Minister.', 'M. Karunanidhi was the Chief Minister of Tamil Nadu, not Madhya Pradesh. He held the position multiple times from 1969 to 2011, serving a total of five terms.', 'Harsh Vardhan was the Chief Ministerial candidate for the BJP in the 2013 Delhi assembly election but the BJP did not form the government. He was named the Chief Minister candidate for Delhi Assembly elections by the BJP on 23 October 2013.', 'Sucheta Kripalani was the first female Chief Minister of Uttar Pradesh, not Madhya Pradesh. She served as the Chief Minister of Uttar Pradesh, not Madhya Pradesh.']
Final ans: The chief minister of Madhya Pradesh is Kamal Nath of the Indian National Congress, who has been in office since 17 December 2018. He was appointed after the Bharatiya Janata Party (BJP) lost its majority in the state assembly. Before Kamal Nath, the chief ministers of Madhya Pradesh were Digvijaya Singh, Uma Bharti, Babulal Gaur, and Shivraj Singh Chouhan. Babulal Gaur served as the chief minister from 23 August 2004 to 29 November 2005. The current chief minister, Kamal Nath, is the 18th chief minister of Madhya Pradesh.The chief minister of Madhya Pradesh is Kamal Nath of the Indian National Congress, who has been in office since 17 December 2018. He was appointed after the Bharatiya Janata Party lost its majority in the state assembly. As of the information, Kamal Nath is the 18th chief minister of Madhya Pradesh. However, it is also possible that you are referring to the previous chief ministers of Madhya Pradesh, such as Digvijaya Singh, Uma Bharti, Babulal Gaur, and Shivraj Singh Chouhan. Babulal Gaur served as the chief minister from 23 August 2004 to 29 November 2005.
The chief minister of Madhya Pradesh is Kamal Nath of the Indian National Congress, who has been in office since 17 December 2018. He was appointed after the Bharatiya Janata Party lost its majority in the state assembly. As of the information, Kamal Nath is the 18th chief minister of Madhya Pradesh. However, it is also possible that you are referring to the previous chief ministers of Madhya Pradesh, such as Digvijaya Singh, Uma Bharti, Babulal Gaur, and Shivraj Singh Chouhan. Babulal Gaur served as the chief minister from 23 August 2004 to 29 November 2005.
Who is the chief minister of m. p?
['Who is the 17th Chief Minister of MP?', 'Who is the 16th Chief Minister of MP?', 'Who is the 15th Chief Minister of MP?', 'Who is the 17th chief minister of m. p?', 'Who is the 16th chief minister of m. p?', 'Who is the 15th chief minister of m. p?']
[['Shivraj Singh Chauhan'], ['Babulal Gaur'], ['Uma Bharti'], ['Shivraj Singh Chauhan'], ['Babulal Gaur', 'Babulal Gaur Yadav'], ['Uma Bharti']]
follow question : Who is the 17th Chief Minister of MP?
short answer : ['Shivraj Singh Chauhan']
{'score': 2.1651833321811864e-06, 'start': 40, 'end': 50, 'answer': 'Kamal Nath'}
follow question : Who is the 16th Chief Minister of MP?
short answer : ['Babulal Gaur']
{'score': 9.04875605556299e-08, 'start': 40, 'end': 50, 'answer': 'Kamal Nath'}
follow question : Who is the 15th Chief Minister of MP?
short answer : ['Uma Bharti']
{'score': 7.883691210963661e-08, 'start': 40, 'end': 50, 'answer': 'Kamal Nath'}
follow question : Who is the 17th chief minister of m. p?
short answer : ['Shivraj Singh Chauhan']
{'score': 4.55959678902218e-07, 'start': 40, 'end': 50, 'answer': 'Kamal Nath'}
follow question : Who is the 16th chief minister of m. p?
short answer : ['Babulal Gaur', 'Babulal Gaur Yadav']

100%|██████████| 20/20 [59:49<00:00, 179.47s/it]

{'score': 4.633776029550063e-08, 'start': 40, 'end': 50, 'answer': 'Kamal Nath'}
follow question : Who is the 15th chief minister of m. p?
short answer : ['Uma Bharti']
{'score': 3.4664896730873807e-08, 'start': 40, 'end': 50, 'answer': 'Kamal Nath'}
{'rougeLsum': 48.40764331210191, 'length': 96.0, 'str_em': 66.66666666666666, 'Disambig-F1': 0.0}

rougeLsum       35.940787
length         106.200000
str_em          64.166667
Disambig-F1     46.714286
dtype: float64

In [29]:
query="Who has the highest goals in world football?"

In [30]:
first_ans=["Ali Daei holds the record for the highest number of international goals with 109 goals for Iran, surpassing Ferenc Puskás' record of 84 goals. Cristiano Ronaldo has scored 1030 goals in his career, the highest among active players, with a total of 738 goals in his international career. Miroslav Klose holds the record for most World Cup goals with 16 goals, while Gerd Müller used to be the holder of that record from 1974 until it was broken by Ronaldo in 2006. Pelé scored 77 international goals, the highest among players from outside Europe, and Jürgen Klinsmann scored 11 goals in the World Cup, the highest among players from Germany. The top goalscorers in the World Cup history are Ali Daei, Cristiano Ronaldo, Ferenc Puskás, Kunishige Kamamoto, Godfrey Chitalu, Hussein Saeed, and Zainal Abidin, among others.",
 "Ali Daei has the highest goals in world football with 109 international goals. He achieved this feat in his career span of 1993–2006, scoring his 50th goal on 9 January 2000. As of 2 December 2019, he holds the record for the most international goals scored.Ferenc Puskás of Hungary was the second player to achieve the feat, scoring 84 international goals. He scored his 50th goal on 24 July 1952, and his record remained unbroken for 47 years until Ali Daei broke it in 2003. Puskás held the record for the most international goals scored by a European player.Pelé of Brazil was the first player from outside Europe to score at least 50 goals, achieving the feat on 21 November 1965. He scored 77 international goals in his career span of 1957–1971. Pelé's record for the most international goals scored by a South American player was later surpassed by other players.Bader Al-Mutawa of Kuwait played the most matches to score 50 international goals, achieving the feat on 3 September 2015. He scored a hat-trick against Myanmar in the 2018 FIFA World Cup qualification matches.",
 'Josef Bican has the highest goals in world football with a total of 805 goals. He achieved this record between 1928 and 1955. Bican played for various clubs and national teams during his career.',
 'Ali Daei of Iran holds the record for the highest goals in international football with 109 goals, surpassing Ferenc Puskás of Hungary who had held the record for 47 years. He achieved this feat on 17 November 2004, when he scored a hat-trick against Laos in the 2006 FIFA World Cup qualification. This record is as of 2 December 2019.',
 "Miroslav Klose holds the record for the most goals in the World Cup, with 16 goals across four consecutive tournaments between 2002 and 2014. His record stood for more than three decades until it was surpassed by another player. Klose's achievement is considered one of the most impressive in the history of the World Cup.Ronaldo is the second-highest goalscorer in the World Cup, with 15 goals between 1998 and 2006 for Brazil. He broke the overall record when he scored his 14th goal in the World Cup final tournament during West Germany's win in the 1974 final. His record stood for more than three decades until Klose surpassed him.The top 97 goalscorers have represented 28 nations, with 14 players scoring for Brazil, and another 14 for Germany or West Germany. In total, 64 footballers came from UEFA (Europe), 29 from CONMEBOL (South America), and only four from elsewhere.",
 "Ali Daei holds the record for the highest goals in world football with 109 international goals as of 2 December 2019. He achieved this feat while playing for Iran, a country with a rich football history. This impressive record showcases Daei's exceptional skill and dedication to the sport.",
 'Christine Sinclair has the highest goals in world football among the listed players with 185 international goals. She achieved this milestone in just under 10 years of her active years, which started in 2000 and is still ongoing. As of 29 January 2020, she holds the record for the highest number of international goals.The top scorer of the respective nation is also a part of the list, however, it is not a direct answer to the query.',
 'Cristiano Ronaldo has the highest goals in the UEFA Champions League with 128 goals. He achieved this milestone throughout his career, starting from 2003 and playing for Manchester United, Real Madrid, and Juventus. As of February 1, 2020, his record remains unmatched in the competition.This information is relevant to the List of UEFA Champions League top scorers, which provides a comprehensive overview of the top goal scorers in the competition.',
 'Miroslav Klose has the highest goals in world football with a total of 16 goals scored in the finals of the FIFA World Cup. He achieved this record throughout his career spanning from 2002 to 2014. His impressive goal-scoring record earned him a place in the history of the FIFA World Cup.',
 'France has the highest number of own goals in favor of a team in one tournament, with 2 own goals in the 2014 and 2018 tournaments. France also holds the record for the most own goals in favor of a team overall, with 6 own goals. The team with the most own goals overall is Mexico, with 4 own goals.',
 "Miroslav Klose of Germany has the highest goals in world football with 16 goals, surpassing Ronaldo of Brazil's record of 15 goals. He achieved this milestone during the 2014 World Cup, specifically in the semi-final match against Brazil. This impressive feat earned him the top spot among all-time World Cup scorers."]

In [31]:
basic_ans="Ali Daei holds the record for the highest number of international goals with 109 goals for Iran, surpassing Ferenc Puskás' record of 84 goals. Cristiano Ronaldo has scored 1030 goals in his career, the highest among active players, with a total of 738 goals in his international career. Miroslav Klose holds the record for most World Cup goals with 16 goals, while Gerd Müller used to be the holder of that record from 1974 until it was broken by Ronaldo in 2006. Pelé scored 77 international goals, the highest among players from outside Europe, and Jürgen Klinsmann scored 11 goals in the World Cup, the highest among players from Germany. The top goalscorers in the World Cup history are Ali Daei, Cristiano Ronaldo, Ferenc Puskás, Kunishige Kamamoto, Godfrey Chitalu, Hussein Saeed, and Zainal Abidin, among others."

In [31]:
set_seed(24)
final_ans=total_answer(query, first_ans)
final_ans

'Ali Daei holds the record for the highest goals in world football with 109 international goals as of 2 December 2019. Josef Bican has the highest goals in world football with a total of 805 goals achieved between 1928 and 1955. However, Ali Daei of Iran holds the record for the highest goals in international football with 109 goals, surpassing Ferenc Puskás of Hungary who had held the record for 47 years. Christine Sinclair has the highest goals in world football among the listed players with 185 international goals, making her the top scorer.'

In [34]:
from evaluation import evaluate
scores=evaluate([final_ans], [row.to_dict()])
scores

Ali Daei holds the record for the highest goals in world football with 109 international goals as of 2 December 2019. Josef Bican has the highest goals in world football with a total of 805 goals achieved between 1928 and 1955. However, Ali Daei of Iran holds the record for the highest goals in international football with 109 goals, surpassing Ferenc Puskás of Hungary who had held the record for 47 years. Christine Sinclair has the highest goals in world football among the listed players with 185 international goals, making her the top scorer.
Who has the highest goals in world football?
["Who has the highest goals in men's world international football?", "Who has the highest goals all-time in men's football?", "Who has the highest goals in women's world international football?"]
[['Daei', 'Ali Daei'], ['Bican', 'Josef Bican'], ['Sinclair', 'Christine Sinclair']]
follow question : Who has the highest goals in men's world international football?
short answer : ['Daei', 'Ali Daei']
{'score': 0.278212308883667, 'start': 118, 'end': 129, 'answer': 'Josef Bican'}
follow question : Who has the highest goals all-time in men's football?
short answer : ['Bican', 'Josef Bican']
{'score': 0.0021326811984181404, 'start': 118, 'end': 129, 'answer': 'Josef Bican'}
follow question : Who has the highest goals in women's world international football?
short answer : ['Sinclair', 'Christine Sinclair']
{'score': 0.9738244414329529, 'start': 409, 'end': 427, 'answer': 'Christine Sinclair'}

{'rougeLsum': 48.484848484848484,
 'length': 94.0,
 'str_em': 100.0,
 'Disambig-F1': 66.66666666666666}

In [50]:
# scores_df.to_csv('./results/titleRAG_0218_results.csv', index=False)
import pandas as pd
import math
sf = pd.read_csv('results/titleRAG_0218_results.csv')
sf=sf[sf['length']<1000][:100]
print(len(sf))
print(sf.mean())
r=sf.mean()['rougeLsum']
d=sf.mean()['Disambig-F1']
dr=math.sqrt(r*d)
print(dr)

20
rougeLsum       34.604354
length         104.550000
str_em          54.166667
Disambig-F1     46.166667
dtype: float64
39.96958463256686

In [ ]:
import pandas as pd
import math
sf = pd.read_csv('results/basicRAG_seed24-len20-title_results.csv')
sf=sf[sf['length']<1000][:100]
print(len(sf))
print(sf.mean())
r=sf.mean()['rougeLsum']
d=sf.mean()['Disambig-F1']
dr=math.sqrt(r*d)
print(dr)

# Answer RAG

In [30]:
def hyde_query(query):
    prompt = """
    Create text that can answer the following question: Question: {0} Answer:
    """.format(query)
    input_ids = tokenizer_gen.apply_chat_template([{"role":'user', "content":prompt}], return_tensors='pt').to(device1)

    attention_mask = (input_ids != tokenizer_gen.pad_token_id).long().to(device1)

    out = model_gen.generate(input_ids, attention_mask=attention_mask, pad_token_id=tokenizer_gen.pad_token_id, max_new_tokens = 1024)
    res = tokenizer_gen.decode(out[0]).split('<|end_header_id|>')[-1] 
    return re.sub('\n|<\|eot_id\|>', '', res)

In [ ]:
docs=[]
for _ in range(1):
    docs.append(hyde_query("Who has the highet goals in world football?"))
docs

["The highest goals in world football are held by Brazilian legend, Pelé, who scored an impressive 772 goals in 891 appearances throughout his career. However, it's essential to note that the accuracy of Pelé's goals may be disputed due to the lack of official records from his early years.The player with the second-highest goals in world football is Argentine legend, Lionel Messi, who has scored over 770 goals in around 912 appearances. Messi's impressive goal-scoring record has earned him numerous accolades, including seven Ballon d'Or awards.Other notable players who have achieved high goal-scoring records include:- Josef Bican (Austria): 805 goals in 529 appearances- Ferenc Puskás (Hungary): 746 goals in 629 appearances- Gerd Müller (Germany): 735 goals in 706 appearances- Roberto Baggio (Italy): 707 goals in 758 appearances- Alfredo Di Stéfano (Argentina/Spain): 694 goals in 659 appearancesThese players have all achieved incredible feats in the world of football, and their records continue to inspire and motivate new generations of players and fans alike."]

In [34]:
def hyde_answer(ans):
    prompt = """
    Create a text that can ask questions in the following answers. Answer: {0} Question:
    """.format(ans)
    input_ids = tokenizer_gen.apply_chat_template([{"role":'user', "content":prompt}], return_tensors='pt').to(device1)

    attention_mask = (input_ids != tokenizer_gen.pad_token_id).long().to(device1)

    out = model_gen.generate(input_ids, attention_mask=attention_mask, pad_token_id=tokenizer_gen.pad_token_id, max_new_tokens = 1024)
    res = tokenizer_gen.decode(out[0]).split('<|end_header_id|>')[-1] 
    return re.sub('\n|<\|eot_id\|>', '', res)

In [152]:
from tqdm import tqdm
from evaluation import evaluate

set_seed(24)

stop_iteration = 20

scores_list=[]
retrival_list=[]
for idx, row in tqdm(qa_df.iterrows(), total=min([stop_iteration, len(qa_df)])):
    if idx == stop_iteration: break
    query = row['question']
    
    retrieved_docs, doc_ids = retrieve_documents(query)
    tmp1=0
    for doc_id in doc_ids:    
        tmp1+=match_sample_id(idx, doc_id)
    first_retrival=tmp1/len(retrieved_docs)
    print("First Retrival Match Rate:", first_retrival)
    
    dic=dict()
    dic['first_retrival']=first_retrival
    
    first_ans=total_answer(query,retrieved_docs)
    print('First ans:', first_ans)
    
    # hyde_ans_list=hyde(query,first_ans)
    # print(hyde_ans_list)
    
    virtual_ans=hyde_answer(first_ans)
    print(virtual_ans)
    
    ans_docs, doc_ids=retrieve_documents(virtual_ans)
    
    tmp2=0
    for doc_id in doc_ids:    
        tmp2+=match_sample_id(idx, doc_id)
    
    second_retrival=tmp2/len(ans_docs)
    print("Second Retrival Match Rate:", second_retrival)
    
    dic['second_retrival']=second_retrival
    
    final_ans=total_answer(query, ans_docs)
    print('Second ans:', final_ans)
    scores=evaluate([final_ans], [row.to_dict()])
    scores_list.append(scores)
    scores_df=pd.DataFrame(scores_list)
    print(scores)
    retrival_list.append(dic)
    retrival_df=pd.DataFrame(retrival_list)
    print(dic)
        
scores_df=pd.DataFrame(scores_list)
scores_df.mean()

retrival_df=pd.DataFrame(retrival_list)
retrival_df.mean()

  0%|          | 0/20 [00:00<?, ?it/s]

First Retrival Match Rate: 0.5

  0%|          | 0/20 [00:03<?, ?it/s]

KeyboardInterrupt:

In [39]:
scores_df.to_csv('./results/0211answer_results.csv', index=False)
import pandas as pd
import math
sf = pd.read_csv('results/0211answer_results.csv')
sf=sf[sf['length']<1000][:100]
print(len(sf))
print(sf.mean())
r=sf.mean()['rougeLsum']
d=sf.mean()['Disambig-F1']
dr=math.sqrt(r*d)
print(dr)

19
rougeLsum      38.764659
length         86.526316
str_em         58.333333
Disambig-F1    45.701754
dtype: float64
42.09053249441862

In [54]:
def answer_2020(query, context):
    prompt = """
    Context information is below.
    ---------------------
    {0}
    ---------------------
    Given the context information and not prior knowledge, answer this ambiuous question.
    1. You should include in answer the content according to the various interpretations of the question
    2. When using time-related information to answer the question, only use information before February 1, 2020.
    3. If you can’t answer the question, say "Not relevant" only.
    4. Answers to questions should be no longer than 3 sentences.
    Do not comment your answer and strictly follow this instructions.
    Query: {1}
    Answer:
    """.format('\n'.join(context), query)
    input_ids = tokenizer_gen.apply_chat_template([{"role":'user', "content":prompt}], return_tensors='pt').to(device1)

    attention_mask = (input_ids != tokenizer_gen.pad_token_id).long().to(device1)

    out = model_gen.generate(input_ids, attention_mask=attention_mask, pad_token_id=tokenizer_gen.pad_token_id, max_new_tokens = 512)
    res = tokenizer_gen.decode(out[0]).split('<|end_header_id|>')[-1] 
    return re.sub('\n|<\|eot_id\|>', '', res)

In [134]:
for i in range(600,1000):
    res=evidence_df['text'][i].split('Document: ')[-1].split('\n')[0].split('/')[0].split('# ')[-1].split(' #')[0]
    print(res)

The Fast Saga
The Fast Saga
The Fast Saga
The Fast Saga
The Fast Saga
The Fast Saga
The Fast Saga
The Fast Saga
The Fast and the Furious (2001 film)
The Fast and the Furious (2001 film)
The Fast and the Furious (2001 film)
The Fast and the Furious (2001 film)
The Fast and the Furious (2001 film)
The Fast and the Furious (2001 film)
The Fast and the Furious (2001 film)
The Fast and the Furious: Tokyo Drift
The Fast and the Furious: Tokyo Drift
The Fast and the Furious: Tokyo Drift
The Fast and the Furious: Tokyo Drift
The Fast and the Furious: Tokyo Drift
I'm Coming Out
I'm Coming Out
I'm Coming Out
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
List of Dragon Ball Super episodes
First Epistle to the Thessalonians
First Epistle to the Thessalonians
First Epistle to the Thessalonians
Second Epistle to the Thessalonians
Second Epistle to the Thessalonians
Second Epistle to the Thessalonians
Second Epistle to the Thessalonians
Second Epistle to the Thessalonians
Second Epistle to the Thessalonians
Authorship of the Pauline epistles

In [139]:
eval_df[eval_df['title'].isin(["I'm Coming Out"])]

,sample_id,title,text
624,3421083040429613594,I'm Coming Out,"Document: I'm Coming Out\n\n""I'm Coming Out"":F..."
625,3421083040429613594,I'm Coming Out,Document: I'm Coming Out\n\n## Trombone solo #...
626,3421083040429613594,I'm Coming Out,Document: I'm Coming Out\n\n## Amerie version ...

In [122]:
evidence_df['text'][67]

'# Sound of Silence (Dami Im song) #\n\n\nTitle: Fighting for Love\nDescription: SinglebyDami Im\n\nFields:\nReleased: 11 March 2016\nRecorded: 2016\nGenre: Pop\nLength: 3:15\nLabel: Sony\nSongwriter(s): Anthony EgiziiDavid Musumeci\nProducer(s): DNA\nCountry: Australia\nArtist(s): Dami Im\nLanguage: English\nComposer(s): Anthony Egizii, David Musumeci\nLyricist(s): Anthony Egizii, David Musumeci\nSemi-final result: 1st\nSemi-final points: 330\nFinal result: 2nd\nFinal points: 511\n\nSingles Chronology:\nSmile (2015)\n"Sound of Silence"(2016) (2016)\nFighting for Love (2016)\n\nExternal Links:\n"Sound of Silence": https://www.youtube.com/watch?v=2EG_Jtw4OyU\n"Sound of Silence" is a song performed by Australian recording artist Dami Im.[2] Written by Anthony Egizii and David Musumeci of DNA Songs, it is best known as Australia\'s entry at the Eurovision Song Contest 2016 which was held in Stockholm, Sweden, where it finished 2nd, receiving a total of 511 points.[3][4][5] The song also won the Marcel Bezençon Award in the composer category. The song was leaked on 10 March 2016, one day before its initial release date.[6] It is Dami Im\'s fourth Australian top 20 hit and worldwide, it reached the top 40 in more than six countries after the Eurovision Song Contest 2016 Final.\n\n## Track listing ##\nOther versions (Sony promo release):\n* Glamstarr Club Mix – 6:26\n* Glamstarr Radio Edit – 3:49\n* Glamstarr Instrumental – 6:26\n## Charts ##\nChart (2016):5\n----\nChart (2016):39\n----\nChart (2016):10\n----\nChart (2016):11\n----\nChart (2016):69\n----\nChart (2016):57\n----\nChart (2016):9\n----\nChart (2016):100\n----\nChart (2016):53\n----\nChart (2016):37\n----\nChart (2016):17\n----\nChart (2016):55\n----\nChart (2016):54\n----\nChart (2016):160\n## Certifications ##\nRegion:Platinum\nCertification:70,000‡\n----\nRegion:Gold\nCertification:20,000‡\n----\nRegion:^Shipments figures based on certification alone.\nCertification:^Shipments figures based on certification alone.\nCertified units/sales:^Shipments figures based on certification alone.\n## References ##\n'

In [141]:
evidence_df['title'] = evidence_df['text'].apply(lambda x: x.split('Document: ')[-1].split('\n')[0].split('/')[0].split('# ')[-1].split(' #')[0])

In [143]:
evidence_df['title'][67]

'Sound of Silence (Dami Im song)'

In [144]:
# evidence_df.to_csv(f'{data_dir}/test/evidence_test2.csv',index=False)

In [69]:
def virtual_answer(query, context):
    prompt = """
    Context information is below.
    ---------------------
    {0}
    ---------------------
    Given the context information and not prior knowledge, answer this ambiuous question.
    1. The answer is an answer to an ambiguous query.
    2. Generate an answer to a query with the same structure as the answer.
    Do not comment your answer and strictly follow this instructions.
    Query: {1}
    Answer:
    """.format('\n'.join(context), query)
    input_ids = tokenizer_gen.apply_chat_template([{"role":'user', "content":prompt}], return_tensors='pt').to(device1)

    attention_mask = (input_ids != tokenizer_gen.pad_token_id).long().to(device1)

    out = model_gen.generate(input_ids, attention_mask=attention_mask, pad_token_id=tokenizer_gen.pad_token_id, max_new_tokens = 512)
    res = tokenizer_gen.decode(out[0]).split('<|end_header_id|>')[-1] 
    return re.sub('\n|<\|eot_id\|>', '', res)

In [165]:
from tqdm import tqdm
from evaluation import evaluate

set_seed(24)

stop_iteration = 20

scores_list=[]
retrival_list=[]
for idx, row in tqdm(qa_df.iterrows(), total=min([stop_iteration, len(qa_df)])):
    if idx == stop_iteration: break
    query = row['question']
    
    retrieved_docs, doc_ids = retrieve_documents(query)
    tmp1=0
    for doc_id in doc_ids:    
        tmp1+=match_sample_id(idx, doc_id)
    
    dic=dict()
    
    first_retrival=tmp1/len(retrieved_docs)
    print("First Document Match Rate:", first_retrival)
    dic['first_doc_retrival']=first_retrival
    
    title_retival_rate=cal_sample_title(idx, retrieved_docs)
    print("First Title Match Rate:", title_retival_rate)
    dic['first_title_retrival']=title_retival_rate
    
    first_ans=total_answer(query,retrieved_docs)
    print("First ans: ", first_ans)

    ans_docs, doc_ids=retrieve_documents(first_ans)
    
    tmp1=0
    for doc_id in doc_ids:    
        tmp1+=match_sample_id(idx, doc_id)
    
    second_retrival=tmp1/len(ans_docs)
    print("Second Document Match Rate:", second_retrival)
    dic['second_doc_retrival']=second_retrival
    
    title_retival_rate=cal_sample_title(idx, ans_docs)
    print("Second Title Match Rate:", title_retival_rate)
    dic['second_title_retrival']=title_retival_rate
    
    final_ans=answer(query, ans_docs)
    print("Final ans: ", final_ans)
    
    scores=evaluate([final_ans], [row.to_dict()])
    scores_list.append(scores)
    scores_df=pd.DataFrame(scores_list)
    print(scores)
    # scores_df.to_csv('./results/answer_rag_0219_seed24_results.csv', index=False)
    
    retrival_list.append(dic)
    retrival_df=pd.DataFrame(retrival_list)
    print(dic)
        
scores_df=pd.DataFrame(scores_list)
print(scores_df.mean())
# scores_df.to_csv('./results/answer_rag_0219_seed24_results.csv', index=False)

retrival_df=pd.DataFrame(retrival_list)
print(retrival_df.mean())

  0%|          | 0/20 [00:00<?, ?it/s]/home/dataconv/.cache/huggingface/modules/transformers_modules/nvidia/NV-Embed-v2/5130cf1daf847c1bacee854a6ef1ca939e747fb2/modeling_nvembed.py:349: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'input_ids': torch.tensor(batch_dict.get('input_ids').to(batch_dict.get('input_ids')).long()),
/home/dataconv/anaconda3/envs/sf_rag_djk/lib/python3.10/contextlib.py:103: FutureWarning: `torch.backends.cuda.sdp_kernel()` is deprecated. In the future, this context manager will be removed. Please see `torch.nn.attention.sdpa_kernel()` for the new context manager, with updated signature.
  self.gen = func(*args, **kwds)

First Document Match Rate: 0.5
['List of FIFA World Cup records and statistics'
 'List of footballers with more than 50 international goals'
 'List of footballers with 500 or more goals'
 'List of footballers with 500 or more goals'
 'List of footballers with 500 or more goals'
 "List of top international men's association football goal scorers by ..."
 "List of men's footballers with 50 or more international goals"
 'Football records and statistics in Spain'
 'Germany at the FIFA World Cup' 'FIFA World Cup top goalscorers']
{'International Federation of Football History & Statistics', 'List of footballers with more than 50 international goals', 'List of footballers with 500 or more goals', 'List of FIFA World Cup records and statistics', "List of women's footballers with 100 or more international goals ..."}
First Title Match Rate: 0.6
First ans:  Ali Daei holds the record for the highest number of international goals with 109 goals for Iran, surpassing Ferenc Puskás' record of 84 goals. Cristiano Ronaldo has scored 1030 goals in his career, the highest among active players, with a total of 738 goals in his international career. Miroslav Klose holds the record for most World Cup goals with 16 goals, while Gerd Müller used to be the holder of that record from 1974 until it was broken by Ronaldo in 2006. Pelé scored 77 international goals, the highest among players from outside Europe, and Jürgen Klinsmann scored 11 goals in the World Cup, the highest among players from Germany. The top goalscorers in the World Cup history are Ali Daei, Cristiano Ronaldo, Ferenc Puskás, Kunishige Kamamoto, Godfrey Chitalu, Hussein Saeed, and Zainal Abidin, among others.
Second Document Match Rate: 0.5
['List of FIFA World Cup records and statistics'
 'List of FIFA World Cup records and statistics'
 'List of FIFA World Cup records and statistics'
 'List of footballers with more than 50 international goals'
 'List of footballers with 500 or more goals'
 "List of top international men's association football goal scorers by ..."
 "List of men's footballers with 50 or more international goals"
 'Germany at the FIFA World Cup' 'FIFA World Cup top goalscorers'
 'FIFA World Cup top goalscorers']
{'International Federation of Football History & Statistics', 'List of footballers with more than 50 international goals', 'List of footballers with 500 or more goals', 'List of FIFA World Cup records and statistics', "List of women's footballers with 100 or more international goals ..."}
Second Title Match Rate: 0.6
Final ans:  Based on the provided context information, Josef Bican has the highest goals in world football with 805 goals.
Based on the provided context information, Josef Bican has the highest goals in world football with 805 goals.
Who has the highest goals in world football?
["Who has the highest goals in men's world international football?", "Who has the highest goals all-time in men's football?", "Who has the highest goals in women's world international football?"]
[['Daei', 'Ali Daei'], ['Bican', 'Josef Bican'], ['Sinclair', 'Christine Sinclair']]

  5%|▌         | 1/20 [00:47<15:06, 47.70s/it]

follow question : Who has the highest goals in men's world international football?
short answer : ['Daei', 'Ali Daei']
{'score': 0.9853910803794861, 'start': 43, 'end': 54, 'answer': 'Josef Bican'}
follow question : Who has the highest goals all-time in men's football?
short answer : ['Bican', 'Josef Bican']
{'score': 0.9467952251434326, 'start': 43, 'end': 54, 'answer': 'Josef Bican'}
follow question : Who has the highest goals in women's world international football?
short answer : ['Sinclair', 'Christine Sinclair']
{'score': 0.984576404094696, 'start': 43, 'end': 54, 'answer': 'Josef Bican'}
{'rougeLsum': 41.37931034482759, 'length': 18.0, 'str_em': 33.33333333333333, 'Disambig-F1': 33.33333333333333}
{'first_doc_retrival': 0.5, 'first_title_retrival': 0.6, 'second_doc_retrival': 0.5, 'second_title_retrival': 0.6}
First Document Match Rate: 1.0
['The Sound of Silence' 'The Sound of Silence' 'The Sound of Silence'
 'The Sound of Silence' 'The Sound of Silence' 'The Sound of Silence'
 'The Sound of Silence' 'Sounds of Silence' 'Sounds of Silence'
 'Sound of Silence (Dami Im song)']
{'The Sound of Silence', 'Sound of Silence (Dami Im song)', 'Sounds of Silence'}
First Title Match Rate: 1.0
First ans:  The original artist of "Sound of Silence" is Simon & Garfunkel, an American music duo composed of Paul Simon and Art Garfunkel. The song was written by Paul Simon, and the duo recorded it in March 1964 for their debut album, Wednesday Morning, 3 A.M. The song was later re-recorded with electric instruments and released as a single in September 1965, which became a huge success and reached number one on the Billboard Hot 100 chart. Simon & Garfunkel's version of "Sound of Silence" is considered a classic folk rock song and has been added to the National Recording Registry in the Library of Congress.
Second Document Match Rate: 1.0
['The Sound of Silence' 'The Sound of Silence' 'The Sound of Silence'
 'The Sound of Silence' 'The Sound of Silence' 'The Sound of Silence'
 'The Sound of Silence' 'Sounds of Silence' 'Sounds of Silence'
 'Sound of Silence (Dami Im song)']
{'The Sound of Silence', 'Sound of Silence (Dami Im song)', 'Sounds of Silence'}
Second Title Match Rate: 1.0
Final ans:  The original artist of "The Sound of Silence" is Simon & Garfunkel, a musical duo composed of Paul Simon and Art Garfunkel.
The original artist of "The Sound of Silence" is Simon & Garfunkel, a musical duo composed of Paul Simon and Art Garfunkel.
Who is the original artist of sound of silence?
['Who is the original artist of sound of silence, the song, released in 1964?', 'Who is the original artist of sound of silence, the album?', 'Who is the original artist of sound of silence, the song, released in 2016?']
[['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon'], ['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon'], ['Dami Im']]

 10%|█         | 2/20 [01:22<12:04, 40.25s/it]

follow question : Who is the original artist of sound of silence, the song, released in 1964?
short answer : ['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon']
{'score': 0.8265178203582764, 'start': 49, 'end': 66, 'answer': 'Simon & Garfunkel'}
follow question : Who is the original artist of sound of silence, the album?
short answer : ['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon']
{'score': 0.9214609265327454, 'start': 49, 'end': 66, 'answer': 'Simon & Garfunkel'}
follow question : Who is the original artist of sound of silence, the song, released in 2016?
short answer : ['Dami Im']
{'score': 0.9067099690437317, 'start': 49, 'end': 66, 'answer': 'Simon & Garfunkel'}
{'rougeLsum': 38.46153846153846, 'length': 22.0, 'str_em': 66.66666666666666, 'Disambig-F1': 66.66666666666666}
{'first_doc_retrival': 1.0, 'first_title_retrival': 1.0, 'second_doc_retrival': 1.0, 'second_title_retrival': 1.0}
First Document Match Rate: 0.9
['iPhone (1st generation)' 'iPhone (1st generation)'
 'iPhone (1st generation)' 'History of iPhone' 'History of iPhone'
 'iPhone' 'iPhone' 'iPhone' 'iPhone' 'iPhone']
{'History of iPhone', 'iPhone', 'iPhone (1st generation)'}
First Title Match Rate: 1.0
First ans:  The first iPhone was announced by Steve Jobs on January 9, 2007, and was released to the public on June 29, 2007. The development of the iPhone began in 2004, and it was created during a secretive collaboration with Cingular Wireless (now AT&T Mobility) at an estimated development cost of US$150 million over thirty months. The iPhone was initially available in the US, UK, Canada, Germany, Norway, Sweden, Finland, France, Spain, Italy, and South Africa. The first generation iPhone was discontinued on July 15, 2008, and was replaced by the iPhone 3G. The iPhone was a revolutionary device that combined a mobile phone, an iPod, and an internet communications device into one product.
Second Document Match Rate: 0.9
['iPhone (1st generation)' 'iPhone (1st generation)'
 'iPhone (1st generation)' 'History of iPhone' 'History of iPhone'
 'History of iPhone' 'History of iPhone' 'iPhone' 'iPhone' 'iPhone']
{'History of iPhone', 'iPhone', 'iPhone (1st generation)'}
Second Title Match Rate: 1.0
Final ans:  The first Apple iPhone was conceived in 2005, and its development began in that year. The original iPhone was officially launched and made accessible to the public in 2007.
The first Apple iPhone was conceived in 2005, and its development began in that year. The original iPhone was officially launched and made accessible to the public in 2007.
When was the first apple i phone made?
['When was the first apple i phone released?', 'When was the first apple i phone for beta testing made?', 'When was the first apple i phone 1 made?', 'When was the first apple i phone beta made?']
[['June 29, 2007'], ['2004'], ['June 29, 2007.'], ['2004.']]

 15%|█▌        | 3/20 [02:05<11:40, 41.19s/it]

follow question : When was the first apple i phone released?
short answer : ['June 29, 2007']
{'score': 0.9618066549301147, 'start': 167, 'end': 171, 'answer': '2007'}
follow question : When was the first apple i phone for beta testing made?
short answer : ['2004']
{'score': 2.1161393306101672e-05, 'start': 40, 'end': 44, 'answer': '2005'}
follow question : When was the first apple i phone 1 made?
short answer : ['June 29, 2007.']
{'score': 0.7481622695922852, 'start': 167, 'end': 171, 'answer': '2007'}
follow question : When was the first apple i phone beta made?
short answer : ['2004.']
{'score': 9.010155395117181e-07, 'start': 40, 'end': 44, 'answer': '2005'}
{'rougeLsum': 38.70967741935484, 'length': 29.0, 'str_em': 0.0, 'Disambig-F1': 25.0}
{'first_doc_retrival': 0.9, 'first_title_retrival': 1.0, 'second_doc_retrival': 0.9, 'second_title_retrival': 1.0}
First Document Match Rate: 0.9
['List of Harry Potter characters'
 'List of supporting Harry Potter characters'
 'List of Harry Potter cast members' 'List of Harry Potter cast members'
 'List of Harry Potter cast members' 'List of Harry Potter cast members'
 'Order of the Phoenix (fictional organisation)'
 'Order of the Phoenix (fictional organisation)'
 'Order of the Phoenix (fictional organisation)'
 'Harry Potter and the Prisoner of Azkaban (film)']
{'Order of the Phoenix (fictional organisation)', 'List of Harry Potter cast members', 'List of Harry Potter characters', 'List of supporting Harry Potter characters'}
First Title Match Rate: 1.0
First ans:  The Weasley brothers, Fred and George, were played by twins James and Oliver Phelps. They portrayed the twins in all eight films of the series, from the first film, "Harry Potter and the Philosopher's Stone," to the final film, "Harry Potter and the Deathly Hallows – Part 2." James and Oliver Phelps were cast as the Weasley twins due to their identical twin status, which was essential for the roles. They played the twins in various scenes, including their pranks and mischievous behavior, as well as their relationships with their family members. The twins' portrayal was well-received by fans and critics alike, and they became an integral part of the Harry Potter franchise.
Second Document Match Rate: 1.0
['List of Harry Potter cast members' 'List of Harry Potter cast members'
 'List of Harry Potter cast members' 'List of Harry Potter cast members'
 'List of Harry Potter cast members' 'List of Harry Potter cast members'
 'List of Harry Potter cast members' 'List of Harry Potter cast members'
 'List of Harry Potter cast members'
 'Order of the Phoenix (fictional organisation)']
{'Order of the Phoenix (fictional organisation)', 'List of Harry Potter cast members', 'List of Harry Potter characters', 'List of supporting Harry Potter characters'}
Second Title Match Rate: 0.5
Final ans:  James Phelps and Oliver Phelps played the Weasley brothers in the Harry Potter film series.
James Phelps and Oliver Phelps played the Weasley brothers in the Harry Potter film series.
Who played the weasley brothers in harry potter?
['Who played  Bill weasley in Harry Potter and the Prisoner of Azkaban?', 'Who played percy weasley in harry potter?', 'Who played fred weasley in harry potter?', 'Who played ron weasley in harry potter?', 'Who played george weasley in harry potter?', 'Who played  Bill weasley in harry potter (2001-2011)?']
[['Richard Fish'], ['Chris Rankin'], ['James Phelps'], ['Rupert Grint'], ['Oliver Phelps'], ['Domhnall Gleeson']]

 20%|██        | 4/20 [02:40<10:23, 38.99s/it]

follow question : Who played  Bill weasley in Harry Potter and the Prisoner of Azkaban?
short answer : ['Richard Fish']
{'score': 0.0007388486992567778, 'start': 0, 'end': 30, 'answer': 'James Phelps and Oliver Phelps'}
follow question : Who played percy weasley in harry potter?
short answer : ['Chris Rankin']
{'score': 0.034815430641174316, 'start': 0, 'end': 30, 'answer': 'James Phelps and Oliver Phelps'}
follow question : Who played fred weasley in harry potter?
short answer : ['James Phelps']
{'score': 0.006445024162530899, 'start': 0, 'end': 30, 'answer': 'James Phelps and Oliver Phelps'}
follow question : Who played ron weasley in harry potter?
short answer : ['Rupert Grint']
{'score': 0.5571157336235046, 'start': 0, 'end': 30, 'answer': 'James Phelps and Oliver Phelps'}
follow question : Who played george weasley in harry potter?
short answer : ['Oliver Phelps']
{'score': 0.13007201254367828, 'start': 0, 'end': 30, 'answer': 'James Phelps and Oliver Phelps'}
follow question : Who played  Bill weasley in harry potter (2001-2011)?
short answer : ['Domhnall Gleeson']
{'score': 0.00544063001871109, 'start': 0, 'end': 30, 'answer': 'James Phelps and Oliver Phelps'}
{'rougeLsum': 24.778761061946902, 'length': 15.0, 'str_em': 33.33333333333333, 'Disambig-F1': 19.04761904761905}
{'first_doc_retrival': 0.9, 'first_title_retrival': 1.0, 'second_doc_retrival': 1.0, 'second_title_retrival': 0.5}
First Document Match Rate: 0.4
['List of Virginia state parks' 'List of Virginia state parks'
 'List of Virginia state parks' 'List of Virginia state parks'
 'List of Virginia state parks' 'New York (state)' 'Richmond, Virginia'
 'Richmond, Virginia' 'Virginia State Capitol' 'New York City']
{'List of Virginia state parks'}
First Title Match Rate: 1.0
First ans:  The Virginia state park system has a total of 38 parks. These parks are managed by the Virginia Department of Conservation and Recreation. The original six parks that opened in 1936 have been expanded to include many more parks, which are now overseen by the department. Some of the parks are open for public use, while others are closed or under construction. The number of state parks in Virginia has been increasing over the years to provide more recreational opportunities for the public.
Second Document Match Rate: 0.4
['List of Virginia state parks' 'List of Virginia state parks'
 'List of Virginia state parks' 'List of Virginia state parks'
 'List of Virginia state parks' 'New York (state)' 'Richmond, Virginia'
 'Richmond, Virginia' 'Virginia State Capitol' 'New York City']
{'List of Virginia state parks'}
Second Title Match Rate: 1.0
Final ans:  According to the provided context information, there are 38 state parks in Virginia.
According to the provided context information, there are 38 state parks in Virginia.
How many state parks are there in virginia?
['How many state parks are there in virginia in 1936?', 'How many state parks are there in virginia in 2016?', 'How many state parks were there when the state park system formed in Virginia?', 'How many state parks were there in Virginia as of 2016?']
[['six'], ['38'], ['6'], ['38']]

 25%|██▌       | 5/20 [03:03<08:18, 33.24s/it]

follow question : How many state parks are there in virginia in 1936?
short answer : ['six']
{'score': 0.00018283803365193307, 'start': 57, 'end': 59, 'answer': '38'}
follow question : How many state parks are there in virginia in 2016?
short answer : ['38']
{'score': 0.22148355841636658, 'start': 57, 'end': 59, 'answer': '38'}
follow question : How many state parks were there when the state park system formed in Virginia?
short answer : ['6']
{'score': 0.008699050173163414, 'start': 57, 'end': 59, 'answer': '38'}
follow question : How many state parks were there in Virginia as of 2016?
short answer : ['38']
{'score': 0.8922719955444336, 'start': 57, 'end': 59, 'answer': '38'}
{'rougeLsum': 29.78723404255319, 'length': 13.0, 'str_em': 50.0, 'Disambig-F1': 50.0}
{'first_doc_retrival': 0.4, 'first_title_retrival': 1.0, 'second_doc_retrival': 0.4, 'second_title_retrival': 1.0}
First Document Match Rate: 0.5
['2018 UEFA Champions League Final' '2018 UEFA Champions League Final'
 '2018 UEFA Champions League Final' '2018 UEFA Champions League Final'
 '2018 UEFA Champions League Final' '2018 UEFA Champions League Final'
 'List of Super Bowl halftime shows' '2018 FIFA World Cup'
 'UEFA Champions League' '2017 AFL Grand Final']
{'2018 UEFA Champions League Final'}
First Title Match Rate: 1.0
First ans:  The opening ceremony of the 2018 UEFA Champions League Final featured English singer Dua Lipa, who performed alongside Jamaican rapper Sean Paul, and the UEFA Champions League Anthem by Slovenian-Croatian cello duo 2Cellos. The annual UEFA Champions Festival was held between 24–27 May 2018 at the Kiev city centre, but the specific performers at this event are not mentioned in the context. The 2018 UEFA Champions League Final match itself did not feature any halftime show or performances, as it is a football match. However, the official match ball, the "Telstar 18", was unveiled on 9 November 2017, and the official mascot for the tournament, Zabivaka, was unveiled on 21 October 2016. The official song of the tournament, "Live It Up", was released on 25 May 2018.
Second Document Match Rate: 0.3
['2018 UEFA Champions League Final' '2018 UEFA Champions League Final'
 '2018 UEFA Champions League Final' '2018 UEFA Champions League Final'
 '2017–18 UEFA Champions League group stage' 'FIFA' '2018 FIFA World Cup'
 '2018 FIFA World Cup' 'UEFA Champions League' 'UEFA Champions League']
{'2018 UEFA Champions League Final'}
Second Title Match Rate: 1.0
Final ans:  The information provided does not specify who performed at the Champions League final in 2018. However, according to the context, it is mentioned that the UEFA Champions League Anthem was performed by Slovenian–Croatian cello duo 2Cellos.
The information provided does not specify who performed at the Champions League final in 2018. However, according to the context, it is mentioned that the UEFA Champions League Anthem was performed by Slovenian–Croatian cello duo 2Cellos.
Who performed at the champions league final 2018?
['Who are the teams that performed in competition at the champions league final 2018?', 'Who performed best at the champions league final 2018, winning man of the match?', 'Who performed at the opening ceremony of the champions league final 2018?', 'Who performed the anthem at the champions league final 2018?']
[['Real Madrid and Liverpool', 'Liverpool', 'Real Madrid'], ['Gareth Bale', 'Bale'], ['Dua Lipa', 'Sean Paul', 'Dua Lipa and Sean Paul'], ['2Cellos', 'Luka Šulić and Stjepan Hauser', 'Luka Šulić', '2CΞLLOS', 'Stjepan Hauser']]

 30%|███       | 6/20 [03:36<07:44, 33.16s/it]

follow question : Who are the teams that performed in competition at the champions league final 2018?
short answer : ['Real Madrid and Liverpool', 'Liverpool', 'Real Madrid']
{'score': 0.12481953203678131, 'start': 0, 'end': 93, 'answer': 'The information provided does not specify who performed at the Champions League final in 2018'}
follow question : Who performed best at the champions league final 2018, winning man of the match?
short answer : ['Gareth Bale', 'Bale']
{'score': 1.2776503126588068e-06, 'start': 230, 'end': 237, 'answer': '2Cellos'}
follow question : Who performed at the opening ceremony of the champions league final 2018?
short answer : ['Dua Lipa', 'Sean Paul', 'Dua Lipa and Sean Paul']
{'score': 0.004665156826376915, 'start': 230, 'end': 237, 'answer': '2Cellos'}
follow question : Who performed the anthem at the champions league final 2018?
short answer : ['2Cellos', 'Luka Šulić and Stjepan Hauser', 'Luka Šulić', '2CΞLLOS', 'Stjepan Hauser']
{'score': 0.5019283890724182, 'start': 230, 'end': 237, 'answer': '2Cellos'}
{'rougeLsum': 37.096774193548384, 'length': 36.0, 'str_em': 25.0, 'Disambig-F1': 25.0}
{'first_doc_retrival': 0.5, 'first_title_retrival': 1.0, 'second_doc_retrival': 0.3, 'second_title_retrival': 1.0}
First Document Match Rate: 0.3
['Thelma & Louise' 'Thelma & Louise' 'Thelma & Louise' 'Thelma & Louise'
 'Riddler' 'Snapped' 'Snapped: Killer Couples' 'The Bodyguard (1992 film)'
 '800 Words' 'List of Lucifer episodes']
{'Thelma & Louise', 'Come Thelma & Louise'}
First Title Match Rate: 0.5
First ans:  The man who was killed in the movie Thelma and Louise was Harlan, a stranger who attempted to rape Thelma at a roadhouse bar. He was shot and killed by Louise in self-defense after he became violent and threatened Thelma. This event sets off a chain reaction of events that leads to the main characters going on the run and committing various crimes. The killer of the man is not a person, but rather an action taken by Louise in self-defense. The movie's plot revolves around the consequences of this event and the characters' subsequent actions.
Second Document Match Rate: 0.3
['Thelma & Louise' 'Thelma & Louise' 'Thelma & Louise' 'Thelma & Louise'
 'Riddler' "Hell's Angels (film)"
 'The Girl with the Dragon Tattoo (2011 film)' 'Snapped'
 'The Bodyguard (1992 film)' '800 Words']
{'Thelma & Louise', 'Come Thelma & Louise'}
Second Title Match Rate: 0.5
Final ans:  In the movie "Thelma and Louise," it is Louise who kills the man, Harlan, after he attempts to rape Thelma.
In the movie "Thelma and Louise," it is Louise who kills the man, Harlan, after he attempts to rape Thelma.
Who killed the man in thelma and louise?
['Which character killed the man in thelma and louise?', 'Which actor killed the man in thelma and louise?', 'Who is the character that kills Harlan in the film Thelma and Louise?', 'Who is the actor of the character that killed a man in the film Thelma and Louise?']
[['Louise Elizabeth Sawyer', 'Louise'], ['Susan Sarandon', 'Susan Abigail Sarandon'], ['Louise Elizabeth Sawyer', 'Louise'], ['Susan Sarandon']]

 35%|███▌      | 7/20 [04:10<07:11, 33.21s/it]

follow question : Which character killed the man in thelma and louise?
short answer : ['Louise Elizabeth Sawyer', 'Louise']
{'score': 0.867597222328186, 'start': 40, 'end': 46, 'answer': 'Louise'}
follow question : Which actor killed the man in thelma and louise?
short answer : ['Susan Sarandon', 'Susan Abigail Sarandon']
{'score': 0.0006438228883780539, 'start': 40, 'end': 46, 'answer': 'Louise'}
follow question : Who is the character that kills Harlan in the film Thelma and Louise?
short answer : ['Louise Elizabeth Sawyer', 'Louise']
{'score': 0.9833641648292542, 'start': 40, 'end': 46, 'answer': 'Louise'}
follow question : Who is the actor of the character that killed a man in the film Thelma and Louise?
short answer : ['Susan Sarandon']
{'score': 4.7267262743844185e-06, 'start': 40, 'end': 46, 'answer': 'Louise'}
{'rougeLsum': 22.222222222222225, 'length': 20.0, 'str_em': 50.0, 'Disambig-F1': 50.0}
{'first_doc_retrival': 0.3, 'first_title_retrival': 0.5, 'second_doc_retrival': 0.3, 'second_title_retrival': 0.5}
First Document Match Rate: 0.9
["Charlie Kelly (It's Always Sunny in Philadelphia)"
 "Charlie Kelly (It's Always Sunny in Philadelphia)"
 "Charlie Kelly (It's Always Sunny in Philadelphia)"
 "Charlie Kelly (It's Always Sunny in Philadelphia)"
 "Charlie Kelly (It's Always Sunny in Philadelphia)"
 "Charlie Kelly (It's Always Sunny in Philadelphia)"
 "Charlie Kelly (It's Always Sunny in Philadelphia)"
 "List of It's Always Sunny in Philadelphia characters"
 "List of It's Always Sunny in Philadelphia characters"
 "List of It's Always Sunny in Philadelphia characters"]
{"List of It's Always Sunny in Philadelphia characters", "Charlie Kelly (It's Always Sunny in Philadelphia)"}
First Title Match Rate: 1.0
First ans:  Charlie Kelly is played by Charlie Day. Charlie Kelly is a main character in the TV show "It's Always Sunny in Philadelphia," and Charlie Day is the actor who portrays him. Charlie Kelly is a member of the main gang and is known for his erratic behavior, poor decision-making, and general chaos he causes. Charlie Day is also a co-creator and writer of the show, and his portrayal of Charlie Kelly is a key part of the series. Charlie Day's performance as Charlie Kelly has received praise for its comedic accuracy and depth.
Second Document Match Rate: 0.9
["Charlie Kelly (It's Always Sunny in Philadelphia)"
 "Charlie Kelly (It's Always Sunny in Philadelphia)"
 "Charlie Kelly (It's Always Sunny in Philadelphia)"
 "Charlie Kelly (It's Always Sunny in Philadelphia)"
 "Charlie Kelly (It's Always Sunny in Philadelphia)"
 "Charlie Kelly (It's Always Sunny in Philadelphia)"
 "List of It's Always Sunny in Philadelphia characters"
 "List of It's Always Sunny in Philadelphia characters"
 "List of It's Always Sunny in Philadelphia characters"
 "List of It's Always Sunny in Philadelphia characters"]
{"List of It's Always Sunny in Philadelphia characters", "Charlie Kelly (It's Always Sunny in Philadelphia)"}
Second Title Match Rate: 1.0
Final ans:  Charlie Kelly is played by Charlie Day.
Charlie Kelly is played by Charlie Day.
Who plays charlie on it's always sunny?
["Who does Charlie Day play on It's Always Sunny in Philadelphia?", "Who plays Charlie Kelly on It's Always Sunny in Philadelphia?"]
[['Charlie Kelly'], ['Charlie Day']]

 40%|████      | 8/20 [04:34<06:04, 30.36s/it]

follow question : Who does Charlie Day play on It's Always Sunny in Philadelphia?
short answer : ['Charlie Kelly']
{'score': 0.9979801177978516, 'start': 0, 'end': 13, 'answer': 'Charlie Kelly'}
follow question : Who plays Charlie Kelly on It's Always Sunny in Philadelphia?
short answer : ['Charlie Day']
{'score': 0.9869707226753235, 'start': 27, 'end': 38, 'answer': 'Charlie Day'}
{'rougeLsum': 37.03703703703704, 'length': 7.0, 'str_em': 100.0, 'Disambig-F1': 100.0}
{'first_doc_retrival': 0.9, 'first_title_retrival': 1.0, 'second_doc_retrival': 0.9, 'second_title_retrival': 1.0}
First Document Match Rate: 0.4
['Los Angeles Lakers' 'Los Angeles Lakers' 'Los Angeles Lakers'
 'Los Angeles Lakers' 'Los Angeles Lakers' '2010 NBA Finals'
 '2010 NBA Finals' '2010 NBA Finals' '2009 NBA Finals'
 'National Basketball Association']
{'Los Angeles Lakers'}
First Title Match Rate: 1.0
First ans:  The Los Angeles Lakers have won the NBA Finals 16 times, with their first title coming in 1949 and their most recent in 2010. They have appeared in the Finals a total of 31 times, making them one of the most successful teams in NBA history. Their 16 titles are second only to the Boston Celtics, who have won 17 championships. The Lakers have won multiple championships in the 1940s, 1950s, 1970s, 1980s, and 2000s, with their most successful decade being the 1980s, where they won five championships in a nine-year span. The team's 16 titles have been won under the leadership of several Hall of Fame coaches, including Phil Jackson, who won 11 championships with the team.
Second Document Match Rate: 0.6
['Los Angeles Lakers' 'Los Angeles Lakers' 'Los Angeles Lakers'
 'Los Angeles Lakers' 'Los Angeles Lakers' 'Los Angeles Lakers'
 'Los Angeles Lakers' '2010 NBA Finals' '2010 NBA Finals'
 'National Basketball Association']
{'Los Angeles Lakers'}
Second Title Match Rate: 1.0
Final ans:  The Los Angeles Lakers have won the NBA Finals 16 times.
The Los Angeles Lakers have won the NBA Finals 16 times.
How many times have the lakers won the finals?
['As of 2017, how many times have the lakers won the finals?', 'As of 2016, how many times have the Lakers won the finals?', 'As of 2015, how many times have the Lakers won the finals?']
[['16'], ['16'], ['16']]

 45%|████▌     | 9/20 [05:12<06:00, 32.75s/it]

follow question : As of 2017, how many times have the lakers won the finals?
short answer : ['16']
{'score': 0.8424578309059143, 'start': 47, 'end': 49, 'answer': '16'}
follow question : As of 2016, how many times have the Lakers won the finals?
short answer : ['16']
{'score': 0.9183763265609741, 'start': 47, 'end': 49, 'answer': '16'}
follow question : As of 2015, how many times have the Lakers won the finals?
short answer : ['16']
{'score': 0.9005101323127747, 'start': 47, 'end': 49, 'answer': '16'}
{'rougeLsum': 25.454545454545457, 'length': 11.0, 'str_em': 100.0, 'Disambig-F1': 100.0}
{'first_doc_retrival': 0.4, 'first_title_retrival': 1.0, 'second_doc_retrival': 0.6, 'second_title_retrival': 1.0}
First Document Match Rate: 0.7
['Indian National Congress' 'Indian National Congress'
 'Indian National Congress' 'Indian National Congress'
 'Indian National Congress' 'Indian National Congress'
 'Indian National Congress'
 'List of current Indian ruling and opposition parties'
 'List of presidents of the Indian National Congress' 'India']
{'List of current Indian ruling and opposition parties', 'Indian National Congress'}
First Title Match Rate: 1.0
First ans:  The Indian National Congress is in power in 7 states of India: Punjab, Chhattisgarh, Rajasthan, Madhya Pradesh, Maharashtra, Jharkhand, and Puducherry. These states have a total of 7 legislative assemblies where the Congress party has a majority or is in power as part of a coalition government. Additionally, the Congress party has a presence in other states and union territories, but is not in power in all of them. As of 2019, the party is in power in 6 legislative assemblies, and has a significant presence in several other states. The party's current structure and composition show that it has a hierarchical organization, with a president and an All India Congress Committee (AICC) that are elected by delegates from state and district parties.
Second Document Match Rate: 0.6
['Indian National Congress' 'Indian National Congress'
 'Indian National Congress' 'Indian National Congress'
 'Indian National Congress' 'Indian National Congress'
 'List of current Indian ruling and opposition parties'
 'List of presidents of the Indian National Congress' 'India'
 'List of current members of the Rajya Sabha']
{'List of current Indian ruling and opposition parties', 'Indian National Congress'}
Second Title Match Rate: 1.0
Final ans:  Based on the given context information, the following states in India are under the Indian National Congress:1. Punjab2. Chhattisgarh3. Rajasthan4. Madhya Pradesh5. PuducherryThese states have a total of 7 governments in power, including the union territory of Puducherry.
Based on the given context information, the following states in India are under the Indian National Congress:1. Punjab2. Chhattisgarh3. Rajasthan4. Madhya Pradesh5. PuducherryThese states have a total of 7 governments in power, including the union territory of Puducherry.
How many states in india are under congress?
['How many states plus territories in india are under congress?', 'How many states alone in india are under congress?']
[['7'], ['5']]

 50%|█████     | 10/20 [05:55<06:01, 36.11s/it]

follow question : How many states plus territories in india are under congress?
short answer : ['7']
{'score': 0.5612826347351074, 'start': 204, 'end': 205, 'answer': '7'}
follow question : How many states alone in india are under congress?
short answer : ['5']
{'score': 0.20594587922096252, 'start': 162, 'end': 163, 'answer': '5'}
{'rougeLsum': 32.0, 'length': 38.0, 'str_em': 100.0, 'Disambig-F1': 100.0}
{'first_doc_retrival': 0.7, 'first_title_retrival': 1.0, 'second_doc_retrival': 0.6, 'second_title_retrival': 1.0}
First Document Match Rate: 1.0
['Fiddler on the Roof (film)' 'Fiddler on the Roof (film)'
 'Fiddler on the Roof (film)' 'Fiddler on the Roof' 'Fiddler on the Roof'
 'Fiddler on the Roof' 'Fiddler on the Roof' 'Fiddler on the Roof'
 'Fiddler on the Roof' 'Fiddler on the Roof']
{'Fiddler on the Roof', 'Category:Fiddler on the Roof', 'Jessica Vosk', 'Fiddler on the Roof (film)'}
First Title Match Rate: 0.5
First ans:  Fruma-Sarah is the deceased wife of Lazar Wolf, a wealthy butcher in the village of Anatevka, who rises from the grave to warn Tevye and his family of severe retribution if Tzeitel marries Lazar. She is mentioned in the story as a warning to Tevye and his family, but she does not appear in the musical or film directly. However, her character is significant in shaping Tevye's decision to allow Tzeitel to marry Motel, rather than Lazar. In the musical, Fruma-Sarah's character is a plot device used to convey the idea that the ancestors are watching over the family and guiding their decisions. Her presence is felt throughout the story, influencing the characters and their actions.
Second Document Match Rate: 0.8
['Fiddler on the Roof (film)' 'Fiddler on the Roof (film)'
 'Fiddler on the Roof (film)' 'Fiddler on the Roof' 'Fiddler on the Roof'
 'Fiddler on the Roof' 'Fiddler on the Roof' 'Fiddler on the Roof'
 'The Phantom of the Opera (1925 film)' 'Beauty and the Beast (musical)']
{'Fiddler on the Roof', 'Category:Fiddler on the Roof', 'Jessica Vosk', 'Fiddler on the Roof (film)'}
Second Title Match Rate: 0.5
Final ans:  Fruma-Sarah is the deceased wife of Lazar Wolf, a wealthy butcher in the village of Anatevka. She rises from the grave in Tevye's "nightmare" to warn of severe retribution if Tzeitel marries Lazar.
Fruma-Sarah is the deceased wife of Lazar Wolf, a wealthy butcher in the village of Anatevka. She rises from the grave in Tevye's "nightmare" to warn of severe retribution if Tzeitel marries Lazar.
Who is fruma sarah in fiddler on the roof?
['Who played fruma sarah in the 1971 film, Fiddler on the Roof?', 'Who played Fruma Sarah in the original 1964 Broadway cast of Fiddler on the Roof?', 'Who is the character of Fruma Sarah in Fiddler on the Roof?', 'Who played Fruma Sarah in the 2015-2016 Broadway Revival of Fiddler on the Roof?']
[['Ruth Madoc'], ['Carol Sawyer Yussel'], ['a ghostly depiction of the late wife of Lazar Wolf'], ['Jessica Vosk']]

 55%|█████▌    | 11/20 [06:34<05:31, 36.84s/it]

follow question : Who played fruma sarah in the 1971 film, Fiddler on the Roof?
short answer : ['Ruth Madoc']
{'score': 0.0003479774750303477, 'start': 36, 'end': 46, 'answer': 'Lazar Wolf'}
follow question : Who played Fruma Sarah in the original 1964 Broadway cast of Fiddler on the Roof?
short answer : ['Carol Sawyer Yussel']
{'score': 1.1581705621210858e-05, 'start': 36, 'end': 46, 'answer': 'Lazar Wolf'}
follow question : Who is the character of Fruma Sarah in Fiddler on the Roof?
short answer : ['a ghostly depiction of the late wife of Lazar Wolf']
{'score': 0.4112100899219513, 'start': 15, 'end': 46, 'answer': 'the deceased wife of Lazar Wolf'}
follow question : Who played Fruma Sarah in the 2015-2016 Broadway Revival of Fiddler on the Roof?
short answer : ['Jessica Vosk']
{'score': 0.0001080510628526099, 'start': 36, 'end': 46, 'answer': 'Lazar Wolf'}
{'rougeLsum': 21.897810218978105, 'length': 33.0, 'str_em': 0.0, 'Disambig-F1': 15.384615384615385}
{'first_doc_retrival': 1.0, 'first_title_retrival': 0.5, 'second_doc_retrival': 0.8, 'second_title_retrival': 0.5}
First Document Match Rate: 0.9
['List of Major League Baseball All-Star Game venues'
 'List of Major League Baseball All-Star Game venues'
 'List of Major League Baseball All-Star Game venues'
 'List of Major League Baseball All-Star Game venues'
 'List of Major League Baseball All-Star Game venues'
 'List of Major League Baseball All-Star Game venues'
 'List of Major League Baseball All-Star Game venues'
 'List of Major League Baseball All-Star Game venues'
 'List of Major League Baseball All-Star Game venues'
 'List of Major League Baseball All-Star Game venues']
{'List of Major League Baseball All-Star Game venues'}
First Title Match Rate: 1.0
First ans:  The Toronto Blue Jays hosted the MLB All-Star Game on July 9, 1991, with a stadium of SkyDome and an attendance of 52,383.
Second Document Match Rate: 0.9
['List of Major League Baseball All-Star Game venues'
 'List of Major League Baseball All-Star Game venues'
 'List of Major League Baseball All-Star Game venues'
 'List of Major League Baseball All-Star Game venues'
 'List of Major League Baseball All-Star Game venues'
 'List of Major League Baseball All-Star Game venues'
 'List of Major League Baseball All-Star Game venues'
 'List of Major League Baseball All-Star Game venues'
 'List of Major League Baseball All-Star Game venues'
 'List of Major League Baseball All-Star Game venues']
{'List of Major League Baseball All-Star Game venues'}
Second Title Match Rate: 1.0
Final ans:  July 9, 1991
July 9, 1991
When did toronto host the mlb all-star game?
['What date did toronto host the mlb all-star game?', 'Which all-star game did toronto host?']
[['July 9, 1991'], ['1991 Major League Baseball All-Star Game', 'the 62nd playing of the midsummer classic']]

 60%|██████    | 12/20 [06:45<03:52, 29.09s/it]

follow question : What date did toronto host the mlb all-star game?
short answer : ['July 9, 1991']
{'score': 0.9896409511566162, 'start': 0, 'end': 12, 'answer': 'July 9, 1991'}
follow question : Which all-star game did toronto host?
short answer : ['1991 Major League Baseball All-Star Game', 'the 62nd playing of the midsummer classic']
{'score': 0.18676654994487762, 'start': 0, 'end': 12, 'answer': 'July 9, 1991'}
{'rougeLsum': 23.076923076923077, 'length': 3.0, 'str_em': 50.0, 'Disambig-F1': 61.111111111111114}
{'first_doc_retrival': 0.9, 'first_title_retrival': 1.0, 'second_doc_retrival': 0.9, 'second_title_retrival': 1.0}
First Document Match Rate: 0.7
['To Catch a Thief' 'To Catch a Thief' 'To Catch a Thief'
 'To Catch a Thief' 'To Catch a Thief (1936 film)' 'Sunbeam Alpine'
 'Sunbeam Alpine' 'It Takes a Thief (1968 TV series)'
 'List of Cars characters' 'Doc Hudson']
{'Sunbeam Alpine', 'To Catch a Thief', 'To Catch a Thief (1936 film)', 'It Takes a Thief (1968 TV series)'}
First Title Match Rate: 1.0
First ans:  A metallic blue 1953 Sunbeam Alpine Mk I is driven by Grace Kelly in the 1955 film To Catch a Thief. The car was a two-seater sports roadster initially developed for a one-off rally car, and it was hand-built at Thrupp & Maberly coachbuilders from 1953 to 1955. A Sunbeam Alpine Mk III is also driven by Peggy Cummins in the film Night of the Demon, while a red Series I Alpine is driven by Elizabeth Taylor in the film Butterfield 8. Additionally, a white Series 1 Alpine was the regular drive of Rod Taylor's character Glenn Evans in the early 1960s TV series Hong Kong, and a lake blue "Series II" Alpine roadster is amongst the first on-screen "Bond cars" in the 1962 film Dr. No.
Second Document Match Rate: 0.8
['To Catch a Thief' 'To Catch a Thief' 'To Catch a Thief' 'Sunbeam Alpine'
 'Sunbeam Alpine' 'Sunbeam Alpine' 'Sunbeam Alpine' 'Sunbeam Alpine'
 'Sunbeam Alpine' 'Grace Kelly']
{'Sunbeam Alpine', 'To Catch a Thief', 'To Catch a Thief (1936 film)', 'It Takes a Thief (1968 TV series)'}
Second Title Match Rate: 0.5
Final ans:  A metallic blue 1953 Sunbeam Alpine Mk I.
A metallic blue 1953 Sunbeam Alpine Mk I.
What kind of car in to catch a thief?
['What kind of car in to catch a thief in terms of model?', 'What kind of car in to catch a thief in terms of automobile make?']
[['Sunbeam Alpine', '1953 Sunbeam Alpine Mk I'], ['Rootes Group']]

 65%|██████▌   | 13/20 [07:02<02:56, 25.21s/it]

follow question : What kind of car in to catch a thief in terms of model?
short answer : ['Sunbeam Alpine', '1953 Sunbeam Alpine Mk I']
{'score': 0.0028908655513077974, 'start': 16, 'end': 20, 'answer': '1953'}
follow question : What kind of car in to catch a thief in terms of automobile make?
short answer : ['Rootes Group']
{'score': 0.0035272978711873293, 'start': 16, 'end': 40, 'answer': '1953 Sunbeam Alpine Mk I'}
{'rougeLsum': 35.55555555555556, 'length': 8.0, 'str_em': 50.0, 'Disambig-F1': 16.666666666666668}
{'first_doc_retrival': 0.7, 'first_title_retrival': 1.0, 'second_doc_retrival': 0.8, 'second_title_retrival': 0.5}
First Document Match Rate: 0.8
['Jersey Shore (TV series)' 'Jersey Shore (TV series)'
 'Jersey Shore (TV series)' 'Jersey Shore (TV series)'
 'Jersey Shore (TV series)' 'Jersey Shore (TV series)'
 'Jersey Shore (TV series)' 'Jersey Shore (TV series)'
 'Jersey Shore (TV series)' 'Nashville (season 6)']
{'Jersey Shore (TV series)'}
First Title Match Rate: 1.0
First ans:  The sixth and final season of Jersey Shore premiered on October 4, 2012, and the last episode aired on December 20, 2012. However, the Jersey Shore franchise continued with a new series, Jersey Shore: Family Vacation, which premiered on April 5, 2018. The new series is considered a new series and not the seventh season of the original show. The original series ended with its sixth season, but the cast members reunited for a new series. The new series has been airing since 2018, but the original series ended in 2012.
Second Document Match Rate: 0.6
['Jersey Shore (TV series)' 'Jersey Shore (TV series)'
 'Jersey Shore (TV series)' 'Jersey Shore (TV series)'
 'Jersey Shore (TV series)' 'Jersey Shore (TV series)'
 'Jersey Shore (TV series)' 'Baby Daddy' 'Nashville (season 6)'
 'Only Fools and Horses']
{'Jersey Shore (TV series)'}
Second Title Match Rate: 1.0
Final ans:  The last season of Jersey Shore aired from April 5, 2018, to July 26, 2018, as part of the new series Jersey Shore: Family Vacation, not the seventh season of the original show.
The last season of Jersey Shore aired from April 5, 2018, to July 26, 2018, as part of the new series Jersey Shore: Family Vacation, not the seventh season of the original show.
When did the last season of jersey shore air?
['When did season 4 of jersey shore first air?', 'When did season 4 of jersey shore last air?', 'When did season 5 of jersey shore first air?', 'When did season 5 of jersey shore last air?', 'When did season 6 of jersey shore first air?', 'When did season 6 of jersey shore last air?']
[['August 4, 2011'], ['October 20, 2011'], ['January 5, 2012'], ['March 15, 2012'], ['October 4, 2012'], ['December 20, 2012']]

 70%|███████   | 14/20 [07:17<02:13, 22.22s/it]

follow question : When did season 4 of jersey shore first air?
short answer : ['August 4, 2011']
{'score': 0.00018012481450568885, 'start': 43, 'end': 56, 'answer': 'April 5, 2018'}
follow question : When did season 4 of jersey shore last air?
short answer : ['October 20, 2011']
{'score': 0.4825093746185303, 'start': 43, 'end': 74, 'answer': 'April 5, 2018, to July 26, 2018'}
follow question : When did season 5 of jersey shore first air?
short answer : ['January 5, 2012']
{'score': 0.0428227074444294, 'start': 43, 'end': 56, 'answer': 'April 5, 2018'}
follow question : When did season 5 of jersey shore last air?
short answer : ['March 15, 2012']
{'score': 0.8443519473075867, 'start': 43, 'end': 56, 'answer': 'April 5, 2018'}
follow question : When did season 6 of jersey shore first air?
short answer : ['October 4, 2012']
{'score': 0.00010489402484381571, 'start': 43, 'end': 56, 'answer': 'April 5, 2018'}
follow question : When did season 6 of jersey shore last air?
short answer : ['December 20, 2012']
{'score': 0.5084505081176758, 'start': 43, 'end': 56, 'answer': 'April 5, 2018'}
{'rougeLsum': 26.666666666666668, 'length': 33.0, 'str_em': 0.0, 'Disambig-F1': 5.555555555555555}
{'first_doc_retrival': 0.8, 'first_title_retrival': 1.0, 'second_doc_retrival': 0.6, 'second_title_retrival': 1.0}
First Document Match Rate: 0.7
["One Flight Down (Grey's Anatomy)" "Grey's Anatomy (season 9)"
 "Grey's Anatomy (season 9)" "Flight (Grey's Anatomy)"
 "Flight (Grey's Anatomy)" "Flight (Grey's Anatomy)"
 "Going, Going, Gone (Grey's Anatomy)" "Grey's Anatomy (season 8)"
 "Grey's Anatomy (season 6)" "Grey's Anatomy"]
{"One Flight Down (Grey's Anatomy)", "Grey's Anatomy (season 8)", "Grey's Anatomy (season 9)", "Going, Going, Gone (Grey's Anatomy)", "Flight (Grey's Anatomy)"}
First Title Match Rate: 1.0
First ans:  The plane crash occurred at the end of Season 8. It was the season finale, "Flight", which marked a significant turning point in the series, leading to the deaths of Lexie Grey and the hospital's financial struggles. The aftermath of the crash continued into Season 9, with the characters dealing with the consequences of the crash and the hospital's financial struggles. The plane crash also had a lasting impact on the characters, particularly Meredith Grey, who struggled to cope with the loss of her sister, Lexie. The crash also led to the departure of several characters, including Lexie and Mark Sloan.
Second Document Match Rate: 0.6
["One Flight Down (Grey's Anatomy)" "Grey's Anatomy (season 9)"
 "Grey's Anatomy (season 9)" "Flight (Grey's Anatomy)"
 "Flight (Grey's Anatomy)" "Flight (Grey's Anatomy)"
 "Grey's Anatomy (season 8)" 'Lexie Grey' 'Lexie Grey' "Grey's Anatomy"]
{"One Flight Down (Grey's Anatomy)", "Grey's Anatomy (season 8)", "Grey's Anatomy (season 9)", "Going, Going, Gone (Grey's Anatomy)", "Flight (Grey's Anatomy)"}
Second Title Match Rate: 0.8
Final ans:  The plane crash occurred at the end of season 8.
The plane crash occurred at the end of season 8.
What season of greys anatomy was the plane crash?
["What season of Grey's Anatomy was the plane crash involving six doctors?", "What season of Grey's Anatomy was the plane crash in Seattle that brought memories of a previous plane crash?", "What season of Grey's Anatomy was the plane crash that claimed the life of Lexie Grey?", "What season of Grey's Anatomy was the plane crash in downtown Seattle?"]
[['season 8'], ['season 11'], ['8'], ['11']]

 75%|███████▌  | 15/20 [07:31<01:38, 19.67s/it]

follow question : What season of Grey's Anatomy was the plane crash involving six doctors?
short answer : ['season 8']
{'score': 0.7814993262290955, 'start': 39, 'end': 47, 'answer': 'season 8'}
follow question : What season of Grey's Anatomy was the plane crash in Seattle that brought memories of a previous plane crash?
short answer : ['season 11']
{'score': 0.8026421666145325, 'start': 39, 'end': 47, 'answer': 'season 8'}
follow question : What season of Grey's Anatomy was the plane crash that claimed the life of Lexie Grey?
short answer : ['8']
{'score': 0.8036807775497437, 'start': 39, 'end': 47, 'answer': 'season 8'}
follow question : What season of Grey's Anatomy was the plane crash in downtown Seattle?
short answer : ['11']
{'score': 0.8158382177352905, 'start': 39, 'end': 47, 'answer': 'season 8'}
{'rougeLsum': 25.454545454545453, 'length': 10.0, 'str_em': 50.0, 'Disambig-F1': 54.166666666666664}
{'first_doc_retrival': 0.7, 'first_title_retrival': 1.0, 'second_doc_retrival': 0.6, 'second_title_retrival': 0.8}
First Document Match Rate: 0.1
['Oriental Bank of Commerce' 'Oriental Bank of Commerce'
 'Public Accounts Committee (India)'
 'List of Indian parliamentary committees'
 'List of Indian parliamentary committees' 'India'
 'India at the 2018 Asian Games' 'India at the 2018 Asian Games'
 'Christianity' 'Sports Authority of India']
{'Oriental Bank of Commerce'}
First Title Match Rate: 1.0
First ans:  The Oriental Bank of Commerce has 2390 branches across India. As of 2018-2019, the bank had a total of 2390 branches and 2625 ATMs across the country. The bank has undergone several mergers and acquisitions, including the merger with Global Trust Bank in 2004 and the proposed merger with United Bank of India in 2019. However, the exact number of branches may have changed since then due to these mergers and acquisitions. As of the latest available information, the bank had a total of 2390 branches.
Second Document Match Rate: 0.1
['Oriental Bank of Commerce' 'Oriental Bank of Commerce'
 'Vice President of India' 'India' 'India at the 2018 Asian Games'
 'India at the 2018 Asian Games'
 "Ministry of Agriculture & Farmers' Welfare"
 'Minister of Agriculture & Farmers Welfare' 'Nissan Leaf' 'Starbucks']
{'Oriental Bank of Commerce'}
Second Title Match Rate: 1.0
Final ans:  2390
2390
Number of branches of oriental bank of commerce in india?
['As per the March 2018-2019 report, what is the number of branches of oriental bank of commerce in india?', 'What is the number of branches of oriental bank of commerce in india after amalgamation of Global Trust Bank?', 'Number of branches of oriental bank of commerce in india after expected merger with United Bank of India in 2020?']
[['2390'], ['1092'], ['11,437']]

 80%|████████  | 16/20 [07:45<01:12, 18.07s/it]

follow question : As per the March 2018-2019 report, what is the number of branches of oriental bank of commerce in india?
short answer : ['2390']
{'score': 0.9923193454742432, 'start': 0, 'end': 4, 'answer': '2390'}
follow question : What is the number of branches of oriental bank of commerce in india after amalgamation of Global Trust Bank?
short answer : ['1092']
{'score': 0.9800064563751221, 'start': 0, 'end': 4, 'answer': '2390'}
follow question : Number of branches of oriental bank of commerce in india after expected merger with United Bank of India in 2020?
short answer : ['11,437']
{'score': 0.9414204359054565, 'start': 0, 'end': 4, 'answer': '2390'}
{'rougeLsum': 3.225806451612903, 'length': 1.0, 'str_em': 33.33333333333333, 'Disambig-F1': 33.33333333333333}
{'first_doc_retrival': 0.1, 'first_title_retrival': 1.0, 'second_doc_retrival': 0.1, 'second_title_retrival': 1.0}
First Document Match Rate: 0.5
['History of the St. Louis Rams' 'History of the St. Louis Rams'
 'History of the St. Louis Rams' 'History of the Los Angeles Rams'
 'History of the Los Angeles Rams' 'History of the Los Angeles Rams'
 'History of the St. Louis Cardinals (NFL)' 'Los Angeles Rams'
 'Los Angeles Rams' 'Los Angeles Rams']
{'History of the Los Angeles Rams', 'History of the St. Louis Rams'}
First Title Match Rate: 1.0
First ans:  The Rams relocated to St. Louis in 1995, after a 21-3-6 vote by the NFL owners initially rejected the move. However, the owners later acquiesced to the demands of Georgia Frontiere, the Rams' owner, and allowed the team to move to St. Louis. The Rams played their first game in St. Louis on September 10, 1995, against the New Orleans Saints. The team played their home games at the Trans World Dome, which was later renamed the Edward Jones Dome, until the end of the 2015 season. The Rams returned to Los Angeles in 2016, ending their 21-year tenure in St. Louis.
Second Document Match Rate: 0.6
['History of the St. Louis Rams' 'History of the St. Louis Rams'
 'History of the St. Louis Rams' 'History of the Los Angeles Rams'
 'History of the Los Angeles Rams' 'History of the Los Angeles Rams'
 'History of the Los Angeles Rams' 'Los Angeles Rams' 'Los Angeles Rams'
 'Los Angeles Rams']
{'History of the Los Angeles Rams', 'History of the St. Louis Rams'}
Second Title Match Rate: 1.0
Final ans:  The Rams relocated to St. Louis in 1995, after the 1994 NFL season.
The Rams relocated to St. Louis in 1995, after the 1994 NFL season.
When did the rams go to st louis?
['In what year did the rams go to St. Louis?', 'What was the first game the Rams played in St. Louis?']
[['1995'], ['September 10, 1995']]

 85%|████████▌ | 17/20 [08:02<00:53, 17.68s/it]

follow question : In what year did the rams go to St. Louis?
short answer : ['1995']
{'score': 0.9887253642082214, 'start': 35, 'end': 39, 'answer': '1995'}
follow question : What was the first game the Rams played in St. Louis?
short answer : ['September 10, 1995']
{'score': 1.60994648013002e-06, 'start': 35, 'end': 39, 'answer': '1995'}
{'rougeLsum': 20.253164556962027, 'length': 13.0, 'str_em': 50.0, 'Disambig-F1': 75.0}
{'first_doc_retrival': 0.5, 'first_title_retrival': 1.0, 'second_doc_retrival': 0.6, 'second_title_retrival': 1.0}
First Document Match Rate: 0.8
['Voortrekkers (youth organisation)' 'Voortrekkers (youth organisation)'
 'Voortrekkers (youth organisation)' 'Great Trek' 'Great Trek'
 'Great Trek' 'Great Trek' 'Great Trek' 'Great Trek' 'Great Trek']
{'Voortrekkers (youth organisation)', 'Great Trek'}
First Title Match Rate: 1.0
First ans:  The Voortrekkers arrived in South Africa in various waves between 1835 and 1840, with the first wave lasting from 1835 to 1840 and consisting of an estimated 6,000 people. The first two parties of Voortrekkers left in September 1835, led by Louis Tregardt and Hans van Rensburg. A party led by Hendrik Potgieter trekked out of the Tarka area in either late 1835 or early 1836, and in September 1836 a party led by Gerrit Maritz began their trek from Graaff-Reinet. The Voortrekkers also made exploratory treks to Natal in January 1832, June 1834, and September 1834. They established settlements in various parts of South Africa, including the Natalia Republic, which was proclaimed after the defeat of the Zulu forces in December 1838.
Second Document Match Rate: 0.8
['Voortrekkers (youth organisation)' 'Voortrekkers (youth organisation)'
 'Great Trek' 'Great Trek' 'Great Trek' 'Great Trek' 'Great Trek'
 'Great Trek' 'Great Trek' 'Great Trek']
{'Voortrekkers (youth organisation)', 'Great Trek'}
Second Title Match Rate: 1.0
Final ans:  The Voortrekkers arrived in South Africa in the early 19th century, specifically between 1835 and 1840. The first two parties of Voortrekkers left in September 1835, led by Louis Tregardt and Hans van Rensburg.
The Voortrekkers arrived in South Africa in the early 19th century, specifically between 1835 and 1840. The first two parties of Voortrekkers left in September 1835, led by Louis Tregardt and Hans van Rensburg.
When did the voortrekkers arrive in south africa?
['When did the first wave of voortrekkers arrive in south africa?', 'When did the voortrekkers exploratory treks arrive in south africa?']
[['1836', '1836 onwards'], ['February 1835']]

 90%|█████████ | 18/20 [08:26<00:39, 19.68s/it]

follow question : When did the first wave of voortrekkers arrive in south africa?
short answer : ['1836', '1836 onwards']
{'score': 0.309481143951416, 'start': 150, 'end': 164, 'answer': 'September 1835'}
follow question : When did the voortrekkers exploratory treks arrive in south africa?
short answer : ['February 1835']
{'score': 0.2599780857563019, 'start': 81, 'end': 102, 'answer': 'between 1835 and 1840'}
{'rougeLsum': 49.12280701754386, 'length': 34.0, 'str_em': 0.0, 'Disambig-F1': 16.666666666666664}
{'first_doc_retrival': 0.8, 'first_title_retrival': 1.0, 'second_doc_retrival': 0.8, 'second_title_retrival': 1.0}
First Document Match Rate: 0.8
['10 Things I Hate About You' '10 Things I Hate About You'
 '10 Things I Hate About You' '10 Things I Hate About You'
 '10 Things I Hate About You' '10 Things I Hate About You (TV series)'
 '10 Things I Hate About You (TV series)'
 '10 Things I Hate About You (TV series)'
 '10 Things I Hate About You (TV series)'
 '10 Things I Hate About You (TV series)']
{'10 Things I Hate About You', '10 Things I Hate About You (TV series)'}
First Title Match Rate: 1.0
First ans:  In the 1999 film adaptation of 10 Things I Hate About You, Patrick Verona is played by Heath Ledger. In the 2009-2010 television series adaptation, Patrick Verona is played by Ethan Peck.
Second Document Match Rate: 0.6
['10 Things I Hate About You' '10 Things I Hate About You'
 '10 Things I Hate About You' '10 Things I Hate About You'
 '10 Things I Hate About You' '10 Things I Hate About You (TV series)'
 '10 Things I Hate About You (TV series)'
 '10 Things I Hate About You (TV series)' 'Katherine Heigl'
 'Justin Hartley']
{'10 Things I Hate About You', '10 Things I Hate About You (TV series)'}
Second Title Match Rate: 1.0
Final ans:  Heath Ledger plays Patrick Verona in the 1999 film version of 10 Things I Hate About You, and Ethan Peck plays Patrick Verona in the 2009 TV series adaptation of the same name.
Heath Ledger plays Patrick Verona in the 1999 film version of 10 Things I Hate About You, and Ethan Peck plays Patrick Verona in the 2009 TV series adaptation of the same name.
Who plays patrick in 10 things i hate about you?
['Who plays patrick in  the 1999 film 10 things i hate about you?', 'Who plays patrick in the 2009 tv series 10 things i hate about you?', 'Who plays patrick in the film 10 things i hate about you?', 'Who plays patrick in the TV series 10 things i hate about you?']
[['Heath Andrew Ledger', 'Heath Ledger', 'Ledger'], ['Ethan Peck', 'Peck', 'Ethan Gregory Peck'], ['Heath Andrew Ledger', 'Heath Ledger'], ['Ethan Peck', 'Ethan Gregory Peck']]

 95%|█████████▌| 19/20 [08:38<00:17, 17.35s/it]

follow question : Who plays patrick in  the 1999 film 10 things i hate about you?
short answer : ['Heath Andrew Ledger', 'Heath Ledger', 'Ledger']
{'score': 0.997129499912262, 'start': 0, 'end': 12, 'answer': 'Heath Ledger'}
follow question : Who plays patrick in the 2009 tv series 10 things i hate about you?
short answer : ['Ethan Peck', 'Peck', 'Ethan Gregory Peck']
{'score': 0.9977927803993225, 'start': 94, 'end': 104, 'answer': 'Ethan Peck'}
follow question : Who plays patrick in the film 10 things i hate about you?
short answer : ['Heath Andrew Ledger', 'Heath Ledger']
{'score': 0.9964517951011658, 'start': 0, 'end': 12, 'answer': 'Heath Ledger'}
follow question : Who plays patrick in the TV series 10 things i hate about you?
short answer : ['Ethan Peck', 'Ethan Gregory Peck']
{'score': 0.9931430220603943, 'start': 94, 'end': 104, 'answer': 'Ethan Peck'}
{'rougeLsum': 52.054794520547944, 'length': 33.0, 'str_em': 100.0, 'Disambig-F1': 100.0}
{'first_doc_retrival': 0.8, 'first_title_retrival': 1.0, 'second_doc_retrival': 0.6, 'second_title_retrival': 1.0}
First Document Match Rate: 0.7
['Indian National Congress' 'List of chief ministers of Madhya Pradesh'
 'List of chief ministers of Madhya Pradesh'
 'List of chief ministers of Madhya Pradesh'
 'List of chief ministers of Madhya Pradesh' 'Babulal Gaur' 'Babulal Gaur'
 'Babulal Gaur' 'List of chief ministers of Maharashtra'
 'List of current members of the Rajya Sabha']
{'M. Karunanidhi', 'List of chief ministers of Maharashtra', 'List of chief ministers of Madhya Pradesh', 'Babulal Gaur'}
First Title Match Rate: 0.75
First ans:  The current chief minister of Madhya Pradesh is Kamal Nath of the Indian National Congress. He has been in office since 17 December 2018. Babulal Gaur was the 16th Chief Minister of Madhya Pradesh, serving from 23 August 2004 to 29 November 2005. Digvijaya Singh was the 14th Chief Minister of Madhya Pradesh, serving from 7 December 1993 to 1 December 1998. He was succeeded by himself as he served his second term from 1 December 1998 to 7 December 2003.
Second Document Match Rate: 0.7
['Indian National Congress' 'List of chief ministers of Madhya Pradesh'
 'List of chief ministers of Madhya Pradesh'
 'List of chief ministers of Madhya Pradesh' 'Babulal Gaur' 'Babulal Gaur'
 'Babulal Gaur' 'List of chief ministers of Maharashtra'
 'List of chief ministers of Maharashtra'
 'List of current members of the Rajya Sabha']
{'M. Karunanidhi', 'List of chief ministers of Maharashtra', 'List of chief ministers of Madhya Pradesh', 'Babulal Gaur'}
Second Title Match Rate: 0.75
Final ans:  Kamal Nath is the current Chief Minister of Madhya Pradesh.
Kamal Nath is the current Chief Minister of Madhya Pradesh.
Who is the chief minister of m. p?
['Who is the 17th Chief Minister of MP?', 'Who is the 16th Chief Minister of MP?', 'Who is the 15th Chief Minister of MP?', 'Who is the 17th chief minister of m. p?', 'Who is the 16th chief minister of m. p?', 'Who is the 15th chief minister of m. p?']
[['Shivraj Singh Chauhan'], ['Babulal Gaur'], ['Uma Bharti'], ['Shivraj Singh Chauhan'], ['Babulal Gaur', 'Babulal Gaur Yadav'], ['Uma Bharti']]

100%|██████████| 20/20 [08:53<00:00, 26.69s/it]

follow question : Who is the 17th Chief Minister of MP?
short answer : ['Shivraj Singh Chauhan']
{'score': 0.0021384556312114, 'start': 0, 'end': 10, 'answer': 'Kamal Nath'}
follow question : Who is the 16th Chief Minister of MP?
short answer : ['Babulal Gaur']
{'score': 0.001500168233178556, 'start': 0, 'end': 10, 'answer': 'Kamal Nath'}
follow question : Who is the 15th Chief Minister of MP?
short answer : ['Uma Bharti']
{'score': 0.00042285321978852153, 'start': 0, 'end': 10, 'answer': 'Kamal Nath'}
follow question : Who is the 17th chief minister of m. p?
short answer : ['Shivraj Singh Chauhan']
{'score': 0.0007201292901299894, 'start': 0, 'end': 10, 'answer': 'Kamal Nath'}
follow question : Who is the 16th chief minister of m. p?
short answer : ['Babulal Gaur', 'Babulal Gaur Yadav']
{'score': 0.0005609843647107482, 'start': 0, 'end': 10, 'answer': 'Kamal Nath'}
follow question : Who is the 15th chief minister of m. p?
short answer : ['Uma Bharti']
{'score': 6.543472409248352e-05, 'start': 0, 'end': 10, 'answer': 'Kamal Nath'}
{'rougeLsum': 16.901408450704224, 'length': 10.0, 'str_em': 0.0, 'Disambig-F1': 0.0}
{'first_doc_retrival': 0.7, 'first_title_retrival': 0.75, 'second_doc_retrival': 0.7, 'second_title_retrival': 0.75}
rougeLsum      30.056829
length         19.350000
str_em         44.583333
Disambig-F1    47.346612
dtype: float64
first_doc_retrival       0.6750
first_title_retrival     0.9175
second_doc_retrival      0.6500
second_title_retrival    0.8575
dtype: float64

In [173]:
print(scores_df.mean())
print(retrival_df.mean())

rougeLsum      30.056829
length         19.350000
str_em         44.583333
Disambig-F1    47.346612
dtype: float64
first_doc_retrival       0.6750
first_title_retrival     0.9175
second_doc_retrival      0.6500
second_title_retrival    0.8575
dtype: float64

In [41]:
scores_df.mean()

rougeLsum      41.618101
length         90.600000
str_em         67.083333
Disambig-F1    51.569444
dtype: float64

In [19]:
scores_df.to_csv('./results/answer_rag_4_len60_results.csv', index=False)

In [3]:
sf = pd.read_csv('results/basicRAG_seed24-totalanswer-doc10_results.csv')
sf=sf[sf['length']<1000][:100]
print(len(sf))
print(sf.mean())
r=sf.mean()['rougeLsum']
d=sf.mean()['Disambig-F1']
dr=math.sqrt(r*d)
print(dr)

20
rougeLsum      36.529148
length         93.200000
str_em         58.333333
Disambig-F1    49.708333
dtype: float64
42.61224056875744

In [158]:
# 기본 라그에서 total_answer함수써서 답변 생성 후 그 답변을 다시 검색해서 total_answer로 최종 답변 생성
# first_doc_retrival       0.6750
# first_title_retrival     0.9175
# second_doc_retrival      0.6350
# second_title_retrival    0.8925
sf = pd.read_csv('results/answer_rag_0219_seed24_results.csv')
sf=sf[sf['length']<1000][:1000]
print(len(sf))
print(sf.mean())
r=sf.mean()['rougeLsum']
d=sf.mean()['Disambig-F1']
dr=math.sqrt(r*d)
print(dr)

199
rougeLsum      39.235850
length         97.924623
str_em         57.135678
Disambig-F1    50.390317
dtype: float64
44.46467054683511

In [14]:
sf = pd.read_csv('results/basicRAG_seed24-answer-len100_results.csv')
sf=sf[sf['length']<1000][:100]
print(len(sf))
print(sf.mean())
r=sf.mean()['rougeLsum']
d=sf.mean()['Disambig-F1']
dr=math.sqrt(r*d)
print(dr)

100
rougeLsum      32.685894
length         36.740000
str_em         46.516667
Disambig-F1    45.098707
dtype: float64
38.39390009491526

In [27]:
from tqdm import tqdm
from evaluation import evaluate

set_seed()

stop_iteration = 20

scores_list=[]
for idx, row in tqdm(qa_df.iterrows(), total=min([stop_iteration, len(qa_df)])):
    if idx == stop_iteration: break
    query = row['question']
    retrieved_docs = retrieve_documents(query)
    first_ans=answer(query,retrieved_docs)
    print('First ans:', first_ans[0])
    ans_docs=retrieve_documents(first_ans[0])
    final_ans=answer(first_ans[0],ans_docs)
    print('Second ans:', final_ans[0])
    scores=evaluate(final_ans, [row.to_dict()])
    scores_list.append(scores)
    scores_df=pd.DataFrame(scores_list)
    print(scores)
        
scores_df=pd.DataFrame(scores_list)
scores_df.mean()

  0%|          | 0/20 [00:00<?, ?it/s]/home/dataconv/.cache/huggingface/modules/transformers_modules/nvidia/NV-Embed-v2/5130cf1daf847c1bacee854a6ef1ca939e747fb2/modeling_nvembed.py:349: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'input_ids': torch.tensor(batch_dict.get('input_ids').to(batch_dict.get('input_ids')).long()),
/home/dataconv/anaconda3/envs/sf_rag_djk/lib/python3.10/contextlib.py:103: FutureWarning: `torch.backends.cuda.sdp_kernel()` is deprecated. In the future, this context manager will be removed. Please see `torch.nn.attention.sdpa_kernel()` for the new context manager, with updated signature.
  self.gen = func(*args, **kwds)

First ans: According to the provided context information, the player with the highest goals in world football is Ali Daei of Iran, with 109 goals in international matches.
Second ans: According to the provided context information, the player with the highest goals in world football is Ali Daei of Iran, with 109 goals in international matches.
According to the provided context information, the player with the highest goals in world football is Ali Daei of Iran, with 109 goals in international matches.
Who has the highest goals in world football?
["Who has the highest goals in men's world international football?", "Who has the highest goals all-time in men's football?", "Who has the highest goals in women's world international football?"]
[['Daei', 'Ali Daei'], ['Bican', 'Josef Bican'], ['Sinclair', 'Christine Sinclair']]

  5%|▌         | 1/20 [00:07<02:27,  7.74s/it]

follow question : Who has the highest goals in men's world international football?
short answer : ['Daei', 'Ali Daei']
{'score': 0.8568584322929382, 'start': 102, 'end': 110, 'answer': 'Ali Daei'}
follow question : Who has the highest goals all-time in men's football?
short answer : ['Bican', 'Josef Bican']
{'score': 0.17466114461421967, 'start': 102, 'end': 110, 'answer': 'Ali Daei'}
follow question : Who has the highest goals in women's world international football?
short answer : ['Sinclair', 'Christine Sinclair']
{'score': 0.05843370407819748, 'start': 102, 'end': 110, 'answer': 'Ali Daei'}
{'rougeLsum': 36.36363636363637, 'length': 26.0, 'str_em': 33.33333333333333, 'Disambig-F1': 33.33333333333333}
First ans: Simon & Garfunkel
Second ans: Simon & Garfunkel was an American folk rock duo consisting of Paul Simon and Art Garfunkel. They were one of the most popular and influential musical acts of the 1960s, known for their harmonious vocals and introspective songwriting.Simon & Garfunkel's music career began in the early 1960s, when they performed together as a folk duo called Tom and Jerry. However, they went their separate ways in the late 1950s and early 1960s, with Simon attending college and Garfunkel studying at Columbia University.In 1963, Simon and Garfunkel regrouped and began performing together again, this time as Simon & Garfunkel. They signed with Columbia Records and released their debut album, "Wednesday Morning, 3 A.M.," in 1964. Although the album was initially a commercial failure, it eventually gained popularity and became a cult classic.Simon & Garfunkel's breakthrough came with the release of their single "The Sound of Silence" in 1965. The song, which was originally recorded in an acoustic version for their debut album, was remixed with electric instruments and drums by producer Tom Wilson. The new version of the song became a huge success, reaching number one on the Billboard Hot 100 chart in January 1966.The duo's second album, "Sounds of Silence," was released in 1966 and featured a mix of folk rock, pop, and psychedelic sounds. The album included the hit singles "I Am a Rock" and "The Sound of Silence," and became a huge commercial success, reaching number 21 on the Billboard 200 chart.Simon & Garfunkel's music career continued to thrive throughout the 1960s and 1970s, with the release of albums such as "Parsley, Sage, Rosemary and Thyme" and "Bridge Over Troubled Water." They became one of the most popular and influential musical acts of the decade, known for their harmonious vocals and introspective songwriting.Some of their most famous songs include:* "The Sound of Silence"* "I Am a Rock"* "The Boxer"* "Bridge Over Troubled Water"* "Cecilia"* "Mrs. Robinson"Simon & Garfunkel's music has had a lasting impact on the music industry, and they continue to be celebrated as one of the most influential and beloved musical acts of all
Simon & Garfunkel was an American folk rock duo consisting of Paul Simon and Art Garfunkel. They were one of the most popular and influential musical acts of the 1960s, known for their harmonious vocals and introspective songwriting.Simon & Garfunkel's music career began in the early 1960s, when they performed together as a folk duo called Tom and Jerry. However, they went their separate ways in the late 1950s and early 1960s, with Simon attending college and Garfunkel studying at Columbia University.In 1963, Simon and Garfunkel regrouped and began performing together again, this time as Simon & Garfunkel. They signed with Columbia Records and released their debut album, "Wednesday Morning, 3 A.M.," in 1964. Although the album was initially a commercial failure, it eventually gained popularity and became a cult classic.Simon & Garfunkel's breakthrough came with the release of their single "The Sound of Silence" in 1965. The song, which was originally recorded in an acoustic version for their debut album, was remixed with electric instruments and drums by producer Tom Wilson. The new version of the song became a huge success, reaching number one on the Billboard Hot 100 chart in January 1966.The duo's second album, "Sounds of Silence," was released in 1966 and featured a mix of folk rock, pop, and psychedelic sounds. The album included the hit singles "I Am a Rock" and "The Sound of Silence," and became a huge commercial success, reaching number 21 on the Billboard 200 chart.Simon & Garfunkel's music career continued to thrive throughout the 1960s and 1970s, with the release of albums such as "Parsley, Sage, Rosemary and Thyme" and "Bridge Over Troubled Water." They became one of the most popular and influential musical acts of the decade, known for their harmonious vocals and introspective songwriting.Some of their most famous songs include:* "The Sound of Silence"* "I Am a Rock"* "The Boxer"* "Bridge Over Troubled Water"* "Cecilia"* "Mrs. Robinson"Simon & Garfunkel's music has had a lasting impact on the music industry, and they continue to be celebrated as one of the most influential and beloved musical acts of all
Who is the original artist of sound of silence?
['Who is the original artist of sound of silence, the song, released in 1964?', 'Who is the original artist of sound of silence, the album?', 'Who is the original artist of sound of silence, the song, released in 2016?']
[['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon'], ['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon'], ['Dami Im']]

 10%|█         | 2/20 [00:36<06:06, 20.37s/it]

follow question : Who is the original artist of sound of silence, the song, released in 1964?
short answer : ['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon']
{'score': 0.0009827768662944436, 'start': 1080, 'end': 1090, 'answer': 'Tom Wilson'}
follow question : Who is the original artist of sound of silence, the album?
short answer : ['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon']
{'score': 0.13287265598773956, 'start': 1499, 'end': 1516, 'answer': 'Simon & Garfunkel'}
follow question : Who is the original artist of sound of silence, the song, released in 2016?
short answer : ['Dami Im']
{'score': 6.20093260295107e-06, 'start': 1080, 'end': 1090, 'answer': 'Tom Wilson'}
{'rougeLsum': 21.97309417040359, 'length': 348.0, 'str_em': 66.66666666666666, 'Disambig-F1': 33.33333333333333}
First ans: The first Apple iPhone was made in 2005, when Apple started to gather a team of 1,000 employees to work on the highly confidential "Project Purple."
Second ans: The statement is incorrect. The first Apple iPhone was not made in 2005. According to the provided information, development of the iPhone began in 2005, but it was released in 2007. The development cost of the collaboration was estimated to have been $150 million over a thirty-month period, and the original iPhone was introduced by Steve Jobs on January 9, 2007, at the Macworld Conference & Expo held in Moscone West in San Francisco, California.
The statement is incorrect. The first Apple iPhone was not made in 2005. According to the provided information, development of the iPhone began in 2005, but it was released in 2007. The development cost of the collaboration was estimated to have been $150 million over a thirty-month period, and the original iPhone was introduced by Steve Jobs on January 9, 2007, at the Macworld Conference & Expo held in Moscone West in San Francisco, California.
When was the first apple i phone made?
['When was the first apple i phone released?', 'When was the first apple i phone for beta testing made?', 'When was the first apple i phone 1 made?', 'When was the first apple i phone beta made?']
[['June 29, 2007'], ['2004'], ['June 29, 2007.'], ['2004.']]

 15%|█▌        | 3/20 [00:47<04:27, 15.75s/it]

follow question : When was the first apple i phone released?
short answer : ['June 29, 2007']
{'score': 0.5703911781311035, 'start': 176, 'end': 180, 'answer': '2007'}
follow question : When was the first apple i phone for beta testing made?
short answer : ['2004']
{'score': 0.2193128764629364, 'start': 67, 'end': 71, 'answer': '2005'}
follow question : When was the first apple i phone 1 made?
short answer : ['June 29, 2007.']
{'score': 0.3912900984287262, 'start': 67, 'end': 71, 'answer': '2005'}
follow question : When was the first apple i phone beta made?
short answer : ['2004.']
{'score': 0.07923733443021774, 'start': 67, 'end': 71, 'answer': '2005'}
{'rougeLsum': 34.53237410071942, 'length': 75.0, 'str_em': 0.0, 'Disambig-F1': 12.5}
First ans: The Weasley brothers were played by the following actors:* Bill Weasley: Richard Fish (briefly in the film adaptation of Harry Potter and the Prisoner of Azkaban), Domhnall Gleeson (in Harry Potter and the Deathly Hallows)* Charlie Weasley: Alex Crockford (briefly in the film adaptation of Prisoner of Azkaban)* Fred and George Weasley: James and Oliver PhelpsThey are twins who played the identical twin brothers in the film series.
Second ans: The Weasley brothers were played by the following actors:* Bill Weasley: Richard Fish (briefly in the film adaptation of Harry Potter and the Prisoner of Azkaban), Domhnall Gleeson (in Harry Potter and the Deathly Hallows)* Charlie Weasley: Alex Crockford (briefly in the film adaptation of Prisoner of Azkaban)* Fred and George Weasley: James and Oliver Phelps (They are twins who played the identical twin brothers in the film series.)
The Weasley brothers were played by the following actors:* Bill Weasley: Richard Fish (briefly in the film adaptation of Harry Potter and the Prisoner of Azkaban), Domhnall Gleeson (in Harry Potter and the Deathly Hallows)* Charlie Weasley: Alex Crockford (briefly in the film adaptation of Prisoner of Azkaban)* Fred and George Weasley: James and Oliver Phelps (They are twins who played the identical twin brothers in the film series.)
Who played the weasley brothers in harry potter?
['Who played  Bill weasley in Harry Potter and the Prisoner of Azkaban?', 'Who played percy weasley in harry potter?', 'Who played fred weasley in harry potter?', 'Who played ron weasley in harry potter?', 'Who played george weasley in harry potter?', 'Who played  Bill weasley in harry potter (2001-2011)?']
[['Richard Fish'], ['Chris Rankin'], ['James Phelps'], ['Rupert Grint'], ['Oliver Phelps'], ['Domhnall Gleeson']]

 20%|██        | 4/20 [01:00<03:55, 14.71s/it]

follow question : Who played  Bill weasley in Harry Potter and the Prisoner of Azkaban?
short answer : ['Richard Fish']
{'score': 0.6618728637695312, 'start': 73, 'end': 85, 'answer': 'Richard Fish'}
follow question : Who played percy weasley in harry potter?
short answer : ['Chris Rankin']
{'score': 0.7059646844863892, 'start': 73, 'end': 85, 'answer': 'Richard Fish'}
follow question : Who played fred weasley in harry potter?
short answer : ['James Phelps']
{'score': 0.7058833837509155, 'start': 73, 'end': 85, 'answer': 'Richard Fish'}
follow question : Who played ron weasley in harry potter?
short answer : ['Rupert Grint']
{'score': 0.7591727375984192, 'start': 73, 'end': 85, 'answer': 'Richard Fish'}
follow question : Who played george weasley in harry potter?
short answer : ['Oliver Phelps']
{'score': 0.3762194514274597, 'start': 73, 'end': 85, 'answer': 'Richard Fish'}
follow question : Who played  Bill weasley in harry potter (2001-2011)?
short answer : ['Domhnall Gleeson']
{'score': 0.6254032254219055, 'start': 73, 'end': 85, 'answer': 'Richard Fish'}
{'rougeLsum': 48.05194805194806, 'length': 69.0, 'str_em': 50.0, 'Disambig-F1': 16.666666666666664}
First ans: According to the provided context information, there are 38 state parks in Virginia.
Second ans: That's correct. According to the provided context information, there are 38 state parks in Virginia.
That's correct. According to the provided context information, there are 38 state parks in Virginia.
How many state parks are there in virginia?
['How many state parks are there in virginia in 1936?', 'How many state parks are there in virginia in 2016?', 'How many state parks were there when the state park system formed in Virginia?', 'How many state parks were there in Virginia as of 2016?']
[['six'], ['38'], ['6'], ['38']]

 25%|██▌       | 5/20 [01:04<02:45, 11.02s/it]

follow question : How many state parks are there in virginia in 1936?
short answer : ['six']
{'score': 0.008646625094115734, 'start': 73, 'end': 75, 'answer': '38'}
follow question : How many state parks are there in virginia in 2016?
short answer : ['38']
{'score': 0.5548556447029114, 'start': 73, 'end': 75, 'answer': '38'}
follow question : How many state parks were there when the state park system formed in Virginia?
short answer : ['6']
{'score': 0.8253440856933594, 'start': 73, 'end': 75, 'answer': '38'}
follow question : How many state parks were there in Virginia as of 2016?
short answer : ['38']
{'score': 0.575831413269043, 'start': 73, 'end': 75, 'answer': '38'}
{'rougeLsum': 31.999999999999996, 'length': 15.0, 'str_em': 50.0, 'Disambig-F1': 50.0}
First ans: Dua Lipa performed at the opening ceremony preceding the final. Jamaican rapper Sean Paul joined her as a special guest to perform their collaborative song, "No Lie". The UEFA Champions League Anthem was performed by Slovenian–Croatian cello duo 2Cellos.
Second ans: Dua Lipa performed at the opening ceremony preceding the 2018 UEFA Champions League Final, accompanied by Jamaican rapper Sean Paul, who performed their collaborative song "No Lie". Additionally, the Slovenian-Croatian cello duo 2Cellos performed the UEFA Champions League Anthem.
Dua Lipa performed at the opening ceremony preceding the 2018 UEFA Champions League Final, accompanied by Jamaican rapper Sean Paul, who performed their collaborative song "No Lie". Additionally, the Slovenian-Croatian cello duo 2Cellos performed the UEFA Champions League Anthem.
Who performed at the champions league final 2018?
['Who are the teams that performed in competition at the champions league final 2018?', 'Who performed best at the champions league final 2018, winning man of the match?', 'Who performed at the opening ceremony of the champions league final 2018?', 'Who performed the anthem at the champions league final 2018?']
[['Real Madrid and Liverpool', 'Liverpool', 'Real Madrid'], ['Gareth Bale', 'Bale'], ['Dua Lipa', 'Sean Paul', 'Dua Lipa and Sean Paul'], ['2Cellos', 'Luka Šulić and Stjepan Hauser', 'Luka Šulić', '2CΞLLOS', 'Stjepan Hauser']]

 30%|███       | 6/20 [01:13<02:23, 10.27s/it]

follow question : Who are the teams that performed in competition at the champions league final 2018?
short answer : ['Real Madrid and Liverpool', 'Liverpool', 'Real Madrid']
{'score': 0.016498327255249023, 'start': 200, 'end': 236, 'answer': 'Slovenian-Croatian cello duo 2Cellos'}
follow question : Who performed best at the champions league final 2018, winning man of the match?
short answer : ['Gareth Bale', 'Bale']
{'score': 0.87488853931427, 'start': 0, 'end': 8, 'answer': 'Dua Lipa'}
follow question : Who performed at the opening ceremony of the champions league final 2018?
short answer : ['Dua Lipa', 'Sean Paul', 'Dua Lipa and Sean Paul']
{'score': 0.7995817065238953, 'start': 0, 'end': 8, 'answer': 'Dua Lipa'}
follow question : Who performed the anthem at the champions league final 2018?
short answer : ['2Cellos', 'Luka Šulić and Stjepan Hauser', 'Luka Šulić', '2CΞLLOS', 'Stjepan Hauser']
{'score': 0.3890477418899536, 'start': 229, 'end': 236, 'answer': '2Cellos'}
{'rougeLsum': 53.54330708661418, 'length': 39.0, 'str_em': 50.0, 'Disambig-F1': 50.0}
First ans: In the movie Thelma and Louise, the man who was killed was Harlan, a stranger who attempted to rape Thelma. He was shot and killed by Louise after she threatened him with a gun.
Second ans: Harlan, a stranger who attempted to rape Thelma, was shot and killed by Louise after she threatened him with a gun.
Harlan, a stranger who attempted to rape Thelma, was shot and killed by Louise after she threatened him with a gun.
Who killed the man in thelma and louise?
['Which character killed the man in thelma and louise?', 'Which actor killed the man in thelma and louise?', 'Who is the character that kills Harlan in the film Thelma and Louise?', 'Who is the actor of the character that killed a man in the film Thelma and Louise?']
[['Louise Elizabeth Sawyer', 'Louise'], ['Susan Sarandon', 'Susan Abigail Sarandon'], ['Louise Elizabeth Sawyer', 'Louise'], ['Susan Sarandon']]

 35%|███▌      | 7/20 [01:20<01:58,  9.15s/it]

follow question : Which character killed the man in thelma and louise?
short answer : ['Louise Elizabeth Sawyer', 'Louise']
{'score': 0.6458455324172974, 'start': 0, 'end': 6, 'answer': 'Harlan'}
follow question : Which actor killed the man in thelma and louise?
short answer : ['Susan Sarandon', 'Susan Abigail Sarandon']
{'score': 0.6744271516799927, 'start': 0, 'end': 6, 'answer': 'Harlan'}
follow question : Who is the character that kills Harlan in the film Thelma and Louise?
short answer : ['Louise Elizabeth Sawyer', 'Louise']
{'score': 0.6058520078659058, 'start': 10, 'end': 18, 'answer': 'stranger'}
follow question : Who is the actor of the character that killed a man in the film Thelma and Louise?
short answer : ['Susan Sarandon']
{'score': 0.772394597530365, 'start': 0, 'end': 6, 'answer': 'Harlan'}
{'rougeLsum': 15.384615384615383, 'length': 21.0, 'str_em': 50.0, 'Disambig-F1': 0.0}
First ans: Charlie Kelly is played by Charlie Day.
Second ans: Yes, that is correct. Charlie Kelly is played by Charlie Day.
Yes, that is correct. Charlie Kelly is played by Charlie Day.
Who plays charlie on it's always sunny?
["Who does Charlie Day play on It's Always Sunny in Philadelphia?", "Who plays Charlie Kelly on It's Always Sunny in Philadelphia?"]
[['Charlie Kelly'], ['Charlie Day']]

 40%|████      | 8/20 [01:24<01:29,  7.49s/it]

follow question : Who does Charlie Day play on It's Always Sunny in Philadelphia?
short answer : ['Charlie Kelly']
{'score': 0.9868155717849731, 'start': 22, 'end': 35, 'answer': 'Charlie Kelly'}
follow question : Who plays Charlie Kelly on It's Always Sunny in Philadelphia?
short answer : ['Charlie Day']
{'score': 0.9854613542556763, 'start': 49, 'end': 60, 'answer': 'Charlie Day'}
{'rougeLsum': 32.25806451612903, 'length': 11.0, 'str_em': 100.0, 'Disambig-F1': 100.0}
First ans: The Los Angeles Lakers have won the NBA Finals 16 times.
Second ans: Yes, that's correct. The Los Angeles Lakers have won the NBA Finals 16 times, which is the second-most championships in NBA history, behind the Boston Celtics' 17 championships.
Yes, that's correct. The Los Angeles Lakers have won the NBA Finals 16 times, which is the second-most championships in NBA history, behind the Boston Celtics' 17 championships.
How many times have the lakers won the finals?
['As of 2017, how many times have the lakers won the finals?', 'As of 2016, how many times have the Lakers won the finals?', 'As of 2015, how many times have the Lakers won the finals?']
[['16'], ['16'], ['16']]

 45%|████▌     | 9/20 [01:30<01:18,  7.10s/it]

follow question : As of 2017, how many times have the lakers won the finals?
short answer : ['16']
{'score': 0.8009308576583862, 'start': 68, 'end': 70, 'answer': '16'}
follow question : As of 2016, how many times have the Lakers won the finals?
short answer : ['16']
{'score': 0.8325595259666443, 'start': 68, 'end': 70, 'answer': '16'}
follow question : As of 2015, how many times have the Lakers won the finals?
short answer : ['16']
{'score': 0.6845507621765137, 'start': 68, 'end': 70, 'answer': '16'}
{'rougeLsum': 37.83783783783784, 'length': 28.0, 'str_em': 100.0, 'Disambig-F1': 100.0}
First ans: Based on the provided context information, the following states in India are under the Congress:1. Punjab2. Chhattisgarh3. Rajasthan4. Madhya Pradesh5. Puducherry (union territory)6. Maharashtra (as part of the Maha Vikas Aghadi coalition)7. Jharkhand (junior ally with Jharkhand Mukti Morcha)These states and union territories are under the control of the Indian National Congress, either as the ruling party or as part of a coalition government.
Second ans: Based on the provided context information, the following states in India are under the Congress:1. Punjab2. Chhattisgarh3. Rajasthan4. Madhya Pradesh5. Puducherry (union territory)6. Maharashtra (as part of the Maha Vikas Aghadi coalition)7. Jharkhand (junior ally with Jharkhand Mukti Morcha)These states and union territories are under the control of the Indian National Congress, either as the ruling party or as part of a coalition government.
Based on the provided context information, the following states in India are under the Congress:1. Punjab2. Chhattisgarh3. Rajasthan4. Madhya Pradesh5. Puducherry (union territory)6. Maharashtra (as part of the Maha Vikas Aghadi coalition)7. Jharkhand (junior ally with Jharkhand Mukti Morcha)These states and union territories are under the control of the Indian National Congress, either as the ruling party or as part of a coalition government.
How many states in india are under congress?
['How many states plus territories in india are under congress?', 'How many states alone in india are under congress?']
[['7'], ['5']]

 50%|█████     | 10/20 [01:44<01:31,  9.19s/it]

follow question : How many states plus territories in india are under congress?
short answer : ['7']
{'score': 0.023033540695905685, 'start': 96, 'end': 106, 'answer': '1. Punjab2'}
follow question : How many states alone in india are under congress?
short answer : ['5']
{'score': 0.015681445598602295, 'start': 43, 'end': 56, 'answer': 'the following'}
{'rougeLsum': 31.007751937984494, 'length': 64.0, 'str_em': 100.0, 'Disambig-F1': 0.0}
First ans: Fruma-Sarah is the deceased wife of Lazar Wolf, a wealthy butcher in the village of Anatevka. She rises from the grave in Tevye's "nightmare" to warn of severe retribution if Tzeitel marries Lazar.
Second ans: Fruma-Sarah is the deceased wife of Lazar Wolf, a wealthy butcher in the village of Anatevka. She rises from the grave in Tevye's "nightmare" to warn of severe retribution if Tzeitel marries Lazar.
Fruma-Sarah is the deceased wife of Lazar Wolf, a wealthy butcher in the village of Anatevka. She rises from the grave in Tevye's "nightmare" to warn of severe retribution if Tzeitel marries Lazar.
Who is fruma sarah in fiddler on the roof?
['Who played fruma sarah in the 1971 film, Fiddler on the Roof?', 'Who played Fruma Sarah in the original 1964 Broadway cast of Fiddler on the Roof?', 'Who is the character of Fruma Sarah in Fiddler on the Roof?', 'Who played Fruma Sarah in the 2015-2016 Broadway Revival of Fiddler on the Roof?']
[['Ruth Madoc'], ['Carol Sawyer Yussel'], ['a ghostly depiction of the late wife of Lazar Wolf'], ['Jessica Vosk']]

 55%|█████▌    | 11/20 [01:52<01:19,  8.88s/it]

follow question : Who played fruma sarah in the 1971 film, Fiddler on the Roof?
short answer : ['Ruth Madoc']
{'score': 0.0021976102143526077, 'start': 122, 'end': 127, 'answer': 'Tevye'}
follow question : Who played Fruma Sarah in the original 1964 Broadway cast of Fiddler on the Roof?
short answer : ['Carol Sawyer Yussel']
{'score': 0.023890621960163116, 'start': 122, 'end': 127, 'answer': 'Tevye'}
follow question : Who is the character of Fruma Sarah in Fiddler on the Roof?
short answer : ['a ghostly depiction of the late wife of Lazar Wolf']
{'score': 0.5104489326477051, 'start': 36, 'end': 46, 'answer': 'Lazar Wolf'}
follow question : Who played Fruma Sarah in the 2015-2016 Broadway Revival of Fiddler on the Roof?
short answer : ['Jessica Vosk']
{'score': 0.005705648101866245, 'start': 122, 'end': 127, 'answer': 'Tevye'}
{'rougeLsum': 21.897810218978105, 'length': 33.0, 'str_em': 0.0, 'Disambig-F1': 10.0}
First ans: July 9, 1991, the Toronto Blue Jays hosted the MLB All-Star Game at the SkyDome.
Second ans: No, that is incorrect. The Toronto Blue Jays hosted the MLB All-Star Game on July 9, 1991, at the SkyDome, but they were the American League team, and the host team was actually the Toronto Blue Jays.
No, that is incorrect. The Toronto Blue Jays hosted the MLB All-Star Game on July 9, 1991, at the SkyDome, but they were the American League team, and the host team was actually the Toronto Blue Jays.
When did toronto host the mlb all-star game?
['What date did toronto host the mlb all-star game?', 'Which all-star game did toronto host?']
[['July 9, 1991'], ['1991 Major League Baseball All-Star Game', 'the 62nd playing of the midsummer classic']]

 60%|██████    | 12/20 [02:00<01:07,  8.44s/it]

follow question : What date did toronto host the mlb all-star game?
short answer : ['July 9, 1991']
{'score': 0.9494990110397339, 'start': 77, 'end': 89, 'answer': 'July 9, 1991'}
follow question : Which all-star game did toronto host?
short answer : ['1991 Major League Baseball All-Star Game', 'the 62nd playing of the midsummer classic']
{'score': 0.3525626063346863, 'start': 56, 'end': 73, 'answer': 'MLB All-Star Game'}
{'rougeLsum': 39.603960396039604, 'length': 37.0, 'str_em': 50.0, 'Disambig-F1': 72.22222222222221}
First ans: A metallic blue 1953 Sunbeam Alpine Mk I is driven by Grace Kelly in the film "To Catch a Thief" (1955) with Cary Grant.
Second ans: The Sunbeam Alpine Mk I, a metallic blue 1953 model, is driven by Grace Kelly in the 1955 film "To Catch a Thief" starring Cary Grant.
The Sunbeam Alpine Mk I, a metallic blue 1953 model, is driven by Grace Kelly in the 1955 film "To Catch a Thief" starring Cary Grant.
What kind of car in to catch a thief?
['What kind of car in to catch a thief in terms of model?', 'What kind of car in to catch a thief in terms of automobile make?']
[['Sunbeam Alpine', '1953 Sunbeam Alpine Mk I'], ['Rootes Group']]

 65%|██████▌   | 13/20 [02:07<00:55,  7.99s/it]

follow question : What kind of car in to catch a thief in terms of model?
short answer : ['Sunbeam Alpine', '1953 Sunbeam Alpine Mk I']
{'score': 0.5046610832214355, 'start': 4, 'end': 23, 'answer': 'Sunbeam Alpine Mk I'}
follow question : What kind of car in to catch a thief in terms of automobile make?
short answer : ['Rootes Group']
{'score': 0.5758154988288879, 'start': 4, 'end': 23, 'answer': 'Sunbeam Alpine Mk I'}
{'rougeLsum': 31.746031746031743, 'length': 26.0, 'str_em': 50.0, 'Disambig-F1': 44.44444444444445}
First ans: The last season of Jersey Shore (Season 6) aired from October 4, 2012, to December 20, 2012.
Second ans: The last season of Jersey Shore (Season 6) actually aired from October 4, 2012, to December 4, 2012, not December 20, 2012.
The last season of Jersey Shore (Season 6) actually aired from October 4, 2012, to December 4, 2012, not December 20, 2012.
When did the last season of jersey shore air?
['When did season 4 of jersey shore first air?', 'When did season 4 of jersey shore last air?', 'When did season 5 of jersey shore first air?', 'When did season 5 of jersey shore last air?', 'When did season 6 of jersey shore first air?', 'When did season 6 of jersey shore last air?']
[['August 4, 2011'], ['October 20, 2011'], ['January 5, 2012'], ['March 15, 2012'], ['October 4, 2012'], ['December 20, 2012']]

 70%|███████   | 14/20 [02:13<00:45,  7.63s/it]

follow question : When did season 4 of jersey shore first air?
short answer : ['August 4, 2011']
{'score': 0.07206683605909348, 'start': 63, 'end': 78, 'answer': 'October 4, 2012'}
follow question : When did season 4 of jersey shore last air?
short answer : ['October 20, 2011']
{'score': 0.2847982347011566, 'start': 83, 'end': 99, 'answer': 'December 4, 2012'}
follow question : When did season 5 of jersey shore first air?
short answer : ['January 5, 2012']
{'score': 0.021944589912891388, 'start': 63, 'end': 78, 'answer': 'October 4, 2012'}
follow question : When did season 5 of jersey shore last air?
short answer : ['March 15, 2012']
{'score': 0.09906397759914398, 'start': 63, 'end': 78, 'answer': 'October 4, 2012'}
follow question : When did season 6 of jersey shore first air?
short answer : ['October 4, 2012']
{'score': 0.17413854598999023, 'start': 63, 'end': 78, 'answer': 'October 4, 2012'}
follow question : When did season 6 of jersey shore last air?
short answer : ['December 20, 2012']
{'score': 0.6348809599876404, 'start': 63, 'end': 78, 'answer': 'October 4, 2012'}
{'rougeLsum': 43.0379746835443, 'length': 22.0, 'str_em': 33.33333333333333, 'Disambig-F1': 38.88888888888889}
First ans: The plane crash occurred in the Season 8 episode "Flight" which is the 24th episode of the season and the 172nd episode overall.
Second ans: The plane crash occurred in the Season 8 episode "Flight" which is the 24th episode of the season and the 172nd episode overall.
The plane crash occurred in the Season 8 episode "Flight" which is the 24th episode of the season and the 172nd episode overall.
What season of greys anatomy was the plane crash?
["What season of Grey's Anatomy was the plane crash involving six doctors?", "What season of Grey's Anatomy was the plane crash in Seattle that brought memories of a previous plane crash?", "What season of Grey's Anatomy was the plane crash that claimed the life of Lexie Grey?", "What season of Grey's Anatomy was the plane crash in downtown Seattle?"]
[['season 8'], ['season 11'], ['8'], ['11']]

 75%|███████▌  | 15/20 [02:20<00:36,  7.23s/it]

follow question : What season of Grey's Anatomy was the plane crash involving six doctors?
short answer : ['season 8']
{'score': 0.8863816857337952, 'start': 32, 'end': 40, 'answer': 'Season 8'}
follow question : What season of Grey's Anatomy was the plane crash in Seattle that brought memories of a previous plane crash?
short answer : ['season 11']
{'score': 0.9001052379608154, 'start': 32, 'end': 40, 'answer': 'Season 8'}
follow question : What season of Grey's Anatomy was the plane crash that claimed the life of Lexie Grey?
short answer : ['8']
{'score': 0.8906877040863037, 'start': 32, 'end': 40, 'answer': 'Season 8'}
follow question : What season of Grey's Anatomy was the plane crash in downtown Seattle?
short answer : ['11']
{'score': 0.9075095653533936, 'start': 32, 'end': 40, 'answer': 'Season 8'}
{'rougeLsum': 32.35294117647059, 'length': 23.0, 'str_em': 50.0, 'Disambig-F1': 54.166666666666664}
First ans: According to the provided context information, the Oriental Bank of Commerce had 2390 branches across India as of the 2018-2019 annual report.
Second ans: According to the provided context information, the Oriental Bank of Commerce had 2390 branches across India as of the 2018-2019 annual report.
According to the provided context information, the Oriental Bank of Commerce had 2390 branches across India as of the 2018-2019 annual report.
Number of branches of oriental bank of commerce in india?
['As per the March 2018-2019 report, what is the number of branches of oriental bank of commerce in india?', 'What is the number of branches of oriental bank of commerce in india after amalgamation of Global Trust Bank?', 'Number of branches of oriental bank of commerce in india after expected merger with United Bank of India in 2020?']
[['2390'], ['1092'], ['11,437']]

 80%|████████  | 16/20 [02:26<00:28,  7.04s/it]

follow question : As per the March 2018-2019 report, what is the number of branches of oriental bank of commerce in india?
short answer : ['2390']
{'score': 0.8879122734069824, 'start': 81, 'end': 85, 'answer': '2390'}
follow question : What is the number of branches of oriental bank of commerce in india after amalgamation of Global Trust Bank?
short answer : ['1092']
{'score': 0.7891730070114136, 'start': 81, 'end': 85, 'answer': '2390'}
follow question : Number of branches of oriental bank of commerce in india after expected merger with United Bank of India in 2020?
short answer : ['11,437']
{'score': 0.4474791884422302, 'start': 81, 'end': 85, 'answer': '2390'}
{'rougeLsum': 30.952380952380953, 'length': 22.0, 'str_em': 33.33333333333333, 'Disambig-F1': 33.33333333333333}
First ans: 1995
Second ans: Here are some of the notable events and information from the provided context related to the year 1995:1. **Windows 95**: Microsoft released Windows 95, a new version of its operating system, on August 24, 1995. This operating system was designed to be more user-friendly and efficient than its predecessors.2. **1995 Canadian Open**: The 1995 Canadian Open was a men's and women's professional tennis tournament that took place in Montreal, Quebec, Canada, from July 24 to July 31, 1995, and in Toronto, Ontario, Canada, from August 13 to August 20, 1995.3. **Manchester United**: The 1995-96 season was a significant one for Manchester United, as they won the league title and the FA Cup, with Sir Alex Ferguson at the helm.4. **UEFA Champions League**: The 1995-96 UEFA Champions League season saw the introduction of a new format, with the top teams from each group advancing to the quarterfinals.5. **Major League Baseball**: The 1995 season was a notable one for Major League Baseball, with the Colorado Rockies and the New York Yankees competing for the World Series title.6. **FIFA World Cup**: The 1994 FIFA World Cup was held in the United States, and the 1998 FIFA World Cup was held in France. The 1995-96 season was a significant one for the FIFA World Cup, with the introduction of new rules and regulations.7. **Personal Computers**: The 1990s saw significant advancements in personal computers, with the introduction of new technologies such as CD-ROMs, ThinkPads, and Power Macintosh computers.These are just a few of the notable events and information related to the year 1995 from the provided context.
Here are some of the notable events and information from the provided context related to the year 1995:1. **Windows 95**: Microsoft released Windows 95, a new version of its operating system, on August 24, 1995. This operating system was designed to be more user-friendly and efficient than its predecessors.2. **1995 Canadian Open**: The 1995 Canadian Open was a men's and women's professional tennis tournament that took place in Montreal, Quebec, Canada, from July 24 to July 31, 1995, and in Toronto, Ontario, Canada, from August 13 to August 20, 1995.3. **Manchester United**: The 1995-96 season was a significant one for Manchester United, as they won the league title and the FA Cup, with Sir Alex Ferguson at the helm.4. **UEFA Champions League**: The 1995-96 UEFA Champions League season saw the introduction of a new format, with the top teams from each group advancing to the quarterfinals.5. **Major League Baseball**: The 1995 season was a notable one for Major League Baseball, with the Colorado Rockies and the New York Yankees competing for the World Series title.6. **FIFA World Cup**: The 1994 FIFA World Cup was held in the United States, and the 1998 FIFA World Cup was held in France. The 1995-96 season was a significant one for the FIFA World Cup, with the introduction of new rules and regulations.7. **Personal Computers**: The 1990s saw significant advancements in personal computers, with the introduction of new technologies such as CD-ROMs, ThinkPads, and Power Macintosh computers.These are just a few of the notable events and information related to the year 1995 from the provided context.
When did the rams go to st louis?
['In what year did the rams go to St. Louis?', 'What was the first game the Rams played in St. Louis?']
[['1995'], ['September 10, 1995']]

 85%|████████▌ | 17/20 [02:47<00:33, 11.20s/it]

follow question : In what year did the rams go to St. Louis?
short answer : ['1995']
{'score': 0.0012254201574251056, 'start': 98, 'end': 102, 'answer': '1995'}
follow question : What was the first game the Rams played in St. Louis?
short answer : ['September 10, 1995']
{'score': 1.4408171409741044e-05, 'start': 98, 'end': 102, 'answer': '1995'}
{'rougeLsum': 20.971867007672635, 'length': 262.0, 'str_em': 50.0, 'Disambig-F1': 75.0}
First ans: The Voortrekkers, a group of Dutch-speaking settlers, began their trek into South Africa in 1835. The first two parties left in September 1835, led by Louis Tregardt and Hans van Rensburg. They crossed the Vaal river at Robert's Drift in January 1836.However, the question seems to refer to the Voortrekkers as a youth organization, which was established in 1931. In this case, the answer would be:The Voortrekkers youth organization was established in 1931, and its first "Kommando" (Troop) was established in Bloemfontein at the Central High School in 1920.
Second ans: The Voortrekkers youth organization was established in 1931, and its first "Kommando" (Troop) was established in Bloemfontein at the Central High School in 1920.
The Voortrekkers youth organization was established in 1931, and its first "Kommando" (Troop) was established in Bloemfontein at the Central High School in 1920.
When did the voortrekkers arrive in south africa?
['When did the first wave of voortrekkers arrive in south africa?', 'When did the voortrekkers exploratory treks arrive in south africa?']
[['1836', '1836 onwards'], ['February 1835']]

 90%|█████████ | 18/20 [02:59<00:22, 11.42s/it]

follow question : When did the first wave of voortrekkers arrive in south africa?
short answer : ['1836', '1836 onwards']
{'score': 0.0015232550213113427, 'start': 156, 'end': 160, 'answer': '1920'}
follow question : When did the voortrekkers exploratory treks arrive in south africa?
short answer : ['February 1835']
{'score': 4.85175805806648e-05, 'start': 55, 'end': 59, 'answer': '1931'}
{'rougeLsum': 29.78723404255319, 'length': 24.0, 'str_em': 0.0, 'Disambig-F1': 0.0}
First ans: Heath Ledger plays Patrick Verona in the 1999 film "10 Things I Hate About You."
Second ans: Yes, that's correct. In the 1999 film "10 Things I Hate About You," Heath Ledger plays the role of Patrick Verona, the "bad boy" who is hired to date Kat Stratford, played by Julia Stiles.
Yes, that's correct. In the 1999 film "10 Things I Hate About You," Heath Ledger plays the role of Patrick Verona, the "bad boy" who is hired to date Kat Stratford, played by Julia Stiles.
Who plays patrick in 10 things i hate about you?
['Who plays patrick in  the 1999 film 10 things i hate about you?', 'Who plays patrick in the 2009 tv series 10 things i hate about you?', 'Who plays patrick in the film 10 things i hate about you?', 'Who plays patrick in the TV series 10 things i hate about you?']
[['Heath Andrew Ledger', 'Heath Ledger', 'Ledger'], ['Ethan Peck', 'Peck', 'Ethan Gregory Peck'], ['Heath Andrew Ledger', 'Heath Ledger'], ['Ethan Peck', 'Ethan Gregory Peck']]

 95%|█████████▌| 19/20 [03:06<00:09,  9.98s/it]

follow question : Who plays patrick in  the 1999 film 10 things i hate about you?
short answer : ['Heath Andrew Ledger', 'Heath Ledger', 'Ledger']
{'score': 0.9635234475135803, 'start': 68, 'end': 80, 'answer': 'Heath Ledger'}
follow question : Who plays patrick in the 2009 tv series 10 things i hate about you?
short answer : ['Ethan Peck', 'Peck', 'Ethan Gregory Peck']
{'score': 1.869488914962858e-05, 'start': 68, 'end': 80, 'answer': 'Heath Ledger'}
follow question : Who plays patrick in the film 10 things i hate about you?
short answer : ['Heath Andrew Ledger', 'Heath Ledger']
{'score': 0.8692940473556519, 'start': 68, 'end': 80, 'answer': 'Heath Ledger'}
follow question : Who plays patrick in the TV series 10 things i hate about you?
short answer : ['Ethan Peck', 'Ethan Gregory Peck']
{'score': 0.00026919867377728224, 'start': 68, 'end': 80, 'answer': 'Heath Ledger'}
{'rougeLsum': 42.10526315789474, 'length': 35.0, 'str_em': 50.0, 'Disambig-F1': 50.0}
First ans: No, Microsoft Live Movie Maker is not an example of a free product. It is a freeware product, which means it is free to download and use, but it is not open-source. It is a proprietary software developed by Microsoft, and its source code is not available for modification or redistribution.
Second ans: Microsoft Live Movie Maker is actually an example of a freeware product, not a free product. It is a proprietary software developed by Microsoft, and its source code is not available for modification or redistribution. While it is free to download and use, it is not open-source, and its development and maintenance are controlled by Microsoft.
Microsoft Live Movie Maker is actually an example of a freeware product, not a free product. It is a proprietary software developed by Microsoft, and its source code is not available for modification or redistribution. While it is free to download and use, it is not open-source, and its development and maintenance are controlled by Microsoft.
Microsoft live movie maker is an example of free?
['Microsoft live movie maker is an example of a freely licensed software, often called free what?', 'Microsoft live movie maker is an example of free software used for what purpose?']
[['freeware'], ['Video editing software']]

100%|██████████| 20/20 [03:14<00:00,  9.75s/it]

follow question : Microsoft live movie maker is an example of a freely licensed software, often called free what?
short answer : ['freeware']
{'score': 0.023067617788910866, 'start': 55, 'end': 63, 'answer': 'freeware'}
follow question : Microsoft live movie maker is an example of free software used for what purpose?
short answer : ['Video editing software']
{'score': 0.2880362868309021, 'start': 239, 'end': 255, 'answer': 'download and use'}
{'rougeLsum': 32.608695652173914, 'length': 56.0, 'str_em': 50.0, 'Disambig-F1': 50.0}

rougeLsum      33.400839
length         61.800000
str_em         48.333333
Disambig-F1    41.194444
dtype: float64

In [25]:
scores_df.to_csv('./results/answer_rag_2_results.csv', index=False)

In [77]:
import pandas as pd
import math
sf = pd.read_csv('results/answer_rag_full_results.csv')
sf=sf[sf['length']<1000][:20]
print(len(sf))
print(sf.mean())
r=sf.mean()['rougeLsum']
d=sf.mean()['Disambig-F1']
dr=math.sqrt(r*d)
print(dr)

20
rougeLsum      32.897948
length         67.700000
str_em         57.916667
Disambig-F1    49.930556
dtype: float64
40.52916036496496