In [1]:
import os
import importlib
os.environ["CUDA_VISIBLE_DEVICES"]="1,2"
from transformers import AutoTokenizer, BitsAndBytesConfig, AutoModelForCausalLM, AutoModel
from datasets import load_dataset
import torch
#from sentence_transformers import SentenceTransformer, InputExample, losses
#from sentence_transformers.evaluation import EmbeddingSimilarityEvaluator, SimilarityFunction
from torch.utils.data import DataLoader
from datasets import Dataset
import pandas as pd
from collections import defaultdict
import re
import numpy as np
import time

device1 = 'cuda:0'
device2 = 'cuda:1'
data_dir = '/raid/deallab/SF_RAG_Data/ASQA'
# data_dir = '../data'

/home/dataconv/anaconda3/envs/sf_rag_djk/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
#load embeddings
embedd_test_path = f'{data_dir}/test/embedd_test.npy'
evidence_embeddings = np.load(embedd_test_path)
print(evidence_embeddings.shape)
evidence_embeddings = torch.from_numpy(evidence_embeddings).to(device1)

#load evidence
evidence_test_path = f'{data_dir}/test/evidence_test.csv'
evidence_df = pd.read_csv(evidence_test_path)

#load qa data
qa_df=pd.read_csv(f'{data_dir}/test/qa_test.csv') #data=df[['question','long_answers']] # questions=data['question'] #references = [row.to_dict() for i, row in df.iterrows() if i < len(questions)]
qa_df.head()

(21586, 4096)

,id,sample_id,question,follow_up_questions,long_answers,short_answers
0,c2687961-0957-45cb-bae0-42314e38f790,-7013890438520559398,Who has the highest goals in world football?,"[""Who has the highest goals in men's world int...","[""Ali Dael has the highest goals in men's worl...","[['Daei', 'Ali Daei'], ['Bican', 'Josef Bican'..."
1,26830122-8240-40a9-aaff-d9731d53b197,7089015503030534342,Who is the original artist of sound of silence?,['Who is the original artist of sound of silen...,[' The original artist of the song sound of si...,"[['Simon & Garfunkel', 'Paul Simon and Art Gar..."
2,268116a9-5ecb-4364-8da4-4a648f9d5b43,8793099883447006698,When was the first apple i phone made?,"['When was the first apple i phone released?',...",['The iPhone beta was created in 2004 to test ...,"[['June 29, 2007'], ['2004'], ['June 29, 2007...."
3,efb4810e-637b-4954-a776-3c2d05d1290c,-881464876144297194,Who played the weasley brothers in harry potter?,['Who played Bill weasley in Harry Potter and...,['Rupert Grint played Ron Weasley in all the H...,"[['Richard Fish'], ['Chris Rankin'], ['James P..."
4,99817eba-d32a-4c4d-9fe2-93a50ae1d367,1650309494326541834,How many state parks are there in virginia?,['How many state parks are there in virginia i...,['When the Virginia state park system was form...,"[['six'], ['38'], ['6'], ['38']]"

In [3]:
#load quantized model
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_storage=torch.bfloat16,
)

# load model with tokenizer
model = AutoModel.from_pretrained(
    'nvidia/NV-Embed-v2', 
    trust_remote_code=True,
    quantization_config = bnb_config,
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage =True,
)
model.eval()

Loading checkpoint shards: 100%|██████████| 4/4 [00:06<00:00,  1.67s/it]

NVEmbedModel(
  (latent_attention_model): LatentAttentionModel(
    (cross_attend_blocks): ModuleList(
      (0): PreNorm(
        (fn): Attention(
          (to_q): Linear4bit(in_features=4096, out_features=32768, bias=False)
          (to_kv): Linear4bit(in_features=4096, out_features=65536, bias=False)
          (to_out): Linear4bit(in_features=32768, out_features=4096, bias=False)
        )
        (norm): LayerNorm((4096,), eps=1e-05, elementwise_affine=True)
        (norm_context): LayerNorm((4096,), eps=1e-05, elementwise_affine=True)
      )
      (1): PreNorm(
        (fn): FeedForward(
          (net): Sequential(
            (0): Linear4bit(in_features=4096, out_features=32768, bias=True)
            (1): GEGLU()
            (2): Linear4bit(in_features=16384, out_features=4096, bias=True)
          )
        )
        (norm): LayerNorm((4096,), eps=1e-05, elementwise_affine=True)
      )
    )
  )
  (embedding_model): BidirectionalMistralModel(
    (embed_tokens): Embedding(32000, 4096)
    (layers): ModuleList(
      (0-31): 32 x MistralDecoderLayer(
        (self_attn): MistralSdpaAttention(
          (q_proj): Linear4bit(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear4bit(in_features=4096, out_features=1024, bias=False)
          (v_proj): Linear4bit(in_features=4096, out_features=1024, bias=False)
          (o_proj): Linear4bit(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): MistralRotaryEmbedding()
        )
        (mlp): MistralMLP(
          (gate_proj): Linear4bit(in_features=4096, out_features=14336, bias=False)
          (up_proj): Linear4bit(in_features=4096, out_features=14336, bias=False)
          (down_proj): Linear4bit(in_features=14336, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): MistralRMSNorm()
        (post_attention_layernorm): MistralRMSNorm()
      )
    )
    (norm): MistralRMSNorm()
  )
)

In [4]:
#load tokenizer
tokenizer_gen = AutoTokenizer.from_pretrained("meta-llama/Meta-Llama-3.1-8B-Instruct")
# cache_dir= '/raid/deallab/.cache')
tokenizer_gen.pad_token = tokenizer_gen.eos_token

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    # bnb_4bit_quant_type="nf4",
    # bnb_4bit_compute_dtype=torch.bfloat16,
    # bnb_4bit_use_double_quant=True,
    # bnb_4bit_quant_storage=torch.bfloat16,
)

model_gen = AutoModelForCausalLM.from_pretrained(
    "meta-llama/Meta-Llama-3.1-8B-Instruct",
    quantization_config=bnb_config,
    torch_dtype=torch.bfloat16,
    device_map= 'auto',
    # cache_dir= '/raid/deallab/.cache'
)
model_gen.eval()

Loading checkpoint shards: 100%|██████████| 4/4 [00:02<00:00,  1.38it/s]

LlamaForCausalLM(
  (model): LlamaModel(
    (embed_tokens): Embedding(128256, 4096)
    (layers): ModuleList(
      (0-31): 32 x LlamaDecoderLayer(
        (self_attn): LlamaSdpaAttention(
          (q_proj): Linear4bit(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear4bit(in_features=4096, out_features=1024, bias=False)
          (v_proj): Linear4bit(in_features=4096, out_features=1024, bias=False)
          (o_proj): Linear4bit(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear4bit(in_features=4096, out_features=14336, bias=False)
          (up_proj): Linear4bit(in_features=4096, out_features=14336, bias=False)
          (down_proj): Linear4bit(in_features=14336, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm()
        (post_attention_layernorm): LlamaRMSNorm()
      )
    )
    (norm): LlamaRMSNorm()
    (rotary_emb): LlamaRotaryEmbedding()
  )
  (lm_head): Linear(in_features=4096, out_features=128256, bias=False)
)

In [5]:
import pandas as pd
evidence_test_path = f'/raid/deallab/SF_RAG_Data/ASQA/test/evidence_test.csv'

evidence_text = pd.read_csv(evidence_test_path)

In [6]:
evidence_text

                                                    text
0      Document: International Federation of Football...
1      Document: International Federation of Football...
2      Document: International Federation of Football...
3      Document: International Federation of Football...
4      Document: International Federation of Football...
...                                                  ...
21581  Document: Sign of the Times (Harry Styles song...
21582  Document: Sign of the Times (Harry Styles song...
21583  Document: Sign of the Times (Harry Styles song...
21584  Document: Sign of the Times (Harry Styles song...
21585  Document: Sign of the Times (Harry Styles song...

[21586 rows x 1 columns]

In [8]:
evidence_text_list = evidence_text['text'].tolist()

In [22]:
evidence_text_list[0]

"Document: International Federation of Football History & Statistics\n\n\n\nTitle: N/A\nDescription: N/A\n\nFields:\nFormation: 1984\nHeadquarters: Lausanne, Switzerland\nOfficial language: English, French, Spanish, German\nPresident: Saleh Bahwini[1]\nWebsite: http://iffhs.de/\n\nSingles Chronology:\n\nExternal Links:\nThe International Federation of Football History & Statistics (IFFHS) is an organization that chronicles the history and records of association football.[2][3][4] \nIt was founded on 27 March 1984 in Leipzig by Alfredo Pöge with the blessings of general secretary of the FIFA at the time, Helmut Käser.[2] The IFFHS was based at Al-Muroor Street 147, Abu Dhabi for some time but, in 2010, relocated to Bonn, Germany.[5]\n\nDuring its early stages, and until 2002, the IFFHS concentrated on publishing the quarterly magazines Fußball-Weltzeitschrift, Libero spezial deutsch and Libero international.[6] When these had to be discontinued for reasons which were not officially told, the organization published its material in a series of multi-lingual books in co-operation with sponsors.[7]  The statistical organization has now confined its publishing activities to its website, receiving support from FIFA,[7] organization that recognise the IFFHS and its work[4][7] although the latter has no affiliation with the football's governing body.[8]\n\n"

In [57]:
from langchain_text_splitters import TokenTextSplitter

text_splitter = TokenTextSplitter(
    chunk_size=500,  # 청크 크기를 10으로 설정합니다.
    chunk_overlap=50,  # 청크 간 중복을 0으로 설정합니다.
)
# combined_text = " ".join(evidence_text_list)
# texts = text_splitter.split_text(combined_text)
split_texts = [text_splitter.split_text(text)[0] for text in evidence_text_list]
print(split_texts[0])

Document: International Federation of Football History & Statistics



Title: N/A
Description: N/A

Fields:
Formation: 1984
Headquarters: Lausanne, Switzerland
Official language: English, French, Spanish, German
President: Saleh Bahwini[1]
Website: http://iffhs.de/

Singles Chronology:

External Links:
The International Federation of Football History & Statistics (IFFHS) is an organization that chronicles the history and records of association football.[2][3][4]
It was founded on 27 March 1984 in Leipzig by Alfredo Pöge with the blessings of general secretary of the FIFA at the time, Helmut Käser.[2] The IFFHS was based at Al-Muroor Street 147, Abu Dhabi for some time but, in 2010, relocated to Bonn, Germany.[5]

During its early stages, and until 2002, the IFFHS concentrated on publishing the quarterly magazines Fußball-Weltzeitschrift, Libero spezial deutsch and Libero international.[6] When these had to be discontinued for reasons which were not officially told, the organization published its material in a series of multi-lingual books in co-operation with sponsors.[7]  The statistical organization has now confined its publishing activities to its website, receiving support from FIFA,[7] organization that recognise the IFFHS and its work[4][7] although the latter has no affiliation with the football's governing body.[8]

In [72]:
from langchain.retrievers import BM25Retriever, EnsembleRetriever
from langchain.vectorstores import FAISS

# bm25 retriever와 faiss retriever를 초기화합니다.
bm25_retriever = BM25Retriever.from_texts(
    evidence_text_list,
)
bm25_retriever.k = 10  # BM25Retriever의 검색 결과 개수를 1로 설정합니다.

# embedding = model
# faiss_vectorstore = FAISS.from_texts(
#     evidence_text,
#     embedding,
# )
# faiss_retriever = faiss_vectorstore.as_retriever(search_kwargs={"k": 2})

# # 앙상블 retriever를 초기화합니다.
# ensemble_retriever = EnsembleRetriever(
#     retrievers=[bm25_retriever, faiss_retriever],
#     weights=[0.7, 0.3],
# )

In [75]:
from langchain_community.document_transformers import LongContextReorder

def bm25_retrieve(query):
    bm25_result = bm25_retriever.invoke(query)
    bm25_docs=list()

    print("[BM25 Retriever]")
    for doc in bm25_result:
        # print(f"Content: {doc.page_content}")
        # print()
        bm25_docs.append(doc.page_content)
    reordering = LongContextReorder()
    bm25_docs = reordering.transform_documents(bm25_docs)
    return bm25_docs

In [76]:
res=bm25_retrieve("Who has the highest goals in world football?")
res

[BM25 Retriever]

['Document: List of players with five or more goals in an NHL game\n\nThis is a list of players who have scored five or more goals in a National Hockey League (NHL) game. Scoring five or more goals in a single game is considered a great feat, as it has only been accomplished 61 times, by 45 players, in the history of the league.[1] The first player to do so was Joe Malone, with the Montreal Canadiens, in the first ever NHL game, on December 19, 1917. The most recent player to do so was Patrik Laine, with the Winnipeg Jets, in the 101st NHL season of play, on November 24, 2018.\n\nIn addition to being first, Joe Malone holds the overall record with five different five-or-more goal games, including the NHL record seven goals in a game, as well as a six-goal game and three five-goal games – all in the first three seasons of the NHL’s existence. He is also the only player to record a five-goal game with more than one team, accomplishing his first three with the Montreal Canadiens and his last two with the Quebec Bulldogs.\n\nOverall, seven different players have scored six goals in a game—including brothers Corb and Cy Denneny, with different teams, within a few weeks of each other in 1921. A total of 40 individual players have scored exactly five goals in a game, on one or more occasions. While five-goal games continue to occur from time to time, no player has scored six or more goals since Darryl Sittler scored six in February 1976.[2]\n\nOnly eight players have multiple five-goal games. Next to Malone achieving the mark five different times, both Wayne Gretzky and Mario Lemieux attained the feat four times, Newsy Lalonde did it three times, while four other players have had two five-goal games. Of the eight players with multiple five-goal games, only two have achieved the multiple in a single season: Malone (3 times in 1917–18, twice in 1919–20) and Sittler (twice in 1975–76). Gretzky (early and late 1981) and Maurice Richard (early and late 1944) had two five-goal games in the same calendar year, across two NHL seasons.\n\nIan Turnbull is the only defenseman who has scored five goals in a game, doing so in February 1977. Mario Lemieux is the only player in history to achieve a five-goal game by scoring in five different ways – in December 1988, he scored an even-strength goal, a power-play goal, a short-handed goal, a penalty shot goal and an empty net goal.[3] Wayne Gretzky’s second five-goal game, in December 1981, also marked his achievement of the NHL’s fastest ever 50 goals in 50 games, when he scored five goals in his 39th game of the season.\n\nOf the 61 different five-goal games, five instances were achieved in a playoff game.[4]\n\nThe Montreal Canadiens have had the highest number of players, 9, and the highest number of occurrences, 14, of a five-goal game. The Toronto St. Patricks/Toronto Maple Leafs are second in both categories, with 7 different players scoring a five-goal game, on 9 different occasions.\n\n',
 "Document: List of men's footballers with 50 or more international goals\n\n\n\nThe first player to score 50 international goals was Poul Nielsen of Denmark. He achieved this feat on his 36th cap against Sweden in the 1924–28 Nordic Football Championship on 14 June 1925. This is also the least number of matches played by any player to score 50 goals. He scored 52 goals in just 38 matches in his international career.[1][2][3][4]\nFerenc Puskás of Hungary was the second player and the second European after Nielsen to achieve the feat. His 50th goal came on 24 July 1952, when he scored a brace (two goals) in the semi-final match against Turkey at the 1952 Summer Olympics.[5] Puskás scored 84 goals in his international career.[6] He remained the highest international goalscorer for 47 years following his 84th goal in 1956 against Austria until Ali Daei of Iran broke the record in 2003 after scoring his 85th goal against Lebanon.[7] Daei is the only player to score over 100 goals in international football with 109 goals.[8][9] He scored his 50th goal in a friendly match against Mexico on 9 January 2000, becoming the first Asian footballer to achieve the feat. His 100th goal came on 17 November 2004, when he scored a hat-trick (in this case four goals) against Laos in the 2006 FIFA World Cup qualification.[10] However, the first player from Asia to score at least 50 goals was Japan's Kunishige Kamamoto. He achieved the feat after scoring against Malaysia in 1972 Merdeka Tournament and he went on to score 80 goals for his country in 84 international appearances.[11][12] Just two years after Puskás' scored his 50th goal, his teammate Sándor Kocsis did the same on 19 September 1954 in a friendly match against Romania.[13] He became the third player and the third European to achieve the feat. He went on to score a total of 75 goals in 65 matches in international football.[14]\nPelé of Brazil was the first player from outside Europe and the first player from South America to score at least 50 goals. He attained this in a friendly match against the Soviet Union on 21 November 1965. He scored 77 international goals in 92 matches.[15] Malawi's Kinnah Phiri  was the first player from Africa, and also the youngest player, to score 50 international goals. He scored his 50th goal in a friendly match against Sierra Leone on 6 July 1978 when he was 23 years 8 months and 6 days old.[16] Stern John of Trinidad and Tobago was the first player from North America to score 50 international goals. He scored 70 goals in 115 matches with his 50th goal coming in a friendly match against the Dominican Republic on 13 June 2004.[17]\n\nTo date four players each representing Brazil and Hungary have scored 50 or more international goals. Iraq and Japan each have three players who have achieved the feat. The Asian Football Confederation (AFC) has the highest number of footballers who have scored at least 50 goals in their international career with 23 players achieving the feat to date.[18]\n\nBader Al-Mutawa of Kuwait has played the most matches so far to score 50 international goals.[19] He scored his 50th goal during his 155th international appearance, while scoring a hat-trick against Myanmar on 3 September 2015 during 2018 FIFA World Cup qualification matches.[20]\n\n",
 "Document: Pakistan men's national field hockey team\n\n\n\nTitle: Home\nDescription: N/A\n\nFields:\nNickname(s): Green Shirts; Green Machines\nAssociation: Pakistan Hockey Federation(PHF)\nConfederation: ASHF(Asia)\nHead Coach: Khawaja Junaid\nAssistant coach(es): Waseem AhmedSameer HussainAjmal Khan\nManager: Khawaja Junaid\nCaptain: Muhammad Rizwan Sr.\nMostcaps: Waseem Ahmad(410)\nTop scorer: Sohail Abbas(348)\nCurrent: 151 (23 November 2024)[1]\nHighest: 4(2004)\nLowest: 17(June 2019 – present)\nAppearances: 17 (first in1948)\nBest result: 1st (1960,1968,1984)\nAppearances: 13 (first in1971)\nBest result: 1st (1971,1978,1982and1994)\nAppearances: 31 (first in 1978)\nBest result: 1st (1978,1980and1994)\nAppearances: 16 (first in1958)\nBest result: 1st (1958,1962,1970,1974,1978,1982,1990,2010)\n\nSingles Chronology:\n (Home)\n (Away)\nHome (Home)\n\nExternal Links:\nTitle: N/A\nDescription: N/A\n\nFields:\n\nSingles Chronology:\n\nExternal Links:\nThe Pakistan national field hockey team (Template:Lang-ur)[2] is administered by the Pakistan Hockey Federation (PHF), the governing body for hockey in Pakistan. They have been a member of the International Hockey Federation (FIH) since 1948 and founding member of the Asian Hockey Federation (ASHF) which formed in 1958.[3] Pakistan is the most successful national field hockey team in the Hockey World Cup with four championships: 1971, 1978, 1982 and 1994. Pakistan also has the best overall performance in World Cup history in both proportional and absolute terms with 53 victories in 84 matches played, seven time draws, six appearances in the finals and only 24 losses. Pakistan national team has played in all FIH World Cup editions with only one absence in 2014. The green shirts is also one of the most successful national teams in the Asian Games with eight gold medals: 1958, 1962, 1970, 1974, 1978, 1982, 1990 and 2010, the highest number of times a country has come first, and the only Asian team to have won the prestigious Champions Trophy with three championships: 1978, 1980 and 1994. Pakistan have won a total of 29 official international titles to professional and grassroots level selections, with three gold medals in the Olympic Games field hockey tournaments in Rome 1960, Mexico City 1968 and Los Angeles 1984. However, Pakistan could not qualify for Olympics since 2012.\n\nField hockey being the national sport of the country,[4][5] Pakistan national team has been ranked as the #1 team in the world from 2000 till 2001 by FIH, and former captain Sohail Abbas holds the world record for the most international goals scored by a player[6] in the history of international field hockey, with a tally of 348 goals.[7] Waseem Ahmad holds the record for Pakistan appearances, having played 410 times between 1996 and 2012.[8]\n\nPakistan is known for having fierce rivalry with India, having a record of playing each other in South Asian Games and Asian Games finals. They have competed against one another in twenty major tournaments finals so far, out of which Pakistan has won thirteen titles in total. Pakistan have a record of winning the first three championships of Hockey Asia Cup in 1982, 1985 and 1989 against India in row. Pakistan's home ground is National Hockey Stadium, in Lahore, and the current team head coach and manager is Khawaja Muhammad Junaid.[9]\n\n",
 'Document: List of Sri Lanka Test cricket records\n\n\n\nTest cricket is the oldest form of cricket played at international level.[1] A Test match takes place over a period of five days, and is played by teams representing Full Member nations of the International Cricket Council (ICC).[2][3] Sri Lanka obtained Full Member status of the ICC in 1981, becoming the eighth nation eligible to play Test cricket.[4] The Sri Lanka national cricket team played their first Test match on 17 February 1982, against England, and recorded their first victory on 6 September 1985, in a match against India.[5] Since then, they have played nearly 200 matches, against every other Test-playing nation.[6] Sri Lanka holds the world record for the highest team score, which was established against India in 1997.[7] The highest partnership in Test cricket was also established by two Sri Lankan batsmen; Mahela Jayawardene and Kumar Sangakkara.[8] Sri Lankan players also hold the highest partnership scores for the second and third wickets.[9]\n\nTop order batsman and former captain Kumar Sangakkara holds several Sri Lankan batting records as he has scored the most runs for Sri Lanka in Test cricket. He is also the record holder for the highest number of centuries as well as the highest number of half-centuries. The 374 made by Mahela Jayawardene  against South Africa in 2006 is the highest individual score by a Sri Lankan cricketer, surpassing the previous best of 340 by Sanath Jayasuriya, which was established in 1997.[10] It is also the fourth-highest individual score in Test cricket. Jayawardene, Jayasuriya and Kumar Sangakkara [319] are the only Sri Lankan players who have scored triple centuries.[11]\n\nMuttiah Muralitharan, who was hailed by the Wisden Cricketers\' Almanack in 2002 as the "best bowler ever" in Test cricket, dominates the bowling records for Sri Lanka.[12] He is the world record holder for the highest number of wickets, the most number of five wickets per innings, as well as the most number of ten wickets per match.[13] Muralitharan also holds the records for the best bowling average, best figures in an innings, best figures in a match, and best figures in a series. He missed an opportunity to capture all ten wickets in an innings in 2002 against Zimbabwe, when Chaminda Vaas took the last wicket after Muralitharan had taken the previous nine.[14]\nThe Sri Lankan team won an ODI series against Australia in Australia in 2010. However, they are yet to register a Test match win and an ODI series win against India in India, as of 2017.\n\nSri Lanka witnessed a unique record of having most Test wickets by a both right arm and left bowler, Muralitharan with 800 wickets and Rangana Herath with 433 wickets.\n\n',
 'Document: All-Ireland Senior Hurling Championship/Scoring records\n\n(1)  The 80 minute final. This 80 minute final took place in 1971 between Tipperary and Kilkenny. Eddie Keher scored 2-11 which makes a total of 17 points. However 2-08 of this was scored from frees. (2) The record for all 70 minute finals. This record was made in 1989. This hurling final was between Tipperary and Antrim. Nicholas English scored 2-12 points which equals  a total of 18 points. However 0-9 of this was achieved from frees. (3) The 60 minute final: The overall scoring record is held by Michael Gah Ahern the greatest sharpshooter of the 1920s and early 1930s. He scored 5-04. What makes this scoring  record remarkable is that he scored ALL of his scores from his hands. \n\nNicky Rackard of Wexford got the highest confirmed total in a major championship game. In Wexford\'s 12−17 to 2–3 defeat of Antrim in the 1954 All-Ireland semi-final he scored a remarkable 7 goals and 7 points. His tally of 6 goals and 4 points against Dublin is also a scoring record. Rackard also scored 5 goals and 4 points against Galway in the 1956 All-Ireland semi-final.\n\nPrior to the 1930s scoring records for championship games were rarely kept. A number of players have been credited with enormous tallies. Andy \'Dooric\' Buckley scored at least 6 goals when Cork beat Kilkenny by 8–9 to 0–8 in the 1903 All-Ireland \'home\' final. Other newspaper reports credit him with 7 goals and 4 points.\n\nP. J. Riordan is alleged[by whom?] to have scored all but 1 point of Tipperary\'s total when they beat Kilkenny by 6–8 to 0−1 in the 1895 All-Ireland final.\n\nJimmy Kelly of Kilkenny is said[by whom?] to have scored 7 goals in 30 minutes against Cork in the replay of the 1905 final.\n\nIn 1990 the rule prohibiting a hand-passed score was introduced. This had a large bearing on the scoring records above with less goals being scored in open play following its introduction. In the 1990 Congress the score rule was changed to read:\n"A Goal is scored when the ball is played by either team between the goalposts and under the crossbar. A point is scored when the ball is played by either team between the uprights and over the crossbar. The ball shall not be thrown or carried over the goal-line by an attacking player.\nIn Hurling a score may not be made by an attacking player in possession fisting or handpassing the ball but a score may be made by a player stricking the ball in flight with the fist or open hand.\'\'"\n\n',
 "Document: Israel/Economy\n\n### Science and technology ###\nIsrael's development of cutting-edge technologies in software, communications and the life sciences have evoked comparisons with Silicon Valley.[544][545] Israel ranks 5th in the 2019 Bloomberg Innovation Index,[68] and is 1st in the world in expenditure on research and development as a percentage of GDP.[65] Israel boasts 140 scientists, technicians, and engineers per 10,000 employees, the highest number in the world (in comparison, the same is 85 for the U.S.).[546][547][548] Israel has produced six Nobel Prize-winning scientists since 2004[549] and has been frequently ranked as one of the countries with the highest ratios of scientific papers per capita in the world.[550][551][552] Israel has led the world in stem-cell research papers per capita since 2000.[553] Israeli universities are ranked among the top 50 world universities in computer science (Technion and Tel Aviv University), mathematics (Hebrew University of Jerusalem) and chemistry (Weizmann Institute of Science).[391]\n\nIn 2012, Israel was ranked ninth in the world by the Futron's Space Competitiveness Index.[554] The Israel Space Agency coordinates all Israeli space research programs with scientific and commercial goals, and have indigenously designed and built at least 13 commercial, research and spy satellites.[555] Some of Israel's satellites are ranked among the world's most advanced space systems.[556] Shavit is a space launch vehicle produced by Israel to launch small satellites into low Earth orbit.[557] It was first launched in 1988, making Israel the eighth nation to have a space launch capability. In 2003, Ilan Ramon became Israel's first astronaut, serving as payload specialist of STS-107, the fatal mission of the Space Shuttle Columbia.[558]\n\nThe ongoing shortage of water in the country has spurred innovation in water conservation techniques, and a substantial agricultural modernization, drip irrigation, was invented in Israel. Israel is also at the technological forefront of desalination and water recycling. The Sorek desalination plant is the largest seawater reverse osmosis (SWRO) desalination facility in the world.[559] By 2014, Israel's desalination programs provided roughly 35% of Israel's drinking water and it is expected to supply 40% by 2015 and 70% by 2050.[560] As of 2015[update], more than 50 percent of the water for Israeli households, agriculture and industry is artificially produced.[561] The country hosts an annual Water Technology and Environmental Control Exhibition & Conference (WATEC) that attracts thousands of people from across the world.[562][563] In 2011, Israel's water technology industry was worth around $2 billion a year with annual exports of products and services in the tens of millions of dollars. As a result of innovations in reverse osmosis technology, Israel is set to become a net exporter of water in the coming years.[564]\n\nIsrael has embraced solar energy; its engineers are on the cutting edge of solar energy technology[566] and its solar companies work on projects around the world.[567][568] Over 90% of Israeli homes use solar energy for hot water, the highest per capita in the world.[310][569] According to government figures, the country saves 8% of its electricity consumption per year because of its solar energy use in heating.[570] The high annual incident solar irradiance at its geographic latitude creates ideal conditions for what is an internationally renowned solar research and development industry in the Negev Desert.[566][567][568] Israel had a modern electric car infrastructure involving a countrywide network of charging stations to facilitate the charging and exchange of car batteries. It was thought that this would have lowered Israel's oil dependency and lowered the fuel costs of hundreds of Israel's motorists that use cars powered only by electric batteries.[571][572][573] The Israeli model was being studied by several countries and being implemented in Denmark and Australia.[574] However, Israel's trailblazing electric car company Better Place shut down in 2013.[575]\n\n",

In [5]:
# retrive docs from the document embeddings
def retrieve_documents(query):
    max_length = 1024
    
    #query prefix
    task_name_to_instruct = {"example": "Given a question, retrieve passages that answer the question",}
    query_prefix = "Instruct: "+task_name_to_instruct["example"]+"\nQuery: "
    
    query_embedding = model.encode([query],instruction=query_prefix, max_length=max_length).to(device1)
    
    similarities = torch.nn.functional.cosine_similarity(query_embedding, evidence_embeddings)

    top_results = similarities.argsort(descending=True)[:10].cpu().detach().numpy()
    res=[evidence_df.loc[idx, 'text'] for idx in top_results if idx < len(evidence_df)]
        
    return res

In [6]:
def summarize(query, docs):
    prompt = """
    In a Retrieval Augmentation Generation system, documents close to the query vector are as follows:
    ---------------------
    {0}
    ---------------------
    Identify entities and contexts in a query, and use them to extract and summarize only relevant content from documents.
    Query: {1}
    Answer:
    """.format('\n'.join(docs), query)
    input_ids = tokenizer_gen.apply_chat_template([{"role":'user', "content":prompt}], return_tensors='pt').to(device2)

    attention_mask = (input_ids != tokenizer_gen.pad_token_id).long().to(device2)

    out = model_gen.generate(input_ids, attention_mask=attention_mask, pad_token_id=tokenizer_gen.pad_token_id, max_new_tokens = 512)
    res = tokenizer_gen.decode(out[0]).split('<|end_header_id|>')[-1] 
    return [re.sub('\n|<\|eot_id\|>', '', res)]

In [43]:
def HyDE(query, docs):
    prompt = """
    In a Retrieval Augmentation Generation system, documents close to the query vector are as follows:
    ---------------------
    {0}
    ---------------------
    Identify entities and contexts in a query, and use them to extract and summarize only relevant content from documents.
    Query: {1}
    Answer:
    """.format('\n'.join(docs), query)
    input_ids = tokenizer_gen.apply_chat_template([{"role":'user', "content":prompt}], return_tensors='pt').to(device2)

    attention_mask = (input_ids != tokenizer_gen.pad_token_id).long().to(device2)

    out = model_gen.generate(input_ids, attention_mask=attention_mask, pad_token_id=tokenizer_gen.pad_token_id, max_new_tokens = 512)
    res = tokenizer_gen.decode(out[0]).split('<|end_header_id|>')[-1] 
    return [re.sub('\n|<\|eot_id\|>', '', res)]

In [7]:
def answer(query, context):
    prompt = """
    Context information is below.
    ---------------------
    {0}
    ---------------------
    Given the context information and not prior knowledge, answer the query.
    Query: {1}
    Answer:
    """.format('\n'.join(context), query)
    input_ids = tokenizer_gen.apply_chat_template([{"role":'user', "content":prompt}], return_tensors='pt').to(device1)

    attention_mask = (input_ids != tokenizer_gen.pad_token_id).long().to(device1)

    out = model_gen.generate(input_ids, attention_mask=attention_mask, pad_token_id=tokenizer_gen.pad_token_id, max_new_tokens = 512)
    res = tokenizer_gen.decode(out[0]).split('<|end_header_id|>')[-1] 
    return [re.sub('\n|<\|eot_id\|>', '', res)]

In [ ]:
tokenizer = AutoTokenizer.from_pretrained('BAAI/bge-reranker-v2-m3')
model = AutoModelForSequenceClassification.from_pretrained('BAAI/bge-reranker-v2-m3')
model.eval()

with torch.no_grad():
    inputs = tokenizer(pairs, padding=True, truncation=True, return_tensors='pt', max_length=512)
    scores = model(**inputs, return_dict=True).logits.view(-1, ).float()
    scores = exp_normalize(scores.numpy()) 
    
print(np.round(scores * 100, 2))

In [77]:
from tqdm import tqdm
from evaluation import evaluate

stop_iteration = 20

scores_list=[]
for idx, row in tqdm(qa_df.iterrows(), total=min([stop_iteration, len(qa_df)])):
    if idx == stop_iteration: break
    query = row['question']
    # retrieved_docs = retrieve_documents(query)
    bm25_docs = bm25_retrieve(query)
    # summary=summarize(query,retrieved_docs)
    # print(summary)
    ans=answer(query,bm25_docs)
    print('Final ans:', ans)
    scores=evaluate(ans, [row.to_dict()])
    scores_list.append(scores)
    scores_df=pd.DataFrame(scores_list)
    print(scores)
        
scores_df=pd.DataFrame(scores_list)
scores_df.mean()

  0%|          | 0/20 [00:00<?, ?it/s]

[BM25 Retriever]
Final ans: ['According to the given context information, the player with the highest goals in world football is Ali Daei of Iran, who has scored 109 goals in international football.']
According to the given context information, the player with the highest goals in world football is Ali Daei of Iran, who has scored 109 goals in international football.
Who has the highest goals in world football?
["Who has the highest goals in men's world international football?", "Who has the highest goals all-time in men's football?", "Who has the highest goals in women's world international football?"]
[['Daei', 'Ali Daei'], ['Bican', 'Josef Bican'], ['Sinclair', 'Christine Sinclair']]

  5%|▌         | 1/20 [00:04<01:20,  4.26s/it]

follow question : Who has the highest goals in men's world international football?
short answer : ['Daei', 'Ali Daei']
{'score': 0.8047415018081665, 'start': 99, 'end': 107, 'answer': 'Ali Daei'}
follow question : Who has the highest goals all-time in men's football?
short answer : ['Bican', 'Josef Bican']
{'score': 0.007298500742763281, 'start': 99, 'end': 107, 'answer': 'Ali Daei'}
follow question : Who has the highest goals in women's world international football?
short answer : ['Sinclair', 'Christine Sinclair']
{'score': 0.010482086800038815, 'start': 99, 'end': 107, 'answer': 'Ali Daei'}
{'rougeLsum': 38.235294117647065, 'length': 28.0, 'str_em': 33.33333333333333, 'Disambig-F1': 33.33333333333333}
[BM25 Retriever]
Final ans: ['The query is about the song "The Sound of Silence" and its original artist. However, the provided context information does not contain any information about the song or its artist.But, according to general knowledge, the song "The Sound of Silence" is by the American rock band The Beatles was not the original artist. The song was written by Paul Simon of the American rock band The Simon & Garfunkel.']
The query is about the song "The Sound of Silence" and its original artist. However, the provided context information does not contain any information about the song or its artist.But, according to general knowledge, the song "The Sound of Silence" is by the American rock band The Beatles was not the original artist. The song was written by Paul Simon of the American rock band The Simon & Garfunkel.
Who is the original artist of sound of silence?
['Who is the original artist of sound of silence, the song, released in 1964?', 'Who is the original artist of sound of silence, the album?', 'Who is the original artist of sound of silence, the song, released in 2016?']
[['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon'], ['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon'], ['Dami Im']]

 10%|█         | 2/20 [00:10<01:38,  5.46s/it]

follow question : Who is the original artist of sound of silence, the song, released in 1964?
short answer : ['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon']
{'score': 0.03602112829685211, 'start': 278, 'end': 289, 'answer': 'The Beatles'}
follow question : Who is the original artist of sound of silence, the album?
short answer : ['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon']
{'score': 0.04939933866262436, 'start': 278, 'end': 289, 'answer': 'The Beatles'}
follow question : Who is the original artist of sound of silence, the song, released in 2016?
short answer : ['Dami Im']
{'score': 0.050298940390348434, 'start': 278, 'end': 289, 'answer': 'The Beatles'}
{'rougeLsum': 30.15873015873015, 'length': 69.0, 'str_em': 66.66666666666666, 'Disambig-F1': 0.0}
[BM25 Retriever]
Final ans: ['There is no information about the first Apple iPhone in the provided context. The context information seems to be a collection of various documents on different topics, including the Jetsons movie, the history of mobile phones, the New York Knicks, American Idol, and the Sagrada Família. The first Apple iPhone was actually released in 2007, but this information is not present in the provided context.']
There is no information about the first Apple iPhone in the provided context. The context information seems to be a collection of various documents on different topics, including the Jetsons movie, the history of mobile phones, the New York Knicks, American Idol, and the Sagrada Família. The first Apple iPhone was actually released in 2007, but this information is not present in the provided context.
When was the first apple i phone made?
['When was the first apple i phone released?', 'When was the first apple i phone for beta testing made?', 'When was the first apple i phone 1 made?', 'When was the first apple i phone beta made?']
[['June 29, 2007'], ['2004'], ['June 29, 2007.'], ['2004.']]

 15%|█▌        | 3/20 [00:16<01:38,  5.77s/it]

follow question : When was the first apple i phone released?
short answer : ['June 29, 2007']
{'score': 0.9777573347091675, 'start': 337, 'end': 341, 'answer': '2007'}
follow question : When was the first apple i phone for beta testing made?
short answer : ['2004']
{'score': 0.017013685777783394, 'start': 337, 'end': 341, 'answer': '2007'}
follow question : When was the first apple i phone 1 made?
short answer : ['June 29, 2007.']
{'score': 0.9676275253295898, 'start': 337, 'end': 341, 'answer': '2007'}
follow question : When was the first apple i phone beta made?
short answer : ['2004.']
{'score': 0.0013752414379268885, 'start': 337, 'end': 341, 'answer': '2007'}
{'rougeLsum': 34.84848484848485, 'length': 65.0, 'str_em': 0.0, 'Disambig-F1': 25.0}
[BM25 Retriever]
Final ans: ['There is no information in the provided context about the Weasley brothers in Harry Potter. The context information seems to be a collection of articles and documents about various topics, including music and film.']
There is no information in the provided context about the Weasley brothers in Harry Potter. The context information seems to be a collection of articles and documents about various topics, including music and film.
Who played the weasley brothers in harry potter?
['Who played  Bill weasley in Harry Potter and the Prisoner of Azkaban?', 'Who played percy weasley in harry potter?', 'Who played fred weasley in harry potter?', 'Who played ron weasley in harry potter?', 'Who played george weasley in harry potter?', 'Who played  Bill weasley in harry potter (2001-2011)?']
[['Richard Fish'], ['Chris Rankin'], ['James Phelps'], ['Rupert Grint'], ['Oliver Phelps'], ['Domhnall Gleeson']]

 20%|██        | 4/20 [00:20<01:22,  5.14s/it]

follow question : Who played  Bill weasley in Harry Potter and the Prisoner of Azkaban?
short answer : ['Richard Fish']
{'score': 1.0699112863221671e-05, 'start': 58, 'end': 74, 'answer': 'Weasley brothers'}
follow question : Who played percy weasley in harry potter?
short answer : ['Chris Rankin']
{'score': 0.003175509860739112, 'start': 58, 'end': 74, 'answer': 'Weasley brothers'}
follow question : Who played fred weasley in harry potter?
short answer : ['James Phelps']
{'score': 0.0032618294935673475, 'start': 58, 'end': 74, 'answer': 'Weasley brothers'}
follow question : Who played ron weasley in harry potter?
short answer : ['Rupert Grint']
{'score': 0.00132146873511374, 'start': 58, 'end': 74, 'answer': 'Weasley brothers'}
follow question : Who played george weasley in harry potter?
short answer : ['Oliver Phelps']
{'score': 0.0007963679381646216, 'start': 58, 'end': 74, 'answer': 'Weasley brothers'}
follow question : Who played  Bill weasley in harry potter (2001-2011)?
short answer : ['Domhnall Gleeson']
{'score': 5.09671081090346e-05, 'start': 58, 'end': 74, 'answer': 'Weasley brothers'}
{'rougeLsum': 21.84873949579832, 'length': 34.0, 'str_em': 0.0, 'Disambig-F1': 0.0}
[BM25 Retriever]
Final ans: ['38 parks.']
38 parks.
How many state parks are there in virginia?
['How many state parks are there in virginia in 1936?', 'How many state parks are there in virginia in 2016?', 'How many state parks were there when the state park system formed in Virginia?', 'How many state parks were there in Virginia as of 2016?']
[['six'], ['38'], ['6'], ['38']]

 25%|██▌       | 5/20 [00:22<00:59,  3.99s/it]

follow question : How many state parks are there in virginia in 1936?
short answer : ['six']
{'score': 0.005780069623142481, 'start': 0, 'end': 2, 'answer': '38'}
follow question : How many state parks are there in virginia in 2016?
short answer : ['38']
{'score': 0.011928805150091648, 'start': 0, 'end': 2, 'answer': '38'}
follow question : How many state parks were there when the state park system formed in Virginia?
short answer : ['6']
{'score': 0.3328418433666229, 'start': 0, 'end': 2, 'answer': '38'}
follow question : How many state parks were there in Virginia as of 2016?
short answer : ['38']
{'score': 0.04651332274079323, 'start': 0, 'end': 2, 'answer': '38'}
{'rougeLsum': 11.11111111111111, 'length': 2.0, 'str_em': 50.0, 'Disambig-F1': 50.0}
[BM25 Retriever]
Final ans: ['Real Madrid won the 2018 UEFA Champions League Final, defeating Liverpool 3-1.']
Real Madrid won the 2018 UEFA Champions League Final, defeating Liverpool 3-1.
Who performed at the champions league final 2018?
['Who are the teams that performed in competition at the champions league final 2018?', 'Who performed best at the champions league final 2018, winning man of the match?', 'Who performed at the opening ceremony of the champions league final 2018?', 'Who performed the anthem at the champions league final 2018?']
[['Real Madrid and Liverpool', 'Liverpool', 'Real Madrid'], ['Gareth Bale', 'Bale'], ['Dua Lipa', 'Sean Paul', 'Dua Lipa and Sean Paul'], ['2Cellos', 'Luka Šulić and Stjepan Hauser', 'Luka Šulić', '2CΞLLOS', 'Stjepan Hauser']]

 30%|███       | 6/20 [00:25<00:50,  3.64s/it]

follow question : Who are the teams that performed in competition at the champions league final 2018?
short answer : ['Real Madrid and Liverpool', 'Liverpool', 'Real Madrid']
{'score': 0.6557438969612122, 'start': 0, 'end': 11, 'answer': 'Real Madrid'}
follow question : Who performed best at the champions league final 2018, winning man of the match?
short answer : ['Gareth Bale', 'Bale']
{'score': 0.8715537786483765, 'start': 0, 'end': 11, 'answer': 'Real Madrid'}
follow question : Who performed at the opening ceremony of the champions league final 2018?
short answer : ['Dua Lipa', 'Sean Paul', 'Dua Lipa and Sean Paul']
{'score': 0.4003148078918457, 'start': 0, 'end': 11, 'answer': 'Real Madrid'}
follow question : Who performed the anthem at the champions league final 2018?
short answer : ['2Cellos', 'Luka Šulić and Stjepan Hauser', 'Luka Šulić', '2CΞLLOS', 'Stjepan Hauser']
{'score': 0.5518925786018372, 'start': 0, 'end': 11, 'answer': 'Real Madrid'}
{'rougeLsum': 27.77777777777778, 'length': 12.0, 'str_em': 25.0, 'Disambig-F1': 25.0}
[BM25 Retriever]
Final ans: ['The answer to the question is not explicitly stated in the provided context information, but based on the information about the movie "Thelma and Louise", the man who was killed is Laura\'s father, and it was Joe\'s father who ran him down.']
The answer to the question is not explicitly stated in the provided context information, but based on the information about the movie "Thelma and Louise", the man who was killed is Laura's father, and it was Joe's father who ran him down.
Who killed the man in thelma and louise?
['Which character killed the man in thelma and louise?', 'Which actor killed the man in thelma and louise?', 'Who is the character that kills Harlan in the film Thelma and Louise?', 'Who is the actor of the character that killed a man in the film Thelma and Louise?']
[['Louise Elizabeth Sawyer', 'Louise'], ['Susan Sarandon', 'Susan Abigail Sarandon'], ['Louise Elizabeth Sawyer', 'Louise'], ['Susan Sarandon']]

 35%|███▌      | 7/20 [00:30<00:53,  4.12s/it]

follow question : Which character killed the man in thelma and louise?
short answer : ['Louise Elizabeth Sawyer', 'Louise']
{'score': 0.45146334171295166, 'start': 181, 'end': 195, 'answer': "Laura's father"}
follow question : Which actor killed the man in thelma and louise?
short answer : ['Susan Sarandon', 'Susan Abigail Sarandon']
{'score': 0.3575655519962311, 'start': 208, 'end': 220, 'answer': "Joe's father"}
follow question : Who is the character that kills Harlan in the film Thelma and Louise?
short answer : ['Louise Elizabeth Sawyer', 'Louise']
{'score': 0.4742181599140167, 'start': 181, 'end': 195, 'answer': "Laura's father"}
follow question : Who is the actor of the character that killed a man in the film Thelma and Louise?
short answer : ['Susan Sarandon']
{'score': 0.3042433559894562, 'start': 208, 'end': 220, 'answer': "Joe's father"}
{'rougeLsum': 17.142857142857142, 'length': 42.0, 'str_em': 50.0, 'Disambig-F1': 0.0}
[BM25 Retriever]
Final ans: ["I'm not able to identify who plays Charlie on It's Always Sunny in Philadelphia."]
I'm not able to identify who plays Charlie on It's Always Sunny in Philadelphia.
Who plays charlie on it's always sunny?
["Who does Charlie Day play on It's Always Sunny in Philadelphia?", "Who plays Charlie Kelly on It's Always Sunny in Philadelphia?"]
[['Charlie Kelly'], ['Charlie Day']]

 40%|████      | 8/20 [00:33<00:45,  3.79s/it]

follow question : Who does Charlie Day play on It's Always Sunny in Philadelphia?
short answer : ['Charlie Kelly']
{'score': 0.00033270189305767417, 'start': 0, 'end': 42, 'answer': "I'm not able to identify who plays Charlie"}
follow question : Who plays Charlie Kelly on It's Always Sunny in Philadelphia?
short answer : ['Charlie Day']
{'score': 0.00013266415044199675, 'start': 0, 'end': 42, 'answer': "I'm not able to identify who plays Charlie"}
{'rougeLsum': 33.33333333333333, 'length': 14.0, 'str_em': 0.0, 'Disambig-F1': 20.0}
[BM25 Retriever]
Final ans: ['The answer to this question is not directly provided in the given context information. However, based on the information about the Boston Celtics/Rivalries document, it can be inferred that the Lakers have won the NBA Finals 16 times, but the exact number of times they have won the finals is not specified.']
The answer to this question is not directly provided in the given context information. However, based on the information about the Boston Celtics/Rivalries document, it can be inferred that the Lakers have won the NBA Finals 16 times, but the exact number of times they have won the finals is not specified.
How many times have the lakers won the finals?
['As of 2017, how many times have the lakers won the finals?', 'As of 2016, how many times have the Lakers won the finals?', 'As of 2015, how many times have the Lakers won the finals?']
[['16'], ['16'], ['16']]

 45%|████▌     | 9/20 [00:38<00:45,  4.12s/it]

follow question : As of 2017, how many times have the lakers won the finals?
short answer : ['16']
{'score': 0.162079319357872, 'start': 225, 'end': 227, 'answer': '16'}
follow question : As of 2016, how many times have the Lakers won the finals?
short answer : ['16']
{'score': 0.4103235900402069, 'start': 225, 'end': 227, 'answer': '16'}
follow question : As of 2015, how many times have the Lakers won the finals?
short answer : ['16']
{'score': 0.017162088304758072, 'start': 225, 'end': 227, 'answer': '16'}
{'rougeLsum': 32.98969072164948, 'length': 52.0, 'str_em': 100.0, 'Disambig-F1': 100.0}
[BM25 Retriever]
Final ans: ['The query is not related to the provided context information. The context information seems to be a collection of various documents on different topics such as education, history, politics, and more.However, I can try to provide a general answer based on my knowledge. India is a federal republic with 28 states and 8 union territories. The governance of these states is divided between the central government and the state governments.If you are referring to the number of states that are under the control of the Indian National Congress, a political party, I can provide a general answer.As of my last update in 2023, the Indian National Congress is in power in several states, but the exact number of states can vary depending on the current government and elections.However, I can suggest some states where the Indian National Congress has been in power in the past or has a significant presence:1. Punjab2. Rajasthan3. Chhattisgarh4. Madhya Pradesh5. Maharashtra6. Karnataka7. Telangana8. Andhra Pradesh9. Tamil Nadu10. KeralaPlease note that this information may not be up-to-date or accurate, and I recommend verifying it with a reliable source for the most recent information.']
The query is not related to the provided context information. The context information seems to be a collection of various documents on different topics such as education, history, politics, and more.However, I can try to provide a general answer based on my knowledge. India is a federal republic with 28 states and 8 union territories. The governance of these states is divided between the central government and the state governments.If you are referring to the number of states that are under the control of the Indian National Congress, a political party, I can provide a general answer.As of my last update in 2023, the Indian National Congress is in power in several states, but the exact number of states can vary depending on the current government and elections.However, I can suggest some states where the Indian National Congress has been in power in the past or has a significant presence:1. Punjab2. Rajasthan3. Chhattisgarh4. Madhya Pradesh5. Maharashtra6. Karnataka7. Telangana8. Andhra Pradesh9. Tamil Nadu10. KeralaPlease note that this information may not be up-to-date or accurate, and I recommend verifying it with a reliable source for the most recent information.
How many states in india are under congress?
['How many states plus territories in india are under congress?', 'How many states alone in india are under congress?']
[['7'], ['5']]

 50%|█████     | 10/20 [00:53<01:13,  7.35s/it]

follow question : How many states plus territories in india are under congress?
short answer : ['7']
{'score': 0.202698215842247, 'start': 302, 'end': 304, 'answer': '28'}
follow question : How many states alone in india are under congress?
short answer : ['5']
{'score': 0.004908116068691015, 'start': 302, 'end': 304, 'answer': '28'}
{'rougeLsum': 22.745098039215684, 'length': 187.0, 'str_em': 100.0, 'Disambig-F1': 0.0}
[BM25 Retriever]
Final ans: ['Fruma-Sarah is the late wife of Lazar Wolf, a wealthy butcher, in the musical Fiddler on the Roof. She is mentioned in a dream sequence by Tevye, where he claims she warned him that Tzeitel should not marry Lazar, but rather Motel Kamzoil.']
Fruma-Sarah is the late wife of Lazar Wolf, a wealthy butcher, in the musical Fiddler on the Roof. She is mentioned in a dream sequence by Tevye, where he claims she warned him that Tzeitel should not marry Lazar, but rather Motel Kamzoil.
Who is fruma sarah in fiddler on the roof?
['Who played fruma sarah in the 1971 film, Fiddler on the Roof?', 'Who played Fruma Sarah in the original 1964 Broadway cast of Fiddler on the Roof?', 'Who is the character of Fruma Sarah in Fiddler on the Roof?', 'Who played Fruma Sarah in the 2015-2016 Broadway Revival of Fiddler on the Roof?']
[['Ruth Madoc'], ['Carol Sawyer Yussel'], ['a ghostly depiction of the late wife of Lazar Wolf'], ['Jessica Vosk']]

 55%|█████▌    | 11/20 [01:00<01:04,  7.19s/it]

follow question : Who played fruma sarah in the 1971 film, Fiddler on the Roof?
short answer : ['Ruth Madoc']
{'score': 0.009049774147570133, 'start': 139, 'end': 144, 'answer': 'Tevye'}
follow question : Who played Fruma Sarah in the original 1964 Broadway cast of Fiddler on the Roof?
short answer : ['Carol Sawyer Yussel']
{'score': 0.003931158222258091, 'start': 139, 'end': 144, 'answer': 'Tevye'}
follow question : Who is the character of Fruma Sarah in Fiddler on the Roof?
short answer : ['a ghostly depiction of the late wife of Lazar Wolf']
{'score': 0.8576837778091431, 'start': 32, 'end': 42, 'answer': 'Lazar Wolf'}
follow question : Who played Fruma Sarah in the 2015-2016 Broadway Revival of Fiddler on the Roof?
short answer : ['Jessica Vosk']
{'score': 0.010593813844025135, 'start': 139, 'end': 144, 'answer': 'Tevye'}
{'rougeLsum': 24.657534246575345, 'length': 43.0, 'str_em': 0.0, 'Disambig-F1': 10.0}
[BM25 Retriever]
Final ans: ['There is no information in the provided context about the MLB All-Star Game in Toronto. The context only mentions Darin Erstad, an MLB all-star and World Series Champion, but does not specify which team he played for or where he played.']
There is no information in the provided context about the MLB All-Star Game in Toronto. The context only mentions Darin Erstad, an MLB all-star and World Series Champion, but does not specify which team he played for or where he played.
When did toronto host the mlb all-star game?
['What date did toronto host the mlb all-star game?', 'Which all-star game did toronto host?']
[['July 9, 1991'], ['1991 Major League Baseball All-Star Game', 'the 62nd playing of the midsummer classic']]

 60%|██████    | 12/20 [01:04<00:50,  6.33s/it]

follow question : What date did toronto host the mlb all-star game?
short answer : ['July 9, 1991']
{'score': 0.0004311902157496661, 'start': 0, 'end': 23, 'answer': 'There is no information'}
follow question : Which all-star game did toronto host?
short answer : ['1991 Major League Baseball All-Star Game', 'the 62nd playing of the midsummer classic']
{'score': 0.6025953888893127, 'start': 58, 'end': 75, 'answer': 'MLB All-Star Game'}
{'rougeLsum': 20.754716981132077, 'length': 41.0, 'str_em': 0.0, 'Disambig-F1': 22.22222222222222}
[BM25 Retriever]
Final ans: ['A car with a good alarm system, a dash cam, and a tracking device would be a good choice to catch a thief. Additionally, a car with a unique or distinctive design, such as a sports car or a vintage car, might be more likely to be targeted by thieves, but could also be more easily identifiable if caught on camera or tracked with a GPS device.']
A car with a good alarm system, a dash cam, and a tracking device would be a good choice to catch a thief. Additionally, a car with a unique or distinctive design, such as a sports car or a vintage car, might be more likely to be targeted by thieves, but could also be more easily identifiable if caught on camera or tracked with a GPS device.
What kind of car in to catch a thief?
['What kind of car in to catch a thief in terms of model?', 'What kind of car in to catch a thief in terms of automobile make?']
[['Sunbeam Alpine', '1953 Sunbeam Alpine Mk I'], ['Rootes Group']]

 65%|██████▌   | 13/20 [01:10<00:44,  6.31s/it]

follow question : What kind of car in to catch a thief in terms of model?
short answer : ['Sunbeam Alpine', '1953 Sunbeam Alpine Mk I']
{'score': 0.06101648882031441, 'start': 174, 'end': 201, 'answer': 'sports car or a vintage car'}
follow question : What kind of car in to catch a thief in terms of automobile make?
short answer : ['Rootes Group']
{'score': 0.0687730461359024, 'start': 2, 'end': 65, 'answer': 'car with a good alarm system, a dash cam, and a tracking device'}
{'rougeLsum': 15.384615384615383, 'length': 67.0, 'str_em': 0.0, 'Disambig-F1': 0.0}
[BM25 Retriever]
Final ans: ["The last season of Jersey Shore aired in 2012. The show's sixth season, which consisted of 38 episodes, premiered on October 4, 2012, and concluded on December 22, 2012."]
The last season of Jersey Shore aired in 2012. The show's sixth season, which consisted of 38 episodes, premiered on October 4, 2012, and concluded on December 22, 2012.
When did the last season of jersey shore air?
['When did season 4 of jersey shore first air?', 'When did season 4 of jersey shore last air?', 'When did season 5 of jersey shore first air?', 'When did season 5 of jersey shore last air?', 'When did season 6 of jersey shore first air?', 'When did season 6 of jersey shore last air?']
[['August 4, 2011'], ['October 20, 2011'], ['January 5, 2012'], ['March 15, 2012'], ['October 4, 2012'], ['December 20, 2012']]

 70%|███████   | 14/20 [01:15<00:34,  5.79s/it]

follow question : When did season 4 of jersey shore first air?
short answer : ['August 4, 2011']
{'score': 0.376492440700531, 'start': 128, 'end': 132, 'answer': '2012'}
follow question : When did season 4 of jersey shore last air?
short answer : ['October 20, 2011']
{'score': 0.8071120977401733, 'start': 41, 'end': 45, 'answer': '2012'}
follow question : When did season 5 of jersey shore first air?
short answer : ['January 5, 2012']
{'score': 0.26440468430519104, 'start': 117, 'end': 132, 'answer': 'October 4, 2012'}
follow question : When did season 5 of jersey shore last air?
short answer : ['March 15, 2012']
{'score': 0.7399580478668213, 'start': 41, 'end': 45, 'answer': '2012'}
follow question : When did season 6 of jersey shore first air?
short answer : ['October 4, 2012']
{'score': 0.7867692112922668, 'start': 117, 'end': 132, 'answer': 'October 4, 2012'}
follow question : When did season 6 of jersey shore last air?
short answer : ['December 20, 2012']
{'score': 0.6838536858558655, 'start': 41, 'end': 45, 'answer': '2012'}
{'rougeLsum': 29.885057471264364, 'length': 29.0, 'str_em': 16.666666666666664, 'Disambig-F1': 38.888888888888886}
[BM25 Retriever]
Final ans: ["Season 8 of Grey's Anatomy."]
Season 8 of Grey's Anatomy.
What season of greys anatomy was the plane crash?
["What season of Grey's Anatomy was the plane crash involving six doctors?", "What season of Grey's Anatomy was the plane crash in Seattle that brought memories of a previous plane crash?", "What season of Grey's Anatomy was the plane crash that claimed the life of Lexie Grey?", "What season of Grey's Anatomy was the plane crash in downtown Seattle?"]
[['season 8'], ['season 11'], ['8'], ['11']]

 75%|███████▌  | 15/20 [01:17<00:23,  4.77s/it]

follow question : What season of Grey's Anatomy was the plane crash involving six doctors?
short answer : ['season 8']
{'score': 0.5060269832611084, 'start': 0, 'end': 8, 'answer': 'Season 8'}
follow question : What season of Grey's Anatomy was the plane crash in Seattle that brought memories of a previous plane crash?
short answer : ['season 11']
{'score': 0.6679225564002991, 'start': 0, 'end': 8, 'answer': 'Season 8'}
follow question : What season of Grey's Anatomy was the plane crash that claimed the life of Lexie Grey?
short answer : ['8']
{'score': 0.5756567120552063, 'start': 0, 'end': 8, 'answer': 'Season 8'}
follow question : What season of Grey's Anatomy was the plane crash in downtown Seattle?
short answer : ['11']
{'score': 0.4947417080402374, 'start': 0, 'end': 8, 'answer': 'Season 8'}
{'rougeLsum': 23.52941176470588, 'length': 5.0, 'str_em': 50.0, 'Disambig-F1': 54.166666666666664}
[BM25 Retriever]
Final ans: ['According to the provided information, the Oriental Bank of Commerce (OBC) has 2390 branches and 2625 ATMs across India.']
According to the provided information, the Oriental Bank of Commerce (OBC) has 2390 branches and 2625 ATMs across India.
Number of branches of oriental bank of commerce in india?
['As per the March 2018-2019 report, what is the number of branches of oriental bank of commerce in india?', 'What is the number of branches of oriental bank of commerce in india after amalgamation of Global Trust Bank?', 'Number of branches of oriental bank of commerce in india after expected merger with United Bank of India in 2020?']
[['2390'], ['1092'], ['11,437']]

 80%|████████  | 16/20 [01:21<00:17,  4.36s/it]

follow question : As per the March 2018-2019 report, what is the number of branches of oriental bank of commerce in india?
short answer : ['2390']
{'score': 0.8939629197120667, 'start': 79, 'end': 83, 'answer': '2390'}
follow question : What is the number of branches of oriental bank of commerce in india after amalgamation of Global Trust Bank?
short answer : ['1092']
{'score': 0.886996328830719, 'start': 79, 'end': 83, 'answer': '2390'}
follow question : Number of branches of oriental bank of commerce in india after expected merger with United Bank of India in 2020?
short answer : ['11,437']
{'score': 0.8622214198112488, 'start': 79, 'end': 83, 'answer': '2390'}
{'rougeLsum': 25.0, 'length': 19.0, 'str_em': 33.33333333333333, 'Disambig-F1': 33.33333333333333}
[BM25 Retriever]
Final ans: ['There is no information in the provided context about the Rams going to St. Louis. The context appears to be a collection of episode summaries from various TV shows, including "The Next Step", "I Love Lucy", and "Soul Eater". There is no mention of the Rams or St. Louis in the provided text.']
There is no information in the provided context about the Rams going to St. Louis. The context appears to be a collection of episode summaries from various TV shows, including "The Next Step", "I Love Lucy", and "Soul Eater". There is no mention of the Rams or St. Louis in the provided text.
When did the rams go to st louis?
['In what year did the rams go to St. Louis?', 'What was the first game the Rams played in St. Louis?']
[['1995'], ['September 10, 1995']]

 85%|████████▌ | 17/20 [01:27<00:14,  4.78s/it]

follow question : In what year did the rams go to St. Louis?
short answer : ['1995']
{'score': 0.0003485000052023679, 'start': 0, 'end': 23, 'answer': 'There is no information'}
follow question : What was the first game the Rams played in St. Louis?
short answer : ['September 10, 1995']
{'score': 6.0659808696073014e-06, 'start': 9, 'end': 81, 'answer': 'no information in the provided context about the Rams going to St. Louis'}
{'rougeLsum': 30.252100840336137, 'length': 53.0, 'str_em': 0.0, 'Disambig-F1': 0.0}
[BM25 Retriever]
Final ans: ['The query about the voortrekkers arriving in South Africa cannot be answered based on the provided context information. The information provided is about various TV shows and documents, including "I Love Lucy", "Only Fools and Horses", "Still Game", and historical documents about the Louisiana Purchase, North American fur trade, and the Transformers series. There is no mention of the voortrekkers or their arrival in South Africa in the provided information.']
The query about the voortrekkers arriving in South Africa cannot be answered based on the provided context information. The information provided is about various TV shows and documents, including "I Love Lucy", "Only Fools and Horses", "Still Game", and historical documents about the Louisiana Purchase, North American fur trade, and the Transformers series. There is no mention of the voortrekkers or their arrival in South Africa in the provided information.
When did the voortrekkers arrive in south africa?
['When did the first wave of voortrekkers arrive in south africa?', 'When did the voortrekkers exploratory treks arrive in south africa?']
[['1836', '1836 onwards'], ['February 1835']]

 90%|█████████ | 18/20 [01:34<00:10,  5.45s/it]

follow question : When did the first wave of voortrekkers arrive in south africa?
short answer : ['1836', '1836 onwards']
{'score': 0.00047584480489604175, 'start': 360, 'end': 379, 'answer': 'There is no mention'}
follow question : When did the voortrekkers exploratory treks arrive in south africa?
short answer : ['February 1835']
{'score': 0.005036311689764261, 'start': 360, 'end': 379, 'answer': 'There is no mention'}
{'rougeLsum': 19.35483870967742, 'length': 70.0, 'str_em': 0.0, 'Disambig-F1': 0.0}
[BM25 Retriever]
Final ans: ['I don\'t have any information about a character named Patrick in the movie "10 Things I Hate About You". However, I can tell you that the movie is a modern retelling of Shakespeare\'s "The Taming of the Shrew" and it stars Heath Ledger as the character of Patrick Verona.']
I don't have any information about a character named Patrick in the movie "10 Things I Hate About You". However, I can tell you that the movie is a modern retelling of Shakespeare's "The Taming of the Shrew" and it stars Heath Ledger as the character of Patrick Verona.
Who plays patrick in 10 things i hate about you?
['Who plays patrick in  the 1999 film 10 things i hate about you?', 'Who plays patrick in the 2009 tv series 10 things i hate about you?', 'Who plays patrick in the film 10 things i hate about you?', 'Who plays patrick in the TV series 10 things i hate about you?']
[['Heath Andrew Ledger', 'Heath Ledger', 'Ledger'], ['Ethan Peck', 'Peck', 'Ethan Gregory Peck'], ['Heath Andrew Ledger', 'Heath Ledger'], ['Ethan Peck', 'Ethan Gregory Peck']]

 95%|█████████▌| 19/20 [01:39<00:05,  5.44s/it]

follow question : Who plays patrick in  the 1999 film 10 things i hate about you?
short answer : ['Heath Andrew Ledger', 'Heath Ledger', 'Ledger']
{'score': 0.055483803153038025, 'start': 221, 'end': 233, 'answer': 'Heath Ledger'}
follow question : Who plays patrick in the 2009 tv series 10 things i hate about you?
short answer : ['Ethan Peck', 'Peck', 'Ethan Gregory Peck']
{'score': 0.012239625677466393, 'start': 221, 'end': 233, 'answer': 'Heath Ledger'}
follow question : Who plays patrick in the film 10 things i hate about you?
short answer : ['Heath Andrew Ledger', 'Heath Ledger']
{'score': 0.6880030632019043, 'start': 221, 'end': 233, 'answer': 'Heath Ledger'}
follow question : Who plays patrick in the TV series 10 things i hate about you?
short answer : ['Ethan Peck', 'Ethan Gregory Peck']
{'score': 1.9201946997782215e-05, 'start': 221, 'end': 233, 'answer': 'Heath Ledger'}
{'rougeLsum': 40.0, 'length': 49.0, 'str_em': 50.0, 'Disambig-F1': 50.0}
[BM25 Retriever]
Final ans: ['Yes, Microsoft Live Movie Maker is an example of a free software.']
Yes, Microsoft Live Movie Maker is an example of a free software.
Microsoft live movie maker is an example of free?
['Microsoft live movie maker is an example of a freely licensed software, often called free what?', 'Microsoft live movie maker is an example of free software used for what purpose?']
[['freeware'], ['Video editing software']]

100%|██████████| 20/20 [01:42<00:00,  5.12s/it]

follow question : Microsoft live movie maker is an example of a freely licensed software, often called free what?
short answer : ['freeware']
{'score': 0.2116268426179886, 'start': 56, 'end': 64, 'answer': 'software'}
follow question : Microsoft live movie maker is an example of free software used for what purpose?
short answer : ['Video editing software']
{'score': 0.011645897291600704, 'start': 49, 'end': 64, 'answer': 'a free software'}
{'rougeLsum': 40.81632653061225, 'length': 12.0, 'str_em': 0.0, 'Disambig-F1': 20.0}

rougeLsum      26.991286
length         44.650000
str_em         28.750000
Disambig-F1    24.097222
dtype: float64

# Baseline

In [71]:
from tqdm import tqdm
from evaluation import evaluate

stop_iteration = 20

scores_list=[]
for idx, row in tqdm(qa_df.iterrows(), total=min([stop_iteration, len(qa_df)])):
    if idx == stop_iteration: break
    query = row['question']
    retrieved_docs = retrieve_documents(query)
    ans=answer(query,retrieved_docs)
    print('Final ans:', ans)
    scores=evaluate(ans, [row.to_dict()])
    scores_list.append(scores)
    scores_df=pd.DataFrame(scores_list)
    print(scores)
        
scores_df=pd.DataFrame(scores_list)
scores_df.mean()

  0%|          | 0/20 [00:00<?, ?it/s]/home/dataconv/.cache/huggingface/modules/transformers_modules/nvidia/NV-Embed-v2/5130cf1daf847c1bacee854a6ef1ca939e747fb2/modeling_nvembed.py:349: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'input_ids': torch.tensor(batch_dict.get('input_ids').to(batch_dict.get('input_ids')).long()),
/home/dataconv/anaconda3/envs/sf_rag_djk/lib/python3.10/contextlib.py:103: FutureWarning: `torch.backends.cuda.sdp_kernel()` is deprecated. In the future, this context manager will be removed. Please see `torch.nn.attention.sdpa_kernel()` for the new context manager, with updated signature.
  self.gen = func(*args, **kwds)

Final ans: ['Based on the provided information, the player with the highest goals in world football is Ali Daei from Iran, with a total of 109 international goals.']
Based on the provided information, the player with the highest goals in world football is Ali Daei from Iran, with a total of 109 international goals.
Who has the highest goals in world football?
["Who has the highest goals in men's world international football?", "Who has the highest goals all-time in men's football?", "Who has the highest goals in women's world international football?"]
[['Daei', 'Ali Daei'], ['Bican', 'Josef Bican'], ['Sinclair', 'Christine Sinclair']]

  5%|▌         | 1/20 [00:04<01:18,  4.11s/it]

follow question : Who has the highest goals in men's world international football?
short answer : ['Daei', 'Ali Daei']
{'score': 0.9068320989608765, 'start': 90, 'end': 98, 'answer': 'Ali Daei'}
follow question : Who has the highest goals all-time in men's football?
short answer : ['Bican', 'Josef Bican']
{'score': 0.17590554058551788, 'start': 90, 'end': 98, 'answer': 'Ali Daei'}
follow question : Who has the highest goals in women's world international football?
short answer : ['Sinclair', 'Christine Sinclair']
{'score': 0.03374573215842247, 'start': 90, 'end': 98, 'answer': 'Ali Daei'}
{'rougeLsum': 36.36363636363637, 'length': 26.0, 'str_em': 33.33333333333333, 'Disambig-F1': 33.33333333333333}
Final ans: ['Simon & Garfunkel.']
Simon & Garfunkel.
Who is the original artist of sound of silence?
['Who is the original artist of sound of silence, the song, released in 1964?', 'Who is the original artist of sound of silence, the album?', 'Who is the original artist of sound of silence, the song, released in 2016?']
[['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon'], ['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon'], ['Dami Im']]

 10%|█         | 2/20 [00:06<00:56,  3.13s/it]

follow question : Who is the original artist of sound of silence, the song, released in 1964?
short answer : ['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon']
{'score': 0.05452003329992294, 'start': 0, 'end': 17, 'answer': 'Simon & Garfunkel'}
follow question : Who is the original artist of sound of silence, the album?
short answer : ['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon']
{'score': 0.559449315071106, 'start': 0, 'end': 17, 'answer': 'Simon & Garfunkel'}
follow question : Who is the original artist of sound of silence, the song, released in 2016?
short answer : ['Dami Im']
{'score': 0.20271916687488556, 'start': 0, 'end': 17, 'answer': 'Simon & Garfunkel'}
{'rougeLsum': 6.779661016949151, 'length': 3.0, 'str_em': 66.66666666666666, 'Disambig-F1': 66.66666666666666}
Final ans: ['The first Apple iPhone was made in 2004, but it was not released to the public. The first iPhone was officially launched and made accessible to the public in 2007.']
The first Apple iPhone was made in 2004, but it was not released to the public. The first iPhone was officially launched and made accessible to the public in 2007.
When was the first apple i phone made?
['When was the first apple i phone released?', 'When was the first apple i phone for beta testing made?', 'When was the first apple i phone 1 made?', 'When was the first apple i phone beta made?']
[['June 29, 2007'], ['2004'], ['June 29, 2007.'], ['2004.']]

 15%|█▌        | 3/20 [00:10<01:01,  3.63s/it]

follow question : When was the first apple i phone released?
short answer : ['June 29, 2007']
{'score': 0.9450268149375916, 'start': 35, 'end': 39, 'answer': '2004'}
follow question : When was the first apple i phone for beta testing made?
short answer : ['2004']
{'score': 0.039315611124038696, 'start': 35, 'end': 39, 'answer': '2004'}
follow question : When was the first apple i phone 1 made?
short answer : ['June 29, 2007.']
{'score': 0.9628487229347229, 'start': 35, 'end': 39, 'answer': '2004'}
follow question : When was the first apple i phone beta made?
short answer : ['2004.']
{'score': 0.002406901214271784, 'start': 158, 'end': 162, 'answer': '2007'}
{'rougeLsum': 51.06382978723405, 'length': 30.0, 'str_em': 50.0, 'Disambig-F1': 25.0}
Final ans: ['The Weasley brothers, Fred and George, were played by actors James Phelps and Oliver Phelps.']
The Weasley brothers, Fred and George, were played by actors James Phelps and Oliver Phelps.
Who played the weasley brothers in harry potter?
['Who played  Bill weasley in Harry Potter and the Prisoner of Azkaban?', 'Who played percy weasley in harry potter?', 'Who played fred weasley in harry potter?', 'Who played ron weasley in harry potter?', 'Who played george weasley in harry potter?', 'Who played  Bill weasley in harry potter (2001-2011)?']
[['Richard Fish'], ['Chris Rankin'], ['James Phelps'], ['Rupert Grint'], ['Oliver Phelps'], ['Domhnall Gleeson']]

 20%|██        | 4/20 [00:13<00:54,  3.42s/it]

follow question : Who played  Bill weasley in Harry Potter and the Prisoner of Azkaban?
short answer : ['Richard Fish']
{'score': 0.008735242299735546, 'start': 61, 'end': 91, 'answer': 'James Phelps and Oliver Phelps'}
follow question : Who played percy weasley in harry potter?
short answer : ['Chris Rankin']
{'score': 0.734296977519989, 'start': 61, 'end': 91, 'answer': 'James Phelps and Oliver Phelps'}
follow question : Who played fred weasley in harry potter?
short answer : ['James Phelps']
{'score': 0.7380316853523254, 'start': 61, 'end': 91, 'answer': 'James Phelps and Oliver Phelps'}
follow question : Who played ron weasley in harry potter?
short answer : ['Rupert Grint']
{'score': 0.6803927421569824, 'start': 61, 'end': 91, 'answer': 'James Phelps and Oliver Phelps'}
follow question : Who played george weasley in harry potter?
short answer : ['Oliver Phelps']
{'score': 0.6067038178443909, 'start': 61, 'end': 91, 'answer': 'James Phelps and Oliver Phelps'}
follow question : Who played  Bill weasley in harry potter (2001-2011)?
short answer : ['Domhnall Gleeson']
{'score': 0.010211968794465065, 'start': 61, 'end': 91, 'answer': 'James Phelps and Oliver Phelps'}
{'rougeLsum': 26.000000000000007, 'length': 15.0, 'str_em': 33.33333333333333, 'Disambig-F1': 19.04761904761905}
Final ans: ['According to the provided context information, there are 38 state parks in Virginia.']
According to the provided context information, there are 38 state parks in Virginia.
How many state parks are there in virginia?
['How many state parks are there in virginia in 1936?', 'How many state parks are there in virginia in 2016?', 'How many state parks were there when the state park system formed in Virginia?', 'How many state parks were there in Virginia as of 2016?']
[['six'], ['38'], ['6'], ['38']]

 25%|██▌       | 5/20 [00:16<00:47,  3.16s/it]

follow question : How many state parks are there in virginia in 1936?
short answer : ['six']
{'score': 0.0019380656303837895, 'start': 57, 'end': 59, 'answer': '38'}
follow question : How many state parks are there in virginia in 2016?
short answer : ['38']
{'score': 0.4065036177635193, 'start': 57, 'end': 59, 'answer': '38'}
follow question : How many state parks were there when the state park system formed in Virginia?
short answer : ['6']
{'score': 0.785505473613739, 'start': 57, 'end': 59, 'answer': '38'}
follow question : How many state parks were there in Virginia as of 2016?
short answer : ['38']
{'score': 0.43257200717926025, 'start': 57, 'end': 59, 'answer': '38'}
{'rougeLsum': 29.78723404255319, 'length': 13.0, 'str_em': 50.0, 'Disambig-F1': 50.0}
Final ans: ['Dua Lipa performed at the opening ceremony preceding the final. Jamaican rapper Sean Paul joined her as a special guest to perform their collaborative song, "No Lie". The UEFA Champions League Anthem was performed by Slovenian–Croatian cello duo 2Cellos.']
Dua Lipa performed at the opening ceremony preceding the final. Jamaican rapper Sean Paul joined her as a special guest to perform their collaborative song, "No Lie". The UEFA Champions League Anthem was performed by Slovenian–Croatian cello duo 2Cellos.
Who performed at the champions league final 2018?
['Who are the teams that performed in competition at the champions league final 2018?', 'Who performed best at the champions league final 2018, winning man of the match?', 'Who performed at the opening ceremony of the champions league final 2018?', 'Who performed the anthem at the champions league final 2018?']
[['Real Madrid and Liverpool', 'Liverpool', 'Real Madrid'], ['Gareth Bale', 'Bale'], ['Dua Lipa', 'Sean Paul', 'Dua Lipa and Sean Paul'], ['2Cellos', 'Luka Šulić and Stjepan Hauser', 'Luka Šulić', '2CΞLLOS', 'Stjepan Hauser']]

 30%|███       | 6/20 [00:21<00:52,  3.74s/it]

follow question : Who are the teams that performed in competition at the champions league final 2018?
short answer : ['Real Madrid and Liverpool', 'Liverpool', 'Real Madrid']
{'score': 0.007240962237119675, 'start': 217, 'end': 254, 'answer': 'Slovenian–Croatian cello duo 2Cellos.'}
follow question : Who performed best at the champions league final 2018, winning man of the match?
short answer : ['Gareth Bale', 'Bale']
{'score': 0.6521135568618774, 'start': 0, 'end': 8, 'answer': 'Dua Lipa'}
follow question : Who performed at the opening ceremony of the champions league final 2018?
short answer : ['Dua Lipa', 'Sean Paul', 'Dua Lipa and Sean Paul']
{'score': 0.147010937333107, 'start': 0, 'end': 8, 'answer': 'Dua Lipa'}
follow question : Who performed the anthem at the champions league final 2018?
short answer : ['2Cellos', 'Luka Šulić and Stjepan Hauser', 'Luka Šulić', '2CΞLLOS', 'Stjepan Hauser']
{'score': 0.7429537177085876, 'start': 246, 'end': 253, 'answer': '2Cellos'}
{'rougeLsum': 62.99212598425197, 'length': 39.0, 'str_em': 50.0, 'Disambig-F1': 50.0}
Final ans: ['Harlan. He was a stranger that Thelma met at a roadhouse bar, and he attempted to rape her. Louise found them and, in a fit of rage, shot Harlan in the chest, killing him instantly.']
Harlan. He was a stranger that Thelma met at a roadhouse bar, and he attempted to rape her. Louise found them and, in a fit of rage, shot Harlan in the chest, killing him instantly.
Who killed the man in thelma and louise?
['Which character killed the man in thelma and louise?', 'Which actor killed the man in thelma and louise?', 'Who is the character that kills Harlan in the film Thelma and Louise?', 'Who is the actor of the character that killed a man in the film Thelma and Louise?']
[['Louise Elizabeth Sawyer', 'Louise'], ['Susan Sarandon', 'Susan Abigail Sarandon'], ['Louise Elizabeth Sawyer', 'Louise'], ['Susan Sarandon']]

 35%|███▌      | 7/20 [00:25<00:52,  4.00s/it]

follow question : Which character killed the man in thelma and louise?
short answer : ['Louise Elizabeth Sawyer', 'Louise']
{'score': 0.5165236592292786, 'start': 0, 'end': 6, 'answer': 'Harlan'}
follow question : Which actor killed the man in thelma and louise?
short answer : ['Susan Sarandon', 'Susan Abigail Sarandon']
{'score': 0.40816888213157654, 'start': 0, 'end': 6, 'answer': 'Harlan'}
follow question : Who is the character that kills Harlan in the film Thelma and Louise?
short answer : ['Louise Elizabeth Sawyer', 'Louise']
{'score': 0.06835994869470596, 'start': 92, 'end': 98, 'answer': 'Louise'}
follow question : Who is the actor of the character that killed a man in the film Thelma and Louise?
short answer : ['Susan Sarandon']
{'score': 0.8175877928733826, 'start': 0, 'end': 6, 'answer': 'Harlan'}
{'rougeLsum': 45.28301886792453, 'length': 35.0, 'str_em': 50.0, 'Disambig-F1': 25.0}
Final ans: ['Charlie Kelly is played by Charlie Day.']
Charlie Kelly is played by Charlie Day.
Who plays charlie on it's always sunny?
["Who does Charlie Day play on It's Always Sunny in Philadelphia?", "Who plays Charlie Kelly on It's Always Sunny in Philadelphia?"]
[['Charlie Kelly'], ['Charlie Day']]

 40%|████      | 8/20 [00:28<00:41,  3.46s/it]

follow question : Who does Charlie Day play on It's Always Sunny in Philadelphia?
short answer : ['Charlie Kelly']
{'score': 0.9911195039749146, 'start': 0, 'end': 13, 'answer': 'Charlie Kelly'}
follow question : Who plays Charlie Kelly on It's Always Sunny in Philadelphia?
short answer : ['Charlie Day']
{'score': 0.9776415824890137, 'start': 27, 'end': 38, 'answer': 'Charlie Day'}
{'rougeLsum': 37.03703703703704, 'length': 7.0, 'str_em': 100.0, 'Disambig-F1': 100.0}
Final ans: ['The Los Angeles Lakers have won the NBA Finals 16 times.']
The Los Angeles Lakers have won the NBA Finals 16 times.
How many times have the lakers won the finals?
['As of 2017, how many times have the lakers won the finals?', 'As of 2016, how many times have the Lakers won the finals?', 'As of 2015, how many times have the Lakers won the finals?']
[['16'], ['16'], ['16']]

 45%|████▌     | 9/20 [00:31<00:35,  3.25s/it]

follow question : As of 2017, how many times have the lakers won the finals?
short answer : ['16']
{'score': 0.8386049270629883, 'start': 47, 'end': 49, 'answer': '16'}
follow question : As of 2016, how many times have the Lakers won the finals?
short answer : ['16']
{'score': 0.8818942904472351, 'start': 47, 'end': 49, 'answer': '16'}
follow question : As of 2015, how many times have the Lakers won the finals?
short answer : ['16']
{'score': 0.7783189415931702, 'start': 47, 'end': 49, 'answer': '16'}
{'rougeLsum': 25.454545454545457, 'length': 11.0, 'str_em': 100.0, 'Disambig-F1': 100.0}
Final ans: ['According to the provided context information, as of July 2019, the party is in power in six legislative assemblies: Punjab, Rajasthan, Chhattisgarh, Madhya Pradesh, Maharashtra (as part of the Maha Vikas Aghadi), and the union territory of Puducherry (in an alliance with DMK).']
According to the provided context information, as of July 2019, the party is in power in six legislative assemblies: Punjab, Rajasthan, Chhattisgarh, Madhya Pradesh, Maharashtra (as part of the Maha Vikas Aghadi), and the union territory of Puducherry (in an alliance with DMK).
How many states in india are under congress?
['How many states plus territories in india are under congress?', 'How many states alone in india are under congress?']
[['7'], ['5']]

 50%|█████     | 10/20 [00:36<00:38,  3.89s/it]

follow question : How many states plus territories in india are under congress?
short answer : ['7']
{'score': 0.43441668152809143, 'start': 89, 'end': 92, 'answer': 'six'}
follow question : How many states alone in india are under congress?
short answer : ['5']
{'score': 0.08470899611711502, 'start': 89, 'end': 92, 'answer': 'six'}
{'rougeLsum': 13.461538461538462, 'length': 43.0, 'str_em': 0.0, 'Disambig-F1': 0.0}
Final ans: ["Fruma-Sarah is the late wife of Lazar Wolf, a wealthy butcher in the village of Anatevka. She rises from the grave in Tevye's dream to warn him of severe retribution if Tzeitel marries Lazar."]
Fruma-Sarah is the late wife of Lazar Wolf, a wealthy butcher in the village of Anatevka. She rises from the grave in Tevye's dream to warn him of severe retribution if Tzeitel marries Lazar.
Who is fruma sarah in fiddler on the roof?
['Who played fruma sarah in the 1971 film, Fiddler on the Roof?', 'Who played Fruma Sarah in the original 1964 Broadway cast of Fiddler on the Roof?', 'Who is the character of Fruma Sarah in Fiddler on the Roof?', 'Who played Fruma Sarah in the 2015-2016 Broadway Revival of Fiddler on the Roof?']
[['Ruth Madoc'], ['Carol Sawyer Yussel'], ['a ghostly depiction of the late wife of Lazar Wolf'], ['Jessica Vosk']]

 55%|█████▌    | 11/20 [00:40<00:36,  4.08s/it]

follow question : Who played fruma sarah in the 1971 film, Fiddler on the Roof?
short answer : ['Ruth Madoc']
{'score': 0.0006140280165709555, 'start': 118, 'end': 123, 'answer': 'Tevye'}
follow question : Who played Fruma Sarah in the original 1964 Broadway cast of Fiddler on the Roof?
short answer : ['Carol Sawyer Yussel']
{'score': 0.0026697940193116665, 'start': 118, 'end': 123, 'answer': 'Tevye'}
follow question : Who is the character of Fruma Sarah in Fiddler on the Roof?
short answer : ['a ghostly depiction of the late wife of Lazar Wolf']
{'score': 0.5638086199760437, 'start': 32, 'end': 42, 'answer': 'Lazar Wolf'}
follow question : Who played Fruma Sarah in the 2015-2016 Broadway Revival of Fiddler on the Roof?
short answer : ['Jessica Vosk']
{'score': 0.001089999102987349, 'start': 118, 'end': 123, 'answer': 'Tevye'}
{'rougeLsum': 23.188405797101446, 'length': 34.0, 'str_em': 0.0, 'Disambig-F1': 10.0}
Final ans: ['July 9, 1991']
July 9, 1991
When did toronto host the mlb all-star game?
['What date did toronto host the mlb all-star game?', 'Which all-star game did toronto host?']
[['July 9, 1991'], ['1991 Major League Baseball All-Star Game', 'the 62nd playing of the midsummer classic']]

 60%|██████    | 12/20 [00:43<00:29,  3.64s/it]

follow question : What date did toronto host the mlb all-star game?
short answer : ['July 9, 1991']
{'score': 0.010271838866174221, 'start': 0, 'end': 12, 'answer': 'July 9, 1991'}
follow question : Which all-star game did toronto host?
short answer : ['1991 Major League Baseball All-Star Game', 'the 62nd playing of the midsummer classic']
{'score': 1.9473118300084025e-06, 'start': 8, 'end': 12, 'answer': '1991'}
{'rougeLsum': 23.076923076923077, 'length': 3.0, 'str_em': 50.0, 'Disambig-F1': 64.28571428571428}
Final ans: ['A metallic blue 1953 Sunbeam Alpine Mk I is driven by Grace Kelly in the film To Catch a Thief.']
A metallic blue 1953 Sunbeam Alpine Mk I is driven by Grace Kelly in the film To Catch a Thief.
What kind of car in to catch a thief?
['What kind of car in to catch a thief in terms of model?', 'What kind of car in to catch a thief in terms of automobile make?']
[['Sunbeam Alpine', '1953 Sunbeam Alpine Mk I'], ['Rootes Group']]

 65%|██████▌   | 13/20 [00:46<00:24,  3.56s/it]

follow question : What kind of car in to catch a thief in terms of model?
short answer : ['Sunbeam Alpine', '1953 Sunbeam Alpine Mk I']
{'score': 0.3136484622955322, 'start': 21, 'end': 40, 'answer': 'Sunbeam Alpine Mk I'}
follow question : What kind of car in to catch a thief in terms of automobile make?
short answer : ['Rootes Group']
{'score': 0.4145355522632599, 'start': 21, 'end': 40, 'answer': 'Sunbeam Alpine Mk I'}
{'rougeLsum': 35.08771929824562, 'length': 20.0, 'str_em': 50.0, 'Disambig-F1': 44.44444444444445}
Final ans: ['The last season of Jersey Shore aired from January 6, 2011, to March 24, 2011.']
The last season of Jersey Shore aired from January 6, 2011, to March 24, 2011.
When did the last season of jersey shore air?
['When did season 4 of jersey shore first air?', 'When did season 4 of jersey shore last air?', 'When did season 5 of jersey shore first air?', 'When did season 5 of jersey shore last air?', 'When did season 6 of jersey shore first air?', 'When did season 6 of jersey shore last air?']
[['August 4, 2011'], ['October 20, 2011'], ['January 5, 2012'], ['March 15, 2012'], ['October 4, 2012'], ['December 20, 2012']]

 70%|███████   | 14/20 [00:50<00:21,  3.53s/it]

follow question : When did season 4 of jersey shore first air?
short answer : ['August 4, 2011']
{'score': 0.03765404224395752, 'start': 43, 'end': 58, 'answer': 'January 6, 2011'}
follow question : When did season 4 of jersey shore last air?
short answer : ['October 20, 2011']
{'score': 0.5519999265670776, 'start': 43, 'end': 58, 'answer': 'January 6, 2011'}
follow question : When did season 5 of jersey shore first air?
short answer : ['January 5, 2012']
{'score': 0.04579399898648262, 'start': 43, 'end': 58, 'answer': 'January 6, 2011'}
follow question : When did season 5 of jersey shore last air?
short answer : ['March 15, 2012']
{'score': 0.5343342423439026, 'start': 43, 'end': 58, 'answer': 'January 6, 2011'}
follow question : When did season 6 of jersey shore first air?
short answer : ['October 4, 2012']
{'score': 0.09365998208522797, 'start': 43, 'end': 58, 'answer': 'January 6, 2011'}
follow question : When did season 6 of jersey shore last air?
short answer : ['December 20, 2012']
{'score': 0.5951405167579651, 'start': 43, 'end': 58, 'answer': 'January 6, 2011'}
{'rougeLsum': 25.0, 'length': 15.0, 'str_em': 0.0, 'Disambig-F1': 16.666666666666664}
Final ans: ['The plane crash occurred in the season 8 finale, which is the 24th episode of the 8th season, "Going, Going, Gone".']
The plane crash occurred in the season 8 finale, which is the 24th episode of the 8th season, "Going, Going, Gone".
What season of greys anatomy was the plane crash?
["What season of Grey's Anatomy was the plane crash involving six doctors?", "What season of Grey's Anatomy was the plane crash in Seattle that brought memories of a previous plane crash?", "What season of Grey's Anatomy was the plane crash that claimed the life of Lexie Grey?", "What season of Grey's Anatomy was the plane crash in downtown Seattle?"]
[['season 8'], ['season 11'], ['8'], ['11']]

 75%|███████▌  | 15/20 [00:54<00:17,  3.58s/it]

follow question : What season of Grey's Anatomy was the plane crash involving six doctors?
short answer : ['season 8']
{'score': 0.4570264220237732, 'start': 32, 'end': 40, 'answer': 'season 8'}
follow question : What season of Grey's Anatomy was the plane crash in Seattle that brought memories of a previous plane crash?
short answer : ['season 11']
{'score': 0.4474673867225647, 'start': 32, 'end': 40, 'answer': 'season 8'}
follow question : What season of Grey's Anatomy was the plane crash that claimed the life of Lexie Grey?
short answer : ['8']
{'score': 0.3868967592716217, 'start': 32, 'end': 40, 'answer': 'season 8'}
follow question : What season of Grey's Anatomy was the plane crash in downtown Seattle?
short answer : ['11']
{'score': 0.4854734539985657, 'start': 32, 'end': 40, 'answer': 'season 8'}
{'rougeLsum': 27.272727272727277, 'length': 21.0, 'str_em': 50.0, 'Disambig-F1': 54.166666666666664}
Final ans: ['According to the provided context information, the Oriental Bank of Commerce has 2390 branches across India.']
According to the provided context information, the Oriental Bank of Commerce has 2390 branches across India.
Number of branches of oriental bank of commerce in india?
['As per the March 2018-2019 report, what is the number of branches of oriental bank of commerce in india?', 'What is the number of branches of oriental bank of commerce in india after amalgamation of Global Trust Bank?', 'Number of branches of oriental bank of commerce in india after expected merger with United Bank of India in 2020?']
[['2390'], ['1092'], ['11,437']]

 80%|████████  | 16/20 [00:57<00:13,  3.49s/it]

follow question : As per the March 2018-2019 report, what is the number of branches of oriental bank of commerce in india?
short answer : ['2390']
{'score': 0.8879225850105286, 'start': 81, 'end': 85, 'answer': '2390'}
follow question : What is the number of branches of oriental bank of commerce in india after amalgamation of Global Trust Bank?
short answer : ['1092']
{'score': 0.8447265625, 'start': 81, 'end': 85, 'answer': '2390'}
follow question : Number of branches of oriental bank of commerce in india after expected merger with United Bank of India in 2020?
short answer : ['11,437']
{'score': 0.7973387241363525, 'start': 81, 'end': 85, 'answer': '2390'}
{'rougeLsum': 23.376623376623375, 'length': 16.0, 'str_em': 33.33333333333333, 'Disambig-F1': 33.33333333333333}
Final ans: ['The Rams relocated to St. Louis in 1995.']
The Rams relocated to St. Louis in 1995.
When did the rams go to st louis?
['In what year did the rams go to St. Louis?', 'What was the first game the Rams played in St. Louis?']
[['1995'], ['September 10, 1995']]

 85%|████████▌ | 17/20 [00:59<00:09,  3.20s/it]

follow question : In what year did the rams go to St. Louis?
short answer : ['1995']
{'score': 0.986748993396759, 'start': 35, 'end': 39, 'answer': '1995'}
follow question : What was the first game the Rams played in St. Louis?
short answer : ['September 10, 1995']
{'score': 0.3165511190891266, 'start': 35, 'end': 39, 'answer': '1995'}
{'rougeLsum': 18.91891891891892, 'length': 8.0, 'str_em': 50.0, 'Disambig-F1': 75.0}
Final ans: ["The Voortrekkers arrived in South Africa in the early 19th century, specifically between 1835 and 1840. They were a group of Dutch-speaking settlers who migrated from the Cape Colony into the interior of modern South Africa, seeking to live beyond the Cape's British colonial administration.The first wave of Voortrekkers lasted from 1835 to 1840, during which an estimated 6,000 people trekked. They were led by various leaders, including Louis Tregardt, Hans van Rensburg, Hendrik Potgieter, Gerrit Maritz, Piet Retief, and Piet Uys.The Voortrekkers arrived in various parts of South Africa, including the areas that are now known as the provinces of the Orange Free State, the Transvaal, and Natal. They established several autonomous Boer republics, including the South African Republic (also known as the Transvaal), the Orange Free State, and the Natalia Republic.The Voortrekkers' arrival in South Africa had a significant impact on the country's history, leading to the displacement of the Northern Ndebele people and contributing to the decline and collapse of the Zulu Empire."]
The Voortrekkers arrived in South Africa in the early 19th century, specifically between 1835 and 1840. They were a group of Dutch-speaking settlers who migrated from the Cape Colony into the interior of modern South Africa, seeking to live beyond the Cape's British colonial administration.The first wave of Voortrekkers lasted from 1835 to 1840, during which an estimated 6,000 people trekked. They were led by various leaders, including Louis Tregardt, Hans van Rensburg, Hendrik Potgieter, Gerrit Maritz, Piet Retief, and Piet Uys.The Voortrekkers arrived in various parts of South Africa, including the areas that are now known as the provinces of the Orange Free State, the Transvaal, and Natal. They established several autonomous Boer republics, including the South African Republic (also known as the Transvaal), the Orange Free State, and the Natalia Republic.The Voortrekkers' arrival in South Africa had a significant impact on the country's history, leading to the displacement of the Northern Ndebele people and contributing to the decline and collapse of the Zulu Empire.
When did the voortrekkers arrive in south africa?
['When did the first wave of voortrekkers arrive in south africa?', 'When did the voortrekkers exploratory treks arrive in south africa?']
[['1836', '1836 onwards'], ['February 1835']]

 90%|█████████ | 18/20 [01:14<00:13,  6.58s/it]

follow question : When did the first wave of voortrekkers arrive in south africa?
short answer : ['1836', '1836 onwards']
{'score': 0.26387420296669006, 'start': 334, 'end': 346, 'answer': '1835 to 1840'}
follow question : When did the voortrekkers exploratory treks arrive in south africa?
short answer : ['February 1835']
{'score': 0.2865034341812134, 'start': 81, 'end': 102, 'answer': 'between 1835 and 1840'}
{'rougeLsum': 22.119815668202765, 'length': 166.0, 'str_em': 0.0, 'Disambig-F1': 16.666666666666664}
Final ans: ['Heath Ledger plays Patrick Verona in the 1999 film "10 Things I Hate About You".']
Heath Ledger plays Patrick Verona in the 1999 film "10 Things I Hate About You".
Who plays patrick in 10 things i hate about you?
['Who plays patrick in  the 1999 film 10 things i hate about you?', 'Who plays patrick in the 2009 tv series 10 things i hate about you?', 'Who plays patrick in the film 10 things i hate about you?', 'Who plays patrick in the TV series 10 things i hate about you?']
[['Heath Andrew Ledger', 'Heath Ledger', 'Ledger'], ['Ethan Peck', 'Peck', 'Ethan Gregory Peck'], ['Heath Andrew Ledger', 'Heath Ledger'], ['Ethan Peck', 'Ethan Gregory Peck']]

 95%|█████████▌| 19/20 [01:17<00:05,  5.70s/it]

follow question : Who plays patrick in  the 1999 film 10 things i hate about you?
short answer : ['Heath Andrew Ledger', 'Heath Ledger', 'Ledger']
{'score': 0.9766072630882263, 'start': 0, 'end': 12, 'answer': 'Heath Ledger'}
follow question : Who plays patrick in the 2009 tv series 10 things i hate about you?
short answer : ['Ethan Peck', 'Peck', 'Ethan Gregory Peck']
{'score': 3.505659333313815e-05, 'start': 0, 'end': 12, 'answer': 'Heath Ledger'}
follow question : Who plays patrick in the film 10 things i hate about you?
short answer : ['Heath Andrew Ledger', 'Heath Ledger']
{'score': 0.9249846935272217, 'start': 0, 'end': 12, 'answer': 'Heath Ledger'}
follow question : Who plays patrick in the TV series 10 things i hate about you?
short answer : ['Ethan Peck', 'Ethan Gregory Peck']
{'score': 0.0006961016915738583, 'start': 0, 'end': 12, 'answer': 'Heath Ledger'}
{'rougeLsum': 36.36363636363637, 'length': 15.0, 'str_em': 50.0, 'Disambig-F1': 50.0}
Final ans: ['Yes, Microsoft Live Movie Maker is an example of free software. According to the context information, it is classified as a "Freeware" under the "License" section.']
Yes, Microsoft Live Movie Maker is an example of free software. According to the context information, it is classified as a "Freeware" under the "License" section.
Microsoft live movie maker is an example of free?
['Microsoft live movie maker is an example of a freely licensed software, often called free what?', 'Microsoft live movie maker is an example of free software used for what purpose?']
[['freeware'], ['Video editing software']]

100%|██████████| 20/20 [01:21<00:00,  4.08s/it]

follow question : Microsoft live movie maker is an example of a freely licensed software, often called free what?
short answer : ['freeware']
{'score': 0.7824744582176208, 'start': 125, 'end': 133, 'answer': 'Freeware'}
follow question : Microsoft live movie maker is an example of free software used for what purpose?
short answer : ['Video editing software']
{'score': 0.4667998254299164, 'start': 125, 'end': 133, 'answer': 'Freeware'}
{'rougeLsum': 45.90163934426229, 'length': 26.0, 'str_em': 50.0, 'Disambig-F1': 50.0}

rougeLsum      30.726452
length         27.300000
str_em         43.333333
Disambig-F1    44.180556
dtype: float64

In [9]:
from tqdm import tqdm
from evaluation import evaluate

stop_iteration = 20

scores_list=[]
for idx, row in tqdm(qa_df.iterrows(), total=min([stop_iteration, len(qa_df)])):
    if idx == stop_iteration: break
    query = row['question']
    retrieved_docs = retrieve_documents(query)
    ans=answer(query,retrieved_docs)
    print('First ans:', ans[0])
    ans_docs=retrieve_documents(ans[0])
    final_ans=answer(query,ans_docs)
    print('Second ans:', final_ans[0])
    scores=evaluate(final_ans, [row.to_dict()])
    scores_list.append(scores)
    scores_df=pd.DataFrame(scores_list)
    print(scores)
        
scores_df=pd.DataFrame(scores_list)
scores_df.mean()

  0%|          | 0/20 [00:00<?, ?it/s]/home/dataconv/.cache/huggingface/modules/transformers_modules/nvidia/NV-Embed-v2/5130cf1daf847c1bacee854a6ef1ca939e747fb2/modeling_nvembed.py:349: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'input_ids': torch.tensor(batch_dict.get('input_ids').to(batch_dict.get('input_ids')).long()),
/home/dataconv/anaconda3/envs/sf_rag_djk/lib/python3.10/contextlib.py:103: FutureWarning: `torch.backends.cuda.sdp_kernel()` is deprecated. In the future, this context manager will be removed. Please see `torch.nn.attention.sdpa_kernel()` for the new context manager, with updated signature.
  self.gen = func(*args, **kwds)

First ans: Based on the provided context information, the answer to the query "Who has the highest goals in world football?" is Ali Daei of Iran, with 109 goals in international football.
Second ans: Josef Bican with 805 goals is the player with the highest goals in world football, however, his total goals are not from international football but from all levels of football.
Josef Bican with 805 goals is the player with the highest goals in world football, however, his total goals are not from international football but from all levels of football.
Who has the highest goals in world football?
["Who has the highest goals in men's world international football?", "Who has the highest goals all-time in men's football?", "Who has the highest goals in women's world international football?"]
[['Daei', 'Ali Daei'], ['Bican', 'Josef Bican'], ['Sinclair', 'Christine Sinclair']]

  5%|▌         | 1/20 [00:08<02:41,  8.49s/it]

follow question : Who has the highest goals in men's world international football?
short answer : ['Daei', 'Ali Daei']
{'score': 0.9422071576118469, 'start': 0, 'end': 11, 'answer': 'Josef Bican'}
follow question : Who has the highest goals all-time in men's football?
short answer : ['Bican', 'Josef Bican']
{'score': 0.06932494789361954, 'start': 0, 'end': 11, 'answer': 'Josef Bican'}
follow question : Who has the highest goals in women's world international football?
short answer : ['Sinclair', 'Christine Sinclair']
{'score': 4.98272966069635e-05, 'start': 0, 'end': 11, 'answer': 'Josef Bican'}
{'rougeLsum': 40.0, 'length': 30.0, 'str_em': 33.33333333333333, 'Disambig-F1': 33.33333333333333}
First ans: The original artist of "The Sound of Silence" is Simon & Garfunkel, a duo composed of Paul Simon and Art Garfunkel.
Second ans: The original artist of "The Sound of Silence" is Simon & Garfunkel, a duo consisting of Paul Simon and Art Garfunkel.
The original artist of "The Sound of Silence" is Simon & Garfunkel, a duo consisting of Paul Simon and Art Garfunkel.
Who is the original artist of sound of silence?
['Who is the original artist of sound of silence, the song, released in 1964?', 'Who is the original artist of sound of silence, the album?', 'Who is the original artist of sound of silence, the song, released in 2016?']
[['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon'], ['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon'], ['Dami Im']]

 10%|█         | 2/20 [00:15<02:14,  7.48s/it]

follow question : Who is the original artist of sound of silence, the song, released in 1964?
short answer : ['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon']
{'score': 0.16110120713710785, 'start': 49, 'end': 66, 'answer': 'Simon & Garfunkel'}
follow question : Who is the original artist of sound of silence, the album?
short answer : ['Simon & Garfunkel', 'Paul Simon and Art Garfunkel', 'Art Garfunkel', 'Paul Simon']
{'score': 0.9659111499786377, 'start': 49, 'end': 66, 'answer': 'Simon & Garfunkel'}
follow question : Who is the original artist of sound of silence, the song, released in 2016?
short answer : ['Dami Im']
{'score': 0.6944733262062073, 'start': 49, 'end': 66, 'answer': 'Simon & Garfunkel'}
{'rougeLsum': 38.961038961038966, 'length': 21.0, 'str_em': 66.66666666666666, 'Disambig-F1': 66.66666666666666}
First ans: The first iPhone was announced by Steve Jobs on January 9, 2007, and was released in the United States on June 29, 2007.
Second ans: The first iPhone was announced on January 9, 2007, and was released on June 29, 2007.
The first iPhone was announced on January 9, 2007, and was released on June 29, 2007.
When was the first apple i phone made?
['When was the first apple i phone released?', 'When was the first apple i phone for beta testing made?', 'When was the first apple i phone 1 made?', 'When was the first apple i phone beta made?']
[['June 29, 2007'], ['2004'], ['June 29, 2007.'], ['2004.']]

 15%|█▌        | 3/20 [00:22<02:07,  7.52s/it]

follow question : When was the first apple i phone released?
short answer : ['June 29, 2007']
{'score': 0.7293349504470825, 'start': 71, 'end': 84, 'answer': 'June 29, 2007'}
follow question : When was the first apple i phone for beta testing made?
short answer : ['2004']
{'score': 0.16601374745368958, 'start': 34, 'end': 49, 'answer': 'January 9, 2007'}
follow question : When was the first apple i phone 1 made?
short answer : ['June 29, 2007.']
{'score': 0.7112618684768677, 'start': 34, 'end': 49, 'answer': 'January 9, 2007'}
follow question : When was the first apple i phone beta made?
short answer : ['2004.']
{'score': 0.06009191274642944, 'start': 34, 'end': 49, 'answer': 'January 9, 2007'}
{'rougeLsum': 27.500000000000004, 'length': 16.0, 'str_em': 50.0, 'Disambig-F1': 33.33333333333333}
First ans: The Weasley brothers, Fred, George, and their family members, were played by the following actors:* Fred and George Weasley were played by James and Oliver Phelps, respectively.* Bill Weasley was played by Domhnall Gleeson.* Charlie Weasley was played by Alex Crockford.* Arthur Weasley was played by Mark Williams.* Percy Weasley was played by Chris Rankin.* Ron Weasley was played by Rupert Grint.* Ginny Weasley was played by Bonnie Wright.* The Weasley parents, Arthur and Molly, were played by Mark Williams and Julie Walters, respectively.
Second ans: The Weasley brothers, Fred and George, were played by James and Oliver Phelps.
The Weasley brothers, Fred and George, were played by James and Oliver Phelps.
Who played the weasley brothers in harry potter?
['Who played  Bill weasley in Harry Potter and the Prisoner of Azkaban?', 'Who played percy weasley in harry potter?', 'Who played fred weasley in harry potter?', 'Who played ron weasley in harry potter?', 'Who played george weasley in harry potter?', 'Who played  Bill weasley in harry potter (2001-2011)?']
[['Richard Fish'], ['Chris Rankin'], ['James Phelps'], ['Rupert Grint'], ['Oliver Phelps'], ['Domhnall Gleeson']]

 20%|██        | 4/20 [00:33<02:23,  8.94s/it]

follow question : Who played  Bill weasley in Harry Potter and the Prisoner of Azkaban?
short answer : ['Richard Fish']
{'score': 0.006908164359629154, 'start': 54, 'end': 77, 'answer': 'James and Oliver Phelps'}
follow question : Who played percy weasley in harry potter?
short answer : ['Chris Rankin']
{'score': 0.8993854522705078, 'start': 54, 'end': 77, 'answer': 'James and Oliver Phelps'}
follow question : Who played fred weasley in harry potter?
short answer : ['James Phelps']
{'score': 0.9052622318267822, 'start': 54, 'end': 77, 'answer': 'James and Oliver Phelps'}
follow question : Who played ron weasley in harry potter?
short answer : ['Rupert Grint']
{'score': 0.9002230167388916, 'start': 54, 'end': 77, 'answer': 'James and Oliver Phelps'}
follow question : Who played george weasley in harry potter?
short answer : ['Oliver Phelps']
{'score': 0.8872855305671692, 'start': 54, 'end': 77, 'answer': 'James and Oliver Phelps'}
follow question : Who played  Bill weasley in harry potter (2001-2011)?
short answer : ['Domhnall Gleeson']
{'score': 0.005987644661217928, 'start': 54, 'end': 77, 'answer': 'James and Oliver Phelps'}
{'rougeLsum': 22.44897959183674, 'length': 13.0, 'str_em': 16.666666666666664, 'Disambig-F1': 22.22222222222222}
First ans: There are 38 state parks in Virginia.
Second ans: According to the provided context information, there are 38 state parks in Virginia.
According to the provided context information, there are 38 state parks in Virginia.
How many state parks are there in virginia?
['How many state parks are there in virginia in 1936?', 'How many state parks are there in virginia in 2016?', 'How many state parks were there when the state park system formed in Virginia?', 'How many state parks were there in Virginia as of 2016?']
[['six'], ['38'], ['6'], ['38']]

 25%|██▌       | 5/20 [00:38<01:50,  7.36s/it]

follow question : How many state parks are there in virginia in 1936?
short answer : ['six']
{'score': 0.0019380656303837895, 'start': 57, 'end': 59, 'answer': '38'}
follow question : How many state parks are there in virginia in 2016?
short answer : ['38']
{'score': 0.4065036177635193, 'start': 57, 'end': 59, 'answer': '38'}
follow question : How many state parks were there when the state park system formed in Virginia?
short answer : ['6']
{'score': 0.785505473613739, 'start': 57, 'end': 59, 'answer': '38'}
follow question : How many state parks were there in Virginia as of 2016?
short answer : ['38']
{'score': 0.43257200717926025, 'start': 57, 'end': 59, 'answer': '38'}
{'rougeLsum': 29.78723404255319, 'length': 13.0, 'str_em': 50.0, 'Disambig-F1': 50.0}
First ans: The opening ceremony of the 2018 UEFA Champions League Final featured English singer Dua Lipa, who performed alongside Jamaican rapper Sean Paul. The UEFA Champions League Anthem was performed by Slovenian-Croatian cello duo 2Cellos.
Second ans: Dua Lipa performed at the opening ceremony preceding the 2018 UEFA Champions League Final.
Dua Lipa performed at the opening ceremony preceding the 2018 UEFA Champions League Final.
Who performed at the champions league final 2018?
['Who are the teams that performed in competition at the champions league final 2018?', 'Who performed best at the champions league final 2018, winning man of the match?', 'Who performed at the opening ceremony of the champions league final 2018?', 'Who performed the anthem at the champions league final 2018?']
[['Real Madrid and Liverpool', 'Liverpool', 'Real Madrid'], ['Gareth Bale', 'Bale'], ['Dua Lipa', 'Sean Paul', 'Dua Lipa and Sean Paul'], ['2Cellos', 'Luka Šulić and Stjepan Hauser', 'Luka Šulić', '2CΞLLOS', 'Stjepan Hauser']]

 30%|███       | 6/20 [00:46<01:44,  7.47s/it]

follow question : Who are the teams that performed in competition at the champions league final 2018?
short answer : ['Real Madrid and Liverpool', 'Liverpool', 'Real Madrid']
{'score': 0.008891591802239418, 'start': 0, 'end': 8, 'answer': 'Dua Lipa'}
follow question : Who performed best at the champions league final 2018, winning man of the match?
short answer : ['Gareth Bale', 'Bale']
{'score': 0.9125087261199951, 'start': 0, 'end': 8, 'answer': 'Dua Lipa'}
follow question : Who performed at the opening ceremony of the champions league final 2018?
short answer : ['Dua Lipa', 'Sean Paul', 'Dua Lipa and Sean Paul']
{'score': 0.9244086146354675, 'start': 0, 'end': 8, 'answer': 'Dua Lipa'}
follow question : Who performed the anthem at the champions league final 2018?
short answer : ['2Cellos', 'Luka Šulić and Stjepan Hauser', 'Luka Šulić', '2CΞLLOS', 'Stjepan Hauser']
{'score': 0.9314979910850525, 'start': 0, 'end': 8, 'answer': 'Dua Lipa'}
{'rougeLsum': 32.87671232876713, 'length': 14.0, 'str_em': 25.0, 'Disambig-F1': 25.0}
First ans: The man who was killed in the movie Thelma and Louise was Harlan, a stranger who attempted to rape Thelma at a roadhouse bar. He was shot and killed by Louise in self-defense.
Second ans: Louise killed Harlan, the man who attempted to rape Thelma, by shooting him in the chest.
Louise killed Harlan, the man who attempted to rape Thelma, by shooting him in the chest.
Who killed the man in thelma and louise?
['Which character killed the man in thelma and louise?', 'Which actor killed the man in thelma and louise?', 'Who is the character that kills Harlan in the film Thelma and Louise?', 'Who is the actor of the character that killed a man in the film Thelma and Louise?']
[['Louise Elizabeth Sawyer', 'Louise'], ['Susan Sarandon', 'Susan Abigail Sarandon'], ['Louise Elizabeth Sawyer', 'Louise'], ['Susan Sarandon']]

 35%|███▌      | 7/20 [00:53<01:36,  7.43s/it]

follow question : Which character killed the man in thelma and louise?
short answer : ['Louise Elizabeth Sawyer', 'Louise']
{'score': 0.004115897696465254, 'start': 0, 'end': 6, 'answer': 'Louise'}
follow question : Which actor killed the man in thelma and louise?
short answer : ['Susan Sarandon', 'Susan Abigail Sarandon']
{'score': 0.0002129778586095199, 'start': 0, 'end': 20, 'answer': 'Louise killed Harlan'}
follow question : Who is the character that kills Harlan in the film Thelma and Louise?
short answer : ['Louise Elizabeth Sawyer', 'Louise']
{'score': 0.12847399711608887, 'start': 0, 'end': 6, 'answer': 'Louise'}
follow question : Who is the actor of the character that killed a man in the film Thelma and Louise?
short answer : ['Susan Sarandon']
{'score': 0.018107296898961067, 'start': 0, 'end': 6, 'answer': 'Louise'}
{'rougeLsum': 35.294117647058826, 'length': 16.0, 'str_em': 50.0, 'Disambig-F1': 50.0}
First ans: Charlie Kelly is played by Charlie Day.
Second ans: Charlie Kelly is played by Charlie Day.
Charlie Kelly is played by Charlie Day.
Who plays charlie on it's always sunny?
["Who does Charlie Day play on It's Always Sunny in Philadelphia?", "Who plays Charlie Kelly on It's Always Sunny in Philadelphia?"]
[['Charlie Kelly'], ['Charlie Day']]

 40%|████      | 8/20 [00:57<01:16,  6.41s/it]

follow question : Who does Charlie Day play on It's Always Sunny in Philadelphia?
short answer : ['Charlie Kelly']
{'score': 0.9911195039749146, 'start': 0, 'end': 13, 'answer': 'Charlie Kelly'}
follow question : Who plays Charlie Kelly on It's Always Sunny in Philadelphia?
short answer : ['Charlie Day']
{'score': 0.9776415824890137, 'start': 27, 'end': 38, 'answer': 'Charlie Day'}
{'rougeLsum': 37.03703703703704, 'length': 7.0, 'str_em': 100.0, 'Disambig-F1': 100.0}
First ans: The Los Angeles Lakers have won the NBA Finals 16 times.
Second ans: The Los Angeles Lakers have won the NBA Finals 16 times.
The Los Angeles Lakers have won the NBA Finals 16 times.
How many times have the lakers won the finals?
['As of 2017, how many times have the lakers won the finals?', 'As of 2016, how many times have the Lakers won the finals?', 'As of 2015, how many times have the Lakers won the finals?']
[['16'], ['16'], ['16']]

 45%|████▌     | 9/20 [01:03<01:07,  6.11s/it]

follow question : As of 2017, how many times have the lakers won the finals?
short answer : ['16']
{'score': 0.8386049270629883, 'start': 47, 'end': 49, 'answer': '16'}
follow question : As of 2016, how many times have the Lakers won the finals?
short answer : ['16']
{'score': 0.8818942904472351, 'start': 47, 'end': 49, 'answer': '16'}
follow question : As of 2015, how many times have the Lakers won the finals?
short answer : ['16']
{'score': 0.7783189415931702, 'start': 47, 'end': 49, 'answer': '16'}
{'rougeLsum': 25.454545454545457, 'length': 11.0, 'str_em': 100.0, 'Disambig-F1': 100.0}
First ans: Based on the provided context information, the following states are under the Indian National Congress:1. Punjab2. Chhattisgarh3. Rajasthan4. Madhya Pradesh5. Maharashtra (as part of the Maha Vikas Aghadi)6. Puducherry (in an alliance with DMK)Additionally, the union territories of Chandigarh and Delhi are also under the Congress.The total number of states and union territories under the Congress is 7.
Second ans: Based on the provided context information, the Indian National Congress is in power in the following states:1. Punjab2. Chhattisgarh3. Rajasthan4. Madhya Pradesh5. Maharashtra (as part of the Maha Vikas Aghadi)6. Puducherry (in an alliance with DMK)Additionally, the Congress-led United Progressive Alliance (UPA) is in power in the following states:1. Andhra Pradesh2. Arunachal Pradesh3. Assam4. Bihar5. Goa6. Gujarat7. Haryana8. Himachal Pradesh9. Jharkhand10. Karnataka11. Kerala12. Odisha13. Tamil Nadu14. Telangana15. Tripura16. Uttar Pradesh17. Uttarakhand18. West BengalTherefore, the total number of states in India where the Indian National Congress is in power, either directly or as part of the UPA, is 7 (directly) + 18 (as part of UPA) = 25.
Based on the provided context information, the Indian National Congress is in power in the following states:1. Punjab2. Chhattisgarh3. Rajasthan4. Madhya Pradesh5. Maharashtra (as part of the Maha Vikas Aghadi)6. Puducherry (in an alliance with DMK)Additionally, the Congress-led United Progressive Alliance (UPA) is in power in the following states:1. Andhra Pradesh2. Arunachal Pradesh3. Assam4. Bihar5. Goa6. Gujarat7. Haryana8. Himachal Pradesh9. Jharkhand10. Karnataka11. Kerala12. Odisha13. Tamil Nadu14. Telangana15. Tripura16. Uttar Pradesh17. Uttarakhand18. West BengalTherefore, the total number of states in India where the Indian National Congress is in power, either directly or as part of the UPA, is 7 (directly) + 18 (as part of UPA) = 25.
How many states in india are under congress?
['How many states plus territories in india are under congress?', 'How many states alone in india are under congress?']
[['7'], ['5']]

 50%|█████     | 10/20 [01:23<01:46, 10.63s/it]

follow question : How many states plus territories in india are under congress?
short answer : ['7']
{'score': 0.47177666425704956, 'start': 752, 'end': 754, 'answer': '25'}
follow question : How many states alone in india are under congress?
short answer : ['5']
{'score': 0.1924983263015747, 'start': 752, 'end': 754, 'answer': '25'}
{'rougeLsum': 19.883040935672515, 'length': 107.0, 'str_em': 100.0, 'Disambig-F1': 0.0}
First ans: Fruma-Sarah is the late wife of Lazar Wolf, a wealthy butcher in the village of Anatevka. She rises from the grave in Tevye's dream, warning of severe retribution if Tzeitel marries Lazar.
Second ans: Fruma-Sarah is the late wife of Lazar Wolf, a wealthy butcher in the village of Anatevka. She rises from the grave in Tevye's "nightmare" to warn of severe retribution if Tzeitel marries Lazar.
Fruma-Sarah is the late wife of Lazar Wolf, a wealthy butcher in the village of Anatevka. She rises from the grave in Tevye's "nightmare" to warn of severe retribution if Tzeitel marries Lazar.
Who is fruma sarah in fiddler on the roof?
['Who played fruma sarah in the 1971 film, Fiddler on the Roof?', 'Who played Fruma Sarah in the original 1964 Broadway cast of Fiddler on the Roof?', 'Who is the character of Fruma Sarah in Fiddler on the Roof?', 'Who played Fruma Sarah in the 2015-2016 Broadway Revival of Fiddler on the Roof?']
[['Ruth Madoc'], ['Carol Sawyer Yussel'], ['a ghostly depiction of the late wife of Lazar Wolf'], ['Jessica Vosk']]

 55%|█████▌    | 11/20 [01:32<01:30, 10.08s/it]

follow question : Who played fruma sarah in the 1971 film, Fiddler on the Roof?
short answer : ['Ruth Madoc']
{'score': 0.002632009331136942, 'start': 118, 'end': 123, 'answer': 'Tevye'}
follow question : Who played Fruma Sarah in the original 1964 Broadway cast of Fiddler on the Roof?
short answer : ['Carol Sawyer Yussel']
{'score': 0.02573438547551632, 'start': 118, 'end': 123, 'answer': 'Tevye'}
follow question : Who is the character of Fruma Sarah in Fiddler on the Roof?
short answer : ['a ghostly depiction of the late wife of Lazar Wolf']
{'score': 0.6071492433547974, 'start': 32, 'end': 42, 'answer': 'Lazar Wolf'}
follow question : Who played Fruma Sarah in the 2015-2016 Broadway Revival of Fiddler on the Roof?
short answer : ['Jessica Vosk']
{'score': 0.005738516338169575, 'start': 118, 'end': 123, 'answer': 'Tevye'}
{'rougeLsum': 23.35766423357664, 'length': 33.0, 'str_em': 0.0, 'Disambig-F1': 10.0}
First ans: July 9, 1991, the Toronto Blue Jays hosted the MLB All-Star Game at the SkyDome.
Second ans: The Toronto Blue Jays hosted the MLB All-Star Game on July 9, 1991.
The Toronto Blue Jays hosted the MLB All-Star Game on July 9, 1991.
When did toronto host the mlb all-star game?
['What date did toronto host the mlb all-star game?', 'Which all-star game did toronto host?']
[['July 9, 1991'], ['1991 Major League Baseball All-Star Game', 'the 62nd playing of the midsummer classic']]

 60%|██████    | 12/20 [01:40<01:13,  9.22s/it]

follow question : What date did toronto host the mlb all-star game?
short answer : ['July 9, 1991']
{'score': 0.8688445091247559, 'start': 54, 'end': 66, 'answer': 'July 9, 1991'}
follow question : Which all-star game did toronto host?
short answer : ['1991 Major League Baseball All-Star Game', 'the 62nd playing of the midsummer classic']
{'score': 0.3965654671192169, 'start': 33, 'end': 50, 'answer': 'MLB All-Star Game'}
{'rougeLsum': 54.05405405405405, 'length': 13.0, 'str_em': 50.0, 'Disambig-F1': 72.22222222222221}
First ans: A metallic blue 1953 Sunbeam Alpine Mk I is driven by Grace Kelly in the film "To Catch a Thief" (1955) starring Cary Grant.
Second ans: A metallic blue 1953 Sunbeam Alpine Mk I is driven by Grace Kelly in the movie "To Catch a Thief".
A metallic blue 1953 Sunbeam Alpine Mk I is driven by Grace Kelly in the movie "To Catch a Thief".
What kind of car in to catch a thief?
['What kind of car in to catch a thief in terms of model?', 'What kind of car in to catch a thief in terms of automobile make?']
[['Sunbeam Alpine', '1953 Sunbeam Alpine Mk I'], ['Rootes Group']]

 65%|██████▌   | 13/20 [01:46<00:59,  8.47s/it]

follow question : What kind of car in to catch a thief in terms of model?
short answer : ['Sunbeam Alpine', '1953 Sunbeam Alpine Mk I']
{'score': 0.29012349247932434, 'start': 21, 'end': 40, 'answer': 'Sunbeam Alpine Mk I'}
follow question : What kind of car in to catch a thief in terms of automobile make?
short answer : ['Rootes Group']
{'score': 0.4094903767108917, 'start': 21, 'end': 40, 'answer': 'Sunbeam Alpine Mk I'}
{'rougeLsum': 35.08771929824562, 'length': 20.0, 'str_em': 50.0, 'Disambig-F1': 44.44444444444445}
First ans: The last season of Jersey Shore, which was Season 6, aired from January 5, 2012, to December 20, 2012.
Second ans: The last season of Jersey Shore aired from October 4, 2012, to December 20, 2012.
The last season of Jersey Shore aired from October 4, 2012, to December 20, 2012.
When did the last season of jersey shore air?
['When did season 4 of jersey shore first air?', 'When did season 4 of jersey shore last air?', 'When did season 5 of jersey shore first air?', 'When did season 5 of jersey shore last air?', 'When did season 6 of jersey shore first air?', 'When did season 6 of jersey shore last air?']
[['August 4, 2011'], ['October 20, 2011'], ['January 5, 2012'], ['March 15, 2012'], ['October 4, 2012'], ['December 20, 2012']]

 70%|███████   | 14/20 [01:53<00:48,  8.07s/it]

follow question : When did season 4 of jersey shore first air?
short answer : ['August 4, 2011']
{'score': 0.07297001779079437, 'start': 43, 'end': 58, 'answer': 'October 4, 2012'}
follow question : When did season 4 of jersey shore last air?
short answer : ['October 20, 2011']
{'score': 0.5013733506202698, 'start': 43, 'end': 58, 'answer': 'October 4, 2012'}
follow question : When did season 5 of jersey shore first air?
short answer : ['January 5, 2012']
{'score': 0.028503216803073883, 'start': 43, 'end': 58, 'answer': 'October 4, 2012'}
follow question : When did season 5 of jersey shore last air?
short answer : ['March 15, 2012']
{'score': 0.3522070348262787, 'start': 43, 'end': 58, 'answer': 'October 4, 2012'}
follow question : When did season 6 of jersey shore first air?
short answer : ['October 4, 2012']
{'score': 0.03184444457292557, 'start': 43, 'end': 58, 'answer': 'October 4, 2012'}
follow question : When did season 6 of jersey shore last air?
short answer : ['December 20, 2012']
{'score': 0.3431626856327057, 'start': 43, 'end': 58, 'answer': 'October 4, 2012'}
{'rougeLsum': 38.888888888888886, 'length': 15.0, 'str_em': 33.33333333333333, 'Disambig-F1': 44.44444444444444}
First ans: Season 8.
Second ans: Based on the provided context information, I do not see any information about a plane crash in Grey's Anatomy Season 8. However, I can provide information about a plane crash in Grey's Anatomy.The plane crash occurred in Season 2, Episode 9, "Into You Like a Train" (air date: January 25, 2007).
Based on the provided context information, I do not see any information about a plane crash in Grey's Anatomy Season 8. However, I can provide information about a plane crash in Grey's Anatomy.The plane crash occurred in Season 2, Episode 9, "Into You Like a Train" (air date: January 25, 2007).
What season of greys anatomy was the plane crash?
["What season of Grey's Anatomy was the plane crash involving six doctors?", "What season of Grey's Anatomy was the plane crash in Seattle that brought memories of a previous plane crash?", "What season of Grey's Anatomy was the plane crash that claimed the life of Lexie Grey?", "What season of Grey's Anatomy was the plane crash in downtown Seattle?"]
[['season 8'], ['season 11'], ['8'], ['11']]

 75%|███████▌  | 15/20 [02:01<00:39,  8.00s/it]

follow question : What season of Grey's Anatomy was the plane crash involving six doctors?
short answer : ['season 8']
{'score': 0.11173555254936218, 'start': 110, 'end': 118, 'answer': 'Season 8'}
follow question : What season of Grey's Anatomy was the plane crash in Seattle that brought memories of a previous plane crash?
short answer : ['season 11']
{'score': 0.3027290999889374, 'start': 221, 'end': 229, 'answer': 'Season 2'}
follow question : What season of Grey's Anatomy was the plane crash that claimed the life of Lexie Grey?
short answer : ['8']
{'score': 0.6155017614364624, 'start': 221, 'end': 229, 'answer': 'Season 2'}
follow question : What season of Grey's Anatomy was the plane crash in downtown Seattle?
short answer : ['11']
{'score': 0.3547928035259247, 'start': 221, 'end': 229, 'answer': 'Season 2'}
{'rougeLsum': 32.32323232323232, 'length': 51.0, 'str_em': 50.0, 'Disambig-F1': 37.5}
First ans: According to the given information, the Oriental Bank of Commerce has 2390 branches across India.
Second ans: According to the provided context, the Oriental Bank of Commerce has 2390 branches across India.
According to the provided context, the Oriental Bank of Commerce has 2390 branches across India.
Number of branches of oriental bank of commerce in india?
['As per the March 2018-2019 report, what is the number of branches of oriental bank of commerce in india?', 'What is the number of branches of oriental bank of commerce in india after amalgamation of Global Trust Bank?', 'Number of branches of oriental bank of commerce in india after expected merger with United Bank of India in 2020?']
[['2390'], ['1092'], ['11,437']]

 80%|████████  | 16/20 [02:07<00:29,  7.39s/it]

follow question : As per the March 2018-2019 report, what is the number of branches of oriental bank of commerce in india?
short answer : ['2390']
{'score': 0.8917698264122009, 'start': 69, 'end': 73, 'answer': '2390'}
follow question : What is the number of branches of oriental bank of commerce in india after amalgamation of Global Trust Bank?
short answer : ['1092']
{'score': 0.8534523844718933, 'start': 69, 'end': 73, 'answer': '2390'}
follow question : Number of branches of oriental bank of commerce in india after expected merger with United Bank of India in 2020?
short answer : ['11,437']
{'score': 0.7966567277908325, 'start': 69, 'end': 73, 'answer': '2390'}
{'rougeLsum': 23.684210526315788, 'length': 15.0, 'str_em': 33.33333333333333, 'Disambig-F1': 33.33333333333333}
First ans: The Rams relocated to St. Louis in 1995.
Second ans: The Rams relocated to St. Louis in 1995, after the 1994 NFL season.
The Rams relocated to St. Louis in 1995, after the 1994 NFL season.
When did the rams go to st louis?
['In what year did the rams go to St. Louis?', 'What was the first game the Rams played in St. Louis?']
[['1995'], ['September 10, 1995']]

 85%|████████▌ | 17/20 [02:12<00:19,  6.62s/it]

follow question : In what year did the rams go to St. Louis?
short answer : ['1995']
{'score': 0.6700248122215271, 'start': 35, 'end': 39, 'answer': '1995'}
follow question : What was the first game the Rams played in St. Louis?
short answer : ['September 10, 1995']
{'score': 0.33787354826927185, 'start': 35, 'end': 39, 'answer': '1995'}
{'rougeLsum': 20.253164556962027, 'length': 13.0, 'str_em': 50.0, 'Disambig-F1': 75.0}
First ans: The Voortrekkers arrived in South Africa in the early 19th century, specifically between 1835 and 1840. They were a group of Dutch-speaking settlers who migrated from the Cape Colony into the interior of modern South Africa, seeking to live beyond the Cape's British colonial administration.However, the first wave of Voortrekkers, led by Louis Tregardt and Hans van Rensburg, left the Cape Colony in September 1835. They crossed the Vaal river at Robert's Drift in January 1836, but the two parties split up in April 1836, after differences between Tregardt and van Rensburg.Other notable leaders of the Voortrekkers, such as Hendrik Potgieter, Gerrit Maritz, Piet Retief, and Piet Uys, also led their own parties, with the first wave of Voortrekkers lasting from 1835 to 1840.So, while the Voortrekkers did not arrive in South Africa as a single, unified group, the first wave of Voortrekkers began to arrive in the region in September 1835, with the majority of the party crossing the Vaal river in January 1836.
Second ans: The Voortrekkers arrived in South Africa in 1835, with the first two parties led by Louis Tregardt and Hans van Rensburg crossing the Vaal river at Robert's Drift in January 1836.
The Voortrekkers arrived in South Africa in 1835, with the first two parties led by Louis Tregardt and Hans van Rensburg crossing the Vaal river at Robert's Drift in January 1836.
When did the voortrekkers arrive in south africa?
['When did the first wave of voortrekkers arrive in south africa?', 'When did the voortrekkers exploratory treks arrive in south africa?']
[['1836', '1836 onwards'], ['February 1835']]

 90%|█████████ | 18/20 [02:31<00:20, 10.31s/it]

follow question : When did the first wave of voortrekkers arrive in south africa?
short answer : ['1836', '1836 onwards']
{'score': 0.5285306572914124, 'start': 44, 'end': 48, 'answer': '1835'}
follow question : When did the voortrekkers exploratory treks arrive in south africa?
short answer : ['February 1835']
{'score': 0.8811651468276978, 'start': 44, 'end': 48, 'answer': '1835'}
{'rougeLsum': 43.63636363636363, 'length': 31.0, 'str_em': 50.0, 'Disambig-F1': 33.33333333333333}
First ans: Heath Ledger plays Patrick Verona in the 1999 film adaptation of 10 Things I Hate About You.
Second ans: Heath Ledger plays Patrick Verona in the 1999 film '10 Things I Hate About You', and Ethan Peck plays Patrick Verona in the 2009-2010 TV series '10 Things I Hate About You'.
Heath Ledger plays Patrick Verona in the 1999 film '10 Things I Hate About You', and Ethan Peck plays Patrick Verona in the 2009-2010 TV series '10 Things I Hate About You'.
Who plays patrick in 10 things i hate about you?
['Who plays patrick in  the 1999 film 10 things i hate about you?', 'Who plays patrick in the 2009 tv series 10 things i hate about you?', 'Who plays patrick in the film 10 things i hate about you?', 'Who plays patrick in the TV series 10 things i hate about you?']
[['Heath Andrew Ledger', 'Heath Ledger', 'Ledger'], ['Ethan Peck', 'Peck', 'Ethan Gregory Peck'], ['Heath Andrew Ledger', 'Heath Ledger'], ['Ethan Peck', 'Ethan Gregory Peck']]

 95%|█████████▌| 19/20 [02:38<00:09,  9.34s/it]

follow question : Who plays patrick in  the 1999 film 10 things i hate about you?
short answer : ['Heath Andrew Ledger', 'Heath Ledger', 'Ledger']
{'score': 0.9754783511161804, 'start': 0, 'end': 12, 'answer': 'Heath Ledger'}
follow question : Who plays patrick in the 2009 tv series 10 things i hate about you?
short answer : ['Ethan Peck', 'Peck', 'Ethan Gregory Peck']
{'score': 0.8937796354293823, 'start': 85, 'end': 95, 'answer': 'Ethan Peck'}
follow question : Who plays patrick in the film 10 things i hate about you?
short answer : ['Heath Andrew Ledger', 'Heath Ledger']
{'score': 0.9013998508453369, 'start': 0, 'end': 12, 'answer': 'Heath Ledger'}
follow question : Who plays patrick in the TV series 10 things i hate about you?
short answer : ['Ethan Peck', 'Ethan Gregory Peck']
{'score': 0.9357442259788513, 'start': 85, 'end': 95, 'answer': 'Ethan Peck'}
{'rougeLsum': 48.78048780487806, 'length': 32.0, 'str_em': 100.0, 'Disambig-F1': 100.0}
First ans: Yes, Microsoft Live Movie Maker is an example of free software. It is a part of the Windows Essentials suite and is available for free download from the Microsoft website.
Second ans: Yes, Microsoft Live Movie Maker is an example of free software. According to the document, it is licensed as Freeware.
Yes, Microsoft Live Movie Maker is an example of free software. According to the document, it is licensed as Freeware.
Microsoft live movie maker is an example of free?
['Microsoft live movie maker is an example of a freely licensed software, often called free what?', 'Microsoft live movie maker is an example of free software used for what purpose?']
[['freeware'], ['Video editing software']]

100%|██████████| 20/20 [02:44<00:00,  8.23s/it]

follow question : Microsoft live movie maker is an example of a freely licensed software, often called free what?
short answer : ['freeware']
{'score': 0.9443901181221008, 'start': 109, 'end': 117, 'answer': 'Freeware'}
follow question : Microsoft live movie maker is an example of free software used for what purpose?
short answer : ['Video editing software']
{'score': 0.28220003843307495, 'start': 109, 'end': 117, 'answer': 'Freeware'}
{'rougeLsum': 50.90909090909091, 'length': 20.0, 'str_em': 50.0, 'Disambig-F1': 50.0}

rougeLsum      34.010879
length         24.550000
str_em         52.916667
Disambig-F1    49.041667
dtype: float64